/**
 * The curriculum model: the single source of truth for what a learner may meet
 * at each point in the book. Lessons, the validator, the learner model and the
 * authoring agents all read from here.
 *
 * Every lesson has exactly ten TARGET words — drilled hard in their own lesson
 * and recycled in every later lesson — plus a few STRUCTURE words that its
 * grammar needs (pronouns, prepositions, negation). Verbs and adjectives list
 * every form the learner may see; a form can unlock later than its word
 * (`laterForms`), e.g. “is” in lesson 1 but “ben / bent / zijn” in lesson 2.
 */

export const lessonPlan = [
  {
    id: 'wat-is-dit',
    title: 'Wat is dit?',
    subtitle: 'A house, a tree, two people — and the two words for “the”.',
    image: 'neighbourhood',
    targets: ['huis', 'boom', 'bank', 'man', 'vrouw', 'kind', 'deur', 'raam', 'auto', 'straat'],
    structure: ['dit', 'zijn', 'een', 'de', 'het', 'wat', 'ja', 'nee', 'geen', 'en'],
    grammar: ['dit-is', 'de-het', 'yes-no-question', 'geen'],
  },
  {
    id: 'ik-ben',
    title: 'Ik ben moe',
    subtitle: 'Bram and Lotte arrive. Every person, one verb: zijn.',
    image: 'man-tired',
    targets: ['groot', 'klein', 'oud', 'jong', 'moe', 'blij', 'ziek', 'mooi', 'nieuw', 'lief'],
    structure: ['ik', 'jij', 'hij', 'zij', 'wij', 'jullie', 'niet', 'ook'],
    grammar: ['subject-pronouns', 'zijn', 'inversion', 'niet', 'hij-het-things'],
  },
  {
    id: 'ik-woon',
    title: 'Waar woon jij?',
    subtitle: 'Ten everyday verbs and the rule behind every present tense.',
    image: 'people-home',
    targets: ['wonen', 'werken', 'lopen', 'zitten', 'slapen', 'koken', 'spelen', 'leren', 'praten', 'wachten'],
    structure: ['in', 'op', 'hier', 'waar', 'thuis'],
    grammar: ['present-regular', 'spelling-stem', 'question-word'],
  },
  {
    id: 'ik-heb',
    title: 'Ik heb een hond',
    subtitle: 'Hebben, geen versus niet, and why a big dog is “een grote hond”.',
    image: 'man-dog',
    targets: ['hebben', 'hond', 'kat', 'boek', 'fiets', 'tas', 'sleutel', 'telefoon', 'jas', 'bed'],
    structure: ['mijn', 'maar', 'of'],
    grammar: ['hebben', 'geen-niet', 'adjective-e'],
  },
  {
    id: 'ik-lees',
    title: 'Wat eet je graag?',
    subtitle: 'Reading, eating, drinking — and where “graag”, “altijd” and “nooit” go.',
    image: 'woman-reading',
    targets: ['lezen', 'eten', 'drinken', 'schrijven', 'koffie', 'thee', 'water', 'brood', 'kaas', 'appel'],
    structure: ['graag', 'altijd', 'nooit'],
    grammar: ['spelling-z-s', 'adverb-position'],
  },
  {
    id: 'vandaag',
    title: 'Vandaag ga ik naar het park',
    subtitle: 'Going places, and the verb that always stays second.',
    image: 'park',
    targets: ['gaan', 'komen', 'vandaag', 'morgen', 'park', 'winkel', 'school', 'station', 'stad', 'trein'],
    structure: ['naar', 'nu', 'dan', 'met'],
    grammar: ['gaan', 'v2-inversion', 'time-place'],
  },
  {
    id: 'twee-katten', volume: 1,
    title: 'Twee katten, vier stoelen',
    subtitle: 'Counting, plurals, and “er is / er zijn” — a tour of the house.',
    image: 'living-room',
    targets: ['twee', 'drie', 'vier', 'vijf', 'kamer', 'tafel', 'stoel', 'keuken', 'tuin', 'veel'],
    structure: ['er', 'hoeveel', 'één'],
    grammar: ['plural', 'er-is-zijn', 'numbers'],
  },
  {
    id: 'mijn-familie', volume: 1,
    title: 'Hoe heet jouw broer?',
    subtitle: 'Family, names, and a possessive for every person.',
    image: 'family',
    targets: ['vader', 'moeder', 'broer', 'zus', 'vriend', 'vriendin', 'familie', 'naam', 'heten', 'jaar'],
    structure: ['jouw', 'haar', 'ons', 'hun', 'wie', 'hoe'],
    grammar: ['possessives', 'wie-hoe'],
  },
  {
    id: 'ik-kan', volume: 1,
    title: 'Ik kan een beetje Nederlands',
    subtitle: 'kunnen, willen, moeten, mogen — and the infinitive that waits at the end.',
    image: 'man-swimming',
    targets: ['kunnen', 'willen', 'moeten', 'mogen', 'zwemmen', 'spreken', 'rijden', 'helpen', 'Nederlands', 'goed'],
    structure: ['Engels', 'beetje', 'heel'],
    grammar: ['modals', 'infinitive-end', 'dt-rule'],
  },
  {
    id: 'op-maandag', volume: 1,
    title: 'Op maandag om acht uur',
    subtitle: 'Days, the clock, and a week in Leuven.',
    image: 'calendar',
    targets: ['maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag', 'zondag', 'week', 'dag', 'uur'],
    structure: ['om', 'laat', 'half', 'elke', 'zes', 'zeven', 'acht', 'negen', 'tien', 'elf', 'twaalf'],
    grammar: ['clock-time', 'days-op-om'],
  },
  {
    id: 'gisteren', volume: 1,
    title: 'Gisteren heb ik gekookt',
    subtitle: 'The perfect tense: hebben or zijn, and a participle at the end.',
    image: 'cinema',
    targets: ['gisteren', 'vorige', 'weekend', 'maken', 'kopen', 'zien', 'doen', 'vinden', 'zeggen', 'film'],
    structure: ['al', 'nog'],
    grammar: ['perfect-hebben', 'participle', 'perfect-zijn'],
  },
  {
    id: 'omdat', volume: 1,
    title: 'Ik ga niet, omdat het regent',
    subtitle: 'want and omdat, dat and als — when the verb goes to the end.',
    image: 'rain',
    targets: ['omdat', 'want', 'als', 'denken', 'weten', 'hopen', 'begrijpen', 'vragen', 'regenen', 'examen'],
    structure: ['dat', 'wanneer', 'misschien'],
    grammar: ['want-omdat', 'verb-final', 'dat-clause', 'als-inversion'],
  },
  {
    id: 'ik-sta-op', volume: 2,
    title: 'Ik sta om zeven uur op',
    subtitle: 'Separable verbs: the little word that jumps to the end.',
    image: 'man-waking',
    targets: ['staan', 'opstaan', 'bellen', 'opbellen', 'nemen', 'meenemen', 'aankomen', 'uitgaan', 'vroeg', 'ontbijt'],
    structure: ['mee', 'aan', 'uit'],
    grammar: ['separable', 'separable-together', 'separable-perfect'],
  },
  {
    id: 'groter', volume: 2,
    title: 'Groter, sneller, beter',
    subtitle: 'Comparing things: -er, het -st, meer, liever, even … als.',
    image: 'snail',
    targets: ['duur', 'goedkoop', 'snel', 'langzaam', 'warm', 'koud', 'lang', 'kort', 'makkelijk', 'moeilijk'],
    structure: ['meer', 'meest', 'beter', 'best', 'liever', 'liefst', 'even'],
    grammar: ['comparative', 'superlative', 'dan-als'],
  },
  {
    id: 'toen', volume: 2,
    title: 'Toen ik klein was',
    subtitle: 'The simple past: woonde, werkte, was, ging — and a childhood by the sea.',
    image: 'grandparents',
    targets: ['toen', 'vroeger', 'geleden', 'vakantie', 'zee', 'strand', 'reizen', 'foto', 'oma', 'opa'],
    structure: ['samen'],
    grammar: ['imperfect-weak', 'imperfect-strong', 'toen-past'],
  },
  {
    id: 'ik-voel-me', volume: 2,
    title: 'Ik voel me niet goed',
    subtitle: 'Reflexive verbs, the imperative, and a visit to the doctor.',
    image: 'doctor',
    targets: ['voelen', 'herinneren', 'haasten', 'hoofd', 'buik', 'rug', 'pijn', 'dokter', 'apotheek', 'medicijn'],
    structure: ['me', 'zich'],
    grammar: ['reflexive', 'imperative', 'pijn-hebben'],
  },
  {
    id: 'volgende-zomer', volume: 2,
    title: 'Volgende zomer gaan we naar zee',
    subtitle: 'The future with zullen and gaan, plans, and te + infinitive.',
    image: 'plane',
    targets: ['zullen', 'volgende', 'zomer', 'winter', 'reis', 'vliegen', 'vliegtuig', 'hotel', 'proberen', 'beginnen'],
    structure: ['te', 'over'],
    grammar: ['zullen-future', 'te-infinitive', 'over-geleden'],
  },
  {
    id: 'die-dat', volume: 2,
    title: 'De buurman die altijd leest',
    subtitle: 'Relative clauses with die and dat, kennen versus weten, and university.',
    image: 'university',
    targets: ['buurman', 'buurvrouw', 'collega', 'student', 'universiteit', 'les', 'leraar', 'antwoord', 'kennen', 'ontmoeten'],
    structure: ['die'],
    grammar: ['relative-clause', 'kennen-weten', 'participle-no-ge'],
  },
];

/** kind: target | structure. `forms` are unlocked with the word; `laterForms` by lesson. */
export const words = [
  // 1 — Wat is dit?
  { id: 'huis', dutch: 'huis', article: 'het', english: 'house', kind: 'target', image: 'house', laterForms: { 'twee-katten': ['huizen'] } },
  { id: 'boom', dutch: 'boom', article: 'de', english: 'tree', kind: 'target', image: 'tree', laterForms: { 'twee-katten': ['bomen'] } },
  { id: 'bank', dutch: 'bank', article: 'de', english: 'bench', kind: 'target', image: 'bench', laterForms: { 'twee-katten': ['banken'] } },
  { id: 'man', dutch: 'man', article: 'de', english: 'man', kind: 'target', image: 'man', laterForms: { 'twee-katten': ['mannen'] } },
  { id: 'vrouw', dutch: 'vrouw', article: 'de', english: 'woman', kind: 'target', image: 'woman', laterForms: { 'twee-katten': ['vrouwen'] } },
  { id: 'kind', dutch: 'kind', article: 'het', english: 'child', kind: 'target', image: 'child', laterForms: { 'twee-katten': ['kinderen'] } },
  { id: 'deur', dutch: 'deur', article: 'de', english: 'door', kind: 'target', image: 'door', laterForms: { 'twee-katten': ['deuren'] } },
  { id: 'raam', dutch: 'raam', article: 'het', english: 'window', kind: 'target', image: 'window', laterForms: { 'twee-katten': ['ramen'] } },
  { id: 'auto', dutch: 'auto', article: 'de', english: 'car', kind: 'target', image: 'car' },
  { id: 'straat', dutch: 'straat', article: 'de', english: 'street', kind: 'target', image: 'neighbourhood', laterForms: { 'twee-katten': ['straten'] } },
  { id: 'dit', dutch: 'dit', english: 'this', kind: 'structure' },
  { id: 'zijn', dutch: 'zijn', english: 'to be', kind: 'structure', forms: ['is'], laterForms: { 'ik-ben': ['ben', 'bent', 'zijn'], gisteren: ['geweest'], toen: ['was', 'waren'] } },
  { id: 'een', dutch: 'een', english: 'a / an', kind: 'structure' },
  { id: 'de', dutch: 'de', english: 'the (de-words)', kind: 'structure' },
  { id: 'het', dutch: 'het', english: 'the (het-words) / it', kind: 'structure' },
  { id: 'wat', dutch: 'wat', english: 'what', kind: 'structure' },
  { id: 'ja', dutch: 'ja', english: 'yes', kind: 'structure' },
  { id: 'nee', dutch: 'nee', english: 'no', kind: 'structure' },
  { id: 'geen', dutch: 'geen', english: 'no / not a', kind: 'structure' },
  { id: 'en', dutch: 'en', english: 'and', kind: 'structure' },

  // 2 — Ik ben moe
  { id: 'groot', dutch: 'groot', english: 'big', kind: 'target', image: 'house', laterForms: { 'ik-heb': ['grote'], groter: ['groter', 'grootst', 'grootste'] } },
  { id: 'klein', dutch: 'klein', english: 'small', kind: 'target', image: 'house-small', laterForms: { 'ik-heb': ['kleine'], groter: ['kleiner', 'kleinst', 'kleinste'] } },
  { id: 'oud', dutch: 'oud', english: 'old', kind: 'target', image: 'old-man', laterForms: { 'ik-heb': ['oude'], groter: ['ouder', 'oudst', 'oudste'] } },
  { id: 'jong', dutch: 'jong', english: 'young', kind: 'target', image: 'woman', laterForms: { 'ik-heb': ['jonge'], groter: ['jonger', 'jongst', 'jongste'] } },
  { id: 'moe', dutch: 'moe', english: 'tired', kind: 'target', image: 'man-tired' },
  { id: 'blij', dutch: 'blij', english: 'happy', kind: 'target', image: 'man-happy', laterForms: { groter: ['blijer'] } },
  { id: 'ziek', dutch: 'ziek', english: 'ill', kind: 'target', image: 'woman-sick' },
  { id: 'mooi', dutch: 'mooi', english: 'beautiful', kind: 'target', image: 'park', laterForms: { 'ik-heb': ['mooie'], groter: ['mooier', 'mooist', 'mooiste'] } },
  { id: 'nieuw', dutch: 'nieuw', english: 'new', kind: 'target', image: 'car', laterForms: { 'ik-heb': ['nieuwe'], groter: ['nieuwer', 'nieuwst', 'nieuwste'] } },
  { id: 'lief', dutch: 'lief', english: 'sweet / kind', kind: 'target', image: 'dog-small', laterForms: { 'ik-heb': ['lieve'] } },
  { id: 'ik', dutch: 'ik', english: 'I', kind: 'structure' },
  { id: 'jij', dutch: 'jij', english: 'you (one person)', kind: 'structure', forms: ['je'] },
  { id: 'hij', dutch: 'hij', english: 'he / it (de-words)', kind: 'structure' },
  { id: 'zij', dutch: 'zij', english: 'she / they', kind: 'structure', forms: ['ze'] },
  { id: 'wij', dutch: 'wij', english: 'we', kind: 'structure', forms: ['we'] },
  { id: 'jullie', dutch: 'jullie', english: 'you (several people)', kind: 'structure' },
  { id: 'niet', dutch: 'niet', english: 'not', kind: 'structure' },
  { id: 'ook', dutch: 'ook', english: 'also / too', kind: 'structure' },

  // 3 — Waar woon jij?
  { id: 'wonen', dutch: 'wonen', english: 'to live (somewhere)', kind: 'target', image: 'people-home', forms: ['woon', 'woont'], laterForms: { gisteren: ['gewoond'], toen: ['woonde', 'woonden'] } },
  { id: 'werken', dutch: 'werken', english: 'to work', kind: 'target', image: 'woman-working', forms: ['werk', 'werkt'], laterForms: { gisteren: ['gewerkt'], toen: ['werkte', 'werkten'] } },
  { id: 'lopen', dutch: 'lopen', english: 'to walk', kind: 'target', image: 'man-walking', forms: ['loop', 'loopt'], laterForms: { gisteren: ['gelopen'], toen: ['liep', 'liepen'] } },
  { id: 'zitten', dutch: 'zitten', english: 'to sit', kind: 'target', image: 'woman-sitting', forms: ['zit'], laterForms: { gisteren: ['gezeten'], toen: ['zat', 'zaten'] } },
  { id: 'slapen', dutch: 'slapen', english: 'to sleep', kind: 'target', image: 'man-sleeping', forms: ['slaap', 'slaapt'], laterForms: { gisteren: ['geslapen'], toen: ['sliep', 'sliepen'] } },
  { id: 'koken', dutch: 'koken', english: 'to cook', kind: 'target', image: 'man-cooking', forms: ['kook', 'kookt'], laterForms: { gisteren: ['gekookt'], toen: ['kookte', 'kookten'] } },
  { id: 'spelen', dutch: 'spelen', english: 'to play', kind: 'target', image: 'child-playing', forms: ['speel', 'speelt'], laterForms: { gisteren: ['gespeeld'], toen: ['speelde', 'speelden'] } },
  { id: 'leren', dutch: 'leren', english: 'to learn / to study', kind: 'target', image: 'woman-studying', forms: ['leer', 'leert'], laterForms: { gisteren: ['geleerd'], toen: ['leerde', 'leerden'] } },
  { id: 'praten', dutch: 'praten', english: 'to talk', kind: 'target', image: 'couple-talking', forms: ['praat'], laterForms: { gisteren: ['gepraat'], toen: ['praatte', 'praatten'] } },
  { id: 'wachten', dutch: 'wachten', english: 'to wait', kind: 'target', image: 'man-waiting', forms: ['wacht'], laterForms: { gisteren: ['gewacht'], toen: ['wachtte', 'wachtten'] } },
  { id: 'in', dutch: 'in', english: 'in', kind: 'structure' },
  { id: 'op', dutch: 'op', english: 'on', kind: 'structure' },
  { id: 'hier', dutch: 'hier', english: 'here', kind: 'structure' },
  { id: 'waar', dutch: 'waar', english: 'where', kind: 'structure' },
  { id: 'thuis', dutch: 'thuis', english: 'at home', kind: 'structure' },

  // 4 — Ik heb een hond
  { id: 'hebben', dutch: 'hebben', english: 'to have', kind: 'target', image: 'man-dog', forms: ['heb', 'hebt', 'heeft'], laterForms: { gisteren: ['gehad'], toen: ['had', 'hadden'] } },
  { id: 'hond', dutch: 'hond', article: 'de', english: 'dog', kind: 'target', image: 'dog-big', laterForms: { 'twee-katten': ['honden'] } },
  { id: 'kat', dutch: 'kat', article: 'de', english: 'cat', kind: 'target', image: 'cat', laterForms: { 'twee-katten': ['katten'] } },
  { id: 'boek', dutch: 'boek', article: 'het', english: 'book', kind: 'target', image: 'book', laterForms: { 'twee-katten': ['boeken'] } },
  { id: 'fiets', dutch: 'fiets', article: 'de', english: 'bicycle', kind: 'target', image: 'bike', laterForms: { 'twee-katten': ['fietsen'] } },
  { id: 'tas', dutch: 'tas', article: 'de', english: 'bag', kind: 'target', image: 'bag', laterForms: { 'twee-katten': ['tassen'] } },
  { id: 'sleutel', dutch: 'sleutel', article: 'de', english: 'key', kind: 'target', image: 'key', laterForms: { 'twee-katten': ['sleutels'] } },
  { id: 'telefoon', dutch: 'telefoon', article: 'de', english: 'phone', kind: 'target', image: 'phone', laterForms: { 'twee-katten': ['telefoons'] } },
  { id: 'jas', dutch: 'jas', article: 'de', english: 'coat', kind: 'target', image: 'coat', laterForms: { 'twee-katten': ['jassen'] } },
  { id: 'bed', dutch: 'bed', article: 'het', english: 'bed', kind: 'target', image: 'bed', laterForms: { 'twee-katten': ['bedden'] } },
  { id: 'mijn', dutch: 'mijn', english: 'my', kind: 'structure' },
  { id: 'maar', dutch: 'maar', english: 'but', kind: 'structure' },
  { id: 'of', dutch: 'of', english: 'or', kind: 'structure' },

  // 5 — Wat eet je graag?
  { id: 'lezen', dutch: 'lezen', english: 'to read', kind: 'target', image: 'woman-reading', forms: ['lees', 'leest'], laterForms: { gisteren: ['gelezen'], toen: ['las', 'lazen'] } },
  { id: 'eten', dutch: 'eten', english: 'to eat', kind: 'target', image: 'man-eating', forms: ['eet'], laterForms: { gisteren: ['gegeten'], toen: ['at', 'aten'] } },
  { id: 'drinken', dutch: 'drinken', english: 'to drink', kind: 'target', image: 'woman-drinking', forms: ['drink', 'drinkt'], laterForms: { gisteren: ['gedronken'], toen: ['dronk', 'dronken'] } },
  { id: 'schrijven', dutch: 'schrijven', english: 'to write', kind: 'target', image: 'man-writing', forms: ['schrijf', 'schrijft'], laterForms: { gisteren: ['geschreven'], toen: ['schreef', 'schreven'] } },
  { id: 'thee', dutch: 'thee', article: 'de', english: 'tea', kind: 'target', image: 'tea' },
  { id: 'water', dutch: 'water', article: 'het', english: 'water', kind: 'target', image: 'water' },
  { id: 'kaas', dutch: 'kaas', article: 'de', english: 'cheese', kind: 'target', image: 'cheese' },
  { id: 'appel', dutch: 'appel', article: 'de', english: 'apple', kind: 'target', image: 'apple', laterForms: { 'twee-katten': ['appels'] } },
  { id: 'koffie', dutch: 'koffie', article: 'de', english: 'coffee', kind: 'target', image: 'coffee' },
  { id: 'brood', dutch: 'brood', article: 'het', english: 'bread', kind: 'target', image: 'bread' },
  { id: 'graag', dutch: 'graag', english: 'gladly (like to)', kind: 'structure' },
  { id: 'altijd', dutch: 'altijd', english: 'always', kind: 'structure' },
  { id: 'nooit', dutch: 'nooit', english: 'never', kind: 'structure' },

  // 6 — Vandaag ga ik naar het park
  { id: 'gaan', dutch: 'gaan', english: 'to go', kind: 'target', image: 'man-walking', forms: ['ga', 'gaat'], laterForms: { gisteren: ['gegaan'], toen: ['ging', 'gingen'] } },
  { id: 'komen', dutch: 'komen', english: 'to come', kind: 'target', image: 'train', forms: ['kom', 'komt'], laterForms: { gisteren: ['gekomen'], toen: ['kwam', 'kwamen'] } },
  { id: 'school', dutch: 'school', article: 'de', english: 'school', kind: 'target', image: 'school', laterForms: { 'twee-katten': ['scholen'] } },
  { id: 'station', dutch: 'station', article: 'het', english: 'station', kind: 'target', image: 'station', laterForms: { 'twee-katten': ['stations'] } },
  { id: 'stad', dutch: 'stad', article: 'de', english: 'city / town', kind: 'target', image: 'city', laterForms: { 'twee-katten': ['steden'] } },
  { id: 'trein', dutch: 'trein', article: 'de', english: 'train', kind: 'target', image: 'train', laterForms: { 'twee-katten': ['treinen'] } },
  { id: 'vandaag', dutch: 'vandaag', english: 'today', kind: 'target' },
  { id: 'morgen', dutch: 'morgen', english: 'tomorrow', kind: 'target' },
  { id: 'park', dutch: 'park', article: 'het', english: 'park', kind: 'target', image: 'park', laterForms: { 'twee-katten': ['parken'] } },
  { id: 'winkel', dutch: 'winkel', article: 'de', english: 'shop', kind: 'target', image: 'shop', laterForms: { 'twee-katten': ['winkels'] } },
  { id: 'naar', dutch: 'naar', english: 'to (towards)', kind: 'structure' },
  { id: 'nu', dutch: 'nu', english: 'now', kind: 'structure' },
  { id: 'dan', dutch: 'dan', english: 'then', kind: 'structure' },
  { id: 'met', dutch: 'met', english: 'with / by', kind: 'structure' },

  // 7 — Twee katten, vier stoelen
  { id: 'twee', dutch: 'twee', english: 'two', kind: 'target', image: 'cats-two' },
  { id: 'drie', dutch: 'drie', english: 'three', kind: 'target', image: 'apples-three' },
  { id: 'vier', dutch: 'vier', english: 'four', kind: 'target', image: 'chairs-four' },
  { id: 'vijf', dutch: 'vijf', english: 'five', kind: 'target' },
  { id: 'kamer', dutch: 'kamer', article: 'de', english: 'room', kind: 'target', image: 'living-room', laterForms: { 'twee-katten': ['kamers'] } },
  { id: 'tafel', dutch: 'tafel', article: 'de', english: 'table', kind: 'target', image: 'table', forms: ['tafels'] },
  { id: 'stoel', dutch: 'stoel', article: 'de', english: 'chair', kind: 'target', image: 'chair', forms: ['stoelen'] },
  { id: 'keuken', dutch: 'keuken', article: 'de', english: 'kitchen', kind: 'target', image: 'kitchen', forms: ['keukens'] },
  { id: 'tuin', dutch: 'tuin', article: 'de', english: 'garden', kind: 'target', image: 'garden', forms: ['tuinen'] },
  { id: 'veel', dutch: 'veel', english: 'many / a lot', kind: 'target' },
  { id: 'er', dutch: 'er', english: 'there (er is / er zijn)', kind: 'structure' },
  { id: 'hoeveel', dutch: 'hoeveel', english: 'how many / how much', kind: 'structure' },
  { id: 'één', dutch: 'één', english: 'one', kind: 'structure' },

  // 8 — Hoe heet jouw broer?
  { id: 'vader', dutch: 'vader', article: 'de', english: 'father', kind: 'target', image: 'father', forms: ['vaders'] },
  { id: 'moeder', dutch: 'moeder', article: 'de', english: 'mother', kind: 'target', image: 'mother', forms: ['moeders'] },
  { id: 'broer', dutch: 'broer', article: 'de', english: 'brother', kind: 'target', image: 'brother', forms: ['broers'] },
  { id: 'zus', dutch: 'zus', article: 'de', english: 'sister', kind: 'target', image: 'sister', forms: ['zussen'] },
  { id: 'vriend', dutch: 'vriend', article: 'de', english: 'friend (male) / boyfriend', kind: 'target', image: 'friends', forms: ['vrienden'] },
  { id: 'vriendin', dutch: 'vriendin', article: 'de', english: 'friend (female) / girlfriend', kind: 'target', image: 'friends', forms: ['vriendinnen'] },
  { id: 'familie', dutch: 'familie', article: 'de', english: 'family', kind: 'target', image: 'family' },
  { id: 'naam', dutch: 'naam', article: 'de', english: 'name', kind: 'target', forms: ['namen'] },
  { id: 'heten', dutch: 'heten', english: 'to be called', kind: 'target', forms: ['heet'], laterForms: { toen: ['heette', 'heetten'] } },
  { id: 'jaar', dutch: 'jaar', article: 'het', english: 'year', kind: 'target', forms: ['jaren'] },
  { id: 'jouw', dutch: 'jouw', english: 'your (stressed)', kind: 'structure' },
  { id: 'haar', dutch: 'haar', english: 'her', kind: 'structure' },
  { id: 'ons', dutch: 'ons', english: 'our (het-words)', kind: 'structure', forms: ['onze'] },
  { id: 'hun', dutch: 'hun', english: 'their', kind: 'structure' },
  { id: 'wie', dutch: 'wie', english: 'who', kind: 'structure' },
  { id: 'hoe', dutch: 'hoe', english: 'how', kind: 'structure' },

  // 9 — Ik kan een beetje Nederlands
  { id: 'kunnen', dutch: 'kunnen', english: 'can / to be able to', kind: 'target', forms: ['kan', 'kunt'], laterForms: { toen: ['kon', 'konden'] } },
  { id: 'willen', dutch: 'willen', english: 'to want', kind: 'target', forms: ['wil', 'wilt'], laterForms: { toen: ['wilde', 'wilden'] } },
  { id: 'moeten', dutch: 'moeten', english: 'must / to have to', kind: 'target', forms: ['moet'], laterForms: { toen: ['moest', 'moesten'] } },
  { id: 'mogen', dutch: 'mogen', english: 'may / to be allowed to', kind: 'target', forms: ['mag'], laterForms: { toen: ['mocht', 'mochten'] } },
  { id: 'zwemmen', dutch: 'zwemmen', english: 'to swim', kind: 'target', image: 'man-swimming', forms: ['zwem', 'zwemt'], laterForms: { gisteren: ['gezwommen'], toen: ['zwom', 'zwommen'] } },
  { id: 'spreken', dutch: 'spreken', english: 'to speak', kind: 'target', image: 'couple-talking', forms: ['spreek', 'spreekt'], laterForms: { gisteren: ['gesproken'], toen: ['sprak', 'spraken'] } },
  { id: 'rijden', dutch: 'rijden', english: 'to drive / to ride', kind: 'target', image: 'man-driving', forms: ['rijd', 'rijdt'], laterForms: { gisteren: ['gereden'], toen: ['reed', 'reden'] } },
  { id: 'helpen', dutch: 'helpen', english: 'to help', kind: 'target', image: 'man-helping', forms: ['help', 'helpt'], laterForms: { gisteren: ['geholpen'], toen: ['hielp', 'hielpen'] } },
  { id: 'Nederlands', dutch: 'Nederlands', english: 'Dutch (the language)', kind: 'target' },
  { id: 'goed', dutch: 'goed', english: 'good / well', kind: 'target', forms: ['goede'] },
  { id: 'Engels', dutch: 'Engels', english: 'English (the language)', kind: 'structure' },
  { id: 'beetje', dutch: 'beetje', english: 'a bit (een beetje)', kind: 'structure' },
  { id: 'heel', dutch: 'heel', english: 'very', kind: 'structure' },

  // 10 — Op maandag om acht uur
  { id: 'maandag', dutch: 'maandag', english: 'Monday', kind: 'target', image: 'calendar' },
  { id: 'dinsdag', dutch: 'dinsdag', english: 'Tuesday', kind: 'target', image: 'calendar' },
  { id: 'woensdag', dutch: 'woensdag', english: 'Wednesday', kind: 'target', image: 'calendar' },
  { id: 'donderdag', dutch: 'donderdag', english: 'Thursday', kind: 'target', image: 'calendar' },
  { id: 'vrijdag', dutch: 'vrijdag', english: 'Friday', kind: 'target', image: 'calendar' },
  { id: 'zaterdag', dutch: 'zaterdag', english: 'Saturday', kind: 'target', image: 'calendar' },
  { id: 'zondag', dutch: 'zondag', english: 'Sunday', kind: 'target', image: 'calendar' },
  { id: 'week', dutch: 'week', article: 'de', english: 'week', kind: 'target', image: 'calendar', forms: ['weken'] },
  { id: 'dag', dutch: 'dag', article: 'de', english: 'day', kind: 'target', forms: ['dagen'] },
  { id: 'uur', dutch: 'uur', article: 'het', english: 'hour / o’clock', kind: 'target', image: 'clock' },
  { id: 'om', dutch: 'om', english: 'at (a time)', kind: 'structure' },
  { id: 'laat', dutch: 'laat', english: 'late (hoe laat = what time)', kind: 'structure' },
  { id: 'half', dutch: 'half', english: 'half (half drie = 2:30)', kind: 'structure' },
  { id: 'elke', dutch: 'elke', english: 'every', kind: 'structure', forms: ['elk'] },
  { id: 'zes', dutch: 'zes', english: 'six', kind: 'structure' },
  { id: 'zeven', dutch: 'zeven', english: 'seven', kind: 'structure' },
  { id: 'acht', dutch: 'acht', english: 'eight', kind: 'structure' },
  { id: 'negen', dutch: 'negen', english: 'nine', kind: 'structure' },
  { id: 'tien', dutch: 'tien', english: 'ten', kind: 'structure' },
  { id: 'elf', dutch: 'elf', english: 'eleven', kind: 'structure' },
  { id: 'twaalf', dutch: 'twaalf', english: 'twelve', kind: 'structure' },

  // 11 — Gisteren heb ik gekookt
  { id: 'gisteren', dutch: 'gisteren', english: 'yesterday', kind: 'target' },
  { id: 'vorige', dutch: 'vorige', english: 'last (vorige week)', kind: 'target', forms: ['vorig'] },
  { id: 'weekend', dutch: 'weekend', article: 'het', english: 'weekend', kind: 'target', forms: ['weekends'] },
  { id: 'maken', dutch: 'maken', english: 'to make', kind: 'target', image: 'man-making', forms: ['maak', 'maakt', 'gemaakt'], laterForms: { toen: ['maakte', 'maakten'] } },
  { id: 'kopen', dutch: 'kopen', english: 'to buy', kind: 'target', image: 'woman-buying', forms: ['koop', 'koopt', 'gekocht'], laterForms: { toen: ['kocht', 'kochten'] } },
  { id: 'zien', dutch: 'zien', english: 'to see', kind: 'target', forms: ['zie', 'ziet', 'gezien'], laterForms: { toen: ['zag', 'zagen'] } },
  { id: 'doen', dutch: 'doen', english: 'to do', kind: 'target', forms: ['doe', 'doet', 'gedaan'], laterForms: { toen: ['deed', 'deden'] } },
  { id: 'vinden', dutch: 'vinden', english: 'to find / to think of', kind: 'target', forms: ['vind', 'vindt', 'gevonden'], laterForms: { toen: ['vond', 'vonden'] } },
  { id: 'zeggen', dutch: 'zeggen', english: 'to say', kind: 'target', forms: ['zeg', 'zegt', 'gezegd'], laterForms: { toen: ['zei', 'zeiden'] } },
  { id: 'film', dutch: 'film', article: 'de', english: 'film', kind: 'target', image: 'cinema', forms: ['films'] },
  { id: 'al', dutch: 'al', english: 'already', kind: 'structure' },
  { id: 'nog', dutch: 'nog', english: 'still / yet', kind: 'structure' },

  // 12 — Ik ga niet, omdat het regent
  { id: 'omdat', dutch: 'omdat', english: 'because (verb to the end)', kind: 'target' },
  { id: 'want', dutch: 'want', english: 'because (normal word order)', kind: 'target' },
  { id: 'als', dutch: 'als', english: 'if / when', kind: 'target' },
  { id: 'denken', dutch: 'denken', english: 'to think', kind: 'target', image: 'man-thinking', forms: ['denk', 'denkt', 'gedacht'], laterForms: { toen: ['dacht', 'dachten'] } },
  { id: 'weten', dutch: 'weten', english: 'to know (a fact)', kind: 'target', forms: ['weet', 'geweten'], laterForms: { toen: ['wist', 'wisten'] } },
  { id: 'hopen', dutch: 'hopen', english: 'to hope', kind: 'target', forms: ['hoop', 'hoopt', 'gehoopt'], laterForms: { toen: ['hoopte', 'hoopten'] } },
  { id: 'begrijpen', dutch: 'begrijpen', english: 'to understand', kind: 'target', forms: ['begrijp', 'begrijpt', 'begrepen'], laterForms: { toen: ['begreep'] } },
  { id: 'vragen', dutch: 'vragen', english: 'to ask', kind: 'target', forms: ['vraag', 'vraagt', 'gevraagd'], laterForms: { toen: ['vroegen'] } },
  { id: 'regenen', dutch: 'regenen', english: 'to rain', kind: 'target', image: 'rain', forms: ['regent', 'geregend'], laterForms: { toen: ['regende'] } },
  { id: 'examen', dutch: 'examen', article: 'het', english: 'exam', kind: 'target', image: 'exam', forms: ['examens'] },
  { id: 'dat', dutch: 'dat', english: 'that', kind: 'structure' },
  { id: 'wanneer', dutch: 'wanneer', english: 'when (question)', kind: 'structure' },
  { id: 'misschien', dutch: 'misschien', english: 'maybe', kind: 'structure' },

  // 13 — Ik sta om zeven uur op
  { id: 'staan', dutch: 'staan', english: 'to stand', kind: 'target', forms: ['sta', 'staat', 'gestaan'], laterForms: { toen: ['stond', 'stonden'] } },
  { id: 'opstaan', dutch: 'opstaan', english: 'to get up', kind: 'target', image: 'man-waking', forms: ['opsta', 'opstaat', 'opgestaan'] },
  { id: 'bellen', dutch: 'bellen', english: 'to call (phone)', kind: 'target', image: 'woman-phoning', forms: ['bel', 'belt', 'gebeld'], laterForms: { toen: ['belde', 'belden'] } },
  { id: 'opbellen', dutch: 'opbellen', english: 'to ring up', kind: 'target', image: 'woman-phoning', forms: ['opbel', 'opbelt', 'opgebeld'] },
  { id: 'nemen', dutch: 'nemen', english: 'to take', kind: 'target', forms: ['neem', 'neemt', 'genomen'], laterForms: { toen: ['nam'] } },
  { id: 'meenemen', dutch: 'meenemen', english: 'to take along', kind: 'target', image: 'man-packing', forms: ['meeneem', 'meeneemt', 'meegenomen'] },
  { id: 'aankomen', dutch: 'aankomen', english: 'to arrive', kind: 'target', image: 'train', forms: ['aankom', 'aankomt', 'aangekomen'] },
  { id: 'uitgaan', dutch: 'uitgaan', english: 'to go out', kind: 'target', image: 'night-out', forms: ['uitga', 'uitgaat', 'uitgegaan'] },
  { id: 'vroeg', dutch: 'vroeg', english: 'early', kind: 'target', image: 'man-waking', forms: ['vroege'] },
  { id: 'ontbijt', dutch: 'ontbijt', article: 'het', english: 'breakfast', kind: 'target', image: 'breakfast' },
  { id: 'mee', dutch: 'mee', english: 'along (separable part)', kind: 'structure' },
  { id: 'aan', dutch: 'aan', english: 'on / at (separable part)', kind: 'structure' },
  { id: 'uit', dutch: 'uit', english: 'out (separable part) / from', kind: 'structure' },

  // 14 — Groter, sneller, beter
  { id: 'duur', dutch: 'duur', english: 'expensive', kind: 'target', image: 'price-tags', forms: ['dure', 'duurder', 'duurst', 'duurste'] },
  { id: 'goedkoop', dutch: 'goedkoop', english: 'cheap', kind: 'target', image: 'price-tags', forms: ['goedkope', 'goedkoper', 'goedkoopst', 'goedkoopste'] },
  { id: 'snel', dutch: 'snel', english: 'fast', kind: 'target', image: 'train', forms: ['snelle', 'sneller', 'snelst', 'snelste'] },
  { id: 'langzaam', dutch: 'langzaam', english: 'slow', kind: 'target', image: 'snail', forms: ['langzame', 'langzamer', 'langzaamst', 'langzaamste'] },
  { id: 'warm', dutch: 'warm', english: 'warm / hot', kind: 'target', image: 'sun', forms: ['warme', 'warmer', 'warmst', 'warmste'] },
  { id: 'koud', dutch: 'koud', english: 'cold', kind: 'target', image: 'snow', forms: ['koude', 'kouder', 'koudst', 'koudste'] },
  { id: 'lang', dutch: 'lang', english: 'long / tall', kind: 'target', image: 'tall-short', forms: ['lange', 'langer', 'langst', 'langste'] },
  { id: 'kort', dutch: 'kort', english: 'short', kind: 'target', image: 'tall-short', forms: ['korte', 'korter', 'kortst', 'kortste'] },
  { id: 'makkelijk', dutch: 'makkelijk', english: 'easy', kind: 'target', forms: ['makkelijke', 'makkelijker', 'makkelijkst', 'makkelijkste'] },
  { id: 'moeilijk', dutch: 'moeilijk', english: 'difficult', kind: 'target', forms: ['moeilijke', 'moeilijker', 'moeilijkst', 'moeilijkste'] },
  { id: 'meer', dutch: 'meer', english: 'more', kind: 'structure' },
  { id: 'meest', dutch: 'meest', english: 'most', kind: 'structure', forms: ['meeste'] },
  { id: 'beter', dutch: 'beter', english: 'better', kind: 'structure' },
  { id: 'best', dutch: 'best', english: 'best', kind: 'structure', forms: ['beste'] },
  { id: 'liever', dutch: 'liever', english: 'rather (graag → liever)', kind: 'structure' },
  { id: 'liefst', dutch: 'liefst', english: 'most of all (het liefst)', kind: 'structure' },
  { id: 'even', dutch: 'even', english: 'as (even groot als)', kind: 'structure' },

  // 15 — Toen ik klein was
  { id: 'toen', dutch: 'toen', english: 'then / when (past)', kind: 'target' },
  { id: 'vroeger', dutch: 'vroeger', english: 'in the past / used to', kind: 'target' },
  { id: 'geleden', dutch: 'geleden', english: 'ago', kind: 'target' },
  { id: 'vakantie', dutch: 'vakantie', article: 'de', english: 'holiday', kind: 'target', image: 'sea', forms: ['vakanties'] },
  { id: 'zee', dutch: 'zee', article: 'de', english: 'sea', kind: 'target', image: 'sea' },
  { id: 'strand', dutch: 'strand', article: 'het', english: 'beach', kind: 'target', image: 'child-beach', forms: ['stranden'] },
  { id: 'reizen', dutch: 'reizen', english: 'to travel', kind: 'target', image: 'suitcase', forms: ['reis', 'reist', 'gereisd', 'reisde', 'reisden'] },
  { id: 'foto', dutch: 'foto', article: 'de', english: 'photo', kind: 'target', image: 'photo' },
  { id: 'oma', dutch: 'oma', article: 'de', english: 'grandma', kind: 'target', image: 'grandparents' },
  { id: 'opa', dutch: 'opa', article: 'de', english: 'grandpa', kind: 'target', image: 'grandparents' },
  { id: 'samen', dutch: 'samen', english: 'together', kind: 'structure' },

  // 16 — Ik voel me niet goed
  { id: 'voelen', dutch: 'voelen', english: 'to feel', kind: 'target', image: 'man-headache', forms: ['voel', 'voelt', 'gevoeld', 'voelde', 'voelden'] },
  { id: 'herinneren', dutch: 'herinneren', english: 'to remember (zich herinneren)', kind: 'target', image: 'photo', forms: ['herinner', 'herinnert', 'herinnerd', 'herinnerde'] },
  { id: 'haasten', dutch: 'haasten', english: 'to hurry (zich haasten)', kind: 'target', image: 'man-hurrying', forms: ['haast', 'gehaast', 'haastte'] },
  { id: 'hoofd', dutch: 'hoofd', article: 'het', english: 'head', kind: 'target', image: 'man-headache' },
  { id: 'buik', dutch: 'buik', article: 'de', english: 'belly', kind: 'target', image: 'woman-stomachache' },
  { id: 'rug', dutch: 'rug', article: 'de', english: 'back', kind: 'target', image: 'back-pain' },
  { id: 'pijn', dutch: 'pijn', article: 'de', english: 'pain', kind: 'target', image: 'man-headache', forms: ['hoofdpijn', 'buikpijn', 'rugpijn'] },
  { id: 'dokter', dutch: 'dokter', article: 'de', english: 'doctor', kind: 'target', image: 'doctor', forms: ['dokters'] },
  { id: 'apotheek', dutch: 'apotheek', article: 'de', english: 'pharmacy', kind: 'target', image: 'pharmacy' },
  { id: 'medicijn', dutch: 'medicijn', article: 'het', english: 'medicine', kind: 'target', image: 'medicine', forms: ['medicijnen'] },
  { id: 'me', dutch: 'me', english: 'me / myself', kind: 'structure' },
  { id: 'zich', dutch: 'zich', english: 'himself / herself / themselves', kind: 'structure' },

  // 17 — Volgende zomer gaan we naar zee
  { id: 'zullen', dutch: 'zullen', english: 'will / shall', kind: 'target', forms: ['zal', 'zult'] },
  { id: 'volgende', dutch: 'volgende', english: 'next', kind: 'target', forms: ['volgend'] },
  { id: 'zomer', dutch: 'zomer', article: 'de', english: 'summer', kind: 'target', image: 'sun' },
  { id: 'winter', dutch: 'winter', article: 'de', english: 'winter', kind: 'target', image: 'snow' },
  { id: 'reis', dutch: 'reis', article: 'de', english: 'trip / journey', kind: 'target', image: 'suitcase' },
  { id: 'vliegen', dutch: 'vliegen', english: 'to fly', kind: 'target', image: 'plane', forms: ['vlieg', 'vliegt', 'gevlogen', 'vloog', 'vlogen'] },
  { id: 'vliegtuig', dutch: 'vliegtuig', article: 'het', english: 'plane', kind: 'target', image: 'plane', forms: ['vliegtuigen'] },
  { id: 'hotel', dutch: 'hotel', article: 'het', english: 'hotel', kind: 'target', image: 'hotel', forms: ['hotels'] },
  { id: 'proberen', dutch: 'proberen', english: 'to try', kind: 'target', forms: ['probeer', 'probeert', 'geprobeerd', 'probeerde'] },
  { id: 'beginnen', dutch: 'beginnen', english: 'to begin', kind: 'target', forms: ['begin', 'begint', 'begonnen', 'begon'] },
  { id: 'te', dutch: 'te', english: 'to (te + infinitive) / too', kind: 'structure' },
  { id: 'over', dutch: 'over', english: 'in (over twee weken) / about', kind: 'structure' },

  // 18 — De buurman die altijd leest
  { id: 'buurman', dutch: 'buurman', article: 'de', english: 'neighbour (man)', kind: 'target', image: 'neighbours' },
  { id: 'buurvrouw', dutch: 'buurvrouw', article: 'de', english: 'neighbour (woman)', kind: 'target', image: 'neighbours' },
  { id: 'collega', dutch: 'collega', article: 'de', english: 'colleague', kind: 'target', image: 'colleagues' },
  { id: 'student', dutch: 'student', article: 'de', english: 'student', kind: 'target', image: 'students', forms: ['studenten'] },
  { id: 'universiteit', dutch: 'universiteit', article: 'de', english: 'university', kind: 'target', image: 'university' },
  { id: 'les', dutch: 'les', article: 'de', english: 'lesson / class', kind: 'target', image: 'classroom', forms: ['lessen'] },
  { id: 'leraar', dutch: 'leraar', article: 'de', english: 'teacher', kind: 'target', image: 'classroom', forms: ['leraren'] },
  { id: 'antwoord', dutch: 'antwoord', article: 'het', english: 'answer', kind: 'target', forms: ['antwoorden'] },
  { id: 'kennen', dutch: 'kennen', english: 'to know (a person, a place)', kind: 'target', forms: ['ken', 'kent', 'gekend', 'kende', 'kenden'] },
  { id: 'ontmoeten', dutch: 'ontmoeten', english: 'to meet', kind: 'target', image: 'couple-talking', forms: ['ontmoet', 'ontmoette', 'ontmoetten'] },
  { id: 'die', dutch: 'die', english: 'who / that (relative) / that one', kind: 'structure' },
];

/** Proper names may appear anywhere; they are never tracked as vocabulary. */
export const names = ['Bram', 'Lotte', 'Max', 'Leuven', 'Gent', 'Brussel', 'Antwerpen', 'Sofie', 'Tom', 'Emma', 'Jonas', 'Noor', 'Mimi', 'België', 'Spanje', 'Oostende'];

export const grammarPoints = [
  { id: 'dit-is', title: 'Dit is een …', summary: 'Naming what you see: “Dit is een huis.”' },
  { id: 'de-het', title: 'de and het', summary: 'Every noun is a de-word or a het-word. “Een” works for both.' },
  { id: 'yes-no-question', title: 'Yes/no questions', summary: 'The verb moves to the front: “Is dit een huis?”' },
  { id: 'geen', title: 'geen', summary: '“Geen” replaces “een”: “Dit is geen huis.”' },
  { id: 'subject-pronouns', title: 'Subject pronouns', summary: 'ik, jij/je, hij, zij/ze, het, wij/we, jullie, zij/ze.' },
  { id: 'zijn', title: 'zijn (to be)', summary: 'ik ben, jij bent, hij is, wij/jullie/zij zijn.' },
  { id: 'inversion', title: 'Verb before subject', summary: 'In a question the verb comes first, and “jij bent” becomes “ben jij”.' },
  { id: 'niet', title: 'niet', summary: '“Niet” comes after the verb: “Ik ben niet moe.”' },
  { id: 'hij-het-things', title: 'hij and het for things', summary: 'A de-word is “hij”, a het-word is “het”.' },
  { id: 'present-regular', title: 'The present tense', summary: 'ik + stem, jij/hij + stem + t, wij/jullie/zij + infinitive.' },
  { id: 'spelling-stem', title: 'Spelling the stem', summary: 'wonen → woon, slapen → slaap, zitten → zit, hij zit.' },
  { id: 'question-word', title: 'Question words', summary: '“Waar woon jij?” — question word, verb, subject.' },
  { id: 'hebben', title: 'hebben (to have)', summary: 'ik heb, jij hebt, hij heeft, wij/jullie/zij hebben.' },
  { id: 'geen-niet', title: 'geen or niet?', summary: '“Geen” for een-nouns, “niet” for everything else.' },
  { id: 'adjective-e', title: 'een grote hond', summary: 'An adjective before a noun takes -e, except een + het-word.' },
  { id: 'spelling-z-s', title: 'z → s, v → f', summary: 'z → s and v → f: lezen → ik lees, schrijven → ik schrijf.' },
  { id: 'adverb-position', title: 'graag, altijd, nooit', summary: 'They come straight after the verb: “Ik drink graag koffie.”' },
  { id: 'gaan', title: 'gaan (to go)', summary: 'ik ga, jij gaat, hij gaat, wij/jullie/zij gaan.' },
  { id: 'v2-inversion', title: 'The verb stays second', summary: '“Vandaag ga ik naar het park.”' },
  { id: 'time-place', title: 'Time before place', summary: '“Ik ga morgen naar de winkel.”' },
  { id: 'plural', title: 'Plurals', summary: 'Most nouns add -en (bomen, katten), some -s (tafels); every plural takes de.' },
  { id: 'er-is-zijn', title: 'er is / er zijn', summary: '“Er is een tuin. Er zijn twee stoelen.”' },
  { id: 'numbers', title: 'Counting', summary: 'één, twee, drie … and hoeveel? with a plural noun.' },
  { id: 'possessives', title: 'mijn, jouw, zijn, haar …', summary: 'mijn, jouw/je, zijn, haar, ons/onze, jullie, hun.' },
  { id: 'wie-hoe', title: 'wie and hoe', summary: '“Wie is dat? Hoe heet jij? Hoe oud is hij?”' },
  { id: 'modals', title: 'kunnen, willen, moeten, mogen', summary: 'ik kan, jij kunt, hij kan · ik wil, hij wil · ik moet · ik mag.' },
  { id: 'infinitive-end', title: 'The infinitive goes to the end', summary: '“Ik wil morgen naar het park gaan.”' },
  { id: 'dt-rule', title: 'd + t', summary: 'rijden → ik rijd, hij rijdt, rijd jij?' },
  { id: 'clock-time', title: 'Telling the time', summary: '“Hoe laat is het? Het is drie uur / half vier.”' },
  { id: 'days-op-om', title: 'op maandag, om acht uur', summary: 'op + day, om + clock time, elke dag.' },
  { id: 'perfect-hebben', title: 'The perfect with hebben', summary: '“Ik heb gekookt.” — hebben second, participle at the end.' },
  { id: 'participle', title: 'Making the participle', summary: 'ge- + stem + t/d (’t kofschip), and strong verbs: gelezen, gegeten.' },
  { id: 'perfect-zijn', title: 'The perfect with zijn', summary: '“Ik ben naar Gent gegaan.” — movement and change take zijn.' },
  { id: 'want-omdat', title: 'want or omdat?', summary: 'want keeps normal order; omdat sends the verb to the end.' },
  { id: 'verb-final', title: 'The verb at the end', summary: 'In a clause with omdat, dat, als or wanneer the conjugated verb goes last.' },
  { id: 'dat-clause', title: 'dat', summary: '“Ik denk dat hij thuis is.”' },
  { id: 'als-inversion', title: 'Starting with als', summary: '“Als het regent, ga ik niet” — the clause counts as position one.' },
  { id: 'separable', title: 'Separable verbs', summary: 'opstaan → “Ik sta om zeven uur op.” The particle goes to the end.' },
  { id: 'separable-together', title: 'Back together', summary: 'With a modal or in a subclause: “Ik moet vroeg opstaan”, “omdat ik vroeg opsta”.' },
  { id: 'separable-perfect', title: 'opgestaan, meegenomen', summary: 'ge- goes between the particle and the verb.' },
  { id: 'comparative', title: 'groter dan', summary: 'Add -er (duurder after r); goed → beter, veel → meer, graag → liever.' },
  { id: 'superlative', title: 'het grootst', summary: '-st: de grootste kamer, het best, het liefst.' },
  { id: 'dan-als', title: 'dan and even … als', summary: '“groter dan”, “even groot als”.' },
  { id: 'imperfect-weak', title: 'The simple past: -te / -de', summary: '’t kofschip again: werkte, woonde; plural -ten / -den.' },
  { id: 'imperfect-strong', title: 'The simple past: was, ging, kwam', summary: 'Strong verbs change their vowel: ging, kwam, zag, las, at.' },
  { id: 'toen-past', title: 'toen and vroeger', summary: '“Toen ik klein was, woonde ik aan zee.” — past stories use the simple past.' },
  { id: 'reflexive', title: 'Reflexive verbs', summary: 'ik voel me, jij voelt je, hij voelt zich, wij voelen ons.' },
  { id: 'imperative', title: 'The imperative', summary: 'The stem: “Neem een medicijn! Ga naar de dokter!”' },
  { id: 'pijn-hebben', title: 'Ik heb hoofdpijn', summary: 'pijn hebben, pijn aan …, ziek zijn, zich beter voelen.' },
  { id: 'zullen-future', title: 'zullen', summary: 'ik zal, jij zult, hij zal — promises and predictions; gaan for plans.' },
  { id: 'te-infinitive', title: 'te + infinitive', summary: '“Ik probeer Nederlands te spreken.” “Het begint te regenen.”' },
  { id: 'over-geleden', title: 'over and geleden', summary: '“over twee weken” (future) — “twee weken geleden” (past).' },
  { id: 'relative-clause', title: 'die and dat', summary: '“De man die daar woont” — die for de-words and plurals, dat for het-words; verb at the end.' },
  { id: 'kennen-weten', title: 'kennen or weten?', summary: 'kennen a person or place; weten a fact.' },
  { id: 'participle-no-ge', title: 'No ge-', summary: 'Verbs starting with be-, ge-, her-, ont-, ver- take no ge-: ontmoet, begrepen, herinnerd.' },
];

/** Semantic image keys → accessible descriptions. Every key must exist in public/images. */
export const images = {
  house: 'a large brick house', tree: 'a tall tree', bench: 'a park bench', man: 'Bram, a young man',
  woman: 'Lotte, a young woman', 'man-walking': 'Bram walking', 'woman-sitting': 'Lotte sitting on a bench',
  neighbourhood: 'a house on a quiet street', 'house-small': 'a small cottage', 'tree-small': 'a young, small tree',
  'old-man': 'an old man with a walking stick', 'old-woman': 'an old woman', 'man-tired': 'Bram yawning, tired',
  'woman-tired': 'Lotte yawning, tired', 'woman-walking': 'Lotte walking', 'man-sitting': 'Bram sitting on a bench',
  'man-sleeping': 'Bram asleep in bed', 'woman-sleeping': 'Lotte asleep in bed', 'man-working': 'Bram working at a desk',
  'woman-working': 'Lotte working at a desk', 'people-home': 'Bram and Lotte in front of their house',
  'couple-bench': 'Bram and Lotte sitting on a bench', 'dog-big': 'a big dog', 'dog-small': 'a small dog', cat: 'a cat',
  'cat-sleeping': 'a cat asleep', book: 'a book', bike: 'a bicycle', 'man-dog': 'Bram walking his dog',
  'woman-bike': 'Lotte with her bicycle', coffee: 'a cup of coffee', bread: 'a loaf of bread',
  'woman-reading': 'Lotte reading on a bench', 'man-reading': 'Bram reading in an armchair',
  'man-eating': 'Bram eating bread', 'woman-drinking': 'Lotte drinking from a cup', park: 'a park', shop: 'a small shop',
  child: 'a child', door: 'a front door', window: 'a window', car: 'a car', 'man-happy': 'Bram smiling, happy',
  'woman-sick': 'Lotte ill in bed', 'man-cooking': 'Bram cooking', 'child-playing': 'a child playing with a ball',
  'woman-studying': 'Lotte studying at a table with books', 'couple-talking': 'Bram and Lotte talking',
  'man-waiting': 'Bram waiting, looking at his watch', 'man-writing': 'Bram writing', bag: 'a bag', key: 'a key',
  phone: 'a phone', coat: 'a coat', bed: 'an empty bed', tea: 'a cup of tea', water: 'a glass of water',
  cheese: 'a piece of cheese', apple: 'an apple', train: 'a train', station: 'a railway station', school: 'a school',
  city: 'a city square',
  'living-room': 'a living room with a sofa, table and chairs', kitchen: 'a kitchen', garden: 'a garden behind a house',
  table: 'a wooden table', chair: 'a chair', 'cats-two': 'two cats', 'apples-three': 'three apples', 'chairs-four': 'four chairs around a table',
  family: 'a family of five: grandparents, parents and a child', father: 'Bram’s father', mother: 'Bram’s mother',
  brother: 'Lotte’s brother', sister: 'Bram’s sister', friends: 'two friends laughing together',
  'man-swimming': 'Bram swimming', 'man-driving': 'Bram driving a car', 'man-helping': 'Bram helping the old man',
  cinema: 'a cinema screen with an audience', 'woman-buying': 'Lotte buying something at a shop counter',
  'man-making': 'Bram making a wooden bench', clock: 'a wall clock', calendar: 'a week calendar',
  rain: 'a rainy street with an umbrella', 'man-thinking': 'Bram thinking', exam: 'a student writing an exam',
  'man-waking': 'Bram getting out of bed next to an alarm clock', 'woman-phoning': 'Lotte on the phone',
  'man-packing': 'Bram putting things into his bag', 'night-out': 'Bram and Lotte going out in the evening',
  breakfast: 'a breakfast table', snail: 'a snail', 'price-tags': 'two coats with price tags, one expensive, one cheap',
  sun: 'a hot sunny day', snow: 'a cold snowy street', 'tall-short': 'a tall man next to a short man',
  sea: 'the Belgian coast: sea, beach and dunes', 'child-beach': 'a child building a sandcastle on the beach',
  suitcase: 'a packed suitcase', photo: 'an old family photo', grandparents: 'grandma and grandpa',
  'man-headache': 'Bram with a headache', 'woman-stomachache': 'Lotte with a stomach ache', 'back-pain': 'Bram with back pain',
  'man-hurrying': 'Bram hurrying', doctor: 'a doctor in her practice', pharmacy: 'a pharmacy', medicine: 'a box of medicine',
  plane: 'a plane in the sky', hotel: 'a hotel by the sea', neighbours: 'the old neighbours, a man and a woman',
  colleagues: 'Bram and two colleagues in an office', students: 'students on a university square',
  university: 'the old university building in Leuven', classroom: 'a teacher and students in a classroom',
};

/**
 * Recorded voices (macOS `say`). Dialogue lines are spoken by their character's voice; every other
 * sentence gets a voice chosen from the text itself, so the learner hears both accents throughout.
 * Install another Dutch voice (e.g. Claire) and add it here to widen the mix.
 */
export const voices = {
  ellen: { system: 'Ellen', label: 'Ellen · Belgian Dutch' },
  xander: { system: 'Xander', label: 'Xander · Netherlands Dutch' },
};
export const speakerVoices = {
  Bram: 'xander', Lotte: 'ellen', 'De man': 'xander', 'De oude man': 'xander', Tom: 'xander', Jonas: 'xander',
  Emma: 'ellen', Sofie: 'ellen', Noor: 'ellen', Moeder: 'ellen', Vader: 'xander',
};
