/**
 * Lesson 2 — Ik ben moe.
 * Targets: groot, klein, oud, jong, moe, blij, ziek, mooi, nieuw, lief.
 * Structure: ik, jij/je, hij, zij/ze, wij/we, jullie, niet, ook (+ ben, bent, zijn).
 * Grammar: subject pronouns · zijn · verb-first questions · niet · hij/het for things.
 * Recycles: dit is · de/het · yes/no questions · geen.
 * Adjectives appear only after zijn (no -e) — attributive forms wait for lesson 4.
 * Things referred to as “hij” are kept to masculine nouns (boom, auto), so the
 * sentences are right in Flanders too, where de straat / de deur / de bank are “ze”.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Ten words that describe', grammar: ['de-het'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice.',
    cards: [
      { nl: 'Het huis is groot.', en: 'The house is big.', image: 'house' },
      { nl: 'Het huis is klein.', en: 'The house is small.', image: 'house-small' },
      { nl: 'De man is oud.', en: 'The man is old.', image: 'old-man' },
      { nl: 'Lotte is jong.', en: 'Lotte is young.', image: 'woman' },
      { nl: 'Bram is moe.', en: 'Bram is tired.', image: 'man-tired' },
      { nl: 'Bram is blij.', en: 'Bram is happy.', image: 'man-happy' },
      { nl: 'Lotte is ziek.', en: 'Lotte is ill.', image: 'woman-sick' },
      { nl: 'De straat is mooi.', en: 'The street is beautiful.', image: 'neighbourhood' },
      { nl: 'De auto is nieuw.', en: 'The car is new.', image: 'car' },
      { nl: 'Het kind is lief.', en: 'The child is sweet.', image: 'child' },
      { nl: 'De boom is klein.', en: 'The tree is small.', image: 'tree-small' },
    ],
    note: 'groot (big), klein (small), oud (old), jong (young), moe (tired), blij (happy), ziek (ill), mooi (beautiful), nieuw (new), lief (sweet, kind). After “is” an adjective never changes its form — it is always groot, never anything longer. Before a noun it can change; that waits until lesson 4.',
  },
  {
    type: 'picture', title: 'Big or small?', grammar: ['de-het'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Het huis is klein.', en: 'The house is small.', answer: 'house-small',
    choices: [{ image: 'house', nl: 'Het huis is groot.' }, { image: 'house-small', nl: 'Het huis is klein.' }, { image: 'tree-small', nl: 'De boom is klein.' }],
  },
  {
    type: 'picture', listen: true, title: 'Old or young? By ear', grammar: ['de-het'],
    instruction: 'Listen without reading. Which picture is it?',
    nl: 'De man is oud.', en: 'The man is old.', answer: 'old-man',
    choices: [{ image: 'man', nl: 'Bram is jong.' }, { image: 'old-man', nl: 'De man is oud.' }, { image: 'old-woman', nl: 'De vrouw is oud.' }, { image: 'tree', nl: 'De boom is groot.' }],
  },
  {
    type: 'picture', title: 'Tired, happy or ill?',
    instruction: 'Read and choose.',
    nl: 'Bram is blij.', en: 'Bram is happy.', answer: 'man-happy',
    choices: [{ image: 'man-tired', nl: 'Bram is moe.' }, { image: 'woman-sick', nl: 'Lotte is ziek.' }, { image: 'man-happy', nl: 'Bram is blij.' }, { image: 'woman-tired', nl: 'Lotte is moe.' }],
  },
  {
    type: 'picture', listen: true, title: 'Who is ill? By ear',
    instruction: 'Listen. Choose the picture.',
    nl: 'Lotte is ziek.', en: 'Lotte is ill.', answer: 'woman-sick',
    choices: [{ image: 'woman-tired', nl: 'Lotte is moe.' }, { image: 'woman-sick', nl: 'Lotte is ziek.' }, { image: 'man-happy', nl: 'Bram is blij.' }],
  },
  {
    type: 'picture', listen: true, title: 'What is new?', grammar: ['de-het'],
    instruction: 'Listen. The noun is the clue — the adjective is the same in two of them.',
    nl: 'De auto is nieuw.', en: 'The car is new.', answer: 'car',
    choices: [{ image: 'door', nl: 'De deur is nieuw.' }, { image: 'child', nl: 'Het kind is lief.' }, { image: 'car', nl: 'De auto is nieuw.' }, { image: 'tree-small', nl: 'De boom is klein.' }],
  },
  {
    type: 'drill', title: 'Write the word', grammar: ['de-het'],
    instruction: 'Look at the picture and type the missing adjective.',
    items: [
      { image: 'house', nl: 'Het huis is ___.', en: 'The house is big.', answer: 'groot' },
      { image: 'man-happy', nl: 'Bram is ___.', en: 'Bram is happy.', answer: 'blij' },
      { image: 'old-man', nl: 'De man is ___.', en: 'The man is old.', answer: 'oud' },
      { image: 'woman-sick', nl: 'Lotte is ___.', en: 'Lotte is ill.', answer: 'ziek' },
      { image: 'man-tired', nl: 'Bram is ___.', en: 'Bram is tired.', answer: 'moe' },
      { image: 'car', nl: 'De auto is ___.', en: 'The car is new.', answer: 'nieuw' },
      { image: 'house-small', nl: 'Het huis is ___.', en: 'The house is small.', answer: 'klein' },
      { image: 'neighbourhood', nl: 'De straat is ___.', en: 'The street is beautiful.', answer: 'mooi' },
      { image: 'woman', nl: 'Lotte is ___.', en: 'Lotte is young.', answer: 'jong' },
      { image: 'child', nl: 'Het kind is ___.', en: 'The child is sweet.', answer: 'lief' },
      { image: 'tree', nl: 'De boom is ___.', en: 'The tree is big.', answer: 'groot' },
      { image: 'door', nl: 'De deur is ___.', en: 'The door is new.', answer: 'nieuw' },
      { image: 'old-woman', nl: 'De vrouw is ___.', en: 'The woman is old.', answer: 'oud' },
      { image: 'window', nl: 'Het raam is ___.', en: 'The window is beautiful.', answer: 'mooi' },
      { image: 'tree-small', nl: 'De boom is ___.', en: 'The tree is small.', answer: 'klein' },
      { image: 'woman-tired', nl: 'Lotte is ___.', en: 'Lotte is tired.', answer: 'moe' },
    ],
    explanation: 'Ten adjectives, and after “is” none of them ever changes, whatever the noun: de auto is nieuw, het raam is mooi.',
  },
  {
    type: 'drill', title: 'Hear and spell',
    instruction: 'Play each word or sentence and type it. Replay as often as you like.',
    items: [
      { listen: 'moe' }, { listen: 'blij' }, { listen: 'oud' }, { listen: 'ziek' }, { listen: 'klein' },
      { listen: 'nieuw' }, { listen: 'groot' }, { listen: 'lief' }, { listen: 'jong' }, { listen: 'mooi' },
      { listen: 'De boom is oud.' },
      { listen: 'Het kind is blij.' },
    ],
    explanation: '“oe” (moe) is the English “oo” in “too”. “ou” (oud) is the same sound as “ouw” in vrouw. “ij” (blij) and “ei” (klein) are two spellings of one sound — you must learn which word takes which. “ie” (ziek, lief) is the English “ee”; “nieuw” is that “ee” rounded off into a w. “ooi” (mooi) is the long o of “boom” gliding into a short y. A final d is pronounced as t: “oud” sounds like “out”. The j in “jong” is an English y.',
  },

  // ——— Grammar: subject pronouns ———
  {
    part: 'Grammar', type: 'grammar', title: 'Who? The subject pronouns', grammar: ['subject-pronouns'],
    body: [
      'A subject pronoun stands in for the person or thing the sentence is about: *Bram is moe* → ***Hij** is moe.* Dutch has one for every person, as English does — with three differences worth knowing from the start.',
      '**1. Stressed and unstressed forms.** Three pronouns have two forms: **jij / je**, **zij / ze**, **wij / we**. The unstressed forms (je, ze, we) are what people normally say. The stressed forms carry contrast or emphasis: *Ik ben moe. En **jij**?* Both are correct; in this course both are always accepted.',
      '**2. zij / ze is both “she” and “they”.** Often only the verb tells you which: *ze **is** ziek* is she, *ze **zijn** ziek* is they. You will see this on the next page.',
      '**3. “You” is either one person or several.** **jij / je** speaks to one person, **jullie** to two or more. English hides the difference; Dutch always marks it. (Dutch also has a formal *u*; this course uses the everyday jij/je.)',
      '**het** means *it*. For things there is a twist — a de-word is “hij” — which gets its own page later in this lesson.',
    ],
    tables: [
      { caption: 'Singular', rows: [{ nl: 'ik', en: 'I' }, { nl: 'jij / je', en: 'you (one person)' }, { nl: 'hij', en: 'he' }, { nl: 'zij / ze', en: 'she' }, { nl: 'het', en: 'it' }] },
      { caption: 'Plural', rows: [{ nl: 'wij / we', en: 'we' }, { nl: 'jullie', en: 'you (two or more)' }, { nl: 'zij / ze', en: 'they' }] },
    ],
    examples: [
      { nl: 'Bram is moe. Hij is moe.', en: 'Bram is tired. He is tired.' },
      { nl: 'Lotte is ziek. Ze is ziek.', en: 'Lotte is ill. She is ill.' },
      { nl: 'Bram en Lotte zijn blij. Ze zijn blij.', en: 'Bram and Lotte are happy. They are happy.' },
      { nl: 'Lotte en ik zijn moe. We zijn moe.', en: 'Lotte and I are tired. We are tired.' },
    ],
  },
  {
    type: 'drill', title: 'Which pronoun?', grammar: ['subject-pronouns'], choices: ['ik', 'jij', 'hij', 'zij', 'het', 'wij', 'jullie'],
    instruction: 'Which pronoun can replace these words? For “jij en …” think: who am I talking to?',
    items: [
      { nl: 'Bram', answer: 'hij' },
      { nl: 'Lotte', answer: 'zij' },
      { nl: 'Bram en Lotte', en: 'talking about them', answer: 'zij' },
      { nl: 'Lotte en ik', answer: 'wij' },
      { nl: 'jij en Bram', en: 'talking to both of them', answer: 'jullie' },
      { nl: 'de man', answer: 'hij' },
      { nl: 'de vrouw', answer: 'zij' },
      { nl: 'het huis', answer: 'het' },
    ],
    explanation: '“X en ik” is always wij. “Jij en X” is always jullie. Two or more people you talk about are zij — the same word as “she”.',
  },

  // ——— Grammar: zijn ———
  {
    type: 'grammar', title: 'zijn — to be', grammar: ['zijn', 'subject-pronouns'],
    body: [
      '**zijn** (to be) is the most irregular verb in Dutch and the one you will use most. You already know one form, **is**. Here is the whole present tense.',
      'Singular: **ik ben**, **jij bent**, **hij / zij / het is**. The -t of *bent* belongs to jij/je alone — ik ben, without t.',
      'Plural: **wij zijn**, **jullie zijn**, **zij zijn** — all three the same, and identical to the infinitive (the dictionary form). This holds for every Dutch verb, so notice it now: the plural of the present tense is always the infinitive.',
      'This is how you tell *ze* = she from *ze* = they: **ze is** moe (she), **ze zijn** moe (they).',
      'An adjective after zijn never changes: ik ben blij, wij zijn blij, de auto is nieuw.',
    ],
    tables: [
      { caption: 'zijn — singular', rows: [{ nl: 'ik [ben]', en: 'I am' }, { nl: 'jij [bent]', en: 'you are (one person)' }, { nl: 'hij [is]', en: 'he is' }, { nl: 'zij [is]', en: 'she is' }, { nl: 'het [is]', en: 'it is' }] },
      { caption: 'zijn — plural', rows: [{ nl: 'wij [zijn]', en: 'we are' }, { nl: 'jullie [zijn]', en: 'you are (two or more)' }, { nl: 'zij [zijn]', en: 'they are' }] },
    ],
    examples: [
      { nl: 'Ik ben blij.', en: 'I am happy.' },
      { nl: 'Jij bent lief.', en: 'You are sweet.' },
      { nl: 'Het huis is mooi.', en: 'The house is beautiful.' },
      { nl: 'Wij zijn jong.', en: 'We are young.' },
      { nl: 'Jullie zijn moe.', en: 'You (two or more) are tired.' },
      { nl: 'Ze is ziek.', en: 'She is ill.' },
      { nl: 'Ze zijn oud.', en: 'They are old.' },
    ],
  },
  {
    type: 'drill', title: 'Conjugate zijn', grammar: ['zijn', 'subject-pronouns'], layout: 'table', task: 'zijn',
    instruction: 'Type the form of zijn for every person. No looking back.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'ben' },
      { label: 'jij', gloss: 'you', answer: 'bent' },
      { label: 'hij', gloss: 'he', answer: 'is' },
      { label: 'zij', gloss: 'she', answer: 'is' },
      { label: 'het', gloss: 'it', answer: 'is' },
      { label: 'wij', gloss: 'we', answer: 'zijn' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'zijn' },
      { label: 'zij', gloss: 'they', answer: 'zijn' },
    ],
    explanation: 'ben — bent — is — zijn. Only four forms for eight persons.',
  },
  {
    type: 'drill', title: 'ben, bent, is or zijn?', grammar: ['zijn', 'de-het'], choices: ['ben', 'bent', 'is', 'zijn'],
    instruction: 'Choose the form. Look at the subject first, then choose.',
    items: [
      { nl: 'Ik ___ blij.', answer: 'ben' },
      { nl: 'De auto ___ nieuw.', answer: 'is' },
      { nl: 'Bram en Lotte ___ jong.', answer: 'zijn' },
      { nl: 'Jij ___ lief.', answer: 'bent' },
      { nl: 'Het raam ___ klein.', answer: 'is' },
      { nl: 'Jullie ___ ziek.', answer: 'zijn' },
      { nl: 'Het kind ___ blij.', answer: 'is' },
      { nl: 'Ze ___ oud.', en: 'She is old.', answer: 'is' },
      { nl: 'Ze ___ oud.', en: 'They are old.', answer: 'zijn' },
    ],
    explanation: 'Two names joined by “en” are plural: Bram en Lotte zijn. One child is singular: het kind is.',
  },
  {
    type: 'drill', title: 'zijn, in another order', grammar: ['zijn', 'subject-pronouns'], layout: 'table', task: 'zijn',
    instruction: 'The same verb, the everyday short pronouns, a new order. Type every form.',
    items: [
      { label: 'we', gloss: 'we', answer: 'zijn' },
      { label: 'ze', gloss: 'she', answer: 'is' },
      { label: 'je', gloss: 'you', answer: 'bent' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'zijn' },
      { label: 'ik', gloss: 'I', answer: 'ben' },
      { label: 'ze', gloss: 'they', answer: 'zijn' },
      { label: 'het', gloss: 'it', answer: 'is' },
      { label: 'hij', gloss: 'he', answer: 'is' },
    ],
    explanation: 'je bent, like jij bent. ze is (she) against ze zijn (they): the verb does the work.',
  },
  {
    type: 'drill', title: 'Type the right form', grammar: ['zijn', 'subject-pronouns'],
    instruction: 'Type the form of zijn. The English settles every “ze”.',
    items: [
      { nl: 'Ik ___ ziek.', cue: 'zijn', en: 'I am ill.', answer: 'ben' },
      { nl: 'Jij ___ lief.', cue: 'zijn', en: 'You are sweet.', answer: 'bent' },
      { nl: 'Bram ___ blij.', cue: 'zijn', en: 'Bram is happy.', answer: 'is' },
      { nl: 'Wij ___ jong.', cue: 'zijn', en: 'We are young.', answer: 'zijn' },
      { nl: 'Jullie ___ moe.', cue: 'zijn', en: 'You (plural) are tired.', answer: 'zijn' },
      { nl: 'De straat ___ mooi.', cue: 'zijn', en: 'The street is beautiful.', answer: 'is' },
      { nl: 'Ze ___ ziek.', cue: 'zijn', en: 'She is ill.', answer: 'is' },
      { nl: 'Ze ___ blij.', cue: 'zijn', en: 'They are happy.', answer: 'zijn' },
      { nl: 'Je ___ moe.', cue: 'zijn', en: 'You are tired.', answer: 'bent' },
      { nl: 'De deur ___ nieuw.', cue: 'zijn', en: 'The door is new.', answer: 'is' },
      { nl: 'Lotte en ik ___ blij.', cue: 'zijn', en: 'Lotte and I are happy.', answer: 'zijn' },
      { nl: 'Ik ___ ook moe.', cue: 'zijn', en: 'I am tired too.', answer: 'ben' },
    ],
    explanation: '“Ook” (too, also) comes straight after the verb: Ik ben ook moe.',
  },
  {
    type: 'drill', title: 'Change the subject', grammar: ['zijn', 'subject-pronouns'],
    instruction: 'Rewrite the sentence with the new subject. The verb must change with it.',
    items: [
      { nl: 'Ik ben ziek.', task: 'Change to hij', answer: 'Hij is ziek.' },
      { nl: 'Hij is blij.', task: 'Change to jullie', answer: 'Jullie zijn blij.' },
      { nl: 'Wij zijn moe.', task: 'Change to ik', answer: 'Ik ben moe.' },
      { nl: 'Zij is lief.', task: 'Change to jij', answer: 'Jij bent lief.' },
      { nl: 'Lotte is ziek.', task: 'Change to Bram en Lotte', answer: 'Bram en Lotte zijn ziek.' },
      { nl: 'Jullie zijn oud.', task: 'Change to ik', answer: 'Ik ben oud.' },
      { nl: 'Ik ben ook blij.', task: 'Change to jij', answer: 'Jij bent ook blij.' },
      { nl: 'Bram is jong.', task: 'Change to Bram en ik', answer: 'Bram en ik zijn jong.' },
      { nl: 'Het kind is lief.', task: 'Change to jullie', answer: 'Jullie zijn lief.' },
    ],
  },

  // ——— Grammar: verb-first questions ———
  {
    type: 'grammar', title: 'Questions: the verb comes first', grammar: ['inversion', 'zijn', 'yes-no-question'],
    body: [
      'In lesson 1 you made a question by putting the verb first: *Is dit een huis?* The rule is the same with every subject: **verb first, subject second**, the rest in its place. Dutch has no helper like English “do” — it only swaps.',
      '**The trap.** When **jij** or **je** comes *directly after* the verb, the verb loses its -t: *jij ben**t** moe* → ***Ben** jij moe?* Never “bent jij”. The -t drops for jij/je only, and only when jij/je follows the verb.',
      'Everything else simply swaps: *hij is* → *is hij*, *wij zijn* → *zijn wij*, *jullie zijn* → *zijn jullie*. Jullie is not jij: *zijn jullie* keeps its form.',
      'When you answer, switch point of view. *Ben **jij** moe?* — *Ja, **ik** ben moe.* *Zijn **jullie** blij?* — *Ja, **wij** zijn blij.*',
      'This swap, and the lost -t after jij, will happen with every verb you learn. Get it automatic now, with zijn.',
    ],
    tables: [
      { caption: 'Questions with zijn', rows: [
        { nl: 'Ben ik oud?', en: 'Am I old?' },
        { nl: 'Ben jij moe?', en: 'Are you tired?' },
        { nl: 'Ben je ziek?', en: 'Are you ill? (everyday form)' },
        { nl: 'Is hij blij?', en: 'Is he happy?' },
        { nl: 'Is ze moe?', en: 'Is she tired?' },
        { nl: 'Is het nieuw?', en: 'Is it new?' },
        { nl: 'Zijn we moe?', en: 'Are we tired?' },
        { nl: 'Zijn jullie ziek?', en: 'Are you (two or more) ill?' },
        { nl: 'Zijn ze blij?', en: 'Are they happy?' },
      ] },
    ],
    examples: [
      { nl: 'Jij ben[t] moe.', en: 'You are tired. — with t' },
      { nl: 'Ben jij moe?', en: 'Are you tired? — no t' },
      { nl: 'Ja, ik ben moe.', en: 'Yes, I am tired.' },
      { nl: 'Zijn jullie blij?', en: 'Are you (two or more) happy?' },
      { nl: 'Ja, wij zijn blij.', en: 'Yes, we are happy.' },
    ],
  },
  {
    type: 'drill', title: 'The -t trap', grammar: ['inversion', 'zijn'], choices: ['ben', 'bent'],
    instruction: 'ben or bent? Look at where jij/je stands: before the verb or after it?',
    items: [
      { nl: 'Jij ___ lief.', answer: 'bent' },
      { nl: 'Bram, ___ jij moe?', answer: 'ben' },
      { nl: 'Je ___ ziek.', answer: 'bent' },
      { nl: 'Lotte, ___ je ook blij?', answer: 'ben' },
      { nl: 'Ik ___ moe.', answer: 'ben' },
      { nl: 'Jij ___ ook jong.', answer: 'bent' },
    ],
    explanation: 'jij/je before the verb: bent. jij/je after the verb: ben. And ik is always ben.',
  },
  {
    type: 'drill', title: 'Start the question', grammar: ['inversion', 'zijn'],
    instruction: 'Type the verb that begins each question.',
    items: [
      { nl: '___ jij ziek?', cue: 'zijn', en: 'Are you ill?', answer: 'Ben' },
      { nl: '___ hij oud?', cue: 'zijn', en: 'Is he old?', answer: 'Is' },
      { nl: '___ jullie blij?', cue: 'zijn', en: 'Are you (plural) happy?', answer: 'Zijn' },
      { nl: '___ ik oud?', cue: 'zijn', en: 'Am I old?', answer: 'Ben' },
      { nl: '___ ze moe?', cue: 'zijn', en: 'Is she tired?', answer: 'Is' },
      { nl: '___ ze moe?', cue: 'zijn', en: 'Are they tired?', answer: 'Zijn' },
      { nl: '___ je ook moe?', cue: 'zijn', en: 'Are you tired too?', answer: 'Ben' },
      { nl: '___ de auto nieuw?', cue: 'zijn', en: 'Is the car new?', answer: 'Is' },
      { nl: '___ Bram en Lotte jong?', cue: 'zijn', en: 'Are Bram and Lotte young?', answer: 'Zijn' },
      { nl: '___ het kind lief?', cue: 'zijn', en: 'Is the child sweet?', answer: 'Is' },
    ],
  },
  {
    type: 'drill', title: 'Make it a question', grammar: ['inversion', 'yes-no-question', 'zijn', 'dit-is'], task: 'Make it a question',
    instruction: 'Rewrite each statement as a yes/no question. Verb first — and watch jij.',
    items: [
      { nl: 'Jij bent ziek.', answer: 'Ben jij ziek?' },
      { nl: 'Hij is oud.', answer: 'Is hij oud?' },
      { nl: 'Wij zijn blij.', answer: 'Zijn wij blij?' },
      { nl: 'Je bent ook moe.', answer: 'Ben je ook moe?' },
      { nl: 'Jullie zijn moe.', answer: 'Zijn jullie moe?' },
      { nl: 'De straat is mooi.', answer: 'Is de straat mooi?' },
      { nl: 'Zij zijn oud.', answer: 'Zijn zij oud?' },
      { nl: 'Lotte is lief.', answer: 'Is Lotte lief?' },
      { nl: 'Het raam is nieuw.', answer: 'Is het raam nieuw?' },
      { nl: 'Dit is een auto.', answer: 'Is dit een auto?' },
    ],
    explanation: 'Only one sentence changed its verb: jij bent → ben jij. Everywhere else the verb just moved.',
  },
  {
    type: 'arrange', title: 'Build the question', grammar: ['inversion', 'zijn'],
    instruction: 'Build: “Are you tired too?” Two words are left over.',
    nl: 'Ben jij ook moe?', en: 'Are you tired too?', image: 'woman-tired', distractors: ['bent', 'is'],
  },

  // ——— Grammar: niet ———
  {
    type: 'grammar', title: 'niet — and how it differs from geen', grammar: ['niet', 'geen', 'zijn', 'dit-is'],
    body: [
      '**niet** means *not*. With zijn it comes straight **after the verb**, before the adjective: *Ik ben **niet** ziek.* *Het huis is **niet** groot.*',
      'In a question the verb goes first and niet follows the subject: *Ben jij **niet** moe?* — Aren’t you tired?',
      'With **ook**, ook comes first: *Ik ben **ook niet** moe* — I am not tired either.',
      '**geen or niet?** You know **geen** from lesson 1: it *replaces een* in front of a noun. *Dit is een auto* → *Dit is **geen** auto.* Dutch does not say “niet een” here. For everything else use **niet**: before an adjective (*niet moe*), and also before a noun with *de* or *het*: *Dit is **niet** het huis* — this is not *the* house.',
      'The quick test: would the positive sentence have **een**? Then geen. Otherwise niet.',
    ],
    tables: [
      { caption: 'geen replaces een — niet does the rest', rows: [
        { nl: 'Bram is [geen] vrouw.', en: 'Bram is not a woman.' },
        { nl: 'Bram is [niet] oud.', en: 'Bram is not old.' },
        { nl: 'Dit is [geen] auto.', en: 'This is not a car.' },
        { nl: 'Dit is [niet] de auto.', en: 'This is not the car.' },
        { nl: 'De auto is [niet] nieuw.', en: 'The car is not new.' },
      ] },
    ],
    examples: [
      { nl: 'Ik ben niet ziek.', en: 'I am not ill.' },
      { nl: 'Ben jij niet moe?', en: 'Aren’t you tired?' },
      { nl: 'Ik ben ook niet moe.', en: 'I am not tired either.' },
      { nl: 'Het huis is niet oud.', en: 'The house is not old.' },
      { nl: 'Nee, dit is geen raam. Dit is een deur.', en: 'No, this is not a window. This is a door.' },
    ],
  },
  {
    type: 'drill', title: 'zijn with niet', grammar: ['niet', 'zijn'], layout: 'table', task: '… niet ziek',
    instruction: 'Complete each row: the right form of zijn, then “niet ziek”.',
    items: [
      { label: 'ik', gloss: 'I am not ill', answer: 'ben niet ziek' },
      { label: 'jij', gloss: 'you are not ill', answer: 'bent niet ziek' },
      { label: 'hij', gloss: 'he is not ill', answer: 'is niet ziek' },
      { label: 'zij', gloss: 'she is not ill', answer: 'is niet ziek' },
      { label: 'wij', gloss: 'we are not ill', answer: 'zijn niet ziek' },
      { label: 'jullie', gloss: 'you (plural) are not ill', answer: 'zijn niet ziek' },
      { label: 'zij', gloss: 'they are not ill', answer: 'zijn niet ziek' },
    ],
  },
  {
    type: 'drill', title: 'Say it is not so', grammar: ['niet', 'geen', 'zijn', 'inversion', 'dit-is'], task: 'Make it negative',
    instruction: 'Make each sentence negative. Decide every time: niet or geen?',
    items: [
      { nl: 'Ik ben ziek.', answer: 'Ik ben niet ziek.' },
      { nl: 'Hij is oud.', answer: 'Hij is niet oud.' },
      { nl: 'Dit is een boom.', answer: 'Dit is geen boom.' },
      { nl: 'Ben jij moe?', answer: 'Ben jij niet moe?' },
      { nl: 'De auto is nieuw.', answer: 'De auto is niet nieuw.' },
      { nl: 'Wij zijn blij.', answer: 'Wij zijn niet blij.' },
      { nl: 'Dit is een deur.', answer: 'Dit is geen deur.' },
      { nl: 'Dit is een bank.', answer: 'Dit is geen bank.' },
      { nl: 'Ik ben ook moe.', answer: 'Ik ben ook niet moe.' },
      { nl: 'Is het huis klein?', answer: 'Is het huis niet klein?' },
      { nl: 'Het kind is ziek.', answer: 'Het kind is niet ziek.' },
    ],
    explanation: '“een” became “geen” three times; everywhere else “niet” went in straight after the verb — or after the subject in a question.',
  },
  {
    type: 'drill', title: 'geen or niet?', grammar: ['niet', 'geen'], choices: ['geen', 'niet'],
    instruction: 'Choose. Is there an “een” to replace?',
    items: [
      { nl: 'Bram is ___ vrouw.', answer: 'geen' },
      { nl: 'Bram is ___ ziek.', answer: 'niet' },
      { nl: 'Dit is ___ huis.', en: 'This is not a house.', answer: 'geen' },
      { nl: 'Het raam is ___ klein.', answer: 'niet' },
      { nl: 'Lotte is ___ moe.', answer: 'niet' },
      { nl: 'Nee, dit is ___ bank. Dit is een boom.', answer: 'geen' },
      { nl: 'De man is ___ jong.', answer: 'niet' },
      { nl: 'Lotte is ___ man.', answer: 'geen' },
    ],
  },
  {
    type: 'drill', title: 'geen or niet — now type it', grammar: ['niet', 'geen', 'de-het'],
    instruction: 'Type geen or niet. The English decides; watch “a” against “the”.',
    items: [
      { nl: 'Dit is ___ de boom.', cue: 'geen / niet', en: 'This is not the tree.', answer: 'niet' },
      { nl: 'Dit is ___ boom.', cue: 'geen / niet', en: 'This is not a tree.', answer: 'geen' },
      { nl: 'De vrouw is ___ oud.', cue: 'geen / niet', en: 'The woman is not old.', answer: 'niet' },
      { nl: 'Dit is ___ het raam.', cue: 'geen / niet', en: 'This is not the window.', answer: 'niet' },
      { nl: 'Jullie zijn ___ moe.', cue: 'geen / niet', en: 'You (plural) are not tired.', answer: 'niet' },
      { nl: 'Dit is ___ auto.', cue: 'geen / niet', en: 'This is not a car.', answer: 'geen' },
      { nl: 'De straat is ___ mooi.', cue: 'geen / niet', en: 'The street is not beautiful.', answer: 'niet' },
      { nl: 'Bram is ___ vrouw.', cue: 'geen / niet', en: 'Bram is not a woman.', answer: 'geen' },
    ],
    explanation: 'Only “een” turns into “geen”. With de, het or an adjective, it is niet.',
  },

  // ——— Grammar: hij and het for things ———
  {
    type: 'grammar', title: 'hij and het for things', grammar: ['hij-het-things', 'de-het'],
    body: [
      'English calls every thing *it*. Dutch looks at the article: a **de**-word is referred to as **hij**, a **het**-word as **het**.',
      '*De auto is nieuw. **Hij** is mooi.* — here “hij” means *it*, not *he*. *Het raam is klein. **Het** is oud.*',
      'People follow who they are, not the article: de man → **hij**, de vrouw → **zij**. The one exception is **het kind**: when you speak about “the child” in general, it is **het**, as the article says. *Het kind is ziek. **Het** is moe.*',
      'This is the practical reason articles matter: you cannot even say “it” in Dutch without knowing whether a noun is de or het. Learn every noun with its article — and so with its pronoun.',
      'A note for Belgium: in Flanders some de-words — *de straat*, *de deur*, *de bank* — are traditionally feminine and called **ze**, not hij. The examples in this course use hij only with words like *de boom* and *de auto*, where the whole language area agrees.',
      'One limit: when you point at something to *name* it, you say **dit** whatever the noun is: *Dit is een auto.* Hij and het are for talking about something already mentioned.',
    ],
    tables: [
      { caption: 'de-word → hij · het-word → het', rows: [
        { nl: 'De boom is groot. [Hij] is oud.', en: 'The tree is big. It is old.' },
        { nl: 'De auto is nieuw. [Hij] is mooi.', en: 'The car is new. It is beautiful.' },
        { nl: 'Het huis is klein. [Het] is oud.', en: 'The house is small. It is old.' },
        { nl: 'Het raam is groot. [Het] is nieuw.', en: 'The window is big. It is new.' },
        { nl: 'Het kind is ziek. [Het] is moe.', en: 'The child is ill. It is tired.' },
        { nl: 'De man is oud. [Hij] is niet moe.', en: 'The man is old. He is not tired.' },
        { nl: 'De vrouw is oud. [Zij] is lief.', en: 'The woman is old. She is sweet.' },
      ] },
    ],
    examples: [
      { nl: 'Is de boom groot? Ja, hij is groot.', en: 'Is the tree big? Yes, it is big.' },
      { nl: 'Is het huis oud? Nee, het is niet oud.', en: 'Is the house old? No, it is not old.' },
      { nl: 'Is de auto nieuw? Ja, hij is nieuw.', en: 'Is the car new? Yes, it is new.' },
    ],
  },
  {
    type: 'drill', title: 'hij, zij or het?', grammar: ['hij-het-things', 'de-het'], choices: ['Hij', 'Zij', 'Het'],
    instruction: 'Choose the pronoun for the second sentence. Check the article in the first.',
    items: [
      { nl: 'De boom is groot. ___ is oud.', answer: 'Hij' },
      { nl: 'Het huis is klein. ___ is oud.', answer: 'Het' },
      { nl: 'De vrouw is oud. ___ is lief.', answer: 'Zij' },
      { nl: 'De auto is nieuw. ___ is ook mooi.', answer: 'Hij' },
      { nl: 'Het raam is groot. ___ is niet oud.', answer: 'Het' },
      { nl: 'De man is jong. ___ is moe.', answer: 'Hij' },
      { nl: 'Het kind is ziek. ___ is moe.', answer: 'Het' },
    ],
    explanation: 'boom and auto are de-words, so “it” is hij. huis, raam and kind are het-words: het.',
  },
  {
    type: 'drill', title: 'Answer with hij or het', grammar: ['hij-het-things', 'yes-no-question', 'niet'], task: 'Answer in full',
    instruction: 'Look at the picture and answer with a pronoun: “Ja, hij is …” or “Nee, het is niet …”.',
    items: [
      { image: 'tree', nl: 'Is de boom groot?', answer: 'Ja, hij is groot.' },
      { image: 'house-small', nl: 'Is het huis groot?', answer: 'Nee, het is niet groot.', accept: ['Nee, het is klein.', 'Nee, het is niet groot. Het is klein.'] },
      { image: 'car', nl: 'Is de auto nieuw?', answer: 'Ja, hij is nieuw.' },
      { image: 'tree-small', nl: 'Is de boom oud?', answer: 'Nee, hij is niet oud.', accept: ['Nee, hij is jong.', 'Nee, hij is niet oud. Hij is jong.'] },
      { image: 'woman-sick', nl: 'Is Lotte ziek?', answer: 'Ja, zij is ziek.' },
      { image: 'old-man', nl: 'Is de man jong?', answer: 'Nee, hij is niet jong.', accept: ['Nee, hij is oud.', 'Nee, hij is niet jong. Hij is oud.'] },
      { image: 'child', nl: 'Is het kind klein?', answer: 'Ja, het is klein.' },
      { image: 'man-happy', nl: 'Is Bram moe?', answer: 'Nee, hij is niet moe.', accept: ['Nee, hij is blij.', 'Nee, hij is niet moe. Hij is blij.'] },
      { image: 'house', nl: 'Is het huis groot?', answer: 'Ja, het is groot.' },
    ],
  },
  {
    type: 'drill', title: 'Replace the noun', grammar: ['hij-het-things', 'inversion', 'niet'], task: 'Use hij, zij or het',
    instruction: 'Rewrite the sentence with a pronoun instead of the noun. Everything else stays.',
    items: [
      { nl: 'De boom is oud.', answer: 'Hij is oud.' },
      { nl: 'Het huis is klein.', answer: 'Het is klein.' },
      { nl: 'De vrouw is ziek.', answer: 'Zij is ziek.' },
      { nl: 'Is de auto nieuw?', answer: 'Is hij nieuw?' },
      { nl: 'Is het raam groot?', answer: 'Is het groot?' },
      { nl: 'De man is niet moe.', answer: 'Hij is niet moe.' },
      { nl: 'Bram en Lotte zijn blij.', answer: 'Zij zijn blij.' },
      { nl: 'De boom is ook mooi.', answer: 'Hij is ook mooi.' },
      { nl: 'Het kind is lief.', answer: 'Het is lief.' },
    ],
    explanation: '“Is het groot?” — het is now the subject, so the article is gone. “Is hij nieuw?” is the car. “Het is lief” is the child: het kind takes het.',
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'observe', title: 'What we know about the street', grammar: ['hij-het-things', 'niet', 'geen', 'dit-is'],
    instruction: 'Everything in this lesson, in one small world. Read, listen, and say each card twice.',
    cards: [
      { nl: 'Bram is jong. Hij is moe.', en: 'Bram is young. He is tired.', image: 'man-tired' },
      { nl: 'Lotte is ook jong. Ze is niet moe.', en: 'Lotte is young too. She is not tired.', image: 'woman' },
      { nl: 'Het huis is groot en mooi. Het is niet oud.', en: 'The house is big and beautiful. It is not old.', image: 'house' },
      { nl: 'De boom is groot. Hij is oud.', en: 'The tree is big. It is old.', image: 'tree' },
      { nl: 'Dit is geen boom. Dit is een bank.', en: 'This is not a tree. This is a bench.', image: 'bench' },
      { nl: 'De man is oud. Hij is lief.', en: 'The man is old. He is kind.', image: 'old-man' },
      { nl: 'De auto is nieuw. Hij is mooi.', en: 'The car is new. It is beautiful.', image: 'car' },
      { nl: 'Het kind is klein. Het is blij.', en: 'The child is small. It is happy.', image: 'child' },
    ],
    note: 'Bram and Lotte live in this house in Leuven. The old man often sits on the bench in the street. Bram works in Brussel and is often tired; Lotte rarely is. “Lief” is sweet or kind — said of children, of people you like, of the old man on the bench.',
  },
  {
    type: 'drill', title: 'Every verb so far: zijn in every sentence', grammar: ['zijn', 'inversion', 'niet', 'subject-pronouns'],
    instruction: 'zijn is still your only verb, so it gets everything: statements, questions, negatives. Type the form.',
    items: [
      { nl: 'Ik ___ niet ziek.', cue: 'zijn', answer: 'ben' },
      { nl: '___ jij moe?', cue: 'zijn', answer: 'Ben' },
      { nl: 'Lotte ___ ook jong.', cue: 'zijn', answer: 'is' },
      { nl: '___ jullie niet blij?', cue: 'zijn', answer: 'Zijn' },
      { nl: 'Jij ___ niet moe.', cue: 'zijn', answer: 'bent' },
      { nl: '___ het huis mooi?', cue: 'zijn', answer: 'Is' },
      { nl: 'Ze ___ niet oud.', cue: 'zijn', en: 'She is not old.', answer: 'is' },
      { nl: 'Ze ___ niet oud.', cue: 'zijn', en: 'They are not old.', answer: 'zijn' },
      { nl: '___ ik oud?', cue: 'zijn', answer: 'Ben' },
      { nl: 'Bram en ik ___ moe.', cue: 'zijn', answer: 'zijn' },
      { nl: 'De auto ___ niet nieuw.', cue: 'zijn', answer: 'is' },
      { nl: 'De bank ___ niet groot.', cue: 'zijn', answer: 'is' },
      { nl: '___ het kind ziek?', cue: 'zijn', answer: 'Is' },
    ],
    explanation: 'Every future verb will get this same treatment — all persons, question, negative.',
  },
  {
    type: 'drill', title: 'Ask, then say no', grammar: ['inversion', 'niet', 'geen', 'hij-het-things', 'dit-is'], task: 'Answer: nee + niet / geen',
    instruction: 'Answer every question with “Nee, …” and a full sentence. Switch the point of view: a question with jij gets an answer with ik.',
    items: [
      { nl: 'Ben jij ziek?', answer: 'Nee, ik ben niet ziek.' },
      { nl: 'Zijn jullie moe?', answer: 'Nee, wij zijn niet moe.' },
      { nl: 'Is Lotte moe?', answer: 'Nee, zij is niet moe.', accept: ['Nee, Lotte is niet moe.'] },
      { nl: 'Is het huis klein?', answer: 'Nee, het is niet klein.', accept: ['Nee, het huis is niet klein.'] },
      { nl: 'Ben ik oud?', answer: 'Nee, jij bent niet oud.' },
      { nl: 'Is de auto oud?', answer: 'Nee, hij is niet oud.', accept: ['Nee, de auto is niet oud.'] },
      { nl: 'Zijn Bram en Lotte oud?', answer: 'Nee, zij zijn niet oud.', accept: ['Nee, Bram en Lotte zijn niet oud.'] },
      { nl: 'Is het kind ziek?', answer: 'Nee, het is niet ziek.', accept: ['Nee, het kind is niet ziek.'] },
      { image: 'tree', nl: 'Is dit een huis?', answer: 'Nee, dit is geen huis.', accept: ['Nee, dit is geen huis. Dit is een boom.'] },
      { image: 'door', nl: 'Is dit een raam?', answer: 'Nee, dit is geen raam.', accept: ['Nee, dit is geen raam. Dit is een deur.'] },
    ],
    explanation: 'Jij → ik, jullie → wij, ik → jij. And the last two needed geen: there was an “een”.',
  },
  {
    type: 'arrange', title: 'Two negatives, two words', grammar: ['niet', 'geen', 'subject-pronouns'],
    instruction: 'Build: “Bram is not a woman, and he is not old.” Two tiles are traps.',
    nl: 'Bram is geen vrouw en hij is niet oud.', en: 'Bram is not a woman, and he is not old.', image: 'man', distractors: ['een', 'bent'],
  },
  {
    type: 'arrange', title: 'It is beautiful too', grammar: ['hij-het-things', 'de-het'],
    instruction: 'Build: “The car is new. It is beautiful too.”',
    nl: 'De auto is nieuw. Hij is ook mooi.', en: 'The car is new. It is beautiful too.', image: 'car', distractors: ['het', 'zijn'],
  },
  {
    type: 'drill', title: 'Two changes at once', grammar: ['inversion', 'niet', 'geen', 'zijn', 'de-het', 'hij-het-things'],
    instruction: 'Do exactly what the task says. Some tasks change the subject and the verb with it.',
    items: [
      { nl: 'Ik ben moe.', task: 'Make it a question with jij', answer: 'Ben jij moe?' },
      { nl: 'Hij is niet ziek.', task: 'Change to wij', answer: 'Wij zijn niet ziek.' },
      { nl: 'De boom is oud.', task: 'Make it negative', answer: 'De boom is niet oud.' },
      { nl: 'Jullie zijn blij.', task: 'Make it a question', answer: 'Zijn jullie blij?' },
      { nl: 'Zij is ook moe.', task: 'Change to ik', answer: 'Ik ben ook moe.' },
      { nl: 'Ben jij oud?', task: 'Change to hij', answer: 'Is hij oud?' },
      { nl: 'Wij zijn niet moe.', task: 'Change to jij', answer: 'Jij bent niet moe.' },
      { nl: 'Is het huis klein?', task: 'Use “boom” instead of “huis”', answer: 'Is de boom klein?' },
      { nl: 'De auto is nieuw.', task: 'Use “raam” instead of “auto”', answer: 'Het raam is nieuw.' },
    ],
    explanation: 'The last two: huis → boom turns het into de, and auto → raam turns de into het.',
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Moe', image: 'neighbourhood', grammar: ['zijn', 'inversion', 'niet', 'hij-het-things', 'subject-pronouns'],
    instruction: 'Evening in Leuven. Bram is home from work in Brussel. He and Lotte stand in front of their house; across the street the old man sits on the bench, and a new car is parked in the street. They talk about what they see — not to the old man. Read, listen to every line, then read it again without the English.',
    lines: [
      { speaker: 'Lotte', nl: 'Bram, ben je moe?', en: 'Bram, are you tired?', image: 'man-tired' },
      { speaker: 'Bram', nl: 'Ja, ik ben moe. En jij? Ben jij ook moe?', en: 'Yes, I am tired. And you? Are you tired too?', image: 'man-tired' },
      { speaker: 'Lotte', nl: 'Nee, ik ben niet moe. Ik ben blij. De straat is mooi!', en: 'No, I am not tired. I am happy. The street is beautiful!', image: 'neighbourhood' },
      { speaker: 'Lotte', nl: 'Is de boom oud, Bram?', en: 'Is the tree old, Bram?', image: 'tree' },
      { speaker: 'Bram', nl: 'Ja, hij is oud. En hij is groot.', en: 'Yes, it is old. And it is big.', image: 'tree' },
      { speaker: 'Lotte', nl: 'En de man? Is hij ook oud?', en: 'And the man? Is he old too?', image: 'old-man' },
      { speaker: 'Bram', nl: 'Ja, hij is oud. Hij is lief. En hij is niet moe!', en: 'Yes, he is old. He is kind. And he is not tired!', image: 'old-man' },
      { speaker: 'Lotte', nl: 'En de auto? Is hij nieuw?', en: 'And the car? Is it new?', image: 'car' },
      { speaker: 'Bram', nl: 'Ja, hij is nieuw. En hij is mooi.', en: 'Yes, it is new. And it is beautiful.', image: 'car' },
      { speaker: 'Bram', nl: 'En ik, Lotte? Ben ik oud?', en: 'And me, Lotte? Am I old?', image: 'man-tired' },
      { speaker: 'Lotte', nl: 'Nee, Bram. Jij bent niet oud. Jij bent jong.', en: 'No, Bram. You are not old. You are young.', image: 'woman' },
      { speaker: 'Lotte', nl: 'Jong, moe — en lief!', en: 'Young, tired — and sweet!', image: 'man-tired' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'hij-het-things'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the conversation. Answer without looking back.',
    items: [
      { nl: 'Is Bram moe?', answer: 'Ja' },
      { nl: 'Is Lotte moe?', answer: 'Nee' },
      { nl: 'Is Lotte blij?', answer: 'Ja' },
      { nl: 'Is de boom klein?', answer: 'Nee' },
      { nl: 'Is de man oud?', answer: 'Ja' },
      { nl: 'Is de man moe?', answer: 'Nee' },
      { nl: 'Is de auto oud?', answer: 'Nee' },
      { nl: 'Is de straat mooi?', answer: 'Ja' },
    ],
  },
  {
    type: 'drill', title: 'Answer in a full sentence', grammar: ['hij-het-things', 'niet', 'inversion', 'yes-no-question'], task: 'Answer in full',
    instruction: 'Answer from the story with a complete sentence. Use a pronoun (hij, zij, het) instead of the name or noun.',
    items: [
      { nl: 'Is Bram moe?', answer: 'Ja, hij is moe.', accept: ['Ja, Bram is moe.'] },
      { nl: 'Is Lotte ook moe?', answer: 'Nee, zij is niet moe.', accept: ['Nee, Lotte is niet moe.', 'Nee, zij is niet moe. Zij is blij.', 'Nee, zij is blij.'] },
      { nl: 'Is de boom oud?', answer: 'Ja, hij is oud.', accept: ['Ja, de boom is oud.', 'Ja, hij is oud. En hij is groot.'] },
      { nl: 'Is de auto nieuw?', answer: 'Ja, hij is nieuw.', accept: ['Ja, de auto is nieuw.', 'Ja, hij is nieuw. En hij is mooi.'] },
      { nl: 'Is de man jong?', answer: 'Nee, hij is niet jong.', accept: ['Nee, hij is oud.', 'Nee, de man is niet jong.', 'Nee, de man is oud.'] },
      { nl: 'Is de man lief?', answer: 'Ja, hij is lief.', accept: ['Ja, de man is lief.'] },
      { nl: 'Is Bram oud?', answer: 'Nee, hij is niet oud.', accept: ['Nee, hij is jong.', 'Nee, Bram is niet oud.', 'Nee, Bram is jong.', 'Nee, hij is niet oud. Hij is jong.'] },
      { nl: 'Zijn Bram en Lotte jong?', answer: 'Ja, ze zijn jong.', accept: ['Ja, Bram en Lotte zijn jong.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['niet', 'inversion', 'hij-het-things', 'geen', 'dit-is'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'Ik ben niet ziek.' },
      { listen: 'Ben jij ook moe?' },
      { listen: 'De boom is groot. Hij is oud.' },
      { listen: 'Zijn jullie blij?' },
      { listen: 'Het huis is niet klein.' },
      { listen: 'Nee, dit is geen deur.' },
      { listen: 'Lotte is jong en ze is niet moe.' },
      { listen: 'De auto is nieuw en mooi.' },
      { listen: 'Het kind is lief.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['subject-pronouns', 'zijn', 'inversion', 'niet', 'hij-het-things', 'geen', 'de-het', 'dit-is'],
    instruction: 'Translate. “You” means one person unless it says “plural”.',
    items: [
      { en: 'I am tired.', answer: 'Ik ben moe.' },
      { en: 'Are you ill?', answer: 'Ben jij ziek?' },
      { en: 'Are you tired too?', answer: 'Ben jij ook moe?' },
      { en: 'We are not old.', answer: 'Wij zijn niet oud.' },
      { en: 'Are you (plural) happy?', answer: 'Zijn jullie blij?' },
      { en: 'The tree is big. It is old.', answer: 'De boom is groot. Hij is oud.' },
      { en: 'The house is small. It is not old.', answer: 'Het huis is klein. Het is niet oud.' },
      { en: 'The car is new. It is beautiful.', answer: 'De auto is nieuw. Hij is mooi.' },
      { en: 'She is young and she is not tired.', answer: 'Zij is jong en zij is niet moe.' },
      { en: 'They are old.', answer: 'Zij zijn oud.' },
      { en: 'This is not a window.', answer: 'Dit is geen raam.' },
      { en: 'This is not a bench.', answer: 'Dit is geen bank.' },
      { en: 'The door is not new.', answer: 'De deur is niet nieuw.' },
      { en: 'The child is sweet.', answer: 'Het kind is lief.' },
      { en: 'Bram is not old. He is young.', answer: 'Bram is niet oud. Hij is jong.' },
    ],
  },
  {
    type: 'arrange', title: 'Not old — young', grammar: ['niet', 'zijn', 'inversion'],
    instruction: 'Build Lotte’s answer: “No, Bram. You are not old. You are young.”',
    nl: 'Nee, Bram. Jij bent niet oud. Jij bent jong.', en: 'No, Bram. You are not old. You are young.', image: 'man', distractors: ['ben', 'geen'],
  },
  {
    type: 'drill', title: 'Everything together', grammar: ['zijn', 'inversion', 'niet', 'geen', 'hij-het-things', 'de-het', 'subject-pronouns', 'yes-no-question'],
    instruction: 'A last mixed round. Type every answer.',
    items: [
      { nl: 'Jij ___ lief.', cue: 'zijn', answer: 'bent' },
      { nl: '___ jij ziek?', cue: 'zijn', answer: 'Ben' },
      { nl: '___ huis is groot.', cue: 'de / het', answer: 'Het' },
      { nl: '___ raam is nieuw.', cue: 'de / het', answer: 'Het' },
      { nl: 'De auto is nieuw. ___ is ook mooi.', cue: 'hij / het', answer: 'Hij' },
      { nl: 'Het kind is blij. ___ is niet ziek.', cue: 'hij / het', answer: 'Het' },
      { nl: 'Bram is ___ vrouw.', cue: 'geen / niet', answer: 'geen' },
      { nl: 'Lotte is ___ moe.', cue: 'geen / niet', answer: 'niet' },
      { nl: 'Wij zijn blij.', task: 'Make it a question', answer: 'Zijn wij blij?' },
      { nl: 'Jij bent oud.', task: 'Make it negative', answer: 'Jij bent niet oud.' },
      { nl: 'Zijn jullie ziek?', task: 'Answer: nee + niet', answer: 'Nee, wij zijn niet ziek.' },
      { en: 'Is it big? (the house)', answer: 'Is het groot?' },
      { en: 'I am not tired either.', answer: 'Ik ben ook niet moe.' },
      { listen: 'Is hij niet moe?' },
      { image: 'tree-small', nl: 'Is de boom groot?', task: 'Answer in full', answer: 'Nee, hij is niet groot.', accept: ['Nee, hij is klein.', 'Nee, hij is niet groot. Hij is klein.'] },
    ],
  },
  {
    type: 'complete', title: 'Lesson two, properly learned',
    instruction: 'Ten adjectives, every person, the verb zijn, questions with the verb first, niet next to geen, and “it” in two forms. From now on every verb you learn goes through all of this.',
  },
];
