/**
 * Lesson 3 — Waar woon jij?
 * Targets: wonen, werken, lopen, zitten, slapen, koken, spelen, leren, praten, wachten.
 * Structure: in, op, hier, waar, thuis.
 * Grammar: the regular present tense · spelling the stem · question words.
 * Earlier grammar is recycled throughout: dit is, de/het, yes/no questions, geen,
 * pronouns, zijn, verb-first questions, niet, hij/het for things.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Ten verbs', grammar: ['present-regular', 'subject-pronouns'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice. Watch the verbs: they change shape.',
    cards: [
      { nl: 'Bram en Lotte wonen in Leuven.', en: 'Bram and Lotte live in Leuven.', image: 'people-home' },
      { nl: 'Lotte werkt thuis.', en: 'Lotte works at home.', image: 'woman-working' },
      { nl: 'Bram werkt in Brussel.', en: 'Bram works in Brussels.', image: 'man-working' },
      { nl: 'Lotte loopt in de straat.', en: 'Lotte is walking in the street.', image: 'woman-walking' },
      { nl: 'Bram zit op de bank.', en: 'Bram is sitting on the bench.', image: 'man-sitting' },
      { nl: 'Bram is moe. Hij slaapt.', en: 'Bram is tired. He is sleeping.', image: 'man-sleeping' },
      { nl: 'Bram kookt thuis.', en: 'Bram cooks at home.', image: 'man-cooking' },
      { nl: 'Het kind speelt op straat.', en: 'The child is playing in the street.', image: 'child-playing' },
      { nl: 'Lotte leert thuis.', en: 'Lotte is studying at home.', image: 'woman-studying' },
      { nl: 'Bram en Lotte praten.', en: 'Bram and Lotte are talking.', image: 'couple-talking' },
      { nl: 'Bram wacht op Lotte.', en: 'Bram is waiting for Lotte.', image: 'man-waiting' },
    ],
    note: 'The ten verbs: wonen (to live somewhere, to reside — not “to be alive”), werken (to work), lopen (to walk), zitten (to sit), slapen (to sleep), koken (to cook), spelen (to play), leren (to learn; in Flanders also the everyday word for “to study”), praten (to talk), wachten (to wait; wachten op = to wait for). Already you can see two shapes: “Lotte werkt” but “Bram en Lotte wonen”. That difference is the grammar of this lesson. Dutch has one present tense for both “works” and “is working”. (In everyday Flemish, lopen often means “to run”; in this course it means “to walk”, as in standard Dutch.)',
  },
  {
    type: 'observe', title: 'Where? Here, at home, in, on', grammar: ['question-word', 'dit-is', 'zijn', 'hij-het-things'],
    instruction: 'Five small words that tell you where something happens. Listen and repeat.',
    cards: [
      { nl: 'Dit is het huis. Wij wonen hier.', en: 'This is the house. We live here.', image: 'people-home' },
      { nl: 'Het huis is in Leuven. Het is groot en mooi.', en: 'The house is in Leuven. It is big and beautiful.', image: 'house' },
      { nl: 'Lotte zit op de bank.', en: 'Lotte is sitting on the bench.', image: 'woman-sitting' },
      { nl: 'Waar is Lotte? Lotte is thuis. Zij is ziek.', en: 'Where is Lotte? Lotte is at home. She is ill.', image: 'woman-sick' },
      { nl: 'Waar werkt Bram? In Brussel.', en: 'Where does Bram work? In Brussels.', image: 'man-working' },
      { nl: 'Waar speelt het kind? Op straat. Het is blij.', en: 'Where is the child playing? In the street. It is happy.', image: 'child-playing' },
      { nl: 'Bram en Lotte zitten op de bank.', en: 'Bram and Lotte are sitting on the bench.', image: 'couple-bench' },
    ],
    note: 'in = in (a town, a house, a car) · op = on (a bench) · hier = here · thuis = at home, one word, no “in” before it · waar = where (not “were”!). Two fixed pairs with op: “op straat” = out in the street, with no article; “wachten op” = to wait for.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['present-regular'],
    instruction: 'Read the sentence and choose its picture. Two of them show Lotte at a desk or a table — look closely.',
    nl: 'Lotte leert thuis.', en: 'Lotte is studying at home.', answer: 'woman-studying',
    choices: [
      { image: 'woman-working', nl: 'De vrouw werkt' }, { image: 'woman-studying', nl: 'De vrouw leert' },
      { image: 'woman-sick', nl: 'De vrouw is ziek' }, { image: 'woman-sitting', nl: 'De vrouw zit op de bank' },
    ],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['present-regular', 'zijn'],
    instruction: 'Listen without reading. Which picture is it?',
    nl: 'Bram is moe. Hij slaapt.', en: 'Bram is tired. He is sleeping.', answer: 'man-sleeping',
    choices: [
      { image: 'man-cooking', nl: 'Bram kookt' }, { image: 'man-waiting', nl: 'Bram wacht' },
      { image: 'man-sleeping', nl: 'Bram slaapt' }, { image: 'man-working', nl: 'Bram werkt' },
    ],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['present-regular'],
    instruction: 'Listen. Who is it, and what are they doing?',
    nl: 'Bram en Lotte praten.', en: 'Bram and Lotte are talking.', answer: 'couple-talking',
    choices: [
      { image: 'couple-bench', nl: 'Zij zitten op de bank' }, { image: 'child-playing', nl: 'Het kind speelt' },
      { image: 'couple-talking', nl: 'Zij praten' }, { image: 'people-home', nl: 'Zij wonen hier' },
    ],
  },
  {
    type: 'drill', title: 'Write the verb',
    instruction: 'Type the verb for each picture in its dictionary form, the infinitive — it always ends in -en here.',
    items: [
      { image: 'people-home', answer: 'wonen' },
      { image: 'man-cooking', answer: 'koken' },
      { image: 'man-walking', answer: 'lopen' },
      { image: 'couple-talking', answer: 'praten' },
      { image: 'man-sitting', answer: 'zitten' },
      { image: 'child-playing', answer: 'spelen' },
      { image: 'woman-sleeping', answer: 'slapen' },
      { image: 'man-waiting', answer: 'wachten' },
      { image: 'woman-working', answer: 'werken' },
      { image: 'woman-studying', answer: 'leren' },
    ],
    explanation: 'Note the double t in zitten — it will disappear in a moment — and the single a in praten, which will not stay single.',
  },
  {
    type: 'drill', title: 'The small words', grammar: ['question-word'],
    instruction: 'Type the missing word: in, op, hier, thuis or waar.',
    items: [
      { nl: 'Lotte zit ___ de bank.', en: 'Lotte is sitting on the bench.', answer: 'op' },
      { nl: 'Lotte leert ___.', en: 'Lotte studies at home.', answer: 'thuis' },
      { nl: 'Wij wonen ___.', en: 'We live here.', answer: 'hier' },
      { nl: '___ is Bram?', en: 'Where is Bram?', answer: 'Waar' },
      { nl: 'Bram wacht ___ Lotte.', en: 'Bram is waiting for Lotte.', answer: 'op' },
      { nl: 'Het kind speelt ___ straat.', en: 'The child is playing in the street.', answer: 'op' },
      { nl: 'Wij praten ___ de auto.', en: 'We are talking in the car.', answer: 'in' },
    ],
    explanation: '“Op de bank” (on the bench), “in Leuven”, “in de auto”, “thuis” (at home — no preposition). And two fixed pairs: op straat, wachten op.',
  },
  {
    type: 'drill', title: 'Hear and spell',
    instruction: 'Play each word and type it. Listen for the long vowels: “oo” in wonen, “aa” in slapen, “ee” in spelen.',
    items: [
      { listen: 'wonen' }, { listen: 'slapen' }, { listen: 'zitten' }, { listen: 'koken' },
      { listen: 'spelen' }, { listen: 'praten' }, { listen: 'wachten' }, { listen: 'thuis' },
    ],
    explanation: 'wonen and koken have a long o, slapen and praten a long a, spelen a long e; zitten has a short i, wachten a short a. The spelling shows the difference — the next grammar pages depend on it.',
  },

  // ——— Grammar: the present tense ———
  {
    part: 'Grammar', type: 'grammar', title: 'The present tense: three forms', grammar: ['present-regular', 'subject-pronouns'],
    body: [
      'Almost every Dutch verb works like **werken** (to work). Take the infinitive, remove **-en**, and what is left is the **stem**: werk-en → **werk**.',
      'The stem alone goes with **ik**. The stem **+ t** goes with **jij/je**, **hij**, **zij/ze** (she) and **het** (it). The three plural persons — **wij/we**, **jullie** and **zij/ze** (they) — use the full infinitive.',
      'So a regular verb has only three present-tense forms: *werk, werkt, werken*. Thousands of verbs follow this pattern; once you can do it with ten verbs, you can do it with all of them.',
      '**zij** can mean “she” or “they”. The verb tells you which: *zij werkt* = she works, *zij werken* = they work — just as *zij is* and *zij zijn* did in lesson 2.',
      '**het** means “it”. With **het kind**, **het** is possible when speaking about a child in general: *Het kind speelt. **Het** is blij.* For a particular child, **hij** or **zij** is also natural. The article **het** does not force you to use the pronoun **het** for a person.',
      'Dutch has one present tense where English has two: *ik werk* is both “I work” and “I am working”. Never translate “am working” with *ben*: *ik ben werk* is wrong; *ik werk* is right.',
    ],
    tables: [
      { caption: 'werken — to work (stem: werk)', rows: [
        { nl: 'ik werk', en: 'I work' }, { nl: 'jij werk[t]', en: 'you work' }, { nl: 'hij werk[t]', en: 'he works' },
        { nl: 'zij werk[t]', en: 'she works' }, { nl: 'het werk[t]', en: 'it works' }, { nl: 'wij werk[en]', en: 'we work' },
        { nl: 'jullie werk[en]', en: 'you (plural) work' }, { nl: 'zij werk[en]', en: 'they work' },
      ] },
      { caption: 'Compare zijn — the irregular one', rows: [
        { nl: 'ik ben', en: 'I am' }, { nl: 'jij bent', en: 'you are' }, { nl: 'hij is', en: 'he is' }, { nl: 'wij zijn', en: 'we are' },
      ] },
    ],
    examples: [
      { nl: 'Ik werk thuis.', en: 'I work at home.' },
      { nl: 'Lotte werkt thuis.', en: 'Lotte works at home.' },
      { nl: 'Bram werkt in Brussel.', en: 'Bram works in Brussels.' },
      { nl: 'Zij werkt. Zij werken.', en: 'She works. They work.' },
      { nl: 'Bram en Lotte zijn jong. Zij werken.', en: 'Bram and Lotte are young. They work.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'werken, every person', grammar: ['present-regular', 'subject-pronouns'],
    instruction: 'werken — to work. Type the form for each person. Stem: werk.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'werk' },
      { label: 'jij', gloss: 'you', answer: 'werkt' },
      { label: 'hij', gloss: 'he', answer: 'werkt' },
      { label: 'zij', gloss: 'she', answer: 'werkt' },
      { label: 'het', gloss: 'it', answer: 'werkt' },
      { label: 'wij', gloss: 'we', answer: 'werken' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'werken' },
      { label: 'zij', gloss: 'they', answer: 'werken' },
    ],
    explanation: 'Stem, stem + t, infinitive. “Het werkt” means “it works” — of a machine or a plan.',
  },
  {
    type: 'drill', title: 'werk, werkt or werken?', grammar: ['present-regular', 'subject-pronouns'], choices: ['werk', 'werkt', 'werken'],
    instruction: 'First contact: choose the form. Look at the subject first — it decides everything.',
    items: [
      { nl: 'Ik ___ in Leuven.', answer: 'werk' },
      { nl: 'Lotte ___ thuis.', answer: 'werkt' },
      { nl: 'Wij ___ thuis.', answer: 'werken' },
      { nl: 'Jij ___ in Brussel.', answer: 'werkt' },
      { nl: 'Zij ___ thuis.', en: 'She works at home.', answer: 'werkt' },
      { nl: 'Zij ___ in Antwerpen.', en: 'They work in Antwerp.', answer: 'werken' },
      { nl: 'Bram ___ in Brussel.', answer: 'werkt' },
    ],
    explanation: 'A name is a “hij” or a “zij”: Bram werkt, Lotte werkt. Two names together are a “zij” (they): Bram en Lotte werken.',
  },
  {
    type: 'drill', title: 'Now type it', grammar: ['present-regular', 'niet', 'zijn'],
    instruction: 'Type the right form of the verb in brackets.',
    items: [
      { nl: 'Ik ___ thuis.', cue: 'werken', en: 'I work at home.', answer: 'werk' },
      { nl: 'Hij ___ in Gent.', cue: 'werken', en: 'He works in Ghent.', answer: 'werkt' },
      { nl: 'Zij ___ in Brussel.', cue: 'werken', en: 'They work in Brussels.', answer: 'werken' },
      { nl: 'Lotte is ziek. Zij ___ niet.', cue: 'werken', en: 'Lotte is ill. She is not working.', answer: 'werkt' },
      { nl: 'Jullie ___ niet.', cue: 'werken', en: 'You (plural) are not working.', answer: 'werken' },
    ],
  },

  // ——— Grammar: spelling the stem ———
  {
    type: 'grammar', title: 'Spelling the stem', grammar: ['spelling-stem', 'present-regular'],
    body: [
      'Dutch spelling shows vowel length with one simple rule. At the end of a syllable — an *open* syllable — a single vowel letter already sounds long: **wo**-nen, **sla**-pen, **lo**-pen, **ko**-ken, **spe**-len, **le**-ren, **pra**-ten. But when a consonant closes the syllable, a long vowel needs **two** letters.',
      '**Rule 1 — double the vowel.** Cutting off -en closes the syllable, so to keep the sound the same you double the vowel: wonen → **woon**, slapen → **slaap**, lopen → **loop**, koken → **kook**, spelen → **speel**, leren → **leer**. Writing *won*, *slap*, *kok*, *spel* or *ler* would make the vowel short — a different sound, and wrong. koken, spelen and leren are pure practice of this rule: *ik kook, hij kookt · ik speel, hij speelt · ik leer, hij leert*.',
      '**Rule 2 — one consonant is enough.** In zit-ten the double t is only there to keep the i short in the open spelling. In the stem the syllable is closed anyway, so one t is enough: zitten → **zit**. Never *zitt*.',
      '**Rule 3 — a stem that already ends in -t takes no extra t.** A Dutch verb form never ends in -tt, so jij and hij look exactly like ik: *ik zit, jij zit, hij zit*. **praten** and **wachten** are the next two examples, and they are worth learning as a pair with zitten: *ik praat, jij praat, hij praat* (never *praatt*) · *ik wacht, jij wacht, hij wacht* (never *wachtt*).',
      'praten needs **two** rules: pra-ten → **praat** doubles the a (rule 1), and because praat ends in t, hij praat gets nothing more (rule 3). **werken** and **wachten** keep their stem as it is: the vowel is short and two consonants follow, so the stem is simply *werk*, *wacht*. (wacht then follows rule 3: *hij wacht*.)',
      'The plural never changes: it is the infinitive exactly as you find it in the dictionary — *wij wonen, wij koken, wij spelen, wij zitten, wij praten, wij wachten*. The doubling and the single t belong only to ik, jij and hij/zij/het.',
    ],
    tables: [
      { caption: 'From infinitive to stem', rows: [
        { nl: 'ik woon', en: 'wonen: wo-nen → woon (one o becomes two)' },
        { nl: 'ik kook', en: 'koken: ko-ken → kook (one o becomes two)' },
        { nl: 'ik loop', en: 'lopen: lo-pen → loop (one o becomes two)' },
        { nl: 'ik slaap', en: 'slapen: sla-pen → slaap (one a becomes two)' },
        { nl: 'ik speel', en: 'spelen: spe-len → speel (one e becomes two)' },
        { nl: 'ik leer', en: 'leren: le-ren → leer (one e becomes two)' },
        { nl: 'ik praat', en: 'praten: pra-ten → praat (one a becomes two)' },
        { nl: 'ik zit', en: 'zitten: zit-ten → zit (tt becomes t)' },
        { nl: 'ik werk', en: 'werken: werk-en → werk (no change)' },
        { nl: 'ik wacht', en: 'wachten: wacht-en → wacht (no change)' },
      ] },
      { caption: 'A stem ending in t: no second t', rows: [
        { nl: 'hij zit', en: 'he sits' }, { nl: 'hij praat', en: 'he talks' }, { nl: 'hij wacht', en: 'he waits' },
        { nl: 'jij zit', en: 'you sit' }, { nl: 'jij praat', en: 'you talk' }, { nl: 'jij wacht', en: 'you wait' },
        { nl: 'wij zitt[en]', en: 'we sit' }, { nl: 'wij prat[en]', en: 'we talk' }, { nl: 'wij wacht[en]', en: 'we wait' },
      ] },
    ],
    examples: [
      { nl: 'Bram slaapt. Lotte leert.', en: 'Bram is sleeping. Lotte is studying.' },
      { nl: 'Bram kookt thuis.', en: 'Bram cooks at home.' },
      { nl: 'Het kind speelt op straat.', en: 'The child is playing in the street.' },
      { nl: 'Hij zit op de bank en hij praat.', en: 'He is sitting on the bench and he is talking.' },
      { nl: 'Jij wacht op Lotte. Wij wachten ook.', en: 'You are waiting for Lotte. We are waiting too.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'wonen, every person', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'wonen — to live (somewhere). Stem: woon. Type each form.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'woon' },
      { label: 'jij', gloss: 'you', answer: 'woont' },
      { label: 'hij', gloss: 'he', answer: 'woont' },
      { label: 'zij', gloss: 'she', answer: 'woont' },
      { label: 'wij', gloss: 'we', answer: 'wonen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'wonen' },
      { label: 'zij', gloss: 'they', answer: 'wonen' },
    ],
    explanation: 'Two o’s in woon and woont, one o in wonen: wo-nen is an open syllable.',
  },
  {
    type: 'drill', layout: 'table', title: 'koken, every person', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'koken — to cook. It works exactly like wonen. You find the stem this time.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'kook' },
      { label: 'jij', gloss: 'you', answer: 'kookt' },
      { label: 'hij', gloss: 'he', answer: 'kookt' },
      { label: 'zij', gloss: 'she', answer: 'kookt' },
      { label: 'wij', gloss: 'we', answer: 'koken' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'koken' },
      { label: 'zij', gloss: 'they', answer: 'koken' },
    ],
    explanation: 'kook, kookt, koken — two o’s where the syllable is closed, one where it is open. “Kokt” does not exist.',
  },
  {
    type: 'drill', layout: 'table', title: 'slapen, every person', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'slapen — to sleep. Stem: slaap. Type each form.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'slaap' },
      { label: 'jij', gloss: 'you', answer: 'slaapt' },
      { label: 'hij', gloss: 'he', answer: 'slaapt' },
      { label: 'zij', gloss: 'she', answer: 'slaapt' },
      { label: 'wij', gloss: 'we', answer: 'slapen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'slapen' },
      { label: 'zij', gloss: 'they', answer: 'slapen' },
    ],
    explanation: 'slaap, slaapt — never “slapt”. Back to one a in slapen.',
  },
  {
    type: 'drill', layout: 'table', title: 'spelen, every person', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns', 'hij-het-things'],
    instruction: 'spelen — to play. The e doubles, just as the a in slapen. Note the het row: het kind → het speelt.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'speel' },
      { label: 'jij', gloss: 'you', answer: 'speelt' },
      { label: 'hij', gloss: 'he', answer: 'speelt' },
      { label: 'het', gloss: 'it (the child)', answer: 'speelt' },
      { label: 'wij', gloss: 'we', answer: 'spelen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'spelen' },
      { label: 'zij', gloss: 'they', answer: 'spelen' },
    ],
    explanation: 'speel, speelt, spelen. “Spelt” is a different word altogether (it spells) — the double e is not optional.',
  },
  {
    type: 'drill', layout: 'table', title: 'lopen, shuffled', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'lopen — to walk. Stem: loop. The persons are out of order now: read the pronoun before you type.',
    items: [
      { label: 'hij', gloss: 'he', answer: 'loopt' },
      { label: 'wij', gloss: 'we', answer: 'lopen' },
      { label: 'ik', gloss: 'I', answer: 'loop' },
      { label: 'zij', gloss: 'they', answer: 'lopen' },
      { label: 'jij', gloss: 'you', answer: 'loopt' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'lopen' },
      { label: 'zij', gloss: 'she', answer: 'loopt' },
    ],
    explanation: 'loop, loopt, lopen. “Lopt” does not exist.',
  },
  {
    type: 'drill', layout: 'table', title: 'leren, shuffled', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'leren — to learn, to study. Out of order, and no stem given: work it out from le-ren.',
    items: [
      { label: 'zij', gloss: 'she', answer: 'leert' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'leren' },
      { label: 'ik', gloss: 'I', answer: 'leer' },
      { label: 'wij', gloss: 'we', answer: 'leren' },
      { label: 'jij', gloss: 'you', answer: 'leert' },
      { label: 'zij', gloss: 'they', answer: 'leren' },
      { label: 'hij', gloss: 'he', answer: 'leert' },
    ],
    explanation: 'leer, leert, leren — two e’s where the syllable is closed, one in the open le-ren. “Hij lert” does not exist.',
  },
  {
    type: 'drill', layout: 'table', title: 'zitten, shuffled', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'zitten — to sit. Stem: zit. Out of order again. Careful with jij and hij.',
    items: [
      { label: 'jij', gloss: 'you', answer: 'zit' },
      { label: 'zij', gloss: 'they', answer: 'zitten' },
      { label: 'ik', gloss: 'I', answer: 'zit' },
      { label: 'hij', gloss: 'he', answer: 'zit' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'zitten' },
      { label: 'zij', gloss: 'she', answer: 'zit' },
      { label: 'wij', gloss: 'we', answer: 'zitten' },
    ],
    explanation: 'zit, zit, zit: the stem already ends in t, so jij and hij add nothing. Never “zitt”. The double t only comes back in zitten.',
  },
  {
    type: 'drill', layout: 'table', title: 'praten, shuffled', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'praten — to talk. Two rules at once: double the a, then add no t, because the stem already ends in one.',
    items: [
      { label: 'hij', gloss: 'he', answer: 'praat' },
      { label: 'ik', gloss: 'I', answer: 'praat' },
      { label: 'wij', gloss: 'we', answer: 'praten' },
      { label: 'jij', gloss: 'you', answer: 'praat' },
      { label: 'zij', gloss: 'they', answer: 'praten' },
      { label: 'zij', gloss: 'she', answer: 'praat' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'praten' },
    ],
    explanation: 'praat for ik, jij, hij and zij (she); praten for the plural. Never “praatt”, and never “praaten” — the open syllable pra-ten needs only one a.',
  },
  {
    type: 'drill', layout: 'table', title: 'wachten, shuffled', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'wachten — to wait. Short a, stem ends in t: which rule applies, and which does not?',
    items: [
      { label: 'jij', gloss: 'you', answer: 'wacht' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'wachten' },
      { label: 'hij', gloss: 'he', answer: 'wacht' },
      { label: 'ik', gloss: 'I', answer: 'wacht' },
      { label: 'zij', gloss: 'they', answer: 'wachten' },
      { label: 'wij', gloss: 'we', answer: 'wachten' },
      { label: 'zij', gloss: 'she', answer: 'wacht' },
    ],
    explanation: 'Only rule 3: the stem wacht already ends in t, so jij wacht, hij wacht. Nothing doubles, because the a is short.',
  },
  {
    type: 'drill', title: 'Double the vowel', grammar: ['spelling-stem', 'present-regular', 'niet', 'zijn'],
    instruction: 'wonen, slapen, lopen, koken, spelen, leren — all six double their vowel. Type the form of the verb in brackets.',
    items: [
      { nl: 'Bram ___ thuis.', cue: 'koken', en: 'Bram cooks at home.', answer: 'kookt' },
      { nl: 'Het kind ___ op straat.', cue: 'spelen', en: 'The child is playing in the street.', answer: 'speelt' },
      { nl: 'Lotte is ziek. Zij ___ thuis.', cue: 'slapen', en: 'Lotte is ill. She is sleeping at home.', answer: 'slaapt' },
      { nl: 'Ik ___ thuis.', cue: 'leren', en: 'I study at home.', answer: 'leer' },
      { nl: 'Wij ___ thuis.', cue: 'koken', en: 'We cook at home.', answer: 'koken' },
      { nl: 'De man is oud. Hij ___ hier.', cue: 'lopen', en: 'The man is old. He walks here.', answer: 'loopt' },
      { nl: 'Ik ___ niet; ik ben moe.', cue: 'koken', en: 'I am not cooking; I am tired.', answer: 'kook' },
      { nl: 'Jullie ___ niet.', cue: 'leren', en: 'You (plural) are not studying.', answer: 'leren' },
      { nl: 'Het kind is blij. Het ___.', cue: 'spelen', en: 'The child is happy. It is playing.', answer: 'speelt' },
      { nl: 'Zij ___ thuis.', cue: 'leren', en: 'She studies at home.', answer: 'leert' },
    ],
    explanation: 'kookt, speelt, slaapt, woont, leert, loopt — two vowel letters wherever the syllable is closed. koken, leren, spelen in the plural — one letter again.',
  },
  {
    type: 'drill', title: 'Already a t', grammar: ['spelling-stem', 'present-regular', 'niet', 'hij-het-things'],
    instruction: 'zitten, praten and wachten, with werken as the contrast. When the stem already ends in t, jij and hij add nothing.',
    items: [
      { nl: 'Bram ___ op de bank.', cue: 'zitten', en: 'Bram is sitting on the bench.', answer: 'zit' },
      { nl: 'Lotte ___ niet.', cue: 'praten', en: 'Lotte is not talking.', answer: 'praat' },
      { nl: 'Jij ___ op Lotte.', cue: 'wachten', en: 'You are waiting for Lotte.', answer: 'wacht' },
      { nl: 'Hij ___ thuis.', cue: 'werken', en: 'He works at home.', answer: 'werkt' },
      { nl: 'Wij ___ op de bank.', cue: 'praten', en: 'We are talking on the bench.', answer: 'praten' },
      { nl: 'Hij ___ op het kind.', cue: 'wachten', en: 'He is waiting for the child.', answer: 'wacht' },
      { nl: 'Het kind is moe. Het ___ niet.', cue: 'praten', en: 'The child is tired. It is not talking.', answer: 'praat' },
      { nl: 'Lotte ___ in de auto.', cue: 'wachten', en: 'Lotte is waiting in the car.', answer: 'wacht' },
      { nl: 'Jij ___ thuis.', cue: 'werken', en: 'You work at home.', answer: 'werkt' },
      { nl: 'Jullie ___ hier.', cue: 'wachten', en: 'You (plural) are waiting here.', answer: 'wachten' },
    ],
    explanation: 'zit, praat, wacht — but werkt, because werk does not end in t. And the plural is the infinitive: zitten, praten, wachten.',
  },
  {
    type: 'drill', title: 'Change the subject', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns', 'zijn'],
    instruction: 'Rewrite the sentence with the new subject. Change the subject and its verb; keep the rest of the sentence.',
    items: [
      { nl: 'Ik woon in Leuven.', task: 'Change ik to hij', answer: 'Hij woont in Leuven.' },
      { nl: 'Hij slaapt.', task: 'Change hij to wij', answer: 'Wij slapen.' },
      { nl: 'Wij zitten op de bank.', task: 'Change wij to Lotte', answer: 'Lotte zit op de bank.' },
      { nl: 'Ik ben blij en ik kook.', task: 'Change ik to hij', answer: 'Hij is blij en hij kookt.' },
      { nl: 'Het kind speelt.', task: 'Change het kind to jullie', answer: 'Jullie spelen.' },
      { nl: 'Zij wachten op Bram.', task: 'Change zij (they) to zij (she)', answer: 'Zij wacht op Bram.' },
      { nl: 'Wij praten niet.', task: 'Change wij to hij', answer: 'Hij praat niet.' },
      { nl: 'Ik leer thuis.', task: 'Change ik to jullie', answer: 'Jullie leren thuis.' },
    ],
    explanation: 'With zijn the whole verb changes (ben → is); with a regular verb only the ending changes (kook → kookt) — and with praten, ik praat and hij praat are even identical.',
  },

  // ——— Grammar: questions ———
  {
    type: 'grammar', title: 'Questions: jij loses its -t', grammar: ['present-regular', 'inversion', 'yes-no-question'],
    body: [
      'In lesson 2 you made a question by putting the verb first: *Jij bent moe* → ***Ben** jij moe?* That works for every verb: *Bram werkt thuis* → ***Werkt** Bram thuis?* There is no helper word like English “do”.',
      'And the same exception applies. When **jij/je** comes straight **after** the verb, the verb loses its **-t**: *Jij woont hier* → ***Woon** jij hier?* · *Je kookt thuis* → ***Kook** je thuis?* It is exactly the rule behind *ben jij*: the -t of *bent* disappears in the same way.',
      'This happens **only** with jij/je. With hij, zij, het and names the -t stays: ***Woont** hij hier? **Werkt** Lotte thuis? **Speelt** het kind?*',
      'With zitten, praten and wachten you cannot see it at all, because their -t belongs to the stem and never goes: *jij zit* → *zit jij*, *jij praat* → *praat jij*, *jij wacht* → *wacht jij*.',
      'Plural questions simply use the infinitive: ***Wonen** jullie hier? **Zitten** zij op de bank?*',
      'Answer with ja or nee and the normal statement order: *Woon jij hier? — Ja, ik woon hier.*',
    ],
    tables: [
      { caption: 'jij/je after the verb: the -t goes', rows: [
        { nl: 'Jij woon[t] hier.', en: 'You live here.' }, { nl: 'Woon jij hier?', en: 'Do you live here?' },
        { nl: 'Jij leer[t] thuis.', en: 'You study at home.' }, { nl: 'Leer jij thuis?', en: 'Do you study at home?' },
        { nl: 'Jij ben[t] moe.', en: 'You are tired.' }, { nl: 'Ben jij moe?', en: 'Are you tired?' },
      ] },
      { caption: 'hij, zij, a name: the -t stays', rows: [
        { nl: 'Hij woon[t] hier.', en: 'He lives here.' }, { nl: 'Woon[t] hij hier?', en: 'Does he live here?' },
        { nl: 'Lotte werk[t] thuis.', en: 'Lotte works at home.' }, { nl: 'Werk[t] Lotte thuis?', en: 'Does Lotte work at home?' },
      ] },
    ],
    examples: [
      { nl: 'Werk je thuis? — Ja, ik werk thuis.', en: 'Do you work at home? — Yes, I work at home.' },
      { nl: 'Kook jij? — Nee, Bram kookt.', en: 'Are you cooking? — No, Bram is cooking.' },
      { nl: 'Slaapt Bram? — Ja, hij slaapt.', en: 'Is Bram sleeping? — Yes, he is sleeping.' },
      { nl: 'Zitten jullie op de bank? — Ja, wij zitten op de bank.', en: 'Are you sitting on the bench? — Yes, we are sitting on the bench.' },
      { nl: 'Wacht jij op Lotte? — Nee, ik wacht op het kind.', en: 'Are you waiting for Lotte? — No, I am waiting for the child.' },
    ],
  },
  {
    type: 'drill', title: 'With or without -t?', grammar: ['inversion', 'present-regular', 'yes-no-question'],
    instruction: 'First contact: choose the verb. Who comes after it — jij/je, or someone else?',
    items: [
      { nl: '___ jij thuis?', en: 'Do you work at home?', choices: ['Werk', 'Werkt'], answer: 'Werk' },
      { nl: '___ hij hier?', en: 'Does he live here?', choices: ['Woon', 'Woont'], answer: 'Woont' },
      { nl: '___ je thuis?', en: 'Do you cook at home?', choices: ['Kook', 'Kookt'], answer: 'Kook' },
      { nl: '___ het kind?', en: 'Is the child playing?', choices: ['Speel', 'Speelt'], answer: 'Speelt' },
      { nl: '___ jij?', en: 'Are you sleeping?', choices: ['Slaap', 'Slaapt'], answer: 'Slaap' },
      { nl: '___ Lotte thuis?', en: 'Does Lotte study at home?', choices: ['Leer', 'Leert'], answer: 'Leert' },
      { nl: '___ jij thuis?', en: 'Do you study at home?', choices: ['Leer', 'Leert'], answer: 'Leer' },
      { nl: '___ jullie op de bank?', en: 'Are you (plural) sitting on the bench?', choices: ['Zit', 'Zitten'], answer: 'Zitten' },
    ],
    explanation: 'Only jij/je right after the verb removes the -t. Hij, zij, het kind, Bram and Lotte keep it.',
  },
  {
    type: 'drill', title: 'Make it a question', grammar: ['inversion', 'yes-no-question', 'present-regular', 'zijn'], task: 'Make it a question',
    instruction: 'Rewrite as a yes/no question: verb first. If jij/je follows the verb, drop the -t — unless the stem itself ends in t.',
    items: [
      { nl: 'Jij woont in Leuven.', answer: 'Woon jij in Leuven?' },
      { nl: 'Bram kookt thuis.', answer: 'Kookt Bram thuis?' },
      { nl: 'Je werkt thuis.', answer: 'Werk je thuis?' },
      { nl: 'Hij slaapt.', answer: 'Slaapt hij?' },
      { nl: 'Jij speelt op straat.', answer: 'Speel jij op straat?' },
      { nl: 'Jij wacht op Lotte.', answer: 'Wacht jij op Lotte?' },
      { nl: 'Jij leert thuis.', answer: 'Leer jij thuis?' },
      { nl: 'Jij bent ziek.', answer: 'Ben jij ziek?' },
      { nl: 'Het kind is lief.', answer: 'Is het kind lief?' },
    ],
    explanation: 'woont → woon jij, speelt → speel jij, bent → ben jij: one rule. wacht jij keeps its t — it is part of the stem. With hij, Bram and het kind nothing is lost.',
  },
  {
    type: 'arrange', title: 'Build the question', grammar: ['inversion', 'present-regular'],
    instruction: 'Build: “Do you cook at home too?” Two words are left over.',
    nl: 'Kook jij ook thuis?', en: 'Do you cook at home too?', image: 'man-cooking', distractors: ['kookt', 'in'],
  },

  // ——— Grammar: question words ———
  {
    type: 'grammar', title: 'Waar and wat: question words', grammar: ['question-word', 'present-regular', 'hij-het-things'],
    body: [
      '**Waar** (where) and **wat** (what) open a question. After the question word comes the **verb**, then the **subject** — the same order as a yes/no question, with one word in front: ***Waar** woont Bram?*',
      'Because jij still comes after the verb, it still loses its -t: *Waar **woon** jij?* — never *waar woont jij*. The question word changes nothing about that rule.',
      'A waar-question cannot be answered with ja or nee; you answer with a place. **in** a town, a building or a car (*in Leuven, in het huis, in de auto*), **op** a surface such as a bench (*op de bank*), and **thuis** on its own — “at home” needs no preposition. **hier** means “here”. “Op straat” (out in the street) is fixed, without de.',
      '**wat** you already know from *Wat is dit?* It works the same way: question word, verb, subject.',
      'Remember the examples from lesson 2: *Waar is de auto? **Hij** is hier. Waar is het huis? **Het** is in Leuven.* Masculine de-words use **hij**; het-words for things use **het**. For **het kind**, **het**, **hij** or **zij** can be possible, depending on how you refer to the child.',
    ],
    tables: [
      { caption: 'Question word + verb + subject', rows: [
        { nl: 'Waar woon jij?', en: 'Where do you live?' }, { nl: 'Waar woont Bram?', en: 'Where does Bram live?' },
        { nl: 'Waar werkt Lotte?', en: 'Where does Lotte work?' }, { nl: 'Waar speelt het kind?', en: 'Where is the child playing?' },
        { nl: 'Waar zitten jullie?', en: 'Where are you (plural) sitting?' }, { nl: 'Wat is dit?', en: 'What is this?' },
      ] },
    ],
    examples: [
      { nl: 'Waar woon jij? — Ik woon in Leuven.', en: 'Where do you live? — I live in Leuven.' },
      { nl: 'Waar werkt Bram? — Hij werkt in Brussel.', en: 'Where does Bram work? — He works in Brussels.' },
      { nl: 'Waar leert Lotte? — Zij leert thuis.', en: 'Where does Lotte study? — She studies at home.' },
      { nl: 'Waar zit de man? — Hij zit op de bank.', en: 'Where is the man sitting? — He is sitting on the bench.' },
      { nl: 'Waar is de auto? — Hij is hier.', en: 'Where is the car? — It is here.' },
      { nl: 'Wat is dit? — Dit is een raam.', en: 'What is this? — This is a window.' },
    ],
  },
  {
    type: 'drill', title: 'Ask with waar', grammar: ['question-word', 'inversion', 'present-regular', 'hij-het-things'], task: 'Ask with waar',
    instruction: 'Ask the question that this sentence answers. Start with “Waar”, then the verb, then the subject — and drop the place.',
    items: [
      { nl: 'Bram werkt in Brussel.', answer: 'Waar werkt Bram?' },
      { nl: 'Jij woont in Leuven.', answer: 'Waar woon jij?' },
      { nl: 'Het kind speelt op straat.', answer: 'Waar speelt het kind?' },
      { nl: 'Je leert thuis.', answer: 'Waar leer je?' },
      { nl: 'De man loopt hier.', answer: 'Waar loopt de man?' },
      { nl: 'Het huis is in Leuven.', answer: 'Waar is het huis?' },
      { nl: 'Jij wacht hier.', answer: 'Waar wacht jij?' },
      { nl: 'Bram en Lotte praten op de bank.', answer: 'Waar praten Bram en Lotte?' },
    ],
    explanation: 'Waar woon jij, waar leer je — jij/je after the verb, so no -t. Waar wacht jij — the t stays, it is the stem. Waar loopt de man, waar speelt het kind — the -t stays.',
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'grammar', title: 'niet with every verb', grammar: ['niet', 'present-regular', 'geen'],
    body: [
      'In lesson 2, **niet** came straight after *zijn*: *Ik ben niet moe.* With every other verb it is the same when nothing else follows: *Bram werkt niet. Lotte slaapt niet.*',
      'When a place follows, niet comes **before** the place: *Ik werk niet thuis. Bram woont niet in Gent. Het kind speelt niet op straat.*',
      'One common exception: **hier** comes before niet. *Ik woon hier niet.* (“Ik woon niet hier” is only used to contrast: not here, but somewhere else.)',
      'In a question niet follows the subject: *Slaap jij niet? Werkt Bram niet?*',
      'And do not forget **geen** from lesson 1. Geen replaces *een* before a noun: *Dit is een deur* → *Dit is geen deur.* With a verb, an adjective or a place you use niet.',
    ],
    examples: [
      { nl: 'Bram werkt niet. Hij slaapt.', en: 'Bram is not working. He is sleeping.' },
      { nl: 'Lotte is ziek. Zij werkt niet.', en: 'Lotte is ill. She is not working.' },
      { nl: 'Ik kook niet thuis.', en: 'I do not cook at home.' },
      { nl: 'Wij wonen niet in Brussel.', en: 'We do not live in Brussels.' },
      { nl: 'Hij woont hier niet.', en: 'He does not live here.' },
      { nl: 'Dit is geen deur. Dit is een raam.', en: 'This is not a door. This is a window.' },
    ],
  },
  {
    type: 'drill', title: 'Make it negative', grammar: ['niet', 'geen', 'present-regular', 'zijn', 'dit-is'], task: 'Make it negative',
    instruction: 'Add niet in the right place — or use geen if the sentence has “een”.',
    items: [
      { nl: 'Bram werkt.', answer: 'Bram werkt niet.' },
      { nl: 'Lotte leert.', answer: 'Lotte leert niet.' },
      { nl: 'Ik kook thuis.', answer: 'Ik kook niet thuis.' },
      { nl: 'Ik woon hier.', answer: 'Ik woon hier niet.' },
      { nl: 'Lotte is ziek.', answer: 'Lotte is niet ziek.' },
      { nl: 'Dit is een boom.', answer: 'Dit is geen boom.' },
      { nl: 'Wacht jij?', answer: 'Wacht jij niet?' },
      { nl: 'De auto is nieuw.', answer: 'De auto is niet nieuw.' },
      { nl: 'Het kind speelt op straat.', answer: 'Het kind speelt niet op straat.' },
      { nl: 'Het raam is klein.', answer: 'Het raam is niet klein.' },
    ],
    explanation: 'niet after the verb, before a place (niet thuis, niet op straat, niet op de bank), but after hier. geen instead of een.',
  },
  {
    type: 'arrange', title: 'Ill at home', grammar: ['niet', 'present-regular', 'zijn'],
    instruction: 'Build: “Lotte is ill. She is not working.” Two tiles are traps.',
    nl: 'Lotte is ziek. Zij werkt niet.', en: 'Lotte is ill. She is not working.', image: 'woman-sick', distractors: ['geen', 'werk'],
  },
  {
    type: 'drill', title: 'hij, het, zij — and where?', grammar: ['hij-het-things', 'question-word', 'de-het', 'zijn', 'dit-is'],
    instruction: 'Type the missing pronoun. Use hij for boom and auto, het for huis and raam, and zij for Lotte. For the child, het, hij or zij is possible.',
    items: [
      { nl: 'Is de auto nieuw? Ja, ___ is nieuw.', en: 'Is the car new? Yes, it is new.', answer: 'hij' },
      { nl: 'Is het raam groot? Nee, ___ is klein.', en: 'Is the window big? No, it is small.', answer: 'het' },
      { nl: 'Waar is het kind? ___ speelt op straat.', en: 'Where is the child? It is playing in the street.', answer: 'Het', accept: ['Hij', 'Zij'] },
      { nl: 'Is de boom oud? Ja, ___ is oud.', en: 'Is the tree old? Yes, it is old.', answer: 'hij' },
      { nl: 'Waar is de vrouw? ___ is thuis; zij is ziek.', en: 'Where is the woman? She is at home; she is ill.', answer: 'Zij' },
      { nl: 'Is het kind lief? Ja, ___ is lief.', en: 'Is the child sweet? Yes, it is sweet.', answer: 'het', accept: ['hij', 'zij'] },
      { nl: 'Wat is dit? ___ is een deur.', en: 'What is this? This is a door.', answer: 'Dit', accept: ['Het'] },
      { nl: 'Is het huis klein? Nee, ___ is groot.', en: 'Is the house small? No, it is big.', answer: 'het' },
    ],
    explanation: 'de boom, de auto → hij; het huis, het raam → het. For het kind, het is possible, and hij or zij can refer to the particular child.',
  },
  {
    type: 'drill', title: 'Answer in a full sentence', grammar: ['yes-no-question', 'present-regular', 'zijn', 'niet', 'subject-pronouns'], task: 'Answer in full',
    instruction: 'Look at the picture and answer with a complete sentence. Use a pronoun (hij, zij, het, wij) for the person.',
    items: [
      { image: 'woman-sick', nl: 'Werkt Lotte?', answer: 'Nee, zij is ziek.', accept: ['Nee, Lotte is ziek.', 'Nee, zij werkt niet.', 'Nee, Lotte werkt niet.', 'Nee, zij werkt niet. Zij is ziek.', 'Nee, zij slaapt.', 'Nee, Lotte slaapt.'] },
      { image: 'man-happy', nl: 'Is Bram moe?', answer: 'Nee, hij is blij.', accept: ['Nee, Bram is blij.', 'Nee, hij is niet moe.', 'Nee, Bram is niet moe.', 'Nee, hij is niet moe. Hij is blij.'] },
      { image: 'couple-talking', nl: 'Slapen Bram en Lotte?', answer: 'Nee, zij praten.', accept: ['Nee, Bram en Lotte praten.', 'Nee, zij slapen niet.', 'Nee, Bram en Lotte slapen niet.', 'Nee, zij slapen niet. Zij praten.'] },
      { image: 'people-home', nl: 'Bram en Lotte, wonen jullie hier?', task: 'Answer as Bram and Lotte', answer: 'Ja, wij wonen hier.' },
      { image: 'child-playing', nl: 'Slaapt het kind?', answer: 'Nee, het speelt.', accept: ['Nee, het kind speelt.', 'Nee, het slaapt niet.', 'Nee, het kind slaapt niet.', 'Nee, het slaapt niet. Het speelt.', 'Nee, hij speelt.', 'Nee, zij speelt.', 'Nee, hij slaapt niet.', 'Nee, zij slaapt niet.'] },
      { image: 'man-cooking', nl: 'Slaapt Bram?', answer: 'Nee, hij kookt.', accept: ['Nee, Bram kookt.', 'Nee, hij slaapt niet.', 'Nee, Bram slaapt niet.', 'Nee, hij slaapt niet. Hij kookt.'] },
      { image: 'woman-studying', nl: 'Slaapt Lotte?', answer: 'Nee, zij leert.', accept: ['Nee, Lotte leert.', 'Nee, zij slaapt niet.', 'Nee, Lotte slaapt niet.', 'Nee, zij slaapt niet. Zij leert.'] },
      { image: 'old-man', nl: 'Is de man jong?', answer: 'Nee, hij is oud.', accept: ['Nee, de man is oud.', 'Nee, hij is niet jong.', 'Nee, de man is niet jong.'] },
    ],
  },
  {
    type: 'drill', title: 'Every verb so far', grammar: ['present-regular', 'spelling-stem', 'zijn', 'inversion', 'question-word'],
    instruction: 'zijn and all ten new verbs, mixed. Type the form of the verb in brackets.',
    items: [
      { nl: 'Ik ___ moe.', cue: 'zijn', en: 'I am tired.', answer: 'ben' },
      { nl: '___ jij thuis?', cue: 'koken', en: 'Do you cook at home?', answer: 'Kook' },
      { nl: '___ jij blij?', cue: 'zijn', en: 'Are you happy?', answer: 'Ben' },
      { nl: 'De man ___ op de bank.', cue: 'zitten', en: 'The man is sitting on the bench.', answer: 'zit' },
      { nl: 'Jullie ___ jong.', cue: 'zijn', en: 'You (plural) are young.', answer: 'zijn' },
      { nl: 'Lotte ___ niet ziek.', cue: 'zijn', en: 'Lotte is not ill.', answer: 'is' },
      { nl: 'Zij ___ thuis.', cue: 'leren', en: 'She studies at home.', answer: 'leert' },
      { nl: 'Waar ___ jullie?', cue: 'wachten', en: 'Where are you (plural) waiting?', answer: 'wachten' },
      { nl: 'Hij ___ niet.', cue: 'praten', en: 'He is not talking.', answer: 'praat' },
      { nl: '___ jij op Bram?', cue: 'wachten', en: 'Are you waiting for Bram?', answer: 'Wacht' },
      { nl: 'Het kind ___ klein.', cue: 'zijn', en: 'The child is small.', answer: 'is' },
      { nl: 'Jij ___ in de straat.', cue: 'lopen', en: 'You are walking in the street.', answer: 'loopt' },
    ],
    explanation: 'zijn is the only irregular verb so far: ben, bent, is, zijn. The other ten all follow stem / stem + t / infinitive — with the vowel doubled or the t already there.',
  },
  {
    type: 'arrange', title: 'Two sentences, two verbs', grammar: ['zijn', 'present-regular', 'hij-het-things'],
    instruction: 'Build: “The child is happy. It is playing.” Two tiles are traps.',
    nl: 'Het kind is blij. Het speelt.', en: 'The child is happy. It is playing.', image: 'child-playing', distractors: ['spelen', 'speel'],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'De man op de bank', image: 'neighbourhood', grammar: ['present-regular', 'question-word', 'zijn', 'niet', 'inversion'],
    instruction: 'Bram and Lotte meet a neighbour. Read, listen to every line, then read it again without the English.',
    lines: [
      { nl: 'Bram en Lotte lopen in de straat. Een kind speelt hier; het is blij.', en: 'Bram and Lotte are walking in the street. A child is playing here; it is happy.', image: 'child-playing' },
      { nl: 'Een man zit op de bank. Hij is oud.', en: 'A man is sitting on the bench. He is old.', image: 'old-man' },
      { speaker: 'De man', nl: 'Jullie zijn jong! Wonen jullie hier?', en: 'You are young! Do you live here?', image: 'people-home' },
      { speaker: 'Lotte', nl: 'Ja, wij wonen hier in Leuven. Dit is het huis.', en: 'Yes, we live here in Leuven. This is the house.', image: 'house' },
      { speaker: 'De man', nl: 'Het huis is groot en mooi! Werken jullie in Leuven?', en: 'The house is big and beautiful! Do you work in Leuven?', image: 'house' },
      { speaker: 'Bram', nl: 'Nee, ik werk niet in Leuven. Ik werk in Brussel.', en: 'No, I don’t work in Leuven. I work in Brussels.', image: 'man-working' },
      { speaker: 'Lotte', nl: 'En ik werk thuis. Ik leer ook thuis.', en: 'And I work at home. I study at home too.', image: 'woman-studying' },
      { speaker: 'De man', nl: 'En jij? Ben jij moe?', en: 'And you? Are you tired?', image: 'man-tired' },
      { speaker: 'Bram', nl: 'Ja, ik ben moe. Ik werk in Brussel en ik kook ook.', en: 'Yes, I am tired. I work in Brussels and I cook too.', image: 'man-cooking' },
      { speaker: 'Lotte', nl: 'En jij? Waar woon jij?', en: 'And you? Where do you live?', image: 'old-man' },
      { speaker: 'De man', nl: 'Ik woon hier ook. Ik werk niet; ik ben oud. Ik zit hier en ik wacht op het kind. Het is lief!', en: 'I live here too. I don’t work; I’m old. I sit here and wait for the child. It is sweet!', image: 'old-man' },
      { nl: 'Bram en Lotte zitten ook op de bank. Zij praten, en het kind speelt.', en: 'Bram and Lotte sit on the bench too. They talk, and the child plays.', image: 'couple-bench' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'question-word', 'present-regular', 'zijn', 'niet', 'subject-pronouns'],
    instruction: 'Questions about the conversation, without looking back. First ja or nee; then answer in a complete sentence, starting with a pronoun: hij, zij, het.',
    items: [
      { nl: 'Wonen Bram en Lotte hier?', choices: ['Ja', 'Nee'], answer: 'Ja' },
      { nl: 'Werkt Bram in Leuven?', choices: ['Ja', 'Nee'], answer: 'Nee' },
      { nl: 'Kookt Bram?', choices: ['Ja', 'Nee'], answer: 'Ja' },
      { nl: 'Waar wonen Bram en Lotte?', task: 'Answer in full', answer: 'Zij wonen in Leuven.', accept: ['Bram en Lotte wonen in Leuven.', 'Zij wonen hier.', 'Zij wonen hier in Leuven.', 'Bram en Lotte wonen hier in Leuven.'] },
      { nl: 'Waar leert Lotte?', task: 'Answer in full', answer: 'Zij leert thuis.', accept: ['Lotte leert thuis.', 'Zij leert ook thuis.'] },
      { nl: 'Is het huis mooi?', task: 'Answer in full', answer: 'Ja, het is mooi.', accept: ['Ja, het huis is mooi.'] },
      { nl: 'Wacht de man op Bram?', task: 'Answer in full', answer: 'Nee, hij wacht op het kind.', accept: ['Nee, de man wacht op het kind.'] },
      { nl: 'Is het kind lief?', task: 'Answer in full', answer: 'Ja, het is lief.', accept: ['Ja, het kind is lief.', 'Ja, hij is lief.', 'Ja, zij is lief.'] },
      { nl: 'Praten Bram en Lotte?', task: 'Answer in full', answer: 'Ja, zij praten.', accept: ['Ja, Bram en Lotte praten.', 'Ja, zij praten op de bank.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['present-regular', 'spelling-stem', 'question-word', 'niet'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'Waar woon jij?' },
      { listen: 'Het kind speelt op straat.' },
      { listen: 'Lotte is ziek; zij slaapt.' },
      { listen: 'Wacht jij ook hier?' },
      { listen: 'Hij praat niet; hij is moe.' },
      { listen: 'Kook jij? Nee, ik leer.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['present-regular', 'question-word', 'inversion', 'zijn', 'dit-is', 'de-het', 'hij-het-things'],
    instruction: 'Translate. No hints — this is where the lesson becomes yours.',
    items: [
      { en: 'Where do you live?', answer: 'Waar woon jij?' },
      { en: 'Bram works in Brussels and he cooks at home.', answer: 'Bram werkt in Brussel en hij kookt thuis.', accept: ['Bram werkt in Brussel en kookt thuis.'] },
      { en: 'Do you work at home?', answer: 'Werk jij thuis?' },
      { en: 'The child is playing in the street.', answer: 'Het kind speelt op straat.', accept: ['Het kind speelt in de straat.'] },
      { en: 'Is Lotte studying?', answer: 'Leert Lotte?' },
      { en: 'Bram is waiting for Lotte.', answer: 'Bram wacht op Lotte.' },
      { en: 'Are you (plural) sleeping? No, we are talking.', answer: 'Slapen jullie? Nee, wij praten.' },
      { en: 'She is ill; she isn’t working.', answer: 'Zij is ziek; zij werkt niet.' },
      { en: 'The car is not new. It is old.', answer: 'De auto is niet nieuw. Hij is oud.' },
      { en: 'This is the house. It is big and we live here.', answer: 'Dit is het huis. Het is groot en wij wonen hier.' },
    ],
  },
  {
    type: 'arrange', title: 'The whole picture', grammar: ['present-regular', 'niet', 'zijn'],
    instruction: 'Build: “Bram is waiting for Lotte; he is not happy.” Two tiles are traps.',
    nl: 'Bram wacht op Lotte; hij is niet blij.', en: 'Bram is waiting for Lotte; he is not happy.', image: 'man-waiting', distractors: ['wachten', 'geen'],
  },
  {
    type: 'drill', title: 'Everything together', grammar: ['present-regular', 'spelling-stem', 'question-word', 'inversion', 'niet', 'geen', 'hij-het-things', 'zijn', 'de-het'],
    instruction: 'A last mixed round. Type every answer.',
    items: [
      { nl: 'Hij ___ op de bank.', cue: 'zitten', en: 'He is sitting on the bench.', answer: 'zit' },
      { nl: '___ jij in Gent?', cue: 'wonen', en: 'Do you live in Ghent?', answer: 'Woon' },
      { nl: '___ speelt het kind?', en: 'Where is the child playing?', answer: 'Waar' },
      { nl: 'Bram wacht ___ Lotte.', en: 'Bram is waiting for Lotte.', answer: 'op' },
      { nl: 'Jij praat.', task: 'Make it a question', answer: 'Praat jij?' },
      { nl: 'Lotte leert thuis.', task: 'Make it negative', answer: 'Lotte leert niet thuis.' },
      { nl: 'Ik kook hier.', task: 'Change ik to zij (she)', answer: 'Zij kookt hier.' },
      { image: 'man-sleeping', nl: 'Werkt Bram?', task: 'Answer in full', answer: 'Nee, hij slaapt.', accept: ['Nee, Bram slaapt.', 'Nee, hij werkt niet.', 'Nee, Bram werkt niet.', 'Nee, hij werkt niet. Hij slaapt.'] },
      { listen: 'Spelen jullie hier?' },
      { nl: 'Waar is het raam? ___ is hier.', en: 'Where is the window? It is here.', answer: 'Het' },
      { en: 'The child is sweet.', answer: 'Het kind is lief.' },
      { nl: 'Jij ___ niet op Bram.', cue: 'wachten', en: 'You are not waiting for Bram.', answer: 'wacht' },
    ],
  },
  {
    type: 'complete', title: 'Every present tense, from one rule',
    instruction: 'Stem, stem + t, infinitive; double the vowel, drop the double consonant, never write -tt; and jij loses its -t after the verb. That is the Dutch present tense — every new verb from now on uses it.',
  },
];
