/**
 * Lesson 4 — Ik heb een hond.
 * Targets: hebben, hond, kat, boek, fiets, tas, sleutel, telefoon, jas, bed.
 * Structure: mijn, maar, of (+ grote, kleine, oude, jonge, mooie, nieuwe, lieve).
 * Grammar: hebben · geen or niet · adjective -e.
 * Story: Bram has a big dog, Max. Lotte has a small cat, a bike and an old book she loves. Bram has no bike —
 * and he cannot find his key.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'A dog, a cat, a book, a bike', grammar: ['dit-is', 'de-het'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice.',
    cards: [
      { nl: 'Dit is een hond. De hond is groot.', en: 'This is a dog. The dog is big.', image: 'dog-big' },
      { nl: 'Dit is een kat. De kat is klein.', en: 'This is a cat. The cat is small.', image: 'cat' },
      { nl: 'Dit is een boek. Het boek is oud.', en: 'This is a book. The book is old.', image: 'book' },
      { nl: 'Dit is een fiets. De fiets is niet groot.', en: 'This is a bicycle. The bicycle is not big.', image: 'bike' },
      { nl: 'Bram heeft een hond. Dit is Max.', en: 'Bram has a dog. This is Max.', image: 'man-dog' },
      { nl: 'Lotte heeft een fiets.', en: 'Lotte has a bicycle.', image: 'woman-bike' },
    ],
    note: 'Learn them with their articles: de hond, de kat, het boek, de fiets — three de-words, one het-word. “Heeft” means “has”; it is a form of hebben (to have), the verb of this lesson. Max is Bram’s dog; “heet” (is called) is not in this book yet, so for now we simply say who he is.',
  },
  {
    type: 'observe', title: 'A bag, a key, a phone, a coat, a bed', grammar: ['dit-is', 'de-het', 'hij-het-things'],
    instruction: 'Five more things — the things you own and carry every day. Listen and repeat, twice.',
    cards: [
      { nl: 'Dit is een tas. Lotte heeft een tas.', en: 'This is a bag. Lotte has a bag.', image: 'bag' },
      { nl: 'Dit is een sleutel. Hij is klein.', en: 'This is a key. It is small.', image: 'key' },
      { nl: 'Dit is een telefoon. Bram heeft een telefoon.', en: 'This is a phone. Bram has a phone.', image: 'phone' },
      { nl: 'Dit is een jas. De jas is mooi.', en: 'This is a coat. The coat is beautiful.', image: 'coat' },
      { nl: 'Dit is een bed. Het bed is groot.', en: 'This is a bed. The bed is big.', image: 'bed' },
      { nl: 'Bram is moe. Hij slaapt in bed.', en: 'Bram is tired. He is sleeping in bed.', image: 'man-sleeping' },
    ],
    note: 'de tas, de sleutel, de telefoon, de jas — four de-words — and **het bed**, a het-word. You now know five het-words: het huis, het kind, het raam, het boek, het bed. So a key, a phone, a bag or a coat is “hij”; the bed is “het”. “In bed” needs no article, just as in English. The “eu” in sleutel has no English twin: say the “ay” of “say” with your lips rounded as for “oo” — keep replaying it.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['dit-is', 'geen'],
    instruction: 'Read the sentences and choose their picture.',
    nl: 'Dit is geen tas. Dit is een jas.', en: 'This is not a bag. This is a coat.', answer: 'coat',
    choices: [{ image: 'bag', nl: 'een tas' }, { image: 'coat', nl: 'een jas' }, { image: 'key', nl: 'een sleutel' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['present-regular'],
    instruction: 'Listen without reading. Which picture is it?',
    nl: 'De kat slaapt.', en: 'The cat is asleep.', answer: 'cat-sleeping',
    choices: [{ image: 'cat', nl: 'Dit is een kat.' }, { image: 'man-sleeping', nl: 'Bram slaapt.' }, { image: 'cat-sleeping', nl: 'De kat slaapt.' }, { image: 'dog-small', nl: 'De hond is klein.' }],
  },
  {
    type: 'picture', listen: true, title: 'Which thing?', grammar: ['dit-is'],
    instruction: 'Listen. Choose the picture.',
    nl: 'Dit is een telefoon.', en: 'This is a phone.', answer: 'phone',
    choices: [{ image: 'key', nl: 'Dit is een sleutel.' }, { image: 'phone', nl: 'Dit is een telefoon.' }, { image: 'bed', nl: 'Dit is een bed.' }, { image: 'book', nl: 'Dit is een boek.' }],
  },
  {
    type: 'picture', listen: true, title: 'Big or small?', grammar: ['zijn'],
    instruction: 'Listen. Choose the picture.',
    nl: 'De hond is klein.', en: 'The dog is small.', answer: 'dog-small',
    choices: [{ image: 'dog-big', nl: 'De hond is groot.' }, { image: 'cat', nl: 'De kat is klein.' }, { image: 'dog-small', nl: 'De hond is klein.' }],
  },
  {
    type: 'drill', title: 'Write the word', grammar: ['de-het'],
    instruction: 'Type the Dutch noun for each picture — no article.',
    items: [
      { image: 'dog-big', answer: 'hond' },
      { image: 'key', answer: 'sleutel' },
      { image: 'book', answer: 'boek' },
      { image: 'coat', answer: 'jas' },
      { image: 'cat', answer: 'kat' },
      { image: 'phone', answer: 'telefoon' },
      { image: 'bike', answer: 'fiets' },
      { image: 'bed', answer: 'bed' },
      { image: 'bag', answer: 'tas' },
    ],
    explanation: 'hond, sleutel, boek, jas, kat, telefoon, fiets, bed, tas. “oe” in boek sounds like the long “oo” in English “boot” (not the short one in “book”); “ie” in fiets like “ee” in “feet”; telefoon ends in a long “oo” — two o’s.',
  },
  {
    type: 'drill', title: 'Every noun with its article', grammar: ['de-het'],
    instruction: 'Type “the …”: article and noun together. The old nouns are mixed in.',
    items: [
      { image: 'book', answer: 'het boek' },
      { image: 'bed', answer: 'het bed' },
      { image: 'key', answer: 'de sleutel' },
      { image: 'tree', answer: 'de boom' },
      { image: 'window', answer: 'het raam' },
      { image: 'phone', answer: 'de telefoon' },
      { image: 'child', answer: 'het kind' },
      { image: 'bag', answer: 'de tas' },
      { image: 'door', answer: 'de deur' },
      { image: 'coat', answer: 'de jas' },
      { image: 'car', answer: 'de auto' },
    ],
    explanation: 'Five het-words so far: het huis, het kind, het raam, het boek, het bed. Everything else you know is a de-word — including all four things you carry: de tas, de sleutel, de telefoon, de jas.',
  },
  {
    type: 'drill', title: 'Hear and spell', grammar: ['de-het', 'subject-pronouns'],
    instruction: 'Play each phrase and type it. Listen for the long “ee” in heeft and the “eu” in sleutel.',
    items: [
      { listen: 'de sleutel' }, { listen: 'ik heb' }, { listen: 'hij heeft' },
      { listen: 'de telefoon' }, { listen: 'het bed' }, { listen: 'de jas' },
    ],
    explanation: '“heb” is short and sharp; “heeft” has a long “ee” and ends in “-ft”. They sound very different — keep replaying them. sleutel: s-l-eu-t-e-l.',
  },
  {
    type: 'observe', title: 'mijn, maar, of', grammar: ['hebben', 'geen', 'yes-no-question'],
    instruction: 'Three small words that make longer sentences possible. Listen and repeat.',
    cards: [
      { nl: 'Dit is mijn fiets.', en: 'This is my bicycle.', image: 'woman-bike' },
      { nl: 'Mijn kat slaapt.', en: 'My cat is asleep.', image: 'cat-sleeping' },
      { nl: 'Waar is mijn sleutel?', en: 'Where is my key?', image: 'key' },
      { nl: 'Bram heeft een hond, maar hij heeft geen fiets.', en: 'Bram has a dog, but he has no bicycle.', image: 'man-dog' },
      { nl: 'Heb jij een hond of een kat?', en: 'Do you have a dog or a cat?', image: 'cat' },
      { nl: 'Is de hond groot of klein?', en: 'Is the dog big or small?', image: 'dog-big' },
    ],
    note: '**mijn** = my, for de-words and het-words alike (mijn fiets, mijn boek, mijn bed). **maar** = but; it joins two full sentences and normally has a comma before it. **of** = or. Careful: “of” never means “of” in English.',
  },

  // ——— Grammar: hebben ———
  {
    part: 'Grammar', type: 'grammar', title: 'hebben: to have', grammar: ['hebben', 'present-regular', 'spelling-stem'],
    body: [
      '**hebben** is almost regular, and that is exactly what makes it dangerous. Start from the rule you know: stem for ik, stem + t for jij, infinitive for the plural. The stem of *hebben* is **heb** — a double consonant at the end of a stem becomes single, just as *zitten* gives *ik zit*.',
      'So: *ik **heb***, *jij **hebt***, *wij/jullie/zij **hebben***. All regular.',
      'The one exception is the third person singular: **hij heeft, zij heeft, het heeft** — not *hebt*. English learners often write *hij hebt*; it is simply wrong. Think of English “has”, which also breaks the pattern of “have”.',
      'Questions work as before. The verb moves to the front, and when *jij* follows the verb, the -t disappears: *jij hebt* → ***heb** jij?* But *heeft* is not a “stem + t” form, so it never changes: *Heeft Lotte een fiets?*',
      'Remember that **zij** is both “she” (zij heeft) and “they” (zij hebben). The verb tells you which one is meant.',
    ],
    tables: [
      {
        caption: 'hebben — present tense',
        rows: [
          { nl: 'ik heb', en: 'I have' }, { nl: 'jij heb[t]', en: 'you have' }, { nl: 'hij h[eef]t', en: 'he has' },
          { nl: 'zij h[eef]t', en: 'she has' }, { nl: 'wij hebb[en]', en: 'we have' }, { nl: 'jullie hebb[en]', en: 'you (plural) have' },
          { nl: 'zij hebb[en]', en: 'they have' },
        ],
      },
      {
        caption: 'zijn and hebben side by side — both irregular in the third person',
        rows: [
          { nl: 'ik ben — ik heb', en: 'I am — I have' }, { nl: 'jij bent — jij hebt', en: 'you are — you have' },
          { nl: 'hij [is] — hij [heeft]', en: 'he is — he has' }, { nl: 'wij zijn — wij hebben', en: 'we are — we have' },
        ],
      },
    ],
    examples: [
      { nl: 'Ik heb een telefoon.', en: 'I have a phone.' },
      { nl: 'Jij hebt een tas.', en: 'You have a bag.' },
      { nl: 'Heb jij een sleutel?', en: 'Do you have a key?' },
      { nl: 'Bram heeft een hond.', en: 'Bram has a dog.' },
      { nl: 'Heeft Lotte een kat? Ja, zij heeft een kat.', en: 'Does Lotte have a cat? Yes, she has a cat.' },
      { nl: 'Bram en Lotte hebben een hond en een kat.', en: 'Bram and Lotte have a dog and a cat.' },
    ],
  },
  {
    type: 'drill', title: 'The table: hebben', grammar: ['hebben', 'subject-pronouns'], layout: 'table',
    instruction: 'Type every form of hebben. Say “ik heb, jij hebt …” out loud as you go.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'heb' },
      { label: 'jij', gloss: 'you', answer: 'hebt' },
      { label: 'hij', gloss: 'he', answer: 'heeft' },
      { label: 'zij', gloss: 'she', answer: 'heeft' },
      { label: 'wij', gloss: 'we', answer: 'hebben' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'hebben' },
      { label: 'zij', gloss: 'they', answer: 'hebben' },
    ],
    explanation: 'heb, hebt, heeft, heeft, hebben, hebben, hebben. Two forms of zij: “zij heeft” is she, “zij hebben” is they.',
  },
  {
    type: 'drill', title: 'Which form?', grammar: ['hebben', 'inversion'], choices: ['heb', 'hebt', 'heeft', 'hebben'],
    instruction: 'First contact: choose the form. From the next page on you type.',
    items: [
      { nl: 'Lotte ___ een kat.', answer: 'heeft' },
      { nl: 'Ik ___ een sleutel.', answer: 'heb' },
      { nl: 'Jij ___ een fiets.', answer: 'hebt' },
      { nl: '___ jij een telefoon?', answer: 'heb' },
      { nl: 'Jullie ___ een hond.', answer: 'hebben' },
      { nl: 'Hij ___ een jas.', answer: 'heeft' },
    ],
    explanation: 'The trap is “hebt” after hij. It does not exist: hij heeft. And “hebt jij?” does not exist either: heb jij?',
  },
  {
    type: 'drill', title: 'Fill in hebben', grammar: ['hebben', 'inversion', 'subject-pronouns'],
    instruction: 'Type the right form of hebben. Read the English to decide between she and they.',
    items: [
      { nl: 'Bram ___ een hond.', cue: 'hebben', en: 'Bram has a dog.', answer: 'heeft' },
      { nl: 'Ik ___ een kat.', cue: 'hebben', en: 'I have a cat.', answer: 'heb' },
      { nl: 'Jij ___ een tas.', cue: 'hebben', en: 'You have a bag.', answer: 'hebt' },
      { nl: '___ jij een hond?', cue: 'hebben', en: 'Do you have a dog?', answer: 'Heb' },
      { nl: '___ Lotte een fiets?', cue: 'hebben', en: 'Does Lotte have a bicycle?', answer: 'Heeft' },
      { nl: 'Zij ___ geen auto.', cue: 'hebben', en: 'They have no car.', answer: 'hebben' },
      { nl: '___ jullie een sleutel?', cue: 'hebben', en: 'Do you (plural) have a key?', answer: 'Hebben' },
      { nl: 'Hij ___ geen fiets.', cue: 'hebben', en: 'He has no bicycle.', answer: 'heeft' },
      { nl: 'Het kind ___ een jas.', cue: 'hebben', en: 'The child has a coat.', answer: 'heeft' },
    ],
    explanation: 'Only three forms to write: heb (ik, and jij after the verb), hebt (jij before the verb), heeft (hij/zij/het, and every single person or thing: Bram, het kind). Everything plural is hebben.',
  },
  {
    type: 'drill', title: 'ben or heb?', grammar: ['hebben', 'zijn', 'inversion'],
    instruction: 'zijn or hebben? The cue tells you the verb; you choose the form. Mixing them is the most common beginner mistake.',
    items: [
      { nl: 'Ik ___ moe.', cue: 'zijn', en: 'I am tired.', answer: 'ben' },
      { nl: 'Ik ___ een hond.', cue: 'hebben', en: 'I have a dog.', answer: 'heb' },
      { nl: 'Hij ___ oud.', cue: 'zijn', en: 'He is old.', answer: 'is' },
      { nl: 'Hij ___ een boek.', cue: 'hebben', en: 'He has a book.', answer: 'heeft' },
      { nl: '___ jij ziek?', cue: 'zijn', en: 'Are you ill?', answer: 'Ben' },
      { nl: '___ jij een kat?', cue: 'hebben', en: 'Do you have a cat?', answer: 'Heb' },
      { nl: 'Het kind ___ blij.', cue: 'zijn', en: 'The child is happy.', answer: 'is' },
      { nl: 'Het kind ___ een bed.', cue: 'hebben', en: 'The child has a bed.', answer: 'heeft' },
      { nl: 'Wij ___ thuis.', cue: 'zijn', en: 'We are at home.', answer: 'zijn' },
      { nl: 'Wij ___ een huis.', cue: 'hebben', en: 'We have a house.', answer: 'hebben' },
    ],
    explanation: 'Line them up: ben/heb, bent/hebt, is/heeft, zijn/hebben. Both verbs drop the -t in “ben jij?” and “heb jij?”.',
  },
  {
    type: 'drill', title: 'Change the subject', grammar: ['hebben', 'present-regular', 'spelling-stem', 'subject-pronouns', 'inversion'],
    instruction: 'Rewrite the sentence with the new subject. Every verb you know is in here, not only hebben.',
    items: [
      { nl: 'Ik heb een kat.', task: 'Change to: Lotte', answer: 'Lotte heeft een kat.' },
      { nl: 'Bram heeft een telefoon.', task: 'Change to: ik', answer: 'Ik heb een telefoon.' },
      { nl: 'Ik heb een jas.', task: 'Change to: jij', answer: 'Jij hebt een jas.' },
      { nl: 'Heeft Lotte een tas?', task: 'Change to: jij', answer: 'Heb jij een tas?' },
      { nl: 'Ik kook thuis.', task: 'Change to: Bram', answer: 'Bram kookt thuis.' },
      { nl: 'Wij wachten op Lotte.', task: 'Change to: jij', answer: 'Jij wacht op Lotte.' },
      { nl: 'Het kind speelt op straat.', task: 'Change to: jullie', answer: 'Jullie spelen op straat.' },
      { nl: 'Leert Lotte thuis?', task: 'Change to: jij', answer: 'Leer jij thuis?' },
      { nl: 'Wij praten op de bank.', task: 'Change to: de oude man', answer: 'De oude man praat op de bank.' },
      { nl: 'Werkt Lotte thuis?', task: 'Change to: jij', answer: 'Werk jij thuis?' },
    ],
    explanation: 'Change the subject and the verb must follow it. “Jij wacht” and “hij praat” get no second t: the stem already ends in t. After the verb, jij takes the bare stem: heb jij, leer jij, werk jij.',
  },
  {
    type: 'drill', title: 'Ask the question', grammar: ['hebben', 'inversion', 'yes-no-question', 'present-regular'], task: 'Make it a question',
    instruction: 'Turn each statement into a yes/no question. The verb goes first; jij loses its -t.',
    items: [
      { nl: 'Jij hebt een sleutel.', answer: 'Heb jij een sleutel?' },
      { nl: 'Lotte heeft een fiets.', answer: 'Heeft Lotte een fiets?' },
      { nl: 'Jij kookt thuis.', answer: 'Kook jij thuis?' },
      { nl: 'Jij zit op de bank.', answer: 'Zit jij op de bank?' },
      { nl: 'Jij wacht op Bram.', answer: 'Wacht jij op Bram?' },
      { nl: 'Het kind speelt op straat.', answer: 'Speelt het kind op straat?' },
      { nl: 'Bram werkt in Brussel.', answer: 'Werkt Bram in Brussel?' },
      { nl: 'Jij loopt in Leuven.', answer: 'Loop jij in Leuven?' },
    ],
    explanation: '“Zit jij?” and “Wacht jij?” look unchanged because the stems zit and wacht already end in t — the rule still applied. “Speelt het kind?” and “Werkt Bram?” keep their t: only jij loses it.',
  },

  // ——— Grammar: geen or niet ———
  {
    type: 'grammar', title: 'geen or niet?', grammar: ['geen-niet', 'geen', 'niet'],
    body: [
      'Dutch uses **niet** and **geen** in different patterns. These exercises practise ordinary, neutral negation.',
      '**geen** replaces **een** — or no article at all — in front of a noun. It means “not a / no”: *Ik heb **een** hond* → *Ik heb **geen** hond.* For neutral negation, use **geen hond**. A contrast with emphasis can use **niet een**, but that is not the pattern practised here.',
      '**niet** negates everything else: an adjective (*De hond is **niet** groot*), a verb (*Bram werkt **niet***), a place (*Lotte werkt **niet** in Brussel*), and a noun that already has **de, het** or **mijn** in front of it (*Dit is **niet** mijn fiets*).',
      'So the test is quick: is there **een** (or nothing) in front of a noun? Then **geen**. In every other case, **niet**.',
      'Where does *niet* go? Straight in front of the adjective, the place, or the noun with *de/het/mijn* after *is* that it negates (*De kat is **niet** klein*, *Lotte werkt **niet** in Brussel*, *Dit is **niet** het huis*). When it negates the whole action it goes to the end: *Max slaapt **niet**.* With **hebben** and a noun that has *mijn, de* or *het*, that noun comes first and *niet* follows it: *Ik heb mijn sleutel **niet**.*',
      'Feel the difference: *Ik heb **geen** sleutel* — there is no key at all. *Ik heb mijn sleutel **niet*** — my key exists, but I do not have it (with me).',
      'An adjective does not change the choice: *een grote hond* → *geen grote hond*.',
    ],
    tables: [
      {
        caption: 'geen — instead of een',
        rows: [
          { nl: 'Ik heb een fiets. → Ik heb [geen] fiets.', en: 'I have a bike. → I have no bike.' },
          { nl: 'Dit is een kat. → Dit is [geen] kat.', en: 'This is a cat. → This is not a cat.' },
          { nl: 'Ik heb een grote hond. → Ik heb [geen] grote hond.', en: 'I have a big dog. → I do not have a big dog.' },
        ],
      },
      {
        caption: 'niet — for everything else',
        rows: [
          { nl: 'De hond is [niet] groot.', en: 'The dog is not big.' },
          { nl: 'Bram werkt [niet].', en: 'Bram is not working.' },
          { nl: 'Lotte werkt [niet] in Brussel.', en: 'Lotte does not work in Brussels.' },
          { nl: 'Dit is [niet] mijn fiets.', en: 'This is not my bike.' },
          { nl: 'Ik heb mijn telefoon [niet].', en: 'I do not have my phone (with me).' },
        ],
      },
    ],
    examples: [
      { nl: 'Heeft Bram een fiets? Nee, hij heeft geen fiets.', en: 'Does Bram have a bike? No, he has no bike.' },
      { nl: 'Is de fiets groot? Nee, hij is niet groot.', en: 'Is the bike big? No, it is not big.' },
      { nl: 'Waar is mijn sleutel? Ik heb mijn sleutel niet.', en: 'Where is my key? I do not have my key.' },
      { nl: 'Dit is niet mijn boek. Mijn boek is oud.', en: 'This is not my book. My book is old.' },
    ],
  },
  {
    type: 'drill', title: 'geen or niet?', grammar: ['geen-niet', 'hebben'], choices: ['geen', 'niet'],
    instruction: 'First contact. Ask yourself: is there een (or nothing) in front of a noun?',
    items: [
      { nl: 'Ik heb ___ hond.', answer: 'geen' },
      { nl: 'De hond is ___ groot.', answer: 'niet' },
      { nl: 'Bram heeft ___ fiets.', answer: 'geen' },
      { nl: 'Dit is ___ mijn boek.', answer: 'niet' },
      { nl: 'Ik heb ___ telefoon.', answer: 'geen' },
      { nl: 'Ik heb mijn sleutel ___.', answer: 'niet' },
      { nl: 'Lotte heeft ___ grote kat.', answer: 'geen' },
      { nl: 'Het bed is ___ groot.', answer: 'niet' },
    ],
    explanation: 'geen: before an een-noun (hond, fiets, telefoon, grote kat). niet: an adjective, a verb, a place, or a noun with mijn/de/het — “Ik heb mijn sleutel niet”.',
  },
  {
    type: 'drill', title: 'Make it negative', grammar: ['geen-niet', 'niet', 'hebben', 'present-regular', 'zijn'], task: 'Make it negative',
    instruction: 'Rewrite each sentence as a negative. Decide first: geen or niet? And where does niet go?',
    items: [
      { nl: 'Ik heb een hond.', answer: 'Ik heb geen hond.' },
      { nl: 'De kat is groot.', answer: 'De kat is niet groot.' },
      { nl: 'Jij hebt een sleutel.', answer: 'Jij hebt geen sleutel.' },
      { nl: 'Bram werkt in Leuven.', answer: 'Bram werkt niet in Leuven.' },
      { nl: 'Dit is mijn boek.', answer: 'Dit is niet mijn boek.' },
      { nl: 'Ik heb mijn telefoon.', answer: 'Ik heb mijn telefoon niet.' },
      { nl: 'De jas is nieuw.', answer: 'De jas is niet nieuw.' },
      { nl: 'Wij hebben een auto.', answer: 'Wij hebben geen auto.' },
      { nl: 'Het kind speelt op straat.', answer: 'Het kind speelt niet op straat.' },
      { nl: 'Bram kookt.', answer: 'Bram kookt niet.' },
    ],
    explanation: 'Three with geen (a noun with een), seven with niet. “Ik heb mijn telefoon niet” — mijn blocks geen, and with hebben niet comes after the noun.',
  },
  {
    type: 'arrange', title: 'One has, one has not', grammar: ['geen-niet', 'hebben'],
    instruction: 'Build: “Lotte has a bike, but Bram has no bike.” Two tiles are traps.',
    nl: 'Lotte heeft een fiets, maar Bram heeft geen fiets.', en: 'Lotte has a bicycle, but Bram has no bicycle.', image: 'woman-bike', distractors: ['niet', 'hebt'],
  },
  {
    type: 'drill', title: 'No — and say why', grammar: ['geen-niet', 'niet', 'yes-no-question', 'hebben', 'present-regular'], task: 'Answer: Nee, …',
    instruction: 'All of these are false — for Bram, Lotte and Max, or for the picture. Answer with a full negative sentence. You may use the name or a pronoun.',
    items: [
      { nl: 'Heeft Bram een fiets?', answer: 'Nee, Bram heeft geen fiets.', accept: ['Nee, hij heeft geen fiets.'] },
      { nl: 'Is Max klein?', answer: 'Nee, Max is niet klein.', accept: ['Nee, hij is niet klein.'] },
      { nl: 'Woont Bram in Brussel?', answer: 'Nee, Bram woont niet in Brussel.', accept: ['Nee, hij woont niet in Brussel.'] },
      { nl: 'Werkt Lotte in Brussel?', answer: 'Nee, Lotte werkt niet in Brussel.', accept: ['Nee, zij werkt niet in Brussel.'] },
      { nl: 'Is de kat groot?', answer: 'Nee, de kat is niet groot.', accept: ['Nee, hij is niet groot.'] },
      { image: 'key', nl: 'Is dit een telefoon?', answer: 'Nee, dit is geen telefoon.', accept: ['Nee, dit is geen telefoon. Dit is een sleutel.'] },
      { image: 'bed', nl: 'Is dit een bank?', answer: 'Nee, dit is geen bank.', accept: ['Nee, dit is geen bank. Dit is een bed.'] },
    ],
    explanation: 'Bram lives in Leuven and works in Brussel — the question tried to catch you. The cat is a de-word, so “hij”.',
  },

  // ——— Grammar: adjective -e ———
  {
    type: 'grammar', title: 'een grote hond', grammar: ['adjective-e', 'de-het', 'geen-niet'],
    body: [
      'After **is / zijn** an adjective never changes: *De hond is **groot**.* That is what you have done since lesson 2.',
      'Put the adjective **in front of a noun**, though, and it normally takes **-e**: *de **grote** hond, een **grote** hond, mijn **grote** hond, het **grote** huis.*',
      'There is **one exception**: after **een** or **geen** with a **het-word**, there is no -e: *een **groot** huis, een **klein** boek, een **nieuw** bed, geen **oud** huis.* With *het*, *mijn* or *de* in front, the -e is back: *het **grote** huis, mijn **kleine** boek, het **nieuwe** bed.*',
      'So the only question is: *een/geen + het-word?* Then no -e. Everything else before a noun: -e. This is why you must know whether a noun is a de-word or a het-word — and you now know five het-words: **huis, kind, raam, boek, bed**.',
      'Spelling: **groot → grote**. Adding -e opens the syllable (gro-te), and an open syllable needs only one *o* — the same rule as *wonen → woon* in reverse. *klein → kleine*, *oud → oude*, *jong → jonge*, *mooi → mooie*, *nieuw → nieuwe* just add -e.',
      '**lief → lieve**: between two vowels an *f* becomes a *v* — you hear it, and you write it. But where no -e comes, the *f* stays: *een **lief** kind* (een + het-word), *Max is **lief***.',
      '*moe*, *blij* and *ziek* you will use only after the verb for now: *Bram is moe*, *Lotte is ziek*, *het kind is blij*.',
    ],
    tables: [
      {
        caption: 'de-words: always -e',
        rows: [
          { nl: 'de grot[e] hond', en: 'the big dog' }, { nl: 'een grot[e] hond', en: 'a big dog' },
          { nl: 'geen grot[e] hond', en: 'no big dog' }, { nl: 'mijn klein[e] kat', en: 'my small cat' },
          { nl: 'een nieuw[e] jas', en: 'a new coat' }, { nl: 'een liev[e] hond', en: 'a sweet dog' },
        ],
      },
      {
        caption: 'het-words: -e, except after een and geen',
        rows: [
          { nl: 'het grot[e] huis', en: 'the big house' }, { nl: 'mijn oud[e] boek', en: 'my old book' },
          { nl: 'het nieuw[e] bed', en: 'the new bed' },
          { nl: 'een groot huis', en: 'a big house' }, { nl: 'een mooi huis', en: 'a beautiful house' },
          { nl: 'een klein boek', en: 'a small book' }, { nl: 'geen oud huis', en: 'not an old house' },
        ],
      },
      {
        caption: 'after is: never -e',
        rows: [{ nl: 'De hond is groot.', en: 'The dog is big.' }, { nl: 'Het boek is klein.', en: 'The book is small.' }, { nl: 'Max is lief.', en: 'Max is sweet.' }],
      },
    ],
    examples: [
      { nl: 'Bram heeft een grote hond.', en: 'Bram has a big dog.' },
      { nl: 'Max is een lieve hond.', en: 'Max is a sweet dog.' },
      { nl: 'Lotte heeft een oud boek.', en: 'Lotte has an old book.' },
      { nl: 'Ik heb een nieuwe jas.', en: 'I have a new coat.' },
      { nl: 'Het nieuwe bed is groot.', en: 'The new bed is big.' },
      { nl: 'Wij wonen in een mooi huis.', en: 'We live in a beautiful house.' },
    ],
  },
  {
    type: 'drill', title: 'With or without -e?', grammar: ['adjective-e', 'de-het'],
    instruction: 'First contact. Before choosing, ask: is it een/geen + a het-word?',
    items: [
      { nl: 'een ___ hond', choices: ['groot', 'grote'], answer: 'grote' },
      { nl: 'een ___ huis', choices: ['groot', 'grote'], answer: 'groot' },
      { nl: 'het ___ huis', choices: ['groot', 'grote'], answer: 'grote' },
      { nl: 'een ___ jas', choices: ['nieuw', 'nieuwe'], answer: 'nieuwe' },
      { nl: 'een ___ bed', choices: ['nieuw', 'nieuwe'], answer: 'nieuw' },
      { nl: 'mijn ___ kat', choices: ['lief', 'lieve'], answer: 'lieve' },
      { nl: 'een ___ raam', choices: ['mooi', 'mooie'], answer: 'mooi' },
      { nl: 'geen ___ huis', choices: ['oud', 'oude'], answer: 'oud' },
    ],
    explanation: 'No -e only four times: een groot huis, een nieuw bed, een mooi raam, geen oud huis: een/geen + het-word.',
  },
  {
    type: 'drill', title: 'Type the adjective', grammar: ['adjective-e', 'de-het'],
    instruction: 'Type the adjective in the right form. The cue gives the basic form.',
    items: [
      { nl: 'de ___ hond', cue: 'groot', answer: 'grote' },
      { nl: 'een ___ boek', cue: 'oud', answer: 'oud' },
      { nl: 'het ___ boek', cue: 'oud', answer: 'oude' },
      { nl: 'een ___ kat', cue: 'lief', answer: 'lieve' },
      { nl: 'mijn ___ telefoon', cue: 'nieuw', answer: 'nieuwe' },
      { nl: 'de ___ deur', cue: 'oud', answer: 'oude' },
      { nl: 'een ___ tas', cue: 'mooi', answer: 'mooie' },
      { nl: 'Het huis is ___.', cue: 'groot', answer: 'groot' },
      { nl: 'een ___ auto', cue: 'nieuw', answer: 'nieuwe' },
      { nl: 'de ___ straat', cue: 'mooi', answer: 'mooie' },
      { nl: 'De jas is ___.', cue: 'nieuw', answer: 'nieuw' },
    ],
    explanation: 'grote has one o; lieve has a v. Every noun here except boek and huis is a de-word, so only “een oud boek” and the two after “is” stay bare.',
  },
  {
    type: 'drill', title: 'Five het-words: een groot huis, het grote huis', grammar: ['adjective-e', 'de-het'],
    instruction: 'Only het-words now: huis, kind, raam, boek, bed. Type the adjective. Watch the word in front: een/geen, or het/mijn?',
    items: [
      { nl: 'een ___ bed', cue: 'groot', answer: 'groot' },
      { nl: 'het ___ bed', cue: 'groot', answer: 'grote' },
      { nl: 'een ___ raam', cue: 'klein', answer: 'klein' },
      { nl: 'het ___ raam', cue: 'klein', answer: 'kleine' },
      { nl: 'een ___ kind', cue: 'lief', answer: 'lief' },
      { nl: 'het ___ kind', cue: 'lief', answer: 'lieve' },
      { nl: 'geen ___ huis', cue: 'mooi', answer: 'mooi' },
      { nl: 'mijn ___ huis', cue: 'mooi', answer: 'mooie' },
      { nl: 'een ___ boek', cue: 'nieuw', answer: 'nieuw' },
      { nl: 'mijn ___ boek', cue: 'nieuw', answer: 'nieuwe' },
      { nl: 'het ___ kind', cue: 'jong', answer: 'jonge' },
      { nl: 'Het bed is ___.', cue: 'nieuw', answer: 'nieuw' },
    ],
    explanation: 'The pattern never moves: een/geen + het-word → no -e; het/mijn + het-word → -e. And “een lief kind” keeps its f, because no vowel follows.',
  },
  {
    type: 'drill', title: 'Describe the picture', grammar: ['adjective-e', 'de-het'],
    instruction: 'Write “een” + adjective + noun for each picture. The English tells you which adjective.',
    items: [
      { image: 'dog-big', en: 'a big dog', answer: 'een grote hond' },
      { image: 'house', en: 'a big house', answer: 'een groot huis' },
      { image: 'phone', en: 'a new phone', answer: 'een nieuwe telefoon' },
      { image: 'dog-small', en: 'a sweet dog', answer: 'een lieve hond' },
      { image: 'child', en: 'a sweet child', answer: 'een lief kind' },
      { image: 'coat', en: 'a beautiful coat', answer: 'een mooie jas' },
      { image: 'bed', en: 'a big bed', answer: 'een groot bed' },
      { image: 'car', en: 'a new car', answer: 'een nieuwe auto' },
      { image: 'tree-small', en: 'a young tree', answer: 'een jonge boom' },
    ],
    explanation: 'Only the het-words (huis, kind, bed) stay without -e after een — and “een lief kind” keeps its f.',
  },
  {
    type: 'drill', title: 'Two sentences into one', grammar: ['adjective-e', 'hij-het-things', 'hebben', 'dit-is'], task: 'Make it one sentence',
    instruction: 'Move the adjective in front of the noun and drop the second sentence. Example: “Dit is een hond. Hij is groot.” → “Dit is een grote hond.”',
    items: [
      { nl: 'Dit is een kat. Hij is klein.', answer: 'Dit is een kleine kat.' },
      { nl: 'Dit is een bed. Het is groot.', answer: 'Dit is een groot bed.' },
      { nl: 'Bram heeft een hond. Hij is groot.', answer: 'Bram heeft een grote hond.' },
      { nl: 'Lotte heeft een boek. Het is oud.', answer: 'Lotte heeft een oud boek.' },
      { nl: 'Ik heb een jas. Hij is nieuw.', answer: 'Ik heb een nieuwe jas.' },
      { nl: 'Lotte is een vrouw. Zij is jong.', answer: 'Lotte is een jonge vrouw.' },
      { nl: 'Max is een hond. Hij is lief.', answer: 'Max is een lieve hond.' },
      { nl: 'Dit is het raam. Het is mooi.', answer: 'Dit is het mooie raam.' },
      { nl: 'De man zit op de bank. Hij is oud.', answer: 'De oude man zit op de bank.' },
    ],
    explanation: 'Notice how “hij” points back to a de-word (kat, hond, jas) and “het” to a het-word (bed, boek, raam). “het mooie raam” — het brings the -e back.',
  },
  {
    type: 'drill', title: 'And back again', grammar: ['adjective-e', 'hij-het-things', 'de-het'], task: 'Say it with hij or het + is',
    instruction: 'Now the other way. Say what the thing is like with “Hij is …” or “Het is …” — after “is”, no -e.',
    items: [
      { nl: 'Bram heeft een grote hond.', answer: 'Hij is groot.', accept: ['De hond is groot.'] },
      { nl: 'Lotte heeft een kleine kat.', answer: 'Hij is klein.', accept: ['De kat is klein.'] },
      { nl: 'Ik heb een oud boek.', answer: 'Het is oud.', accept: ['Het boek is oud.'] },
      { nl: 'Bram heeft een nieuwe telefoon.', answer: 'Hij is nieuw.', accept: ['De telefoon is nieuw.'] },
      { nl: 'Wij hebben een groot bed.', answer: 'Het is groot.', accept: ['Het bed is groot.'] },
      { nl: 'Wij wonen in een mooi huis.', answer: 'Het is mooi.', accept: ['Het huis is mooi.'] },
      { nl: 'Dit is mijn kleine sleutel.', answer: 'Hij is klein.', accept: ['Mijn sleutel is klein.', 'De sleutel is klein.'] },
    ],
    explanation: 'Two things change at once: the -e goes (grote → groot, kleine → klein, nieuwe → nieuw), and the noun becomes hij (de-word) or het (het-word). Remember the Flemish note from lesson 2: some de-words, such as de tas or de deur, are “ze” in Belgium, so this drill sticks to hond, kat, telefoon and sleutel.',
  },
  {
    type: 'arrange', title: 'A cat and a book', grammar: ['adjective-e', 'hebben'],
    instruction: 'Build: “Lotte has a small cat and an old book.” Three tiles are traps.',
    nl: 'Lotte heeft een kleine kat en een oud boek.', en: 'Lotte has a small cat and an old book.', image: 'cat', distractors: ['klein', 'oude', 'hebt'],
  },
  {
    type: 'drill', title: 'Say it with hebben', grammar: ['adjective-e', 'hebben', 'geen-niet', 'niet', 'subject-pronouns'],
    instruction: 'Translate. Every sentence has an adjective, and most have hebben — sometimes with geen or niet.',
    items: [
      { en: 'I have a big dog.', answer: 'Ik heb een grote hond.' },
      { en: 'She has a small cat.', answer: 'Zij heeft een kleine kat.' },
      { en: 'He has no big house.', answer: 'Hij heeft geen groot huis.' },
      { en: 'The child has a new coat.', answer: 'Het kind heeft een nieuwe jas.' },
      { en: 'Do you have a big bed?', answer: 'Heb jij een groot bed?' },
      { en: 'Max is a sweet dog.', answer: 'Max is een lieve hond.' },
      { en: 'You (plural) have a beautiful bag.', answer: 'Jullie hebben een mooie tas.' },
      { en: 'The big dog is not tired.', answer: 'De grote hond is niet moe.' },
    ],
    explanation: '“geen groot huis” — geen + het-word, so no -e. “De grote hond is niet moe”: -e in front of the noun, and moe stays after is.',
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', title: 'mijn, maar or of?', grammar: ['hebben', 'geen-niet', 'yes-no-question', 'zijn'],
    instruction: 'Type the missing word: mijn, maar or of.',
    items: [
      { nl: 'Bram heeft een hond, ___ Lotte heeft een kat.', en: 'Bram has a dog, but Lotte has a cat.', answer: 'maar' },
      { nl: 'Heb jij een hond ___ een kat?', en: 'Do you have a dog or a cat?', answer: 'of' },
      { nl: 'Waar is ___ sleutel?', en: 'Where is my key?', answer: 'mijn' },
      { nl: 'Is de telefoon nieuw ___ oud?', en: 'Is the phone new or old?', answer: 'of' },
      { nl: '___ kleine kat slaapt.', en: 'My small cat is asleep.', answer: 'Mijn' },
      { nl: 'Ik heb een fiets, ___ ik heb geen auto.', en: 'I have a bike, but I have no car.', answer: 'maar' },
      { nl: 'Dit is ___ nieuwe jas.', en: 'This is my new coat.', answer: 'mijn' },
      { nl: 'Bram is moe, ___ Lotte is niet moe.', en: 'Bram is tired, but Lotte is not tired.', answer: 'maar' },
    ],
  },
  {
    type: 'drill', title: 'This or that?', grammar: ['hebben', 'adjective-e', 'present-regular', 'question-word'], task: 'Answer in full',
    instruction: 'Questions with “of” ask you to pick one. Answer with a full sentence about Bram, Lotte and Max.',
    items: [
      { nl: 'Heeft Bram een hond of een kat?', answer: 'Bram heeft een hond.', accept: ['Hij heeft een hond.', 'Bram heeft een grote hond.', 'Hij heeft een grote hond.'] },
      { nl: 'Heeft Lotte een grote kat of een kleine kat?', answer: 'Lotte heeft een kleine kat.', accept: ['Zij heeft een kleine kat.'] },
      { nl: 'Werkt Bram in Brussel of thuis?', answer: 'Bram werkt in Brussel.', accept: ['Hij werkt in Brussel.'] },
      { nl: 'Kookt Bram thuis of in Brussel?', answer: 'Bram kookt thuis.', accept: ['Hij kookt thuis.'] },
      { nl: 'Zit de oude man op de bank of in het huis?', answer: 'De oude man zit op de bank.', accept: ['Hij zit op de bank.'] },
      { nl: 'Waar werkt Lotte?', answer: 'Lotte werkt thuis.', accept: ['Zij werkt thuis.'] },
    ],
  },
  {
    type: 'drill', title: 'All twelve verbs', grammar: ['present-regular', 'spelling-stem', 'hebben', 'zijn', 'inversion', 'question-word', 'niet'],
    instruction: 'Every verb you know, in every position. Type the form; the cue is the infinitive.',
    items: [
      { nl: 'Bram ___ in Leuven.', cue: 'wonen', en: 'Bram lives in Leuven.', answer: 'woont' },
      { nl: 'Lotte ___ thuis.', cue: 'werken', en: 'Lotte works at home.', answer: 'werkt' },
      { nl: '___ jij in Brussel?', cue: 'werken', en: 'Do you work in Brussels?', answer: 'Werk' },
      { nl: 'Max ___ in Leuven.', cue: 'lopen', en: 'Max walks in Leuven.', answer: 'loopt' },
      { nl: 'Wij ___ niet.', cue: 'lopen', en: 'We are not walking.', answer: 'lopen' },
      { nl: 'De oude man ___ op de bank.', cue: 'zitten', en: 'The old man sits on the bench.', answer: 'zit' },
      { nl: '___ jij in het grote bed?', cue: 'slapen', en: 'Do you sleep in the big bed?', answer: 'Slaap' },
      { nl: 'Bram ___ thuis.', cue: 'koken', en: 'Bram cooks at home.', answer: 'kookt' },
      { nl: '___ jij niet?', cue: 'koken', en: 'Don’t you cook?', answer: 'Kook' },
      { nl: 'Het kind ___ op straat.', cue: 'spelen', en: 'The child is playing in the street.', answer: 'speelt' },
      { nl: 'Lotte ___ thuis.', cue: 'leren', en: 'Lotte studies at home.', answer: 'leert' },
      { nl: '___ jij thuis?', cue: 'leren', en: 'Do you study at home?', answer: 'Leer' },
      { nl: 'Bram en Lotte ___ thuis.', cue: 'praten', en: 'Bram and Lotte are talking at home.', answer: 'praten' },
      { nl: 'De oude man ___ niet.', cue: 'praten', en: 'The old man is not talking.', answer: 'praat' },
      { nl: 'Max ___ op Bram.', cue: 'wachten', en: 'Max is waiting for Bram.', answer: 'wacht' },
      { nl: 'Waar ___ jij?', cue: 'wachten', en: 'Where are you waiting?', answer: 'wacht' },
      { nl: 'Jij ___ ziek.', cue: 'zijn', en: 'You are ill.', answer: 'bent' },
      { nl: 'Zij ___ blij.', cue: 'zijn', en: 'They are happy.', answer: 'zijn' },
      { nl: 'Jij ___ geen fiets.', cue: 'hebben', en: 'You have no bike.', answer: 'hebt' },
    ],
    explanation: 'Stem rules everywhere: woon, werk, loop, zit, slaap, kook, speel, leer, praat, wacht, heb. Stems ending in t take no second t (hij praat, jij wacht). Only zijn and the hij-form of hebben (heeft) break the pattern.',
  },
  {
    type: 'arrange', title: 'A question with of', grammar: ['hebben', 'inversion'],
    instruction: 'Build: “Do you have a dog or a cat?” Two tiles are traps.',
    nl: 'Heb jij een hond of een kat?', en: 'Do you have a dog or a cat?', image: 'dog-small', distractors: ['hebt', 'heeft'],
  },
  {
    type: 'arrange', title: 'Not my coat', grammar: ['geen-niet', 'dit-is', 'adjective-e'],
    instruction: 'Build: “This is not my coat. My coat is new.” Two tiles are traps.',
    nl: 'Dit is niet mijn jas. Mijn jas is nieuw.', en: 'This is not my coat. My coat is new.', image: 'coat', distractors: ['geen', 'nieuwe'],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Een grote hond', image: 'old-man', grammar: ['hebben', 'geen-niet', 'adjective-e', 'inversion'],
    instruction: 'Bram is out with Max, Lotte with her bike. The old man is on his bench. Read, listen to every line, then read it again without the English.',
    lines: [
      { speaker: 'De oude man', nl: 'Wat een grote hond!', en: 'What a big dog!', image: 'dog-big' },
      { speaker: 'Bram', nl: 'Ja, dit is mijn hond, Max. Hij is groot, maar hij is lief.', en: 'Yes, this is my dog, Max. He is big, but he is sweet.', image: 'man-dog' },
      { speaker: 'De oude man', nl: 'Heb jij ook een kat?', en: 'Do you have a cat too?', image: 'old-man' },
      { speaker: 'Bram', nl: 'Nee, ik heb geen kat, maar Lotte heeft een kleine kat. Hij slaapt thuis op het bed.', en: 'No, I don’t have a cat, but Lotte has a small cat. It is asleep at home on the bed.', image: 'cat-sleeping' },
      { speaker: 'De oude man', nl: 'Jij hebt een mooie fiets en een oud boek, Lotte. En jij, Bram? Heb jij ook een fiets?', en: 'You have a beautiful bike and an old book, Lotte. And you, Bram? Do you have a bike too?', image: 'woman-bike' },
      { speaker: 'Lotte', nl: 'Bram heeft geen fiets, maar hij heeft een grote hond!', en: 'Bram has no bike, but he has a big dog!', image: 'man-dog' },
      { speaker: 'Bram', nl: 'Lotte, waar is mijn sleutel? Ik heb mijn sleutel niet!', en: 'Lotte, where is my key? I don’t have my key!', image: 'key' },
      { speaker: 'Lotte', nl: 'Is hij niet in mijn tas?', en: 'Isn’t it in my bag?', image: 'bag' },
      { speaker: 'Bram', nl: 'Nee, dit is mijn telefoon. Ja! Hier is hij, in mijn jas.', en: 'No, this is my phone. Yes! Here it is, in my coat.', image: 'coat' },
      { speaker: 'De oude man', nl: 'Ik heb geen hond, geen kat en geen fiets. Ik zit hier op mijn bank!', en: 'I have no dog, no cat and no bike. I sit here on my bench!', image: 'old-man' },
      { speaker: 'Bram', nl: 'Max is moe, Lotte.', en: 'Max is tired, Lotte.', image: 'dog-big' },
      { speaker: 'Lotte', nl: 'Max is niet moe, Bram. Jij bent moe!', en: 'Max is not tired, Bram. You are tired!', image: 'man-tired' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'hebben'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the conversation. Answer without looking back.',
    items: [
      { nl: 'Heeft Bram een kleine hond?', answer: 'Nee' },
      { nl: 'Is Max lief?', answer: 'Ja' },
      { nl: 'Slaapt de kat op het bed?', answer: 'Ja' },
      { nl: 'Heeft Bram een fiets?', answer: 'Nee' },
      { nl: 'Is de sleutel in de tas?', answer: 'Nee' },
      { nl: 'Is Bram moe?', answer: 'Ja' },
    ],
  },
  {
    type: 'drill', title: 'Answer in a full sentence', grammar: ['hebben', 'geen-niet', 'adjective-e', 'question-word', 'hij-het-things'], task: 'Answer in full',
    instruction: 'Answer each question about the story with a complete sentence. A name or a pronoun are both fine.',
    items: [
      { nl: 'Heeft Bram een fiets?', answer: 'Nee, Bram heeft geen fiets.', accept: ['Nee, hij heeft geen fiets.'] },
      { nl: 'Heeft Bram een grote of een kleine hond?', answer: 'Bram heeft een grote hond.', accept: ['Hij heeft een grote hond.'] },
      { nl: 'Waar slaapt de kat?', answer: 'De kat slaapt thuis op het bed.', accept: ['Hij slaapt thuis op het bed.', 'De kat slaapt op het bed.', 'Hij slaapt op het bed.', 'De kat slaapt thuis.', 'Hij slaapt thuis.'] },
      { nl: 'Heeft Lotte de sleutel?', answer: 'Nee, Lotte heeft de sleutel niet.', accept: ['Nee, zij heeft de sleutel niet.', 'Nee, Bram heeft de sleutel.'] },
      { nl: 'Waar is de sleutel?', answer: 'De sleutel is in de jas.', accept: ['Hij is in de jas.'] },
      { nl: 'Heeft de oude man een kat?', answer: 'Nee, de oude man heeft geen kat.', accept: ['Nee, hij heeft geen kat.'] },
      { nl: 'Is Max moe?', answer: 'Nee, Max is niet moe.', accept: ['Nee, hij is niet moe.'] },
      { nl: 'Waar zit de oude man?', answer: 'De oude man zit op de bank.', accept: ['Hij zit op de bank.', 'De oude man zit hier op de bank.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['hebben', 'geen-niet', 'adjective-e', 'inversion'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'Lotte is een jonge vrouw en zij heeft een kleine kat.' },
      { listen: 'Bram heeft geen fiets.' },
      { listen: 'Heb jij een hond of een kat?' },
      { listen: 'Het oude boek is niet groot.' },
      { listen: 'Waar is mijn sleutel? Ik heb mijn sleutel niet.' },
      { listen: 'Het kind heeft een nieuwe jas en een mooie tas.' },
      { listen: 'Bram en Lotte praten op straat, maar Max wacht thuis.' },
      { listen: 'Wij hebben een jonge hond, maar jullie hebben een oude kat.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['hebben', 'geen-niet', 'adjective-e', 'present-regular', 'zijn', 'inversion'],
    instruction: 'Translate. No hints — every rule of this lesson is in here somewhere.',
    items: [
      { en: 'Do you have a key?', answer: 'Heb jij een sleutel?' },
      { en: 'Lotte has a small cat.', answer: 'Lotte heeft een kleine kat.' },
      { en: 'Bram does not have a bike.', answer: 'Bram heeft geen fiets.' },
      { en: 'I don’t have my phone.', answer: 'Ik heb mijn telefoon niet.' },
      { en: 'We live in a big house.', answer: 'Wij wonen in een groot huis.' },
      { en: 'The new bed is not big.', answer: 'Het nieuwe bed is niet groot.' },
      { en: 'Bram has a dog, but Lotte has a cat.', answer: 'Bram heeft een hond, maar Lotte heeft een kat.' },
      { en: 'Do you (plural) have a dog or a cat?', answer: 'Hebben jullie een hond of een kat?' },
      { en: 'This is not my coat.', answer: 'Dit is niet mijn jas.' },
      { en: 'The child is playing in the street.', answer: 'Het kind speelt op straat.', accept: ['Het kind speelt in de straat.'] },
      { en: 'Max is waiting for Bram.', answer: 'Max wacht op Bram.' },
      { en: 'Is Lotte ill? No, she is not ill. She is happy.', answer: 'Is Lotte ziek? Nee, zij is niet ziek. Zij is blij.' },
      { en: 'We walk in Leuven, but we live in Gent.', answer: 'Wij lopen in Leuven, maar wij wonen in Gent.' },
    ],
  },
  {
    type: 'arrange', title: 'The whole lesson in one sentence', grammar: ['hebben', 'geen-niet', 'adjective-e'],
    instruction: 'Build: “The old man has no dog, but he has a beautiful coat.” Three tiles are traps.',
    nl: 'De oude man heeft geen hond, maar hij heeft een mooie jas.', en: 'The old man has no dog, but he has a beautiful coat.', image: 'old-man', distractors: ['oud', 'niet', 'hebt'],
  },
  {
    type: 'drill', title: 'Everything together', grammar: ['hebben', 'geen-niet', 'adjective-e', 'de-het', 'inversion', 'present-regular', 'question-word', 'hij-het-things'],
    instruction: 'A last mixed round, all typed. Read each task carefully — they change from line to line.',
    items: [
      { nl: '___ bed', cue: 'de / het', answer: 'het' },
      { nl: '___ sleutel', cue: 'de / het', answer: 'de' },
      { nl: 'Lotte ___ een kleine kat.', cue: 'hebben', answer: 'heeft' },
      { nl: '___ jij een telefoon?', cue: 'hebben', answer: 'Heb' },
      { nl: 'een ___ bed', cue: 'klein', answer: 'klein' },
      { nl: 'het ___ bed', cue: 'klein', answer: 'kleine' },
      { nl: 'een ___ hond', cue: 'lief', answer: 'lieve' },
      { nl: 'Bram heeft ___ fiets.', cue: 'geen / niet', answer: 'geen' },
      { nl: 'Ik heb mijn tas ___.', cue: 'geen / niet', answer: 'niet' },
      { nl: 'Jij hebt een jas.', task: 'Make it a question', answer: 'Heb jij een jas?' },
      { nl: 'Ik leer thuis.', task: 'Change to: Lotte', answer: 'Lotte leert thuis.' },
      { en: 'Where does Bram work?', answer: 'Waar werkt Bram?' },
      { en: 'My small cat is not sleeping.', answer: 'Mijn kleine kat slaapt niet.' },
      { listen: 'Heeft Bram een grote hond of een kleine hond?' },
      { image: 'bed', en: 'the new bed', answer: 'het nieuwe bed' },
    ],
  },
  {
    type: 'complete', title: 'Lesson four: have, not have, and a big dog',
    instruction: 'hebben in every person, geen versus niet, and the -e that appears in front of a noun. From now on every noun you learn needs its article for two reasons: de/het, and the adjective in front of it.',
  },
];
