/**
 * Lesson 5 — Wat eet je graag?
 * Targets: lezen, eten, drinken, schrijven, koffie, thee, water, brood, kaas, appel.
 * Structure: graag, altijd, nooit.
 * Grammar: z becomes s, v becomes f (ik lees, ik schrijf) · adverb position (graag, altijd, nooit).
 * Recycles every earlier word and grammar point: see docs/CURRICULUM.md.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Coffee, tea, water — bread, cheese, an apple', grammar: ['dit-is', 'de-het'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice.',
    cards: [
      { nl: 'Dit is koffie.', en: 'This is coffee.', image: 'coffee' },
      { nl: 'Dit is thee.', en: 'This is tea.', image: 'tea' },
      { nl: 'Dit is water.', en: 'This is water.', image: 'water' },
      { nl: 'Dit is brood.', en: 'This is bread.', image: 'bread' },
      { nl: 'Dit is kaas.', en: 'This is cheese.', image: 'cheese' },
      { nl: 'Dit is een appel.', en: 'This is an apple.', image: 'apple' },
    ],
    note: 'Koffie, thee, water, brood and kaas take no “een”: they are things you do not count. An apple you do count, so it is “een appel”. Learn every word with its article: de koffie, de thee, het water, het brood, de kaas, de appel.',
  },
  {
    type: 'observe', title: 'Reading, eating, drinking, writing', grammar: ['present-regular', 'subject-pronouns'],
    instruction: 'Four new verbs. Listen, repeat, and notice the verb forms.',
    cards: [
      { nl: 'Bram eet brood.', en: 'Bram eats bread.', image: 'man-eating' },
      { nl: 'Bram drinkt koffie.', en: 'Bram drinks coffee.', image: 'coffee' },
      { nl: 'Lotte drinkt thee.', en: 'Lotte drinks tea.', image: 'tea' },
      { nl: 'Lotte leest een boek.', en: 'Lotte is reading a book.', image: 'woman-reading' },
      { nl: 'Bram leest ook een boek.', en: 'Bram is reading a book too.', image: 'man-reading' },
      { nl: 'Bram schrijft. Hij schrijft een boek.', en: 'Bram is writing. He is writing a book.', image: 'man-writing' },
    ],
    note: 'The verbs are lezen (to read), eten (to eat), drinken (to drink) and schrijven (to write). “Leest”, “eet”, “drinkt” and “schrijft” follow the rule you know from wonen and werken — with spelling twists you will meet in a moment.',
  },
  {
    type: 'observe', title: 'Always, never, gladly', grammar: ['adverb-position'],
    instruction: 'Three small words that change a sentence. Listen, repeat, and notice where they stand.',
    cards: [
      { nl: 'Bram drinkt altijd koffie.', en: 'Bram always drinks coffee.', image: 'coffee' },
      { nl: 'Lotte drinkt nooit koffie.', en: 'Lotte never drinks coffee.', image: 'woman' },
      { nl: 'Lotte drinkt graag thee.', en: 'Lotte likes tea.', image: 'tea' },
      { nl: 'Lotte leest graag.', en: 'Lotte likes reading.', image: 'woman-reading' },
      { nl: 'Bram schrijft graag.', en: 'Bram likes writing.', image: 'man-writing' },
    ],
    note: '“Altijd” = always, “nooit” = never, “graag” = gladly — Dutch’s way of saying you like doing something. In the simple statements here, they follow the conjugated verb. In questions they follow the subject. Later you will learn other positions, including putting an adverb first for emphasis.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['present-regular'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Bram eet brood.', en: 'Bram is eating bread.', answer: 'man-eating',
    choices: [{ image: 'man-reading', nl: 'Bram leest.' }, { image: 'man-eating', nl: 'Bram eet.' }, { image: 'man-writing', nl: 'Bram schrijft.' }, { image: 'man-sleeping', nl: 'Bram slaapt.' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['present-regular'],
    instruction: 'Listen without reading. Which picture is it?',
    nl: 'Lotte zit op de bank en leest een boek.', en: 'Lotte is sitting on the bench and reading a book.', answer: 'woman-reading',
    choices: [{ image: 'woman-working', nl: 'Lotte werkt.' }, { image: 'woman-sleeping', nl: 'Lotte slaapt.' }, { image: 'woman-reading', nl: 'Lotte leest.' }, { image: 'woman-bike', nl: 'Lotte heeft een fiets.' }],
  },
  {
    type: 'picture', listen: true, title: 'Reading or writing?', grammar: ['present-regular', 'spelling-z-s'],
    instruction: 'Listen without reading. “Leest” or “schrijft”? Choose the picture.',
    nl: 'Bram schrijft een boek.', en: 'Bram is writing a book.', answer: 'man-writing',
    choices: [{ image: 'man-reading', nl: 'Bram leest een boek.' }, { image: 'man-eating', nl: 'Bram eet brood.' }, { image: 'man-writing', nl: 'Bram schrijft een boek.' }],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['dit-is'],
    instruction: 'Listen. Four drinks and foods — choose the one you hear.',
    nl: 'Dit is thee.', en: 'This is tea.', answer: 'tea',
    choices: [{ image: 'coffee', nl: 'koffie' }, { image: 'tea', nl: 'thee' }, { image: 'water', nl: 'water' }, { image: 'cheese', nl: 'kaas' }],
  },
  {
    type: 'drill', title: 'Write the word', grammar: ['de-het'],
    instruction: 'Type the Dutch. Verbs in the infinitive (the dictionary form, ending in -en).',
    items: [
      { image: 'coffee', answer: 'koffie' },
      { image: 'tea', answer: 'thee' },
      { image: 'water', answer: 'water' },
      { image: 'bread', answer: 'brood' },
      { image: 'cheese', answer: 'kaas' },
      { image: 'apple', answer: 'appel' },
      { image: 'tea', nl: '___ thee', cue: 'de / het', answer: 'de' },
      { image: 'water', nl: '___ water', cue: 'de / het', answer: 'het' },
      { image: 'cheese', nl: '___ kaas', cue: 'de / het', answer: 'de' },
      { image: 'apple', nl: '___ appel', cue: 'de / het', answer: 'de' },
      { en: 'to read', answer: 'lezen' },
      { en: 'to eat', answer: 'eten' },
      { en: 'to drink', answer: 'drinken' },
      { en: 'to write', answer: 'schrijven' },
    ],
    explanation: 'de koffie, de thee, de kaas, de appel — but het water, het brood. Learn them with the article, even though you will often use them without one.',
  },
  {
    type: 'drill', title: 'Hear and spell',
    instruction: 'Play each word and type it. Listen hard to the long vowels, the “g” of graag and the “ij” of altijd and schrijven.',
    items: [{ listen: 'thee' }, { listen: 'kaas' }, { listen: 'appel' }, { listen: 'water' }, { listen: 'koffie' }, { listen: 'brood' }, { listen: 'schrijven' }, { listen: 'graag' }, { listen: 'altijd' }, { listen: 'nooit' }],
    explanation: 'Long vowels at the end of a syllable are written once (wa-ter, le-zen) and twice in a closed syllable (kaas, brood); a long e at the very end of a word is also written twice (thee). “Appel” has a short a, so the p is doubled. The “ij” of schrijven and altijd is the same sound.',
  },

  // ——— Grammar: lezen and schrijven — z becomes s, v becomes f ———
  {
    part: 'Grammar', type: 'grammar', title: 'lezen and schrijven: z → s and v → f', grammar: ['spelling-z-s', 'spelling-stem', 'present-regular'],
    body: [
      '**Lezen** (to read) and **schrijven** (to write) follow the present-tense rule you already know: **ik** + stem, **jij / hij / zij** + stem + **t**, **wij / jullie / zij** + infinitive. Only the stem needs care.',
      '**Step 1 — the vowel doubles.** In *le-zen* the e ends a syllable, so it is long. Take off -en and the e is trapped in a closed syllable; to keep it long you write it twice: *lez-* → *leez-*. This is exactly what happened with *wonen → ik woon* and *slapen → ik slaap*.',
      '**Step 2 — z becomes s.** A Dutch word never ends in **z**. At the end of a word you hear an s-sound anyway, so you write **s**: *leez* → **lees**. Then the normal -t follows: *hij lees**t***.',
      '**v becomes f — the same rule with another letter.** A Dutch word never ends in **v** either. *Schrijven* → *schrijv-* → **schrijf**, and then the -t: *hij schrijf**t***. Here only step 2 is needed: **ij** is already one long sound and is never doubled.',
      'In the plural the z and the v come back, because they sit between two vowels again: *wij le**z**en, wij schrij**v**en*. So the singular has **s / f**, the plural has **z / v**.',
      '**Traps:** never write *ik leez*, *ik schrijv*, *hij leesd* or *hij schrijvt*. And in a question “jij” loses its -t, as always: *jij leest* → ***lees** jij?*, *jij schrijft* → ***schrijf** jij?*',
    ],
    tables: [
      { caption: 'lezen — to read', rows: [
        { nl: 'ik lees', en: 'I read' },
        { nl: 'jij lees[t]', en: 'you read' },
        { nl: 'lees jij?', en: 'do you read?' },
        { nl: 'hij / zij lees[t]', en: 'he / she reads' },
        { nl: 'wij lez[en]', en: 'we read' },
        { nl: 'jullie lez[en]', en: 'you (plural) read' },
        { nl: 'zij lez[en]', en: 'they read' },
      ] },
      { caption: 'schrijven — to write', rows: [
        { nl: 'ik schrijf', en: 'I write' },
        { nl: 'jij schrijf[t]', en: 'you write' },
        { nl: 'schrijf jij?', en: 'do you write?' },
        { nl: 'hij / zij schrijf[t]', en: 'he / she writes' },
        { nl: 'wij schrijv[en]', en: 'we write' },
        { nl: 'jullie schrijv[en]', en: 'you (plural) write' },
        { nl: 'zij schrijv[en]', en: 'they write' },
      ] },
      { caption: 'The same steps you know', rows: [
        { nl: 'wonen → ik woon, hij woon[t]', en: 'the vowel doubles' },
        { nl: 'slapen → ik slaap, hij slaap[t]', en: 'the vowel doubles' },
        { nl: 'lezen → ik lees, hij lees[t]', en: 'the vowel doubles and z becomes s' },
        { nl: 'schrijven → ik schrijf, hij schrijf[t]', en: 'v becomes f' },
      ] },
    ],
    examples: [
      { nl: 'Lotte leest een boek.', en: 'Lotte is reading a book.' },
      { nl: 'Wat lees jij?', en: 'What are you reading?' },
      { nl: 'Bram schrijft een boek.', en: 'Bram is writing a book.' },
      { nl: 'Wat schrijf jij?', en: 'What are you writing?' },
      { nl: 'Wij lezen en schrijven thuis.', en: 'We read and write at home.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate lezen', grammar: ['spelling-z-s', 'subject-pronouns', 'present-regular'],
    instruction: 'Type the form of lezen for every person. Say “ik lees, jij leest …” out loud as you go.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'lees' },
      { label: 'jij', gloss: 'you', answer: 'leest' },
      { label: 'hij', gloss: 'he', answer: 'leest' },
      { label: 'zij', gloss: 'she', answer: 'leest' },
      { label: 'wij', gloss: 'we', answer: 'lezen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'lezen' },
      { label: 'zij', gloss: 'they', answer: 'lezen' },
      { label: 'Lotte', gloss: 'Lotte', answer: 'leest' },
    ],
    explanation: 'Singular: lees, leest (s). Plural: lezen (z). The z only survives between two vowels.',
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate schrijven', grammar: ['spelling-z-s', 'subject-pronouns', 'present-regular'],
    instruction: 'Type the form of schrijven for every person. f in the singular, v in the plural.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'schrijf' },
      { label: 'jij', gloss: 'you', answer: 'schrijft' },
      { label: 'hij', gloss: 'he', answer: 'schrijft' },
      { label: 'zij', gloss: 'she', answer: 'schrijft' },
      { label: 'wij', gloss: 'we', answer: 'schrijven' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'schrijven' },
      { label: 'zij', gloss: 'they', answer: 'schrijven' },
      { label: 'Bram', gloss: 'Bram', answer: 'schrijft' },
    ],
    explanation: 'Singular: schrijf, schrijft (f). Plural: schrijven (v). Exactly the pattern of lees, leest, lezen.',
  },
  {
    type: 'drill', title: 'lees or leest? schrijf or schrijft?', grammar: ['spelling-z-s', 'inversion', 'question-word'], choices: ['lees', 'leest', 'lezen'],
    instruction: 'Choose the right form. Watch the questions: after the verb, “jij” takes no -t.',
    items: [
      { nl: 'Ik ___ een boek.', answer: 'lees' },
      { nl: 'Lotte ___ graag.', answer: 'leest' },
      { nl: 'Wij ___ thuis.', answer: 'lezen' },
      { nl: 'Wat ___ jij?', answer: 'lees' },
      { nl: 'De oude man ___ op de bank.', answer: 'leest' },
      { nl: 'Bram ___ een boek.', choices: ['schrijf', 'schrijft', 'schrijven'], answer: 'schrijft' },
      { nl: 'Wat ___ jij?', choices: ['schrijf', 'schrijft', 'schrijven'], answer: 'schrijf' },
      { nl: 'Jullie ___ graag.', choices: ['schrijf', 'schrijft', 'schrijven'], answer: 'schrijven' },
      { nl: 'Waar ___ Bram graag?', choices: ['schrijf', 'schrijft', 'schrijven'], answer: 'schrijft' },
    ],
  },
  {
    type: 'drill', title: 'Type lezen and schrijven', grammar: ['spelling-z-s', 'inversion', 'question-word', 'adjective-e'],
    instruction: 'Type the form of the verb in brackets. The English tells you who is doing it.',
    items: [
      { nl: 'Lotte ___ graag op de bank.', cue: 'lezen', en: 'Lotte likes reading on the bench.', answer: 'leest' },
      { nl: '___ jij graag?', cue: 'lezen', en: 'Do you like reading?', answer: 'Lees' },
      { nl: 'Ik ___ niet graag.', cue: 'lezen', en: 'I don’t like reading.', answer: 'lees' },
      { nl: 'Hij ___ een groot boek.', cue: 'lezen', en: 'He is reading a big book.', answer: 'leest' },
      { nl: 'Waar ___ zij graag?', cue: 'lezen', en: 'Where do they like to read?', answer: 'lezen' },
      { nl: 'Bram ___ een boek.', cue: 'schrijven', en: 'Bram is writing a book.', answer: 'schrijft' },
      { nl: '___ jij graag?', cue: 'schrijven', en: 'Do you like writing?', answer: 'Schrijf' },
      { nl: 'Ik ___ op mijn telefoon.', cue: 'schrijven', en: 'I write on my phone.', answer: 'schrijf' },
      { nl: 'Wij ___ thuis.', cue: 'schrijven', en: 'We write at home.', answer: 'schrijven' },
      { nl: 'Het kind ___ graag.', cue: 'schrijven', en: 'The child likes writing.', answer: 'schrijft' },
      { nl: 'Wat ___ jullie?', cue: 'schrijven', en: 'What are you (plural) writing?', answer: 'schrijven' },
      { nl: 'De jonge vrouw ___ een boek.', cue: 'lezen', en: 'The young woman is reading a book.', answer: 'leest' },
    ],
    explanation: 'Lees jij? Schrijf jij? — but leest hij, schrijft hij, lezen zij, schrijven zij. Only the jij-question drops the -t.',
  },

  // ——— Grammar: eten and drinken ———
  {
    type: 'grammar', title: 'eten and drinken', grammar: ['present-regular', 'spelling-stem', 'inversion'],
    body: [
      '**Eten** (to eat) needs the same first step as lezen: in *e-ten* the e is long, so the stem is written with a double vowel: *et-* → **eet**.',
      'The stem already ends in **t**, so jij, hij and zij get **no second t** — Dutch never writes *eett*. It works exactly like *zitten → hij zit* and *wachten → hij wacht*. The result: **ik eet, jij eet, hij eet** all sound and look the same.',
      'In a question: ***eet** jij?* Because there was no extra t to lose, nothing changes — but the verb still moves in front of “jij”.',
      '**Drinken** (to drink) is completely regular: the stem is **drink**, jij/hij add -t, the plural is the infinitive. Question: ***drink** jij?*',
      '**Traps:** *hij eet* (not *eett*, not *eten*); *drink jij?* (not *drinkt jij?*).',
    ],
    tables: [
      { caption: 'eten — to eat', rows: [
        { nl: 'ik eet', en: 'I eat' },
        { nl: 'jij eet', en: 'you eat' },
        { nl: 'eet jij?', en: 'do you eat?' },
        { nl: 'hij / zij eet', en: 'he / she eats' },
        { nl: 'wij et[en]', en: 'we eat' },
        { nl: 'jullie et[en]', en: 'you (plural) eat' },
        { nl: 'zij et[en]', en: 'they eat' },
      ] },
      { caption: 'drinken — to drink', rows: [
        { nl: 'ik drink', en: 'I drink' },
        { nl: 'jij drink[t]', en: 'you drink' },
        { nl: 'drink jij?', en: 'do you drink?' },
        { nl: 'hij / zij drink[t]', en: 'he / she drinks' },
        { nl: 'wij drink[en]', en: 'we drink' },
        { nl: 'jullie drink[en]', en: 'you (plural) drink' },
        { nl: 'zij drink[en]', en: 'they drink' },
      ] },
    ],
    examples: [
      { nl: 'Bram eet brood en kaas.', en: 'Bram eats bread and cheese.' },
      { nl: 'Eet jij een appel?', en: 'Are you eating an apple?' },
      { nl: 'Lotte drinkt thee.', en: 'Lotte drinks tea.' },
      { nl: 'Drink jij koffie?', en: 'Do you drink coffee?' },
      { nl: 'Wij eten thuis en drinken water.', en: 'We eat at home and drink water.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate eten', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'Type the form of eten for every person. Remember: no second t.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'eet' },
      { label: 'jij', gloss: 'you', answer: 'eet' },
      { label: 'hij', gloss: 'he', answer: 'eet' },
      { label: 'zij', gloss: 'she', answer: 'eet' },
      { label: 'wij', gloss: 'we', answer: 'eten' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'eten' },
      { label: 'zij', gloss: 'they', answer: 'eten' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate drinken', grammar: ['present-regular', 'subject-pronouns'],
    instruction: 'Type the form of drinken for every person.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'drink' },
      { label: 'jij', gloss: 'you', answer: 'drinkt' },
      { label: 'hij', gloss: 'he', answer: 'drinkt' },
      { label: 'zij', gloss: 'she', answer: 'drinkt' },
      { label: 'wij', gloss: 'we', answer: 'drinken' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'drinken' },
      { label: 'zij', gloss: 'they', answer: 'drinken' },
      { label: 'Bram', gloss: 'Bram', answer: 'drinkt' },
    ],
  },
  {
    type: 'drill', title: 'Eat and drink', grammar: ['present-regular', 'spelling-stem', 'inversion', 'question-word'],
    instruction: 'Type the right form of the verb in brackets. Sentence-first blanks are questions.',
    items: [
      { nl: 'Bram ___ altijd koffie.', cue: 'drinken', en: 'Bram always drinks coffee.', answer: 'drinkt' },
      { nl: 'Lotte ___ graag thee.', cue: 'drinken', en: 'Lotte likes tea.', answer: 'drinkt' },
      { nl: '___ jij brood?', cue: 'eten', en: 'Do you eat bread?', answer: 'Eet' },
      { nl: 'Jij ___ een appel.', cue: 'eten', en: 'You are eating an apple.', answer: 'eet' },
      { nl: 'Hij ___ graag kaas.', cue: 'eten', en: 'He likes eating cheese.', answer: 'eet' },
      { nl: 'Wij ___ geen koffie.', cue: 'drinken', en: 'We don’t drink coffee.', answer: 'drinken' },
      { nl: '___ jullie graag thee?', cue: 'drinken', en: 'Do you (plural) like tea?', answer: 'Drinken' },
      { nl: 'Ik ___ altijd water.', cue: 'drinken', en: 'I always drink water.', answer: 'drink' },
      { nl: 'Zij ___ brood en kaas.', cue: 'eten', en: 'They are eating bread and cheese.', answer: 'eten' },
      { nl: 'Het kind ___ water.', cue: 'drinken', en: 'The child is drinking water.', answer: 'drinkt' },
      { nl: '___ het kind een appel?', cue: 'eten', en: 'Is the child eating an apple?', answer: 'Eet' },
    ],
    explanation: 'eet — eet — eet in the singular, whoever eats. drink — drinkt — drinken, and “drink jij?” in a question.',
  },
  {
    type: 'drill', title: 'Every verb, as a question', grammar: ['inversion', 'yes-no-question', 'zijn', 'hebben', 'spelling-z-s'], task: 'Make it a question',
    instruction: 'Turn each statement into a yes/no question. The verb goes first — and after the verb, “jij” loses its -t.',
    items: [
      { nl: 'Jij leest een boek.', answer: 'Lees jij een boek?' },
      { nl: 'Jij schrijft een boek.', answer: 'Schrijf jij een boek?' },
      { nl: 'Jij eet kaas.', answer: 'Eet jij kaas?' },
      { nl: 'Jij drinkt graag thee.', answer: 'Drink jij graag thee?' },
      { nl: 'Jij woont in Leuven.', answer: 'Woon jij in Leuven?' },
      { nl: 'Jij bent moe.', answer: 'Ben jij moe?' },
      { nl: 'Jij kookt graag.', answer: 'Kook jij graag?' },
      { nl: 'Jij wacht op Lotte.', answer: 'Wacht jij op Lotte?' },
      { nl: 'Hij schrijft graag.', answer: 'Schrijft hij graag?' },
      { nl: 'Het kind speelt op straat.', answer: 'Speelt het kind op straat?' },
      { nl: 'Jullie eten altijd brood.', answer: 'Eten jullie altijd brood?' },
    ],
    explanation: 'Lees jij, schrijf jij, drink jij, woon jij, ben jij, kook jij — only jij changes. “Eet jij” and “wacht jij” end in t already, so nothing is lost. “Schrijft hij?” and “eten jullie?” keep their forms.',
  },

  // ——— Grammar: koffie, thee, kaas — no article ———
  {
    type: 'grammar', title: 'Coffee, tea, cheese: no “een”', grammar: ['de-het', 'geen', 'geen-niet', 'hij-het-things', 'dit-is', 'adjective-e'],
    body: [
      '**Koffie**, **thee**, **water**, **brood** and **kaas** are *mass nouns*: you do not count them. When you talk about them in general, there is **no article at all**: *Ik drink thee. Bram eet kaas. Het kind drinkt water.* (In a café you will hear “een koffie” — a cup of coffee — and at the bakery you buy “een brood”, a whole loaf. That is ordering one portion, not talking about coffee or bread in general.)',
      '**Appel** is different: you can count apples, so it behaves like huis or boek. *Ik eet **een** appel. De appel is groot.*',
      'When you mean a particular one, use the article: **de** koffie, **de** thee, **de** kaas, **de** appel, but **het** water, **het** brood. For the examples here, masculine **kaas** uses **hij**, and **water**, a het-word for a thing, uses **het**. Not every de-word uses hij; feminine nouns can use ze. *De kaas is oud. Hij is oud. — Het water is hier. Het is hier.*',
      '**Negation.** “Geen” replaces “een” — and it also stands where there is *no* article: *Lotte drinkt **geen** koffie. Ik eet **geen** appel. Wij hebben **geen** brood.* Never *niet koffie*.',
      '**geen …, maar …** To say what someone has *instead*, add “maar”: *Lotte drinkt **geen** koffie, **maar** thee.* The noun after “maar” keeps its own article: zero for a mass noun, “een” for a count noun — *Ik eet geen kaas, maar een appel.*',
      'Compare three ways of saying no: *Lotte drinkt **geen** koffie* (she does not drink coffee), *Lotte drinkt **nooit** koffie* (she never drinks it), *Ik drink **niet graag** koffie* (I don’t like drinking it). With “nooit” and “niet graag” the noun keeps its zero article.',
      '**Adjectives without an article** follow the “een” pattern: -e for a de-word, no -e for a het-word. *Oude kaas* and *jonge kaas* are the everyday shop names for aged and mild cheese; but bread is *oud brood*.',
    ],
    tables: [
      { caption: 'With and without an article', rows: [
        { nl: 'Ik drink thee.', en: 'I drink tea. (in general)' },
        { nl: 'De thee is hier. Hij is hier.', en: 'The tea is here. It is here.' },
        { nl: 'Het kind drinkt water.', en: 'The child is drinking water.' },
        { nl: 'Het water is hier. Het is hier.', en: 'The water is here. It is here.' },
        { nl: 'Bram eet kaas.', en: 'Bram eats cheese.' },
        { nl: 'Ik eet een appel.', en: 'I am eating an apple. (you count apples)' },
        { nl: 'Bram eet graag oud[e] kaas.', en: 'Bram likes aged cheese.' },
      ] },
      { caption: 'Saying no', rows: [
        { nl: 'Lotte drinkt [geen] koffie.', en: 'Lotte doesn’t drink coffee.' },
        { nl: 'Lotte drinkt [geen] koffie, [maar] thee.', en: 'Lotte doesn’t drink coffee but tea.' },
        { nl: 'Ik eet [geen] appel.', en: 'I am not eating an apple.' },
        { nl: 'Lotte drinkt [nooit] koffie.', en: 'Lotte never drinks coffee.' },
        { nl: 'Ik drink [niet graag] koffie.', en: 'I don’t like drinking coffee.' },
        { nl: 'Het brood is [niet] oud.', en: 'The bread is not stale.' },
      ] },
    ],
    examples: [
      { nl: 'Is dit koffie? Nee, dit is thee.', en: 'Is this coffee? No, this is tea.' },
      { nl: 'Heb jij kaas? Nee, ik heb geen kaas.', en: 'Do you have cheese? No, I don’t have any cheese.' },
      { nl: 'Een kind drinkt geen koffie, maar water.', en: 'A child doesn’t drink coffee, but water.' },
      { nl: 'Bram heeft altijd koffie thuis.', en: 'Bram always has coffee at home.' },
    ],
  },
  {
    type: 'drill', title: 'een, geen or niet?', grammar: ['geen-niet', 'geen', 'niet'], choices: ['een', 'geen', 'niet'],
    instruction: 'The English tells you the meaning. Choose the word that makes the Dutch say it.',
    items: [
      { nl: 'Lotte drinkt ___ koffie, maar thee.', en: 'Lotte doesn’t drink coffee but tea.', answer: 'geen' },
      { nl: 'Het kind eet ___ appel.', en: 'The child is eating an apple.', answer: 'een' },
      { nl: 'Het brood is ___ oud.', en: 'The bread is not stale.', answer: 'niet' },
      { nl: 'Ik heb ___ appel in mijn tas.', en: 'I have an apple in my bag.', answer: 'een' },
      { nl: 'Ik drink ___ graag water.', en: 'I don’t like drinking water.', answer: 'niet' },
      { nl: 'Bram heeft ___ fiets.', en: 'Bram doesn’t have a bike.', answer: 'geen' },
      { nl: 'Bram heeft ___ nieuwe jas.', en: 'Bram has a new coat.', answer: 'een' },
      { nl: 'Mijn telefoon is ___ nieuw.', en: 'My phone is not new.', answer: 'niet' },
      { nl: 'Dit is ___ auto, maar een fiets.', en: 'This is not a car but a bike.', answer: 'geen' },
      { nl: 'Een kind drinkt ___ koffie.', en: 'A child doesn’t drink coffee.', answer: 'geen' },
    ],
    explanation: '“Geen” before a noun with een or with no article (geen fiets, geen koffie, geen kaas). “Niet” everywhere else — before an adjective, before graag.',
  },
  {
    type: 'drill', title: 'Say no', grammar: ['geen-niet', 'niet', 'hebben', 'adverb-position'], task: 'Make it negative',
    instruction: 'Make each sentence negative with “geen” or “niet” — nothing else changes.',
    items: [
      { nl: 'Ik eet kaas.', answer: 'Ik eet geen kaas.' },
      { nl: 'Het kind drinkt thee.', answer: 'Het kind drinkt geen thee.' },
      { nl: 'Wij hebben brood.', answer: 'Wij hebben geen brood.' },
      { nl: 'Ik heb een jas.', answer: 'Ik heb geen jas.' },
      { nl: 'De appel is groot.', answer: 'De appel is niet groot.' },
      { nl: 'Wij schrijven graag.', answer: 'Wij schrijven niet graag.' },
      { nl: 'Jij drinkt graag koffie.', answer: 'Jij drinkt niet graag koffie.' },
      { nl: 'Mijn telefoon is in mijn tas.', answer: 'Mijn telefoon is niet in mijn tas.' },
      { nl: 'Zij eet graag brood.', answer: 'Zij eet niet graag brood.' },
    ],
    explanation: '“Niet graag” is a fixed pair: niet comes first, then graag, then the rest. Before a place (in mijn tas) “niet” stands straight in front of it.',
  },

  // ——— Grammar: graag, altijd, nooit ———
  {
    type: 'grammar', title: 'graag, altijd, nooit: their place in a sentence', grammar: ['adverb-position', 'niet', 'inversion', 'question-word'],
    body: [
      'In the simple subject-first statements on these pages, **graag**, **altijd** (always), **nooit** (never) and **niet** follow the conjugated verb. This is the pattern to practise here, not their only possible position.',
      'English puts “always” and “never” *before* the verb: *Bram **always** drinks coffee.* In a Dutch subject-first statement, use: *Bram drinkt **altijd** koffie.* “Bram altijd drinkt koffie” is one of the most common learner mistakes — the verb has to come first.',
      '**Graag** has no one-word English equivalent. Literally it means “gladly”; Dutch uses it where English uses the verb *like*: *Ik lees **graag*** = I like reading. *Ik drink **graag** thee* = I like (drinking) tea. To say you don’t like something: ***niet graag***, with niet first — *Ik wacht niet graag.*',
      'In a **question** the verb comes first, then the subject, *then* the adverb: *Drink jij **graag** koffie? Eet Bram **altijd** kaas?* With a question word the pattern is the same: *Wat drink jij **graag**? Waar schrijf jij **graag**?*',
      'The slot is the same with every verb: *Bram heeft **altijd** koffie thuis. Wij wonen **graag** in Leuven. Is Bram **altijd** moe?*',
      'A precise note: the adverb comes before an object *without* de or het (koffie, kaas, een boek) and before a place (thuis, in bed, op straat). A pronoun object such as “het” goes in front of it: *Ik lees het graag.* In the drills the objects are always of the first kind.',
    ],
    tables: [
      { caption: 'Statements: subject — verb — adverb — rest', rows: [
        { nl: 'Ik drink [graag] thee.', en: 'I like tea.' },
        { nl: 'Bram drinkt [altijd] koffie.', en: 'Bram always drinks coffee.' },
        { nl: 'Lotte drinkt [nooit] koffie.', en: 'Lotte never drinks coffee.' },
        { nl: 'Ik wacht [niet graag].', en: 'I don’t like waiting.' },
        { nl: 'Lotte werkt [altijd] thuis.', en: 'Lotte always works at home.' },
      ] },
      { caption: 'Questions: verb — subject — adverb — rest', rows: [
        { nl: 'Drink jij [graag] koffie?', en: 'Do you like coffee?' },
        { nl: 'Eet Bram [altijd] kaas?', en: 'Does Bram always eat cheese?' },
        { nl: 'Wat eet jij [graag]?', en: 'What do you like to eat?' },
        { nl: 'Waar schrijf jij [graag]?', en: 'Where do you like to write?' },
      ] },
    ],
    examples: [
      { nl: 'Lotte leest graag op de bank.', en: 'Lotte likes reading on the bench.' },
      { nl: 'Bram schrijft graag in bed.', en: 'Bram likes writing in bed.' },
      { nl: 'Het kind speelt graag op straat.', en: 'The child likes playing in the street.' },
      { nl: 'Is Bram altijd moe? Nee, niet altijd.', en: 'Is Bram always tired? No, not always.' },
    ],
  },
  {
    type: 'drill', title: 'Which order is Dutch?', grammar: ['adverb-position'],
    instruction: 'Read the English, then choose the only correct Dutch sentence.',
    items: [
      { en: 'Bram always drinks coffee.', choices: ['Bram altijd drinkt koffie.', 'Bram drinkt altijd koffie.', 'Altijd Bram drinkt koffie.'], answer: 'Bram drinkt altijd koffie.' },
      { en: 'I like reading.', choices: ['Ik graag lees.', 'Graag ik lees.', 'Ik lees graag.'], answer: 'Ik lees graag.' },
      { en: 'Lotte never drinks coffee.', choices: ['Lotte drinkt nooit koffie.', 'Lotte nooit drinkt koffie.', 'Nooit Lotte drinkt koffie.'], answer: 'Lotte drinkt nooit koffie.' },
      { en: 'Do you like eating cheese?', choices: ['Eet graag jij kaas?', 'Eet jij graag kaas?', 'Graag eet jij kaas?'], answer: 'Eet jij graag kaas?' },
      { en: 'I don’t like drinking coffee.', choices: ['Ik drink graag niet koffie.', 'Ik niet drink graag koffie.', 'Ik drink niet graag koffie.'], answer: 'Ik drink niet graag koffie.' },
      { en: 'Where do you like to write?', choices: ['Waar jij schrijft graag?', 'Waar schrijf jij graag?', 'Waar schrijf graag jij?'], answer: 'Waar schrijf jij graag?' },
    ],
  },
  {
    type: 'drill', title: 'Put the word in its place', grammar: ['adverb-position', 'inversion', 'question-word', 'hebben'],
    instruction: 'Rewrite each sentence with the word given. Find the verb first; the new word goes right after it — in a question, right after the subject.',
    items: [
      { nl: 'Ik drink water.', task: 'Add “altijd”', answer: 'Ik drink altijd water.' },
      { nl: 'Bram eet kaas.', task: 'Add “graag”', answer: 'Bram eet graag kaas.' },
      { nl: 'Lotte drinkt koffie.', task: 'Add “nooit”', answer: 'Lotte drinkt nooit koffie.' },
      { nl: 'Drink jij thee?', task: 'Add “graag”', answer: 'Drink jij graag thee?' },
      { nl: 'Het kind speelt op straat.', task: 'Add “graag”', answer: 'Het kind speelt graag op straat.' },
      { nl: 'De kat zit in het raam.', task: 'Add “altijd”', answer: 'De kat zit altijd in het raam.' },
      { nl: 'Bram kookt.', task: 'Add “graag”', answer: 'Bram kookt graag.' },
      { nl: 'Ik wacht.', task: 'Add “niet graag”', answer: 'Ik wacht niet graag.' },
      { nl: 'Waar schrijf jij?', task: 'Add “graag”', answer: 'Waar schrijf jij graag?' },
      { nl: 'Eet jij een appel?', task: 'Add “altijd”', answer: 'Eet jij altijd een appel?' },
      { nl: 'Bram heeft koffie thuis.', task: 'Add “altijd”', answer: 'Bram heeft altijd koffie thuis.' },
    ],
    explanation: 'Statement: subject, verb, adverb. Question: verb, subject, adverb. These pages practise the ordinary subject-first statement and its question. An adverb can also start a sentence with inversion, which comes later.',
  },
  {
    type: 'arrange', title: 'Bram and his coffee', grammar: ['adverb-position'],
    instruction: 'Build: “Bram always drinks coffee.” Two words are left over.',
    nl: 'Bram drinkt altijd koffie.', en: 'Bram always drinks coffee.', image: 'coffee', distractors: ['drink', 'nooit'],
  },
  {
    type: 'arrange', title: 'Ask about tea', grammar: ['adverb-position', 'inversion'],
    instruction: 'Build: “Do you like tea?” Two words are left over.',
    nl: 'Drink jij graag thee?', en: 'Do you like tea?', image: 'tea', distractors: ['drinkt', 'geen'],
  },
  {
    type: 'drill', title: 'English order, Dutch order', grammar: ['adverb-position', 'present-regular', 'inversion', 'question-word'],
    instruction: 'Translate using subject-first statements. Put altijd or nooit after the conjugated verb.',
    items: [
      { en: 'Bram always eats bread.', answer: 'Bram eet altijd brood.' },
      { en: 'Lotte always drinks tea.', answer: 'Lotte drinkt altijd thee.' },
      { en: 'Do you like writing?', answer: 'Schrijf jij graag?' },
      { en: 'He never reads.', answer: 'Hij leest nooit.' },
      { en: 'The child never eats cheese.', answer: 'Het kind eet nooit kaas.' },
      { en: 'We like talking.', answer: 'Wij praten graag.' },
      { en: 'She doesn’t like eating bread.', answer: 'Zij eet niet graag brood.' },
      { en: 'Do you always work at home?', answer: 'Werk jij altijd thuis?' },
      { en: 'What do you like to drink?', answer: 'Wat drink jij graag?' },
      { en: 'They never drink coffee.', answer: 'Zij drinken nooit koffie.' },
    ],
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'observe', title: 'Everything you know, in one street', grammar: ['adjective-e', 'hebben', 'adverb-position', 'present-regular'],
    instruction: 'Every sentence here mixes this lesson with earlier ones. Listen, repeat, and name each old rule you spot.',
    cards: [
      { nl: 'Wij wonen graag in Leuven.', en: 'We like living in Leuven.', image: 'people-home' },
      { nl: 'Bram werkt in Brussel. Hij drinkt altijd koffie.', en: 'Bram works in Brussels. He always drinks coffee.', image: 'man-working' },
      { nl: 'Bram heeft koffie. Hij is blij.', en: 'Bram has coffee. He is happy.', image: 'man-happy' },
      { nl: 'Lotte is ziek. Zij drinkt thee en water.', en: 'Lotte is ill. She is drinking tea and water.', image: 'woman-sick' },
      { nl: 'Het kind speelt graag op straat.', en: 'The child likes playing in the street.', image: 'child-playing' },
      { nl: 'Dit is de oude man. Hij leest ook graag.', en: 'This is the old man. He likes reading too.', image: 'old-man' },
      { nl: 'Mijn sleutel zit in mijn jas.', en: 'My key is in my coat.', image: 'key' },
    ],
    note: '“De oude man” (de-word: -e). The adverb sits after the verb in every one of these sentences. And “zit” is how Dutch says where a small thing is inside something: de sleutel zit in de jas, in de tas, in de deur.',
  },
  {
    type: 'drill', title: 'All sixteen verbs', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'zijn', 'hebben', 'inversion'],
    instruction: 'Every verb you know, every person. Type the form of the verb in brackets.',
    items: [
      { nl: '___ jij moe?', cue: 'zijn', en: 'Are you tired?', answer: 'Ben' },
      { nl: 'Wij ___ in Leuven.', cue: 'wonen', en: 'We live in Leuven.', answer: 'wonen' },
      { nl: 'Bram ___ in Brussel.', cue: 'werken', en: 'Bram works in Brussels.', answer: 'werkt' },
      { nl: '___ jij graag?', cue: 'lopen', en: 'Do you like walking?', answer: 'Loop' },
      { nl: 'Lotte ___ op de bank.', cue: 'zitten', en: 'Lotte is sitting on the bench.', answer: 'zit' },
      { nl: 'De kat ___ altijd.', cue: 'slapen', en: 'The cat is always asleep.', answer: 'slaapt' },
      { nl: 'Bram ___ graag.', cue: 'koken', en: 'Bram likes cooking.', answer: 'kookt' },
      { nl: 'Het kind ___ op straat.', cue: 'spelen', en: 'The child is playing in the street.', answer: 'speelt' },
      { nl: '___ jij thuis?', cue: 'leren', en: 'Do you study at home?', answer: 'Leer' },
      { nl: 'Wij ___ graag.', cue: 'praten', en: 'We like talking.', answer: 'praten' },
      { nl: 'Jij ___ op Lotte.', cue: 'wachten', en: 'You are waiting for Lotte.', answer: 'wacht' },
      { nl: 'Bram ___ een grote hond.', cue: 'hebben', en: 'Bram has a big dog.', answer: 'heeft' },
      { nl: '___ jij een fiets?', cue: 'hebben', en: 'Do you have a bike?', answer: 'Heb' },
      { nl: 'Wat ___ jij?', cue: 'lezen', en: 'What are you reading?', answer: 'lees' },
      { nl: '___ jij een boek?', cue: 'schrijven', en: 'Are you writing a book?', answer: 'Schrijf' },
      { nl: 'Jij ___ altijd brood.', cue: 'eten', en: 'You always eat bread.', answer: 'eet' },
      { nl: 'Hij ___ graag thee.', cue: 'drinken', en: 'He likes tea.', answer: 'drinkt' },
      { nl: 'Max ___ niet graag.', cue: 'wachten', en: 'Max doesn’t like waiting.', answer: 'wacht' },
      { nl: '___ Lotte thuis?', cue: 'werken', en: 'Does Lotte work at home?', answer: 'Werkt' },
      { nl: 'Zij ___ jong.', cue: 'zijn', en: 'They are young.', answer: 'zijn' },
    ],
    explanation: 'zijn and hebben are irregular (ben, bent, is — heb, hebt, heeft). Every other verb follows one rule: stem, stem + t, infinitive — with the spelling adjusted (woon, zit, kook, lees, schrijf, eet, wacht).',
  },
  {
    type: 'drill', title: 'Change the subject', grammar: ['subject-pronouns', 'present-regular', 'spelling-z-s', 'zijn', 'inversion', 'adverb-position'],
    instruction: 'Rewrite with the new subject. The verb changes; the adverb stays right after it.',
    items: [
      { nl: 'Ik lees graag.', task: 'Change to hij', answer: 'Hij leest graag.' },
      { nl: 'Ik schrijf graag.', task: 'Change to Bram', answer: 'Bram schrijft graag.' },
      { nl: 'Ik eet altijd een appel.', task: 'Change to jij', answer: 'Jij eet altijd een appel.' },
      { nl: 'Hij drinkt nooit koffie.', task: 'Change to wij', answer: 'Wij drinken nooit koffie.' },
      { nl: 'Wij hebben geen kaas.', task: 'Change to ik', answer: 'Ik heb geen kaas.' },
      { nl: 'Ik kook altijd thuis.', task: 'Change to Bram', answer: 'Bram kookt altijd thuis.' },
      { nl: 'Ik praat graag.', task: 'Change to wij', answer: 'Wij praten graag.' },
      { nl: 'Hij wacht op Lotte.', task: 'Change to jij', answer: 'Jij wacht op Lotte.' },
      { nl: 'Lotte leest een oud boek.', task: 'Change to jullie', answer: 'Jullie lezen een oud boek.' },
      { nl: 'Ik ben blij.', task: 'Change to hij', answer: 'Hij is blij.' },
      { nl: 'Schrijf jij thuis?', task: 'Change to hij', answer: 'Schrijft hij thuis?' },
      { nl: 'Ik leer graag.', task: 'Change to zij (they)', answer: 'Zij leren graag.' },
      { nl: 'Ik loop graag.', task: 'Change to Lotte', answer: 'Lotte loopt graag.' },
    ],
  },
  {
    type: 'drill', title: 'Aged cheese, new coats', grammar: ['adjective-e', 'de-het', 'hij-het-things'],
    instruction: 'Type the adjective in the right form — or replace the noun with hij or het, as the task says.',
    items: [
      { nl: 'Lotte leest een ___ boek.', cue: 'mooi', en: 'Lotte is reading a beautiful book.', answer: 'mooi' },
      { nl: 'De ___ man leest ook graag.', cue: 'oud', en: 'The old man likes reading too.', answer: 'oude' },
      { nl: 'Bram eet graag ___ kaas.', cue: 'oud', en: 'Bram likes aged cheese.', answer: 'oude' },
      { nl: 'Wij wonen in een ___ huis.', cue: 'groot', en: 'We live in a big house.', answer: 'groot' },
      { nl: 'Bram eet het ___ brood.', cue: 'oud', en: 'Bram eats the stale bread.', answer: 'oude' },
      { nl: 'Wij hebben ___ brood.', cue: 'oud', en: 'We have stale bread.', answer: 'oud' },
      { nl: 'Bram heeft een ___ jas.', cue: 'nieuw', en: 'Bram has a new coat.', answer: 'nieuwe' },
      { image: 'car', nl: 'Dit is een ___ auto.', cue: 'nieuw', en: 'This is a new car.', answer: 'nieuwe' },
      { nl: 'Het ___ kind speelt op straat.', cue: 'klein', en: 'The small child is playing in the street.', answer: 'kleine' },
      { nl: 'Max is een ___ hond.', cue: 'groot', en: 'Max is a big dog.', answer: 'grote' },
      { nl: 'De kaas is oud.', task: 'Use hij or het', answer: 'Hij is oud.' },
      { nl: 'Het water is hier.', task: 'Use hij or het', answer: 'Het is hier.' },
      { nl: 'De boom is groot.', task: 'Use hij or het', answer: 'Hij is groot.' },
      { nl: 'De sleutel zit in de deur.', task: 'Use hij or het', answer: 'Hij zit in de deur.' },
      { nl: 'De kat is lief.', task: 'Use hij or het', answer: 'Hij is lief.' },
    ],
    explanation: 'The -e disappears only for a het-word with een or with no article at all (een mooi boek, oud brood). Everywhere else it is there: het oude brood, het kleine kind, oude kaas. “Oud” means stale when it is about bread, and aged when it is about cheese. De-words become hij, het-words become het.',
  },
  {
    type: 'drill', title: 'Ask the question', grammar: ['question-word', 'inversion', 'adverb-position'],
    instruction: 'Here is the answer. Write the question that asks for it, with the question word given.',
    items: [
      { nl: 'Lotte leest een boek.', task: 'Ask with “wat”', answer: 'Wat leest Lotte?' },
      { nl: 'Bram schrijft een boek.', task: 'Ask with “wat”', answer: 'Wat schrijft Bram?' },
      { nl: 'Lotte drinkt graag thee.', task: 'Ask with “wat” — keep “graag”', answer: 'Wat drinkt Lotte graag?' },
      { nl: 'Lotte leest graag op de bank.', task: 'Ask with “waar” — keep “graag”', answer: 'Waar leest Lotte graag?' },
      { nl: 'De sleutel is in de tas.', task: 'Ask with “waar”', answer: 'Waar is de sleutel?' },
      { nl: 'Ik eet graag kaas.', task: 'Ask “jij” with “wat” — keep “graag”', answer: 'Wat eet jij graag?' },
      { nl: 'Wij wonen in Leuven.', task: 'Ask “jullie” with “waar”', answer: 'Waar wonen jullie?' },
      { nl: 'Ik schrijf graag in bed.', task: 'Ask “jij” with “waar” — keep “graag”', answer: 'Waar schrijf jij graag?' },
    ],
    explanation: 'Question word, verb, subject, adverb: Wat drinkt Lotte graag? Waar schrijf jij graag?',
  },
  {
    type: 'arrange', title: 'Where do you like to write?', grammar: ['question-word', 'adverb-position', 'spelling-z-s'],
    instruction: 'Build: “Where do you like to write?” Two words are left over.',
    nl: 'Waar schrijf jij graag?', en: 'Where do you like to write?', image: 'man-writing', distractors: ['schrijft', 'wat'],
  },
  {
    type: 'arrange', title: 'No cheese in the house', grammar: ['hebben', 'geen-niet', 'yes-no-question'],
    instruction: 'Build: “Do you have cheese? No, I don’t have any cheese.”',
    nl: 'Heb jij kaas? Nee, ik heb geen kaas.', en: 'Do you have cheese? No, I don’t have any cheese.', image: 'cheese', distractors: ['hebt', 'niet'],
  },
  {
    type: 'drill', title: 'True for Bram and Lotte?', grammar: ['yes-no-question', 'adverb-position', 'hebben', 'adjective-e'], choices: ['Ja', 'Nee'],
    instruction: 'Everything you know about them, from lesson 1 until now. Listen and answer.',
    items: [
      { nl: 'Drinkt Bram altijd koffie?', answer: 'Ja' },
      { nl: 'Drinkt Lotte graag koffie?', answer: 'Nee' },
      { nl: 'Drinkt Lotte graag thee?', answer: 'Ja' },
      { nl: 'Werkt Lotte in Brussel?', answer: 'Nee' },
      { nl: 'Heeft Bram een fiets?', answer: 'Nee' },
      { nl: 'Is Max een kleine hond?', answer: 'Nee' },
      { nl: 'Wonen Bram en Lotte in Leuven?', answer: 'Ja' },
      { nl: 'Wonen Bram en Lotte in een klein huis?', answer: 'Nee' },
      { nl: 'Schrijft Bram een boek?', answer: 'Ja' },
    ],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Koffie of thee?', image: 'people-home', grammar: ['adverb-position', 'spelling-z-s', 'zijn', 'adjective-e', 'question-word', 'inversion', 'geen-niet', 'hij-het-things'],
    instruction: 'A morning at home in Leuven. Read, listen to every line, then read it again without the English.',
    lines: [
      { speaker: 'Bram', nl: 'Lotte, drink jij koffie of thee?', en: 'Lotte, are you having coffee or tea?', image: 'coffee' },
      { speaker: 'Lotte', nl: 'Thee, Bram. Ik drink nooit koffie.', en: 'Tea, Bram. I never drink coffee.', image: 'tea' },
      { speaker: 'Bram', nl: 'Ik drink altijd koffie. Ik ben moe.', en: 'I always drink coffee. I’m tired.', image: 'man-tired' },
      { speaker: 'Lotte', nl: 'Jij bent altijd moe! Eet jij brood?', en: 'You’re always tired! Are you having bread?', image: 'bread' },
      { speaker: 'Bram', nl: 'Ja, brood en kaas. Ik eet graag oude kaas. En jij?', en: 'Yes, bread and cheese. I like aged cheese. And you?', image: 'cheese' },
      { speaker: 'Lotte', nl: 'Ik eet geen kaas. Ik eet een appel en ik drink water.', en: 'I’m not having cheese. I’m eating an apple and drinking water.', image: 'apple' },
      { speaker: 'Bram', nl: 'En wat lees jij? Een oud boek?', en: 'And what are you reading? An old book?', image: 'book' },
      { speaker: 'Lotte', nl: 'Ja, mijn oude boek. Ik lees graag. En wat schrijf jij, Bram?', en: 'Yes, my old book. I like reading. And what are you writing, Bram?', image: 'book' },
      { speaker: 'Bram', nl: 'Ik schrijf een boek! Ik schrijf graag, hier thuis.', en: 'I’m writing a book! I like writing, here at home.', image: 'man-writing' },
      { speaker: 'Lotte', nl: 'Jij schrijft een boek? Maar jij slaapt altijd!', en: 'You’re writing a book? But you’re always asleep!', image: 'man-sleeping' },
      { speaker: 'Bram', nl: 'Niet altijd! Ik schrijf op mijn telefoon. Waar is hij?', en: 'Not always! I write on my phone. Where is it?', image: 'phone' },
      { speaker: 'Lotte', nl: 'Hier, op het bed. Een boek … mooi, Bram! Ik lees het graag.', en: 'Here, on the bed. A book … lovely, Bram! I’ll gladly read it.', image: 'bed' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'adverb-position'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the conversation. Answer without looking back.',
    items: [
      { nl: 'Drinkt Lotte thee?', answer: 'Ja' },
      { nl: 'Is Bram moe?', answer: 'Ja' },
      { nl: 'Eet Lotte kaas?', answer: 'Nee' },
      { nl: 'Drinkt Lotte water?', answer: 'Ja' },
      { nl: 'Leest Lotte een oud boek?', answer: 'Ja' },
      { nl: 'Schrijft Lotte een boek?', answer: 'Nee' },
      { nl: 'Is de telefoon op het bed?', answer: 'Ja' },
    ],
  },
  {
    type: 'drill', title: 'Answer in a full sentence', grammar: ['question-word', 'adverb-position', 'geen-niet', 'niet', 'spelling-z-s'], task: 'Answer in full',
    instruction: 'Answer each question about the story with a complete sentence. Use the name or a pronoun — both are fine.',
    items: [
      { nl: 'Wat drinkt Bram altijd?', answer: 'Bram drinkt altijd koffie.', accept: ['Hij drinkt altijd koffie.'] },
      { nl: 'Drinkt Lotte koffie?', answer: 'Nee, Lotte drinkt geen koffie.', accept: ['Nee, zij drinkt geen koffie.', 'Nee, Lotte drinkt nooit koffie.', 'Nee, zij drinkt nooit koffie.', 'Nee, Lotte drinkt geen koffie, maar thee.', 'Nee, zij drinkt geen koffie, maar thee.'] },
      { nl: 'Wat eet Bram graag?', answer: 'Bram eet graag oude kaas.', accept: ['Hij eet graag oude kaas.', 'Bram eet graag kaas.', 'Hij eet graag kaas.'] },
      { nl: 'Wat eet Lotte?', answer: 'Lotte eet een appel.', accept: ['Zij eet een appel.'] },
      { nl: 'Wat schrijft Bram?', answer: 'Bram schrijft een boek.', accept: ['Hij schrijft een boek.'] },
      { nl: 'Waar is de telefoon?', answer: 'De telefoon is op het bed.', accept: ['Hij is op het bed.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['adverb-position', 'spelling-z-s', 'geen-niet'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'Bram drinkt altijd koffie.' },
      { listen: 'Lotte drinkt geen koffie, maar thee.' },
      { listen: 'Schrijf jij graag?' },
      { listen: 'Bram eet graag oude kaas.' },
      { listen: 'Het kind drinkt water en eet een appel.' },
      { listen: 'Mijn sleutel is in mijn tas.' },
      { listen: 'Wij hebben geen brood.' },
      { listen: 'Jullie lezen niet graag.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['adverb-position', 'spelling-z-s', 'geen', 'adjective-e', 'hebben', 'question-word'],
    instruction: 'Translate. No hints — watch the verb forms, the adverb position and geen versus niet.',
    items: [
      { en: 'I like reading.', answer: 'Ik lees graag.' },
      { en: 'Lotte doesn’t drink coffee, but tea.', answer: 'Lotte drinkt geen koffie, maar thee.' },
      { en: 'He is writing a book.', answer: 'Hij schrijft een boek.' },
      { en: 'Are you eating an apple?', answer: 'Eet jij een appel?' },
      { en: 'I don’t eat cheese.', answer: 'Ik eet geen kaas.' },
      { en: 'Lotte is ill and drinks water.', answer: 'Lotte is ziek en drinkt water.', accept: ['Lotte is ziek en zij drinkt water.'] },
      { en: 'Where do you like to write?', answer: 'Waar schrijf jij graag?' },
      { en: 'Bram reads in bed.', answer: 'Bram leest in bed.' },
      { en: 'My phone is on the bed.', answer: 'Mijn telefoon is op het bed.' },
      { en: 'My key is in my coat.', answer: 'Mijn sleutel zit in mijn jas.', accept: ['Mijn sleutel is in mijn jas.'] },
      { en: 'The old man likes reading too.', answer: 'De oude man leest ook graag.' },
      { en: 'Bram has a big dog and always drinks coffee.', answer: 'Bram heeft een grote hond en drinkt altijd koffie.', accept: ['Bram heeft een grote hond en hij drinkt altijd koffie.'] },
    ],
  },
  {
    type: 'arrange', title: 'Not coffee, but tea', grammar: ['geen-niet', 'geen'],
    instruction: 'Build: “Lotte doesn’t drink coffee, but tea.” Two words are left over.',
    nl: 'Lotte drinkt geen koffie, maar thee.', en: 'Lotte doesn’t drink coffee, but tea.', image: 'tea', distractors: ['niet', 'drink'],
  },
  {
    type: 'drill', title: 'Everything together', grammar: ['spelling-z-s', 'adverb-position', 'de-het', 'hij-het-things', 'geen-niet', 'dit-is', 'inversion', 'adjective-e'],
    instruction: 'A last mixed round. Type every answer.',
    items: [
      { nl: '___ water', cue: 'de / het', answer: 'het' },
      { nl: '___ kaas', cue: 'de / het', answer: 'de' },
      { nl: 'Hij ___ een boek.', cue: 'lezen', en: 'He is reading a book.', answer: 'leest' },
      { nl: 'Wij ___ een boek.', cue: 'schrijven', en: 'We are writing a book.', answer: 'schrijven' },
      { nl: '___ jij brood?', cue: 'eten', en: 'Do you eat bread?', answer: 'Eet' },
      { nl: 'Jij ___ graag thee.', cue: 'drinken', en: 'You like tea.', answer: 'drinkt' },
      { nl: 'Ik schrijf graag.', task: 'Change to jij and make it a question', answer: 'Schrijf jij graag?' },
      { en: 'The child likes playing in the street.', answer: 'Het kind speelt graag op straat.' },
      { en: 'Are you waiting for Lotte?', answer: 'Wacht jij op Lotte?' },
      { listen: 'De kat zit in de boom, niet in het raam.' },
      { image: 'apple', nl: 'Wat is dit?', task: 'Answer in full', answer: 'Dit is een appel.', accept: ['Het is een appel.'] },
      { nl: 'De kaas is oud.', task: 'Use hij or het', answer: 'Hij is oud.' },
      { nl: 'Ik heb thee.', task: 'Make it negative', answer: 'Ik heb geen thee.' },
      { en: 'The young woman is reading a big book.', answer: 'De jonge vrouw leest een groot boek.' },
    ],
  },
  {
    type: 'complete', title: 'Reading, eating, drinking, writing — in the right order',
    instruction: 'Four new verbs in every person, the z that turns into s and the v that turns into f, coffee and cheese without “een”, and the position of graag, altijd, nooit and niet in simple statements and questions. All of it comes back in lesson 6.',
  },
];
