/**
 * Lesson 6 — Vandaag ga ik naar het park.
 * Targets: gaan, komen, vandaag, morgen, park, winkel, school, station, stad, trein.
 * Structure: naar, nu, dan, met.
 * Grammar: gaan (and komen) · the verb stays second (V2 inversion) · time (manner) place.
 * The last lesson of the volume: every earlier verb, article, negation and adverb
 * rule is combined here with the new word order. See docs/CURRICULUM.md.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Places, days and going', grammar: ['dit-is', 'de-het', 'gaan'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice. Watch where the verb stands.',
    cards: [
      { nl: 'Dit is het park.', en: 'This is the park.', image: 'park' },
      { nl: 'Dit is een winkel.', en: 'This is a shop.', image: 'shop' },
      { nl: 'Dit is een school. Het kind gaat naar school.', en: 'This is a school. The child goes to school.', image: 'school' },
      { nl: 'Dit is het station.', en: 'This is the station.', image: 'station' },
      { nl: 'Leuven is een mooie stad.', en: 'Leuven is a beautiful city.', image: 'city' },
      { nl: 'Bram gaat met de trein naar Brussel.', en: 'Bram goes to Brussels by train.', image: 'train' },
      { nl: 'Nu komt de trein.', en: 'Now the train is coming.', image: 'train' },
      { nl: 'Bram en Max gaan naar het park.', en: 'Bram and Max are going to the park.', image: 'man-dog' },
      { nl: 'Kom jij ook, Lotte? — Ja, ik kom!', en: 'Are you coming too, Lotte? — Yes, I’m coming!', image: 'woman' },
      { nl: 'Lotte werkt vandaag thuis.', en: 'Lotte is working at home today.', image: 'woman-working' },
      { nl: 'Morgen gaat Bram naar de winkel.', en: 'Tomorrow Bram is going to the shop.', image: 'shop' },
      { nl: 'Lotte leest nu een boek.', en: 'Lotte is reading a book now.', image: 'woman-reading' },
      { nl: 'Bram drinkt koffie. Dan eet hij brood.', en: 'Bram drinks coffee. Then he eats bread.', image: 'man-eating' },
    ],
    note: '“het park”, “het station”, “de winkel”, “de school”, “de stad”, “de trein”. “naar” = to (towards a place), “met” = with / by, “nu” = now, “dan” = then (next). “Morgen” = tomorrow. gaan = to go, komen = to come. In “Nu komt de trein” and “Morgen gaat Bram” the verb comes before the subject — that is the grammar of this lesson.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['dit-is', 'de-het'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Dit is een station.', en: 'This is a station.', answer: 'station',
    choices: [{ image: 'school', nl: 'een school' }, { image: 'station', nl: 'een station' }, { image: 'shop', nl: 'een winkel' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['gaan'],
    instruction: 'Listen without reading. Where are they going?',
    nl: 'Vandaag gaan Bram en Max naar het park.', en: 'Today Bram and Max are going to the park.', answer: 'park',
    choices: [{ image: 'shop', nl: 'de winkel' }, { image: 'park', nl: 'het park' }, { image: 'station', nl: 'het station' }, { image: 'school', nl: 'de school' }],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['gaan', 'time-place'],
    instruction: 'Listen. Where is Bram going tomorrow?',
    nl: 'Bram gaat morgen naar de winkel.', en: 'Bram is going to the shop tomorrow.', answer: 'shop',
    choices: [{ image: 'park', nl: 'het park' }, { image: 'city', nl: 'de stad' }, { image: 'shop', nl: 'de winkel' }],
  },
  {
    type: 'picture', listen: true, title: 'What is coming now?', grammar: ['v2-inversion'],
    instruction: 'Listen and choose the picture that matches.',
    nl: 'Nu komt de trein.', en: 'Now the train is coming.', answer: 'train',
    choices: [{ image: 'car', nl: 'de auto' }, { image: 'bike', nl: 'de fiets' }, { image: 'train', nl: 'de trein' }, { image: 'child', nl: 'het kind' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['de-het'],
    instruction: 'For a picture, type the noun with its article. For English, type the Dutch.',
    items: [
      { image: 'park', answer: 'het park' },
      { image: 'shop', answer: 'de winkel' },
      { image: 'school', answer: 'de school' },
      { image: 'station', answer: 'het station' },
      { image: 'city', answer: 'de stad' },
      { image: 'train', answer: 'de trein' },
      { en: 'today', answer: 'vandaag' },
      { en: 'tomorrow', answer: 'morgen' },
      { en: 'to come', answer: 'komen' },
      { en: 'to the park', answer: 'naar het park' },
      { en: 'to the station', answer: 'naar het station' },
      { en: 'by train', answer: 'met de trein' },
      { en: 'with Max', answer: 'met Max' },
    ],
    explanation: 'Two het-words (het park, het station, like het huis and het boek) and four de-words (de winkel, de school, de stad, de trein). Learn them in pairs from the start. “By train” keeps its article in Dutch: met de trein.',
  },
  {
    type: 'drill', title: 'Hear and spell',
    instruction: 'Play each one and type it. The Dutch “g” in vandaag and morgen is a soft rasp at the back of the throat — in Flanders softer than in the Netherlands.',
    items: [
      { listen: 'vandaag' },
      { listen: 'morgen' },
      { listen: 'trein' },
      { listen: 'station' },
      { listen: 'Vandaag gaan wij naar het park.' },
      { listen: 'Morgen ga ik naar de winkel.' },
      { listen: 'Ik kom met de trein.' },
      { listen: 'Leuven is een mooie stad.' },
    ],
    explanation: 'vandaag has a long “aa”: van-daag. naar has the same long “aa”. trein has the “ei” of klein. station is said sta-SJON, stress at the end.',
  },

  // ——— Grammar: gaan ———
  {
    part: 'Grammar', type: 'grammar', title: 'gaan: to go', grammar: ['gaan', 'spelling-stem', 'subject-pronouns'],
    body: [
      '**gaan** (to go) is short and looks unusual, but it follows the pattern you already know from wonen and werken: **ik** + stem, **jij / hij / zij** + stem + **t**, **wij / jullie / zij** (they) = the infinitive.',
      'The stem is **ga**, with one *a*. This is the stem-spelling rule from lesson 3, seen from the other side: a vowel at the open end of a syllable is already long, so one letter is enough (*ga*, like *ja*). Add **-t** and the syllable closes, so the double letter comes back: *jij **gaat***, *hij **gaat***. Same logic as *sla-pen → ik slaap*.',
      'In a question the verb comes first and **jij** takes the bare stem, exactly as in *Woon jij …?* and *Ben jij …?*: ***Ga** jij naar huis?* Never *gaat jij*.',
      'The place you go to follows **naar** (to, towards): *naar het park, naar de winkel, naar het station, naar Brussel*. Two places are special. **naar huis** (home) has no article, and neither has **naar school** when you go there to learn: *Het kind gaat naar school.* And **naar de stad** is how you say “into town”. Keep *naar* (movement) apart from *in* and *op* (location): *Ik ga **naar** het park* — *Ik zit **in** het park* — *Ik zit **op** de bank*.',
      '**gaan + infinitive** makes a plan, like English “going to”: *Ik ga slapen. Wij gaan eten.* The infinitive stands at the very **end**, and there is no word for “to”: *Bram gaat koffie **drinken**.*',
      'Dutch uses the plain present for “I go”, “I am going” and, with a time word, “I will go”. There is no separate -ing form to learn.',
    ],
    tables: [
      { caption: 'gaan', rows: [
        { nl: 'ik ga', en: 'I go / I am going' },
        { nl: 'jij gaa[t]', en: 'you go' },
        { nl: 'hij gaa[t]', en: 'he goes' },
        { nl: 'zij gaa[t]', en: 'she goes' },
        { nl: 'wij gaa[n]', en: 'we go' },
        { nl: 'jullie gaa[n]', en: 'you (plural) go' },
        { nl: 'zij gaa[n]', en: 'they go' },
        { nl: 'ga jij?', en: 'are you going? — no -t' },
      ] },
      { caption: 'naar + place', rows: [
        { nl: 'naar het park', en: 'to the park' },
        { nl: 'naar de winkel', en: 'to the shop' },
        { nl: 'naar het station', en: 'to the station' },
        { nl: 'naar Brussel', en: 'to Brussels' },
        { nl: 'naar de stad', en: 'into town' },
        { nl: 'naar huis', en: 'home — no article' },
        { nl: 'naar school', en: 'to school — no article' },
      ] },
    ],
    examples: [
      { nl: 'Ik ga naar de winkel.', en: 'I am going to the shop.' },
      { nl: 'Ga jij naar het station?', en: 'Are you going to the station?' },
      { nl: 'Lotte gaat naar huis.', en: 'Lotte is going home.' },
      { nl: 'Het kind gaat naar school.', en: 'The child goes to school.' },
      { nl: 'Jullie gaan niet naar Brussel.', en: 'You (plural) are not going to Brussels.' },
      { nl: 'Wij gaan eten.', en: 'We are going to eat.' },
      { nl: 'Bram gaat koffie drinken.', en: 'Bram is going to drink coffee.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate gaan', grammar: ['gaan', 'subject-pronouns'],
    instruction: 'Type the form of gaan for every person. Say “ik ga, jij gaat …” out loud as you go.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'ga' },
      { label: 'jij', gloss: 'you', answer: 'gaat' },
      { label: 'hij', gloss: 'he', answer: 'gaat' },
      { label: 'zij', gloss: 'she', answer: 'gaat' },
      { label: 'wij', gloss: 'we', answer: 'gaan' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'gaan' },
      { label: 'zij', gloss: 'they', answer: 'gaan' },
      { label: 'Bram en Lotte', gloss: 'they', answer: 'gaan' },
    ],
    explanation: 'One a in ga, two in gaat and gaan. zij + gaat = she, zij + gaan = they: the verb tells you which.',
  },
  {
    type: 'drill', title: 'ga, gaat or gaan?', grammar: ['gaan', 'inversion', 'yes-no-question'], choices: ['ga', 'gaat', 'gaan'],
    instruction: 'Choose the form. Look at the subject — and at whether jij comes before or after the verb.',
    items: [
      { nl: 'Ik ___ naar het park.', answer: 'ga' },
      { nl: 'Lotte ___ naar de winkel.', answer: 'gaat' },
      { nl: '___ jij naar huis?', answer: 'ga' },
      { nl: '___ Bram naar het station?', answer: 'gaat' },
      { nl: '___ jullie naar Gent?', answer: 'gaan' },
      { nl: 'Het kind ___ naar school.', answer: 'gaat' },
      { nl: 'Max en Bram ___ naar het park.', answer: 'gaan' },
    ],
  },
  {
    type: 'drill', title: 'Type the form of gaan', grammar: ['gaan', 'inversion', 'niet'],
    instruction: 'Type the missing form. The infinitive in brackets is the verb you need.',
    items: [
      { nl: 'Ik ___ naar de winkel.', cue: 'gaan', answer: 'ga' },
      { nl: 'Lotte ___ naar huis.', cue: 'gaan', answer: 'gaat' },
      { nl: 'Wij ___ naar de stad.', cue: 'gaan', answer: 'gaan' },
      { nl: '___ jij naar Brussel?', cue: 'gaan', answer: 'Ga' },
      { nl: 'Jij ___ naar het station.', cue: 'gaan', answer: 'gaat' },
      { nl: 'Max ___ niet naar de winkel.', cue: 'gaan', answer: 'gaat' },
      { nl: 'Het kind ___ niet naar school.', cue: 'gaan', answer: 'gaat' },
      { nl: 'Ik ___ slapen.', cue: 'gaan', en: 'I am going to sleep.', answer: 'ga' },
      { nl: '___ Lotte naar de winkel of naar het park?', cue: 'gaan', answer: 'Gaat' },
    ],
  },

  // ——— Grammar: komen and met ———
  {
    type: 'grammar', title: 'komen: to come — and met', grammar: ['gaan', 'present-regular', 'spelling-stem', 'inversion'],
    body: [
      '**komen** (to come) takes the endings you know: **ik kom**, **jij / hij / zij komt**, **wij / jullie / zij komen**. In a question jij takes the bare stem, as always: ***Kom** jij ook?* Never *komt jij*.',
      'Watch the stem. The rule from lesson 3 would give you *koom* (like *wonen → ik woon*), but the stem is **kom**, with one *o* — and it really is short: *kom* has the short o of *op*, while *komen* has the long o of *wonen*. Singular short, infinitive and plural long. It is the only verb in this book that does this, so learn **ik kom, hij komt** as they stand. Never *ik koom*.',
      '**gaan or komen?** As in English, *gaan* is movement away, towards somewhere else; *komen* is movement towards the speaker, or towards the place you are talking about. *Ik ga naar de winkel.* — *Kom jij ook?* (Are you coming too?) — *Nu komt de trein.* (The train is coming in.) **komen … thuis** means “to get home”: *Dan kom ik thuis. Bram komt thuis.*',
      '**met** means “with”: *met Max, met Lotte*. With transport it means “by” — and Dutch keeps the article that English drops: *met **de** trein* (by train), *met **de** fiets*, *met **de** auto*. Never *met trein*. *met* is also the partner of *praten*: *Lotte praat **met** de oude man.*',
      'In a sentence, the met-part comes **before** the place: *Wij gaan **met Max** naar het park. Bram gaat **met de trein** naar Brussel.* You will see why on the time-and-place page.',
    ],
    tables: [
      { caption: 'komen', rows: [
        { nl: 'ik kom', en: 'I come / I am coming' },
        { nl: 'jij kom[t]', en: 'you come' },
        { nl: 'hij kom[t]', en: 'he comes' },
        { nl: 'zij kom[t]', en: 'she comes' },
        { nl: 'wij kom[en]', en: 'we come' },
        { nl: 'jullie kom[en]', en: 'you (plural) come' },
        { nl: 'zij kom[en]', en: 'they come' },
        { nl: 'kom jij?', en: 'are you coming? — no -t' },
      ] },
      { caption: 'met', rows: [
        { nl: 'met Max', en: 'with Max' },
        { nl: 'met de trein', en: 'by train' },
        { nl: 'met de fiets', en: 'by bike' },
        { nl: 'met de auto', en: 'by car' },
      ] },
    ],
    examples: [
      { nl: 'Ik kom met de trein.', en: 'I am coming by train.' },
      { nl: 'Kom jij ook?', en: 'Are you coming too?' },
      { nl: 'Lotte komt met de fiets.', en: 'Lotte is coming by bike.' },
      { nl: 'De trein komt.', en: 'The train is coming.' },
      { nl: 'Wij gaan met Max naar het park.', en: 'We are going to the park with Max.' },
      { nl: 'Bram komt thuis.', en: 'Bram is getting home.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate komen', grammar: ['present-regular', 'subject-pronouns'],
    instruction: 'Type the form of komen for every person. Say “ik kom, jij komt …” out loud.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'kom' },
      { label: 'jij', gloss: 'you', answer: 'komt' },
      { label: 'hij', gloss: 'he', answer: 'komt' },
      { label: 'zij', gloss: 'she', answer: 'komt' },
      { label: 'wij', gloss: 'we', answer: 'komen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'komen' },
      { label: 'zij', gloss: 'they', answer: 'komen' },
      { label: 'de trein', gloss: 'it', answer: 'komt' },
    ],
    explanation: 'One o everywhere — kom, komt, komen. The difference is heard, not written: kom is short, komen is long.',
  },
  {
    type: 'drill', title: 'Type the form of komen', grammar: ['present-regular', 'inversion', 'niet'],
    instruction: 'Type the missing form of komen. Watch jij before and after the verb.',
    items: [
      { nl: 'Ik ___ met de trein.', cue: 'komen', answer: 'kom' },
      { nl: 'Lotte ___ met de fiets.', cue: 'komen', answer: 'komt' },
      { nl: 'Wij ___ met de auto.', cue: 'komen', answer: 'komen' },
      { nl: '___ jij ook?', cue: 'komen', answer: 'Kom' },
      { nl: 'Max ___ ook.', cue: 'komen', answer: 'komt' },
      { nl: '___ jullie met de trein?', cue: 'komen', answer: 'Komen' },
      { nl: 'De trein ___ nu.', cue: 'komen', answer: 'komt' },
      { nl: 'Bram en Lotte ___ niet met de auto.', cue: 'komen', answer: 'komen' },
      { nl: 'Ik ___ nu naar huis.', cue: 'komen', en: 'I am coming home now.', answer: 'kom' },
      { nl: '___ Lotte met de trein of met de fiets?', cue: 'komen', answer: 'Komt' },
    ],
  },
  {
    type: 'drill', title: 'gaan or komen — with met', grammar: ['gaan', 'present-regular', 'yes-no-question', 'adverb-position'],
    instruction: 'Translate. Going away = gaan, coming here = komen. “By train” is met de trein; the met-part comes before naar + place.',
    items: [
      { en: 'Are you coming too? (one person)', answer: 'Kom jij ook?' },
      { en: 'I am coming by train.', answer: 'Ik kom met de trein.' },
      { en: 'Max is coming too.', answer: 'Max komt ook.' },
      { en: 'We are going to the park with Max.', answer: 'Wij gaan met Max naar het park.' },
      { en: 'Lotte is going to the shop by bike.', answer: 'Lotte gaat met de fiets naar de winkel.' },
      { en: 'The child goes to school.', answer: 'Het kind gaat naar school.' },
      { en: 'Are you (plural) coming by car?', answer: 'Komen jullie met de auto?' },
      { en: 'Bram is not coming by train.', answer: 'Bram komt niet met de trein.' },
      { en: 'Lotte is talking with the old man.', answer: 'Lotte praat met de oude man.' },
      { en: 'Bram always goes to Brussels by train.', answer: 'Bram gaat altijd met de trein naar Brussel.' },
    ],
    explanation: 'met de trein, met de fiets, met de auto — the article stays. niet and altijd still come straight after the verb.',
  },
  {
    type: 'drill', title: 'naar, in, op or met?', grammar: ['gaan', 'present-regular'],
    instruction: 'Going somewhere takes “naar”; being somewhere takes “in” or “op”; “with / by” is “met”. Type the right one.',
    items: [
      { nl: 'Ik ga ___ het park.', cue: 'naar / in / op / met', answer: 'naar' },
      { nl: 'Ik zit ___ het park.', cue: 'naar / in / op / met', answer: 'in' },
      { nl: 'Lotte zit ___ de bank.', cue: 'naar / in / op / met', answer: 'op' },
      { nl: 'Bram gaat ___ Brussel.', cue: 'naar / in / op / met', answer: 'naar' },
      { nl: 'Bram gaat ___ de trein.', cue: 'naar / in / op / met', en: 'Bram goes by train.', answer: 'met' },
      { nl: 'Wij wonen ___ Leuven.', cue: 'naar / in / op / met', answer: 'in' },
      { nl: 'Het kind gaat ___ school.', cue: 'naar / in / op / met', answer: 'naar' },
      { nl: 'Lotte praat ___ de oude man.', cue: 'naar / in / op / met', answer: 'met' },
      { nl: 'Wij wachten ___ de trein.', cue: 'naar / in / op / met', en: 'We are waiting for the train.', answer: 'op' },
    ],
    explanation: 'naar = movement towards a place. in / op = where something is. met = with, or by for transport. Two fixed pairs: praten met (talk with) and wachten op (wait for). “naar huis” and “naar school” have no article; “thuis” (at home) needs no preposition at all.',
  },
  {
    type: 'drill', title: 'Plans with gaan', grammar: ['gaan', 'inversion', 'niet'],
    instruction: 'Translate. gaan takes the second place, the infinitive goes to the end — no word for “to”.',
    items: [
      { en: 'I am going to sleep.', answer: 'Ik ga slapen.' },
      { en: 'We are going to cook.', answer: 'Wij gaan koken.' },
      { en: 'Lotte is going to write.', answer: 'Lotte gaat schrijven.' },
      { en: 'The child is going to play.', answer: 'Het kind gaat spelen.' },
      { en: 'Bram is going to drink coffee.', answer: 'Bram gaat koffie drinken.' },
      { en: 'Are you going to drink water? (one person)', answer: 'Ga jij water drinken?' },
      { en: 'I am not going to work.', answer: 'Ik ga niet werken.' },
      { en: 'Are you (plural) going to eat bread?', answer: 'Gaan jullie brood eten?' },
    ],
    explanation: 'Object before the infinitive: “koffie drinken”, “water drinken”, “brood eten”. “niet” comes after gaan: “Ik ga niet werken.”',
  },

  // ——— Grammar: the verb stays second ———
  {
    type: 'grammar', title: 'The verb is always second', grammar: ['v2-inversion', 'inversion', 'question-word', 'niet'],
    body: [
      'This is the most important rule of Dutch word order: in a statement, the conjugated verb is **always the second element**. An element is a sentence part, not a single word: *Bram*, *de oude man*, *vandaag* and *in het park* each count as one.',
      'Most statements start with the subject, so the verb follows it: *Ik **ga** vandaag naar het park.* But Dutch very often starts with something else — a time (*vandaag, morgen, nu, dan*) or a place (*hier, thuis, in het park*). The verb keeps its second place, so the subject has to move **behind** it: *Vandaag **ga** ik naar het park.* Never *Vandaag ik ga* — English allows “Today I go”, Dutch does not. This is the most common mistake English speakers make in Dutch, for years.',
      'You already know this move. In *Ben jij moe?* and *Waar woon jij?* the subject also stands behind the verb. A question word like *waar* takes the first slot exactly as *vandaag* does: ***Waar** woon jij?* — ***Hier** woon ik.* Questions and these statements are one mechanism, not two rules.',
      'And the jij rule comes with it. Whenever **jij / je** stands directly behind the verb, the verb loses its **-t — in statements too**: *Morgen **ga** jij naar de winkel. Morgen **kom** jij met de trein. Nu **ben** jij moe. Thuis **heb** jij een kat.* Only jij/je: *hij*, *zij* and *Bram* keep the -t (*Morgen **gaat** hij*). Stems that already end in -t show no change: *Nu **zit** jij. Dan **eet** jij. Nu **wacht** jij.*',
      'The rest of the sentence stays where it was. *niet*, *geen*, *graag*, *altijd* and *nooit* follow the verb-and-subject pair: *Vandaag gaat Bram **niet** naar Brussel. Thuis drinkt Bram **altijd** koffie.*',
      'Some words take no slot at all: *ja* and *nee*, a name you call someone by (*Lotte, …*), and the linking words **en, maar, of**. After them the count starts again: *Bram werkt in Brussel, **maar** vandaag **werkt** hij niet.* — *maar* is outside, *vandaag* is first, *werkt* is second.',
      'Why start with the time at all? It is simply how Dutch is spoken: the time or place sets the scene, then comes the news. With a time word the present tense also covers the future: *Morgen ga ik naar de winkel* = “Tomorrow I am going / I will go to the shop”.',
    ],
    tables: [
      { caption: 'Subject first — verb second', rows: [
        { nl: 'Ik [ga] vandaag naar het park.', en: 'I am going to the park today.' },
        { nl: 'Bram [werkt] morgen thuis.', en: 'Bram is working at home tomorrow.' },
        { nl: 'Lotte [leest] nu een boek.', en: 'Lotte is reading a book now.' },
        { nl: 'De trein [komt] nu.', en: 'The train is coming now.' },
      ] },
      { caption: 'Something else first — verb second, subject third', rows: [
        { nl: 'Vandaag [ga] ik naar het park.', en: 'Today I am going to the park.' },
        { nl: 'Morgen [werkt] Bram thuis.', en: 'Tomorrow Bram is working at home.' },
        { nl: 'Nu [leest] Lotte een boek.', en: 'Now Lotte is reading a book.' },
        { nl: 'Nu [komt] de trein.', en: 'Now the train is coming.' },
        { nl: 'Dan [drinkt] hij koffie.', en: 'Then he drinks coffee.' },
        { nl: 'In het park [zit] een oude man.', en: 'In the park an old man is sitting.' },
        { nl: 'Hier [woon] ik.', en: 'This is where I live.' },
      ] },
      { caption: 'jij behind the verb — no -t', rows: [
        { nl: 'Morgen [ga] jij naar de winkel.', en: 'Tomorrow you are going to the shop. (jij gaat → ga jij)' },
        { nl: 'Morgen [kom] jij met de trein.', en: 'Tomorrow you are coming by train. (jij komt → kom jij)' },
        { nl: 'Vandaag [werk] jij thuis.', en: 'Today you are working at home. (jij werkt → werk jij)' },
        { nl: 'Nu [ben] jij moe.', en: 'Now you are tired. (jij bent → ben jij)' },
        { nl: 'Thuis [heb] jij een kat.', en: 'At home you have a cat. (jij hebt → heb jij)' },
        { nl: 'Morgen [gaat] hij naar de winkel.', en: 'Tomorrow he is going to the shop. (hij keeps the -t)' },
      ] },
    ],
    examples: [
      { nl: 'Ben jij moe?', en: 'Are you tired? — verb first: a question.' },
      { nl: 'Waar woon jij?', en: 'Where do you live? — waar first, verb second.' },
      { nl: 'Hier woon ik.', en: 'I live here. — hier first, verb second.' },
      { nl: 'Vandaag gaat Bram niet naar Brussel.', en: 'Today Bram is not going to Brussels.' },
      { nl: 'Bram werkt in Brussel, maar vandaag werkt hij niet.', en: 'Bram works in Brussels, but today he is not working.' },
    ],
  },
  {
    type: 'drill', title: 'Which order?', grammar: ['v2-inversion', 'inversion', 'zijn', 'hebben'],
    instruction: 'Choose the words that fill the gap. The verb must be the second element.',
    items: [
      { nl: 'Vandaag ___ naar het park.', en: 'Today I am going to the park.', choices: ['ik ga', 'ga ik'], answer: 'ga ik' },
      { nl: 'Morgen ___ thuis.', en: 'Tomorrow Bram is working at home.', choices: ['Bram werkt', 'werkt Bram'], answer: 'werkt Bram' },
      { nl: 'Nu ___ een boek.', en: 'Now Lotte is reading a book.', choices: ['leest Lotte', 'Lotte leest'], answer: 'leest Lotte' },
      { nl: 'Nu ___ met Max.', en: 'Now Bram is coming with Max.', choices: ['Bram komt', 'komt Bram'], answer: 'komt Bram' },
      { nl: 'Morgen ___ naar de winkel.', en: 'Tomorrow you are going to the shop.', choices: ['jij gaat', 'gaat jij', 'ga jij'], answer: 'ga jij' },
      { nl: 'Morgen ___ met de trein.', en: 'Tomorrow you are coming by train.', choices: ['jij komt', 'komt jij', 'kom jij'], answer: 'kom jij' },
      { nl: 'Vandaag ___ niet moe, Bram.', en: 'Today you are not tired, Bram.', choices: ['bent jij', 'ben jij', 'jij bent'], answer: 'ben jij' },
      { nl: 'Thuis ___ een kleine kat.', en: 'At home Lotte has a small cat.', choices: ['Lotte heeft', 'heeft Lotte'], answer: 'heeft Lotte' },
    ],
  },
  {
    type: 'drill', title: 'Start with the time', grammar: ['v2-inversion', 'time-place', 'present-regular', 'zijn'],
    instruction: 'Rewrite each sentence so that it starts with the word given. The verb stays second; the subject moves behind it. Watch jij.',
    items: [
      { nl: 'Ik ga vandaag naar het park.', task: 'Start with “vandaag”', answer: 'Vandaag ga ik naar het park.' },
      { nl: 'Bram werkt morgen thuis.', task: 'Start with “morgen”', answer: 'Morgen werkt Bram thuis.' },
      { nl: 'Lotte leest nu een boek.', task: 'Start with “nu”', answer: 'Nu leest Lotte een boek.' },
      { nl: 'Jij gaat morgen naar de winkel.', task: 'Start with “morgen”', answer: 'Morgen ga jij naar de winkel.' },
      { nl: 'Wij komen morgen met de trein.', task: 'Start with “morgen”', answer: 'Morgen komen wij met de trein.' },
      { nl: 'Wij eten vandaag brood met kaas.', task: 'Start with “vandaag”', answer: 'Vandaag eten wij brood met kaas.' },
      { nl: 'Het kind gaat nu naar school.', task: 'Start with “nu”', answer: 'Nu gaat het kind naar school.' },
      { nl: 'Jij werkt vandaag thuis.', task: 'Start with “vandaag”', answer: 'Vandaag werk jij thuis.' },
      { nl: 'Lotte is vandaag ziek.', task: 'Start with “vandaag”', answer: 'Vandaag is Lotte ziek.' },
      { nl: 'Jij bent nu moe.', task: 'Start with “nu”', answer: 'Nu ben jij moe.' },
    ],
    explanation: 'Every time: first word, verb, subject, then the rest unchanged. jij gaat → ga jij, jij werkt → werk jij, jij bent → ben jij.',
  },
  {
    type: 'arrange', title: 'Today, first', grammar: ['v2-inversion', 'gaan'],
    instruction: 'Build: “Today I am going to the park.” Two tiles are traps.',
    nl: 'Vandaag ga ik naar het park.', en: 'Today I am going to the park.', image: 'park', distractors: ['gaat', 'de'],
  },
  {
    type: 'drill', layout: 'table', title: 'Every verb you know', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'zijn', 'hebben', 'gaan', 'subject-pronouns'],
    instruction: 'All eighteen verbs of this book, mixed. The small word under each person is the verb to use. Type the form.',
    items: [
      { label: 'ik', gloss: 'gaan', answer: 'ga' },
      { label: 'jij', gloss: 'zijn', answer: 'bent' },
      { label: 'hij', gloss: 'hebben', answer: 'heeft' },
      { label: 'zij', gloss: 'she · lezen', answer: 'leest' },
      { label: 'wij', gloss: 'eten', answer: 'eten' },
      { label: 'jullie', gloss: 'drinken', answer: 'drinken' },
      { label: 'zij', gloss: 'they · slapen', answer: 'slapen' },
      { label: 'ik', gloss: 'zitten', answer: 'zit' },
      { label: 'jij', gloss: 'lopen', answer: 'loopt' },
      { label: 'hij', gloss: 'wonen', answer: 'woont' },
      { label: 'ik', gloss: 'werken', answer: 'werk' },
      { label: 'jij', gloss: 'komen', answer: 'komt' },
      { label: 'hij', gloss: 'koken', answer: 'kookt' },
      { label: 'wij', gloss: 'spelen', answer: 'spelen' },
      { label: 'zij', gloss: 'she · leren', answer: 'leert' },
      { label: 'ik', gloss: 'praten', answer: 'praat' },
      { label: 'jij', gloss: 'wachten', answer: 'wacht' },
      { label: 'hij', gloss: 'schrijven', answer: 'schrijft' },
    ],
    explanation: 'Two true irregulars (zijn, hebben), gaan with its one-a stem (ga, gaat, gaan), and the spelling traps: zitten → zit (no double t at the end), lopen → loop and koken → kook (the double vowel returns), lezen → lees and schrijven → schrijf (z and v become s and f), praten → praat and wachten → wacht (the stem already ends in t, so no second t) — and komen → kom, the one short stem.',
  },
  {
    type: 'drill', title: 'The verb in second place — every verb', grammar: ['v2-inversion', 'present-regular', 'spelling-stem', 'spelling-z-s', 'hebben', 'zijn', 'adverb-position'],
    instruction: 'Each sentence starts with a time or a place. Type the verb form — and check who stands behind it.',
    items: [
      { nl: 'Morgen ___ jij naar Brussel.', cue: 'gaan', answer: 'ga' },
      { nl: 'Nu ___ Lotte een boek.', cue: 'lezen', answer: 'leest' },
      { nl: 'In het park ___ de oude man op de bank.', cue: 'zitten', answer: 'zit' },
      { nl: 'In het park ___ Max water.', cue: 'drinken', answer: 'drinkt' },
      { nl: 'Dan ___ jij een appel.', cue: 'eten', answer: 'eet' },
      { nl: 'Hier ___ wij.', cue: 'wonen', en: 'This is where we live.', answer: 'wonen' },
      { nl: 'Vandaag ___ jij niet moe.', cue: 'zijn', answer: 'ben' },
      { nl: 'Morgen ___ jij met de trein.', cue: 'komen', answer: 'kom' },
      { nl: 'Nu ___ de kleine kat op het bed.', cue: 'slapen', answer: 'slaapt' },
      { nl: 'Thuis ___ jij een grote hond.', cue: 'hebben', answer: 'heb' },
      { nl: 'Vandaag ___ jij.', cue: 'koken', en: 'Today you are cooking.', answer: 'kook' },
      { nl: 'In het park ___ een kind.', cue: 'spelen', answer: 'speelt' },
      { nl: 'Op school ___ het kind graag.', cue: 'leren', en: 'At school the child likes to learn.', answer: 'leert' },
      { nl: 'Nu ___ Lotte met de oude man.', cue: 'praten', answer: 'praat' },
      { nl: 'Hier ___ een oude vrouw op de trein.', cue: 'wachten', answer: 'wacht' },
      { nl: 'Thuis ___ ik graag.', cue: 'schrijven', en: 'At home I like to write.', answer: 'schrijf' },
    ],
    explanation: 'jij after the verb: ga, ben, kom, heb, kook — no -t. “Dan eet jij” looks unchanged because the stem already ends in -t.',
  },
  {
    type: 'drill', title: 'jij loses its -t — in statements too', grammar: ['v2-inversion', 'inversion', 'subject-pronouns', 'hebben', 'zijn'],
    task: 'Change hij to jij',
    instruction: 'Replace hij with jij. The verb stays second, so jij stands behind it — and the -t goes.',
    items: [
      { nl: 'Morgen gaat hij naar de winkel.', answer: 'Morgen ga jij naar de winkel.' },
      { nl: 'Morgen komt hij met de trein.', answer: 'Morgen kom jij met de trein.' },
      { nl: 'Vandaag werkt hij thuis.', answer: 'Vandaag werk jij thuis.' },
      { nl: 'Nu leest hij een boek.', answer: 'Nu lees jij een boek.' },
      { nl: 'Thuis heeft hij een kleine kat.', answer: 'Thuis heb jij een kleine kat.' },
      { nl: 'Vandaag is hij moe.', answer: 'Vandaag ben jij moe.' },
      { nl: 'Vandaag kookt hij thuis.', answer: 'Vandaag kook jij thuis.' },
      { nl: 'Nu zit hij op de bank.', answer: 'Nu zit jij op de bank.' },
      { nl: 'Nu wacht hij op de trein.', answer: 'Nu wacht jij op de trein.' },
    ],
    explanation: 'heeft → heb and is → ben: the irregulars change completely. zit and wacht stay as they are. Everything else simply drops the -t.',
  },
  {
    type: 'arrange', title: 'Tomorrow, you', grammar: ['v2-inversion', 'gaan', 'de-het'],
    instruction: 'Build: “Tomorrow you are going to the shop.” Careful with the verb form.',
    nl: 'Morgen ga jij naar de winkel.', en: 'Tomorrow you are going to the shop.', image: 'shop', distractors: ['gaat', 'het'],
  },

  // ——— Grammar: time before place ———
  {
    type: 'grammar', title: 'Time before place', grammar: ['time-place', 'v2-inversion', 'niet'],
    body: [
      'When a sentence has both a **time** (*nu, vandaag, morgen, dan*) and a **place** (*hier, thuis, in het park, naar de winkel*), the time comes first: *Ik ga **morgen** **naar de winkel**.* English usually does the reverse — “I am going to the shop tomorrow” — so this is exactly where English order will lead you astray.',
      'A short way to remember it: **when before where**.',
      'If the sentence also says **how** — *met de trein, met de fiets, met Max* — that part goes in between: **when, how, where**. *Ik ga **morgen** **met de trein** **naar Brussel**.* English has it back to front again: “I am going to Brussels by train tomorrow”.',
      '**niet** goes after the time, before the rest: *Ik ga vandaag **niet** naar het park. Bram werkt morgen **niet** in Brussel. Lotte komt morgen **niet** met de trein.*',
      'Combined with the verb-second rule, you now have two natural ways to say the same thing: *Ik ga morgen naar de winkel.* and *Morgen ga ik naar de winkel.* When the time moves to the front, how and where stay at the end, in the same order.',
    ],
    tables: [
      { caption: 'subject · verb · time · (niet) · how · place', rows: [
        { nl: 'Ik ga [morgen] naar de winkel.', en: 'I am going to the shop tomorrow.' },
        { nl: 'Bram werkt [vandaag] thuis.', en: 'Bram is working at home today.' },
        { nl: 'Lotte zit [nu] op de bank.', en: 'Lotte is sitting on the bench now.' },
        { nl: 'Wij gaan [vandaag] niet naar het park.', en: 'We are not going to the park today.' },
        { nl: 'Ik ga [morgen] met de trein naar Brussel.', en: 'I am going to Brussels by train tomorrow.' },
      ] },
      { caption: 'time first · verb · subject · (niet) · how · place', rows: [
        { nl: '[Morgen] ga ik naar de winkel.', en: 'Tomorrow I am going to the shop.' },
        { nl: '[Vandaag] werkt Bram thuis.', en: 'Today Bram is working at home.' },
        { nl: '[Nu] zit Lotte op de bank.', en: 'Now Lotte is sitting on the bench.' },
        { nl: '[Vandaag] gaan wij niet naar het park.', en: 'Today we are not going to the park.' },
        { nl: '[Morgen] ga ik met de trein naar Brussel.', en: 'Tomorrow I am going to Brussels by train.' },
      ] },
    ],
    examples: [
      { nl: 'Waar werk jij vandaag?', en: 'Where are you working today?' },
      { nl: 'Ik werk vandaag thuis.', en: 'I am working at home today.' },
      { nl: 'Wij gaan vandaag met Max naar het park.', en: 'We are going to the park with Max today.' },
      { nl: 'Wij gaan nu naar huis.', en: 'We are going home now.' },
      { nl: 'Dan gaan wij naar huis.', en: 'Then we are going home.' },
    ],
  },
  {
    type: 'arrange', title: 'When, how, where', grammar: ['time-place', 'gaan'],
    instruction: 'Build: “We are going to Ghent by train tomorrow.” When, how, where — two tiles are left over.',
    nl: 'Wij gaan morgen met de trein naar Gent.', en: 'We are going to Ghent by train tomorrow.', image: 'train', distractors: ['gaat', 'het'],
  },
  {
    type: 'drill', title: 'Add the time', grammar: ['time-place', 'niet', 'gaan'],
    instruction: 'Add the time word to the sentence, in the right place — the subject still starts the sentence.',
    items: [
      { nl: 'Ik ga naar de winkel.', task: 'Add “morgen”', answer: 'Ik ga morgen naar de winkel.' },
      { nl: 'Bram werkt thuis.', task: 'Add “vandaag”', answer: 'Bram werkt vandaag thuis.' },
      { nl: 'Lotte zit op de bank.', task: 'Add “nu”', answer: 'Lotte zit nu op de bank.' },
      { nl: 'Lotte komt met de fiets.', task: 'Add “morgen”', answer: 'Lotte komt morgen met de fiets.' },
      { nl: 'Wij gaan naar het park.', task: 'Add “vandaag”', answer: 'Wij gaan vandaag naar het park.' },
      { nl: 'Het kind gaat naar school.', task: 'Add “nu”', answer: 'Het kind gaat nu naar school.' },
      { nl: 'Wij gaan met de trein naar Brussel.', task: 'Add “vandaag”', answer: 'Wij gaan vandaag met de trein naar Brussel.' },
      { nl: 'Ik ga niet naar het park.', task: 'Add “vandaag”', answer: 'Ik ga vandaag niet naar het park.' },
      { nl: 'Bram werkt niet in Brussel.', task: 'Add “morgen”', answer: 'Bram werkt morgen niet in Brussel.' },
    ],
    explanation: 'Time straight after the verb, then niet, then how (met …), then the place.',
  },
  {
    type: 'drill', title: 'Now move the time to the front', grammar: ['time-place', 'v2-inversion', 'geen', 'niet'],
    task: 'Start with the time',
    instruction: 'Same sentences, other order: time first, verb second, subject third. How and where stay at the end.',
    items: [
      { nl: 'Ik ga morgen naar de winkel.', answer: 'Morgen ga ik naar de winkel.' },
      { nl: 'Jij gaat vandaag naar het park.', answer: 'Vandaag ga jij naar het park.' },
      { nl: 'Jij komt morgen met de trein.', answer: 'Morgen kom jij met de trein.' },
      { nl: 'Bram werkt vandaag niet in Brussel.', answer: 'Vandaag werkt Bram niet in Brussel.' },
      { nl: 'Lotte gaat vandaag met de fiets naar de stad.', answer: 'Vandaag gaat Lotte met de fiets naar de stad.' },
      { nl: 'De oude man zit vandaag op de bank.', answer: 'Vandaag zit de oude man op de bank.' },
      { nl: 'Jij drinkt nu geen koffie.', answer: 'Nu drink jij geen koffie.' },
      { nl: 'Wij gaan dan naar huis.', answer: 'Dan gaan wij naar huis.' },
    ],
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', title: 'From statement to question', grammar: ['yes-no-question', 'inversion', 'time-place', 'adverb-position'],
    task: 'Make it a question',
    instruction: 'Turn each statement into a yes/no question. The verb goes first; time, how and place keep their order.',
    items: [
      { nl: 'Jij gaat vandaag naar het park.', answer: 'Ga jij vandaag naar het park?' },
      { nl: 'Jij komt morgen met de trein.', answer: 'Kom jij morgen met de trein?' },
      { nl: 'Bram werkt morgen thuis.', answer: 'Werkt Bram morgen thuis?' },
      { nl: 'Lotte leest nu een boek.', answer: 'Leest Lotte nu een boek?' },
      { nl: 'Het kind gaat vandaag naar school.', answer: 'Gaat het kind vandaag naar school?' },
      { nl: 'Jullie gaan morgen naar Gent.', answer: 'Gaan jullie morgen naar Gent?' },
      { nl: 'Leuven is een mooie stad.', answer: 'Is Leuven een mooie stad?' },
      { nl: 'Jij hebt thuis een kat.', answer: 'Heb jij thuis een kat?' },
      { nl: 'Jij drinkt altijd koffie.', answer: 'Drink jij altijd koffie?' },
    ],
    explanation: 'A question is the same machine with an empty first slot: the verb moves up, jij loses its -t, the rest stays put.',
  },
  {
    type: 'drill', title: 'Ask with waar or wat', grammar: ['question-word', 'v2-inversion', 'time-place'],
    instruction: 'Ask for the part the sentence gives you. The question word takes the first slot, the verb the second.',
    items: [
      { nl: 'Bram werkt vandaag in Brussel.', task: 'Ask with “waar”', answer: 'Waar werkt Bram vandaag?' },
      { nl: 'Lotte leest nu een boek.', task: 'Ask with “wat”', answer: 'Wat leest Lotte nu?' },
      { nl: 'Jij woont in Leuven.', task: 'Ask with “waar”', answer: 'Waar woon jij?' },
      { nl: 'Lotte drinkt nu thee.', task: 'Ask with “wat”', answer: 'Wat drinkt Lotte nu?' },
      { nl: 'Het station is in de stad.', task: 'Ask with “waar”', answer: 'Waar is het station?' },
      { nl: 'De school is in mijn straat.', task: 'Ask with “waar”', answer: 'Waar is de school?' },
      { nl: 'Het kind eet een appel.', task: 'Ask with “wat”', answer: 'Wat eet het kind?' },
      { nl: 'Jij drinkt nu koffie.', task: 'Ask with “wat”', answer: 'Wat drink jij nu?' },
      { nl: 'Jij werkt morgen thuis.', task: 'Ask with “waar”', answer: 'Waar werk jij morgen?' },
    ],
    explanation: 'Question word · verb · subject · time. The part you ask about disappears from the sentence.',
  },
  {
    type: 'drill', title: 'Say no: niet or geen?', grammar: ['geen-niet', 'niet', 'geen', 'v2-inversion'],
    task: 'Make it negative',
    instruction: 'Make each sentence negative. “een” or no article before a noun → geen; everything else → niet, after the verb-and-subject pair. A place is never a geen-noun: “naar school” takes niet.',
    items: [
      { nl: 'Vandaag gaat Bram naar Brussel.', answer: 'Vandaag gaat Bram niet naar Brussel.' },
      { nl: 'Nu drinkt Bram koffie.', answer: 'Nu drinkt Bram geen koffie.' },
      { nl: 'Morgen ga ik naar de winkel.', answer: 'Morgen ga ik niet naar de winkel.' },
      { nl: 'Morgen komt Bram met de trein.', answer: 'Morgen komt Bram niet met de trein.' },
      { nl: 'Vandaag werk jij thuis.', answer: 'Vandaag werk jij niet thuis.' },
      { nl: 'Dit is een station.', answer: 'Dit is geen station.' },
      { nl: 'Nu drinkt Lotte thee.', answer: 'Nu drinkt Lotte geen thee.' },
      { nl: 'Vandaag gaat het kind naar school.', answer: 'Vandaag gaat het kind niet naar school.' },
      { nl: 'Nu eet Bram brood.', answer: 'Nu eet Bram geen brood.' },
      { nl: 'Thuis heeft Bram een fiets.', answer: 'Thuis heeft Bram geen fiets.' },
    ],
    explanation: 'koffie, thee and brood have no article, and station and fiets have een, so they take geen. naar Brussel, naar de winkel, met de trein and thuis are places or ways of going, so they take niet — and so does naar school, even without an article: it is a place, not a thing you have or drink.',
  },
  {
    type: 'drill', title: 'Pronouns, endings and adverbs', grammar: ['hij-het-things', 'adjective-e', 'adverb-position', 'de-het'],
    instruction: 'Type the missing word. Everything from lessons 1–5 is in here, now with the new words.',
    items: [
      { nl: 'Het park is groot. ___ is groot.', cue: 'hij / het', answer: 'Het' },
      { nl: 'De boom is groot. ___ is groot.', cue: 'hij / het', answer: 'Hij' },
      { nl: 'De trein is oud. ___ is oud.', cue: 'hij / het', answer: 'Hij' },
      { nl: 'De winkel is mooi. ___ is mooi.', cue: 'hij / het', answer: 'Hij' },
      { nl: 'Dit is het ___ park.', cue: 'groot', answer: 'grote' },
      { nl: 'Leuven is een ___ stad.', cue: 'mooi', answer: 'mooie' },
      { nl: 'Het huis heeft een ___ raam.', cue: 'groot', answer: 'groot' },
      { nl: 'Lotte is een ___ vrouw.', cue: 'jong', answer: 'jonge' },
      { nl: 'Max is een ___ hond.', cue: 'lief', answer: 'lieve' },
      { nl: 'Thuis drinkt Bram ___ koffie.', en: 'At home Bram always drinks coffee.', answer: 'altijd' },
      { nl: 'Lotte drinkt ___ koffie.', en: 'Lotte never drinks coffee.', answer: 'nooit' },
      { nl: 'Lotte leest ___ in het park.', en: 'Lotte likes reading in the park.', answer: 'graag' },
      { nl: 'Bram en Lotte zijn ___.', cue: 'jong', en: 'Bram and Lotte are young.', answer: 'jong' },
    ],
    explanation: 'de-word → hij, het-word → het. een + het-word: no -e (een groot park, een groot raam). het/de + adjective, or een + de-word: -e (het grote park, een mooie stad, een lieve hond). altijd, nooit, graag come straight after the verb — and after the subject when it has moved behind the verb.',
  },
  {
    type: 'arrange', title: 'Always, at home', grammar: ['adverb-position', 'v2-inversion'],
    instruction: 'Build: “At home Bram always drinks coffee.” Watch the verb form and the adverb.',
    nl: 'Thuis drinkt Bram altijd koffie.', en: 'At home Bram always drinks coffee.', image: 'coffee', distractors: ['drink', 'nooit'],
  },
  {
    type: 'arrange', title: 'Not to Brussels today', grammar: ['niet', 'geen-niet', 'v2-inversion'],
    instruction: 'Build: “Today Bram is not going to Brussels.” Two tiles are traps.',
    nl: 'Vandaag gaat Bram niet naar Brussel.', en: 'Today Bram is not going to Brussels.', image: 'man-dog', distractors: ['geen', 'ga'],
  },
  {
    type: 'drill', title: 'Look and answer in full', grammar: ['dit-is', 'yes-no-question', 'geen', 'adjective-e', 'hebben'],
    task: 'Answer in full',
    instruction: 'Look at the picture and answer with a complete sentence. Keep the time word if the question has one.',
    items: [
      { image: 'school', nl: 'Is dit een winkel?', answer: 'Nee, dit is een school.', accept: ['Nee, dit is geen winkel.', 'Nee, dit is geen winkel. Dit is een school.', 'Nee, dit is geen winkel, maar een school.'] },
      { image: 'train', nl: 'Wat is dit?', answer: 'Dit is een trein.', accept: ['Dit is de trein.'] },
      { image: 'station', nl: 'Is dit een station?', answer: 'Ja, dit is een station.', accept: ['Ja, dit is het station.'] },
      { image: 'door', nl: 'Wat is dit?', answer: 'Dit is een deur.', accept: ['Dit is de deur.'] },
      { image: 'tree', nl: 'Is dit een kleine boom?', answer: 'Nee, dit is een grote boom.', accept: ['Nee, dit is geen kleine boom.', 'Nee, dit is geen kleine boom. Dit is een grote boom.'] },
      { image: 'coat', nl: 'Is dit een tas?', answer: 'Nee, dit is een jas.', accept: ['Nee, dit is geen tas.', 'Nee, dit is geen tas. Dit is een jas.'] },
      { image: 'tea', nl: 'Is dit koffie?', answer: 'Nee, dit is thee.', accept: ['Nee, dit is geen koffie.', 'Nee, dit is geen koffie. Dit is thee.'] },
      { image: 'water', nl: 'Is dit water?', answer: 'Ja, dit is water.' },
      { image: 'woman-sick', nl: 'Is Lotte vandaag ziek?', answer: 'Ja, zij is vandaag ziek.', accept: ['Ja, Lotte is vandaag ziek.', 'Ja, vandaag is zij ziek.', 'Ja, vandaag is Lotte ziek.'] },
      { image: 'man-happy', nl: 'Is Bram nu blij?', answer: 'Ja, hij is nu blij.', accept: ['Ja, Bram is nu blij.', 'Ja, nu is hij blij.', 'Ja, nu is Bram blij.'] },
      { image: 'woman-working', nl: 'Werkt Lotte nu thuis?', answer: 'Ja, zij werkt nu thuis.', accept: ['Ja, Lotte werkt nu thuis.', 'Ja, nu werkt zij thuis.', 'Ja, nu werkt Lotte thuis.'] },
    ],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Een dag in Leuven', image: 'park', grammar: ['v2-inversion', 'time-place', 'gaan', 'adjective-e', 'geen-niet', 'hij-het-things', 'adverb-position'],
    instruction: 'A day with Bram and Lotte — everything from the whole book is in it. Read and listen to every line, then read it again without the English. Count how often the verb stands second behind a time or place.',
    lines: [
      { nl: 'Bram en Lotte wonen in Leuven, in een groot huis in een mooie straat.', en: 'Bram and Lotte live in Leuven, in a big house on a beautiful street.', image: 'people-home' },
      { nl: 'Leuven is een mooie, oude stad. Bram werkt in Brussel; hij gaat altijd met de trein.', en: 'Leuven is a beautiful old city. Bram works in Brussels; he always goes by train.', image: 'train' },
      { nl: 'Lotte werkt altijd thuis. Vandaag werkt Bram niet; hij is moe.', en: 'Lotte always works at home. Today Bram is not working; he is tired.', image: 'man-tired' },
      { nl: 'Thuis drinkt hij altijd koffie. Lotte drinkt nooit koffie; zij drinkt thee.', en: 'At home he always drinks coffee. Lotte never drinks coffee; she drinks tea.', image: 'tea' },
      { nl: 'Dan eet Bram brood met kaas, en Lotte eet een appel. De kleine kat slaapt op het bed.', en: 'Then Bram eats bread with cheese, and Lotte eats an apple. The little cat is asleep on the bed.', image: 'cat-sleeping' },
      { speaker: 'Bram', nl: 'Lotte, vandaag ga ik met Max naar het park. Kom jij ook?', en: 'Lotte, today I am going to the park with Max. Are you coming too?', image: 'man-dog' },
      { speaker: 'Lotte', nl: 'Ja, ik kom! In het park lees ik mijn boek. Maar waar is mijn sleutel?', en: 'Yes, I’m coming! In the park I will read my book. But where is my key?', image: 'book' },
      { speaker: 'Bram', nl: 'Hij zit in de deur.', en: 'It’s in the door.', image: 'key' },
      { nl: 'Lotte heeft een fiets, maar Bram heeft geen fiets en geen auto. Vandaag lopen ze.', en: 'Lotte has a bike, but Bram has no bike and no car. Today they walk.', image: 'woman-bike' },
      { nl: 'Het park is groot en mooi. Een kind speelt, en op een bank zit de oude man.', en: 'The park is big and beautiful. A child is playing, and on a bench sits the old man.', image: 'child-playing' },
      { speaker: 'De oude man', nl: 'Max! Hij is groot, maar hij is altijd lief.', en: 'Max! He is big, but he is always sweet.', image: 'dog-big' },
      { speaker: 'Bram', nl: 'Ja, Max is lief, en hij loopt graag in het park.', en: 'Yes, Max is sweet, and he likes walking in the park.', image: 'man-dog' },
      { nl: 'Nu zit Lotte op een bank. Zij leest, en Bram praat met de oude man.', en: 'Now Lotte is sitting on a bench. She reads, and Bram talks with the old man.', image: 'woman-reading' },
      { speaker: 'De oude man', nl: 'Komen jullie morgen ook naar het park?', en: 'Are you coming to the park tomorrow too?', image: 'old-man' },
      { speaker: 'Bram', nl: 'Nee, morgen werk ik thuis, en dan ga ik naar de winkel. Thuis hebben wij geen brood.', en: 'No, tomorrow I am working at home, and then I am going to the shop. We have no bread at home.', image: 'shop' },
      { speaker: 'Lotte', nl: 'Maar ik kom morgen met de fiets!', en: 'But I’ll come tomorrow by bike!', image: 'woman-bike' },
      { nl: 'Dan gaan ze naar huis. Thuis kookt Bram, en Lotte schrijft.', en: 'Then they go home. At home Bram cooks, and Lotte writes.', image: 'man-cooking' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'inversion', 'time-place'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the story. Answer without looking back.',
    items: [
      { nl: 'Gaat Bram altijd met de trein naar Brussel?', answer: 'Ja' },
      { nl: 'Werkt Bram vandaag in Brussel?', answer: 'Nee' },
      { nl: 'Drinkt Lotte thee?', answer: 'Ja' },
      { nl: 'Eet Lotte brood met kaas?', answer: 'Nee' },
      { nl: 'Heeft Bram een auto?', answer: 'Nee' },
      { nl: 'Zit de sleutel in de deur?', answer: 'Ja' },
      { nl: 'Gaat Bram morgen naar de winkel?', answer: 'Ja' },
      { nl: 'Komt Lotte morgen met de trein?', answer: 'Nee' },
    ],
  },
  {
    type: 'drill', title: 'Answer in a full sentence', grammar: ['question-word', 'v2-inversion', 'time-place', 'geen-niet', 'adjective-e'],
    task: 'Answer in full',
    instruction: 'Answer each question about the story with a complete sentence. Use the subject or its pronoun — both are accepted.',
    items: [
      { nl: 'Waar wonen Bram en Lotte?', answer: 'Bram en Lotte wonen in Leuven.', accept: ['Zij wonen in Leuven.', 'Zij wonen in Leuven, in een groot huis.', 'Bram en Lotte wonen in Leuven, in een groot huis.'] },
      { nl: 'Gaat Bram met de trein of met de auto naar Brussel?', answer: 'Bram gaat met de trein naar Brussel.', accept: ['Hij gaat met de trein naar Brussel.', 'Bram gaat altijd met de trein naar Brussel.', 'Hij gaat altijd met de trein naar Brussel.', 'Bram gaat met de trein.', 'Hij gaat met de trein.', 'Bram gaat altijd met de trein.', 'Hij gaat altijd met de trein.'] },
      { nl: 'Wat drinkt Lotte?', answer: 'Lotte drinkt thee.', accept: ['Zij drinkt thee.'] },
      { nl: 'Wat eet Bram?', answer: 'Bram eet brood met kaas.', accept: ['Hij eet brood met kaas.', 'Dan eet Bram brood met kaas.', 'Dan eet hij brood met kaas.'] },
      { nl: 'Gaan ze vandaag naar het park of naar de winkel?', answer: 'Vandaag gaan ze naar het park.', accept: ['Ze gaan vandaag naar het park.', 'Bram en Lotte gaan vandaag naar het park.', 'Vandaag gaan Bram en Lotte naar het park.'] },
      { nl: 'Waar is de sleutel?', answer: 'De sleutel zit in de deur.', accept: ['Hij zit in de deur.', 'De sleutel is in de deur.', 'Hij is in de deur.'] },
      { nl: 'Is Max een kleine hond?', answer: 'Nee, Max is een grote hond.', accept: ['Nee, hij is een grote hond.', 'Nee, Max is geen kleine hond.', 'Nee, hij is geen kleine hond.', 'Nee, Max is groot.', 'Nee, hij is groot.'] },
      { nl: 'Gaat Bram morgen naar de winkel of naar het park?', answer: 'Morgen gaat Bram naar de winkel.', accept: ['Morgen gaat hij naar de winkel.', 'Bram gaat morgen naar de winkel.', 'Hij gaat morgen naar de winkel.'] },
      { nl: 'Komt Lotte morgen met de trein of met de fiets?', answer: 'Lotte komt morgen met de fiets.', accept: ['Zij komt morgen met de fiets.', 'Morgen komt Lotte met de fiets.', 'Morgen komt zij met de fiets.', 'Lotte komt met de fiets.', 'Zij komt met de fiets.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['v2-inversion', 'time-place', 'gaan', 'adverb-position'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'Vandaag ga ik naar het park.' },
      { listen: 'Morgen gaat Bram naar de winkel.' },
      { listen: 'Kom jij morgen met de trein?' },
      { listen: 'Nu leest Lotte een boek in het park.' },
      { listen: 'Thuis drinkt Bram altijd koffie.' },
      { listen: 'Het kind is ziek en gaat vandaag niet naar school.' },
      { listen: 'Leuven is een mooie stad.' },
      { listen: 'Dan gaan wij naar huis.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['v2-inversion', 'time-place', 'gaan', 'question-word', 'hebben', 'zijn', 'adjective-e'],
    instruction: 'Translate. When the English starts with the time, so does your Dutch — and then the verb comes next.',
    items: [
      { en: 'Today I am going to the park.', answer: 'Vandaag ga ik naar het park.' },
      { en: 'Tomorrow you are going to the shop. (one person)', answer: 'Morgen ga jij naar de winkel.' },
      { en: 'Tomorrow I am coming by train.', answer: 'Morgen kom ik met de trein.' },
      { en: 'Bram is working at home today.', answer: 'Bram werkt vandaag thuis.', accept: ['Vandaag werkt Bram thuis.'] },
      { en: 'Are you going to Brussels tomorrow? (one person)', answer: 'Ga jij morgen naar Brussel?' },
      { en: 'Where is the station?', answer: 'Waar is het station?' },
      { en: 'Leuven is a beautiful city.', answer: 'Leuven is een mooie stad.' },
      { en: 'Bram is waiting for the train.', answer: 'Bram wacht op de trein.' },
      { en: 'We are eating bread with cheese.', answer: 'Wij eten brood met kaas.' },
      { en: 'We are not going to the park today.', answer: 'Wij gaan vandaag niet naar het park.', accept: ['Vandaag gaan wij niet naar het park.'] },
      { en: 'The child is going to school with a new bag.', answer: 'Het kind gaat met een nieuwe tas naar school.', accept: ['Het kind gaat naar school met een nieuwe tas.'] },
      { en: 'At home Lotte has a small cat.', answer: 'Thuis heeft Lotte een kleine kat.', accept: ['Lotte heeft thuis een kleine kat.'] },
      { en: 'Lotte has a new coat.', answer: 'Lotte heeft een nieuwe jas.' },
      { en: 'Where are you working today? (one person)', answer: 'Waar werk jij vandaag?' },
      { en: 'Today you are not tired. (one person, start with “today”)', answer: 'Vandaag ben jij niet moe.' },
    ],
  },
  {
    type: 'arrange', title: 'Not Brussels, but the shop', grammar: ['v2-inversion', 'niet', 'time-place'],
    instruction: 'Build: “Tomorrow Bram is going not to Brussels but to the shop.”',
    nl: 'Morgen gaat Bram niet naar Brussel, maar naar de winkel.', en: 'Tomorrow Bram is going not to Brussels, but to the shop.', image: 'shop', distractors: ['geen', 'ga'],
  },
  {
    type: 'drill', title: 'The whole book in one round', grammar: ['dit-is', 'de-het', 'geen', 'yes-no-question', 'subject-pronouns', 'zijn', 'inversion', 'niet', 'hij-het-things', 'present-regular', 'spelling-stem', 'question-word', 'hebben', 'geen-niet', 'adjective-e', 'spelling-z-s', 'adverb-position', 'gaan', 'v2-inversion', 'time-place'],
    instruction: 'A final, demanding round: every grammar point of this volume, mixed. Type every answer. No hints beyond the task.',
    items: [
      { nl: '___ station', cue: 'de / het', answer: 'het' },
      { nl: '___ stad', cue: 'de / het', answer: 'de' },
      { image: 'window', nl: 'Wat is dit?', answer: 'Dit is een raam.', accept: ['Dit is het raam.'] },
      { nl: 'De sleutel is in de tas.', task: 'Replace “de sleutel” with a pronoun', answer: 'Hij is in de tas.' },
      { nl: 'Het kind is ziek.', task: 'Replace “het kind” with a pronoun', answer: 'Het is ziek.' },
      { nl: 'Morgen ___ jij met de trein.', cue: 'komen', answer: 'kom' },
      { nl: 'Nu ___ Lotte een appel.', cue: 'eten', answer: 'eet' },
      { nl: 'Dan ___ Bram in het park.', cue: 'wachten', answer: 'wacht' },
      { nl: 'Dit is een ___ auto.', cue: 'nieuw', answer: 'nieuwe' },
      { nl: 'Bram drinkt thee.', task: 'Add “nooit”', answer: 'Bram drinkt nooit thee.' },
      { nl: 'Ik ga naar de winkel.', task: 'Add “morgen” and start with it', answer: 'Morgen ga ik naar de winkel.' },
      { nl: 'Jij woont in Leuven.', task: 'Ask with “waar”', answer: 'Waar woon jij?' },
      { nl: 'Het kind heeft een telefoon.', task: 'Make it negative', answer: 'Het kind heeft geen telefoon.' },
      { en: 'Then we eat bread.', answer: 'Dan eten wij brood.' },
      { en: 'Lotte is talking with an old woman.', answer: 'Lotte praat met een oude vrouw.' },
      { en: 'Today the old man is walking in the park.', answer: 'Vandaag loopt de oude man in het park.', accept: ['De oude man loopt vandaag in het park.'] },
      { en: 'Tomorrow you are working at home. (one person, start with “tomorrow”)', answer: 'Morgen werk jij thuis.' },
      { en: 'Lotte never writes on the train.', answer: 'Lotte schrijft nooit in de trein.', accept: ['Lotte schrijft nooit op de trein.'] },
      { listen: 'Morgen werkt Bram thuis, en dan gaat hij naar de winkel.' },
    ],
  },
  {
    type: 'complete', title: 'Volume zero, part one: done',
    instruction: 'Eighteen verbs in every person, two articles, geen and niet, adjective endings, adverbs — and now the rule that holds Dutch sentences together: the verb stays second. Vandaag lees je Nederlands; morgen spreek je het.',
  },
];
