/**
 * Lesson 9 — Ik kan een beetje Nederlands.
 * Targets: kunnen, willen, moeten, mogen, zwemmen, spreken, rijden, helpen, Nederlands, goed.
 * Structure: Engels, beetje, heel.
 * Grammar: the four modal verbs · the infinitive at the end of the sentence · d + t (rijden).
 * Every verb of the book returns, now framed by a modal; every earlier word-order rule
 * (verb second, time before place, niet/geen) is combined with the new frame. See docs/CURRICULUM.md.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'What people can do', grammar: ['present-regular', 'adverb-position', 'hebben'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice. Watch the small verbs kan, wil, moet and mag, and where the second verb goes.',
    cards: [
      { nl: 'Bram zwemt graag. Hij zwemt heel goed.', en: 'Bram likes swimming. He swims very well.', image: 'man-swimming' },
      { nl: 'Bram kan goed rijden. In Gent rijdt hij met de auto.', en: 'Bram can drive well. In Ghent he drives the car.', image: 'man-driving' },
      { nl: 'Lotte kan niet rijden. Zij gaat altijd met de fiets.', en: 'Lotte can’t drive. She always goes by bike.', image: 'woman-bike' },
      { nl: 'Bram helpt de oude man.', en: 'Bram is helping the old man.', image: 'man-helping' },
      { nl: 'Lotte spreekt heel goed Engels.', en: 'Lotte speaks English very well.', image: 'couple-talking' },
      { nl: 'Zij spreekt ook heel goed Nederlands.', en: 'She also speaks Dutch very well.', image: 'woman' },
      { nl: 'Ik spreek een beetje Nederlands.', en: 'I speak a bit of Dutch.' },
      { nl: 'Bram wil koffie drinken.', en: 'Bram wants to drink coffee.', image: 'coffee' },
      { nl: 'Vandaag moet Lotte thuis werken.', en: 'Today Lotte has to work at home.', image: 'woman-working' },
      { nl: 'Max mag niet op het bed slapen.', en: 'Max is not allowed to sleep on the bed.', image: 'dog-big' },
      { nl: 'Mag ik hier zitten?', en: 'May I sit here?', image: 'bench' },
    ],
    note: 'zwemmen = to swim, spreken = to speak, rijden = to drive / to ride, helpen = to help. Four small verbs change a sentence: kunnen (can), willen (want), moeten (must, have to), mogen (may, be allowed to). Nederlands = Dutch, Engels = English — languages have a capital letter and no article. een beetje = a bit, heel = very, goed = good / well. Bram has no car of his own; in Gent he drives his father’s. Look at “Bram wil koffie drinken”: the second verb waits at the very end. That is the grammar of this lesson.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['present-regular'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Bram zwemt.', en: 'Bram is swimming.', answer: 'man-swimming',
    choices: [{ image: 'man-driving', nl: 'Bram rijdt.' }, { image: 'man-swimming', nl: 'Bram zwemt.' }, { image: 'man-helping', nl: 'Bram helpt.' }, { image: 'man-walking', nl: 'Bram loopt.' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['present-regular'],
    instruction: 'Listen without reading. What is Bram doing?',
    nl: 'Bram helpt de oude man.', en: 'Bram is helping the old man.', answer: 'man-helping',
    choices: [{ image: 'couple-talking', nl: 'Bram en Lotte praten.' }, { image: 'man-helping', nl: 'Bram helpt de oude man.' }, { image: 'man-sitting', nl: 'Bram zit op de bank.' }],
  },
  {
    type: 'picture', listen: true, title: 'Who cannot drive?', grammar: ['modals'],
    instruction: 'Listen. Choose the picture that goes with the sentence.',
    nl: 'Lotte kan niet rijden. Zij gaat met de fiets.', en: 'Lotte can’t drive. She goes by bike.', answer: 'woman-bike',
    choices: [{ image: 'man-driving', nl: 'Bram rijdt.' }, { image: 'woman-bike', nl: 'Lotte en haar fiets' }, { image: 'woman-walking', nl: 'Lotte loopt.' }],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['dt-rule', 'v2-inversion'],
    instruction: 'Listen and choose the picture that matches.',
    nl: 'In Gent rijdt Bram met de auto.', en: 'In Ghent Bram drives the car.', answer: 'man-driving',
    choices: [{ image: 'man-swimming', nl: 'Bram zwemt.' }, { image: 'train', nl: 'de trein' }, { image: 'man-driving', nl: 'Bram rijdt.' }, { image: 'man-walking', nl: 'Bram loopt.' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['adjective-e', 'possessives'],
    instruction: 'For a picture, type the verb (the infinitive). For English, type the Dutch.',
    items: [
      { image: 'man-swimming', answer: 'zwemmen' },
      { image: 'man-driving', answer: 'rijden' },
      { image: 'man-helping', answer: 'helpen' },
      { en: 'to speak', answer: 'spreken' },
      { en: 'can / to be able to', answer: 'kunnen' },
      { en: 'to want', answer: 'willen' },
      { en: 'must / to have to', answer: 'moeten' },
      { en: 'may / to be allowed to', answer: 'mogen' },
      { en: 'Dutch (the language)', answer: 'Nederlands' },
      { en: 'English (the language)', answer: 'Engels' },
      { en: 'very good', answer: 'heel goed' },
      { en: 'a bit of Dutch', answer: 'een beetje Nederlands' },
      { en: 'my good friend (male)', answer: 'mijn goede vriend' },
    ],
    explanation: 'zwemmen has a double m, like zitten has a double t. Nederlands and Engels are written with a capital letter. goed takes the -e before a noun, like every adjective: een goede vriend, mijn goede vriend.',
  },
  {
    type: 'drill', title: 'Hear and spell',
    instruction: 'Play each one and type it. Listen for the long “ee” in spreken, the “ij” in rijden, and the short “u” sound in kunnen.',
    items: [
      { listen: 'zwemmen' },
      { listen: 'spreken' },
      { listen: 'rijden' },
      { listen: 'kunnen' },
      { listen: 'Nederlands' },
      { listen: 'Ik spreek een beetje Nederlands.' },
      { listen: 'Bram kan heel goed zwemmen.' },
      { listen: 'Lotte spreekt goed Engels.' },
    ],
    explanation: 'Ne-der-lands: stress on the first syllable. rijden has the “ij” of wij and blij; in fast speech, especially in Flanders, the d almost disappears (rij-en), but it is always written. kunnen has a short u, like the vowel of English “put” said with rounded lips.',
  },

  // ——— Grammar: three regular verbs ———
  {
    part: 'Grammar', type: 'grammar', title: 'zwemmen, spreken, helpen', grammar: ['present-regular', 'spelling-stem', 'inversion'],
    body: [
      'Three of the new verbs are completely regular. Everything from lesson 3 applies: **ik** + stem, **jij / hij / zij** + stem + **t**, **wij / jullie / zij** (they) = the infinitive. In a question, and whenever jij stands behind the verb, jij takes the bare stem.',
      '**zwemmen** → stem **zwem**. A Dutch word never ends in a double consonant, so one m goes — exactly as *zitten* gives *ik zit*. Before the -t it stays single: *hij **zwemt***. The infinitive and plural keep both m’s (*wij zwemmen*), because there the double letter keeps the e short.',
      '**spreken** → stem **spreek**. In *spre-ken* the e ends an open syllable, so it is long. Cut off -en and the syllable closes; the vowel is doubled to stay long — the rule of *slapen → slaap* and *lezen → lees*. So: *ik **spreek**, hij **spreekt**, wij **spreken***.',
      '**helpen** → stem **help**. Nothing to change: *ik help, hij helpt, help jij?* helpen takes its object directly, with no preposition: *Bram helpt **de oude man***. What you help with follows **met**: *Bram helpt de oude man **met** zijn tas.*',
      '**Languages.** In Dutch a language is a name: capital letter, no article. *Ik spreek Nederlands. Lotte spreekt Engels.* “A bit” is **een beetje**, “very” is **heel**, and “well” is **goed**. The usual order is verb · how well · language: *Ik spreek **een beetje** Nederlands. Lotte spreekt **heel goed** Engels.* (*Lotte spreekt Engels heel goed* is also correct; it stresses *how* well.) Because a language has no article, the negative is **geen**, like *geen koffie*: *De oude man spreekt **geen** Engels.*',
      '**goed** is one word for two English ones. Before a noun it is the adjective *good* and follows the -e rule of lesson 4: *een **goede** vriend, de **goede** koffie*, but *een **goed** boek* (een + het-word). After a verb it means *well* and never changes: *Bram zwemt **goed**.* **heel** (very) stands in front of it: *heel goed, heel mooi, heel oud*.',
    ],
    tables: [
      { caption: 'zwemmen', rows: [
        { nl: 'ik zwem', en: 'I swim' },
        { nl: 'jij zwem[t]', en: 'you swim' },
        { nl: 'hij zwem[t]', en: 'he swims' },
        { nl: 'wij zwem[men]', en: 'we swim' },
        { nl: 'zwem jij?', en: 'do you swim? — no -t' },
      ] },
      { caption: 'spreken', rows: [
        { nl: 'ik spreek', en: 'I speak' },
        { nl: 'jij spreek[t]', en: 'you speak' },
        { nl: 'zij spreek[t]', en: 'she speaks' },
        { nl: 'jullie spre[ken]', en: 'you (plural) speak' },
        { nl: 'spreek jij?', en: 'do you speak? — no -t' },
      ] },
      { caption: 'helpen', rows: [
        { nl: 'ik help', en: 'I help' },
        { nl: 'jij help[t]', en: 'you help' },
        { nl: 'hij help[t]', en: 'he helps' },
        { nl: 'zij help[en]', en: 'they help' },
        { nl: 'help jij?', en: 'are you helping? — no -t' },
      ] },
    ],
    examples: [
      { nl: 'Ik zwem graag.', en: 'I like swimming.' },
      { nl: 'Zwem jij ook?', en: 'Are you swimming too?' },
      { nl: 'Lotte spreekt heel goed Engels.', en: 'Lotte speaks English very well.' },
      { nl: 'Spreek jij Nederlands? — Ja, een beetje.', en: 'Do you speak Dutch? — Yes, a bit.' },
      { nl: 'De oude man spreekt geen Engels.', en: 'The old man doesn’t speak English.' },
      { nl: 'Bram helpt de oude man met zijn tas.', en: 'Bram helps the old man with his bag.' },
      { nl: 'Jonas is een goede vriend.', en: 'Jonas is a good friend.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate zwemmen', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'Type the form of zwemmen for every person. Say “ik zwem, jij zwemt …” out loud as you go.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'zwem' },
      { label: 'jij', gloss: 'you', answer: 'zwemt' },
      { label: 'hij', gloss: 'he', answer: 'zwemt' },
      { label: 'zij', gloss: 'she', answer: 'zwemt' },
      { label: 'wij', gloss: 'we', answer: 'zwemmen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'zwemmen' },
      { label: 'zij', gloss: 'they', answer: 'zwemmen' },
      { label: 'Max', gloss: 'he', answer: 'zwemt' },
    ],
    explanation: 'One m in zwem and zwemt, two in zwemmen — the same pattern as zit, zit, zitten.',
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate spreken and helpen', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'The small word under each person tells you the verb. Type the form.',
    items: [
      { label: 'ik', gloss: 'spreken', answer: 'spreek' },
      { label: 'jij', gloss: 'spreken', answer: 'spreekt' },
      { label: 'zij', gloss: 'she · spreken', answer: 'spreekt' },
      { label: 'wij', gloss: 'spreken', answer: 'spreken' },
      { label: 'jullie', gloss: 'spreken', answer: 'spreken' },
      { label: 'ik', gloss: 'helpen', answer: 'help' },
      { label: 'hij', gloss: 'helpen', answer: 'helpt' },
      { label: 'jij', gloss: 'helpen', answer: 'helpt' },
      { label: 'zij', gloss: 'they · helpen', answer: 'helpen' },
      { label: 'Bram en Lotte', gloss: 'helpen', answer: 'helpen' },
    ],
    explanation: 'spreek, spreekt with a double e; spreken with one — the open syllable keeps it long. helpen changes nothing.',
  },
  {
    type: 'drill', title: 'Type the form: zwemmen, spreken, helpen', grammar: ['present-regular', 'inversion', 'v2-inversion', 'geen-niet'],
    instruction: 'Type the missing form. The infinitive in brackets is the verb you need. Watch jij before and after the verb.',
    items: [
      { nl: 'Ik ___ graag.', cue: 'zwemmen', en: 'I like swimming.', answer: 'zwem' },
      { nl: 'Bram ___ heel goed.', cue: 'zwemmen', answer: 'zwemt' },
      { nl: '___ jij ook?', cue: 'zwemmen', en: 'Are you swimming too?', answer: 'Zwem' },
      { nl: 'Max ___ ook graag.', cue: 'zwemmen', answer: 'zwemt' },
      { nl: 'Lotte ___ heel goed Engels.', cue: 'spreken', answer: 'spreekt' },
      { nl: 'Ik ___ een beetje Nederlands.', cue: 'spreken', answer: 'spreek' },
      { nl: '___ jij Engels?', cue: 'spreken', answer: 'Spreek' },
      { nl: '___ jullie Nederlands?', cue: 'spreken', answer: 'Spreken' },
      { nl: 'De oude man ___ geen Engels.', cue: 'spreken', answer: 'spreekt' },
      { nl: 'Bram ___ de oude man.', cue: 'helpen', answer: 'helpt' },
      { nl: '___ jij Lotte?', cue: 'helpen', en: 'Are you helping Lotte?', answer: 'Help' },
      { nl: 'Nu ___ jij de oude man.', cue: 'helpen', en: 'Now you are helping the old man.', answer: 'help' },
    ],
    explanation: 'Zwem jij? Spreek jij? Help jij? — and Nu help jij: jij behind the verb takes the bare stem, in questions and statements alike. “Geen Engels”: a language has no article, so it is negated with geen.',
  },

  // ——— Grammar: d + t ———
  {
    type: 'grammar', title: 'rijden: d + t', grammar: ['dt-rule', 'present-regular', 'spelling-stem', 'inversion', 'v2-inversion'],
    body: [
      '**rijden** means to drive (a car) and to ride (a bike); it is also what a train or a car does: *De trein rijdt naar Brussel.* On its own, *Bram kan rijden* means he can drive a car. Its forms follow the ordinary rules exactly. The difficulty is purely one of spelling — and it is the most famous spelling rule of the Dutch language.',
      'Take the stem as always: *rijden* minus *-en* = **rijd**. Add the endings as always. **ik rijd** — the bare stem. **jij rijdt, hij rijdt, zij rijdt** — stem + t, so *d + t*. **wij / jullie / zij rijden**. In a question, and whenever jij stands behind the verb, the t goes: ***Rijd** jij?* — *Morgen **rijd** jij.*',
      'Why is this hard? At the end of a word Dutch pronounces **d** as **t**. *rijd*, *rijdt* — and a misspelled *rijt* — sound exactly the same. You cannot spell this verb by ear. Dutch-speaking children learn it at school as the *d/t-regel*, and a “dt-fout” is the spelling mistake readers notice first, in an email, a letter or an exam. Get it right from day one.',
      '**The test:** replace the verb with **lopen**, whose ending you can hear. Where lopen has no t, rijden has none: *ik loop → ik **rijd***; *loop jij? → **rijd** jij?* Where lopen has a t, rijden adds one after the d: *jij loopt → jij **rijdt***; *hij loopt → hij **rijdt***; *loopt Lotte? → **rijdt** Lotte?*',
      '**Compare stems that end in t:** *zitten → hij zit*, *praten → hij praat*, *wachten → hij wacht*, *heten → hij heet*, *eten → hij eet*. There the stem already ends in t, and Dutch never writes a double t at the end of a word, so nothing is added. A stem in **d** is different: d is not t, so the ending t is added and you write **dt**. (More d-verbs come later; *vinden → hij vindt* works the same.)',
      '**Three wrong forms to avoid:** *ik rijdt* (ik never takes a t), *rijdt jij?* (jij behind the verb never takes a t), and *hij rijd* (hij always takes one).',
    ],
    tables: [
      { caption: 'rijden', rows: [
        { nl: 'ik rijd', en: 'I drive — stem only (like ik loop)' },
        { nl: 'jij rijd[t]', en: 'you drive — d + t (like jij loopt)' },
        { nl: 'hij rijd[t]', en: 'he drives — d + t' },
        { nl: 'zij rijd[t]', en: 'she drives — d + t' },
        { nl: 'wij rijd[en]', en: 'we drive' },
        { nl: 'jullie rijd[en]', en: 'you (plural) drive' },
        { nl: 'zij rijd[en]', en: 'they drive' },
        { nl: 'rijd jij?', en: 'are you driving? — no t (like loop jij?)' },
        { nl: 'rijd[t] hij?', en: 'is he driving? — hij keeps the t' },
      ] },
      { caption: 'stem in t, stem in d', rows: [
        { nl: 'hij zi[t]', en: 'zitten: stem zit, nothing added' },
        { nl: 'hij wach[t]', en: 'wachten: stem wacht, nothing added' },
        { nl: 'hij hee[t]', en: 'heten: stem heet, nothing added' },
        { nl: 'hij rij[dt]', en: 'rijden: stem rijd, + t = dt' },
      ] },
    ],
    examples: [
      { nl: 'Ik rijd naar Gent.', en: 'I am driving to Ghent.' },
      { nl: 'Bram rijdt heel goed.', en: 'Bram drives very well.' },
      { nl: 'Rijd jij met de auto?', en: 'Are you going by car?' },
      { nl: 'Rijdt Lotte met de fiets naar de stad?', en: 'Is Lotte riding her bike into town?' },
      { nl: 'Morgen rijd jij.', en: 'Tomorrow you drive.' },
      { nl: 'De trein rijdt naar Brussel.', en: 'The train goes to Brussels.' },
      { nl: 'Wij rijden met de auto naar Antwerpen.', en: 'We are driving to Antwerp.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate rijden', grammar: ['dt-rule', 'subject-pronouns'],
    instruction: 'Type the form of rijden for every person. Think of lopen: no t where lopen has none, dt where lopen has a t.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'rijd' },
      { label: 'jij', gloss: 'you', answer: 'rijdt' },
      { label: 'hij', gloss: 'he', answer: 'rijdt' },
      { label: 'zij', gloss: 'she', answer: 'rijdt' },
      { label: 'wij', gloss: 'we', answer: 'rijden' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'rijden' },
      { label: 'zij', gloss: 'they', answer: 'rijden' },
      { label: 'de trein', gloss: 'it', answer: 'rijdt' },
    ],
    explanation: 'rijd — rijdt — rijdt — rijden. The d is always there; the t comes exactly where lopen has one.',
  },
  {
    type: 'drill', title: 'rijd, rijdt or rijden?', grammar: ['dt-rule', 'inversion', 'v2-inversion'], choices: ['rijd', 'rijdt', 'rijden'],
    instruction: 'Choose the form. Look at the subject, and at whether jij comes before or after the verb.',
    items: [
      { nl: 'Ik ___ naar Gent.', answer: 'rijd' },
      { nl: 'Bram ___ met de auto.', answer: 'rijdt' },
      { nl: '___ jij met de auto?', answer: 'rijd' },
      { nl: '___ Bram met de auto?', answer: 'rijdt' },
      { nl: 'Wij ___ naar Antwerpen.', answer: 'rijden' },
      { nl: 'De trein ___ naar Brussel.', answer: 'rijdt' },
      { nl: 'Morgen ___ jij.', answer: 'rijd' },
      { nl: 'Jij ___ heel goed.', answer: 'rijdt' },
    ],
  },
  {
    type: 'drill', title: 'd, t or dt?', grammar: ['dt-rule', 'present-regular', 'spelling-stem', 'inversion', 'v2-inversion'],
    instruction: 'Type the verb form. Stems in t add nothing; the stem rijd adds a t where lopen would. Mind jij behind the verb.',
    items: [
      { nl: 'Hij ___ naar Brussel.', cue: 'rijden', answer: 'rijdt' },
      { nl: 'Hij ___ op de bank.', cue: 'zitten', answer: 'zit' },
      { nl: 'Ik ___ met de auto.', cue: 'rijden', answer: 'rijd' },
      { nl: '___ jij met de fiets?', cue: 'rijden', answer: 'Rijd' },
      { nl: 'Lotte ___ met de oude man.', cue: 'praten', answer: 'praat' },
      { nl: '___ Bram vandaag?', cue: 'rijden', en: 'Is Bram driving today?', answer: 'Rijdt' },
      { nl: 'Bram ___ op de trein.', cue: 'wachten', answer: 'wacht' },
      { nl: 'Vandaag ___ jij met de auto.', cue: 'rijden', answer: 'rijd' },
      { nl: 'Mijn broer ___ Tom.', cue: 'heten', answer: 'heet' },
      { nl: 'Jij ___ heel goed.', cue: 'rijden', answer: 'rijdt' },
      { nl: 'Morgen ___ Lotte met de fiets naar de stad.', cue: 'rijden', answer: 'rijdt' },
      { nl: 'Wij ___ met de auto naar Gent.', cue: 'rijden', answer: 'rijden' },
    ],
    explanation: 'zit, praat, wacht, heet: the stem already ends in t — one t, never two. rijdt: the stem ends in d, so the t is added. Rijd jij? and Vandaag rijd jij: jij behind the verb, no t. Rijdt Bram?: Bram is not jij, so the t stays.',
  },
  {
    type: 'drill', title: 'Change it — and spell it', grammar: ['dt-rule', 'present-regular', 'yes-no-question', 'v2-inversion'],
    instruction: 'Rewrite each sentence as the task says. Every verb form must be spelt exactly.',
    items: [
      { nl: 'Ik rijd naar Gent.', task: 'Change ik to hij', answer: 'Hij rijdt naar Gent.' },
      { nl: 'Jij rijdt met de auto.', task: 'Make it a question', answer: 'Rijd jij met de auto?' },
      { nl: 'Bram rijdt morgen naar Gent.', task: 'Change Bram to ik', answer: 'Ik rijd morgen naar Gent.' },
      { nl: 'Wij rijden naar Antwerpen.', task: 'Change wij to jij', answer: 'Jij rijdt naar Antwerpen.' },
      { nl: 'Jij rijdt morgen.', task: 'Start with “morgen”', answer: 'Morgen rijd jij.' },
      { nl: 'Lotte rijdt niet met de auto.', task: 'Change Lotte to ik', answer: 'Ik rijd niet met de auto.' },
      { nl: 'Ik spreek Engels.', task: 'Change ik to Lotte', answer: 'Lotte spreekt Engels.' },
      { nl: 'Jij spreekt Nederlands.', task: 'Make it a question', answer: 'Spreek jij Nederlands?' },
      { nl: 'Hij helpt de oude man.', task: 'Change hij to wij', answer: 'Wij helpen de oude man.' },
      { nl: 'Jij helpt Noor vandaag.', task: 'Start with “vandaag”', answer: 'Vandaag help jij Noor.' },
    ],
  },

  // ——— Grammar: the four modals ———
  {
    type: 'grammar', title: 'kunnen, willen, moeten, mogen', grammar: ['modals', 'subject-pronouns', 'inversion'],
    body: [
      'Four verbs change the shape of a Dutch sentence: **kunnen** (can, be able to), **willen** (want), **moeten** (must, have to) and **mogen** (may, be allowed to). They are the *modal verbs*. They say how an action stands — possible, wanted, necessary, allowed — and a second verb says what the action is: *Ik **kan** zwemmen. Ik **wil** zwemmen. Ik **moet** werken. Ik **mag** hier zitten.*',
      'Their singular is irregular, and there is a reason. Long ago these were past-tense forms that came to be used for the present — which is also why English says *he can, he may, he must*, never *he cans*. So in Dutch too **hij gets no -t**: *hij kan, hij wil, hij mag*. (*hij moet* ends in t only because the stem itself is *moet*.) The plural is always the infinitive: *wij kunnen, willen, moeten, mogen*.',
      '**kunnen**: *ik kan, hij kan*. For **jij** two forms are correct: **jij kunt**, the standard written form taught here, and *jij kan*, very common in speech. Both are accepted in this course. In a question the standard form is *kun jij?* (kunt minus the jij-t); *kan jij?* is just as common in Flanders, and this course writes **Kan jij …?**',
      '**willen**: *ik wil*, **jij wilt**, but **hij wil** — jij takes a t, hij does not. *hij wilt* is a classic mistake. In a question jij loses its t again: ***Wil** jij koffie?*',
      '**moeten**: *ik moet, jij moet, hij moet* — the stem ends in t, so nothing is ever added, as with *zitten* and *wachten*. **mogen**: *ik mag, jij mag, hij mag* — a different vowel in the singular (*mag*, never *moog*), and no t anywhere.',
      '**Meaning traps.** *Ik wil* means “I want”, never “I will”: Dutch *wil* and English *will* are false friends. **mag niet** means “must not, is not allowed to”: *Max **mag niet** op het bed slapen.* So English “must not” is *mag niet*, not *moet niet*. And “don’t have to” is not *moet niet* in standard Dutch either — it needs another verb, which comes later. For now, say what someone must do, and use *mag niet* for what is forbidden.',
      '**kunnen** also means “know how to”: *Bram kan zwemmen* = he knows how to swim. When the second verb is obvious, Dutch simply leaves it out: *Ik **kan** een beetje Nederlands* (I speak a bit of Dutch), *Ik **wil** koffie*, *Mag ik een appel?* In the drills you will always write the second verb.',
    ],
    tables: [
      { caption: 'kunnen — can', rows: [
        { nl: 'ik kan', en: 'I can' },
        { nl: 'jij kun[t] / jij kan', en: 'you can — both correct' },
        { nl: 'hij kan', en: 'he can — no t' },
        { nl: 'wij kunnen', en: 'we can' },
        { nl: 'jullie kunnen', en: 'you (plural) can' },
        { nl: 'zij kunnen', en: 'they can' },
        { nl: 'kan jij?', en: 'can you? (standard spelling: kun jij?)' },
      ] },
      { caption: 'willen — want', rows: [
        { nl: 'ik wil', en: 'I want' },
        { nl: 'jij wil[t]', en: 'you want' },
        { nl: 'hij wil', en: 'he wants — no t!' },
        { nl: 'wij willen', en: 'we want' },
        { nl: 'zij willen', en: 'they want' },
        { nl: 'wil jij?', en: 'do you want? — no t' },
      ] },
      { caption: 'moeten — must, have to', rows: [
        { nl: 'ik moet', en: 'I must' },
        { nl: 'jij moet', en: 'you must' },
        { nl: 'hij moet', en: 'he must' },
        { nl: 'wij moeten', en: 'we must' },
        { nl: 'moet jij?', en: 'must you?' },
      ] },
      { caption: 'mogen — may, be allowed to', rows: [
        { nl: 'ik mag', en: 'I may' },
        { nl: 'jij mag', en: 'you may' },
        { nl: 'hij mag', en: 'he may' },
        { nl: 'wij mogen', en: 'we may' },
        { nl: 'mag ik?', en: 'may I?' },
      ] },
    ],
    examples: [
      { nl: 'Ik kan zwemmen.', en: 'I can swim.' },
      { nl: 'Jij kunt heel goed rijden.', en: 'You can drive very well.' },
      { nl: 'Wil jij koffie?', en: 'Do you want coffee?' },
      { nl: 'Lotte wil thee.', en: 'Lotte wants tea.' },
      { nl: 'Bram moet werken.', en: 'Bram has to work.' },
      { nl: 'Mag ik hier zitten?', en: 'May I sit here?' },
      { nl: 'Max mag niet op het bed slapen.', en: 'Max is not allowed to sleep on the bed.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate kunnen', grammar: ['modals', 'subject-pronouns'],
    instruction: 'Type the form of kunnen for every person. For jij, kunt is the standard form (kan is accepted too).',
    items: [
      { label: 'ik', gloss: 'I', answer: 'kan' },
      { label: 'jij', gloss: 'you', answer: 'kunt', accept: ['kan'] },
      { label: 'hij', gloss: 'he', answer: 'kan' },
      { label: 'zij', gloss: 'she', answer: 'kan' },
      { label: 'wij', gloss: 'we', answer: 'kunnen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'kunnen' },
      { label: 'zij', gloss: 'they', answer: 'kunnen' },
      { label: 'Lotte', gloss: 'she', answer: 'kan' },
    ],
    explanation: 'Singular kan with a, plural kunnen with u. hij kan, never hij kant.',
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate willen', grammar: ['modals', 'subject-pronouns'],
    instruction: 'Type the form of willen for every person. One of them takes a t — only one.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'wil' },
      { label: 'jij', gloss: 'you', answer: 'wilt' },
      { label: 'hij', gloss: 'he', answer: 'wil' },
      { label: 'zij', gloss: 'she', answer: 'wil' },
      { label: 'wij', gloss: 'we', answer: 'willen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'willen' },
      { label: 'zij', gloss: 'they', answer: 'willen' },
      { label: 'Bram', gloss: 'he', answer: 'wil' },
    ],
    explanation: 'jij wilt — hij wil. The only t in the whole verb belongs to jij, and it goes again in “wil jij?”.',
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate moeten and mogen', grammar: ['modals', 'subject-pronouns'],
    instruction: 'The small word under each person tells you the verb. Type the form.',
    items: [
      { label: 'ik', gloss: 'moeten', answer: 'moet' },
      { label: 'jij', gloss: 'moeten', answer: 'moet' },
      { label: 'hij', gloss: 'moeten', answer: 'moet' },
      { label: 'wij', gloss: 'moeten', answer: 'moeten' },
      { label: 'jullie', gloss: 'moeten', answer: 'moeten' },
      { label: 'zij', gloss: 'they · moeten', answer: 'moeten' },
      { label: 'ik', gloss: 'mogen', answer: 'mag' },
      { label: 'jij', gloss: 'mogen', answer: 'mag' },
      { label: 'zij', gloss: 'she · mogen', answer: 'mag' },
      { label: 'wij', gloss: 'mogen', answer: 'mogen' },
      { label: 'jullie', gloss: 'mogen', answer: 'mogen' },
      { label: 'het kind', gloss: 'it · mogen', answer: 'mag' },
    ],
    explanation: 'moet for every singular person, never moett. mag for every singular person, with a; mogen with o.',
  },
  {
    type: 'drill', title: 'Which form?', grammar: ['modals', 'inversion'],
    instruction: 'Choose the form. Look at the subject — and remember that hij never takes a t in these verbs.',
    items: [
      { nl: 'Ik ___ zwemmen.', choices: ['kan', 'kunt', 'kunnen'], answer: 'kan' },
      { nl: 'Bram ___ goed rijden.', choices: ['kan', 'kunt', 'kunnen'], answer: 'kan' },
      { nl: 'Wij ___ een beetje Nederlands spreken.', choices: ['kan', 'kunt', 'kunnen'], answer: 'kunnen' },
      { nl: 'Bram ___ koffie drinken.', choices: ['wil', 'wilt', 'willen'], answer: 'wil' },
      { nl: 'Jij ___ naar het park gaan.', choices: ['wil', 'wilt', 'willen'], answer: 'wilt' },
      { nl: '___ jij koffie?', choices: ['wil', 'wilt', 'willen'], answer: 'wil' },
      { nl: 'Het kind ___ spelen.', choices: ['wil', 'wilt', 'willen'], answer: 'wil' },
      { nl: 'Max ___ niet op het bed slapen.', choices: ['mag', 'mogen', 'moeten'], answer: 'mag' },
    ],
  },
  {
    type: 'drill', title: 'Type the modal', grammar: ['modals', 'inversion', 'niet', 'infinitive-end'],
    instruction: 'Type the form of the verb in brackets. For kunnen with jij, type kunt in a statement (kan is accepted) and kan in a question.',
    items: [
      { nl: 'Ik ___ goed zwemmen.', cue: 'kunnen', answer: 'kan' },
      { nl: 'Lotte ___ niet rijden.', cue: 'kunnen', answer: 'kan' },
      { nl: 'Jij ___ heel goed Engels spreken.', cue: 'kunnen', answer: 'kunt', accept: ['kan'] },
      { nl: '___ jij zwemmen?', cue: 'kunnen', answer: 'Kan' },
      { nl: 'Wij ___ een beetje Nederlands spreken.', cue: 'kunnen', answer: 'kunnen' },
      { nl: 'Bram ___ vandaag naar Gent gaan.', cue: 'willen', answer: 'wil' },
      { nl: 'Jij ___ een appel eten.', cue: 'willen', answer: 'wilt' },
      { nl: '___ jij thee?', cue: 'willen', answer: 'Wil' },
      { nl: 'Jullie ___ in Leuven wonen.', cue: 'willen', answer: 'willen' },
      { nl: 'Ik ___ vandaag thuis werken.', cue: 'moeten', answer: 'moet' },
      { nl: '___ jij vandaag werken?', cue: 'moeten', answer: 'Moet' },
      { nl: 'Wij ___ de oude man helpen.', cue: 'moeten', answer: 'moeten' },
      { nl: '___ ik hier zitten?', cue: 'mogen', answer: 'Mag' },
      { nl: 'Max ___ niet in de keuken komen.', cue: 'mogen', answer: 'mag' },
      { nl: 'De kinderen ___ in de tuin spelen.', cue: 'mogen', answer: 'mogen' },
    ],
    explanation: 'Only the modal changes; the second verb stays an infinitive at the end. “De kinderen” is plural, so mogen — the plural of every modal is its infinitive.',
  },

  // ——— Grammar: the infinitive at the end ———
  {
    type: 'grammar', title: 'The second verb goes to the end', grammar: ['infinitive-end', 'modals', 'v2-inversion', 'time-place', 'niet', 'geen-niet'],
    body: [
      'A modal verb takes the **second place**, like every conjugated verb. The verb that says what happens goes, unchanged, to the **very end** of the sentence, as an infinitive: *Ik **wil** morgen naar het park **gaan**.* Everything else — time, niet, how, place, object — stands between the two. Think of the two verbs as a frame around the rest of the sentence.',
      'You have used this frame before: *Ik ga slapen. Bram gaat koffie drinken.* (lesson 6). gaan + infinitive and the four modals work the same way.',
      'There is no word for “to”: *I want to swim* is *Ik wil zwemmen*. And English order is the trap again. English puts its second verb early — “I want **to go** to the park tomorrow” — Dutch keeps it for last: *Ik wil morgen naar het park **gaan***. Say the sentence to the end before you let the infinitive out.',
      '**Inside the frame** the order is the one you know: **time, (niet), how, place**, and an object comes last, right before the infinitive: *Bram moet vandaag met de trein naar Brussel gaan. Lotte wil een boek lezen. Bram wil de oude man helpen.*',
      '**Verb second still rules.** Put the time first and the subject moves behind the modal; the infinitive stays at the end: *Morgen **moet** ik **werken**. Vandaag **wil** Lotte thuis **lezen**.* With jij behind the modal, the jij-rule applies to the modal: *jij wilt → Morgen **wil** jij …*; *moet* and *mag* do not change; *kunt → **kan** jij* (standard: *kun jij*).',
      '**Questions** work the same way: the modal goes to the front, or follows the question word, and the infinitive waits at the end: ***Kan** jij goed **zwemmen**? **Waar** wil jij **wonen**? **Wat** wil jij **drinken**?*',
      '**Negation.** **niet** comes after the modal and the subject (and after a time word), before how, place and the infinitive: *Ik kan **niet** zwemmen. Lotte kan **niet** rijden. Bram wil vandaag **niet** naar het park gaan.* **geen** still replaces een, or no article, before a noun: *Ik wil **geen** koffie drinken. Hij wil **geen** appel eten.*',
      'Only the modal is conjugated. The infinitive never changes with the subject: *Hij wil zwemmen* — never *hij wil zwemt*.',
    ],
    tables: [
      { caption: 'subject · modal · … · infinitive', rows: [
        { nl: 'Ik [kan] goed [zwemmen].', en: 'I can swim well.' },
        { nl: 'Bram [moet] vandaag in Brussel [werken].', en: 'Bram has to work in Brussels today.' },
        { nl: 'Lotte [wil] een boek [lezen].', en: 'Lotte wants to read a book.' },
        { nl: 'Wij [willen] morgen naar het park [gaan].', en: 'We want to go to the park tomorrow.' },
        { nl: 'Ik [kan] niet [zwemmen].', en: 'I can’t swim.' },
        { nl: 'Ik [wil] geen koffie [drinken].', en: 'I don’t want to drink coffee.' },
      ] },
      { caption: 'time first · modal · subject · … · infinitive', rows: [
        { nl: 'Morgen [moet] ik [werken].', en: 'Tomorrow I have to work.' },
        { nl: 'Vandaag [wil] Lotte thuis [lezen].', en: 'Today Lotte wants to read at home.' },
        { nl: 'Morgen [wil] jij naar Gent [gaan].', en: 'Tomorrow you want to go to Ghent. (jij wilt → wil jij)' },
      ] },
      { caption: 'questions', rows: [
        { nl: '[Kan] jij goed [zwemmen]?', en: 'Can you swim well?' },
        { nl: '[Wil] jij koffie [drinken]?', en: 'Do you want to drink coffee?' },
        { nl: 'Waar [wil] jij [wonen]?', en: 'Where do you want to live?' },
        { nl: '[Mag] ik hier [zitten]?', en: 'May I sit here?' },
      ] },
    ],
    examples: [
      { nl: 'Bram moet vandaag met de trein naar Brussel gaan.', en: 'Bram has to go to Brussels by train today.' },
      { nl: 'Lotte kan niet rijden.', en: 'Lotte can’t drive.' },
      { nl: 'Morgen wil ik de oude man helpen.', en: 'Tomorrow I want to help the old man.' },
      { nl: 'Wat wil jij drinken?', en: 'What do you want to drink?' },
    ],
  },
  {
    type: 'arrange', title: 'The frame', grammar: ['infinitive-end', 'modals', 'time-place'],
    instruction: 'Build: “I want to go to the park tomorrow.” Two tiles are traps.',
    nl: 'Ik wil morgen naar het park gaan.', en: 'I want to go to the park tomorrow.', image: 'park', distractors: ['ga', 'wilt'],
  },
  {
    type: 'drill', title: 'Add the modal', grammar: ['infinitive-end', 'modals', 'niet', 'geen-niet', 'time-place'],
    instruction: 'Add the modal verb. It takes the verb’s place and form; the old verb goes to the end as an infinitive. Nothing else moves.',
    items: [
      { nl: 'Ik zwem.', task: 'Add “kunnen”', answer: 'Ik kan zwemmen.' },
      { nl: 'Bram werkt vandaag in Brussel.', task: 'Add “moeten”', answer: 'Bram moet vandaag in Brussel werken.' },
      { nl: 'Lotte leest een boek.', task: 'Add “willen”', answer: 'Lotte wil een boek lezen.' },
      { nl: 'Wij gaan morgen naar het park.', task: 'Add “willen”', answer: 'Wij willen morgen naar het park gaan.' },
      { nl: 'Jij kookt vandaag.', task: 'Add “moeten”', answer: 'Jij moet vandaag koken.' },
      { nl: 'Max slaapt niet op het bed.', task: 'Add “mogen”', answer: 'Max mag niet op het bed slapen.' },
      { nl: 'Lotte rijdt niet.', task: 'Add “kunnen”', answer: 'Lotte kan niet rijden.' },
      { nl: 'Ik drink geen koffie.', task: 'Add “willen”', answer: 'Ik wil geen koffie drinken.' },
      { nl: 'Jij spreekt heel goed Engels.', task: 'Add “kunnen”', answer: 'Jij kunt heel goed Engels spreken.', accept: ['Jij kan heel goed Engels spreken.'] },
      { nl: 'Het kind speelt in de tuin.', task: 'Add “mogen”', answer: 'Het kind mag in de tuin spelen.' },
      { nl: 'Wij wachten op de trein.', task: 'Add “moeten”', answer: 'Wij moeten op de trein wachten.' },
      { nl: 'Hij schrijft een boek.', task: 'Add “willen”', answer: 'Hij wil een boek schrijven.' },
    ],
    explanation: 'The modal is conjugated for the subject (kan, moet, wil, mag), the old verb becomes an infinitive and goes last: zwem → zwemmen, rijdt → rijden, slaapt → slapen. “op de trein wachten”: the place-phrase stays inside the frame.',
  },
  {
    type: 'drill', title: 'Say it with a modal', grammar: ['infinitive-end', 'modals', 'yes-no-question', 'time-place'],
    instruction: 'Translate. Modal second, infinitive last, no word for “to”. For “can you”, write Kan jij.',
    items: [
      { en: 'I can swim.', answer: 'Ik kan zwemmen.' },
      { en: 'Lotte can’t drive.', answer: 'Lotte kan niet rijden.' },
      { en: 'Bram wants to drink coffee.', answer: 'Bram wil koffie drinken.' },
      { en: 'Do you want to eat an apple? (one person)', answer: 'Wil jij een appel eten?' },
      { en: 'I have to work today.', answer: 'Ik moet vandaag werken.', accept: ['Vandaag moet ik werken.'] },
      { en: 'May I sit here?', answer: 'Mag ik hier zitten?' },
      { en: 'The dog is not allowed to sleep on the bed.', answer: 'De hond mag niet op het bed slapen.' },
      { en: 'We want to live in Leuven.', answer: 'Wij willen in Leuven wonen.' },
      { en: 'He wants to help the old man.', answer: 'Hij wil de oude man helpen.' },
      { en: 'You (plural) have to go to the station.', answer: 'Jullie moeten naar het station gaan.' },
      { en: 'Can you speak English? (one person)', answer: 'Kan jij Engels spreken?' },
      { en: 'Lotte wants to read a book at home today.', answer: 'Lotte wil vandaag thuis een boek lezen.', accept: ['Vandaag wil Lotte thuis een boek lezen.'] },
    ],
    explanation: 'vandaag · thuis · een boek · lezen: time, place, object, infinitive. The English order (“read a book at home today”) is exactly backwards.',
  },
  {
    type: 'drill', title: 'Start with the time', grammar: ['infinitive-end', 'v2-inversion', 'modals', 'dt-rule'],
    task: 'Start with the time word',
    instruction: 'Move the time word to the front. The modal stays second, the subject moves behind it, the infinitive stays last. jij wilt becomes wil jij; for kunnen write kan jij.',
    items: [
      { nl: 'Ik moet morgen werken.', answer: 'Morgen moet ik werken.' },
      { nl: 'Lotte wil vandaag thuis lezen.', answer: 'Vandaag wil Lotte thuis lezen.' },
      { nl: 'Jij wilt morgen naar Gent gaan.', answer: 'Morgen wil jij naar Gent gaan.' },
      { nl: 'Jij moet nu slapen.', answer: 'Nu moet jij slapen.' },
      { nl: 'Bram kan vandaag niet zwemmen.', answer: 'Vandaag kan Bram niet zwemmen.' },
      { nl: 'Wij willen morgen met de trein naar Antwerpen gaan.', answer: 'Morgen willen wij met de trein naar Antwerpen gaan.' },
      { nl: 'Het kind mag nu in de tuin spelen.', answer: 'Nu mag het kind in de tuin spelen.' },
      { nl: 'Jij rijdt morgen met de auto.', answer: 'Morgen rijd jij met de auto.' },
      { nl: 'Bram moet vandaag zijn vader helpen.', answer: 'Vandaag moet Bram zijn vader helpen.' },
      { nl: 'Jij kunt morgen met de fiets gaan.', answer: 'Morgen kan jij met de fiets gaan.' },
    ],
    explanation: 'Time · modal · subject · the rest · infinitive. Morgen wil jij (not wilt), Morgen rijd jij (not rijdt): jij behind the verb never takes the t.',
  },
  {
    type: 'arrange', title: 'Tomorrow, Brussels', grammar: ['infinitive-end', 'v2-inversion', 'modals'],
    instruction: 'Build: “Tomorrow Bram has to work in Brussels.” Two tiles are traps.',
    nl: 'Morgen moet Bram in Brussel werken.', en: 'Tomorrow Bram has to work in Brussels.', image: 'man-working', distractors: ['werkt', 'moeten'],
  },
  {
    type: 'drill', title: 'Say no: niet or geen?', grammar: ['niet', 'geen-niet', 'geen', 'infinitive-end', 'hebben'],
    task: 'Make it negative',
    instruction: 'Make each sentence negative. A noun with een or no article (a language too) takes geen; everything else takes niet — after the modal and subject, before place and infinitive.',
    items: [
      { nl: 'Ik kan zwemmen.', answer: 'Ik kan niet zwemmen.' },
      { nl: 'Bram wil koffie drinken.', answer: 'Bram wil geen koffie drinken.' },
      { nl: 'Max mag op het bed slapen.', answer: 'Max mag niet op het bed slapen.' },
      { nl: 'Ik wil een appel eten.', answer: 'Ik wil geen appel eten.' },
      { nl: 'Vandaag wil Bram naar het park gaan.', answer: 'Vandaag wil Bram niet naar het park gaan.' },
      { nl: 'De oude man spreekt Engels.', answer: 'De oude man spreekt geen Engels.' },
      { nl: 'Het kind mag in de keuken spelen.', answer: 'Het kind mag niet in de keuken spelen.' },
      { nl: 'Jij wilt thee drinken.', answer: 'Jij wilt geen thee drinken.' },
      { nl: 'Morgen kan Lotte met de fiets gaan.', answer: 'Morgen kan Lotte niet met de fiets gaan.' },
      { nl: 'Ik kan goed zwemmen.', answer: 'Ik kan niet goed zwemmen.' },
      { nl: 'Mijn broer heeft een auto.', answer: 'Mijn broer heeft geen auto.' },
    ],
    explanation: 'geen koffie, geen appel, geen Engels, geen auto — nouns with een or no article. niet zwemmen, niet op het bed, niet naar het park, niet goed — everything else. niet stands before goed: “niet goed zwemmen”.',
  },
  {
    type: 'drill', title: 'Ask the question', grammar: ['yes-no-question', 'question-word', 'wie-hoe', 'infinitive-end', 'inversion'],
    instruction: 'Rewrite as the task says. The modal goes first, or straight after the question word; the infinitive stays at the end. For kunnen write Kan jij.',
    items: [
      { nl: 'Jij kunt goed zwemmen.', task: 'Make it a question', answer: 'Kan jij goed zwemmen?' },
      { nl: 'Jij wilt koffie drinken.', task: 'Make it a question', answer: 'Wil jij koffie drinken?' },
      { nl: 'Bram moet morgen werken.', task: 'Make it a question', answer: 'Moet Bram morgen werken?' },
      { nl: 'Ik mag hier zitten.', task: 'Make it a question', answer: 'Mag ik hier zitten?' },
      { nl: 'Jullie willen naar Gent gaan.', task: 'Make it a question', answer: 'Willen jullie naar Gent gaan?' },
      { nl: 'Bram wil in Gent wonen.', task: 'Ask with “waar”', answer: 'Waar wil Bram wonen?' },
      { nl: 'Jij wilt thee drinken.', task: 'Ask with “wat”', answer: 'Wat wil jij drinken?' },
      { nl: 'Lotte spreekt heel goed Engels.', task: 'Ask with “hoe”', answer: 'Hoe spreekt Lotte Engels?' },
      { nl: 'Bram helpt de oude man.', task: 'Ask who helps: “wie”', answer: 'Wie helpt de oude man?' },
      { nl: 'Jij moet vandaag in Brussel werken.', task: 'Ask with “waar”', answer: 'Waar moet jij vandaag werken?' },
      { nl: 'Jouw zus heet Sofie.', task: 'Ask with “hoe”', answer: 'Hoe heet jouw zus?' },
    ],
    explanation: 'The part you ask about disappears: Waar wil Bram wonen? (in Gent is gone). When wie is the subject, the verb is simply second: Wie helpt de oude man?',
  },
  {
    type: 'arrange', title: 'Can you swim well?', grammar: ['modals', 'infinitive-end', 'yes-no-question'],
    instruction: 'Build: “Can you swim well?” Two tiles are traps.',
    nl: 'Kan jij goed zwemmen?', en: 'Can you swim well?', image: 'man-swimming', distractors: ['kunt', 'zwemt'],
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', layout: 'table', title: 'Every verb you know', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'zijn', 'hebben', 'gaan', 'modals', 'dt-rule', 'subject-pronouns'],
    instruction: 'All twenty-seven verbs of the course, mixed. The small word under each person is the verb to use. Type the form.',
    items: [
      { label: 'ik', gloss: 'zijn', answer: 'ben' },
      { label: 'jij', gloss: 'hebben', answer: 'hebt' },
      { label: 'hij', gloss: 'wonen', answer: 'woont' },
      { label: 'zij', gloss: 'she · werken', answer: 'werkt' },
      { label: 'wij', gloss: 'lopen', answer: 'lopen' },
      { label: 'jullie', gloss: 'zitten', answer: 'zitten' },
      { label: 'zij', gloss: 'they · slapen', answer: 'slapen' },
      { label: 'ik', gloss: 'koken', answer: 'kook' },
      { label: 'jij', gloss: 'spelen', answer: 'speelt' },
      { label: 'hij', gloss: 'leren', answer: 'leert' },
      { label: 'ik', gloss: 'praten', answer: 'praat' },
      { label: 'jij', gloss: 'wachten', answer: 'wacht' },
      { label: 'zij', gloss: 'she · lezen', answer: 'leest' },
      { label: 'ik', gloss: 'eten', answer: 'eet' },
      { label: 'hij', gloss: 'drinken', answer: 'drinkt' },
      { label: 'ik', gloss: 'schrijven', answer: 'schrijf' },
      { label: 'jij', gloss: 'gaan', answer: 'gaat' },
      { label: 'hij', gloss: 'komen', answer: 'komt' },
      { label: 'jij', gloss: 'heten', answer: 'heet' },
      { label: 'ik', gloss: 'kunnen', answer: 'kan' },
      { label: 'hij', gloss: 'willen', answer: 'wil' },
      { label: 'jij', gloss: 'willen', answer: 'wilt' },
      { label: 'zij', gloss: 'she · mogen', answer: 'mag' },
      { label: 'ik', gloss: 'zwemmen', answer: 'zwem' },
      { label: 'jij', gloss: 'spreken', answer: 'spreekt' },
      { label: 'hij', gloss: 'rijden', answer: 'rijdt' },
      { label: 'wij', gloss: 'helpen', answer: 'helpen' },
      { label: 'jij', gloss: 'moeten', answer: 'moet' },
    ],
    explanation: 'The traps, all in one place: zitten → zit, praten → praat, wachten → wacht, heten → heet (stem in t, nothing added); rijden → rijdt (stem in d, t added); lezen → leest, schrijven → schrijf (z → s, v → f); zwemmen → zwem (no double consonant at the end); kom, ga; and hij wil, hij kan, hij mag with no t at all.',
  },
  {
    type: 'drill', title: 'Conjugated or infinitive?', grammar: ['infinitive-end', 'present-regular', 'modals', 'dt-rule', 'v2-inversion', 'spelling-z-s'],
    instruction: 'Type the right form of the verb in brackets. If a modal is already in the sentence, the verb goes to the end as an infinitive; if not, conjugate it.',
    items: [
      { nl: 'Bram ___ koffie.', cue: 'drinken', answer: 'drinkt' },
      { nl: 'Bram wil koffie ___.', cue: 'drinken', answer: 'drinken' },
      { nl: 'Lotte ___ een boek.', cue: 'lezen', answer: 'leest' },
      { nl: 'Lotte wil vandaag een boek ___.', cue: 'lezen', answer: 'lezen' },
      { nl: 'Mijn familie ___ in Gent.', cue: 'wonen', en: 'My family lives in Ghent.', answer: 'woont' },
      { nl: '___ jij met de auto?', cue: 'rijden', answer: 'Rijd' },
      { nl: 'Kan jij met de auto ___?', cue: 'rijden', answer: 'rijden' },
      { nl: 'Het kind ___ in de tuin.', cue: 'spelen', answer: 'speelt' },
      { nl: 'Het kind mag in de tuin ___.', cue: 'spelen', answer: 'spelen' },
      { nl: 'Morgen ___ jij thuis.', cue: 'werken', answer: 'werk' },
      { nl: 'Morgen moet jij thuis ___.', cue: 'werken', answer: 'werken' },
      { nl: 'Nu ___ de kat op het bed.', cue: 'slapen', answer: 'slaapt' },
      { nl: 'Mijn moeder ___ heel goed.', cue: 'koken', answer: 'kookt' },
      { nl: 'Wil jij vandaag ___?', cue: 'koken', answer: 'koken' },
      { nl: 'Hoe ___ jouw vriendin?', cue: 'heten', answer: 'heet' },
      { nl: 'Bram ___ een boek.', cue: 'schrijven', answer: 'schrijft' },
    ],
    explanation: 'One conjugated verb per sentence, in second place (or first in a question). A second verb is always the infinitive, and always last.',
  },
  {
    type: 'drill', title: 'Every day, a modal', grammar: ['modals', 'infinitive-end', 'adjective-e', 'geen-niet', 'hij-het-things'],
    instruction: 'Type the form of the verb in brackets. Read the whole sentence first: who is the subject, and what is at the end?',
    items: [
      { nl: 'Waar is mijn sleutel? Ik ___ naar Brussel gaan.', cue: 'moeten', answer: 'moet' },
      { nl: 'Waar is mijn jas? Ik ___ naar de stad gaan.', cue: 'willen', answer: 'wil' },
      { nl: 'Bram ___ brood met kaas eten.', cue: 'willen', answer: 'wil' },
      { nl: 'Lotte ___ geen kaas eten.', cue: 'willen', answer: 'wil' },
      { nl: '___ ik wat water? Ik ben ziek.', cue: 'mogen', en: 'May I have some water? I’m ill.', answer: 'Mag' },
      { nl: 'Noor is vijf jaar. Zij ___ naar school gaan.', cue: 'moeten', answer: 'moet' },
      { nl: 'Het kind ___ niet met de telefoon spelen.', cue: 'mogen', answer: 'mag' },
      { nl: 'Max is heel lief, maar hij ___ niet op de stoel zitten.', cue: 'mogen', answer: 'mag' },
      { nl: 'De kat ___ in de boom zitten.', cue: 'willen', answer: 'wil' },
      { nl: 'De oude vrouw ___ niet goed lopen.', cue: 'kunnen', answer: 'kan' },
      { nl: 'Bram ___ de oude man met de deur helpen.', cue: 'willen', answer: 'wil' },
      { nl: '___ ik op de nieuwe stoel zitten?', cue: 'mogen', answer: 'Mag' },
      { nl: 'Wij ___ nu naar het station gaan; de trein komt.', cue: 'moeten', answer: 'moeten' },
      { nl: 'Lotte ___ vandaag veel lezen.', cue: 'willen', answer: 'wil' },
    ],
    explanation: 'hij wil, zij wil, de kat wil — no t. “Mag ik wat water?” is the everyday way to ask for something: wat here means “some”.',
  },
  {
    type: 'drill', title: 'Everything so far', grammar: ['adjective-e', 'possessives', 'er-is-zijn', 'plural', 'numbers', 'wie-hoe', 'geen-niet', 'hij-het-things', 'de-het'],
    instruction: 'Type the missing word. Adjective endings, possessives, plurals, er is / er zijn, wie and hoe — all with this lesson’s words.',
    items: [
      { nl: 'Bram heeft een ___ vriend, Jonas.', cue: 'goed', answer: 'goede' },
      { nl: 'Dit is een ___ boek.', cue: 'goed', answer: 'goed' },
      { nl: 'Lotte is een ___ vrouw.', cue: 'jong', answer: 'jonge' },
      { nl: 'De oude man heeft een ___ tas.', cue: 'groot', answer: 'grote' },
      { nl: 'Leuven is een ___ stad.', cue: 'mooi', answer: 'mooie' },
      { nl: 'Lotte en ___ vriendin Emma willen naar de stad gaan.', cue: 'her', answer: 'haar' },
      { nl: 'Bram wil ___ vader in Gent helpen.', cue: 'his', answer: 'zijn' },
      { nl: 'Wij willen in ___ tuin zitten.', cue: 'our', answer: 'onze' },
      { nl: 'Er ___ drie kamers in ons huis.', cue: 'is / zijn', answer: 'zijn' },
      { nl: 'Er ___ één boom in de tuin.', cue: 'is / zijn', answer: 'is' },
      { nl: 'De oude man heeft twee ___.', cue: 'kat', answer: 'katten' },
      { nl: 'Hoeveel ___ zijn er in de keuken? — Vier.', cue: 'stoel', answer: 'stoelen' },
      { nl: '___ helpt de oude man?', en: 'Who is helping the old man?', answer: 'Wie' },
      { nl: '___ oud is Noor? — Zij is vijf jaar.', en: 'How old is Noor?', answer: 'Hoe' },
      { nl: 'De tafel is klein. ___ is klein.', cue: 'hij / het', answer: 'Hij' },
      { nl: 'Het raam is groot. ___ is groot.', cue: 'hij / het', answer: 'Het' },
    ],
    explanation: 'een goede vriend but een goed boek: een + het-word keeps the bare adjective. onze tuin (de-word), ons huis (het-word). Er is + one thing, er zijn + a plural. de tafel → hij, het raam → het.',
  },
  {
    type: 'drill', title: 'Family and friends', grammar: ['possessives', 'wie-hoe', 'modals', 'infinitive-end', 'plural', 'numbers'],
    instruction: 'Translate. Everyone from the story so far — now with modal verbs.',
    items: [
      { en: 'My father can drive well.', answer: 'Mijn vader kan goed rijden.' },
      { en: 'His mother cooks very well.', answer: 'Zijn moeder kookt heel goed.' },
      { en: 'Her brother is called Tom.', answer: 'Haar broer heet Tom.' },
      { en: 'Bram has a sister; her name is Sofie.', answer: 'Bram heeft een zus; haar naam is Sofie.', accept: ['Bram heeft een zus; zij heet Sofie.', 'Bram heeft een zus en haar naam is Sofie.', 'Bram heeft een zus en zij heet Sofie.'] },
      { en: 'What is your name? (one person)', answer: 'Wat is jouw naam?', accept: ['Wat is je naam?', 'Hoe heet jij?'] },
      { en: 'Noor is five years old.', answer: 'Noor is vijf jaar oud.', accept: ['Noor is vijf jaar.'] },
      { en: 'Emma is a good friend. (female)', answer: 'Emma is een goede vriendin.' },
      { en: 'Can your friend swim? (one person; the friend is male)', answer: 'Kan jouw vriend zwemmen?', accept: ['Kan je vriend zwemmen?'] },
      { en: 'Our family lives in Belgium.', answer: 'Onze familie woont in België.' },
      { en: 'The children want to play in the garden.', answer: 'De kinderen willen in de tuin spelen.' },
      { en: 'Jonas wants to learn Dutch.', answer: 'Jonas wil Nederlands leren.' },
    ],
    explanation: 'familie is a de-word, so onze familie. “Can your friend swim?”: the modal first, the infinitive last — Kan jouw vriend zwemmen?',
  },
  {
    type: 'drill', title: 'Look and answer in full', grammar: ['yes-no-question', 'modals', 'infinitive-end', 'er-is-zijn', 'zijn', 'dt-rule'],
    task: 'Answer in full',
    instruction: 'Look at the picture and answer with a complete sentence. Keep the modal and put the infinitive at the end.',
    items: [
      { image: 'man-swimming', nl: 'Kan Bram zwemmen?', answer: 'Ja, Bram kan zwemmen.', accept: ['Ja, hij kan zwemmen.', 'Ja, Bram kan goed zwemmen.', 'Ja, hij kan goed zwemmen.', 'Ja, Bram kan heel goed zwemmen.', 'Ja, hij kan heel goed zwemmen.'] },
      { image: 'woman-bike', nl: 'Kan Lotte rijden?', answer: 'Nee, Lotte kan niet rijden.', accept: ['Nee, zij kan niet rijden.'] },
      { image: 'man-helping', nl: 'Wie helpt de oude man?', answer: 'Bram helpt de oude man.' },
      { image: 'man-driving', nl: 'Rijdt Bram met de trein?', answer: 'Nee, Bram rijdt met de auto.', accept: ['Nee, hij rijdt met de auto.'] },
      { image: 'couple-talking', nl: 'Spreken Bram en Lotte Nederlands?', answer: 'Ja, Bram en Lotte spreken Nederlands.', accept: ['Ja, zij spreken Nederlands.'] },
      { image: 'coffee', nl: 'Wil Lotte koffie?', answer: 'Nee, Lotte wil geen koffie.', accept: ['Nee, zij wil geen koffie.'] },
      { image: 'cats-two', nl: 'Hoeveel katten zijn er?', answer: 'Er zijn twee katten.' },
      { image: 'woman-sick', nl: 'Is Lotte vandaag ziek?', answer: 'Ja, Lotte is vandaag ziek.', accept: ['Ja, zij is vandaag ziek.', 'Ja, vandaag is Lotte ziek.', 'Ja, vandaag is zij ziek.', 'Ja, Lotte is ziek.', 'Ja, zij is ziek.'] },
      { image: 'man-tired', nl: 'Is Bram blij?', answer: 'Nee, Bram is moe.', accept: ['Nee, hij is moe.', 'Nee, Bram is niet blij.', 'Nee, hij is niet blij.', 'Nee, Bram is niet blij; hij is moe.', 'Nee, hij is niet blij; hij is moe.'] },
    ],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Kan ik helpen?', image: 'man-helping', grammar: ['modals', 'infinitive-end', 'v2-inversion', 'adjective-e', 'geen-niet', 'dt-rule'],
    instruction: 'A morning in the street in Leuven. Read and listen to every line, then read it again without the English. Find every modal — and the infinitive that belongs to it.',
    lines: [
      { nl: 'Vandaag werkt Bram niet in Brussel. In de straat loopt de oude man met een grote, oude tas.', en: 'Today Bram isn’t working in Brussels. In the street the old man is walking with a big old bag.', image: 'old-man' },
      { speaker: 'Bram', nl: 'Kan ik helpen? De tas is heel groot.', en: 'Can I help? The bag is very big.', image: 'man-helping' },
      { speaker: 'De oude man', nl: 'Ja, graag! Ik ben oud; ik kan niet goed lopen.', en: 'Yes, please! I’m old; I can’t walk well.', image: 'old-man' },
      { nl: 'Bram helpt de oude man met zijn tas. Dan zitten ze op de bank.', en: 'Bram helps the old man with his bag. Then they sit on the bench.', image: 'bench' },
      { speaker: 'De oude man', nl: 'Jij bent een goede man, Bram. Werk jij vandaag niet?', en: 'You’re a good man, Bram. Aren’t you working today?', image: 'old-man' },
      { speaker: 'Bram', nl: 'Nee, vandaag ga ik zwemmen. Ik kan heel goed zwemmen!', en: 'No, today I’m going swimming. I can swim very well!', image: 'man-swimming' },
      { speaker: 'De oude man', nl: 'En Lotte? Wil zij ook zwemmen?', en: 'And Lotte? Does she want to swim too?', image: 'old-man' },
      { speaker: 'Bram', nl: 'Nee, Lotte moet thuis werken. Zij schrijft in het Engels en in het Nederlands.', en: 'No, Lotte has to work at home. She writes in English and in Dutch.', image: 'woman-working' },
      { speaker: 'Lotte', nl: 'Bram, ik moet naar de winkel gaan. Wij hebben geen brood.', en: 'Bram, I have to go to the shop. We have no bread.', image: 'woman-bike' },
      { speaker: 'De oude man', nl: 'Met de fiets? Kan jij niet rijden, Lotte?', en: 'By bike? Can’t you drive, Lotte?', image: 'old-man' },
      { speaker: 'Lotte', nl: 'Nee, ik kan niet rijden. Bram rijdt heel goed, maar wij hebben geen auto.', en: 'No, I can’t drive. Bram drives very well, but we have no car.', image: 'woman-bike' },
      { speaker: 'De oude man', nl: 'Spreek jij ook Engels? Ik spreek geen Engels, maar ik wil het graag leren.', en: 'Do you speak English too? I don’t speak English, but I’d like to learn it.', image: 'old-man' },
      { speaker: 'Lotte', nl: 'Ja, ik spreek heel goed Engels. Morgen kom ik, en dan leren wij Engels!', en: 'Yes, I speak English very well. Tomorrow I’ll come, and then we’ll learn English!', image: 'woman' },
      { nl: 'En ik? Ik spreek een beetje Nederlands, en ik wil het heel goed leren.', en: 'And me? I speak a bit of Dutch, and I want to learn it very well.' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'modals', 'hebben'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the story. Answer without looking back.',
    items: [
      { nl: 'Werkt Bram vandaag in Brussel?', answer: 'Nee' },
      { nl: 'Heeft de oude man een kleine tas?', answer: 'Nee' },
      { nl: 'Kan de oude man goed lopen?', answer: 'Nee' },
      { nl: 'Helpt Bram de oude man?', answer: 'Ja' },
      { nl: 'Kan Bram goed zwemmen?', answer: 'Ja' },
      { nl: 'Moet Lotte vandaag thuis werken?', answer: 'Ja' },
      { nl: 'Kan Lotte rijden?', answer: 'Nee' },
      { nl: 'Hebben Bram en Lotte een auto?', answer: 'Nee' },
      { nl: 'Spreekt de oude man Engels?', answer: 'Nee' },
    ],
  },
  {
    type: 'drill', title: 'Answer in a full sentence', grammar: ['question-word', 'wie-hoe', 'modals', 'infinitive-end', 'adjective-e'],
    task: 'Answer in full',
    instruction: 'Answer each question about the story with a complete sentence. Use the name or its pronoun — both are accepted.',
    items: [
      { nl: 'Wat heeft de oude man?', answer: 'De oude man heeft een grote, oude tas.', accept: ['Hij heeft een grote, oude tas.', 'De oude man heeft een grote tas.', 'Hij heeft een grote tas.', 'De oude man heeft een oude tas.', 'Hij heeft een oude tas.'] },
      { nl: 'Wie helpt de oude man?', answer: 'Bram helpt de oude man.' },
      { nl: 'Kan de oude man goed lopen?', answer: 'Nee, de oude man kan niet goed lopen.', accept: ['Nee, hij kan niet goed lopen.'] },
      { nl: 'Gaat Bram vandaag werken of zwemmen?', answer: 'Vandaag gaat Bram zwemmen.', accept: ['Bram gaat vandaag zwemmen.', 'Vandaag gaat hij zwemmen.', 'Hij gaat vandaag zwemmen.', 'Bram gaat zwemmen.', 'Hij gaat zwemmen.'] },
      { nl: 'Waar moet Lotte werken?', answer: 'Lotte moet thuis werken.', accept: ['Zij moet thuis werken.'] },
      { nl: 'Moet Lotte naar de winkel of naar het park gaan?', answer: 'Lotte moet naar de winkel gaan.', accept: ['Zij moet naar de winkel gaan.'] },
      { nl: 'Kan Lotte rijden?', answer: 'Nee, Lotte kan niet rijden.', accept: ['Nee, zij kan niet rijden.'] },
      { nl: 'Wie kan goed rijden?', answer: 'Bram kan goed rijden.', accept: ['Bram kan heel goed rijden.', 'Bram rijdt heel goed.', 'Bram rijdt goed.'] },
      { nl: 'Hoe spreekt Lotte Engels?', answer: 'Lotte spreekt heel goed Engels.', accept: ['Zij spreekt heel goed Engels.', 'Lotte spreekt Engels heel goed.', 'Zij spreekt Engels heel goed.'] },
      { nl: 'Wat wil de oude man leren?', answer: 'De oude man wil Engels leren.', accept: ['Hij wil Engels leren.', 'De oude man wil graag Engels leren.', 'Hij wil graag Engels leren.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['modals', 'infinitive-end', 'dt-rule', 'v2-inversion'],
    instruction: 'Listen to each sentence and write it. You hear the same sound at the end of rijd and rijdt — the grammar tells you which to write.',
    items: [
      { listen: 'Ik spreek een beetje Nederlands.' },
      { listen: 'Bram kan heel goed zwemmen.' },
      { listen: 'Rijd jij morgen naar Gent?' },
      { listen: 'Hij rijdt met de auto naar Antwerpen.' },
      { listen: 'Morgen moet ik in Brussel werken.' },
      { listen: 'Wil jij koffie of thee?' },
      { listen: 'Mag ik hier zitten?' },
      { listen: 'Wij willen de oude man helpen.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['modals', 'infinitive-end', 'dt-rule', 'v2-inversion', 'time-place', 'question-word', 'possessives', 'geen-niet'],
    instruction: 'Translate. Modal second, infinitive last; d + t where lopen would have a t. For “can you”, write Kan jij.',
    items: [
      { en: 'I speak a bit of Dutch.', answer: 'Ik spreek een beetje Nederlands.' },
      { en: 'Lotte speaks English very well.', answer: 'Lotte spreekt heel goed Engels.', accept: ['Lotte spreekt Engels heel goed.'] },
      { en: 'Can you swim? (one person)', answer: 'Kan jij zwemmen?' },
      { en: 'He is driving to Ghent.', answer: 'Hij rijdt naar Gent.' },
      { en: 'Are you driving to Antwerp? (one person)', answer: 'Rijd jij naar Antwerpen?' },
      { en: 'I drive very well.', answer: 'Ik rijd heel goed.' },
      { en: 'Tomorrow I have to work in Brussels.', answer: 'Morgen moet ik in Brussel werken.' },
      { en: 'We want to go to the park today.', answer: 'Wij willen vandaag naar het park gaan.', accept: ['Vandaag willen wij naar het park gaan.'] },
      { en: 'The child is not allowed to play in the street.', answer: 'Het kind mag niet op straat spelen.', accept: ['Het kind mag niet in de straat spelen.'] },
      { en: 'Bram wants to help his father.', answer: 'Bram wil zijn vader helpen.' },
      { en: 'My sister can’t drive.', answer: 'Mijn zus kan niet rijden.' },
      { en: 'Does he want coffee or tea?', answer: 'Wil hij koffie of thee?' },
      { en: 'Where do you want to live? (one person)', answer: 'Waar wil jij wonen?' },
      { en: 'Tomorrow you have to cook. (one person, start with “tomorrow”)', answer: 'Morgen moet jij koken.' },
      { en: 'The old man doesn’t speak English.', answer: 'De oude man spreekt geen Engels.' },
      { en: 'I want to learn Dutch.', answer: 'Ik wil Nederlands leren.' },
    ],
    explanation: '“op straat spelen” — playing out in the street — has no article; “in de straat” is also correct.',
  },
  {
    type: 'arrange', title: 'Can’t drive, but …', grammar: ['modals', 'infinitive-end', 'niet', 'geen-niet'],
    instruction: 'Build: “Lotte can’t drive, but she speaks English very well.” Two tiles are traps.',
    nl: 'Lotte kan niet rijden, maar zij spreekt heel goed Engels.', en: 'Lotte can’t drive, but she speaks English very well.', image: 'woman-bike', distractors: ['geen', 'kunt'],
  },
  {
    type: 'arrange', title: 'd + t in a question', grammar: ['dt-rule', 'inversion', 'time-place'],
    instruction: 'Build: “Are you driving to Ghent by car tomorrow?” When, how, where — and watch the verb form.',
    nl: 'Rijd jij morgen met de auto naar Gent?', en: 'Are you driving to Ghent by car tomorrow?', image: 'man-driving', distractors: ['rijdt', 'het'],
  },
  {
    type: 'drill', title: 'The whole lesson in one round', grammar: ['modals', 'infinitive-end', 'dt-rule', 'de-het', 'er-is-zijn', 'adjective-e', 'plural', 'numbers', 'possessives', 'geen-niet', 'v2-inversion', 'yes-no-question', 'question-word', 'present-regular', 'spelling-stem'],
    instruction: 'A final, demanding round: this lesson and everything before it, mixed. Type every answer.',
    items: [
      { nl: '___ keuken', cue: 'de / het', answer: 'de' },
      { nl: '___ jaar', cue: 'de / het', answer: 'het' },
      { nl: 'Hij ___ naar Gent.', cue: 'rijden', answer: 'rijdt' },
      { nl: '___ jij met de fiets?', cue: 'rijden', answer: 'Rijd' },
      { nl: 'Bram ___ koffie drinken.', cue: 'willen', answer: 'wil' },
      { nl: 'Jij ___ goed zwemmen.', cue: 'kunnen', answer: 'kunt', accept: ['kan'] },
      { nl: 'Lotte ___ heel goed Engels.', cue: 'spreken', answer: 'spreekt' },
      { nl: 'Er ___ vier stoelen in de keuken.', cue: 'is / zijn', answer: 'zijn' },
      { nl: 'Dit is een ___ vriendin.', cue: 'goed', answer: 'goede' },
      { nl: 'Ik zwem.', task: 'Add “kunnen” and make it negative', answer: 'Ik kan niet zwemmen.' },
      { nl: 'Ik moet morgen werken.', task: 'Start with “morgen”', answer: 'Morgen moet ik werken.' },
      { nl: 'Jij wilt thee.', task: 'Make it a question', answer: 'Wil jij thee?' },
      { nl: 'Wij drinken koffie.', task: 'Add “willen” and make it negative', answer: 'Wij willen geen koffie drinken.' },
      { nl: 'Bram rijdt naar Gent.', task: 'Change Bram to ik', answer: 'Ik rijd naar Gent.' },
      { en: 'The old man has two cats.', answer: 'De oude man heeft twee katten.' },
      { en: 'Today Bram has to help his mother. (start with “today”)', answer: 'Vandaag moet Bram zijn moeder helpen.' },
      { en: 'May we play in the garden?', answer: 'Mogen wij in de tuin spelen?' },
      { en: 'Our house has three rooms.', answer: 'Ons huis heeft drie kamers.' },
      { listen: 'Lotte kan niet rijden, maar zij spreekt heel goed Engels en Nederlands.' },
    ],
  },
  {
    type: 'complete', title: 'Lesson 9: done',
    instruction: 'Four modal verbs, the frame they build with the infinitive at the end, and the d + t of rijden — with every verb you know. Je kunt nu een beetje Nederlands.',
  },
];
