/**
 * Lesson 12 — Ik ga niet, omdat het regent.
 * Targets: omdat, want, als, denken, weten, hopen, begrijpen, vragen, regenen, examen.
 * Structure: dat, wanneer, misschien.
 * Grammar: want vs omdat · the verb at the end · dat-clauses · als + inversion.
 * The capstone of volume one: every verb, plural, possessive, modal, clock time and
 * perfect of lessons 1–11 returns here inside the new subordinate clauses.
 * Teaching choice: in a subordinate clause the course writes the Flemish order
 * “gewerkt heeft” (participle, then the conjugated verb) and “moet werken”
 * (modal, then infinitive); the other orders are correct and always accepted.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Rain, an exam, and “because”', grammar: ['want-omdat', 'verb-final', 'days-op-om'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice. In the sentences with omdat, dat and als, watch where the verb ends up.',
    cards: [
      { nl: 'Het regent in Leuven.', en: 'It is raining in Leuven.', image: 'rain' },
      { nl: 'Lotte heeft vrijdag een examen.', en: 'Lotte has an exam on Friday.', image: 'exam' },
      { nl: 'Lotte leert elke dag, want het examen is vrijdag.', en: 'Lotte studies every day, because the exam is on Friday.', image: 'woman-studying' },
      { nl: 'Lotte gaat niet naar het park, omdat het regent.', en: 'Lotte is not going to the park, because it is raining.', image: 'rain' },
      { nl: 'Lotte hoopt dat het examen goed gaat.', en: 'Lotte hopes that the exam goes well.', image: 'woman-studying' },
      { nl: 'Bram denkt dat het examen goed gaat.', en: 'Bram thinks that the exam will go well.', image: 'man-thinking' },
      { nl: 'Bram vraagt: “Wanneer is het examen?”', en: 'Bram asks: “When is the exam?”', image: 'couple-talking' },
      { nl: 'Als het regent, gaan wij niet naar het park.', en: 'If it rains, we are not going to the park.', image: 'park' },
      { nl: 'Misschien regent het morgen ook.', en: 'Maybe it will rain tomorrow too.', image: 'rain' },
    ],
    note: '“want” and “omdat” both mean “because”; “als” = if / when; “dat” = that; “misschien” = maybe; “wanneer?” = when? New verbs: denken (to think), weten (to know a fact), hopen (to hope), begrijpen (to understand), vragen (to ask), regenen (to rain — only “het regent”). “het examen” is a het-word; plural “de examens”. For one particular coming Friday Dutch usually just says “vrijdag”; “op vrijdag” is also correct.',
  },
  {
    type: 'observe', title: 'Short answers with “het”', grammar: ['dat-clause', 'present-regular', 'inversion'],
    instruction: 'Little conversations. Listen to the answers: English says “I think so” or “I don’t know”; Dutch always puts “het” in.',
    cards: [
      { nl: 'Weet jij waar Max is? — Nee, ik weet het niet.', en: 'Do you know where Max is? — No, I don’t know.', image: 'dog-big' },
      { nl: 'Denk jij dat het morgen regent? — Ja, ik denk het.', en: 'Do you think it will rain tomorrow? — Yes, I think so.', image: 'rain' },
      { nl: 'Regent het zaterdag ook? — Ik hoop het niet!', en: 'Will it rain on Saturday too? — I hope not!', image: 'rain' },
      { nl: 'Begrijp jij het boek? — Ja, nu begrijp ik het.', en: 'Do you understand the book? — Yes, now I understand it.', image: 'book' },
      { nl: 'Wat vraagt Noor? — Zij vraagt hoe laat het is.', en: 'What is Noor asking? — She is asking what time it is.', image: 'clock' },
      { nl: 'Wanneer is het examen? — Vrijdag, om negen uur.', en: 'When is the exam? — Friday, at nine o’clock.', image: 'calendar' },
      { nl: 'Weet jij hoe oud Noor is? — Ik denk dat zij vijf jaar is.', en: 'Do you know how old Noor is? — I think she is five.', image: 'child' },
      { nl: 'Hoe heet de jonge vrouw in onze straat? — Ik weet haar naam niet.', en: 'What is the young woman in our street called? — I don’t know her name.', image: 'woman-walking' },
      { nl: 'Gaat het examen goed? — Ik hoop het!', en: 'Will the exam go well? — I hope so!', image: 'exam' },
    ],
    note: 'Ik weet het (niet). Ik denk het (niet). Ik hoop het (niet). Ik begrijp het (niet). Without “het” these sound broken in Dutch. weten = to know a fact; it has no -t in “hij weet”, because the stem already ends in t.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['present-regular'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Het regent al drie dagen in Leuven.', en: 'It has been raining in Leuven for three days.', answer: 'rain',
    choices: [{ image: 'tree', nl: 'een grote boom' }, { image: 'rain', nl: 'Het regent.' }, { image: 'window', nl: 'een klein raam' }, { image: 'door', nl: 'de deur' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['want-omdat'],
    instruction: 'Listen without reading. What is Lotte doing?',
    nl: 'Lotte leert thuis, want zij heeft vrijdag een examen.', en: 'Lotte is studying at home, because she has an exam on Friday.', answer: 'woman-studying',
    choices: [{ image: 'woman-reading', nl: 'Lotte leest in het park.' }, { image: 'woman-studying', nl: 'Lotte leert.' }, { image: 'woman-bike', nl: 'Lotte en haar fiets' }, { image: 'woman-sick', nl: 'Lotte is ziek.' }],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['present-regular'],
    instruction: 'Listen. Which picture is it?',
    nl: 'Bram denkt: “Waar is mijn sleutel?”', en: 'Bram is thinking: “Where is my key?”', answer: 'man-thinking',
    choices: [{ image: 'man-writing', nl: 'Bram schrijft.' }, { image: 'man-thinking', nl: 'Bram denkt.' }, { image: 'man-sleeping', nl: 'Bram slaapt.' }, { image: 'man-eating', nl: 'Bram eet.' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['de-het', 'plural'],
    instruction: 'Type the Dutch. Nouns with their article.',
    items: [
      { image: 'exam', answer: 'het examen' },
      { en: 'the exams', answer: 'de examens' },
      { en: 'to think', answer: 'denken' },
      { en: 'to know (a fact)', answer: 'weten' },
      { en: 'to hope', answer: 'hopen' },
      { en: 'to understand', answer: 'begrijpen' },
      { en: 'to ask', answer: 'vragen' },
      { image: 'rain', en: 'it is raining', answer: 'het regent' },
      { en: 'maybe', answer: 'misschien' },
      { en: 'when? (question word)', answer: 'wanneer' },
      { en: 'because (the verb goes to the end)', answer: 'omdat' },
      { en: 'because (normal word order)', answer: 'want' },
    ],
    explanation: 'het examen, de examens — like het boek, de boeken: every plural takes de. Two words for “because”: omdat and want. The next pages show why.',
  },
  {
    type: 'drill', title: 'Hear and spell',
    instruction: 'Play each one and type it. “ij” in begrijpen is the “ei” of trein; the “g” of vragen is the soft Flemish g.',
    items: [
      { listen: 'begrijpen' },
      { listen: 'misschien' },
      { listen: 'examen' },
      { listen: 'wanneer' },
      { listen: 'Het regent.' },
      { listen: 'Ik weet het niet.' },
      { listen: 'Ik hoop het.' },
      { listen: 'Begrijp jij het?' },
    ],
    explanation: 'misschien is said mis-SCHIEN: s, then the Dutch “ch”, then “ien”. examen has the stress in the middle: ek-SAA-men. wanneer: wa-NEER.',
  },

  // ——— Grammar: six new verbs ———
  {
    part: 'Grammar', type: 'grammar', title: 'Six new verbs', grammar: ['present-regular', 'spelling-stem', 'participle', 'inversion'],
    body: [
      '**denken** (to think), **weten** (to know), **hopen** (to hope), **begrijpen** (to understand) and **vragen** (to ask) follow the present-tense pattern you have used since lesson 3: **ik** + stem, **jij / hij / zij** + stem + **t**, **wij / jullie / zij** (they) = the infinitive. In a question jij takes the bare stem: ***Denk** jij …? **Begrijp** jij …? **Vraag** jij …?*',
      'The stem follows the spelling rules of lesson 3. *ho-pen*: the o is long at the open end of the syllable; close it and it needs two letters — **ik hoop**, **hij hoopt**. The same for *vra-gen* → **ik vraag**. *be-grij-pen* → **ik begrijp**: *ij* is one sound and never doubles. *den-ken* → **ik denk**.',
      '**weten** is the trap. Its stem, **weet**, already ends in -t, so no second t is added: *jij weet, hij weet, zij weet* — just like *praten → hij praat* and *eten → hij eet*. In the question nothing changes either: ***Weet** jij waar Max is?* weten is to know a **fact**; knowing a person is a different verb, for later.',
      '**regenen** (to rain) has only one subject: **het**. *Het regent. Regent het? Het regent niet.* With **al** and a time, the present means “has been … for”: *Het regent al drie dagen* — it has been raining for three days.',
      'Four of these verbs need **het** in a short answer, where English says “so” or nothing: *Ik weet het. Ik weet het niet. Ik denk het. Ik hoop het niet. Ik begrijp het.* Never *Ik weet niet.* on its own.',
      'The participles, for the perfect: **gedacht** is irregular (like *gekocht*); **gehoopt** takes -t (p is in ’t kofschip); **gevraagd** and **geregend** take -d; **geweten** is strong. **begrepen** has no extra ge-: verbs that start with *be-* never take one. *Ik heb het niet begrepen.*',
    ],
    tables: [
      { caption: 'denken · weten', rows: [
        { nl: 'ik denk · ik weet', en: 'I think · I know' },
        { nl: 'jij denk[t] · jij weet', en: 'you think · you know — weet has no extra t' },
        { nl: 'hij denk[t] · hij weet', en: 'he thinks · he knows' },
        { nl: 'wij denk[en] · wij wet[en]', en: 'we think · we know' },
        { nl: 'denk jij? · weet jij?', en: 'do you think? · do you know?' },
      ] },
      { caption: 'hopen · begrijpen · vragen', rows: [
        { nl: 'ik hoop · ik begrijp · ik vraag', en: 'I hope · I understand · I ask' },
        { nl: 'zij hoop[t] · zij begrijp[t] · zij vraag[t]', en: 'she hopes · understands · asks' },
        { nl: 'jullie hop[en] · jullie begrijp[en] · jullie vrag[en]', en: 'you (plural) hope · understand · ask' },
        { nl: 'het regen[t]', en: 'it is raining' },
      ] },
      { caption: 'Participles', rows: [
        { nl: 'Ik heb het [gedacht].', en: 'I thought so.' },
        { nl: 'Ik heb het altijd [geweten].', en: 'I have always known it.' },
        { nl: 'Wij hebben het [gehoopt].', en: 'We hoped so.' },
        { nl: 'Ik heb het niet [begrepen].', en: 'I did not understand it.' },
        { nl: 'Bram heeft het [gevraagd].', en: 'Bram asked.' },
        { nl: 'Het heeft gisteren [geregend].', en: 'It rained yesterday.' },
      ] },
    ],
    examples: [
      { nl: 'Weet jij waar het station is?', en: 'Do you know where the station is?' },
      { nl: 'Nee, ik weet het niet.', en: 'No, I don’t know.' },
      { nl: 'Begrijp jij het nu?', en: 'Do you understand it now?' },
      { nl: 'Lotte hoopt het.', en: 'Lotte hopes so.' },
      { nl: 'Het regent al drie dagen.', en: 'It has been raining for three days.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate denken', grammar: ['present-regular', 'subject-pronouns'],
    instruction: 'Type the form of denken for every person. Say “ik denk, jij denkt …” out loud.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'denk' },
      { label: 'jij', gloss: 'you', answer: 'denkt' },
      { label: 'hij', gloss: 'he', answer: 'denkt' },
      { label: 'zij', gloss: 'she', answer: 'denkt' },
      { label: 'wij', gloss: 'we', answer: 'denken' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'denken' },
      { label: 'zij', gloss: 'they', answer: 'denken' },
      { label: 'Bram en Lotte', gloss: 'they', answer: 'denken' },
    ],
    explanation: 'Completely regular: denk, denkt, denken. Only the participle is irregular: gedacht.',
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate weten', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'Type the form of weten. Think of praten before you write jij and hij.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'weet' },
      { label: 'jij', gloss: 'you', answer: 'weet' },
      { label: 'hij', gloss: 'he', answer: 'weet' },
      { label: 'zij', gloss: 'she', answer: 'weet' },
      { label: 'wij', gloss: 'we', answer: 'weten' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'weten' },
      { label: 'zij', gloss: 'they', answer: 'weten' },
      { label: 'Lotte', gloss: 'she', answer: 'weet' },
    ],
    explanation: 'weet, weet, weet — then weten. Never “weett”. The plural has one e: we-ten, an open syllable, like praten.',
  },
  {
    type: 'drill', layout: 'table', title: 'hopen, begrijpen, vragen, regenen', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'Mixed persons. The small word under each person is the verb to use. Type the form.',
    items: [
      { label: 'ik', gloss: 'hopen', answer: 'hoop' },
      { label: 'jij', gloss: 'hopen', answer: 'hoopt' },
      { label: 'zij', gloss: 'they · hopen', answer: 'hopen' },
      { label: 'ik', gloss: 'begrijpen', answer: 'begrijp' },
      { label: 'hij', gloss: 'begrijpen', answer: 'begrijpt' },
      { label: 'jullie', gloss: 'begrijpen', answer: 'begrijpen' },
      { label: 'ik', gloss: 'vragen', answer: 'vraag' },
      { label: 'zij', gloss: 'she · vragen', answer: 'vraagt' },
      { label: 'wij', gloss: 'vragen', answer: 'vragen' },
      { label: 'het', gloss: 'regenen', answer: 'regent' },
    ],
    explanation: 'Double vowel in the stem (hoop, vraag), single vowel in the plural (hopen, vragen) — the rule of wonen and slapen. begrijp keeps its ij everywhere.',
  },
  {
    type: 'drill', title: 'Type the form', grammar: ['present-regular', 'inversion', 'v2-inversion', 'niet'],
    instruction: 'Type the missing form. The infinitive is the verb you need. Watch jij before and after the verb.',
    items: [
      { nl: 'Ik ___ het niet.', cue: 'weten', en: 'I don’t know.', answer: 'weet' },
      { nl: '___ jij waar Max is?', cue: 'weten', answer: 'Weet' },
      { nl: 'Lotte ___ het boek niet.', cue: 'begrijpen', answer: 'begrijpt' },
      { nl: '___ jij het?', cue: 'begrijpen', answer: 'Begrijp' },
      { nl: 'Het ___ al drie dagen.', cue: 'regenen', en: 'It has been raining for three days.', answer: 'regent' },
      { nl: 'Bram ___ het ook.', cue: 'denken', en: 'Bram thinks so too.', answer: 'denkt' },
      { nl: 'Wat ___ jij, Lotte?', cue: 'denken', en: 'What do you think, Lotte?', answer: 'denk' },
      { nl: 'Noor ___: “Waar is Max?”', cue: 'vragen', answer: 'vraagt' },
      { nl: 'Nu ___ ik het!', cue: 'begrijpen', en: 'Now I understand!', answer: 'begrijp' },
      { nl: 'Lotte ___ het niet.', cue: 'hopen', en: 'Lotte hopes not.', answer: 'hoopt' },
    ],
    explanation: 'weet never gets a second t. After “nu” the verb stays second and the subject moves behind it: Nu begrijp ik het.',
  },
  {
    type: 'drill', title: 'Question, negative, other person', grammar: ['yes-no-question', 'inversion', 'niet', 'present-regular', 'v2-inversion'],
    instruction: 'Rewrite each sentence as the task says. Everything else stays the same.',
    items: [
      { nl: 'Ik weet het.', task: 'Make it negative', answer: 'Ik weet het niet.' },
      { nl: 'Jij begrijpt het.', task: 'Make it a question', answer: 'Begrijp jij het?' },
      { nl: 'Ik hoop het.', task: 'Change ik to Lotte', answer: 'Lotte hoopt het.' },
      { nl: 'Hij weet het niet.', task: 'Change hij to wij', answer: 'Wij weten het niet.' },
      { nl: 'Bram vraagt: “Hoe laat is het?”', task: 'Change Bram to ik', answer: 'Ik vraag: “Hoe laat is het?”' },
      { nl: 'Het regent vandaag.', task: 'Make it negative', answer: 'Het regent vandaag niet.' },
      { nl: 'Jij begrijpt het boek.', task: 'Start with “nu”', answer: 'Nu begrijp jij het boek.' },
      { nl: 'Lotte begrijpt het boek.', task: 'Make it negative', answer: 'Lotte begrijpt het boek niet.' },
    ],
    explanation: '“niet” goes to the end when the sentence ends in a definite object: Lotte begrijpt het boek niet. Nu begrijp jij — jij behind the verb loses its t, in a statement as in a question.',
  },
  {
    type: 'drill', title: 'The perfect: participles old and new', grammar: ['participle', 'perfect-hebben', 'perfect-zijn'],
    instruction: 'Type the participle of the verb given. Two of these take zijn, not hebben — the helper verb is already there.',
    items: [
      { nl: 'Het heeft gisteren veel ___.', cue: 'regenen', en: 'It rained a lot yesterday.', answer: 'geregend' },
      { nl: 'Bram heeft het ___.', cue: 'vragen', en: 'Bram asked.', answer: 'gevraagd' },
      { nl: 'Ik heb het boek niet ___.', cue: 'begrijpen', answer: 'begrepen' },
      { nl: 'Dat heb ik ___.', cue: 'denken', en: 'I thought so.', answer: 'gedacht' },
      { nl: 'Ik heb het altijd ___.', cue: 'weten', en: 'I have always known it.', answer: 'geweten' },
      { nl: 'Dat hebben wij ___.', cue: 'hopen', en: 'That is what we hoped.', answer: 'gehoopt' },
      { nl: 'Lotte heeft gisteren veel ___.', cue: 'leren', en: 'Lotte studied a lot yesterday.', answer: 'geleerd' },
      { nl: 'Wij zijn zaterdag naar de film ___.', cue: 'gaan', answer: 'gegaan' },
      { nl: 'Emma is vorig weekend naar Leuven ___.', cue: 'komen', answer: 'gekomen' },
    ],
    explanation: 'gedacht and gekocht: irregular, learn them as they are. begrepen: no ge- after be-. gehoopt with t (p is in ’t kofschip); gevraagd, geregend, geleerd with d. gaan and komen are movement: zijn gegaan, is gekomen.',
  },

  // ——— Grammar: want or omdat ———
  {
    type: 'grammar', title: 'want or omdat?', grammar: ['want-omdat', 'verb-final', 'v2-inversion'],
    body: [
      'English has one “because”. Dutch has two, **want** and **omdat**. They mean the same thing, but they build different sentences — and choosing the word means choosing the word order.',
      '**want** is a linking word like *en*, *maar* and *of*. It takes no slot, and what follows is an ordinary main clause, with the verb second: *Ik ga niet, **want** het **regent**.* If the clause after want starts with a time, the verb-second rule works inside it as always: *…, want morgen **heeft** Lotte een examen.*',
      '**omdat** opens a **subordinate clause** (Dutch: *bijzin*) — a clause that cannot stand on its own. In a subordinate clause the subject comes straight after omdat, and the **conjugated verb goes to the very end**: *Ik ga niet, **omdat** het **regent**. …, omdat Lotte morgen een examen **heeft**.*',
      'Everything between the subject and the verb keeps the order you know: time before place, niet in its place, graag and nooit after the subject. Only the verb has left: *Bram werkt vandaag niet in Brussel* → *omdat Bram vandaag niet in Brussel **werkt***.',
      'There is **no inversion** in a subordinate clause. The subject always stands right after omdat — never *omdat morgen heeft zij*. And because jij now stands **before** its verb, jij keeps its -t: *omdat jij morgen **werkt***, *omdat jij moe **bent***.',
      'Which one should you use? In speech, want is very common; in writing — and at a Belgian university — omdat is everywhere, because it can also start the sentence (see the als page). Dutch puts a comma before both; answers never check commas.',
    ],
    tables: [
      { caption: 'want — main clause, verb second', rows: [
        { nl: 'Ik ga niet, want het [regent].', en: 'I am not going, because it is raining.' },
        { nl: 'Lotte is thuis, want zij [heeft] vrijdag een examen.', en: 'Lotte is at home, because she has an exam on Friday.' },
        { nl: 'Lotte is thuis, want vrijdag [heeft] zij een examen.', en: 'the same — vrijdag first, verb second' },
      ] },
      { caption: 'omdat — subordinate clause, verb at the end', rows: [
        { nl: 'Ik ga niet, omdat het [regent].', en: 'I am not going, because it is raining.' },
        { nl: 'Lotte is thuis, omdat zij vrijdag een examen [heeft].', en: 'Lotte is at home, because she has an exam on Friday.' },
        { nl: 'Bram is moe, omdat hij vandaag in Brussel [werkt].', en: 'Bram is tired, because he is working in Brussels today.' },
        { nl: 'Ik ben blij, omdat jij morgen [komt].', en: 'I am happy, because you are coming tomorrow — jij keeps its t.' },
      ] },
    ],
    examples: [
      { nl: 'Wij gaan niet naar het park, want het regent.', en: 'We are not going to the park, because it is raining.' },
      { nl: 'Wij gaan niet naar het park, omdat het regent.', en: 'The same, with omdat.' },
      { nl: 'Lotte drinkt thee, want zij drinkt nooit koffie.', en: 'Lotte drinks tea, because she never drinks coffee.' },
      { nl: 'Lotte drinkt thee, omdat zij nooit koffie drinkt.', en: 'The same, with omdat.' },
    ],
  },
  {
    type: 'drill', title: 'want or omdat? The order decides', grammar: ['want-omdat', 'verb-final'], choices: ['want', 'omdat'],
    instruction: 'Only one of the two fits the word order after the gap. Look where the verb is.',
    items: [
      { nl: 'Ik ga niet naar het park, ___ het regent vandaag.', answer: 'want' },
      { nl: 'Ik ga niet naar het park, ___ het vandaag regent.', answer: 'omdat' },
      { nl: 'Lotte is thuis, ___ zij vrijdag een examen heeft.', answer: 'omdat' },
      { nl: 'Lotte is thuis, ___ zij heeft vrijdag een examen.', answer: 'want' },
      { nl: 'Bram is moe, ___ hij werkt vandaag in Brussel.', answer: 'want' },
      { nl: 'Bram is moe, ___ hij vandaag in Brussel werkt.', answer: 'omdat' },
      { nl: 'Lotte drinkt thee, ___ zij drinkt nooit koffie.', answer: 'want' },
      { nl: 'Lotte drinkt thee, ___ zij nooit koffie drinkt.', answer: 'omdat' },
    ],
    explanation: 'Verb at the end → omdat. Verb second (after the subject, or after a time word like morgen) → want.',
  },
  {
    type: 'drill', title: 'The verb at the end', grammar: ['verb-final', 'want-omdat', 'present-regular', 'hebben', 'zijn', 'dt-rule'],
    instruction: 'Type the missing verb form. It stands at the end of the omdat-clause — and a jij before it keeps its -t.',
    items: [
      { nl: 'Wij gaan niet naar het park, omdat het ___.', cue: 'regenen', answer: 'regent' },
      { nl: 'Lotte is thuis, omdat zij vrijdag een examen ___.', cue: 'hebben', answer: 'heeft' },
      { nl: 'Bram is moe, omdat hij vandaag in Brussel ___.', cue: 'werken', answer: 'werkt' },
      { nl: 'Lotte gaat met de fiets, omdat zij niet ___ rijden.', cue: 'kunnen', answer: 'kan' },
      { nl: 'Max is blij, omdat hij naar het park ___.', cue: 'gaan', answer: 'gaat' },
      { nl: 'Ik begrijp het niet, omdat ik nog niet goed Nederlands ___.', cue: 'spreken', answer: 'spreek' },
      { nl: 'Lotte is blij, omdat jij het ___.', cue: 'begrijpen', answer: 'begrijpt' },
      { nl: 'Bram gaat naar de winkel, omdat wij geen brood ___.', cue: 'hebben', answer: 'hebben' },
      { nl: 'Jij gaat niet naar de film, omdat jij morgen een examen ___.', cue: 'hebben', answer: 'hebt' },
      { nl: 'Bram koopt brood, omdat hij graag brood met kaas ___.', cue: 'eten', answer: 'eet' },
    ],
    explanation: 'omdat jij … hebt, omdat jij … begrijpt: jij stands before the verb, so the -t stays. Everything else keeps its place — niet, nooit, graag, the time — only the verb has moved to the end.',
  },
  {
    type: 'drill', title: 'Join with omdat', grammar: ['want-omdat', 'verb-final', 'time-place', 'adverb-position', 'geen-niet', 'geen'],
    task: 'Join with omdat',
    instruction: 'Make one sentence: the second sentence becomes the omdat-clause. Its verb goes to the end; nothing else moves.',
    items: [
      { nl: 'Lotte gaat niet naar het park. Het regent.', answer: 'Lotte gaat niet naar het park, omdat het regent.' },
      { nl: 'Bram is moe. Hij werkt vandaag in Brussel.', answer: 'Bram is moe, omdat hij vandaag in Brussel werkt.' },
      { nl: 'Lotte leert elke dag. Zij heeft vrijdag een examen.', answer: 'Lotte leert elke dag, omdat zij vrijdag een examen heeft.', accept: ['Lotte leert elke dag, omdat zij op vrijdag een examen heeft.'] },
      { nl: 'Wij gaan naar de winkel. Wij hebben geen brood en geen kaas.', answer: 'Wij gaan naar de winkel, omdat wij geen brood en geen kaas hebben.' },
      { nl: 'Het kind gaat vandaag niet naar school. Het is ziek.', answer: 'Het kind gaat vandaag niet naar school, omdat het ziek is.' },
      { nl: 'Ik ben blij. Jij komt morgen.', answer: 'Ik ben blij, omdat jij morgen komt.' },
      { nl: 'Noor speelt graag met Max. Hij is een lieve hond.', answer: 'Noor speelt graag met Max, omdat hij een lieve hond is.' },
      { nl: 'Bram gaat met de trein. Hij heeft geen auto.', answer: 'Bram gaat met de trein, omdat hij geen auto heeft.' },
      { nl: 'Jij bent moe. Jij slaapt niet goed.', answer: 'Jij bent moe, omdat jij niet goed slaapt.' },
    ],
    explanation: 'The only change is the verb: it leaves its second place and goes to the end. jij komt stays jij komt — no inversion, so no lost t.',
  },
  {
    type: 'drill', title: 'want keeps the order — omdat does not', grammar: ['want-omdat', 'verb-final', 'v2-inversion', 'inversion'],
    instruction: 'Rewrite as the task says. With want, the second half is a normal main clause. With omdat, a time word goes back behind the subject — and jij gets its t back.',
    items: [
      { nl: 'Lotte is thuis. Vrijdag heeft zij een examen.', task: 'Join with want', answer: 'Lotte is thuis, want vrijdag heeft zij een examen.' },
      { nl: 'Jij moet leren. Morgen heb jij een examen.', task: 'Join with want', answer: 'Jij moet leren, want morgen heb jij een examen.' },
      { nl: 'Lotte gaat met de fiets. Zij kan niet rijden.', task: 'Join with want', answer: 'Lotte gaat met de fiets, want zij kan niet rijden.' },
      { nl: 'Ik ga niet, want het regent vandaag.', task: 'Replace want with omdat', answer: 'Ik ga niet, omdat het vandaag regent.' },
      { nl: 'Lotte is thuis, want vrijdag heeft zij een examen.', task: 'Replace want with omdat', answer: 'Lotte is thuis, omdat zij vrijdag een examen heeft.' },
      { nl: 'Wij gaan niet, want morgen werkt Bram.', task: 'Replace want with omdat', answer: 'Wij gaan niet, omdat Bram morgen werkt.' },
      { nl: 'Bram koopt brood, want thuis hebben wij geen brood.', task: 'Replace want with omdat', answer: 'Bram koopt brood, omdat wij thuis geen brood hebben.' },
      { nl: 'Ik ben blij, want morgen kom jij.', task: 'Replace want with omdat', answer: 'Ik ben blij, omdat jij morgen komt.' },
    ],
    explanation: 'want vrijdag heeft zij → omdat zij vrijdag … heeft. want morgen kom jij → omdat jij morgen komt. In an omdat-clause the subject is always first, and the verb always last.',
  },
  {
    type: 'arrange', title: 'Because of the exam', grammar: ['want-omdat', 'verb-final', 'hebben'],
    instruction: 'Build: “Lotte is not going to the park, because she has an exam on Friday.” Two tiles are traps.',
    nl: 'Lotte gaat niet naar het park, omdat zij vrijdag een examen heeft.', en: 'Lotte is not going to the park, because she has an exam on Friday.', image: 'woman-studying', distractors: ['heb', 'geen'],
  },

  // ——— Grammar: two verbs at the end ———
  {
    type: 'grammar', title: 'Two verbs at the end', grammar: ['verb-final', 'modals', 'infinitive-end', 'perfect-hebben', 'perfect-zijn'],
    body: [
      'Since lesson 9 many of your sentences have two verbs: a conjugated one in second place and an infinitive or participle at the end. *Lotte **moet** vandaag **leren**. Bram **heeft** gisteren **gewerkt**.* In a subordinate clause the conjugated verb goes to the end as well — so the two verbs meet there, side by side.',
      '**A modal + infinitive:** the modal comes first, then the infinitive: *omdat Lotte vandaag **moet leren***; *Ik weet dat zij morgen **moet werken***. (*leren moet* also exists, mostly in Flanders, and is accepted — but *moet leren* is the safe, standard order.) The same for gaan + infinitive: *omdat wij **gaan eten***.',
      '**A perfect:** here Dutch really has two orders, and both are correct. *omdat ik gisteren **gewerkt heb*** follows the rule literally — the conjugated verb is last — and is the order you will hear most in Flanders. *omdat ik gisteren **heb gewerkt*** is equally correct and more common in the Netherlands. This course writes **gewerkt heb**, and every answer accepts both. The same with zijn: *omdat Bram naar Gent **gegaan is*** (or *is gegaan*).',
      'Nothing else changes. niet, geen, the time and the place stay exactly where they were in the main clause, in front of the verbs: *omdat Lotte vandaag niet naar het park **kan gaan***.',
      'Why does Dutch do this? The verb at the end is a signal: the clause is not finished until the verb arrives, and that tells the listener where the subordinate clause stops. In a long Dutch sentence you often wait for the verb — so listen to the end.',
    ],
    tables: [
      { caption: 'main clause → subordinate clause', rows: [
        { nl: 'Zij moet vandaag leren.', en: 'She has to study today.' },
        { nl: '… omdat zij vandaag [moet leren].', en: '… because she has to study today.' },
        { nl: 'Bram kan niet komen.', en: 'Bram cannot come.' },
        { nl: '… omdat Bram niet [kan komen].', en: '… because Bram cannot come.' },
        { nl: 'Hij heeft gisteren gewerkt.', en: 'He worked yesterday.' },
        { nl: '… omdat hij gisteren [gewerkt heeft].', en: '… because he worked yesterday. (also: heeft gewerkt)' },
        { nl: 'Wij zijn naar Gent gegaan.', en: 'We went to Ghent.' },
        { nl: '… omdat wij naar Gent [gegaan zijn].', en: '… because we went to Ghent. (also: zijn gegaan)' },
      ] },
    ],
    examples: [
      { nl: 'Lotte is thuis, omdat zij moet leren.', en: 'Lotte is at home, because she has to study.' },
      { nl: 'Ik weet dat zij morgen moet werken.', en: 'I know that she has to work tomorrow.' },
      { nl: 'Bram is moe, omdat hij gisteren veel gewerkt heeft.', en: 'Bram is tired, because he worked a lot yesterday.' },
      { nl: 'Bram is moe, omdat hij gisteren veel heeft gewerkt.', en: 'The same — the other correct order.' },
    ],
  },
  {
    type: 'drill', title: 'Join with omdat — two verbs', grammar: ['verb-final', 'want-omdat', 'modals', 'infinitive-end', 'perfect-hebben', 'perfect-zijn'],
    task: 'Join with omdat',
    instruction: 'Make one sentence with omdat. Both verbs go to the end: modal before infinitive, participle before hebben or zijn (the other order is accepted too).',
    items: [
      { nl: 'Lotte is thuis. Zij moet leren.', answer: 'Lotte is thuis, omdat zij moet leren.', accept: ['Lotte is thuis, omdat zij leren moet.'] },
      { nl: 'Bram gaat niet naar het park. Hij wil slapen.', answer: 'Bram gaat niet naar het park, omdat hij wil slapen.', accept: ['Bram gaat niet naar het park, omdat hij slapen wil.'] },
      { nl: 'Lotte gaat met de fiets. Zij kan niet rijden.', answer: 'Lotte gaat met de fiets, omdat zij niet kan rijden.', accept: ['Lotte gaat met de fiets, omdat zij niet rijden kan.'] },
      { nl: 'Ik ga niet naar de film. Ik moet morgen werken.', answer: 'Ik ga niet naar de film, omdat ik morgen moet werken.', accept: ['Ik ga niet naar de film, omdat ik morgen werken moet.'] },
      { nl: 'Het kind is blij. Het mag in de tuin spelen.', answer: 'Het kind is blij, omdat het in de tuin mag spelen.', accept: ['Het kind is blij, omdat het in de tuin spelen mag.'] },
      { nl: 'Bram is moe. Hij heeft gisteren veel gewerkt.', answer: 'Bram is moe, omdat hij gisteren veel gewerkt heeft.', accept: ['Bram is moe, omdat hij gisteren veel heeft gewerkt.'] },
      { nl: 'Lotte is blij. Zij heeft een nieuwe jas gekocht.', answer: 'Lotte is blij, omdat zij een nieuwe jas gekocht heeft.', accept: ['Lotte is blij, omdat zij een nieuwe jas heeft gekocht.'] },
      { nl: 'Bram eet niet. Hij heeft al gegeten.', answer: 'Bram eet niet, omdat hij al gegeten heeft.', accept: ['Bram eet niet, omdat hij al heeft gegeten.'] },
      { nl: 'Wij zijn moe. Wij zijn naar Gent gegaan.', answer: 'Wij zijn moe, omdat wij naar Gent gegaan zijn.', accept: ['Wij zijn moe, omdat wij naar Gent zijn gegaan.'] },
      { nl: 'Jij bent moe. Jij hebt niet goed geslapen.', answer: 'Jij bent moe, omdat jij niet goed geslapen hebt.', accept: ['Jij bent moe, omdat jij niet goed hebt geslapen.'] },
    ],
    explanation: 'moet leren, wil slapen, kan rijden, mag spelen — modal first. gewerkt heeft, gekocht heeft, gegaan zijn — participle first in this course, but heeft gewerkt is just as correct.',
  },
  {
    type: 'drill', title: 'jij: behind the verb, or before it?', grammar: ['verb-final', 'v2-inversion', 'inversion', 'hebben', 'zijn', 'gaan'],
    instruction: 'Pairs of sentences. In the main clause jij often stands behind the verb (no -t); in the omdat-clause jij always stands before it (-t stays).',
    items: [
      { nl: 'Morgen ___ jij naar Gent.', cue: 'gaan', answer: 'ga' },
      { nl: 'Ik ben blij, omdat jij morgen naar Gent ___.', cue: 'gaan', answer: 'gaat' },
      { nl: 'Vandaag ___ jij thuis.', cue: 'werken', answer: 'werk' },
      { nl: 'Max is blij, omdat jij vandaag thuis ___.', cue: 'werken', answer: 'werkt' },
      { nl: 'Nu ___ jij het.', cue: 'begrijpen', answer: 'begrijp' },
      { nl: 'Ik ben blij, omdat jij het nu ___.', cue: 'begrijpen', answer: 'begrijpt' },
      { nl: 'Thuis ___ jij een kat.', cue: 'hebben', answer: 'heb' },
      { nl: 'Noor komt graag, omdat jij thuis een kat ___.', cue: 'hebben', answer: 'hebt' },
      { nl: 'Vandaag ___ jij moe.', cue: 'zijn', answer: 'ben' },
      { nl: 'Jij slaapt, omdat jij moe ___.', cue: 'zijn', answer: 'bent' },
      { nl: 'Morgen ___ jij met de trein.', cue: 'komen', answer: 'kom' },
      { nl: 'Ik wacht op het station, omdat jij met de trein ___.', cue: 'komen', answer: 'komt' },
    ],
    explanation: 'ga jij / jij gaat, werk jij / jij werkt, heb jij / jij hebt, ben jij / jij bent: the question is only where jij stands. In a subordinate clause it is always before the verb.',
  },
  {
    type: 'arrange', title: 'Tired, and why', grammar: ['verb-final', 'perfect-hebben', 'want-omdat'],
    instruction: 'Build: “Bram is tired, because he worked a lot yesterday.” Two tiles are traps.',
    nl: 'Bram is moe, omdat hij gisteren veel gewerkt heeft.', en: 'Bram is tired, because he worked a lot yesterday.', image: 'man-tired', distractors: ['want', 'hebt'],
  },

  // ——— Grammar: dat ———
  {
    type: 'grammar', title: 'Ik denk dat …', grammar: ['dat-clause', 'verb-final', 'question-word'],
    body: [
      'To say what someone thinks, knows, hopes, says or sees, Dutch uses **dat** + a subordinate clause — so the verb goes to the end: *Ik denk **dat** Bram thuis **is**. Ik weet **dat** zij morgen **moet werken**. Lotte hoopt **dat** het examen goed **gaat**.*',
      'English can drop “that”: “I think Bram is at home”. Dutch **never** drops dat. *Ik denk Bram is thuis* is wrong.',
      'The verbs that take a dat-clause are the ones you would expect: **denken, weten, hopen, zeggen, zien, begrijpen**, and **vinden** for an opinion: *Ik vind dat jij heel goed Nederlands spreekt.*',
      'After *hopen* and *denken* Dutch uses the present for the future: *Ik hoop dat het morgen niet regent* — “I hope it will not rain tomorrow”.',
      '**Questions inside a sentence.** A question word can link clauses in the same way — and then its clause has the verb at the end too: *Waar is Max?* → *Ik weet niet **waar** Max **is**.* *Wanneer is het examen?* → *Bram vraagt **wanneer** het examen **is**.* *Hoe laat is het?* → *Weet jij **hoe laat** het **is**?* This is how you ask politely, and how you report what someone asked.',
      'When everyone already knows what you mean, **het** replaces the whole dat-clause: *Denk jij dat het regent? — Ik denk het.* Or **dat** at the front, as the first element, with the verb second: ***Dat** weet ik niet. **Dat** denk ik ook.* This is the pointing *dat* from *Wie is dat?* — the same word, a different job.',
    ],
    tables: [
      { caption: 'main clause → dat-clause', rows: [
        { nl: 'Bram is thuis.', en: 'Bram is at home.' },
        { nl: 'Ik denk dat Bram thuis [is].', en: 'I think (that) Bram is at home.' },
        { nl: 'Zij moet morgen werken.', en: 'She has to work tomorrow.' },
        { nl: 'Ik weet dat zij morgen [moet werken].', en: 'I know (that) she has to work tomorrow.' },
        { nl: 'Jouw examen gaat goed.', en: 'Your exam will go well.' },
        { nl: 'Ik denk dat jouw examen goed [gaat].', en: 'I think (that) your exam will go well.' },
      ] },
      { caption: 'question → question inside a sentence', rows: [
        { nl: 'Waar is Max?', en: 'Where is Max?' },
        { nl: 'Ik weet niet waar Max [is].', en: 'I don’t know where Max is.' },
        { nl: 'Wanneer is het examen?', en: 'When is the exam?' },
        { nl: 'Bram vraagt wanneer het examen [is].', en: 'Bram asks when the exam is.' },
      ] },
    ],
    examples: [
      { nl: 'Ik hoop dat het morgen niet regent.', en: 'I hope that it won’t rain tomorrow.' },
      { nl: 'Lotte zegt dat Bram brood gekocht heeft.', en: 'Lotte says that Bram has bought bread.' },
      { nl: 'Weet jij hoe laat het is?', en: 'Do you know what time it is?' },
      { nl: 'Dat weet ik niet.', en: 'I don’t know that.' },
    ],
  },
  {
    type: 'drill', title: 'Start with “Ik denk dat …”', grammar: ['dat-clause', 'verb-final', 'modals', 'infinitive-end', 'possessives'],
    instruction: 'Put the sentence behind the words given. It becomes a dat-clause: subject after dat, verbs at the end.',
    items: [
      { nl: 'Bram is thuis.', task: 'Start with “Ik denk dat”', answer: 'Ik denk dat Bram thuis is.' },
      { nl: 'Het regent morgen.', task: 'Start with “Ik denk dat”', answer: 'Ik denk dat het morgen regent.' },
      { nl: 'Het examen gaat goed.', task: 'Start with “Lotte hoopt dat”', answer: 'Lotte hoopt dat het examen goed gaat.' },
      { nl: 'Jouw examen gaat goed.', task: 'Start with “Ik denk dat”', answer: 'Ik denk dat jouw examen goed gaat.', accept: ['Ik denk dat je examen goed gaat.'] },
      { nl: 'Zij moet morgen werken.', task: 'Start with “Ik weet dat”', answer: 'Ik weet dat zij morgen moet werken.', accept: ['Ik weet dat zij morgen werken moet.'] },
      { nl: 'Lotte heeft vrijdag een examen.', task: 'Start with “Bram weet dat”', answer: 'Bram weet dat Lotte vrijdag een examen heeft.' },
      { nl: 'Jij spreekt heel goed Nederlands.', task: 'Start with “Ik vind dat”', answer: 'Ik vind dat jij heel goed Nederlands spreekt.' },
      { nl: 'Het regent zaterdag niet.', task: 'Start with “Ik hoop dat”', answer: 'Ik hoop dat het zaterdag niet regent.' },
      { nl: 'Jij begrijpt het niet.', task: 'Start with “Ik zie dat”', answer: 'Ik zie dat jij het niet begrijpt.' },
      { nl: 'Het kind wil in het park spelen.', task: 'Start with “Ik begrijp dat”', answer: 'Ik begrijp dat het kind in het park wil spelen.', accept: ['Ik begrijp dat het kind in het park spelen wil.'] },
    ],
    explanation: 'The clause after dat keeps its order up to the verb: “dat het zaterdag niet regent”, “dat jij het niet begrijpt”. jij before the verb keeps its t.',
  },
  {
    type: 'drill', title: 'Questions inside a sentence', grammar: ['dat-clause', 'verb-final', 'question-word', 'wie-hoe', 'er-is-zijn', 'possessives'],
    instruction: 'Put the question behind the words given. The question word stays at the front of its clause; the verb goes to the end.',
    items: [
      { nl: 'Wanneer is het examen?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet wanneer het examen is.' },
      { nl: 'Waar is Max?', task: 'Start with “Weet jij”', answer: 'Weet jij waar Max is?' },
      { nl: 'Hoe laat is het?', task: 'Start with “Bram vraagt”', answer: 'Bram vraagt hoe laat het is.' },
      { nl: 'Wanneer komt de trein?', task: 'Start with “Lotte vraagt”', answer: 'Lotte vraagt wanneer de trein komt.' },
      { nl: 'Wie is dat?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet wie dat is.' },
      { nl: 'Hoe heet jouw broer?', task: 'Start with “Emma vraagt”', answer: 'Emma vraagt hoe jouw broer heet.' },
      { nl: 'Wat doet Bram vandaag?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet wat Bram vandaag doet.' },
      { nl: 'Hoeveel stoelen zijn er in de keuken?', task: 'Start with “Noor vraagt”', answer: 'Noor vraagt hoeveel stoelen er in de keuken zijn.' },
      { nl: 'Wanneer gaan jullie naar Gent?', task: 'Start with “Zijn moeder vraagt”', answer: 'Zijn moeder vraagt wanneer jullie naar Gent gaan.' },
    ],
    explanation: 'Waar is Max? → waar Max is. Hoe heet jouw broer? → hoe jouw broer heet. The question mark stays only when the whole sentence is a question: Weet jij waar Max is?',
  },
  {
    type: 'drill', title: 'Say it in Dutch: dat', grammar: ['dat-clause', 'verb-final', 'perfect-hebben', 'modals'],
    instruction: 'Translate. English may drop “that”; Dutch never drops dat. Short answers need het.',
    items: [
      { en: 'I think Bram is at home.', answer: 'Ik denk dat Bram thuis is.' },
      { en: 'I know she has to work tomorrow.', answer: 'Ik weet dat zij morgen moet werken.', accept: ['Ik weet dat zij morgen werken moet.'] },
      { en: 'Lotte hopes the exam will go well.', answer: 'Lotte hoopt dat het examen goed gaat.' },
      { en: 'I don’t know.', answer: 'Ik weet het niet.' },
      { en: 'I think so.', answer: 'Ik denk het.' },
      { en: 'I hope not.', answer: 'Ik hoop het niet.' },
      { en: 'Do you know where the station is? (one person)', answer: 'Weet jij waar het station is?' },
      { en: 'Bram asks when the exam is.', answer: 'Bram vraagt wanneer het examen is.' },
      { en: 'Bram says that Lotte has studied a lot.', answer: 'Bram zegt dat Lotte veel geleerd heeft.', accept: ['Bram zegt dat Lotte veel heeft geleerd.'] },
      { en: 'I don’t know that. (start with “that”)', answer: 'Dat weet ik niet.' },
    ],
    explanation: '“Dat weet ik niet”: dat is the first element, so the verb comes second and ik moves behind it.',
  },
  {
    type: 'arrange', title: 'What Bram thinks', grammar: ['dat-clause', 'verb-final', 'possessives'],
    instruction: 'Build: “I think that your exam will go well.” Two tiles are traps.',
    nl: 'Ik denk dat jouw examen goed gaat.', en: 'I think that your exam will go well.', image: 'man-thinking', distractors: ['jij', 'want'],
  },

  // ——— Grammar: als, misschien, wanneer ———
  {
    type: 'grammar', title: 'Als het regent, …', grammar: ['als-inversion', 'verb-final', 'v2-inversion', 'question-word', 'clock-time'],
    body: [
      '**als** means “if”, and also “when / whenever” for the present and the future: *Als het regent, gaan wij niet naar het park.* It opens a subordinate clause, so its verb goes to the end: *als het **regent***, *als het examen goed **gaat***.',
      'Now the important part. When the als-clause comes **first**, the whole clause counts as **one element** — position one, exactly like *vandaag* in lesson 6. The verb of the main clause must be second, so it comes **straight after the comma**, and the subject follows it: *Als het regent, **gaan wij** niet naar het park.* Never *Als het regent, wij gaan …*. You will recognise the pattern by its sound: verb, comma, verb — *regent, gaan*.',
      'When the main clause comes first, nothing special happens: *Wij gaan niet naar het park, als het regent.* The same holds for an **omdat**-clause at the front: *Omdat het regent, **gaat Lotte** niet naar het park.* (want can never start a sentence like this.)',
      'The jij rule comes along: *Als het regent, **ga jij** met de trein.* Inside the als-clause, of course, jij keeps its t: *Als jij moe **bent**, **kook ik**.*',
      '**misschien** (maybe) is an ordinary first element too: ***Misschien regent** het morgen.* Or put it in the middle, after the verb: *Het regent morgen misschien.* Never *Misschien het regent*.',
      '**wanneer?** asks “when?” — for any time: a day, a moment, a clock time. *Wanneer is het examen? — Vrijdag, om negen uur.* **Hoe laat?** asks only for the clock time. **als** never asks a question. (wanneer can also join clauses like als; you have already used it inside sentences: *Ik weet niet wanneer het examen is.*)',
    ],
    tables: [
      { caption: 'als-clause first → verb, then subject', rows: [
        { nl: 'Als het regent, [gaan wij] niet naar het park.', en: 'If it rains, we won’t go to the park.' },
        { nl: 'Als het examen goed gaat, [is Lotte] blij.', en: 'If the exam goes well, Lotte will be happy.' },
        { nl: 'Als jij moe bent, [kook ik].', en: 'If you are tired, I’ll cook.' },
        { nl: 'Als het regent, [ga jij] met de trein.', en: 'If it rains, you go by train — ga jij, no t.' },
        { nl: 'Omdat het regent, [gaat Lotte] niet naar het park.', en: 'Because it is raining, Lotte is not going to the park.' },
      ] },
      { caption: 'main clause first → normal order', rows: [
        { nl: 'Wij gaan niet naar het park, als het [regent].', en: 'We won’t go to the park if it rains.' },
        { nl: 'Lotte is blij, als het examen goed [gaat].', en: 'Lotte will be happy if the exam goes well.' },
      ] },
    ],
    examples: [
      { nl: 'Misschien regent het morgen.', en: 'Maybe it will rain tomorrow.' },
      { nl: 'Het regent morgen misschien.', en: 'It may rain tomorrow.' },
      { nl: 'Wanneer ga jij naar Gent?', en: 'When are you going to Ghent?' },
      { nl: 'Hoe laat komt de trein?', en: 'What time does the train come?' },
    ],
  },
  {
    type: 'drill', title: 'Which order after the comma?', grammar: ['als-inversion', 'verb-final', 'v2-inversion'],
    instruction: 'Choose the words that fill the gap. After a clause at the front, the verb comes first.',
    items: [
      { nl: 'Als het regent, ___ niet naar het park.', en: 'If it rains, we won’t go to the park.', choices: ['wij gaan', 'gaan wij'], answer: 'gaan wij' },
      { nl: 'Als het examen goed gaat, ___ blij.', en: 'If the exam goes well, Lotte will be happy.', choices: ['Lotte is', 'is Lotte'], answer: 'is Lotte' },
      { nl: 'Als jij moe bent, ___.', en: 'If you are tired, I will cook.', choices: ['ik kook', 'kook ik'], answer: 'kook ik' },
      { nl: 'Als het morgen regent, ___ met de trein.', en: 'If it rains tomorrow, you go by train.', choices: ['jij gaat', 'gaat jij', 'ga jij'], answer: 'ga jij' },
      { nl: 'Omdat het regent, ___ niet naar het park.', en: 'Because it is raining, Max is not going to the park.', choices: ['Max gaat', 'gaat Max'], answer: 'gaat Max' },
      { nl: 'Misschien ___ morgen.', en: 'Maybe it will rain tomorrow.', choices: ['het regent', 'regent het'], answer: 'regent het' },
      { nl: 'Wij gaan naar het park, ___.', en: 'We are going to the park if it doesn’t rain.', choices: ['als het niet regent', 'als regent het niet', 'als het regent niet'], answer: 'als het niet regent' },
      { nl: 'Ik weet niet ___.', en: 'I don’t know when the exam is.', choices: ['wanneer het examen is', 'wanneer is het examen'], answer: 'wanneer het examen is' },
    ],
  },
  {
    type: 'drill', title: 'Start with the als-clause', grammar: ['als-inversion', 'verb-final', 'v2-inversion', 'modals', 'infinitive-end'],
    task: 'Start with the als-clause',
    instruction: 'Move the als-clause (or the omdat-clause) to the front. Then the main clause starts with its verb.',
    items: [
      { nl: 'Wij gaan niet naar het park als het regent.', answer: 'Als het regent, gaan wij niet naar het park.' },
      { nl: 'Lotte is blij als het examen goed gaat.', answer: 'Als het examen goed gaat, is Lotte blij.' },
      { nl: 'Ik kook als jij moe bent.', answer: 'Als jij moe bent, kook ik.' },
      { nl: 'Jij gaat met de trein als het regent.', answer: 'Als het regent, ga jij met de trein.' },
      { nl: 'Het kind speelt in de tuin als het niet regent.', answer: 'Als het niet regent, speelt het kind in de tuin.' },
      { nl: 'Bram helpt de oude man als hij thuis is.', answer: 'Als hij thuis is, helpt Bram de oude man.' },
      { nl: 'Jij mag koffie drinken als jij wilt.', answer: 'Als jij wilt, mag jij koffie drinken.' },
      { nl: 'Wij kunnen naar het park gaan als het morgen niet regent.', answer: 'Als het morgen niet regent, kunnen wij naar het park gaan.' },
      { nl: 'Lotte gaat niet naar het park omdat het regent.', task: 'Start with the omdat-clause', answer: 'Omdat het regent, gaat Lotte niet naar het park.' },
    ],
    explanation: 'Als jij wilt, mag jij: inside the als-clause jij wilt keeps its t; in the main clause the verb comes first. Als het regent, ga jij: jij behind the verb, no t.',
  },
  {
    type: 'drill', title: 'misschien and wanneer', grammar: ['als-inversion', 'question-word', 'v2-inversion', 'clock-time', 'days-op-om', 'perfect-hebben'],
    instruction: 'Rewrite as the task says. misschien takes the first slot like a time word; wanneer takes the place of the time you ask about.',
    items: [
      { nl: 'Het regent morgen.', task: 'Start with “misschien”', answer: 'Misschien regent het morgen.' },
      { nl: 'Bram komt om zeven uur thuis.', task: 'Start with “misschien”', answer: 'Misschien komt Bram om zeven uur thuis.' },
      { nl: 'Jij bent ziek.', task: 'Start with “misschien”', answer: 'Misschien ben jij ziek.' },
      { nl: 'Het examen is vrijdag.', task: 'Ask with “wanneer”', answer: 'Wanneer is het examen?' },
      { nl: 'Jij gaat zondag naar Gent.', task: 'Ask with “wanneer”', answer: 'Wanneer ga jij naar Gent?' },
      { nl: 'De trein komt om acht uur.', task: 'Ask with “hoe laat”', answer: 'Hoe laat komt de trein?' },
      { nl: 'Emma komt morgen.', task: 'Ask with “wanneer”', answer: 'Wanneer komt Emma?' },
      { nl: 'Jullie hebben op maandag een examen.', task: 'Ask with “wanneer”', answer: 'Wanneer hebben jullie een examen?' },
      { nl: 'Jij hebt gisteren het examen gemaakt.', task: 'Ask with “wanneer”', answer: 'Wanneer heb jij het examen gemaakt?' },
      { nl: 'Het heeft vorige week veel geregend.', task: 'Ask with “wanneer”', answer: 'Wanneer heeft het veel geregend?' },
    ],
    explanation: 'Misschien ben jij ziek — jij bent becomes ben jij, as after every first element. With wanneer the time word disappears: it is what you are asking about.',
  },
  {
    type: 'arrange', title: 'If it rains tomorrow', grammar: ['als-inversion', 'verb-final', 'time-place'],
    instruction: 'Build: “If it rains tomorrow, we won’t go to the park.” Two tiles are traps.',
    nl: 'Als het morgen regent, gaan wij niet naar het park.', en: 'If it rains tomorrow, we won’t go to the park.', image: 'rain', distractors: ['gaat', 'omdat'],
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', layout: 'table', title: 'Every verb you know, part one', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'zijn', 'hebben', 'gaan', 'subject-pronouns', 'dt-rule', 'modals'],
    instruction: 'Verbs from all eleven lessons, mixed. The small word under each person is the verb. Type the form.',
    items: [
      { label: 'ik', gloss: 'zijn', answer: 'ben' },
      { label: 'jij', gloss: 'hebben', answer: 'hebt' },
      { label: 'zij', gloss: 'she · gaan', answer: 'gaat' },
      { label: 'ik', gloss: 'komen', answer: 'kom' },
      { label: 'hij', gloss: 'wonen', answer: 'woont' },
      { label: 'jij', gloss: 'lopen', answer: 'loopt' },
      { label: 'ik', gloss: 'zitten', answer: 'zit' },
      { label: 'zij', gloss: 'she · slapen', answer: 'slaapt' },
      { label: 'jij', gloss: 'koken', answer: 'kookt' },
      { label: 'wij', gloss: 'spelen', answer: 'spelen' },
      { label: 'hij', gloss: 'praten', answer: 'praat' },
      { label: 'jij', gloss: 'wachten', answer: 'wacht' },
      { label: 'zij', gloss: 'she · lezen', answer: 'leest' },
      { label: 'ik', gloss: 'eten', answer: 'eet' },
      { label: 'ik', gloss: 'schrijven', answer: 'schrijf' },
      { label: 'hij', gloss: 'heten', answer: 'heet' },
      { label: 'jij', gloss: 'kunnen', answer: 'kunt' },
      { label: 'hij', gloss: 'willen', answer: 'wil' },
      { label: 'ik', gloss: 'rijden', answer: 'rijd' },
      { label: 'hij', gloss: 'rijden', answer: 'rijdt' },
    ],
    explanation: 'The traps of the whole volume in one table: zit (one t), loopt and kookt (double vowel back), leest and schrijf (z → s, v → f), praat, wacht, eet and heet (no second t), kom (the one short stem), jij kunt but hij kan, hij wil without t, rijd / rijdt (d + t).',
  },
  {
    type: 'drill', title: 'Every verb you know, part two — at the end', grammar: ['verb-final', 'dat-clause', 'want-omdat', 'als-inversion', 'dt-rule', 'modals', 'infinitive-end', 'present-regular'],
    instruction: 'Now the other verbs, each at the end of a subordinate clause. Type the form of the verb given.',
    items: [
      { nl: 'Ik weet dat Bram heel goed ___.', cue: 'zwemmen', answer: 'zwemt' },
      { nl: 'Lotte is blij, omdat zij goed Engels ___.', cue: 'spreken', answer: 'spreekt' },
      { nl: 'Ik weet dat jij goed ___.', cue: 'rijden', en: 'I know that you drive well.', answer: 'rijdt' },
      { nl: 'Bram is blij, omdat hij de oude man ___.', cue: 'helpen', answer: 'helpt' },
      { nl: 'Lotte zegt dat Bram een bank voor de tuin ___.', cue: 'maken', answer: 'maakt' },
      { nl: 'Ik denk dat Lotte een nieuwe jas ___.', cue: 'kopen', answer: 'koopt' },
      { nl: 'Weet jij wat Noor in de tuin ___?', cue: 'zien', en: 'Do you know what Noor sees in the garden?', answer: 'ziet' },
      { nl: 'Ik weet niet wat Bram vandaag ___.', cue: 'doen', answer: 'doet' },
      { nl: 'Ik hoop dat jij de film mooi ___.', cue: 'vinden', en: 'I hope that you like the film.', answer: 'vindt' },
      { nl: 'Het kind begrijpt niet wat de oude man ___.', cue: 'zeggen', answer: 'zegt' },
      { nl: 'Ik weet dat jij goed Nederlands ___ spreken.', cue: 'kunnen', answer: 'kunt' },
      { nl: 'Max is blij, omdat hij in het park ___ lopen.', cue: 'mogen', answer: 'mag' },
      { nl: 'Ik denk dat Noor in de tuin ___ spelen.', cue: 'willen', answer: 'wil' },
      { nl: 'Lotte is thuis, omdat zij ___ leren.', cue: 'moeten', answer: 'moet' },
      { nl: 'Als jij het niet ___, kan Bram je helpen.', cue: 'begrijpen', answer: 'begrijpt' },
      { nl: 'Ik weet niet wat Lotte ___.', cue: 'denken', answer: 'denkt' },
      { nl: 'Ik denk dat Emma het ___.', cue: 'weten', answer: 'weet' },
      { nl: 'Lotte ___ dat het zaterdag niet regent.', cue: 'hopen', answer: 'hoopt' },
      { nl: 'Ik weet niet wat Emma ___.', cue: 'vragen', answer: 'vraagt' },
      { nl: 'Bram zegt dat het morgen ___.', cue: 'regenen', answer: 'regent' },
      { nl: 'Weet jij hoe laat het ___?', cue: 'zijn', answer: 'is' },
    ],
    explanation: 'dat jij goed rijdt, dat jij de film mooi vindt: jij before the verb, so stem + t — and the d stays, so you write dt. With a modal the modal comes first: kunt spreken, mag lopen, wil spelen, moet leren.',
  },
  {
    type: 'drill', title: 'The perfect in a subordinate clause', grammar: ['verb-final', 'perfect-hebben', 'perfect-zijn', 'participle', 'dat-clause', 'want-omdat'],
    instruction: 'Rewrite as the task says. The participle and hebben / zijn both go to the end; either order is accepted.',
    items: [
      { nl: 'Bram is moe. Hij heeft gisteren in Brussel gewerkt.', task: 'Join with omdat', answer: 'Bram is moe, omdat hij gisteren in Brussel gewerkt heeft.', accept: ['Bram is moe, omdat hij gisteren in Brussel heeft gewerkt.'] },
      { nl: 'Lotte heeft vorige week een nieuwe jas gekocht.', task: 'Start with “Ik weet dat”', answer: 'Ik weet dat Lotte vorige week een nieuwe jas gekocht heeft.', accept: ['Ik weet dat Lotte vorige week een nieuwe jas heeft gekocht.'] },
      { nl: 'Wij hebben zaterdag een film gezien.', task: 'Start with “Bram zegt dat”', answer: 'Bram zegt dat wij zaterdag een film gezien hebben.', accept: ['Bram zegt dat wij zaterdag een film hebben gezien.'] },
      { nl: 'Het heeft gisteren veel geregend.', task: 'Start with “Ik weet dat”', answer: 'Ik weet dat het gisteren veel geregend heeft.', accept: ['Ik weet dat het gisteren veel heeft geregend.'] },
      { nl: 'Bram en Lotte zijn vorig weekend naar Gent gegaan.', task: 'Start with “Ik weet dat”', answer: 'Ik weet dat Bram en Lotte vorig weekend naar Gent gegaan zijn.', accept: ['Ik weet dat Bram en Lotte vorig weekend naar Gent zijn gegaan.'] },
      { nl: 'Het examen is goed gegaan.', task: 'Start with “Lotte hoopt dat”', answer: 'Lotte hoopt dat het examen goed gegaan is.', accept: ['Lotte hoopt dat het examen goed is gegaan.'] },
      { nl: 'Lotte is blij. Zij heeft het boek begrepen.', task: 'Join with omdat', answer: 'Lotte is blij, omdat zij het boek begrepen heeft.', accept: ['Lotte is blij, omdat zij het boek heeft begrepen.'] },
      { nl: 'Max is moe. Hij heeft veel gelopen.', task: 'Join with omdat', answer: 'Max is moe, omdat hij veel gelopen heeft.', accept: ['Max is moe, omdat hij veel heeft gelopen.'] },
      { nl: 'Bram heeft een bank gemaakt.', task: 'Start with “Lotte zegt dat”', answer: 'Lotte zegt dat Bram een bank gemaakt heeft.', accept: ['Lotte zegt dat Bram een bank heeft gemaakt.'] },
      { nl: 'Jij hebt het gevraagd.', task: 'Start with “Ik ben blij dat”', answer: 'Ik ben blij dat jij het gevraagd hebt.', accept: ['Ik ben blij dat jij het hebt gevraagd.'] },
    ],
    explanation: 'vorige week (de week) but vorig weekend (het weekend): the adjective rule of lesson 4 again. gegaan zijn / zijn gegaan — movement still takes zijn.',
  },
  {
    type: 'drill', title: 'Everything so far, inside the new sentences', grammar: ['plural', 'numbers', 'er-is-zijn', 'possessives', 'wie-hoe', 'clock-time', 'days-op-om', 'adjective-e', 'geen-niet', 'geen', 'niet', 'adverb-position', 'hij-het-things', 'spelling-z-s', 'dit-is', 'de-het'],
    instruction: 'Type the missing word. Every grammar point of volume zero and one is in here, now inside dat-, omdat- and als-clauses.',
    items: [
      { nl: 'Ik weet dat er vier ___ in de keuken zijn.', cue: 'stoel', answer: 'stoelen' },
      { nl: 'Noor vraagt hoeveel ___ de oude man heeft.', cue: 'kat', answer: 'katten' },
      { nl: 'Ik denk dat er ___ tafels in de tuin zijn.', en: 'I think there are two tables in the garden.', answer: 'twee' },
      { nl: 'Lotte zegt dat ___ broer in Antwerpen woont.', en: 'Lotte says that her brother lives in Antwerp.', answer: 'haar' },
      { nl: 'Wij zeggen dat ___ huis drie kamers heeft.', en: 'We say that our house has three rooms.', answer: 'ons' },
      { nl: 'Ik hoop dat ___ tuin mooi is.', en: 'I hope that our garden is beautiful.', answer: 'onze' },
      { nl: 'Weet jij ___ dat is?', en: 'Do you know who that is?', answer: 'wie' },
      { nl: 'Weet jij ___ laat het is?', answer: 'hoe' },
      { nl: 'Het examen is vrijdag ___ negen uur.', cue: 'op / om', answer: 'om' },
      { nl: 'Het is ___ tien.', en: 'It is half past nine.', answer: 'half' },
      { nl: 'Ik denk dat Lotte een ___ jas heeft.', cue: 'nieuw', answer: 'nieuwe' },
      { nl: 'Ik denk dat Lotte vandaag ___ koffie drinkt.', en: 'I think that Lotte isn’t drinking coffee today.', answer: 'geen' },
      { nl: 'Ik hoop dat Bram vandaag ___ naar Brussel gaat.', en: 'I hope that Bram isn’t going to Brussels today.', answer: 'niet' },
      { nl: 'Ik weet dat Lotte ___ koffie drinkt.', en: 'I know that Lotte never drinks coffee.', answer: 'nooit' },
      { nl: 'De film is mooi. Ik denk dat ___ heel mooi is.', cue: 'hij / het', answer: 'hij' },
      { nl: 'Ik denk dat Lotte elke dag een boek ___.', cue: 'lezen', answer: 'leest' },
      { image: 'exam', nl: 'Wat is dit?', answer: 'Dit is een examen.', accept: ['Dit is het examen.'] },
      { nl: '___ examen', cue: 'de / het', answer: 'het' },
    ],
    explanation: 'Plurals: stoelen, katten. ons huis (het-word) but onze tuin (de-word). om + clock time, half tien = 9:30. geen for a noun without an article, niet for the rest. de film → hij.',
  },
  {
    type: 'arrange', title: 'Because it rains, first', grammar: ['als-inversion', 'want-omdat', 'verb-final', 'time-place'],
    instruction: 'Build: “Because it is raining, Lotte is not going to the park today.” The omdat-clause comes first.',
    nl: 'Omdat het regent, gaat Lotte vandaag niet naar het park.', en: 'Because it is raining, Lotte is not going to the park today.', image: 'rain', distractors: ['want', 'geen'],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Het examen', image: 'rain', grammar: ['want-omdat', 'verb-final', 'dat-clause', 'als-inversion', 'v2-inversion', 'clock-time', 'modals', 'perfect-hebben', 'possessives', 'time-place'],
    instruction: 'The longest dialogue of the book, and everything from both volumes is in it. Read and listen to every line, then read it again without the English. Find every verb that stands at the end.',
    lines: [
      { nl: 'Het is woensdag, zes uur. Het regent al drie dagen in Leuven.', en: 'It is Wednesday, six o’clock. It has been raining in Leuven for three days.', image: 'rain' },
      { nl: 'Lotte zit met haar boeken in de keuken, want vrijdag heeft zij een examen.', en: 'Lotte is sitting in the kitchen with her books, because on Friday she has an exam.', image: 'woman-studying' },
      { nl: 'Bram komt thuis. Hij is moe, omdat hij vandaag in Brussel gewerkt heeft.', en: 'Bram comes home. He is tired, because he has been working in Brussels today.', image: 'man-tired' },
      { speaker: 'Bram', nl: 'Lotte, ik ga met Max naar het park. Kom jij ook?', en: 'Lotte, I’m going to the park with Max. Are you coming too?', image: 'man-dog' },
      { speaker: 'Lotte', nl: 'Nee, ik kom niet, omdat ik moet leren. En het regent!', en: 'No, I’m not coming, because I have to study. And it’s raining!', image: 'woman-studying' },
      { speaker: 'Bram', nl: 'Max wil altijd lopen, ook als het regent.', en: 'Max always wants to walk, even when it rains.', image: 'dog-big' },
      { speaker: 'Lotte', nl: 'Goed. Wanneer zijn jullie thuis?', en: 'Fine. When will you be home?', image: 'woman' },
      { speaker: 'Bram', nl: 'Om zeven uur, denk ik. Dan kook ik.', en: 'At seven, I think. Then I’ll cook.', image: 'man-cooking' },
      { speaker: 'Lotte', nl: 'Ik hoop dat mijn examen goed gaat. Ik begrijp het boek nog niet goed.', en: 'I hope my exam goes well. I don’t understand the book well yet.', image: 'book' },
      { speaker: 'Bram', nl: 'Ik denk dat jouw examen goed gaat, want jij leert elke dag.', en: 'I think your exam will go well, because you study every day.', image: 'man-thinking' },
      { nl: 'Bram en Max gaan naar het park. Dan gaat de telefoon. Het is Emma.', en: 'Bram and Max go to the park. Then the phone rings. It is Emma.', image: 'phone' },
      { speaker: 'Emma', nl: 'Dag Lotte! Wanneer is jouw examen?', en: 'Hi Lotte! When is your exam?', image: 'phone' },
      { speaker: 'Lotte', nl: 'Vrijdag, om negen uur. Ik moet nog veel leren.', en: 'Friday, at nine. I still have a lot to study.', image: 'woman-studying' },
      { speaker: 'Emma', nl: 'Zaterdag gaan Jonas en ik naar de film. Komen Bram en jij ook?', en: 'On Saturday Jonas and I are going to the cinema. Are Bram and you coming too?', image: 'cinema' },
      { speaker: 'Lotte', nl: 'Als mijn examen goed gaat, komen wij graag!', en: 'If my exam goes well, we’d love to come!', image: 'woman' },
      { nl: 'Lotte maakt thee en leert nog een uur. Het regent nog altijd.', en: 'Lotte makes tea and studies for another hour. It is still raining.', image: 'tea' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'inversion'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the story. Answer without looking back.',
    items: [
      { nl: 'Regent het al drie dagen in Leuven?', answer: 'Ja' },
      { nl: 'Heeft Lotte vrijdag een examen?', answer: 'Ja' },
      { nl: 'Heeft Bram vandaag thuis gewerkt?', answer: 'Nee' },
      { nl: 'Gaat Lotte met Max naar het park?', answer: 'Nee' },
      { nl: 'Kookt Bram om zeven uur?', answer: 'Ja' },
      { nl: 'Denkt Bram dat het examen goed gaat?', answer: 'Ja' },
      { nl: 'Is het examen om tien uur?', answer: 'Nee' },
      { nl: 'Gaan Emma en Jonas zaterdag naar de film?', answer: 'Ja' },
    ],
  },
  {
    type: 'drill', title: 'Answer in full — and say why', grammar: ['want-omdat', 'verb-final', 'dat-clause', 'als-inversion', 'question-word', 'modals', 'perfect-hebben'],
    instruction: 'Answer each question about the story with a complete sentence. When the task says “say why”, join the given sentence to its reason.',
    items: [
      { nl: 'Wanneer heeft Lotte een examen?', answer: 'Lotte heeft vrijdag een examen.', accept: ['Zij heeft vrijdag een examen.', 'Vrijdag heeft Lotte een examen.', 'Vrijdag heeft zij een examen.', 'Lotte heeft vrijdag om negen uur een examen.', 'Zij heeft vrijdag om negen uur een examen.', 'Lotte heeft op vrijdag een examen.', 'Zij heeft op vrijdag een examen.', 'Vrijdag om negen uur.', 'Vrijdag.'] },
      { nl: 'Hoe laat is het examen?', answer: 'Het examen is om negen uur.', accept: ['Het is om negen uur.', 'Om negen uur.', 'Het examen is vrijdag om negen uur.'] },
      { nl: 'Lotte gaat niet naar het park.', task: 'Say why — use omdat', answer: 'Lotte gaat niet naar het park, omdat zij moet leren.', accept: ['Lotte gaat niet naar het park, omdat zij leren moet.', 'Lotte gaat niet naar het park, omdat het regent.', 'Lotte gaat niet naar het park, omdat zij vrijdag een examen heeft.'] },
      { nl: 'Bram is moe.', task: 'Say why — use omdat', answer: 'Bram is moe, omdat hij vandaag in Brussel gewerkt heeft.', accept: ['Bram is moe, omdat hij vandaag in Brussel heeft gewerkt.', 'Bram is moe, omdat hij vandaag gewerkt heeft.', 'Bram is moe, omdat hij vandaag heeft gewerkt.', 'Bram is moe, omdat hij in Brussel gewerkt heeft.', 'Bram is moe, omdat hij in Brussel heeft gewerkt.'] },
      { nl: 'Lotte zit met haar boeken in de keuken.', task: 'Say why — use want', answer: 'Lotte zit met haar boeken in de keuken, want vrijdag heeft zij een examen.', accept: ['Lotte zit met haar boeken in de keuken, want zij heeft vrijdag een examen.', 'Lotte zit met haar boeken in de keuken, want zij moet leren.'] },
      { nl: 'Wat denkt Bram?', answer: 'Bram denkt dat het examen goed gaat.', accept: ['Hij denkt dat het examen goed gaat.', 'Bram denkt dat haar examen goed gaat.', 'Hij denkt dat haar examen goed gaat.'] },
      { nl: 'Wat hoopt Lotte?', answer: 'Lotte hoopt dat haar examen goed gaat.', accept: ['Zij hoopt dat haar examen goed gaat.', 'Lotte hoopt dat het examen goed gaat.', 'Zij hoopt dat het examen goed gaat.'] },
      { nl: 'Wanneer zijn Bram en Max thuis?', answer: 'Bram en Max zijn om zeven uur thuis.', accept: ['Zij zijn om zeven uur thuis.', 'Om zeven uur zijn zij thuis.', 'Om zeven uur.'] },
      { nl: 'Wat vraagt Emma?', answer: 'Emma vraagt wanneer het examen is.', accept: ['Zij vraagt wanneer het examen is.', 'Emma vraagt wanneer haar examen is.', 'Zij vraagt wanneer haar examen is.'] },
      { nl: 'Gaan Bram en Lotte zaterdag naar de film?', task: 'Answer with als', answer: 'Als het examen goed gaat, gaan zij zaterdag naar de film.', accept: ['Als haar examen goed gaat, gaan zij zaterdag naar de film.', 'Als het examen goed gaat, gaan zij naar de film.', 'Als haar examen goed gaat, gaan zij naar de film.', 'Als het examen goed gaat, gaan Bram en Lotte zaterdag naar de film.', 'Als het examen goed gaat, gaan Bram en Lotte naar de film.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['want-omdat', 'verb-final', 'dat-clause', 'als-inversion'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'Ik ga niet naar het park, omdat het regent.' },
      { listen: 'Lotte heeft vrijdag een examen.' },
      { listen: 'Ik denk dat Bram thuis is.' },
      { listen: 'Als het regent, gaan wij niet naar het park.' },
      { listen: 'Weet jij wanneer het examen is?' },
      { listen: 'Ik hoop dat jouw examen goed gaat.' },
      { listen: 'Misschien regent het morgen niet.' },
      { listen: 'Bram is moe, want hij heeft vandaag in Brussel gewerkt.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['want-omdat', 'verb-final', 'dat-clause', 'als-inversion', 'perfect-hebben', 'modals', 'adjective-e'],
    instruction: 'Translate. When the English names want or omdat, use that one. “You” is one person unless it says plural.',
    items: [
      { en: 'I am not going, because it is raining. (use omdat)', answer: 'Ik ga niet, omdat het regent.' },
      { en: 'I am not going, because it is raining. (use want)', answer: 'Ik ga niet, want het regent.' },
      { en: 'Lotte is at home, because she has to study. (use omdat)', answer: 'Lotte is thuis, omdat zij moet leren.', accept: ['Lotte is thuis, omdat zij leren moet.'] },
      { en: 'Bram thinks your exam will go well.', answer: 'Bram denkt dat jouw examen goed gaat.', accept: ['Bram denkt dat je examen goed gaat.'] },
      { en: 'Do you know when the exam is?', answer: 'Weet jij wanneer het examen is?' },
      { en: 'If it rains tomorrow, we are not going to the park.', answer: 'Als het morgen regent, gaan wij niet naar het park.', accept: ['Wij gaan morgen niet naar het park, als het regent.', 'Wij gaan niet naar het park, als het morgen regent.'] },
      { en: 'I hope it won’t rain on Saturday.', answer: 'Ik hoop dat het zaterdag niet regent.', accept: ['Ik hoop dat het op zaterdag niet regent.'] },
      { en: 'Maybe Bram is at home.', answer: 'Misschien is Bram thuis.', accept: ['Bram is misschien thuis.'] },
      { en: 'I don’t understand it, because I don’t speak Dutch well yet. (use omdat)', answer: 'Ik begrijp het niet, omdat ik nog niet goed Nederlands spreek.' },
      { en: 'Lotte says that she bought a new coat last week.', answer: 'Lotte zegt dat zij vorige week een nieuwe jas gekocht heeft.', accept: ['Lotte zegt dat zij vorige week een nieuwe jas heeft gekocht.'] },
      { en: 'When are you (plural) going to Ghent?', answer: 'Wanneer gaan jullie naar Gent?' },
      { en: 'Emma asks where the station is.', answer: 'Emma vraagt waar het station is.' },
      { en: 'If you are tired, I will cook.', answer: 'Als jij moe bent, kook ik.', accept: ['Ik kook, als jij moe bent.'] },
      { en: 'I know that it rained a lot yesterday.', answer: 'Ik weet dat het gisteren veel geregend heeft.', accept: ['Ik weet dat het gisteren veel heeft geregend.'] },
    ],
  },
  {
    type: 'drill', title: 'Volume one in one round', grammar: ['want-omdat', 'verb-final', 'dat-clause', 'als-inversion', 'de-het', 'plural', 'present-regular', 'inversion', 'v2-inversion', 'question-word', 'perfect-hebben', 'er-is-zijn', 'numbers'],
    instruction: 'A final, demanding round: everything from lesson 1 to lesson 12, mixed. Type every answer. No hints beyond the task.',
    items: [
      { nl: 'twee ___', cue: 'examen', answer: 'examens' },
      { nl: 'Hij ___ het niet.', cue: 'weten', answer: 'weet' },
      { nl: '___ jij het?', cue: 'begrijpen', answer: 'Begrijp' },
      { nl: 'Lotte is thuis, omdat zij vrijdag een examen ___.', cue: 'hebben', answer: 'heeft' },
      { nl: 'Ik ga niet, want morgen ___ ik een examen.', cue: 'hebben', answer: 'heb' },
      { nl: 'Als het regent, ___ Max niet naar het park.', cue: 'gaan', answer: 'gaat' },
      { nl: 'Er ___ drie kamers in het huis.', cue: 'zijn', answer: 'zijn' },
      { nl: 'Bram is thuis.', task: 'Start with “Ik denk dat”', answer: 'Ik denk dat Bram thuis is.' },
      { nl: 'Waar is mijn telefoon?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet waar mijn telefoon is.' },
      { nl: 'Wij gaan niet naar het park als het regent.', task: 'Start with the als-clause', answer: 'Als het regent, gaan wij niet naar het park.' },
      { nl: 'Lotte leert. Zij heeft vrijdag een examen.', task: 'Join with omdat', answer: 'Lotte leert, omdat zij vrijdag een examen heeft.' },
      { nl: 'Het examen is vrijdag.', task: 'Ask with “wanneer”', answer: 'Wanneer is het examen?' },
      { nl: 'Het regent morgen.', task: 'Start with “misschien”', answer: 'Misschien regent het morgen.' },
      { en: 'I think so.', answer: 'Ik denk het.' },
      { en: 'Bram is tired, because he worked yesterday. (use omdat)', answer: 'Bram is moe, omdat hij gisteren gewerkt heeft.', accept: ['Bram is moe, omdat hij gisteren heeft gewerkt.'] },
      { en: 'Do you (plural) know that Lotte has an exam on Friday?', answer: 'Weten jullie dat Lotte vrijdag een examen heeft?', accept: ['Weten jullie dat Lotte op vrijdag een examen heeft?'] },
      { listen: 'Als het examen goed gaat, gaan wij zaterdag naar de film.' },
    ],
  },
  {
    type: 'complete', title: 'Volume one: done',
    instruction: 'Plurals and numbers, a family with names, modals, the week and the clock, the perfect — and now the verb that waits at the end of the clause. You can say what you think, what you know, and why. Ik denk dat jouw Nederlands heel goed gaat.',
  },
];
