/**
 * Lesson 14 — Groter, sneller, beter.
 * Targets: duur, goedkoop, snel, langzaam, warm, koud, lang, kort, makkelijk, moeilijk.
 * Structure: meer, meest, beter, best, liever, liefst, even.
 * Extra vocabulary (vocabulary/groter.js): weer, zon, sneeuw, zo, prijs, sneeuwen, schijnen,
 * buiten, kosten, euro, minder, slak.
 * Grammar: the comparative (-er, -der, beter / meer / liever, the -e before a noun) ·
 * the superlative (de grootste, het grootst, het best, het liefst) · dan and even / niet zo … als.
 * Story: a cold, snowy Saturday in Leuven; Bram buys a warmer coat and rings his mother in Gent.
 * Teaching choices: “lang” is used for tall people and “klein” for short ones (a person is not
 * “kort”); the dan-part is written after a final verb (“omdat de trein sneller is dan de fiets”),
 * and the other order is accepted; predicative superlatives are taught as “het grootst”, and
 * “het grootste” is accepted wherever it can be typed.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Ten words for comparing', grammar: ['adjective-e', 'hij-het-things', 'er-is-zijn'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice. Five pairs of opposites.',
    cards: [
      { nl: 'De trein is snel.', en: 'The train is fast.', image: 'train' },
      { nl: 'Een slak is heel langzaam.', en: 'A snail is very slow.', image: 'snail' },
      { nl: 'Er zijn twee jassen: een dure jas en een goedkope jas.', en: 'There are two coats: an expensive coat and a cheap coat.', image: 'price-tags' },
      { nl: 'De zon schijnt. Het is warm.', en: 'The sun is shining. It is warm.', image: 'sun' },
      { nl: 'Het sneeuwt. Het is koud.', en: 'It is snowing. It is cold.', image: 'snow' },
      { nl: 'Een lange man en een kleine man.', en: 'A tall man and a short man.', image: 'tall-short' },
      { nl: 'De film is kort.', en: 'The film is short.', image: 'cinema' },
      { nl: 'Dit boek is makkelijk.', en: 'This book is easy.', image: 'book' },
      { nl: 'Het examen is moeilijk.', en: 'The exam is difficult.', image: 'exam' },
    ],
    note: 'duur = expensive, goedkoop = cheap, snel = fast, langzaam = slow, warm = warm / hot, koud = cold, lang = long, and tall for a person; kort = short, but only for things and time — a short person is “klein”. makkelijk = easy, moeilijk = difficult. With the -e of lesson 4 the spelling moves: duur → een dure jas, goedkoop → een goedkope jas, snel → een snelle trein, langzaam → een langzame trein.',
  },
  {
    type: 'observe', title: 'Bigger than, faster than', grammar: ['comparative', 'superlative', 'dan-als', 'adverb-position'],
    instruction: 'The same words, now comparing two things. Listen for the -er at the end and the little word “dan”.',
    cards: [
      { nl: 'Max is groter dan Mimi.', en: 'Max is bigger than Mimi.', image: 'dog-big' },
      { nl: 'Bram is langer dan Lotte.', en: 'Bram is taller than Lotte.', image: 'couple-talking' },
      { nl: 'De trein is sneller dan de fiets.', en: 'The train is faster than the bike.', image: 'train' },
      { nl: 'De fiets is goedkoper dan de auto.', en: 'The bike is cheaper than the car.', image: 'bike' },
      { nl: 'Een auto is duurder dan een fiets.', en: 'A car is more expensive than a bike.', image: 'car' },
      { nl: 'Brussel is groter dan Leuven.', en: 'Brussels is bigger than Leuven.', image: 'city' },
      { nl: 'Vandaag is het kouder dan gisteren.', en: 'Today it is colder than yesterday.', image: 'snow' },
      { nl: 'Bram zwemt beter dan Lotte.', en: 'Bram swims better than Lotte.', image: 'man-swimming' },
      { nl: 'Lotte drinkt liever thee dan koffie.', en: 'Lotte would rather drink tea than coffee.', image: 'tea' },
      { nl: 'Leuven, Gent en Brussel: Brussel is het grootst.', en: 'Leuven, Ghent and Brussels: Brussels is the biggest.', image: 'city' },
    ],
    note: '-er = English -er / more: groter, sneller, duurder. dan = than (you know dan as “then”). beter = better, liever = rather, het grootst = the biggest. The next pages explain every form.',
  },
  {
    type: 'observe', title: 'Weather, prices, and a snail', grammar: ['present-regular', 'question-word', 'numbers'],
    instruction: 'Twelve useful words come with this lesson. Listen, and say each sentence out loud.',
    cards: [
      { nl: 'Hoe is het weer? — Het is mooi weer. De zon schijnt.', en: 'What is the weather like? — The weather is nice. The sun is shining.', image: 'sun' },
      { nl: 'Het sneeuwt, en buiten is het heel koud.', en: 'It is snowing, and outside it is very cold.', image: 'snow' },
      { nl: 'Het regent weer!', en: 'It is raining again!', image: 'rain' },
      { nl: 'Hoeveel kost een koffie? — Drie euro.', en: 'How much is a coffee? — Three euros.', image: 'coffee' },
      { nl: 'De prijs is goed: de jas is niet duur.', en: 'The price is good: the coat is not expensive.', image: 'coat' },
      { nl: 'Een fiets kost minder dan een auto.', en: 'A bike costs less than a car.', image: 'bike' },
      { nl: 'Dit is een slak. Een slak is nooit snel.', en: 'This is a snail. A snail is never fast.', image: 'snail' },
      { nl: 'Het is zo koud vandaag!', en: 'It is so cold today!', image: 'snow' },
    ],
    note: 'het weer = the weather; weer also means “again” (Het regent weer!). de zon = the sun, schijnen = to shine; de sneeuw = snow, sneeuwen = to snow (het sneeuwt, like het regent). buiten = outside. kosten = to cost: hoeveel kost …? de prijs = the price (de prijzen). de euro: after a number it stays “euro” — drie euro. minder = less, the opposite of meer. de slak = the snail. zo = so.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['zijn'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Een slak is langzamer dan een trein.', en: 'A snail is slower than a train.', answer: 'snail',
    choices: [{ image: 'train', nl: 'een snelle trein' }, { image: 'snail', nl: 'een langzame slak' }, { image: 'bike', nl: 'een fiets' }, { image: 'dog-big', nl: 'een grote hond' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['zijn'],
    instruction: 'Listen without reading. What is the weather like?',
    nl: 'Het sneeuwt al twee dagen, en het is heel koud.', en: 'It has been snowing for two days, and it is very cold.', answer: 'snow',
    choices: [{ image: 'sun', nl: 'De zon schijnt.' }, { image: 'snow', nl: 'Het sneeuwt.' }, { image: 'rain', nl: 'Het regent.' }, { image: 'park', nl: 'een mooi park' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['de-het'],
    instruction: 'Type the Dutch. Nouns with their article.',
    items: [
      { en: 'expensive', answer: 'duur' },
      { en: 'cheap', answer: 'goedkoop' },
      { image: 'train', en: 'fast', answer: 'snel' },
      { image: 'snail', en: 'slow', answer: 'langzaam' },
      { image: 'sun', en: 'warm', answer: 'warm' },
      { image: 'snow', en: 'cold', answer: 'koud' },
      { en: 'long; tall (a person)', answer: 'lang' },
      { en: 'short (a film, a coat — not a person)', answer: 'kort' },
      { en: 'easy', answer: 'makkelijk' },
      { en: 'difficult', answer: 'moeilijk' },
      { image: 'snail', answer: 'de slak' },
      { en: 'the sun', answer: 'de zon' },
      { en: 'the weather', answer: 'het weer' },
      { en: 'the price', answer: 'de prijs' },
      { en: 'the snow', answer: 'de sneeuw' },
    ],
    explanation: 'de slak, de zon, de sneeuw, de prijs — but het weer. The ten adjectives have no article: they describe.',
  },
  {
    type: 'drill', title: 'Opposites', grammar: ['niet', 'hij-het-things'],
    instruction: 'Type the opposite. Notice the pronoun: hij for a de-word, het for a het-word.',
    items: [
      { nl: 'De trein is niet langzaam. Hij is ___.', answer: 'snel' },
      { nl: 'Een slak is niet snel. Hij is ___.', answer: 'langzaam' },
      { nl: 'Het is vandaag niet warm. Het is ___.', answer: 'koud' },
      { nl: 'Het is vandaag niet koud. Het is ___.', answer: 'warm' },
      { nl: 'Een auto is niet goedkoop. Hij is ___.', answer: 'duur' },
      { nl: 'De koffie is niet duur. Hij is ___.', answer: 'goedkoop' },
      { nl: 'De film is niet kort. Hij is ___.', answer: 'lang' },
      { nl: 'Het weekend is niet lang. Het is ___.', answer: 'kort' },
      { nl: 'Het examen is niet makkelijk. Het is ___.', answer: 'moeilijk' },
      { nl: 'Het boek is niet moeilijk. Het is ___.', answer: 'makkelijk' },
    ],
    explanation: 'de trein, de slak, de auto, de koffie, de film → hij. het weekend, het examen, het boek → het. The weather is always “het”: het is koud.',
  },
  {
    type: 'drill', title: 'Hear and spell',
    instruction: 'Play each one and type it. The ij in moeilijk and makkelijk sounds like a short “uh” here, but it is still written ij.',
    items: [
      { listen: 'makkelijk' },
      { listen: 'moeilijk' },
      { listen: 'langzaam' },
      { listen: 'Het sneeuwt.' },
      { listen: 'De zon schijnt.' },
      { listen: 'Hoeveel kost de jas?' },
    ],
    explanation: 'makkelijk: MAK-ke-luk; moeilijk: MOEI-luk. The -lijk ending is almost always said “luk”. goedkoop is one word: goed + koop.',
  },

  // ——— Grammar: the comparative ———
  {
    part: 'Grammar', type: 'grammar', title: 'Bigger: the comparative', grammar: ['comparative', 'dan-als', 'spelling-stem'],
    body: [
      'Dutch compares with one ending: **-er**. English says “bigger” but “more expensive”; Dutch adds -er to every adjective you know, however long: *groot → **groter**, makkelijk → **makkelijker**, moeilijk → **moeilijker***. The thing you compare with comes after **dan** (than): *Max is **groter dan** Mimi. Een auto is **duurder dan** een fiets.*',
      'So never *meer duur* or *meer moeilijk*. **meer** is “more” of an amount — *meer koffie, meer boeken* — not a word to put in front of an adjective. With the adjectives in this course, the comparative is always the -er form.',
      'The -er adds a syllable, and the spelling rules of lesson 3 do the rest, exactly as between *ik woon* and *wonen*. A long vowel written double loses a letter when its syllable opens: *groot → gro-ter*, *goedkoop → goedko-per*, *langzaam → langza-mer*. A short vowel before a single consonant needs that consonant doubled, or it would sound long: *snel → snel-ler*. Everything else simply adds -er: *kleiner, ouder, jonger, warmer, kouder, langer, korter, mooier, nieuwer, blijer*.',
      'After an **r** the ending is **-der**: *duur → **duurder***. The d makes the two r-sounds easy to say. duur keeps its uu, because the syllable *duur* stays closed.',
      'Listen to *koud → kouder* and *oud → ouder*: at the end of a word a d sounds like a t, but inside kouder it is a real d again. You have heard the same in *ik vind* and *vinden*.',
      'A comparative is still an adjective. After *zijn* it has no ending — *De jas is duurder.* — and before a noun the -e of lesson 4 comes back: *een duurdere jas*. That has its own page below.',
    ],
    tables: [
      { caption: 'just add -er', rows: [
        { nl: 'klein · klein[er]', en: 'small · smaller' },
        { nl: 'oud · oud[er]', en: 'old · older' },
        { nl: 'warm · warm[er]', en: 'warm · warmer' },
        { nl: 'koud · koud[er]', en: 'cold · colder' },
        { nl: 'lang · lang[er]', en: 'long, tall · longer, taller' },
        { nl: 'kort · kort[er]', en: 'short · shorter' },
        { nl: 'makkelijk · makkelijk[er]', en: 'easy · easier' },
        { nl: 'moeilijk · moeilijk[er]', en: 'difficult · more difficult' },
      ] },
      { caption: 'the syllable opens: one vowel less', rows: [
        { nl: 'groot · gro[ter]', en: 'big · bigger' },
        { nl: 'goedkoop · goedko[per]', en: 'cheap · cheaper' },
        { nl: 'langzaam · langza[mer]', en: 'slow · slower' },
      ] },
      { caption: 'the vowel stays short: one consonant more', rows: [
        { nl: 'snel · snel[ler]', en: 'fast · faster' },
      ] },
      { caption: 'after r: -der', rows: [
        { nl: 'duur · duur[der]', en: 'expensive · more expensive' },
      ] },
    ],
    examples: [
      { nl: 'De trein is sneller dan de fiets.', en: 'The train is faster than the bike.' },
      { nl: 'Een fiets is goedkoper dan een auto.', en: 'A bike is cheaper than a car.' },
      { nl: 'Vandaag is het kouder dan gisteren.', en: 'Today it is colder than yesterday.' },
      { nl: 'Schrijven is moeilijker dan lezen.', en: 'Writing is more difficult than reading.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Make the comparative', grammar: ['comparative', 'spelling-stem', 'adjective-e'],
    instruction: 'Type the form asked for. Most adjectives just add -er; for the others: open syllable, one vowel; short vowel, double consonant; after r, -der.',
    items: [
      { label: 'klein', gloss: 'smaller', answer: 'kleiner' },
      { label: 'oud', gloss: 'older', answer: 'ouder' },
      { label: 'koud', gloss: 'colder', answer: 'kouder' },
      { label: 'lang', gloss: 'longer, taller', answer: 'langer' },
      { label: 'kort', gloss: 'shorter', answer: 'korter' },
      { label: 'makkelijk', gloss: 'easier', answer: 'makkelijker' },
      { label: 'moeilijk', gloss: 'more difficult', answer: 'moeilijker' },
      { label: 'groot', gloss: 'bigger', answer: 'groter' },
      { label: 'goedkoop', gloss: 'cheaper', answer: 'goedkoper' },
      { label: 'langzaam', gloss: 'slower', answer: 'langzamer' },
      { label: 'snel', gloss: 'faster', answer: 'sneller' },
      { label: 'duur', gloss: 'more expensive', answer: 'duurder' },
      { label: 'groot', gloss: 'a big (de-word)', answer: 'grote' },
      { label: 'goedkoop', gloss: 'a cheap (de-word)', answer: 'goedkope' },
      { label: 'snel', gloss: 'a fast (de-word)', answer: 'snelle' },
      { label: 'duur', gloss: 'an expensive (de-word)', answer: 'dure' },
    ],
    explanation: 'kleiner, ouder, kouder, langer: just -er. The same rule makes groter and grote, goedkoper and goedkope: an ending opens the syllable, so the double vowel goes. snel keeps its short e by doubling the l: sneller, snelle. Only duur is different: dure, but duurder.',
  },
  {
    type: 'drill', title: 'Type the comparative', grammar: ['comparative', 'dan-als', 'zijn'],
    instruction: 'Type the comparative of the adjective given. Everything here is true in the story.',
    items: [
      { nl: 'De trein is ___ dan de fiets.', cue: 'snel', answer: 'sneller' },
      { nl: 'De fiets is ___ dan de auto.', cue: 'goedkoop', answer: 'goedkoper' },
      { nl: 'Een auto is ___ dan een fiets.', cue: 'duur', answer: 'duurder' },
      { nl: 'Max is ___ dan Mimi.', cue: 'groot', answer: 'groter' },
      { nl: 'Bram is ___ dan Lotte.', cue: 'lang', en: 'Bram is taller than Lotte.', answer: 'langer' },
      { nl: 'Vandaag is het ___ dan gisteren.', cue: 'koud', answer: 'kouder' },
      { nl: 'Een slak is ___ dan een kat.', cue: 'langzaam', answer: 'langzamer' },
      { nl: 'Lezen is ___ dan schrijven.', cue: 'makkelijk', answer: 'makkelijker' },
      { nl: 'Spreken is ___ dan lezen.', cue: 'moeilijk', answer: 'moeilijker' },
      { nl: 'De film is ___ dan het examen.', cue: 'kort', answer: 'korter' },
    ],
    explanation: 'sneller (double l), goedkoper and langzamer (single vowel), duurder (-der). Everything else: just -er.',
  },

  // ——— Grammar: beter, meer, liever ———
  {
    type: 'grammar', title: 'beter, meer, liever — and dan ik', grammar: ['comparative', 'dan-als', 'adverb-position', 'subject-pronouns'],
    body: [
      'Three very common words have their own comparative, as “good → better” does in English: **goed → beter**, **veel → meer**, **graag → liever**.',
      '**beter**: *Bram zwemt **beter** dan Lotte. Lotte spreekt **beter** Engels dan Bram.* goed is both “good” and “well”, so beter is both “better” and “does something better”.',
      '**meer**, and its opposite **minder** (less, fewer): *Bram drinkt **meer** koffie dan Lotte. Een fiets kost **minder** dan een auto.* meer and minder never take an -e, not even in front of a noun: *meer boeken, minder koffie*.',
      '**liever**: graag is how Dutch says “like to” (lesson 5), and liever says “would rather, prefer”. It stands exactly where graag stands — straight after the verb, or after the subject when the verb has gone first: *Ik drink graag thee → Ik drink **liever** thee dan koffie. Drink jij **liever** thee?* What you like less comes after dan.',
      '**dan + a pronoun.** After dan, Dutch uses the subject form: *Bram is groter dan **ik**. Max is sneller dan **jij**. Lotte leest meer dan **hij**.* A verb is understood: *dan ik (ben)*. In relaxed speech you will also hear the object form, like English “than me”, but *dan ik* is the form to write.',
      'When you compare what people do, the comparative stands next to the verb like any other adverb, and Dutch adverbs look exactly like adjectives: *De trein rijdt **sneller** dan de auto. Lotte loopt **langzamer** dan Max.*',
    ],
    tables: [
      { caption: 'three irregular comparatives', rows: [
        { nl: 'goed · [beter]', en: 'good, well · better' },
        { nl: 'veel · [meer]', en: 'much, many · more' },
        { nl: 'graag · [liever]', en: 'like to · would rather' },
        { nl: 'meer · [minder]', en: 'more · less' },
      ] },
      { caption: 'dan + subject pronoun', rows: [
        { nl: 'Bram is groter dan [ik].', en: 'Bram is taller than me.' },
        { nl: 'Max loopt sneller dan [jij].', en: 'Max walks faster than you.' },
        { nl: 'Lotte leest meer dan [hij].', en: 'Lotte reads more than him.' },
      ] },
    ],
    examples: [
      { nl: 'Bram zwemt beter dan Lotte.', en: 'Bram swims better than Lotte.' },
      { nl: 'Bram drinkt meer koffie dan Lotte.', en: 'Bram drinks more coffee than Lotte.' },
      { nl: 'Ik drink liever thee dan koffie.', en: 'I would rather drink tea than coffee.' },
      { nl: 'Drink jij liever thee?', en: 'Would you rather drink tea?' },
      { nl: 'Een fiets kost minder dan een auto.', en: 'A bike costs less than a car.' },
    ],
  },
  {
    type: 'drill', title: 'beter, meer, liever, minder', grammar: ['comparative', 'dan-als', 'adverb-position'],
    instruction: 'Type the missing word. The cue is the plain word; you need its comparative — or, where there is no cue, the English decides.',
    items: [
      { nl: 'Bram zwemt ___ dan Lotte.', cue: 'goed', answer: 'beter' },
      { nl: 'Lotte spreekt ___ Engels dan Bram.', cue: 'goed', answer: 'beter' },
      { nl: 'Bram drinkt ___ koffie dan Lotte.', cue: 'veel', answer: 'meer' },
      { nl: 'Lotte leest ___ dan Bram.', cue: 'veel', answer: 'meer' },
      { nl: 'Ik drink ___ thee dan koffie.', cue: 'graag', answer: 'liever' },
      { nl: 'Lotte gaat ___ met de fiets dan met de trein.', cue: 'graag', answer: 'liever' },
      { nl: 'Een fiets kost ___ dan een auto.', en: 'A bike costs less than a car.', answer: 'minder' },
      { nl: 'Bram is groter dan ___.', en: 'Bram is taller than me.', answer: 'ik' },
      { nl: 'Max loopt sneller dan ___.', en: 'Max walks faster than you.', answer: 'jij' },
      { nl: 'Mimi slaapt ___ dan Max.', cue: 'veel', answer: 'meer' },
      { nl: 'Een auto is ___ dan een fiets.', en: 'A car is more expensive than a bike.', answer: 'duurder' },
    ],
    explanation: 'liever stands where graag stood: Ik drink liever thee. “more expensive” is duurder — never meer duur. After dan: ik, jij, hij.',
  },
  {
    type: 'drill', title: 'Compare the two', grammar: ['comparative', 'dan-als', 'adverb-position'],
    instruction: 'Rewrite the sentence as a comparison with dan. The task shows which one is more: A > B.',
    items: [
      { nl: 'De trein is snel.', task: 'Compare: de trein > de fiets', answer: 'De trein is sneller dan de fiets.' },
      { nl: 'Een auto is duur.', task: 'Compare: een auto > een fiets', answer: 'Een auto is duurder dan een fiets.' },
      { nl: 'Max is groot.', task: 'Compare: Max > Mimi', answer: 'Max is groter dan Mimi.' },
      { nl: 'Brussel is groot.', task: 'Compare: Brussel > Leuven', answer: 'Brussel is groter dan Leuven.' },
      { nl: 'Het is vandaag koud.', task: 'Compare: vandaag > gisteren', answer: 'Het is vandaag kouder dan gisteren.' },
      { nl: 'Bram zwemt goed.', task: 'Compare: Bram > Lotte', answer: 'Bram zwemt beter dan Lotte.' },
      { nl: 'Bram drinkt veel koffie.', task: 'Compare: Bram > Lotte', answer: 'Bram drinkt meer koffie dan Lotte.' },
      { nl: 'Lotte drinkt graag thee.', task: 'Compare: thee > koffie', answer: 'Lotte drinkt liever thee dan koffie.' },
      { nl: 'Schrijven is moeilijk.', task: 'Compare: schrijven > lezen', answer: 'Schrijven is moeilijker dan lezen.' },
    ],
    explanation: 'Only the adjective changes, and dan + the second thing goes after it. graag → liever stays in graag’s place, straight after the verb.',
  },
  {
    type: 'arrange', title: 'Faster than the bike', grammar: ['comparative', 'dan-als'],
    instruction: 'Build: “The train is faster than the bike.” Two tiles are traps.',
    nl: 'De trein is sneller dan de fiets.', en: 'The train is faster than the bike.', image: 'train', distractors: ['als', 'snelle'],
  },

  // ——— Grammar: een duurdere jas ———
  {
    type: 'grammar', title: 'een duurdere jas', grammar: ['comparative', 'adjective-e', 'de-het', 'plural'],
    body: [
      'A comparative in front of a noun is still an adjective, so the rule of lesson 4 applies to it exactly: it takes **-e** — except with **een** (or no article at all) before a singular **het-word**.',
      'de-words: *een **duurdere** jas, de **duurdere** jas, de **snellere** trein*. het-words: *een **groter** huis*, but *het **grotere** huis*. Plurals always take -e: *duurdere jassen, grotere huizen*. And a het-word with no article stays bare too: *warmer weer* (het weer).',
      'The spelling is easy: add a plain -e to the -er form, and nothing doubles: *groter → grotere, sneller → snellere, duurder → duurdere, langzamer → langzamere*.',
      '**beter** does the same: *een **betere** fiets, het betere boek*. **meer** and **minder** never change: *meer jassen, minder koffie*.',
      'The dan-part comes after the noun: *Brussel is een **grotere** stad **dan** Leuven. Lotte leest **moeilijkere** boeken **dan** Bram.*',
    ],
    tables: [
      { caption: 'de-word: always -e', rows: [
        { nl: 'een duurder[e] jas', en: 'a more expensive coat' },
        { nl: 'de duurder[e] jas', en: 'the more expensive coat' },
        { nl: 'een beter[e] fiets', en: 'a better bike' },
      ] },
      { caption: 'het-word: no -e after een', rows: [
        { nl: 'een groter huis', en: 'a bigger house' },
        { nl: 'het groter[e] huis', en: 'the bigger house' },
        { nl: 'een makkelijker boek', en: 'an easier book' },
        { nl: 'warmer weer', en: 'warmer weather' },
      ] },
      { caption: 'plural: always -e', rows: [
        { nl: 'duurder[e] jassen', en: 'more expensive coats' },
        { nl: 'moeilijker[e] boeken', en: 'more difficult books' },
      ] },
    ],
    examples: [
      { nl: 'Lotte wil een warmere jas.', en: 'Lotte wants a warmer coat.' },
      { nl: 'Bram en Lotte willen geen groter huis.', en: 'Bram and Lotte don’t want a bigger house.' },
      { nl: 'Brussel is een grotere stad dan Leuven.', en: 'Brussels is a bigger city than Leuven.' },
      { nl: 'Wij hopen op warmer weer.', en: 'We are hoping for warmer weather.' },
    ],
  },
  {
    type: 'drill', title: '-e or no -e?', grammar: ['comparative', 'adjective-e', 'de-het', 'geen'],
    instruction: 'Type the comparative of the adjective given, with or without -e. Ask two questions: de or het? een or de/het?',
    items: [
      { nl: 'Lotte wil een ___ jas.', cue: 'warm', en: 'Lotte wants a warmer coat.', answer: 'warmere' },
      { nl: 'Bram koopt de ___ jas.', cue: 'goedkoop', en: 'Bram buys the cheaper coat.', answer: 'goedkopere' },
      { nl: 'Brussel is een ___ stad dan Leuven.', cue: 'groot', answer: 'grotere' },
      { nl: 'Leuven is een ___ stad dan Gent.', cue: 'klein', answer: 'kleinere' },
      { nl: 'Bram en Lotte willen geen ___ huis.', cue: 'groot', en: 'They don’t want a bigger house.', answer: 'groter' },
      { nl: 'Het ___ huis is ook duurder.', cue: 'groot', en: 'The bigger house is also more expensive.', answer: 'grotere' },
      { nl: 'Ik neem de ___ trein.', cue: 'snel', en: 'I take the faster train.', answer: 'snellere' },
      { nl: 'Lotte leest een ___ boek.', cue: 'makkelijk', en: 'Lotte is reading an easier book.', answer: 'makkelijker' },
      { nl: 'Ik wil een ___ fiets.', cue: 'goed', en: 'I want a better bike.', answer: 'betere' },
      { nl: 'Wij hopen op ___ weer.', cue: 'warm', en: 'We are hoping for warmer weather.', answer: 'warmer' },
      { nl: 'Lotte leest ___ boeken dan Bram.', cue: 'moeilijk', answer: 'moeilijkere' },
      { nl: 'De ___ film is mooier.', cue: 'kort', en: 'The shorter film is more beautiful.', answer: 'kortere' },
    ],
    explanation: 'een groter huis, een makkelijker boek, warmer weer: a het-word without de/het, so no -e. Everything else: -e. goed → beter → een betere fiets.',
  },

  // ——— Grammar: the superlative ———
  {
    type: 'grammar', title: 'The biggest: het grootst', grammar: ['superlative', 'adjective-e', 'de-het'],
    body: [
      'The superlative adds **-st** to the adjective itself — not to the comparative: *groot → **grootst**, snel → **snelst**, duur → **duurst**, langzaam → **langzaamst**, goedkoop → **goedkoopst***. No syllable is added, so the adjective keeps its spelling: no double l in snelst, no d in duurst, oo and aa stay.',
      'The irregular three: **goed → beter → best**, **veel → meer → meest**, **graag → liever → liefst**.',
      '**Before a noun** a superlative always takes **-e**, because it always comes with de or het — there is no “een grootste”: ***de** grootste stad, **het** grootste huis, **de** snelste trein, **de** beste jas*.',
      '**After zijn, and after any other verb**, Dutch says **het + -st**: *Brussel is **het grootst**. De trein gaat **het snelst**. Bram zwemt **het best**. Ik drink **het liefst** thee.* This het means “most of all” and points at nothing; even a de-word gets it. You will also hear *het grootste, het snelste* — both are correct and the answers accept them. When you mean “the biggest one”, use the article of the noun you have in mind: *Brussel is **de grootste** (stad).*',
      '**het meest** and **het liefst** go with verbs: *Lotte leest **het meest**. Wat doe jij **het liefst**?* — “What do you like doing most?” And **de meeste** goes with a plural noun: *de meeste dagen*, most days.',
      'Dutch, like English, uses the superlative when there are three or more: *Wat is het snelst: de trein, de auto of de fiets?* With two, use the comparative: *Wie is groter: Bram of Lotte?*',
    ],
    tables: [
      { caption: 'adjective · comparative · superlative', rows: [
        { nl: 'groot · groter · groot[st]', en: 'big · bigger · biggest' },
        { nl: 'snel · sneller · snel[st]', en: 'fast · faster · fastest' },
        { nl: 'duur · duurder · duur[st]', en: 'expensive · more · most expensive' },
        { nl: 'goedkoop · goedkoper · goedkoop[st]', en: 'cheap · cheaper · cheapest' },
        { nl: 'langzaam · langzamer · langzaam[st]', en: 'slow · slower · slowest' },
        { nl: 'goed · beter · [best]', en: 'good · better · best' },
        { nl: 'veel · meer · [meest]', en: 'much · more · most' },
        { nl: 'graag · liever · [liefst]', en: 'like to · rather · most of all' },
      ] },
      { caption: 'two ways to use it', rows: [
        { nl: 'Brussel is [de grootste] stad.', en: 'Brussels is the biggest city — before a noun: -e.' },
        { nl: 'Brussel is [het grootst].', en: 'Brussels is the biggest — after zijn: het + -st.' },
        { nl: 'De trein gaat [het snelst].', en: 'The train goes fastest.' },
        { nl: 'Ik drink [het liefst] thee.', en: 'I like drinking tea best.' },
      ] },
    ],
    examples: [
      { nl: 'Leuven, Gent en Brussel: Leuven is het kleinst.', en: 'Leuven, Ghent and Brussels: Leuven is the smallest.' },
      { nl: 'Max is de grootste hond in de straat.', en: 'Max is the biggest dog in the street.' },
      { nl: 'Wie zwemt het best?', en: 'Who swims best?' },
      { nl: 'Lotte leest het meest.', en: 'Lotte reads the most.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Make the superlative', grammar: ['superlative'],
    instruction: 'Type the superlative, without het or -e: groot → grootst. Watch the three irregular ones at the end.',
    items: [
      { label: 'groot', gloss: 'biggest', answer: 'grootst' },
      { label: 'klein', gloss: 'smallest', answer: 'kleinst' },
      { label: 'oud', gloss: 'oldest', answer: 'oudst' },
      { label: 'snel', gloss: 'fastest', answer: 'snelst' },
      { label: 'langzaam', gloss: 'slowest', answer: 'langzaamst' },
      { label: 'duur', gloss: 'most expensive', answer: 'duurst' },
      { label: 'goedkoop', gloss: 'cheapest', answer: 'goedkoopst' },
      { label: 'warm', gloss: 'warmest', answer: 'warmst' },
      { label: 'koud', gloss: 'coldest', answer: 'koudst' },
      { label: 'moeilijk', gloss: 'most difficult', answer: 'moeilijkst' },
      { label: 'goed', gloss: 'best', answer: 'best' },
      { label: 'veel', gloss: 'most', answer: 'meest' },
      { label: 'graag', gloss: 'most of all (like)', answer: 'liefst' },
    ],
    explanation: 'The superlative is built on the plain adjective: snel → snelst (not snellst), duur → duurst, goedkoop → goedkoopst. best, meest, liefst: learn them as words.',
  },
  {
    type: 'drill', title: 'de grootste, het grootst', grammar: ['superlative', 'adjective-e', 'separable', 'question-word'],
    instruction: 'Type the superlative of the word given — with -e before a noun, without -e after “het” at the end.',
    items: [
      { nl: 'Brussel is de ___ stad: groter dan Gent en groter dan Leuven.', cue: 'groot', answer: 'grootste' },
      { nl: 'Wat is het ___: de trein, de auto of de fiets?', cue: 'snel', answer: 'snelst', accept: ['snelste'] },
      { nl: 'De fiets is het ___.', cue: 'goedkoop', answer: 'goedkoopst', accept: ['goedkoopste'] },
      { nl: 'Een slak is het ___.', cue: 'langzaam', answer: 'langzaamst', accept: ['langzaamste'] },
      { nl: 'Bram zwemt het ___.', cue: 'goed', answer: 'best', accept: ['beste'] },
      { nl: 'Ik drink het ___ thee.', cue: 'graag', answer: 'liefst', accept: ['liefste'] },
      { nl: 'Lotte koopt de ___ jas niet.', cue: 'duur', answer: 'duurste' },
      { nl: 'Wie kookt het ___: Bram, Lotte of zijn moeder?', cue: 'goed', answer: 'best', accept: ['beste'] },
      { nl: 'Lotte neemt haar ___ jas mee.', cue: 'warm', en: 'Lotte takes her warmest coat along.', answer: 'warmste' },
    ],
    explanation: 'de grootste stad, de duurste jas, haar warmste jas: before a noun, always -e. Ending on het … : grootst, snelst, best, liefst (the -e is allowed there too). meest has no -e after het.',
  },
  {
    type: 'drill', title: 'Answer with the superlative', grammar: ['superlative', 'question-word', 'wie-hoe'],
    instruction: 'Answer in a full sentence, with het + -st. Three or more things: the superlative.',
    items: [
      { nl: 'Wat is het snelst: de trein, de auto of de fiets?', answer: 'De trein is het snelst.', accept: ['De trein is het snelste.', 'De trein is de snelste.'] },
      { nl: 'Wat is het makkelijkst: lezen, schrijven of spreken?', answer: 'Lezen is het makkelijkst.', accept: ['Lezen is het makkelijkste.'] },
      { nl: 'Wat is het grootst: Brussel, Gent of Leuven?', answer: 'Brussel is het grootst.', accept: ['Brussel is het grootste.', 'Brussel is de grootste.', 'Brussel is de grootste stad.'] },
      { nl: 'Wat is het kleinst: Brussel, Gent of Leuven?', answer: 'Leuven is het kleinst.', accept: ['Leuven is het kleinste.', 'Leuven is de kleinste.', 'Leuven is de kleinste stad.'] },
      { nl: 'Wie is het oudst: Bram, Noor of de oude man?', answer: 'De oude man is het oudst.', accept: ['De oude man is het oudste.', 'De oude man is de oudste.'] },
      { nl: 'Wie is het jongst: Bram, Lotte of Noor?', answer: 'Noor is het jongst.', accept: ['Noor is het jongste.', 'Noor is de jongste.'] },
      { nl: 'Wat is het langzaamst: een slak, een kat of een hond?', answer: 'Een slak is het langzaamst.', accept: ['Een slak is het langzaamste.', 'De slak is het langzaamst.', 'De slak is het langzaamste.', 'Een slak is de langzaamste.', 'De slak is de langzaamste.'] },
      { nl: 'Wat drink jij het liefst: koffie, thee of water?', answer: 'Ik drink het liefst thee.', accept: ['Ik drink het liefst koffie.', 'Ik drink het liefst water.', 'Ik drink het liefste thee.', 'Ik drink het liefste koffie.', 'Ik drink het liefste water.', 'Het liefst drink ik thee.', 'Het liefst drink ik koffie.', 'Het liefst drink ik water.'] },
    ],
    explanation: 'The oude man is the oldest, Noor (five) the youngest, Leuven the smallest of the three cities. “Wat drink jij het liefst?” has no one right answer — any of the three is fine.',
  },
  {
    type: 'arrange', title: 'Fastest and cheapest', grammar: ['superlative', 'geen-niet'],
    instruction: 'Build: “The train is the fastest, but the bike is the cheapest.” Two tiles are traps.',
    nl: 'De trein is het snelst, maar de fiets is het goedkoopst.', en: 'The train is the fastest, but the bike is the cheapest.', image: 'bike', distractors: ['snelste', 'meest'],
  },

  // ——— Grammar: even … als, niet zo … als ———
  {
    type: 'grammar', title: 'even groot als, niet zo groot als', grammar: ['dan-als', 'comparative', 'verb-final', 'infinitive-end', 'perfect-hebben'],
    body: [
      '**even … als** says two things are equal: *Mijn jas is **even** warm **als** jouw jas. Vandaag is het **even** koud **als** gisteren.* The adjective in between is the plain form, without -er.',
      '**niet zo … als** means “not as … as”. It is the soft, polite way to say that something is less: *Lotte is **niet zo** lang **als** Bram* sounds kinder than *Lotte is kleiner dan Bram*. *Leuven is niet zo groot als Brussel.* On its own, zo means “so”: *Het is zo koud!*',
      '**dan or als?** After a comparative — every -er form, and beter, meer, liever, minder — comes **dan**. After **even** and **zo** comes **als**: *groter dan*, but *even groot als, niet zo groot als*. Many Dutch speakers say “groter als”, and you will hear it; in writing, in an exam and at university it counts as a mistake.',
      'Both small words now have two jobs. **dan** is “then” (lesson 6) and “than”. **als** is “if / when” (lesson 12), which opens a clause with its verb at the end — and “as” in *even … als*, which is only a linking word with no verb of its own.',
      '**The dan-part goes last.** When a sentence has a verb at the end — an infinitive, a participle, or the verb of a subordinate clause — the part with dan or als usually comes after it: *Lotte heeft meer boeken gelezen **dan Bram**. Max kan sneller lopen **dan ik**. Ik denk dat de trein sneller is **dan de fiets**.* Putting it in front of the verb (*… sneller dan de fiets is*) is not wrong, but it sounds heavy; answers accept both orders.',
    ],
    tables: [
      { caption: 'equal and not equal', rows: [
        { nl: 'Mijn jas is [even] warm [als] jouw jas.', en: 'My coat is as warm as your coat.' },
        { nl: 'Lotte is [niet zo] lang [als] Bram.', en: 'Lotte is not as tall as Bram.' },
        { nl: 'Bram is lang[er dan] Lotte.', en: 'Bram is taller than Lotte.' },
      ] },
      { caption: 'the dan-part after the final verb', rows: [
        { nl: 'Lotte heeft meer boeken gelezen [dan Bram].', en: 'Lotte has read more books than Bram.' },
        { nl: 'Max kan sneller lopen [dan ik].', en: 'Max can walk faster than me.' },
        { nl: 'Ik denk dat de trein sneller is [dan de fiets].', en: 'I think the train is faster than the bike.' },
      ] },
    ],
    examples: [
      { nl: 'Leuven is niet zo groot als Brussel.', en: 'Leuven is not as big as Brussels.' },
      { nl: 'Vandaag is het even koud als gisteren.', en: 'Today it is as cold as yesterday.' },
      { nl: 'Het is zo koud!', en: 'It is so cold!' },
    ],
  },
  {
    type: 'drill', title: 'dan or als?', grammar: ['dan-als'], choices: ['dan', 'als'],
    instruction: 'An -er form (or beter, meer, liever) takes dan; even and zo take als.',
    items: [
      { nl: 'Max is groter ___ Mimi.', answer: 'dan' },
      { nl: 'Mijn fiets is even oud ___ jouw fiets.', answer: 'als' },
      { nl: 'Lotte is niet zo lang ___ Bram.', answer: 'als' },
      { nl: 'De fiets is goedkoper ___ de auto.', answer: 'dan' },
      { nl: 'Leuven is niet zo groot ___ Brussel.', answer: 'als' },
      { nl: 'Bram drinkt meer koffie ___ Lotte.', answer: 'dan' },
      { nl: 'Vandaag is het even koud ___ gisteren.', answer: 'als' },
      { nl: 'Ik drink liever thee ___ koffie.', answer: 'dan' },
      { nl: 'Een slak is niet zo snel ___ Mimi.', answer: 'als' },
    ],
    explanation: '-er → dan. even / zo → als. Look at the word before the adjective: if it is even or zo, als follows.',
  },
  {
    type: 'drill', title: 'Say it softly, say it equal', grammar: ['dan-als', 'comparative', 'possessives'],
    instruction: 'Rewrite as the task says. With niet zo … als and even … als the adjective loses its -er.',
    items: [
      { nl: 'Lotte is kleiner dan Bram.', task: 'Use niet zo … als, with lang', answer: 'Lotte is niet zo lang als Bram.' },
      { nl: 'Leuven is kleiner dan Brussel.', task: 'Use niet zo … als, with groot', answer: 'Leuven is niet zo groot als Brussel.' },
      { nl: 'De fiets is langzamer dan de trein.', task: 'Use niet zo … als, with snel', answer: 'De fiets is niet zo snel als de trein.' },
      { nl: 'De fiets is goedkoper dan de auto.', task: 'Use niet zo … als, with duur', answer: 'De fiets is niet zo duur als de auto.' },
      { nl: 'Schrijven is moeilijker dan lezen.', task: 'Start with “Lezen”; use niet zo … als, with moeilijk', answer: 'Lezen is niet zo moeilijk als schrijven.' },
      { nl: 'Vandaag is het koud, en gisteren ook.', task: 'Use even … als', answer: 'Vandaag is het even koud als gisteren.', accept: ['Het is vandaag even koud als gisteren.'] },
      { nl: 'Mijn jas is warm, en jouw jas ook.', task: 'Use even … als', answer: 'Mijn jas is even warm als jouw jas.', accept: ['Jouw jas is even warm als mijn jas.', 'Mijn jas is even warm als je jas.'] },
      { nl: 'Gent is mooi, en Leuven ook.', task: 'Use even … als', answer: 'Gent is even mooi als Leuven.', accept: ['Leuven is even mooi als Gent.'] },
    ],
    explanation: 'niet zo lang als, even warm als — the plain adjective. Lotte is kleiner dan Bram and Lotte is niet zo lang als Bram say the same thing; the second is softer.',
  },
  {
    type: 'drill', title: 'The dan-part goes last', grammar: ['dan-als', 'comparative', 'verb-final', 'want-omdat', 'dat-clause', 'perfect-hebben', 'modals', 'infinitive-end', 'hij-het-things'],
    instruction: 'Rewrite as the task says. When a verb stands at the end, put the dan-part after it (the other order is accepted too).',
    items: [
      { nl: 'Lotte heeft veel boeken gelezen.', task: 'Compare: Lotte > Bram', answer: 'Lotte heeft meer boeken gelezen dan Bram.' },
      { nl: 'Max kan snel lopen.', task: 'Compare: Max > Bram', answer: 'Max kan sneller lopen dan Bram.', accept: ['Max kan sneller dan Bram lopen.'] },
      { nl: 'De trein is snel.', task: 'Start with “Ik denk dat”; compare with de fiets', answer: 'Ik denk dat de trein sneller is dan de fiets.', accept: ['Ik denk dat de trein sneller dan de fiets is.'] },
      { nl: 'Het is vandaag koud.', task: 'Start with “Lotte zegt dat”; compare with gisteren', answer: 'Lotte zegt dat het vandaag kouder is dan gisteren.', accept: ['Lotte zegt dat het vandaag kouder dan gisteren is.'] },
      { nl: 'Bram gaat met de trein. De trein is snel.', task: 'Join with omdat; use hij for the train; compare with de auto', answer: 'Bram gaat met de trein, omdat hij sneller is dan de auto.', accept: ['Bram gaat met de trein, omdat hij sneller dan de auto is.', 'Bram gaat met de trein, omdat de trein sneller is dan de auto.', 'Bram gaat met de trein, omdat de trein sneller dan de auto is.'] },
      { nl: 'Lotte neemt de fiets. De fiets is goedkoop.', task: 'Join with omdat; use hij for the bike; compare with de trein', answer: 'Lotte neemt de fiets, omdat hij goedkoper is dan de trein.', accept: ['Lotte neemt de fiets, omdat hij goedkoper dan de trein is.', 'Lotte neemt de fiets, omdat de fiets goedkoper is dan de trein.', 'Lotte neemt de fiets, omdat de fiets goedkoper dan de trein is.'] },
      { nl: 'Jij spreekt goed Nederlands.', task: 'Start with “Ik vind dat”; compare: jij > ik', answer: 'Ik vind dat jij beter Nederlands spreekt dan ik.', accept: ['Ik vind dat jij beter Nederlands dan ik spreekt.'] },
      { nl: 'Het examen is moeilijk.', task: 'Start with “Lotte hoopt dat”; use niet zo … als, compare with het boek', answer: 'Lotte hoopt dat het examen niet zo moeilijk is als het boek.', accept: ['Lotte hoopt dat het examen niet zo moeilijk als het boek is.'] },
    ],
    explanation: 'meer boeken gelezen dan Bram, sneller lopen dan Bram, sneller is dan de fiets: the verb closes the clause, and the comparison follows it. de trein and de fiets are de-words, so: omdat hij …',
  },
  {
    type: 'arrange', title: 'Not as tall', grammar: ['dan-als', 'niet'],
    instruction: 'Build: “Lotte is not as tall as Bram.” Two tiles are traps.',
    nl: 'Lotte is niet zo lang als Bram.', en: 'Lotte is not as tall as Bram.', image: 'couple-talking', distractors: ['dan', 'langer'],
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'observe', title: 'Old words, new comparisons', grammar: ['comparative', 'superlative', 'days-op-om', 'possessives', 'er-is-zijn', 'perfect-hebben', 'separable-together'],
    instruction: 'Everything you know about the house, the family and the week — now compared. Listen, and say every sentence out loud.',
    cards: [
      { nl: 'De boom in onze tuin is groter dan het huis.', en: 'The tree in our garden is taller than the house.', image: 'garden' },
      { nl: 'Het raam in de keuken is groter dan de deur.', en: 'The window in the kitchen is bigger than the door.', image: 'kitchen' },
      { nl: 'Bram heeft een bank gemaakt. Zijn bank is mooier dan de bank in het park.', en: 'Bram has made a bench. His bench is more beautiful than the bench in the park.', image: 'man-making' },
      { nl: 'Het bed in de grote kamer is langer dan Bram.', en: 'The bed in the big room is longer than Bram.', image: 'bed' },
      { nl: 'Er zijn meer stoelen dan tafels in de keuken: vier stoelen en één tafel.', en: 'There are more chairs than tables in the kitchen: four chairs and one table.', image: 'chairs-four' },
      { nl: 'Noor is vijf jaar. Zij is het jongste kind in de straat.', en: 'Noor is five. She is the youngest child in the street.', image: 'child' },
      { nl: 'Max is een lieve hond, en Noor vindt Mimi even lief als Max.', en: 'Max is a sweet dog, and Noor thinks Mimi is as sweet as Max.', image: 'dog-big' },
      { nl: 'Zijn vader is twee jaar ouder dan zijn moeder. Zijn familie woont in Gent, ook zijn zus Sofie.', en: 'His father is two years older than his mother. His family lives in Ghent, his sister Sofie too.', image: 'family' },
      { nl: 'Haar broer Tom woont in Antwerpen, een grotere stad dan Leuven.', en: 'Her brother Tom lives in Antwerp, a bigger city than Leuven.', image: 'brother' },
      { nl: 'Emma is haar beste vriendin, en Jonas is zijn beste vriend.', en: 'Emma is her best friend, and Jonas is his best friend.', image: 'friends' },
      { nl: 'Op maandag, dinsdag, woensdag en donderdag werkt Bram in Brussel. Dan is zijn dag langer.', en: 'On Monday, Tuesday, Wednesday and Thursday Bram works in Brussels. Then his day is longer.', image: 'man-working' },
      { nl: 'Als het koud is, is een warm ontbijt het best. En opstaan is makkelijker als de zon schijnt.', en: 'When it is cold, a warm breakfast is best. And getting up is easier when the sun is shining.', image: 'breakfast' },
      { nl: 'Uitgaan is in Leuven goedkoper dan in Brussel.', en: 'Going out is cheaper in Leuven than in Brussels.', image: 'night-out' },
    ],
    note: 'een warm ontbijt: het ontbijt is a het-word, so no -e after een. het jongste kind: a superlative before a noun always has -e. Dan is zijn dag langer: dan = then, first in the sentence, so the verb comes straight after it.',
  },
  {
    type: 'drill', title: 'Old words, compared', grammar: ['comparative', 'superlative', 'dan-als', 'hebben', 'gaan', 'days-op-om', 'want-omdat', 'verb-final', 'modals', 'separable-perfect', 'separable-together', 'dat-clause'],
    instruction: 'Translate. Every sentence brings back words from earlier lessons. When the English names want or omdat, use that one.',
    items: [
      { en: 'Bram is tired, because he works longer than Lotte. (use omdat)', answer: 'Bram is moe, omdat hij langer werkt dan Lotte.', accept: ['Bram is moe, omdat hij langer dan Lotte werkt.'] },
      { en: 'Noor is ill; she is not as happy as yesterday.', answer: 'Noor is ziek; zij is niet zo blij als gisteren.', accept: ['Noor is ziek, zij is niet zo blij als gisteren.', 'Noor is ziek. Zij is niet zo blij als gisteren.'] },
      { en: 'Bram has taken his key and his bag along.', answer: 'Bram heeft zijn sleutel en zijn tas meegenomen.' },
      { en: 'My new phone is smaller than my old phone.', answer: 'Mijn nieuwe telefoon is kleiner dan mijn oude telefoon.', accept: ['Mijn nieuwe telefoon is kleiner dan mijn oude.'] },
      { en: 'Lotte would rather eat an apple than bread with cheese.', answer: 'Lotte eet liever een appel dan brood met kaas.' },
      { en: 'Water is cheaper than coffee.', answer: 'Water is goedkoper dan koffie.' },
      { en: 'The school is bigger than the station.', answer: 'De school is groter dan het station.' },
      { en: 'Her name is longer than his name.', answer: 'Haar naam is langer dan zijn naam.' },
      { en: 'The old man talks more slowly than Noor.', answer: 'De oude man praat langzamer dan Noor.' },
      { en: 'May I see the cheaper coat?', answer: 'Mag ik de goedkopere jas zien?' },
      { en: 'Bram helps the old man, because the old man walks more slowly. (use want)', answer: 'Bram helpt de oude man, want de oude man loopt langzamer.', accept: ['Bram helpt de oude man, want hij loopt langzamer.'] },
      { en: 'Bram asks how much the long coat costs.', answer: 'Bram vraagt hoeveel de lange jas kost.' },
      { en: 'Lotte studies more than Bram.', answer: 'Lotte leert meer dan Bram.' },
      { en: 'Bram wants to ring his mother, because it is warmer in Ghent. (use want)', answer: 'Bram wil zijn moeder opbellen, want in Gent is het warmer.', accept: ['Bram wil zijn moeder opbellen, want het is in Gent warmer.', 'Bram wil zijn moeder opbellen, want het is warmer in Gent.'] },
      { en: 'On Sunday we are going to Ghent on the fastest train.', answer: 'Op zondag gaan wij met de snelste trein naar Gent.', accept: ['Zondag gaan wij met de snelste trein naar Gent.'] },
      { en: 'Yesterday it snowed more in Leuven than in Ghent.', answer: 'Gisteren heeft het in Leuven meer gesneeuwd dan in Gent.', accept: ['Het heeft gisteren in Leuven meer gesneeuwd dan in Gent.'] },
    ],
    explanation: 'langer werkt dan Lotte: in the omdat-clause the verb goes to the end, and the dan-part follows it. de goedkopere jas: de jas, so -e. meegenomen, opbellen: the particle is back on the verb. Op zondag: op + day; the verb gaan stays second.',
  },
  {
    type: 'grammar', title: 'Three small verbs: kosten, sneeuwen, schijnen', grammar: ['present-regular', 'participle', 'perfect-hebben', 'question-word', 'numbers'],
    body: [
      '**kosten** (to cost) is regular: *het kost, ze kosten, het heeft gekost*. The question you will ask in every Belgian shop is **Hoeveel kost …?** — *Hoeveel kost de jas? Hoeveel kosten de jassen?* A plural subject takes the plural verb.',
      'Prices: after a number, **euro** stays singular — *drie euro, twaalf euro*, never with an -s. You can also say **de prijs** (the price): *De prijs is goed.*',
      '**sneeuwen** (to snow) works exactly like regenen: its only subject is **het**. *Het sneeuwt. Sneeuwt het? Het heeft gesneeuwd.* With al and a time: *Het sneeuwt al twee dagen* — it has been snowing for two days. The noun is **de sneeuw**: *Noor speelt in de sneeuw.*',
      '**schijnen** (to shine) is what the sun does: *De zon schijnt.* Its participle is strong: *De zon heeft vandaag niet **geschenen**.*',
      '**het weer** is the weather: *Hoe is het weer? Het is mooi weer* — no -e, because weer is a het-word without an article. And **weer** is also “again”: *Het regent weer!* The sentence always makes clear which one it is.',
      '**buiten** is “outside”: *Buiten is het koud.* With a movement it is **naar buiten**: *Max wil naar buiten.*',
    ],
    tables: [
      { caption: 'kosten', rows: [
        { nl: 'Het boek kos[t] twaalf euro.', en: 'The book costs twelve euros.' },
        { nl: 'De jassen kost[en] veel.', en: 'The coats cost a lot.' },
        { nl: 'Hoeveel heeft de fiets [gekost]?', en: 'How much did the bike cost?' },
      ] },
      { caption: 'the weather', rows: [
        { nl: 'Het sneeuw[t].', en: 'It is snowing.' },
        { nl: 'Het heeft [gesneeuwd].', en: 'It has snowed.' },
        { nl: 'De zon schijn[t].', en: 'The sun is shining.' },
        { nl: 'De zon heeft [geschenen].', en: 'The sun has shone.' },
        { nl: 'Het regen[t] weer.', en: 'It is raining again.' },
      ] },
    ],
    examples: [
      { nl: 'Hoeveel kost een koffie? — Drie euro.', en: 'How much is a coffee? — Three euros.' },
      { nl: 'Buiten is het zo koud!', en: 'It is so cold outside!' },
      { nl: 'Max wil altijd naar buiten, ook als het sneeuwt.', en: 'Max always wants to go out, even when it snows.' },
    ],
  },
  {
    type: 'drill', title: 'Prices and weather', grammar: ['present-regular', 'participle', 'perfect-hebben', 'als-inversion', 'yes-no-question'],
    instruction: 'Type the missing word. The infinitive cue tells you which verb.',
    items: [
      { nl: 'Hoeveel ___ de lange jas?', cue: 'kosten', answer: 'kost' },
      { nl: 'Een koffie ___ drie euro.', cue: 'kosten', answer: 'kost' },
      { nl: 'De nieuwe fiets heeft veel ___.', cue: 'kosten', answer: 'gekost' },
      { nl: 'Het ___ al twee dagen.', cue: 'sneeuwen', answer: 'sneeuwt' },
      { nl: 'De zon ___, maar het is nog koud.', cue: 'schijnen', answer: 'schijnt' },
      { nl: 'De zon heeft vandaag niet ___.', cue: 'schijnen', answer: 'geschenen' },
      { nl: 'Als het ___, speelt Noor buiten in de sneeuw.', cue: 'sneeuwen', answer: 'sneeuwt' },
      { nl: '___ het nog?', cue: 'regenen', en: 'Is it still raining?', answer: 'Regent' },
      { nl: 'Het regent ___!', en: 'It is raining again!', answer: 'weer' },
    ],
    explanation: 'kost, kosten, gekost — regular. het sneeuwt, het heeft gesneeuwd — like het regent. The sun has geschenen: a strong participle, like geschreven.',
  },
  {
    type: 'drill', layout: 'table', title: 'Every verb you know, part one', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'zijn', 'hebben', 'gaan', 'subject-pronouns', 'dt-rule', 'modals'],
    instruction: 'Verbs from lessons 1 to 9, mixed. The small word under each person is the verb. Type the form.',
    items: [
      { label: 'ik', gloss: 'zijn', answer: 'ben' },
      { label: 'jij', gloss: 'hebben', answer: 'hebt' },
      { label: 'zij', gloss: 'she · gaan', answer: 'gaat' },
      { label: 'hij', gloss: 'komen', answer: 'komt' },
      { label: 'hij', gloss: 'lopen', answer: 'loopt' },
      { label: 'zij', gloss: 'she · zitten', answer: 'zit' },
      { label: 'jij', gloss: 'slapen', answer: 'slaapt' },
      { label: 'ik', gloss: 'koken', answer: 'kook' },
      { label: 'jij', gloss: 'praten', answer: 'praat' },
      { label: 'ik', gloss: 'lezen', answer: 'lees' },
      { label: 'hij', gloss: 'eten', answer: 'eet' },
      { label: 'ik', gloss: 'schrijven', answer: 'schrijf' },
      { label: 'hij', gloss: 'heten', answer: 'heet' },
      { label: 'jij', gloss: 'kunnen', answer: 'kunt' },
      { label: 'hij', gloss: 'willen', answer: 'wil' },
      { label: 'jij', gloss: 'mogen', answer: 'mag' },
      { label: 'zij', gloss: 'she · zwemmen', answer: 'zwemt' },
      { label: 'ik', gloss: 'spreken', answer: 'spreek' },
      { label: 'jij', gloss: 'rijden', answer: 'rijdt' },
    ],
    explanation: 'The traps: zit (one t), loopt and slaapt (double vowel back), lees and schrijf (z → s, v → f), praat, eet and heet (no second t), jij kunt but jij mag, hij wil without t, jij rijdt (d + t).',
  },
  {
    type: 'drill', layout: 'table', title: 'Every verb you know, part two', grammar: ['present-regular', 'separable', 'dt-rule', 'subject-pronouns'],
    instruction: 'Lessons 11 to 14. A separable verb needs two words: hij staat op.',
    items: [
      { label: 'ik', gloss: 'maken', answer: 'maak' },
      { label: 'hij', gloss: 'kopen', answer: 'koopt' },
      { label: 'jij', gloss: 'zien', answer: 'ziet' },
      { label: 'jij', gloss: 'vinden', answer: 'vindt' },
      { label: 'zij', gloss: 'she · zeggen', answer: 'zegt' },
      { label: 'hij', gloss: 'weten', answer: 'weet' },
      { label: 'ik', gloss: 'hopen', answer: 'hoop' },
      { label: 'jullie', gloss: 'begrijpen', answer: 'begrijpen' },
      { label: 'zij', gloss: 'she · vragen', answer: 'vraagt' },
      { label: 'ik', gloss: 'staan', answer: 'sta' },
      { label: 'hij', gloss: 'opstaan', answer: 'staat op' },
      { label: 'jij', gloss: 'bellen', answer: 'belt' },
      { label: 'zij', gloss: 'they · opbellen', answer: 'bellen op' },
      { label: 'ik', gloss: 'nemen', answer: 'neem' },
      { label: 'jij', gloss: 'meenemen', answer: 'neemt mee' },
      { label: 'de trein', gloss: 'aankomen', answer: 'komt aan' },
      { label: 'wij', gloss: 'uitgaan', answer: 'gaan uit' },
      { label: 'de jas', gloss: 'kosten', answer: 'kost' },
      { label: 'het', gloss: 'sneeuwen', answer: 'sneeuwt' },
      { label: 'de zon', gloss: 'schijnen', answer: 'schijnt' },
    ],
    explanation: 'jij vindt: d + t. hij weet: no second t. In a main clause the particle leaves: staat op, bellen op, neemt mee, komt aan, gaan uit.',
  },
  {
    type: 'drill', layout: 'table', title: 'Every participle', grammar: ['perfect-hebben', 'perfect-zijn', 'participle', 'separable-perfect'],
    instruction: 'Type the perfect: the form of hebben or zijn, then the participle. Movement and change take zijn.',
    items: [
      { label: 'ik', gloss: 'opstaan', answer: 'ben opgestaan' },
      { label: 'hij', gloss: 'meenemen', answer: 'heeft meegenomen' },
      { label: 'de trein', gloss: 'aankomen', answer: 'is aangekomen' },
      { label: 'wij', gloss: 'uitgaan', answer: 'zijn uitgegaan' },
      { label: 'jij', gloss: 'opbellen', answer: 'hebt opgebeld' },
      { label: 'zij', gloss: 'she · lezen', answer: 'heeft gelezen' },
      { label: 'wij', gloss: 'gaan', answer: 'zijn gegaan' },
      { label: 'hij', gloss: 'rijden', answer: 'heeft gereden' },
      { label: 'jij', gloss: 'zwemmen', answer: 'hebt gezwommen' },
      { label: 'het', gloss: 'sneeuwen', answer: 'heeft gesneeuwd' },
      { label: 'de zon', gloss: 'schijnen', answer: 'heeft geschenen' },
      { label: 'hij', gloss: 'komen', answer: 'is gekomen' },
      { label: 'ik', gloss: 'begrijpen', answer: 'heb begrepen' },
      { label: 'zij', gloss: 'they · drinken', answer: 'hebben gedronken' },
    ],
    explanation: 'opgestaan, meegenomen, aangekomen, uitgegaan, opgebeld: ge- between the particle and the verb. opstaan, aankomen, uitgaan, gaan and komen take zijn. begrepen: no ge- after be-.',
  },
  {
    type: 'drill', title: 'Separable verbs, compared', grammar: ['separable', 'separable-together', 'separable-perfect', 'comparative', 'superlative', 'verb-final', 'time-place'],
    instruction: 'Type the missing word: a verb form (the cue is its infinitive) or a comparative. In a main clause the particle waits at the end; with a modal, in a subclause or in the perfect it is back on the verb.',
    items: [
      { nl: 'Als het koud is, ___ Bram niet graag op.', cue: 'opstaan', answer: 'staat' },
      { nl: 'Opstaan is ___ als het koud is.', cue: 'moeilijk', answer: 'moeilijker' },
      { nl: 'Bram moet morgen vroeg ___.', cue: 'opstaan', answer: 'opstaan' },
      { nl: 'Lotte ___ haar warmste jas mee.', cue: 'meenemen', answer: 'neemt' },
      { nl: 'Heb jij een warme jas ___?', cue: 'meenemen', answer: 'meegenomen' },
      { nl: 'De snelle trein ___ om acht uur in Brussel aan.', cue: 'aankomen', answer: 'komt' },
      { nl: 'Ik weet dat de langzame trein om negen uur ___.', cue: 'aankomen', answer: 'aankomt' },
      { nl: 'De trein is vandaag laat ___, omdat het sneeuwt.', cue: 'aankomen', answer: 'aangekomen' },
      { nl: 'Bram ___ zijn moeder op, want in Gent is het warmer.', cue: 'opbellen', answer: 'belt' },
      { nl: 'Bram heeft zijn moeder in Gent ___.', cue: 'opbellen', answer: 'opgebeld' },
      { nl: 'Neem jij de trein? — Nee, ik ___ liever de fiets.', cue: 'nemen', answer: 'neem' },
      { nl: 'Uitgaan is in Brussel ___ dan in Leuven.', cue: 'duur', answer: 'duurder' },
      { nl: 'Wij willen vrijdag met Emma en Jonas ___.', cue: 'uitgaan', answer: 'uitgaan' },
      { nl: 'Bram eet ’s ochtends liever een groot ___ dan een klein.', en: 'In the morning Bram would rather eat a big breakfast than a small one.', answer: 'ontbijt' },
    ],
    explanation: 'Bram staat op, Lotte neemt mee, de trein komt aan: particle at the end. moet opstaan, dat … aankomt, is aangekomen, heeft opgebeld: together again. een groot ontbijt — het ontbijt, so no -e after een.',
  },
  {
    type: 'drill', title: 'Everything so far, compared', grammar: ['plural', 'numbers', 'er-is-zijn', 'possessives', 'wie-hoe', 'clock-time', 'days-op-om', 'adjective-e', 'geen-niet', 'geen', 'adverb-position', 'hij-het-things', 'spelling-z-s', 'dit-is', 'de-het'],
    instruction: 'Type the missing word. Every grammar point of the book is in here — now inside comparisons.',
    items: [
      { nl: 'De ___ in de keuken zijn ouder dan de tafel.', cue: 'stoel', answer: 'stoelen' },
      { nl: 'De oude man heeft ___ katten, en Mimi is kleiner dan zij.', en: 'The old man has two cats, and Mimi is smaller than them.', answer: 'twee' },
      { nl: 'Bram zegt dat ___ vader ouder is dan zijn moeder.', en: 'his father', answer: 'zijn' },
      { nl: 'Is ___ tuin groter dan onze tuin?', en: 'your garden (one person)', answer: 'jouw' },
      { nl: '___ is groter: Bram of Lotte?', en: 'Who is taller: Bram or Lotte?', answer: 'Wie' },
      { nl: 'De snelle trein komt ___ negen uur.', cue: 'op / om', answer: 'om' },
      { nl: 'Het is ___ acht, en de trein is nog niet aangekomen.', en: 'It is half past seven, and the train has not arrived yet.', answer: 'half' },
      { nl: 'Lotte heeft een ___ jas gekocht.', cue: 'warm', answer: 'warme' },
      { nl: 'Bram heeft ___ auto; hij gaat met de trein, en de trein is sneller.', en: 'Bram has no car; he goes by train, and the train is faster.', answer: 'geen' },
      { nl: 'Lotte drinkt ___ koffie; zij drinkt liever thee.', en: 'Lotte never drinks coffee; she would rather drink tea.', answer: 'nooit' },
      { nl: 'De trein is snel. Ik denk dat ___ sneller is dan de auto.', cue: 'hij / het', answer: 'hij' },
      { nl: 'Het weer is mooi. Ik hoop dat ___ morgen nog mooier is.', cue: 'hij / het', answer: 'het' },
      { nl: 'Lotte ___ meer dan Bram.', cue: 'lezen', answer: 'leest' },
      { nl: 'Ik ___ beter dan ik spreek.', cue: 'schrijven', en: 'I write better than I speak.', answer: 'schrijf' },
      { image: 'snail', nl: 'Wat is dit?', answer: 'Dit is een slak.', accept: ['Dit is de slak.'] },
      { nl: 'Er ___ twee jassen in de winkel: een lange en een korte.', cue: 'zijn', answer: 'zijn' },
      { nl: 'De slak heeft nog geen ___.', en: 'The snail doesn’t have a name yet.', answer: 'naam' },
      { nl: 'Jouw tas is groter dan mijn ___.', en: 'Your bag is bigger than my bag.', answer: 'tas' },
    ],
    explanation: 'stoelen, twee katten: plurals and numbers. jouw tuin, onze tuin: possessives. om + clock time; half acht = 7:30. geen before a noun without an article. de trein → hij, het weer → het. z → s, v → f: leest, schrijf.',
  },
  {
    type: 'drill', title: 'Question, negative, perfect', grammar: ['yes-no-question', 'inversion', 'niet', 'perfect-hebben', 'perfect-zijn', 'v2-inversion', 'als-inversion', 'dat-clause', 'separable-together', 'separable', 'comparative', 'superlative'],
    instruction: 'Rewrite each sentence as the task says. The comparison stays exactly as it is.',
    items: [
      { nl: 'Jij bent langer dan Lotte.', task: 'Make it a question', answer: 'Ben jij langer dan Lotte?' },
      { nl: 'De trein is sneller dan de auto.', task: 'Make it negative', answer: 'De trein is niet sneller dan de auto.' },
      { nl: 'Lotte koopt een goedkopere jas.', task: 'Put it in the perfect', answer: 'Lotte heeft een goedkopere jas gekocht.' },
      { nl: 'Wij gaan zondag met de snelste trein naar Gent.', task: 'Put it in the perfect, starting with “Vorige zondag”', answer: 'Vorige zondag zijn wij met de snelste trein naar Gent gegaan.' },
      { nl: 'Jij drinkt liever thee.', task: 'Make it a question', answer: 'Drink jij liever thee?' },
      { nl: 'Ik zwem het best.', task: 'Change ik to Bram', answer: 'Bram zwemt het best.', accept: ['Bram zwemt het beste.'] },
      { nl: 'Het is warmer dan gisteren.', task: 'Start with “vandaag”', answer: 'Vandaag is het warmer dan gisteren.' },
      { nl: 'Jij neemt jouw warmste jas mee.', task: 'Make it a question', answer: 'Neem jij jouw warmste jas mee?', accept: ['Neem jij je warmste jas mee?'] },
      { nl: 'Bram staat vroeg op.', task: 'Start with “Als het sneeuwt,”', answer: 'Als het sneeuwt, staat Bram vroeg op.' },
      { nl: 'De trein komt laat aan.', task: 'Start with “Ik denk dat”', answer: 'Ik denk dat de trein laat aankomt.' },
      { nl: 'Het sneeuwt. De trein is langzamer.', task: 'Join with als, the als-clause first', answer: 'Als het sneeuwt, is de trein langzamer.' },
      { nl: 'Max loopt het snelst.', task: 'Change Max to jij and make it a question', answer: 'Loop jij het snelst?', accept: ['Loop jij het snelste?'] },
    ],
    explanation: 'Ben jij, Drink jij, Neem jij, Loop jij: jij behind the verb loses its t. Als het sneeuwt, staat Bram …: the als-clause is position one. dat de trein laat aankomt: in a subclause the particle is back on the verb.',
  },
  {
    type: 'arrange', title: 'Her warmest coat', grammar: ['separable', 'superlative', 'als-inversion', 'possessives'],
    instruction: 'Build: “When it snows, Lotte takes her warmest coat along.” Two tiles are traps.',
    nl: 'Als het sneeuwt, neemt Lotte haar warmste jas mee.', en: 'When it snows, Lotte takes her warmest coat along.', image: 'snow', distractors: ['neem', 'warmer'],
  },
  {
    type: 'drill', title: 'liever and het liefst', grammar: ['comparative', 'superlative', 'adverb-position', 'dat-clause', 'separable', 'time-place'],
    instruction: 'Translate. “Would rather” is liever, “like … most” is het liefst. “You” is one person.',
    items: [
      { en: 'I would rather drink tea than coffee.', answer: 'Ik drink liever thee dan koffie.' },
      { en: 'Lotte would rather go by bike.', answer: 'Lotte gaat liever met de fiets.' },
      { en: 'What do you like doing most?', answer: 'Wat doe jij het liefst?', accept: ['Wat doe jij het liefste?'] },
      { en: 'I like reading most of all.', answer: 'Ik lees het liefst.', accept: ['Ik lees het liefste.', 'Het liefst lees ik.'] },
      { en: 'Bram would rather go out in Leuven than in Brussels.', answer: 'Bram gaat liever in Leuven uit dan in Brussel.', accept: ['Bram gaat liever uit in Leuven dan in Brussel.'] },
      { en: 'Who cooks best?', answer: 'Wie kookt het best?', accept: ['Wie kookt het beste?'] },
      { en: 'Bram says that his mother cooks best.', answer: 'Bram zegt dat zijn moeder het best kookt.', accept: ['Bram zegt dat zijn moeder het beste kookt.'] },
      { en: 'Noor likes playing in the snow most of all.', answer: 'Noor speelt het liefst in de sneeuw.', accept: ['Noor speelt het liefste in de sneeuw.'] },
      { en: 'Lotte reads the most.', answer: 'Lotte leest het meest.' },
      { en: 'I speak English better than Dutch.', answer: 'Ik spreek beter Engels dan Nederlands.', accept: ['Ik spreek Engels beter dan Nederlands.'] },
      { en: 'A bike costs less than a car.', answer: 'Een fiets kost minder dan een auto.' },
    ],
    explanation: 'liever and het liefst sit where graag sits: straight after the verb. In a dat-clause they stay in front of the verb at the end: dat zijn moeder het best kookt.',
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Een koude week', image: 'snow', grammar: ['comparative', 'superlative', 'days-op-om', 'v2-inversion', 'time-place', 'separable', 'separable-together', 'clock-time', 'numbers', 'hebben', 'gaan'],
    instruction: 'Lotte’s notes on a cold week in Leuven. Read and listen, then read again without the English. Every day starts with op + the day — and the verb comes straight after it.',
    lines: [
      { nl: 'Vorige week heeft de zon elke dag geschenen. Maar op maandag is het koud, en het sneeuwt een beetje.', en: 'Last week the sun shone every day. But on Monday it is cold, and it snows a little.', image: 'snow' },
      { nl: 'Bram neemt zijn warmste jas, zijn sleutel en zijn telefoon mee.', en: 'Bram takes his warmest coat, his key and his phone.', image: 'man-packing' },
      { nl: 'Hij wacht op de trein. Op het station is het kouder dan in de trein.', en: 'He waits for the train. At the station it is colder than on the train.', image: 'station' },
      { nl: 'Op dinsdag is het nog kouder. Bram belt zijn zus Sofie in Gent op: “Is het in Gent ook zo koud?”', en: 'On Tuesday it is even colder. Bram rings his sister Sofie in Ghent: “Is it that cold in Ghent too?”', image: 'phone' },
      { nl: 'Op woensdag sneeuwt het meer dan op maandag. Noor ziet sneeuw op de boom en op de bank in de straat.', en: 'On Wednesday it snows more than on Monday. Noor sees snow on the tree and on the bench in the street.', image: 'snow' },
      { nl: 'Het kind in de straat heet Noor. Zij is vijf jaar en heel lief, en zij gaat elke dag naar school, ook als het sneeuwt.', en: 'The child in the street is called Noor. She is five and very sweet, and she goes to school every day, even when it snows.', image: 'child' },
      { nl: 'Max staat aan de deur: hij wil naar buiten. Mimi zit in het raam en ziet de sneeuw.', en: 'Max is standing at the door: he wants to go out. Mimi sits in the window and sees the snow.', image: 'cat' },
      { nl: 'In het park ziet Max een vrouw met een kleine hond. Max is groter en sneller!', en: 'In the park Max sees a woman with a small dog. Max is bigger and faster!', image: 'dog-big' },
      { nl: 'Op donderdag is Lotte ziek en moe. Zij gaat om acht uur naar bed, en Bram kookt.', en: 'On Thursday Lotte is ill and tired. She goes to bed at eight, and Bram cooks.', image: 'woman-sick' },
      { nl: 'Op vrijdag werkt Bram thuis. Hij helpt de oude man in de sneeuw.', en: 'On Friday Bram works at home. He helps the old man in the snow.', image: 'man-helping' },
      { nl: 'Dan gaat hij naar de winkel: brood, kaas en vier appels. Brood is in Leuven goedkoper dan in Brussel, zegt Bram.', en: 'Then he goes to the shop: bread, cheese and four apples. Bread is cheaper in Leuven than in Brussels, Bram says.', image: 'shop' },
      { nl: 'Lotte is niet meer ziek. Zij leert in de kleine kamer, want de kleine kamer is warmer dan de grote.', en: 'Lotte is no longer ill. She studies in the small room, because the small room is warmer than the big one.', image: 'woman-studying' },
      { nl: 'Lotte belt haar broer Tom op, en zij wil ook haar vriendin Emma opbellen. Bram belt zijn vriend Jonas op.', en: 'Lotte rings her brother Tom, and she also wants to ring her friend Emma. Bram rings his friend Jonas.', image: 'woman-phoning' },
      { nl: 'En zaterdag en zondag? Dan sneeuwt het misschien nog meer.', en: 'And Saturday and Sunday? Then maybe it will snow even more.', image: 'snow' },
    ],
  },
  {
    type: 'drill', title: 'About the week', grammar: ['comparative', 'want-omdat', 'verb-final', 'question-word', 'clock-time'],
    instruction: 'Answer each question about the week with a complete sentence.',
    items: [
      { nl: 'Wanneer sneeuwt het meer: op maandag of op woensdag?', answer: 'Op woensdag sneeuwt het meer.', accept: ['Op woensdag sneeuwt het meer dan op maandag.', 'Het sneeuwt op woensdag meer.', 'Het sneeuwt op woensdag meer dan op maandag.', 'Op woensdag.'] },
      { nl: 'Waar is het kouder: op het station of in de trein?', answer: 'Op het station is het kouder.', accept: ['Het is op het station kouder.', 'Op het station is het kouder dan in de trein.', 'Het is op het station kouder dan in de trein.', 'Op het station.'] },
      { nl: 'Wie ziet Max in het park?', answer: 'Max ziet een vrouw met een kleine hond.', accept: ['Hij ziet een vrouw met een kleine hond.', 'In het park ziet Max een vrouw met een kleine hond.', 'Een vrouw met een kleine hond.'] },
      { nl: 'Hoe laat gaat Lotte op donderdag naar bed?', answer: 'Lotte gaat om acht uur naar bed.', accept: ['Zij gaat om acht uur naar bed.', 'Op donderdag gaat Lotte om acht uur naar bed.', 'Op donderdag gaat zij om acht uur naar bed.', 'Lotte gaat op donderdag om acht uur naar bed.', 'Zij gaat op donderdag om acht uur naar bed.', 'Om acht uur.'] },
      { nl: 'Lotte leert in de kleine kamer.', task: 'Say why — use omdat', answer: 'Lotte leert in de kleine kamer, omdat de kleine kamer warmer is dan de grote.', accept: ['Lotte leert in de kleine kamer, omdat de kleine kamer warmer dan de grote is.', 'Lotte leert in de kleine kamer, omdat hij warmer is dan de grote.', 'Lotte leert in de kleine kamer, omdat hij warmer dan de grote is.', 'Lotte leert in de kleine kamer, omdat de kleine kamer warmer is.', 'Lotte leert in de kleine kamer, omdat hij warmer is.', 'Lotte leert in de kleine kamer, omdat de kleine kamer warmer is dan de grote kamer.'] },
      { nl: 'Wat is in Leuven goedkoper dan in Brussel?', answer: 'Brood is in Leuven goedkoper dan in Brussel.', accept: ['In Leuven is brood goedkoper dan in Brussel.', 'Brood is in Leuven goedkoper.', 'Het brood is in Leuven goedkoper dan in Brussel.', 'Brood.'] },
    ],
  },
  {
    type: 'story', title: 'Een koude zaterdag', image: 'snow', grammar: ['comparative', 'superlative', 'dan-als', 'separable', 'separable-perfect', 'als-inversion', 'want-omdat', 'adjective-e', 'v2-inversion', 'clock-time'],
    instruction: 'Read and listen to every line, then read it again without the English. Find every comparative and every superlative.',
    lines: [
      { nl: 'Het is zaterdag, acht uur. Buiten is het koud, en het sneeuwt al een week in Leuven.', en: 'It is Saturday, eight o’clock. Outside it is cold, and it has been snowing in Leuven for a week.', image: 'snow' },
      { nl: 'Bram is vroeg opgestaan. Hij zit met zijn koffie en zijn ontbijt in de keuken.', en: 'Bram got up early. He is sitting in the kitchen with his coffee and his breakfast.', image: 'breakfast' },
      { speaker: 'Bram', nl: 'Het is vandaag nog kouder dan gisteren. En mijn jas is niet zo warm als jouw nieuwe jas.', en: 'It is even colder today than yesterday. And my coat is not as warm as your new coat.', image: 'man' },
      { speaker: 'Lotte', nl: 'Dan gaan we vandaag naar de winkel. Jij moet een warmere jas kopen!', en: 'Then we go to the shop today. You need to buy a warmer coat!', image: 'woman' },
      { nl: 'In de winkel zijn er veel jassen: lange jassen, korte jassen, dure jassen en goedkope jassen.', en: 'In the shop there are lots of coats: long coats, short coats, expensive coats and cheap coats.', image: 'shop' },
      { speaker: 'Bram', nl: 'Hoeveel kost de lange jas?', en: 'How much is the long coat?', image: 'price-tags' },
      { speaker: 'De verkoper', nl: 'De lange jas is de warmste, maar hij is ook de duurste. De korte jas is goedkoper, maar niet zo warm.', en: 'The long coat is the warmest, but it is also the most expensive. The short coat is cheaper, but not as warm.', image: 'price-tags' },
      { speaker: 'Lotte', nl: 'De prijs is goed. In Brussel zijn de jassen duurder dan hier.', en: 'The price is good. In Brussels the coats are more expensive than here.', image: 'woman' },
      { speaker: 'Lotte', nl: 'Jij moet de lange jas nemen, Bram. Jij wacht elke dag op de trein, ook als het sneeuwt.', en: 'You should take the long coat, Bram. You wait for the train every day, even when it snows.', image: 'coat' },
      { speaker: 'Bram', nl: 'Goed, ik neem de lange jas. Een warme jas is beter dan een goedkope jas.', en: 'Fine, I’ll take the long coat. A warm coat is better than a cheap coat.', image: 'coat' },
      { nl: 'Dan belt Bram zijn familie in Gent op. Zijn moeder is aan de telefoon.', en: 'Then Bram rings his family in Ghent. His mother answers the phone.', image: 'phone' },
      { speaker: 'Moeder', nl: 'Dag Bram! Hier in Gent sneeuwt het niet. De zon schijnt, en het is niet zo koud als in Leuven.', en: 'Hello Bram! Here in Ghent it isn’t snowing. The sun is shining, and it is not as cold as in Leuven.', image: 'mother' },
      { speaker: 'Bram', nl: 'Komen jullie morgen naar Leuven? Met de snelle trein ben je hier in een uur.', en: 'Are you coming to Leuven tomorrow? With the fast train you are here in an hour.', image: 'train' },
      { speaker: 'Moeder', nl: 'Nee, wij komen liever als het warmer is. Als het sneeuwt, is de trein altijd langzamer.', en: 'No, we would rather come when it is warmer. When it snows, the train is always slower.', image: 'mother' },
      { nl: 'Bram en Lotte lopen naar huis. Het sneeuwt nog altijd, maar de nieuwe jas is heel warm.', en: 'Bram and Lotte walk home. It is still snowing, but the new coat is very warm.', image: 'snow' },
      { speaker: 'Lotte', nl: 'En? Is jouw nieuwe jas warmer dan de oude?', en: 'Well? Is your new coat warmer than the old one?', image: 'woman' },
      { speaker: 'Bram', nl: 'Veel warmer! Het is de beste jas in Leuven. Nu ben ik blij, en ik vind de sneeuw ook mooi.', en: 'Much warmer! It is the best coat in Leuven. Now I am happy, and I think the snow is beautiful too.', image: 'man-happy' },
      { nl: 'Thuis wachten Max en Mimi. Max wil altijd naar buiten, maar Mimi slaapt het liefst in de warme keuken.', en: 'At home Max and Mimi are waiting. Max always wants to go out, but Mimi likes sleeping in the warm kitchen best.', image: 'dog-big' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'inversion'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the story. Answer without looking back.',
    items: [
      { nl: 'Sneeuwt het in Leuven?', answer: 'Ja' },
      { nl: 'Is Bram laat opgestaan?', answer: 'Nee' },
      { nl: 'Zit Bram met zijn ontbijt in de keuken?', answer: 'Ja' },
      { nl: 'Is het vandaag warmer dan gisteren?', answer: 'Nee' },
      { nl: 'Is de lange jas goedkoper dan de korte jas?', answer: 'Nee' },
      { nl: 'Koopt Bram de korte jas?', answer: 'Nee' },
      { nl: 'Sneeuwt het in Gent?', answer: 'Nee' },
      { nl: 'Heeft Bram zijn moeder opgebeld?', answer: 'Ja' },
      { nl: 'Is het in Gent kouder dan in Leuven?', answer: 'Nee' },
      { nl: 'Slaapt Mimi het liefst in de keuken?', answer: 'Ja' },
    ],
  },
  {
    type: 'drill', title: 'Answer in full', grammar: ['comparative', 'superlative', 'dan-als', 'want-omdat', 'verb-final', 'question-word', 'als-inversion'],
    instruction: 'Answer each question about the story with a complete sentence. When the task says “say why”, add the reason.',
    items: [
      { nl: 'Hoe is het weer in Leuven?', answer: 'Het is koud, en het sneeuwt.', accept: ['Het is koud en het sneeuwt.', 'Het sneeuwt, en het is koud.', 'Het sneeuwt en het is koud.', 'In Leuven is het koud, en het sneeuwt.', 'In Leuven is het koud en het sneeuwt.', 'Het sneeuwt.', 'Het is koud.'] },
      { nl: 'Is het vandaag warmer of kouder dan gisteren?', answer: 'Het is vandaag kouder dan gisteren.', accept: ['Vandaag is het kouder dan gisteren.', 'Het is vandaag nog kouder dan gisteren.', 'Vandaag is het nog kouder dan gisteren.', 'Het is kouder dan gisteren.', 'Kouder.'] },
      { nl: 'Wat is warmer: de lange jas of de korte jas?', answer: 'De lange jas is warmer.', accept: ['De lange jas is warmer dan de korte jas.', 'De lange jas is warmer dan de korte.', 'De lange jas.'] },
      { nl: 'Wat is goedkoper: de lange jas of de korte jas?', answer: 'De korte jas is goedkoper.', accept: ['De korte jas is goedkoper dan de lange jas.', 'De korte jas is goedkoper dan de lange.', 'De korte jas.'] },
      { nl: 'Waar zijn de jassen duurder: in Brussel of in Leuven?', answer: 'In Brussel zijn de jassen duurder.', accept: ['De jassen zijn in Brussel duurder.', 'In Brussel zijn de jassen duurder dan in Leuven.', 'De jassen zijn in Brussel duurder dan in Leuven.', 'In Brussel.'] },
      { nl: 'Bram koopt de lange jas.', task: 'Say why — use omdat', answer: 'Bram koopt de lange jas, omdat hij warmer is.', accept: ['Bram koopt de lange jas, omdat hij de warmste is.', 'Bram koopt de lange jas, omdat hij warmer is dan de korte jas.', 'Bram koopt de lange jas, omdat de lange jas warmer is.', 'Bram koopt de lange jas, omdat de lange jas de warmste is.', 'Bram koopt de lange jas, omdat een warme jas beter is dan een goedkope jas.', 'Bram koopt de lange jas, omdat hij elke dag op de trein wacht.'] },
      { nl: 'Waar is het niet zo koud: in Gent of in Leuven?', answer: 'In Gent is het niet zo koud.', accept: ['In Gent is het niet zo koud als in Leuven.', 'Het is in Gent niet zo koud.', 'Het is in Gent niet zo koud als in Leuven.', 'In Gent is het minder koud.', 'In Gent.'] },
      { nl: 'Zijn moeder komt morgen niet naar Leuven.', task: 'Say why — use want', answer: 'Zijn moeder komt morgen niet naar Leuven, want zij komt liever als het warmer is.', accept: ['Zijn moeder komt morgen niet naar Leuven, want als het sneeuwt, is de trein altijd langzamer.', 'Zijn moeder komt morgen niet naar Leuven, want als het sneeuwt, is de trein langzamer.', 'Zijn moeder komt morgen niet naar Leuven, want de trein is langzamer als het sneeuwt.', 'Zijn moeder komt morgen niet naar Leuven, want de trein is altijd langzamer als het sneeuwt.'] },
      { nl: 'Is de nieuwe jas warmer dan de oude?', answer: 'Ja, de nieuwe jas is veel warmer.', accept: ['Ja, de nieuwe jas is warmer.', 'Ja, de nieuwe jas is veel warmer dan de oude.', 'Ja, de nieuwe jas is warmer dan de oude.', 'Ja, hij is veel warmer.', 'Ja, hij is warmer.', 'Ja, veel warmer.'] },
      { nl: 'Wat doet Mimi het liefst?', answer: 'Mimi slaapt het liefst in de warme keuken.', accept: ['Zij slaapt het liefst in de warme keuken.', 'Mimi slaapt het liefst in de keuken.', 'Zij slaapt het liefst in de keuken.', 'Mimi slaapt het liefst.', 'Zij slaapt het liefst.', 'Mimi slaapt het liefste in de warme keuken.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['comparative', 'superlative', 'dan-als'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'De trein is sneller dan de fiets.' },
      { listen: 'Brussel is groter dan Leuven.' },
      { listen: 'Lotte is niet zo lang als Bram.' },
      { listen: 'Vandaag is het kouder dan gisteren.' },
      { listen: 'Lezen is makkelijker dan schrijven.' },
      { listen: 'Ik drink het liefst thee.' },
      { listen: 'Hoeveel kost de lange jas?' },
      { listen: 'Opstaan is moeilijker als het koud is.' },
      { listen: 'De zon schijnt, maar het is nog koud.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['comparative', 'superlative', 'dan-als', 'adjective-e', 'dat-clause', 'separable-perfect', 'als-inversion'],
    instruction: 'Translate. “You” is one person unless it says plural. For “taller” use lang.',
    items: [
      { en: 'The train is faster than the bike.', answer: 'De trein is sneller dan de fiets.' },
      { en: 'A car is more expensive than a bike.', answer: 'Een auto is duurder dan een fiets.' },
      { en: 'Bram is taller than Lotte.', answer: 'Bram is langer dan Lotte.', accept: ['Bram is groter dan Lotte.'] },
      { en: 'Mimi is not as big as Max.', answer: 'Mimi is niet zo groot als Max.' },
      { en: 'Today it is as cold as yesterday.', answer: 'Vandaag is het even koud als gisteren.', accept: ['Het is vandaag even koud als gisteren.'] },
      { en: 'Leuven, Ghent and Brussels: Brussels is the biggest.', answer: 'Leuven, Gent en Brussel: Brussel is het grootst.', accept: ['Leuven, Gent en Brussel: Brussel is het grootste.', 'Leuven, Gent en Brussel: Brussel is de grootste.', 'Leuven, Gent en Brussel: Brussel is de grootste stad.'] },
      { en: 'Lotte wants a warmer coat.', answer: 'Lotte wil een warmere jas.' },
      { en: 'We are hoping for warmer weather.', answer: 'Wij hopen op warmer weer.' },
      { en: 'I would rather go by train than by car.', answer: 'Ik ga liever met de trein dan met de auto.' },
      { en: 'Getting up is harder when it is cold.', answer: 'Opstaan is moeilijker als het koud is.' },
      { en: 'I think that the train is faster than the car.', answer: 'Ik denk dat de trein sneller is dan de auto.', accept: ['Ik denk dat de trein sneller dan de auto is.'] },
      { en: 'How much does the short coat cost?', answer: 'Hoeveel kost de korte jas?' },
      { en: 'Lotte has taken her warmest coat along.', answer: 'Lotte heeft haar warmste jas meegenomen.' },
      { en: 'Is the exam easier than the book?', answer: 'Is het examen makkelijker dan het boek?' },
      { en: 'Lotte has read more books than Bram.', answer: 'Lotte heeft meer boeken gelezen dan Bram.' },
    ],
  },
  {
    type: 'drill', title: 'Everything in one round', grammar: ['comparative', 'superlative', 'dan-als', 'present-regular', 'inversion', 'v2-inversion', 'plural', 'perfect-zijn', 'separable', 'verb-final', 'geen-niet', 'dit-is'],
    instruction: 'A final, demanding round: the whole book, now with comparisons. Type every answer. No hints beyond the task.',
    items: [
      { nl: 'Max is ___ dan Mimi.', cue: 'groot', answer: 'groter' },
      { nl: 'De fiets is ___ dan de trein.', cue: 'langzaam', answer: 'langzamer' },
      { nl: 'Een auto is het ___.', cue: 'duur', answer: 'duurst', accept: ['duurste'] },
      { nl: 'Lotte heeft een ___ jas gekocht.', cue: 'goedkoop', en: 'Lotte has bought a cheaper coat.', answer: 'goedkopere' },
      { nl: 'Bram zwemt ___ dan Lotte.', cue: 'goed', answer: 'beter' },
      { nl: 'Ik drink ___ thee dan koffie.', cue: 'graag', answer: 'liever' },
      { nl: 'Ik weet dat de trein om negen uur ___.', cue: 'aankomen', answer: 'aankomt' },
      { nl: 'Jij bent groter dan Noor.', task: 'Make it a question', answer: 'Ben jij groter dan Noor?' },
      { nl: 'Het is vandaag warm.', task: 'Compare: vandaag > gisteren', answer: 'Het is vandaag warmer dan gisteren.', accept: ['Vandaag is het warmer dan gisteren.'] },
      { nl: 'Leuven is kleiner dan Gent.', task: 'Use niet zo … als, with groot', answer: 'Leuven is niet zo groot als Gent.' },
      { nl: 'Wij gaan met de trein naar Gent.', task: 'Put it in the perfect', answer: 'Wij zijn met de trein naar Gent gegaan.' },
      { nl: 'De trein is snel.', task: 'Start with “Bram zegt dat”; compare with de auto', answer: 'Bram zegt dat de trein sneller is dan de auto.', accept: ['Bram zegt dat de trein sneller dan de auto is.'] },
      { en: 'Bram has no bike, but he walks faster than Lotte.', answer: 'Bram heeft geen fiets, maar hij loopt sneller dan Lotte.' },
      { en: 'The long coat is the most expensive.', answer: 'De lange jas is het duurst.', accept: ['De lange jas is het duurste.', 'De lange jas is de duurste.'] },
      { image: 'snail', nl: 'Is dit een hond?', answer: 'Nee, dit is een slak.', accept: ['Nee, dit is geen hond.', 'Nee, dit is geen hond, maar een slak.', 'Nee, dit is geen hond. Dit is een slak.'] },
      { listen: 'Als het sneeuwt, is de trein altijd langzamer.' },
    ],
  },
  {
    type: 'complete', title: 'Groter, sneller, beter',
    instruction: 'You can now compare anything: -er and dan, het -st, beter, meer and liever, even … als and niet zo … als — and talk about prices and the weather. Jouw Nederlands is vandaag beter dan gisteren.',
  },
];
