/**
 * Lesson 15 — Toen ik klein was.
 * Targets: toen, vroeger, geleden, vakantie, zee, strand, reizen, foto, oma, opa.
 * Structure: samen. Extra vocabulary: vocabulary/toen.js (zand, zandkasteel, ijsje, schelp,
 * opgroeien, kijken, bij, van, vaak, later).
 * Grammar: the simple past of weak verbs (-te / -de) · of strong verbs (was, had, ging, kwam …)
 * · toen, vroeger, geleden, and when to use the simple past rather than the perfect.
 * Story: Bram's childhood in Oostende, by the sea: in the holidays his parents worked, so he and
 * Sofie went to the beach every day with oma and opa. When he was twelve the family moved to Gent.
 * Lotte grew up in Antwerpen with Tom and went to the sea by train. No “zomer” (lesson 17):
 * the course says “in de vakantie”. Plural “foto’s” needs an apostrophe, so the lesson keeps to
 * one photo at a time.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'A childhood by the sea', grammar: ['present-regular', 'toen-past', 'imperfect-weak'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice. The last three sentences are in a new tense; just notice it for now.',
    cards: [
      { nl: 'Dit is een oude foto.', en: 'This is an old photo.', image: 'photo' },
      { nl: 'Op de foto staan oma en opa.', en: 'Grandma and grandpa are in the photo. (Dutch: “stand on the photo”)', image: 'grandparents' },
      { nl: 'Oostende is een stad aan zee.', en: 'Ostend is a town by the sea.', image: 'sea' },
      { nl: 'Het strand is groot, en het zand is warm.', en: 'The beach is big, and the sand is warm.', image: 'sea' },
      { nl: 'Een kind maakt een zandkasteel op het strand.', en: 'A child is making a sandcastle on the beach.', image: 'child-beach' },
      { nl: 'In de vakantie reizen Bram en Lotte graag.', en: 'In the holidays Bram and Lotte like to travel.', image: 'suitcase' },
      { nl: 'Vroeger woonde Bram in Oostende, aan zee.', en: 'Bram used to live in Ostend, by the sea.', image: 'sea' },
      { nl: 'Toen Bram klein was, ging hij vaak met oma en opa naar het strand.', en: 'When Bram was small, he often went to the beach with grandma and grandpa.', image: 'grandparents' },
      { nl: 'Dat is lang geleden!', en: 'That was a long time ago!', image: 'photo' },
    ],
    note: 'de zee (the sea): **aan zee** = by the sea, at the seaside; **naar zee** = to the seaside — no article in either. het strand (the beach), de vakantie (the holiday; in de vakantie = in the holidays), de foto (the photo — its plural is written with an apostrophe, so this lesson keeps to one photo at a time), de oma, de opa, reizen (to travel). **toen** = when / then (in the past), **vroeger** = in the past, formerly, **geleden** = ago, **samen** = together. Extra words: het zand, het zandkasteel, vaak (often).',
  },
  {
    type: 'observe', title: 'At grandma and grandpa’s', grammar: ['imperfect-strong', 'possessives', 'plural'],
    instruction: 'More words for the story. Listen for bij, van, kijken naar and later.',
    cards: [
      { nl: 'In de vakantie sliepen Bram en Sofie vaak bij oma en opa.', en: 'In the holidays Bram and Sofie often slept at grandma and grandpa’s.', image: 'grandparents' },
      { nl: 'Samen maakten zij een groot zandkasteel.', en: 'Together they made a big sandcastle.', image: 'child-beach' },
      { nl: 'Op het strand vond Sofie mooie schelpen.', en: 'On the beach Sofie found beautiful shells.', image: 'child-beach' },
      { nl: 'Om vier uur aten de kinderen een ijsje.', en: 'At four o’clock the children ate an ice cream.', image: 'sea' },
      { nl: 'Lotte kijkt naar een foto van Bram.', en: 'Lotte is looking at a photo of Bram.', image: 'photo' },
      { nl: 'Lotte is in Antwerpen opgegroeid, samen met haar broer Tom.', en: 'Lotte grew up in Antwerp, together with her brother Tom.', image: 'brother' },
      { nl: 'Later ging Bram met zijn familie in Gent wonen.', en: 'Later Bram went to live in Ghent with his family.', image: 'family' },
      { nl: 'Een uur geleden is de trein aangekomen.', en: 'The train arrived an hour ago.', image: 'train' },
    ],
    note: '**bij** = at someone’s place: *bij oma en opa* (at grandma and grandpa’s). **van** = of / from: *een foto van Bram*. **kijken naar** = to look at: *Lotte kijkt naar de foto.* **later** = later. **opgroeien** = to grow up, a separable verb like opstaan: *Lotte groeide op in Antwerpen*, *Lotte is in Antwerpen opgegroeid*. de schelp, de schelpen (shell); het ijsje (an ice cream — the -je makes it one portion, and every -je word is a het-word).',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['imperfect-strong'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Op de foto staan oma en opa.', en: 'Grandma and grandpa are in the photo.', answer: 'grandparents',
    choices: [{ image: 'grandparents', nl: 'oma en opa' }, { image: 'family', nl: 'een familie' }, { image: 'friends', nl: 'twee vrienden' }, { image: 'couple-bench', nl: 'Bram en Lotte op een bank' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['present-regular'],
    instruction: 'Listen without reading. Which picture is it?',
    nl: 'Het kind maakt een zandkasteel op het strand.', en: 'The child is making a sandcastle on the beach.', answer: 'child-beach',
    choices: [{ image: 'child-playing', nl: 'Het kind speelt.' }, { image: 'child-beach', nl: 'een zandkasteel' }, { image: 'child', nl: 'een kind' }, { image: 'garden', nl: 'een tuin' }],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['present-regular'],
    instruction: 'Listen. Which picture is it?',
    nl: 'Bram en Lotte reizen graag. In de vakantie gaan zij naar zee.', en: 'Bram and Lotte like to travel. In the holidays they are going to the seaside.', answer: 'suitcase',
    choices: [{ image: 'suitcase', nl: 'reizen' }, { image: 'bag', nl: 'een tas' }, { image: 'key', nl: 'een sleutel' }, { image: 'coat', nl: 'een jas' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['de-het', 'plural'],
    instruction: 'Type the Dutch. Nouns with their article.',
    items: [
      { image: 'sea', en: 'the sea', answer: 'de zee' },
      { image: 'child-beach', en: 'the beach', answer: 'het strand' },
      { en: 'the holiday', answer: 'de vakantie' },
      { image: 'photo', en: 'the photo', answer: 'de foto' },
      { image: 'grandparents', en: 'grandma and grandpa', answer: 'oma en opa' },
      { image: 'suitcase', en: 'to travel', answer: 'reizen' },
      { en: 'in the past / formerly (one word)', answer: 'vroeger' },
      { en: 'ago', answer: 'geleden' },
      { en: 'often', answer: 'vaak' },
      { en: 'the sandcastle', answer: 'het zandkasteel' },
      { en: 'the shells', answer: 'de schelpen' },
      { en: 'an ice cream (one portion)', answer: 'een ijsje' },
    ],
    explanation: 'het strand, het zand, het zandkasteel, het ijsje — but de zee, de vakantie, de foto, de schelp. A compound takes the article of its last part: zand + kasteel → het zandkasteel.',
  },
  {
    type: 'drill', title: 'Hear and spell',
    instruction: 'Play each one and type it. “oe” in vroeger is the “oo” of English “food”; the stress in vakantie is in the middle: va-KAN-sie.',
    items: [
      { listen: 'vakantie' },
      { listen: 'geleden' },
      { listen: 'vroeger' },
      { listen: 'zandkasteel' },
      { listen: 'Toen ik klein was.' },
      { listen: 'Dat is lang geleden.' },
      { listen: 'Wij gingen naar zee.' },
      { listen: 'Oma en opa woonden aan zee.' },
    ],
    explanation: 'vakantie is written with t but said with an s-sound: va-kan-sie. zandkasteel: zand + kasteel, the d said as t.',
  },

  // ——— Grammar: the simple past of weak verbs ———
  {
    part: 'Grammar', type: 'grammar', title: 'The simple past: -te and -de', grammar: ['imperfect-weak', 'participle', 'spelling-stem', 'present-regular'],
    body: [
      'Dutch has two past tenses. The **perfect** you know since lesson 11: *Ik heb in Oostende gewoond.* The second is the **simple past** (in Dutch grammars: *de onvoltooid verleden tijd*): one word, like English *lived* or *worked*. *Vroeger **woonde** Bram in Oostende. Oma **kookte** elke dag.* When to use which comes on a later page; first, how to make it.',
      '**Weak verbs** — the regular ones — take the **stem** and add **-te** or **-de**. That one form serves **ik, jij, hij and zij** (she): *ik woonde, jij woonde, hij woonde*. There is **no -t for jij or hij** in the past, so the jij-rule of the present disappears: *Woonde jij in Gent?* For **wij, jullie and zij** (they) add **-n**: *wij woonden, zij werkten*.',
      '**-te or -de?** The same test as for the participle: if the stem ends in a letter of **’t kofschip** (t, k, f, s, ch, p), add **-te**; otherwise add **-de**. The participle already tells you: *gekookt → kookte*, *gespeeld → speelde*. As before, check the **infinitive**: *reizen* has a z, so *reis → **reisde*** (never reiste), just as its participle is *gereisd* with a d.',
      '**A stem that ends in t** still gets the whole ending — so here, unlike the participle, Dutch **does** write a double letter: *praat + te = **praatte***, *wacht + te = **wachtte***, *heet + te = **heette***. Compare *hij praat* (present) and *gepraat* (participle). In speech *praatte* sounds like *prate*; only the spelling shows the past — and the context.',
      '**The stem is the ik-form**, with its spelling: a long vowel stays double because the syllable stays closed: *woon-de, kook-te, speel-de, leer-de, maak-te, hoop-te*. A single consonant stays single: *bel-de*.',
      '**Five common weak verbs are irregular**, and you know the pattern from their participles: *kopen → **kocht*** (gekocht), *denken → **dacht*** (gedacht). *zeggen → **zei**, zeiden. vragen → **vroeg**, vroegen* — the same spelling as *vroeg* (early): *Hij vroeg het* (he asked) against *Hij stond vroeg op* (he got up early). And *willen → **wilde**, wilden*.',
    ],
    tables: [
      { caption: 'wonen (-de) · werken (-te)', rows: [
        { nl: 'ik woon[de] · ik werk[te]', en: 'I lived · I worked' },
        { nl: 'jij woon[de] · jij werk[te]', en: 'you lived · you worked — no -t' },
        { nl: 'hij woon[de] · zij werk[te]', en: 'he lived · she worked' },
        { nl: 'wij woon[den] · wij werk[ten]', en: 'we lived · we worked' },
        { nl: 'jullie woon[den] · zij werk[ten]', en: 'you (plural) lived · they worked' },
        { nl: 'woon[de] jij? · werk[te] jij?', en: 'did you live? · did you work? — nothing changes' },
      ] },
      { caption: '’t kofschip → -te · everything else → -de', rows: [
        { nl: 'koken — gekookt — kook[te]', en: 'cooked — k' },
        { nl: 'hopen — gehoopt — hoop[te]', en: 'hoped — p' },
        { nl: 'maken — gemaakt — maak[te]', en: 'made — k' },
        { nl: 'spelen — gespeeld — speel[de]', en: 'played — l' },
        { nl: 'leren — geleerd — leer[de]', en: 'learnt — r' },
        { nl: 'bellen — gebeld — bel[de]', en: 'called — l' },
        { nl: 'reizen — gereisd — reis[de]', en: 'travelled — z in the infinitive' },
        { nl: 'het regent — het regen[de]', en: 'it rained' },
      ] },
      { caption: 'a stem in t: a double letter', rows: [
        { nl: 'praten — ik praat — ik praat[te]', en: 'I talked' },
        { nl: 'wachten — ik wacht — ik wacht[te]', en: 'I waited' },
        { nl: 'heten — hij heet — hij heet[te]', en: 'he was called' },
      ] },
      { caption: 'irregular', rows: [
        { nl: 'kopen — kocht — kochten', en: 'bought' },
        { nl: 'denken — dacht — dachten', en: 'thought' },
        { nl: 'zeggen — zei — zeiden', en: 'said' },
        { nl: 'vragen — vroeg — vroegen', en: 'asked' },
        { nl: 'willen — wilde — wilden', en: 'wanted' },
      ] },
    ],
    examples: [
      { nl: 'Vroeger woonde Bram in Oostende.', en: 'Bram used to live in Ostend.' },
      { nl: 'Bram en Sofie speelden elke dag op het strand.', en: 'Bram and Sofie played on the beach every day.' },
      { nl: 'Opa praatte graag met de kinderen.', en: 'Grandpa liked talking to the children.' },
      { nl: 'Hoe heette jouw oma?', en: 'What was your grandma called?' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate wonen in the past', grammar: ['imperfect-weak', 'subject-pronouns'],
    instruction: 'Type the simple past of wonen for every person. Say “ik woonde, jij woonde …” out loud.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'woonde' },
      { label: 'jij', gloss: 'you', answer: 'woonde' },
      { label: 'hij', gloss: 'he', answer: 'woonde' },
      { label: 'zij', gloss: 'she', answer: 'woonde' },
      { label: 'wij', gloss: 'we', answer: 'woonden' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'woonden' },
      { label: 'zij', gloss: 'they', answer: 'woonden' },
      { label: 'oma en opa', gloss: 'they', answer: 'woonden' },
    ],
    explanation: 'Two forms only: woonde for one person, woonden for more than one. The double o stays: woon-de.',
  },
  {
    type: 'drill', layout: 'table', title: 'werken and wachten', grammar: ['imperfect-weak', 'subject-pronouns', 'spelling-stem'],
    instruction: 'The small word under each person is the verb. Both take -te. Watch the double t of wachten.',
    items: [
      { label: 'ik', gloss: 'werken', answer: 'werkte' },
      { label: 'jij', gloss: 'werken', answer: 'werkte' },
      { label: 'zij', gloss: 'she · werken', answer: 'werkte' },
      { label: 'wij', gloss: 'werken', answer: 'werkten' },
      { label: 'ik', gloss: 'wachten', answer: 'wachtte' },
      { label: 'hij', gloss: 'wachten', answer: 'wachtte' },
      { label: 'jullie', gloss: 'wachten', answer: 'wachtten' },
      { label: 'zij', gloss: 'they · wachten', answer: 'wachtten' },
    ],
    explanation: 'wacht + te = wachtte, wacht + ten = wachtten. Three t’s in a row look strange, but they are right: the stem keeps its t and the ending brings its own.',
  },
  {
    type: 'drill', layout: 'table', title: '-te or -de: every weak verb', grammar: ['imperfect-weak', 'participle', 'spelling-stem'],
    instruction: 'Mixed persons and verbs. Think of the participle first — gekookt, gespeeld — then write the past.',
    items: [
      { label: 'ik', gloss: 'koken', answer: 'kookte' },
      { label: 'hij', gloss: 'spelen', answer: 'speelde' },
      { label: 'wij', gloss: 'leren', answer: 'leerden' },
      { label: 'zij', gloss: 'she · praten', answer: 'praatte' },
      { label: 'ik', gloss: 'heten', answer: 'heette' },
      { label: 'jij', gloss: 'maken', answer: 'maakte' },
      { label: 'wij', gloss: 'hopen', answer: 'hoopten' },
      { label: 'het', gloss: 'regenen', answer: 'regende' },
      { label: 'hij', gloss: 'bellen', answer: 'belde' },
      { label: 'zij', gloss: 'they · reizen', answer: 'reisden' },
      { label: 'jullie', gloss: 'koken', answer: 'kookten' },
      { label: 'zij', gloss: 'they · spelen', answer: 'speelden' },
    ],
    explanation: 'k and p are in ’t kofschip: kookte, maakte, hoopten. l, r and n are not: speelde, leerden, belde, regende. reisden with d, because the infinitive is reizen.',
  },
  {
    type: 'drill', title: 'Type the past', grammar: ['imperfect-weak', 'v2-inversion', 'inversion'],
    instruction: 'Type the simple past of the verb given. One person: -te / -de. More people: -ten / -den.',
    items: [
      { nl: 'Vroeger ___ Bram in Oostende.', cue: 'wonen', answer: 'woonde' },
      { nl: 'Oma ___ elke dag.', cue: 'koken', en: 'Grandma cooked every day.', answer: 'kookte' },
      { nl: 'Bram en Sofie ___ op het strand.', cue: 'spelen', answer: 'speelden' },
      { nl: 'Zijn vader ___ ook op zaterdag.', cue: 'werken', en: 'His father worked on Saturdays too.', answer: 'werkte' },
      { nl: 'Opa ___ graag met de kinderen.', cue: 'praten', answer: 'praatte' },
      { nl: 'Wij ___ een uur op de trein.', cue: 'wachten', en: 'We waited an hour for the train.', answer: 'wachtten' },
      { nl: 'Hoe ___ jouw oma?', cue: 'heten', en: 'What was your grandma called?', answer: 'heette' },
      { nl: 'Oma en opa ___ graag.', cue: 'reizen', en: 'Grandma and grandpa liked to travel.', answer: 'reisden' },
      { nl: 'Het ___ vaak in de vakantie, maar wij hoopten elke dag op zon.', cue: 'regenen', en: 'It often rained in the holidays, but every day we hoped for sun.', answer: 'regende' },
      { nl: 'Samen ___ wij een groot zandkasteel.', cue: 'maken', answer: 'maakten' },
      { nl: '___ jij vroeger in Antwerpen?', cue: 'wonen', en: 'Did you use to live in Antwerp?', answer: 'Woonde' },
      { nl: 'Bram ___ zwemmen in de zee.', cue: 'leren', en: 'Bram learnt to swim in the sea.', answer: 'leerde' },
    ],
    explanation: '“Woonde jij?” — in the past jij never loses anything, because there is no -t to lose. Samen maakten wij: samen is the first element, so the verb comes second.',
  },
  {
    type: 'drill', title: 'Start with “vroeger”', grammar: ['imperfect-weak', 'toen-past', 'v2-inversion', 'present-regular', 'time-place'],
    task: 'Start with “vroeger”',
    instruction: 'Now it is the present. Start with vroeger and put the verb in the simple past. vroeger is the first element, so the verb comes second.',
    items: [
      { nl: 'Bram woont in Oostende.', answer: 'Vroeger woonde Bram in Oostende.' },
      { nl: 'Ik werk in Brussel.', answer: 'Vroeger werkte ik in Brussel.' },
      { nl: 'Oma kookt elke dag.', answer: 'Vroeger kookte oma elke dag.' },
      { nl: 'Wij spelen op het strand.', answer: 'Vroeger speelden wij op het strand.' },
      { nl: 'Jij woont in Antwerpen.', answer: 'Vroeger woonde jij in Antwerpen.' },
      { nl: 'Oma en opa reizen veel.', answer: 'Vroeger reisden oma en opa veel.' },
      { nl: 'Lotte praat veel met Tom.', answer: 'Vroeger praatte Lotte veel met Tom.' },
      { nl: 'Jullie wachten elke dag op de trein.', answer: 'Vroeger wachtten jullie elke dag op de trein.' },
      { nl: 'Bram belt zijn moeder elke dag.', answer: 'Vroeger belde Bram zijn moeder elke dag.' },
      { nl: 'Het regent hier niet vaak.', answer: 'Vroeger regende het hier niet vaak.' },
    ],
    explanation: 'Vroeger woonde Bram — vroeger + simple past is the Dutch “used to”. Vroeger woonde jij: the present “woon jij” would lose its t, but the past has none to lose.',
  },

  // ——— Grammar: strong verbs ———
  {
    type: 'grammar', title: 'The simple past: was, had, ging, kwam', grammar: ['imperfect-strong', 'zijn', 'hebben', 'modals', 'spelling-z-s', 'separable'],
    body: [
      'The verbs you use most are **strong**: they make their past by **changing the vowel**, and in the singular they add **no ending at all**. *gaan → ik **ging**, jij ging, hij ging. komen → zij **kwam**.* For wij, jullie and zij (they) add **-en**: *wij **gingen**, zij **kwamen***.',
      '**zijn and hebben** first, because every story needs them: *ik **was**, jij was, hij was — wij / jullie / zij **waren***; *ik **had**, jij had, hij had — wij / jullie / zij **hadden***. In a story *was* and *had* are far more common than *ben geweest* and *heb gehad*.',
      '**The four modals:** *kunnen → **kon**, konden · willen → **wilde**, wilden · moeten → **moest**, moesten · mogen → **mocht**, mochten.* The infinitive still waits at the end: *Bram **kon** toen al goed **zwemmen**.*',
      'No rule predicts the new vowel, but there are families. **ij → ee:** schrijven → schreef, rijden → reed, begrijpen → begreep, kijken → keek. **i → o:** drinken → dronk, vinden → vond, zwemmen → zwom. **→ ie:** lopen → liep, slapen → sliep, helpen → hielp. **→ a:** lezen → las, eten → at, spreken → sprak, zitten → zat, nemen → nam, zien → zag. **On their own:** gaan → ging, komen → kwam, staan → stond, doen → deed, weten → wist.',
      '**The plural brings back the spelling rules** of lessons 3 and 5. The -en opens the syllable, so a short a in the singular becomes a long a, written single: *zat → za-ten, at → a-ten, nam → na-men, sprak → spra-ken, zag → za-gen, kwam → kwa-men*. The z and v come back: *las → la**z**en, schreef → schre**v**en*. A vowel that stays short doubles the consonant: *zwom → zwo**mm**en*. And *reed → re-den, deed → de-den, keek → ke-ken*.',
      '**Separable verbs** still split in a main clause: *Bram **stond** om zeven uur **op**. Oma **nam** brood **mee**. De trein **kwam** laat **aan**.* In a subclause they come together as one word, exactly as in the present: *toen de trein **aankwam***, *omdat Bram vroeg **opstond***.',
    ],
    tables: [
      { caption: 'zijn · hebben', rows: [
        { nl: 'ik was · ik had', en: 'I was · I had' },
        { nl: 'jij was · jij had', en: 'you were · you had' },
        { nl: 'hij was · zij had', en: 'he was · she had' },
        { nl: 'wij waren · wij hadden', en: 'we were · we had' },
        { nl: 'jullie waren · zij hadden', en: 'you (plural) were · they had' },
      ] },
      { caption: 'the modals', rows: [
        { nl: 'ik kon · wij konden', en: 'I could · we could' },
        { nl: 'hij wilde · zij wilden', en: 'he wanted · they wanted' },
        { nl: 'jij moest · jullie moesten', en: 'you had to' },
        { nl: 'zij mocht · wij mochten', en: 'she was allowed to · we were allowed to' },
      ] },
      { caption: 'the families: infinitive — singular — plural', rows: [
        { nl: 'schrijven — schreef — schreven', en: 'wrote' },
        { nl: 'kijken — keek — keken', en: 'looked' },
        { nl: 'drinken — dronk — dronken', en: 'drank' },
        { nl: 'zwemmen — zwom — zwommen', en: 'swam' },
        { nl: 'lopen — liep — liepen', en: 'walked' },
        { nl: 'lezen — las — lazen', en: 'read' },
        { nl: 'eten — at — aten', en: 'ate' },
        { nl: 'zitten — zat — zaten', en: 'sat' },
        { nl: 'gaan — ging — gingen', en: 'went' },
        { nl: 'komen — kwam — kwamen', en: 'came' },
        { nl: 'staan — stond — stonden', en: 'stood' },
        { nl: 'doen — deed — deden', en: 'did' },
      ] },
    ],
    examples: [
      { nl: 'Oma en opa waren heel lief.', en: 'Grandma and grandpa were very kind.' },
      { nl: 'Wij gingen elke dag naar het strand.', en: 'We went to the beach every day.' },
      { nl: 'Opa liep langzaam, maar hij zwom heel goed.', en: 'Grandpa walked slowly, but he swam very well.' },
      { nl: 'Sofie las veel boeken.', en: 'Sofie read a lot of books.' },
      { nl: 'Oma nam altijd brood met kaas mee.', en: 'Grandma always took bread and cheese along.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'zijn and hebben in the past', grammar: ['imperfect-strong', 'zijn', 'hebben', 'subject-pronouns'],
    instruction: 'The small word under each person is the verb. Type the simple past.',
    items: [
      { label: 'ik', gloss: 'zijn', answer: 'was' },
      { label: 'jij', gloss: 'zijn', answer: 'was' },
      { label: 'hij', gloss: 'zijn', answer: 'was' },
      { label: 'wij', gloss: 'zijn', answer: 'waren' },
      { label: 'jullie', gloss: 'zijn', answer: 'waren' },
      { label: 'zij', gloss: 'they · zijn', answer: 'waren' },
      { label: 'ik', gloss: 'hebben', answer: 'had' },
      { label: 'jij', gloss: 'hebben', answer: 'had' },
      { label: 'zij', gloss: 'she · hebben', answer: 'had' },
      { label: 'wij', gloss: 'hebben', answer: 'hadden' },
      { label: 'zij', gloss: 'they · hebben', answer: 'hadden' },
    ],
    explanation: 'jij was, not “jij waart”: that form is centuries old. had / hadden: short a, so the d doubles in the plural.',
  },
  {
    type: 'drill', layout: 'table', title: 'gaan, komen, staan — and the modals', grammar: ['imperfect-strong', 'gaan', 'modals', 'subject-pronouns'],
    instruction: 'The small word under each person is the verb. Type the simple past.',
    items: [
      { label: 'ik', gloss: 'gaan', answer: 'ging' },
      { label: 'wij', gloss: 'gaan', answer: 'gingen' },
      { label: 'hij', gloss: 'komen', answer: 'kwam' },
      { label: 'jullie', gloss: 'komen', answer: 'kwamen' },
      { label: 'zij', gloss: 'she · staan', answer: 'stond' },
      { label: 'zij', gloss: 'they · staan', answer: 'stonden' },
      { label: 'ik', gloss: 'kunnen', answer: 'kon' },
      { label: 'wij', gloss: 'kunnen', answer: 'konden' },
      { label: 'jij', gloss: 'willen', answer: 'wilde' },
      { label: 'zij', gloss: 'they · willen', answer: 'wilden' },
      { label: 'hij', gloss: 'moeten', answer: 'moest' },
      { label: 'jullie', gloss: 'moeten', answer: 'moesten' },
      { label: 'ik', gloss: 'mogen', answer: 'mocht' },
      { label: 'wij', gloss: 'mogen', answer: 'mochten' },
    ],
    explanation: 'ging, kwam, stond, kon, moest, mocht: no ending in the singular. wilde is the odd one — it takes -de like a weak verb.',
  },
  {
    type: 'drill', layout: 'table', title: 'Strong verbs: ij, i, ie', grammar: ['imperfect-strong', 'subject-pronouns', 'spelling-z-s'],
    instruction: 'Families one to three. The small word is the verb; the person tells you singular or plural.',
    items: [
      { label: 'opa', gloss: 'he · schrijven', answer: 'schreef' },
      { label: 'jullie', gloss: 'schrijven', answer: 'schreven' },
      { label: 'hij', gloss: 'rijden', answer: 'reed' },
      { label: 'ik', gloss: 'begrijpen', answer: 'begreep' },
      { label: 'wij', gloss: 'kijken', answer: 'keken' },
      { label: 'jij', gloss: 'drinken', answer: 'dronk' },
      { label: 'wij', gloss: 'vinden', answer: 'vonden' },
      { label: 'hij', gloss: 'zwemmen', answer: 'zwom' },
      { label: 'wij', gloss: 'zwemmen', answer: 'zwommen' },
      { label: 'ik', gloss: 'lopen', answer: 'liep' },
      { label: 'zij', gloss: 'they · slapen', answer: 'sliepen' },
      { label: 'oma', gloss: 'she · helpen', answer: 'hielp' },
    ],
    explanation: 'schreef → schreven: the v of schrijven comes back. zwom → zwommen: the o stays short, so the m doubles. vond, not vondt: no -t is ever added in the past.',
  },
  {
    type: 'drill', layout: 'table', title: 'Strong verbs: a, and the loners', grammar: ['imperfect-strong', 'subject-pronouns', 'spelling-z-s', 'spelling-stem'],
    instruction: 'Family four and the verbs on their own. Say the singular and the plural together: las — lazen.',
    items: [
      { label: 'Sofie', gloss: 'she · lezen', answer: 'las' },
      { label: 'wij', gloss: 'lezen', answer: 'lazen' },
      { label: 'ik', gloss: 'eten', answer: 'at' },
      { label: 'zij', gloss: 'they · eten', answer: 'aten' },
      { label: 'zij', gloss: 'she · spreken', answer: 'sprak' },
      { label: 'wij', gloss: 'zitten', answer: 'zaten' },
      { label: 'jij', gloss: 'zien', answer: 'zag' },
      { label: 'zij', gloss: 'they · zien', answer: 'zagen' },
      { label: 'ik', gloss: 'nemen', answer: 'nam' },
      { label: 'wij', gloss: 'doen', answer: 'deden' },
      { label: 'ik', gloss: 'weten', answer: 'wist' },
      { label: 'zij', gloss: 'they · zeggen', answer: 'zeiden' },
    ],
    explanation: 'las → lazen, at → aten, zat → zaten, zag → zagen: in the plural the a is long, so one a is enough. wist is weten’s own: learn it as it is.',
  },
  {
    type: 'drill', title: 'Strong verbs in the story', grammar: ['imperfect-strong', 'separable', 'modals', 'infinitive-end', 'inversion'],
    instruction: 'Type the simple past of the verb given. Separable verbs: only the verb part goes in the gap.',
    items: [
      { nl: 'Bram ___ vroeger elke dag naar het strand.', cue: 'gaan', answer: 'ging' },
      { nl: 'In de vakantie ___ Bram en Sofie bij oma en opa.', cue: 'slapen', answer: 'sliepen' },
      { nl: 'Het water ___ koud.', cue: 'zijn', answer: 'was' },
      { nl: 'Wij ___ geen auto.', cue: 'hebben', answer: 'hadden' },
      { nl: 'Sofie ___ mooie schelpen.', cue: 'vinden', answer: 'vond' },
      { nl: 'Om vier uur ___ de kinderen een ijsje.', cue: 'eten', answer: 'aten' },
      { nl: 'Opa ___ altijd koffie.', cue: 'drinken', answer: 'dronk' },
      { nl: 'Bram ___ al goed zwemmen.', cue: 'kunnen', en: 'Bram could already swim well.', answer: 'kon' },
      { nl: 'De kinderen ___ niet in de zee zwemmen, want het water was koud.', cue: 'mogen', answer: 'mochten' },
      { nl: 'Oma ___ altijd brood met kaas mee.', cue: 'meenemen', answer: 'nam' },
      { nl: 'Wij ___ elke dag in het zand.', cue: 'zitten', answer: 'zaten' },
      { nl: 'Opa ___ langzaam, maar hij zwom heel goed.', cue: 'lopen', answer: 'liep' },
      { nl: '___ jij vroeger ook naar zee?', cue: 'gaan', en: 'Did you use to go to the seaside too?', answer: 'Ging' },
      { nl: 'Bram ___ niet wat opa zei.', cue: 'begrijpen', answer: 'begreep' },
      { nl: 'De trein ___ om tien uur aan.', cue: 'aankomen', answer: 'kwam' },
      { nl: 'Lotte ___ elke dag naar de foto.', cue: 'kijken', en: 'Lotte looked at the photo every day.', answer: 'keek' },
    ],
    explanation: 'sliepen, aten, mochten, zaten: more than one person, so -en. nam … mee, kwam … aan: the particle stays at the end, as in the present.',
  },
  {
    type: 'drill', title: 'From the perfect to the simple past', grammar: ['imperfect-strong', 'imperfect-weak', 'perfect-hebben', 'perfect-zijn', 'participle', 'separable-perfect'],
    task: 'Put it in the simple past',
    instruction: 'The same fact, in the other past tense. hebben / zijn and the participle disappear; one verb form takes their place.',
    items: [
      { nl: 'Ik heb in de zee gezwommen.', answer: 'Ik zwom in de zee.' },
      { nl: 'Bram is naar het strand gegaan.', answer: 'Bram ging naar het strand.' },
      { nl: 'Wij hebben een ijsje gegeten.', answer: 'Wij aten een ijsje.' },
      { nl: 'Sofie heeft een boek gelezen.', answer: 'Sofie las een boek.' },
      { nl: 'Oma heeft thee gedronken.', answer: 'Oma dronk thee.' },
      { nl: 'Jullie zijn met de trein gekomen.', answer: 'Jullie kwamen met de trein.' },
      { nl: 'Ik heb een oude foto gevonden.', answer: 'Ik vond een oude foto.' },
      { nl: 'Opa heeft niet goed geslapen.', answer: 'Opa sliep niet goed.' },
      { nl: 'Zij hebben het niet gezien.', answer: 'Zij zagen het niet.' },
      { nl: 'Lotte heeft een nieuwe jas gekocht.', answer: 'Lotte kocht een nieuwe jas.' },
      { nl: 'Wat heb jij gisteren gedaan?', answer: 'Wat deed jij gisteren?' },
      { nl: 'Bram is om zeven uur opgestaan.', answer: 'Bram stond om zeven uur op.' },
    ],
    explanation: 'gezwommen → zwom, gegeten → at, gedaan → deed: the participle and the past are often different vowels, so learn the three together — zwemmen, zwom, gezwommen. opgestaan → stond … op: the particle goes to the end on its own.',
  },
  {
    type: 'arrange', title: 'Every day to the beach', grammar: ['imperfect-strong', 'v2-inversion', 'time-place'],
    instruction: 'Build: “In the holidays Bram and Sofie went to the beach every day.” Two tiles are traps.',
    nl: 'In de vakantie gingen Bram en Sofie elke dag naar het strand.', en: 'In the holidays Bram and Sofie went to the beach every day.', image: 'sea', distractors: ['ging', 'gaan'],
  },

  // ——— Grammar: toen, vroeger, geleden ———
  {
    type: 'grammar', title: 'toen, vroeger, geleden — and which past?', grammar: ['toen-past', 'verb-final', 'als-inversion', 'v2-inversion', 'perfect-hebben'],
    body: [
      '**toen** + a subclause means *when* for **one moment or one period in the past**. Like omdat and als it sends the verb to the end: *toen ik klein **was***, *toen de trein **aankwam***.',
      'Put the toen-clause first and it fills position one, so the main verb comes straight after the comma — the pattern of *Als het regent, gaan wij …*: ***Toen** ik klein was, **woonde ik** aan zee.* Or keep the main clause first: *Ik woonde aan zee, toen ik klein was.*',
      '**toen, als or wanneer?** English has one *when*; Dutch has three. **toen** — one occasion or period in the past: *Toen Bram twaalf was, …* **als** — now or in the future, and also *whenever* for a habit in the past: *Als het regende, speelden wij in de keuken* (every time it rained). **wanneer** — the question word: *Wanneer was dat?*',
      '**toen** has a second job: on its own it means *then, at that time*, and it is an ordinary first element with inversion: ***Toen ging** opa naar huis* — then grandpa went home. Only the verb tells you which toen you have: *Toen ging opa naar huis* (then …) against *Toen opa naar huis ging, …* (when …). In the middle of a sentence: *Bram was toen zes jaar.* Use **dan** for *then* in the present and future, **toen** in the past.',
      '**vroeger** means *in the past, formerly*. With the simple past it is how Dutch says *used to*: ***Vroeger woonde** Bram in Oostende* — Bram used to live in Ostend. **… geleden** means *ago*, and like English it comes after the time: *drie jaar geleden, een week geleden, lang geleden.* Both are time elements; at the front the verb comes second: *Twee dagen geleden **kocht** Lotte een boek.*',
      '**Simple past or perfect?** Both are correct; the difference is how you use them. The **perfect** reports a single fact or a piece of news, above all in conversation: *Ik heb gisteren gezwommen. Heb jij de foto gezien?* The **simple past** tells a **story** or describes how things **were**: a chain of events, a habit, the background. *Toen ik klein was, woonden wij aan zee. Elke dag gingen wij naar het strand.* A story often opens with a perfect and goes on in the simple past. And with **zijn, hebben and the modals** Dutch prefers the simple past even for a single fact: *Ik was gisteren moe* sounds better than *Ik ben gisteren moe geweest*.',
    ],
    tables: [
      { caption: 'toen + subclause: the verb at the end', rows: [
        { nl: 'Toen ik klein [was], woonde ik aan zee.', en: 'When I was small, I lived by the sea.' },
        { nl: 'Toen de trein [aankwam], stond oma op het station.', en: 'When the train arrived, grandma was standing on the platform.' },
        { nl: 'Bram was blij, toen hij oma en opa [zag].', en: 'Bram was happy when he saw grandma and grandpa.' },
      ] },
      { caption: 'toen · als · wanneer', rows: [
        { nl: 'Toen Bram twaalf [was], gingen zij in Gent wonen.', en: 'When Bram was twelve, they went to live in Ghent. (once)' },
        { nl: 'Als het [regende], speelden wij in de keuken.', en: 'Whenever it rained, we played in the kitchen. (every time)' },
        { nl: 'Wanneer [was] dat?', en: 'When was that? (question)' },
      ] },
      { caption: 'toen = then · vroeger · geleden', rows: [
        { nl: 'Toen [ging] opa naar huis.', en: 'Then grandpa went home.' },
        { nl: 'Bram was toen zes jaar.', en: 'Bram was six at the time.' },
        { nl: 'Vroeger [woonde] Bram in Oostende.', en: 'Bram used to live in Ostend.' },
        { nl: 'Een week geleden [regende] het elke dag.', en: 'A week ago it rained every day.' },
      ] },
    ],
    examples: [
      { nl: 'Gisteren heb ik een oude foto gevonden. Oma en opa stonden op het strand, en ik was nog heel klein.', en: 'Yesterday I found an old photo. Grandma and grandpa were standing on the beach, and I was still very small.' },
      { nl: 'Dat is lang geleden.', en: 'That was a long time ago. (Dutch says “is”)' },
      { nl: 'Wanneer gingen jullie naar zee? — Drie jaar geleden.', en: 'When did you go to the seaside? — Three years ago.' },
    ],
  },
  {
    type: 'drill', title: 'toen, als or wanneer?', grammar: ['toen-past', 'als-inversion', 'question-word'], choices: ['Toen', 'Als', 'Wanneer'],
    instruction: 'One time in the past → toen. Now, the future, or “whenever” → als. A question → wanneer.',
    items: [
      { nl: '___ Bram klein was, woonde hij in Oostende.', answer: 'Toen' },
      { nl: '___ het morgen regent, gaan wij niet naar het strand.', answer: 'Als' },
      { nl: '___ ga jij naar zee?', answer: 'Wanneer' },
      { nl: '___ het regende, speelden de kinderen in de keuken.', en: 'Whenever it rained, the children played in the kitchen.', answer: 'Als' },
      { nl: '___ de trein aankwam, stond oma op het station.', answer: 'Toen' },
      { nl: '___ was dat? — Drie jaar geleden.', answer: 'Wanneer' },
      { nl: '___ Lotte twaalf jaar was, ging zij met Tom naar Oostende.', answer: 'Toen' },
      { nl: '___ jij morgen naar Gent gaat, kom ik mee.', answer: 'Als' },
    ],
    explanation: 'Als het regende: a habit, every time. Toen de trein aankwam: one arrival, one moment. Wanneer only asks.',
  },
  {
    type: 'drill', title: 'Join with toen', grammar: ['toen-past', 'verb-final', 'als-inversion', 'imperfect-strong', 'imperfect-weak', 'separable-together'],
    task: 'Join with toen — toen-clause first',
    instruction: 'The first sentence becomes the toen-clause, with its verb at the end. Then the main clause starts with its verb.',
    items: [
      { nl: 'Ik was klein. Ik woonde aan zee.', answer: 'Toen ik klein was, woonde ik aan zee.' },
      { nl: 'Bram was zes jaar. Hij leerde zwemmen.', answer: 'Toen Bram zes jaar was, leerde hij zwemmen.' },
      { nl: 'De trein kwam aan. Oma stond op het station.', answer: 'Toen de trein aankwam, stond oma op het station.' },
      { nl: 'Het regende. Wij speelden in de keuken.', answer: 'Toen het regende, speelden wij in de keuken.' },
      { nl: 'Lotte was klein. Zij las veel boeken.', answer: 'Toen Lotte klein was, las zij veel boeken.' },
      { nl: 'Wij kwamen in Gent aan. Het regende.', answer: 'Toen wij in Gent aankwamen, regende het.' },
      { nl: 'Opa zag de foto. Hij was blij.', answer: 'Toen opa de foto zag, was hij blij.' },
      { nl: 'Bram stond op. Het was zeven uur.', answer: 'Toen Bram opstond, was het zeven uur.' },
      { nl: 'Oma en opa waren jong. Zij reisden veel.', answer: 'Toen oma en opa jong waren, reisden zij veel.' },
      { nl: 'Bram was twaalf jaar. Hij ging met zijn familie in Gent wonen.', answer: 'Toen Bram twaalf jaar was, ging hij met zijn familie in Gent wonen.' },
    ],
    explanation: 'kwam aan → toen de trein aankwam; stond op → toen Bram opstond: in the subclause the separable verb is one word again, at the end. After the comma: verb, then subject — was hij, stond oma, regende het.',
  },
  {
    type: 'drill', title: 'toen, vroeger, geleden at the front', grammar: ['toen-past', 'v2-inversion', 'inversion', 'question-word', 'yes-no-question', 'imperfect-weak', 'imperfect-strong'],
    instruction: 'Rewrite as the task says. A time word at the front takes the first place, so the verb comes second.',
    items: [
      { nl: 'Opa ging naar huis.', task: 'Start with “toen” (= then)', answer: 'Toen ging opa naar huis.' },
      { nl: 'Wij aten een ijsje.', task: 'Start with “toen” (= then)', answer: 'Toen aten wij een ijsje.' },
      { nl: 'Lotte woonde in Antwerpen.', task: 'Start with “vroeger”', answer: 'Vroeger woonde Lotte in Antwerpen.' },
      { nl: 'Jij had een kat.', task: 'Start with “vroeger”', answer: 'Vroeger had jij een kat.' },
      { nl: 'Bram belde zijn moeder.', task: 'Start with “een uur geleden”', answer: 'Een uur geleden belde Bram zijn moeder.' },
      { nl: 'Lotte kocht een boek.', task: 'Start with “twee dagen geleden”', answer: 'Twee dagen geleden kocht Lotte een boek.' },
      { nl: 'Toen ik klein was, woonde ik aan zee.', task: 'Put the main clause first', answer: 'Ik woonde aan zee, toen ik klein was.' },
      { nl: 'Toen het regende, speelden wij in de keuken.', task: 'Put the main clause first', answer: 'Wij speelden in de keuken, toen het regende.' },
      { nl: 'Bram was zes jaar.', task: 'Add “toen” (= at that time) after the verb', answer: 'Bram was toen zes jaar.' },
      { nl: 'Lotte ging twee weken geleden naar Antwerpen.', task: 'Ask with “wanneer”', answer: 'Wanneer ging Lotte naar Antwerpen?' },
      { nl: 'Jij woonde vroeger in Gent.', task: 'Make it a question', answer: 'Woonde jij vroeger in Gent?' },
      { nl: 'Jullie waren vroeger vaak aan zee.', task: 'Make it a question', answer: 'Waren jullie vroeger vaak aan zee?' },
    ],
    explanation: 'Toen ging opa (then) — toen opa ging (when): the position of the verb is the whole difference. With wanneer the time disappears, because it is what you ask about.',
  },
  {
    type: 'drill', title: 'Which past? Say it in Dutch', grammar: ['toen-past', 'imperfect-weak', 'imperfect-strong', 'perfect-hebben', 'perfect-zijn', 'want-omdat', 'separable-together'],
    instruction: 'Translate. The brackets tell you which past to use; otherwise either is accepted. “You” is one person unless it says plural.',
    items: [
      { en: 'When I was small, I lived by the sea.', answer: 'Toen ik klein was, woonde ik aan zee.', accept: ['Ik woonde aan zee, toen ik klein was.'] },
      { en: 'Did you swim yesterday? (perfect — one fact)', answer: 'Heb jij gisteren gezwommen?' },
      { en: 'Bram used to live in Ostend.', answer: 'Vroeger woonde Bram in Oostende.', accept: ['Bram woonde vroeger in Oostende.'] },
      { en: 'I was tired yesterday.', answer: 'Ik was gisteren moe.', accept: ['Gisteren was ik moe.'] },
      { en: 'Three days ago I found an old photo. (perfect)', answer: 'Drie dagen geleden heb ik een oude foto gevonden.', accept: ['Ik heb drie dagen geleden een oude foto gevonden.'] },
      { en: 'Grandma and grandpa had a small house.', answer: 'Oma en opa hadden een klein huis.' },
      { en: 'We had to wait, because the train arrived late. (use omdat)', answer: 'Wij moesten wachten, omdat de trein laat aankwam.' },
      { en: 'When did you (plural) go to the seaside?', answer: 'Wanneer gingen jullie naar zee?', accept: ['Wanneer zijn jullie naar zee gegaan?'] },
      { en: 'Then grandpa went home.', answer: 'Toen ging opa naar huis.', accept: ['Toen is opa naar huis gegaan.'] },
      { en: 'That was a long time ago.', answer: 'Dat is lang geleden.', accept: ['Dat was lang geleden.'] },
    ],
    explanation: '“Heb jij gisteren gezwommen?” — a single question about one fact: the perfect. “Ik was moe”: zijn prefers the simple past. “Dat is lang geleden”: Dutch looks at the distance from now, so it says is.',
  },
  {
    type: 'arrange', title: 'In the sea every day', grammar: ['toen-past', 'verb-final', 'imperfect-strong'],
    instruction: 'Build: “When Bram was small, he swam in the sea every day.” Two tiles are traps.',
    nl: 'Toen Bram klein was, zwom hij elke dag in de zee.', en: 'When Bram was small, he swam in the sea every day.', image: 'sea', distractors: ['zwemt', 'als'],
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', layout: 'table', title: 'Every verb you know, in the past — one person', grammar: ['imperfect-weak', 'imperfect-strong', 'zijn', 'hebben', 'gaan', 'subject-pronouns', 'modals'],
    instruction: 'Verbs from all fourteen lessons, singular. The small word under each person is the verb. Type the simple past.',
    items: [
      { label: 'ik', gloss: 'zijn', answer: 'was' },
      { label: 'jij', gloss: 'hebben', answer: 'had' },
      { label: 'zij', gloss: 'she · gaan', answer: 'ging' },
      { label: 'hij', gloss: 'komen', answer: 'kwam' },
      { label: 'ik', gloss: 'wonen', answer: 'woonde' },
      { label: 'jij', gloss: 'werken', answer: 'werkte' },
      { label: 'hij', gloss: 'lopen', answer: 'liep' },
      { label: 'ik', gloss: 'zitten', answer: 'zat' },
      { label: 'zij', gloss: 'she · slapen', answer: 'sliep' },
      { label: 'jij', gloss: 'koken', answer: 'kookte' },
      { label: 'hij', gloss: 'spelen', answer: 'speelde' },
      { label: 'ik', gloss: 'leren', answer: 'leerde' },
      { label: 'zij', gloss: 'she · praten', answer: 'praatte' },
      { label: 'hij', gloss: 'wachten', answer: 'wachtte' },
      { label: 'ik', gloss: 'lezen', answer: 'las' },
      { label: 'jij', gloss: 'eten', answer: 'at' },
      { label: 'hij', gloss: 'drinken', answer: 'dronk' },
      { label: 'zij', gloss: 'she · schrijven', answer: 'schreef' },
      { label: 'ik', gloss: 'heten', answer: 'heette' },
      { label: 'hij', gloss: 'kunnen', answer: 'kon' },
      { label: 'jij', gloss: 'spreken', answer: 'sprak' },
      { label: 'ik', gloss: 'helpen', answer: 'hielp' },
    ],
    explanation: 'Weak: woonde, werkte, kookte, speelde, leerde, praatte, wachtte, heette. Strong: was, had, ging, kwam, liep, zat, sliep, las, at, dronk, schreef, kon, sprak, hielp — no ending at all.',
  },
  {
    type: 'drill', layout: 'table', title: 'Every verb you know, in the past — more than one', grammar: ['imperfect-weak', 'imperfect-strong', 'modals', 'dt-rule', 'spelling-z-s', 'separable'],
    instruction: 'Now the plural: -ten / -den for weak verbs, -en for strong ones — with the spelling rules. The small word is the verb.',
    items: [
      { label: 'wij', gloss: 'willen', answer: 'wilden' },
      { label: 'zij', gloss: 'they · moeten', answer: 'moesten' },
      { label: 'jullie', gloss: 'mogen', answer: 'mochten' },
      { label: 'wij', gloss: 'rijden', answer: 'reden' },
      { label: 'jullie', gloss: 'helpen', answer: 'hielpen' },
      { label: 'wij', gloss: 'maken', answer: 'maakten' },
      { label: 'zij', gloss: 'they · kopen', answer: 'kochten' },
      { label: 'wij', gloss: 'zien', answer: 'zagen' },
      { label: 'jullie', gloss: 'doen', answer: 'deden' },
      { label: 'zij', gloss: 'they · vinden', answer: 'vonden' },
      { label: 'wij', gloss: 'zeggen', answer: 'zeiden' },
      { label: 'zij', gloss: 'they · denken', answer: 'dachten' },
      { label: 'jullie', gloss: 'weten', answer: 'wisten' },
      { label: 'wij', gloss: 'hopen', answer: 'hoopten' },
      { label: 'zij', gloss: 'they · vragen', answer: 'vroegen' },
      { label: 'wij', gloss: 'staan', answer: 'stonden' },
      { label: 'zij', gloss: 'they · bellen', answer: 'belden' },
      { label: 'wij', gloss: 'nemen', answer: 'namen' },
      { label: 'wij', gloss: 'reizen', answer: 'reisden' },
      { label: 'zij', gloss: 'they · spreken', answer: 'spraken' },
      { label: 'het', gloss: 'regenen', answer: 'regende' },
    ],
    explanation: 'reden (rijden) looks like nothing you know: re-den, an open syllable with a long e. namen is also the plural of naam — context tells you which. kochten, dachten: the irregular weak verbs add -en to kocht and dacht.',
  },
  {
    type: 'drill', title: 'Two verbs in the past', grammar: ['imperfect-strong', 'modals', 'infinitive-end', 'separable-together', 'gaan'],
    task: 'Put it in the simple past',
    instruction: 'Only the first verb changes. The infinitive stays at the end — and a separable infinitive stays in one piece.',
    items: [
      { nl: 'Ik kan goed zwemmen.', answer: 'Ik kon goed zwemmen.' },
      { nl: 'Lotte wil naar zee gaan.', answer: 'Lotte wilde naar zee gaan.' },
      { nl: 'Wij moeten om zeven uur opstaan.', answer: 'Wij moesten om zeven uur opstaan.' },
      { nl: 'De kinderen mogen een ijsje eten.', answer: 'De kinderen mochten een ijsje eten.' },
      { nl: 'Jij kunt niet komen.', answer: 'Jij kon niet komen.' },
      { nl: 'Bram moet zijn moeder opbellen.', answer: 'Bram moest zijn moeder opbellen.' },
      { nl: 'Mag jij in de zee zwemmen?', answer: 'Mocht jij in de zee zwemmen?' },
      { nl: 'Zij willen niet naar huis gaan.', answer: 'Zij wilden niet naar huis gaan.' },
      { nl: 'Oma gaat een foto maken.', answer: 'Oma ging een foto maken.' },
      { nl: 'Wij kunnen het niet begrijpen.', answer: 'Wij konden het niet begrijpen.' },
      { nl: 'Kun jij vroeg opstaan?', answer: 'Kon jij vroeg opstaan?' },
    ],
    explanation: 'Kun jij → Kon jij: in the present jij loses its t behind the verb; in the past there is nothing to lose. moest … opbellen, moesten … opstaan: after a modal the separable verb is one word at the end.',
  },
  {
    type: 'drill', title: 'Separable verbs in the past', grammar: ['separable', 'separable-together', 'separable-perfect', 'imperfect-strong', 'imperfect-weak', 'verb-final', 'dat-clause', 'toen-past'],
    instruction: 'Rewrite as the task says. In a main clause the particle goes to the end; in a subclause the verb is one word, at the end.',
    items: [
      { nl: 'Bram staat om zeven uur op.', task: 'Put it in the simple past', answer: 'Bram stond om zeven uur op.' },
      { nl: 'Oma neemt brood en kaas mee.', task: 'Put it in the simple past', answer: 'Oma nam brood en kaas mee.' },
      { nl: 'De trein komt om tien uur aan.', task: 'Put it in the simple past', answer: 'De trein kwam om tien uur aan.' },
      { nl: 'Lotte belt Tom op.', task: 'Put it in the simple past', answer: 'Lotte belde Tom op.' },
      { nl: 'Wij zijn vorige week met Emma en Jonas uitgegaan.', task: 'Put it in the simple past', answer: 'Wij gingen vorige week met Emma en Jonas uit.' },
      { nl: 'Jij bent vroeg opgestaan.', task: 'Put it in the simple past', answer: 'Jij stond vroeg op.' },
      { nl: 'Bram stond vroeg op.', task: 'Start with “Ik weet dat”', answer: 'Ik weet dat Bram vroeg opstond.' },
      { nl: 'Bram belde zijn moeder op.', task: 'Start with “Lotte zegt dat”', answer: 'Lotte zegt dat Bram zijn moeder opbelde.' },
      { nl: 'De trein kwam laat aan.', task: 'Start with “Wij moesten wachten, omdat”', answer: 'Wij moesten wachten, omdat de trein laat aankwam.' },
      { nl: 'Wij gingen uit. Het regende.', task: 'Join with toen — toen-clause first', answer: 'Toen wij uitgingen, regende het.' },
      { nl: 'Oma nam brood mee.', task: 'Start with “Ik denk dat”', answer: 'Ik denk dat oma brood meenam.' },
    ],
    explanation: 'stond … op / dat hij opstond; belde … op / dat hij opbelde; kwam … aan / omdat de trein aankwam. The rule of lesson 13 does not care about the tense.',
  },
  {
    type: 'drill', title: 'The past at the end of the clause', grammar: ['verb-final', 'dat-clause', 'want-omdat', 'als-inversion', 'toen-past', 'imperfect-weak', 'imperfect-strong'],
    instruction: 'Type the simple past of the verb given. In a subclause it stands at the end; after want the order is normal.',
    items: [
      { nl: 'Bram was moe, omdat hij niet goed ___.', cue: 'slapen', answer: 'sliep' },
      { nl: 'Ik wist niet dat jij vroeger in Gent ___.', cue: 'wonen', answer: 'woonde' },
      { nl: 'Lotte zei dat het water koud ___.', cue: 'zijn', answer: 'was' },
      { nl: 'Als het ___, speelden wij in de keuken.', cue: 'regenen', en: 'Whenever it rained, we played in the kitchen.', answer: 'regende' },
      { nl: 'Wij gingen niet naar het strand, want het ___ koud.', cue: 'zijn', answer: 'was' },
      { nl: 'Opa vroeg wanneer de trein ___.', cue: 'aankomen', answer: 'aankwam' },
      { nl: 'Bram was blij, omdat hij een ijsje ___ eten.', cue: 'mogen', answer: 'mocht' },
      { nl: 'Weet jij waar oma en opa vroeger ___?', cue: 'wonen', answer: 'woonden' },
      { nl: 'Toen Sofie de schelp ___, was zij heel blij.', cue: 'vinden', answer: 'vond' },
      { nl: 'Ik weet dat Lotte in Antwerpen ___.', cue: 'opgroeien', en: 'I know that Lotte grew up in Antwerp.', answer: 'opgroeide' },
      { nl: 'Wat deed jij, toen jij klein ___?', cue: 'zijn', answer: 'was' },
      { nl: 'Bram zegt dat hij vroeger elke dag ___.', cue: 'zwemmen', answer: 'zwom' },
    ],
    explanation: 'Opa vroeg — here vroeg is the past of vragen, not “early”. omdat hij een ijsje mocht eten: modal first, infinitive last, as in the present.',
  },
  {
    type: 'drill', title: 'Comparing, then', grammar: ['comparative', 'superlative', 'dan-als', 'imperfect-weak', 'imperfect-strong', 'adjective-e'],
    instruction: 'Type the right form of the word given: -er for “more”, het / de … -st(e) for “most”, even … als for “as … as”.',
    items: [
      { nl: 'Vroeger was de trein ___ dan nu.', cue: 'langzaam', answer: 'langzamer' },
      { nl: 'Een ijsje was toen ___ dan nu.', cue: 'goedkoop', answer: 'goedkoper' },
      { nl: 'De zee was ___ dan het zand.', cue: 'koud', answer: 'kouder' },
      { nl: 'Opa was ___ dan oma.', cue: 'lang', en: 'Grandpa was taller than grandma.', answer: 'langer' },
      { nl: 'De vakantie was altijd ___ dan wij wilden.', cue: 'kort', answer: 'korter' },
      { nl: 'Sofie zwom even ___ als Bram.', cue: 'snel', answer: 'snel' },
      { nl: 'Het was de ___ dag van de vakantie.', cue: 'warm', en: 'It was the warmest day of the holiday.', answer: 'warmste' },
      { nl: 'Het examen was ___ dan Lotte dacht.', cue: 'makkelijk', answer: 'makkelijker' },
      { nl: 'Het boek was ___ dan de film.', cue: 'moeilijk', answer: 'moeilijker' },
      { nl: 'Een auto was vroeger ook al ___.', cue: 'duur', en: 'A car was already expensive back then too.', answer: 'duur' },
      { nl: 'Oma kookte het ___.', cue: 'goed', en: 'Grandma cooked best.', answer: 'best' },
      { nl: 'Bram at ___ ijsjes dan Sofie.', cue: 'veel', answer: 'meer' },
      { nl: 'Lotte las het ___ in de tuin.', cue: 'graag', en: 'Lotte liked reading in the garden best.', answer: 'liefst' },
      { nl: 'De trein was ___ dan de fiets.', cue: 'snel', answer: 'sneller' },
    ],
    explanation: 'langzaam → langzamer (the open syllable needs only one a), koud → kouder, lang → langer. even snel als: the plain form. de warmste dag: -st + -e before a noun. goed → beter → best, veel → meer, graag → liever → het liefst.',
  },
  {
    type: 'drill', title: 'Everything so far, now in the past', grammar: ['er-is-zijn', 'plural', 'numbers', 'possessives', 'wie-hoe', 'adjective-e', 'geen-niet', 'geen', 'niet', 'days-op-om', 'clock-time', 'hij-het-things', 'dit-is', 'de-het', 'question-word'],
    instruction: 'Type the missing word. Every grammar point from lesson 1 on, inside sentences about the past.',
    items: [
      { nl: 'Er ___ vier stoelen in de keuken van oma.', cue: 'zijn (past)', answer: 'waren' },
      { nl: 'Er ___ een oude bank in de tuin.', cue: 'zijn (past)', answer: 'was' },
      { nl: 'Oma had drie ___.', cue: 'kat', answer: 'katten' },
      { nl: 'Sofie vond twee mooie ___.', cue: 'schelp', answer: 'schelpen' },
      { nl: 'Bram en Sofie maakten vijf ___.', cue: 'zandkasteel', answer: 'zandkastelen' },
      { nl: 'Lotte speelde vroeger met ___ broer.', en: 'Lotte used to play with her brother.', answer: 'haar' },
      { nl: 'Oma en opa woonden in een klein huis. ___ huis was heel oud.', en: 'Their house was very old.', answer: 'Hun' },
      { nl: 'Opa had een ___ auto.', cue: 'oud', answer: 'oude' },
      { nl: 'Oostende had een ___ strand.', cue: 'mooi', answer: 'mooi' },
      { nl: 'Wij hadden ___ auto.', en: 'We had no car.', answer: 'geen' },
      { nl: 'Het water was ___ warm.', en: 'The water was not warm.', answer: 'niet' },
      { nl: 'De trein kwam ___ zeven uur aan.', cue: 'op / om', answer: 'om' },
      { nl: 'Wij gingen ___ zaterdag altijd naar zee.', cue: 'op / om', answer: 'op' },
      { nl: 'Het was half ___.', en: 'It was half past three.', answer: 'vier' },
      { nl: 'Het zandkasteel was groot. ___ was heel mooi.', cue: 'hij / het', answer: 'Het' },
      { nl: '___ was dat? — Dat was opa.', answer: 'Wie' },
      { nl: '___ oud was jij toen?', answer: 'Hoe' },
      { nl: 'Hoeveel ___ hadden oma en opa?', cue: 'kind', answer: 'kinderen' },
      { image: 'photo', nl: 'Wat is dit?', answer: 'Dit is een foto.', accept: ['Dit is een oude foto.', 'Dit is de foto.'] },
      { nl: '___ strand', cue: 'de / het', answer: 'het' },
    ],
    explanation: 'er was + one thing, er waren + more. een mooi strand: een + het-word, no -e. om + clock time, op + day. half vier = 3:30. het zandkasteel → het.',
  },
  {
    type: 'arrange', title: 'When the train arrived', grammar: ['toen-past', 'separable-together', 'imperfect-strong'],
    instruction: 'Build: “When the train arrived, grandma and grandpa were standing on the platform.” Two tiles are traps.',
    nl: 'Toen de trein aankwam, stonden oma en opa op het station.', en: 'When the train arrived, grandma and grandpa were standing on the platform.', image: 'station', distractors: ['kwam', 'stond'],
  },
  {
    type: 'arrange', title: 'Colder than the sand', grammar: ['comparative', 'dan-als', 'imperfect-strong'],
    instruction: 'Build: “The sea was colder than the sand, but we swam every day.” Two tiles are traps.',
    nl: 'De zee was kouder dan het zand, maar wij zwommen elke dag.', en: 'The sea was colder than the sand, but we swam every day.', image: 'sea', distractors: ['als', 'zwom'],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Een oude foto', image: 'photo', grammar: ['toen-past', 'imperfect-weak', 'imperfect-strong', 'perfect-hebben', 'verb-final', 'v2-inversion', 'possessives', 'days-op-om', 'modals'],
    instruction: 'A Sunday in Gent. Read and listen to every line, then read it again without the English. Underline — in your head — every simple past.',
    lines: [
      { nl: 'Het is zondag. Bram en Lotte zijn in Gent, bij de vader en moeder van Bram.', en: 'It is Sunday. Bram and Lotte are in Ghent, at Bram’s father and mother’s.', image: 'family' },
      { nl: 'De moeder van Bram heeft een oude foto gevonden.', en: 'Bram’s mother has found an old photo.', image: 'photo' },
      { speaker: 'Moeder', nl: 'Lotte, dit is Bram, toen hij zes jaar was.', en: 'Lotte, this is Bram, when he was six.', image: 'photo' },
      { speaker: 'Lotte', nl: 'Wat een lief kind! Waar was dat?', en: 'What a sweet child! Where was that?', image: 'child-beach' },
      { speaker: 'Bram', nl: 'Op het strand van Oostende. Toen woonden wij nog aan zee.', en: 'On the beach at Ostend. We still lived by the sea then.', image: 'sea' },
      { speaker: 'Moeder', nl: 'In de vakantie moesten wij werken. Bram en Sofie gingen elke dag met oma en opa naar het strand.', en: 'In the holidays we had to work. Bram and Sofie went to the beach with grandma and grandpa every day.', image: 'grandparents' },
      { speaker: 'Lotte', nl: 'Wat deden jullie op het strand, Bram?', en: 'What did you do on the beach, Bram?', image: 'woman' },
      { speaker: 'Bram', nl: 'Wij maakten zandkastelen en zwommen in de zee. Het water was altijd koud!', en: 'We made sandcastles and swam in the sea. The water was always cold!', image: 'child-beach' },
      { speaker: 'Bram', nl: 'Ik leerde zwemmen met opa. En om vier uur kocht opa altijd een ijsje.', en: 'I learnt to swim with grandpa. And at four o’clock grandpa always bought an ice cream.', image: 'grandparents' },
      { speaker: 'Moeder', nl: 'En Sofie vond elke dag mooie schelpen.', en: 'And Sofie found beautiful shells every day.', image: 'child-beach' },
      { speaker: 'Lotte', nl: 'Ik ben in Antwerpen opgegroeid. In Antwerpen hadden wij geen strand.', en: 'I grew up in Antwerp. In Antwerp we had no beach.', image: 'woman' },
      { speaker: 'Lotte', nl: 'Maar in de vakantie gingen Tom en ik met de trein naar zee.', en: 'But in the holidays Tom and I went to the seaside by train.', image: 'train' },
      { speaker: 'Bram', nl: 'Naar Oostende?', en: 'To Ostend?', image: 'man' },
      { speaker: 'Lotte', nl: 'Ja! Misschien speelden wij toen al samen op het strand!', en: 'Yes! Maybe we were already playing together on the beach back then!', image: 'couple-talking' },
      { speaker: 'Moeder', nl: 'Dat is lang geleden. Een ijsje was toen nog goedkoop!', en: 'That was a long time ago. An ice cream was still cheap then!', image: 'mother' },
      { speaker: 'Bram', nl: 'Wanneer gingen wij in Gent wonen? Toen ik twaalf was?', en: 'When did we go to live in Ghent? When I was twelve?', image: 'man-thinking' },
      { speaker: 'Moeder', nl: 'Ja. En jij wilde niet weg van de zee.', en: 'Yes. And you didn’t want to leave the sea.', image: 'mother' },
      { nl: 'Lotte kijkt nog lang naar de foto van de kleine Bram.', en: 'Lotte looks at the photo of little Bram for a long time.', image: 'photo' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'inversion', 'imperfect-strong'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the story. Answer without looking back.',
    items: [
      { nl: 'Zijn Bram en Lotte in Gent?', answer: 'Ja' },
      { nl: 'Woonde Bram vroeger in Antwerpen?', answer: 'Nee' },
      { nl: 'Gingen Bram en Sofie in de vakantie met oma en opa naar het strand?', answer: 'Ja' },
      { nl: 'Was het water warm?', answer: 'Nee' },
      { nl: 'Kocht opa om vier uur een ijsje?', answer: 'Ja' },
      { nl: 'Is Lotte in Oostende opgegroeid?', answer: 'Nee' },
      { nl: 'Ging Lotte in de vakantie met de trein naar zee?', answer: 'Ja' },
      { nl: 'Wilde Bram graag weg van de zee?', answer: 'Nee' },
    ],
  },
  {
    type: 'drill', title: 'Answer in full', grammar: ['toen-past', 'imperfect-weak', 'imperfect-strong', 'want-omdat', 'verb-final', 'question-word', 'wie-hoe', 'clock-time'],
    instruction: 'Answer each question about the story with a complete sentence in the simple past (the perfect for Lotte growing up is fine too).',
    items: [
      { nl: 'Waar woonde Bram, toen hij klein was?', answer: 'Toen Bram klein was, woonde hij in Oostende.', accept: ['Bram woonde in Oostende.', 'Hij woonde in Oostende.', 'Toen hij klein was, woonde hij in Oostende.', 'Bram woonde in Oostende, toen hij klein was.', 'Hij woonde in Oostende, toen hij klein was.', 'Bram woonde aan zee, in Oostende.', 'Hij woonde aan zee, in Oostende.', 'In Oostende.'] },
      { nl: 'Wat deden Bram en Sofie op het strand?', answer: 'Zij maakten zandkastelen en zwommen in de zee.', accept: ['Bram en Sofie maakten zandkastelen en zwommen in de zee.', 'Zij maakten zandkastelen.', 'Bram en Sofie maakten zandkastelen.', 'Zij zwommen in de zee en maakten zandkastelen.'] },
      { nl: 'Hoe was het water?', answer: 'Het water was koud.', accept: ['Het was koud.', 'Het water was altijd koud.', 'Het was altijd koud.', 'Koud.'] },
      { nl: 'Hoe laat kocht opa een ijsje?', answer: 'Opa kocht om vier uur een ijsje.', accept: ['Hij kocht om vier uur een ijsje.', 'Om vier uur kocht opa een ijsje.', 'Om vier uur kocht hij een ijsje.', 'Opa kocht om vier uur altijd een ijsje.', 'Om vier uur.'] },
      { nl: 'Wat vond Sofie?', answer: 'Sofie vond mooie schelpen.', accept: ['Zij vond mooie schelpen.', 'Sofie vond elke dag mooie schelpen.', 'Zij vond elke dag mooie schelpen.', 'Sofie vond schelpen.', 'Zij vond schelpen.', 'Mooie schelpen.'] },
      { nl: 'Waar is Lotte opgegroeid?', answer: 'Lotte is in Antwerpen opgegroeid.', accept: ['Zij is in Antwerpen opgegroeid.', 'Lotte groeide op in Antwerpen.', 'Zij groeide op in Antwerpen.', 'Lotte groeide in Antwerpen op.', 'Zij groeide in Antwerpen op.', 'In Antwerpen.'] },
      { nl: 'Hoe ging Lotte in de vakantie naar zee?', answer: 'Lotte ging met de trein naar zee.', accept: ['Zij ging met de trein naar zee.', 'Lotte ging in de vakantie met de trein naar zee.', 'Zij ging in de vakantie met de trein naar zee.', 'Met de trein.'] },
      { nl: 'Hoe oud was Bram, toen zij in Gent gingen wonen?', answer: 'Bram was twaalf jaar.', accept: ['Hij was twaalf jaar.', 'Bram was twaalf.', 'Hij was twaalf.', 'Bram was toen twaalf jaar.', 'Hij was toen twaalf jaar.', 'Twaalf jaar.', 'Twaalf.'] },
      { nl: 'Bram en Sofie gingen met oma en opa naar het strand.', task: 'Say why — use omdat', answer: 'Bram en Sofie gingen met oma en opa naar het strand, omdat hun vader en moeder moesten werken.', accept: ['Bram en Sofie gingen met oma en opa naar het strand, omdat hun vader en moeder werken moesten.', 'Bram en Sofie gingen met oma en opa naar het strand, omdat hun vader en moeder in de vakantie moesten werken.', 'Bram en Sofie gingen met oma en opa naar het strand, omdat hun vader en moeder in de vakantie werken moesten.'] },
      { nl: 'Was een ijsje toen duur?', answer: 'Nee, een ijsje was toen nog goedkoop.', accept: ['Nee, een ijsje was toen goedkoop.', 'Nee, het was toen nog goedkoop.', 'Nee, het was goedkoop.', 'Nee, een ijsje was goedkoop.', 'Nee, toen was een ijsje nog goedkoop.'] },
    ],
  },
  {
    type: 'story', title: 'Aan zee, lang geleden', image: 'child-beach', grammar: ['imperfect-weak', 'imperfect-strong', 'toen-past', 'separable', 'clock-time', 'superlative', 'perfect-hebben'],
    instruction: 'One day from the photo, told the way Dutch tells stories: in the simple past. The people speak in the present and the perfect — they are living it.',
    lines: [
      { nl: 'Het was vakantie, en de zon was warm.', en: 'It was the holidays, and the sun was warm.', image: 'sea' },
      { nl: 'Om acht uur stond Bram op. Sofie sliep nog.', en: 'At eight o’clock Bram got up. Sofie was still asleep.', image: 'child' },
      { nl: 'Oma maakte het ontbijt: brood met kaas, en thee.', en: 'Grandma made breakfast: bread and cheese, and tea.', image: 'breakfast' },
      { speaker: 'Opa', nl: 'Kinderen, wij gaan naar zee! Wie gaat er mee?', en: 'Children, we are going to the seaside! Who is coming along?', image: 'grandparents' },
      { nl: 'Oma nam brood, water en appels mee.', en: 'Grandma took bread, water and apples along.', image: 'grandparents' },
      { nl: 'Zij liepen samen naar het strand. Opa liep langzaam.', en: 'They walked to the beach together. Grandpa walked slowly.', image: 'sea' },
      { nl: 'Op het strand maakten Bram en Sofie een groot zandkasteel.', en: 'On the beach Bram and Sofie made a big sandcastle.', image: 'child-beach' },
      { speaker: 'Sofie', nl: 'Oma, ik heb een mooie schelp gevonden!', en: 'Grandma, I have found a beautiful shell!', image: 'child-beach' },
      { nl: 'Bram wilde in de zee zwemmen, maar het water was koud.', en: 'Bram wanted to swim in the sea, but the water was cold.', image: 'sea' },
      { speaker: 'Opa', nl: 'Wij zwemmen samen, Bram. Dat is makkelijker.', en: 'We will swim together, Bram. That is easier.', image: 'grandparents' },
      { nl: 'Toen zwommen zij samen in de zee.', en: 'Then they swam in the sea together.', image: 'sea' },
      { nl: 'Om vier uur kocht opa ijsjes. Het was de mooiste dag van de vakantie.', en: 'At four o’clock grandpa bought ice creams. It was the most beautiful day of the holiday.', image: 'child-beach' },
      { nl: 'Oma maakte een foto van Bram en Sofie met hun ijsje.', en: 'Grandma took a photo of Bram and Sofie with their ice creams.', image: 'photo' },
      { nl: 'De moeder van Bram heeft de foto nog altijd.', en: 'Bram’s mother still has the photo.', image: 'photo' },
    ],
  },
  {
    type: 'drill', title: 'Tell it back', grammar: ['imperfect-weak', 'imperfect-strong', 'separable', 'clock-time', 'question-word', 'wie-hoe'],
    instruction: 'Answer about the second story, with a complete sentence in the simple past.',
    items: [
      { nl: 'Hoe laat stond Bram op?', answer: 'Bram stond om acht uur op.', accept: ['Hij stond om acht uur op.', 'Om acht uur stond Bram op.', 'Om acht uur stond hij op.', 'Om acht uur.'] },
      { nl: 'Wat maakte oma?', answer: 'Oma maakte het ontbijt.', accept: ['Zij maakte het ontbijt.', 'Oma maakte ontbijt.', 'Zij maakte ontbijt.', 'Het ontbijt.'] },
      { nl: 'Wat nam oma mee?', answer: 'Oma nam brood, water en appels mee.', accept: ['Zij nam brood, water en appels mee.', 'Brood, water en appels.'] },
      { nl: 'Hoe liep opa?', answer: 'Opa liep langzaam.', accept: ['Hij liep langzaam.', 'Langzaam.'] },
      { nl: 'Wat maakten Bram en Sofie op het strand?', answer: 'Zij maakten een groot zandkasteel.', accept: ['Bram en Sofie maakten een groot zandkasteel.', 'Zij maakten een zandkasteel.', 'Bram en Sofie maakten een zandkasteel.', 'Een groot zandkasteel.', 'Een zandkasteel.'] },
      { nl: 'Wat vond Sofie?', answer: 'Sofie vond een mooie schelp.', accept: ['Zij vond een mooie schelp.', 'Sofie vond een schelp.', 'Zij vond een schelp.', 'Een mooie schelp.'] },
      { nl: 'Wie zwom met Bram in de zee?', answer: 'Opa zwom met Bram in de zee.', accept: ['Opa zwom met Bram.', 'Opa zwom met hem in de zee.', 'Opa.'] },
      { nl: 'Wanneer kocht opa ijsjes?', answer: 'Opa kocht om vier uur ijsjes.', accept: ['Om vier uur kocht opa ijsjes.', 'Hij kocht om vier uur ijsjes.', 'Om vier uur kocht hij ijsjes.', 'Om vier uur.'] },
      { nl: 'Wie maakte een foto?', answer: 'Oma maakte een foto.', accept: ['Oma maakte een foto van Bram en Sofie.', 'Oma.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['toen-past', 'imperfect-weak', 'imperfect-strong'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'Toen ik klein was, woonde ik aan zee.' },
      { listen: 'Vroeger gingen wij elke dag naar het strand.' },
      { listen: 'Oma en opa waren heel lief.' },
      { listen: 'Drie jaar geleden reisden wij met de trein naar Oostende.' },
      { listen: 'Sofie vond een mooie schelp.' },
      { listen: 'Het water was kouder dan het zand.' },
      { listen: 'Wij wachtten een uur op de trein.' },
      { listen: 'Lotte is in Antwerpen opgegroeid.' },
      { listen: 'Toen de trein aankwam, stond opa op het station.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['toen-past', 'imperfect-weak', 'imperfect-strong', 'comparative', 'adjective-e', 'dat-clause', 'als-inversion', 'separable'],
    instruction: 'Translate. Use the simple past unless the brackets say otherwise. “You” is one person unless it says plural.',
    items: [
      { en: 'Grandma and grandpa used to live in Ostend.', answer: 'Vroeger woonden oma en opa in Oostende.', accept: ['Oma en opa woonden vroeger in Oostende.'] },
      { en: 'We went to the beach every day.', answer: 'Wij gingen elke dag naar het strand.', accept: ['Elke dag gingen wij naar het strand.'] },
      { en: 'In the holidays we often slept at grandma and grandpa’s.', answer: 'In de vakantie sliepen wij vaak bij oma en opa.', accept: ['Wij sliepen in de vakantie vaak bij oma en opa.'] },
      { en: 'The water was cold, but the sand was warm.', answer: 'Het water was koud, maar het zand was warm.' },
      { en: 'Two weeks ago Lotte bought a new book.', answer: 'Twee weken geleden kocht Lotte een nieuw boek.', accept: ['Lotte kocht twee weken geleden een nieuw boek.', 'Twee weken geleden heeft Lotte een nieuw boek gekocht.', 'Lotte heeft twee weken geleden een nieuw boek gekocht.'] },
      { en: 'Could you swim when you were six?', answer: 'Kon jij zwemmen, toen jij zes jaar was?', accept: ['Kon jij zwemmen, toen jij zes was?'] },
      { en: 'Grandpa always took bread and cheese along.', answer: 'Opa nam altijd brood en kaas mee.', accept: ['Opa nam altijd brood met kaas mee.'] },
      { en: 'Lotte looked at the old photo.', answer: 'Lotte keek naar de oude foto.' },
      { en: 'Later they went to live in Ghent.', answer: 'Later gingen zij in Gent wonen.' },
      { en: 'Then we ate an ice cream.', answer: 'Toen aten wij een ijsje.', accept: ['Toen hebben wij een ijsje gegeten.'] },
      { en: 'I didn’t know that you used to live in Ghent.', answer: 'Ik wist niet dat jij vroeger in Gent woonde.' },
      { en: 'The holiday was shorter than last year.', answer: 'De vakantie was korter dan vorig jaar.' },
      { en: 'Whenever it rained, we played in the kitchen.', answer: 'Als het regende, speelden wij in de keuken.', accept: ['Wij speelden in de keuken, als het regende.'] },
      { en: 'Did you (plural) travel a lot in the past?', answer: 'Reisden jullie vroeger veel?', accept: ['Hebben jullie vroeger veel gereisd?'] },
      { en: 'This is a photo of grandma.', answer: 'Dit is een foto van oma.' },
    ],
  },
  {
    type: 'drill', title: 'Tell it as a story', grammar: ['imperfect-weak', 'imperfect-strong', 'separable', 'v2-inversion', 'modals', 'infinitive-end', 'niet'],
    task: 'Put it in the simple past',
    instruction: 'A day at the sea, in the present. Tell it as a story: every verb into the simple past, nothing else changes.',
    items: [
      { nl: 'Het is vakantie.', answer: 'Het was vakantie.' },
      { nl: 'Bram staat om acht uur op.', answer: 'Bram stond om acht uur op.' },
      { nl: 'Hij eet brood met kaas.', answer: 'Hij at brood met kaas.' },
      { nl: 'Oma drinkt thee en opa drinkt koffie.', answer: 'Oma dronk thee en opa dronk koffie.' },
      { nl: 'Om negen uur gaan zij naar het strand.', answer: 'Om negen uur gingen zij naar het strand.' },
      { nl: 'Opa neemt een oude stoel mee.', answer: 'Opa nam een oude stoel mee.' },
      { nl: 'Oma zit op de stoel en leest een boek.', answer: 'Oma zat op de stoel en las een boek.' },
      { nl: 'De kinderen spelen in het zand.', answer: 'De kinderen speelden in het zand.' },
      { nl: 'Bram wil zwemmen, maar het water is koud.', answer: 'Bram wilde zwemmen, maar het water was koud.' },
      { nl: 'Sofie vindt drie schelpen.', answer: 'Sofie vond drie schelpen.' },
      { nl: 'Het regent niet, en de zon is warm.', answer: 'Het regende niet, en de zon was warm.' },
      { nl: 'Om vijf uur zijn zij moe, en zij gaan naar huis.', answer: 'Om vijf uur waren zij moe, en zij gingen naar huis.' },
      { nl: 'Opa zegt: “Dat was een mooie dag!”', answer: 'Opa zei: “Dat was een mooie dag!”' },
    ],
    explanation: 'at, dronk, gingen, nam … mee, zat, las, vond, waren, zei: most of a story is strong verbs. speelden, wilde, regende: the weak ones with -de.',
  },
  {
    type: 'drill', title: 'Ask about the past', grammar: ['question-word', 'yes-no-question', 'inversion', 'wie-hoe', 'numbers', 'imperfect-weak', 'imperfect-strong', 'toen-past'],
    instruction: 'Rewrite each sentence as a question, as the task says. The question word comes first, then the verb.',
    items: [
      { nl: 'Bram woonde in Oostende.', task: 'Ask with “waar”', answer: 'Waar woonde Bram?' },
      { nl: 'Jij woonde vroeger aan zee.', task: 'Make it a question', answer: 'Woonde jij vroeger aan zee?' },
      { nl: 'Lotte las elke dag een boek.', task: 'Ask with “wat”', answer: 'Wat las Lotte elke dag?' },
      { nl: 'Opa kocht om vier uur een ijsje.', task: 'Ask with “hoe laat”', answer: 'Hoe laat kocht opa een ijsje?' },
      { nl: 'Jullie gingen drie jaar geleden naar zee.', task: 'Ask with “wanneer”', answer: 'Wanneer gingen jullie naar zee?' },
      { nl: 'Bram was toen zes jaar.', task: 'Ask with “hoe oud”', answer: 'Hoe oud was Bram toen?' },
      { nl: 'Oma en opa stonden op de foto.', task: 'Ask with “wie”', answer: 'Wie stonden op de foto?', accept: ['Wie stond op de foto?'] },
      { nl: 'Jij had een hond.', task: 'Make it a question', answer: 'Had jij een hond?' },
      { nl: 'Zij hadden drie katten.', task: 'Ask with “hoeveel”', answer: 'Hoeveel katten hadden zij?' },
      { nl: 'Jij kon goed zwemmen.', task: 'Make it a question', answer: 'Kon jij goed zwemmen?' },
      { nl: 'De kinderen speelden op het strand.', task: 'Ask with “waar”', answer: 'Waar speelden de kinderen?' },
    ],
    explanation: 'Woonde jij, Had jij, Kon jij: the past has no -t, so nothing drops. Hoe oud was Bram toen: toen (then) stays in its place in the middle.',
  },
  {
    type: 'drill', title: 'The whole lesson in one round', grammar: ['toen-past', 'imperfect-weak', 'imperfect-strong', 'verb-final', 'separable-together', 'dat-clause', 'comparative', 'plural', 'als-inversion', 'perfect-zijn'],
    instruction: 'A final, demanding round: everything from this lesson, mixed with the fourteen before it. Type every answer.',
    items: [
      { nl: 'Vroeger ___ Bram in Oostende.', cue: 'wonen', answer: 'woonde' },
      { nl: 'Wij ___ elke dag in de zee.', cue: 'zwemmen', answer: 'zwommen' },
      { nl: 'Opa ___ een uur op de trein.', cue: 'wachten', answer: 'wachtte' },
      { nl: 'Wij ___ geen jas, en het was koud.', cue: 'hebben', answer: 'hadden' },
      { nl: 'Toen de trein ___, stond oma op het station.', cue: 'aankomen', answer: 'aankwam' },
      { nl: 'Hij ___ het niet.', cue: 'weten', en: 'He didn’t know.', answer: 'wist' },
      { nl: 'Lotte ___: “Waar is Tom?”', cue: 'vragen', en: 'Lotte asked: “Where is Tom?”', answer: 'vroeg' },
      { nl: 'Ik ben vorige week naar zee gegaan.', task: 'Put it in the simple past', answer: 'Ik ging vorige week naar zee.' },
      { nl: 'Ik was klein. Ik speelde elke dag op het strand.', task: 'Join with toen — toen-clause first', answer: 'Toen ik klein was, speelde ik elke dag op het strand.' },
      { nl: 'Oma kookte elke dag.', task: 'Start with “vroeger”', answer: 'Vroeger kookte oma elke dag.' },
      { nl: 'Lotte kocht een boek.', task: 'Start with “een week geleden”', answer: 'Een week geleden kocht Lotte een boek.' },
      { nl: 'Bram stond vroeg op.', task: 'Start with “Ik weet dat”', answer: 'Ik weet dat Bram vroeg opstond.' },
      { nl: 'Jij woonde aan zee.', task: 'Make it a question', answer: 'Woonde jij aan zee?' },
      { en: 'The sea was colder than the sand.', answer: 'De zee was kouder dan het zand.' },
      { en: 'Whenever it rained, we read a book.', answer: 'Als het regende, lazen wij een boek.', accept: ['Wij lazen een boek, als het regende.'] },
      { en: 'Then grandma took a photo.', answer: 'Toen maakte oma een foto.', accept: ['Toen heeft oma een foto gemaakt.'] },
      { nl: 'twee ___', cue: 'zandkasteel', answer: 'zandkastelen' },
      { listen: 'Toen Bram klein was, ging hij in de vakantie met oma en opa naar zee.' },
    ],
  },
  {
    type: 'complete', title: 'Toen ik klein was',
    instruction: 'Two past tenses now: the perfect for a single fact, the simple past for a story — woonde, werkte, was, had, ging, kwam, and the rest. With toen, vroeger and geleden you can tell where you come from. Vroeger sprak jij geen Nederlands. Nu spreek jij het elke dag.',
  },
];
