/**
 * Lesson 18 — De buurman die altijd leest.
 * Targets: buurman, buurvrouw, collega, student, universiteit, les, leraar, antwoord, kennen, ontmoeten.
 * Structure: die. Extra vocabulary (vocabulary/die-dat.js): studeren, kantoor, vak, mens, naast, geven,
 * bezoeken, vertellen, gebeuren — and “de buren”, the plural of buurman.
 * Grammar: relative clauses with die and dat · kennen or weten · participles without ge-.
 * The capstone of volume two: the separable verbs, comparatives, simple past, reflexives, imperative,
 * zullen, te and over / geleden of lessons 13–17 return inside relative clauses, about every person in the book.
 * Teaching choices, as in lesson 12: in a subordinate clause the course writes “ontmoet heb” (participle,
 * then the conjugated verb) and “kan spreken” (modal, then infinitive); the other orders are always accepted.
 * Short answers use “die” where spoken Dutch does (“Ja, die ken ik”); hem / haar (lesson 13) are accepted
 * and taught beside it. The relative clause after a final participle or infinitive (“Ik heb de vrouw ontmoet
 * die …”) and the one before it are both accepted. The plural “collega’s” is written with the ’s of lesson 13.
 * Strict kennen / weten: iemand of een plaats kennen; het antwoord, zijn naam weten; een taal spreken or kennen.
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'The people next door', grammar: ['relative-clause', 'possessives', 'plural'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice. In the last three, listen for “die” and “dat”, and for the verb that waits until the end.',
    cards: [
      { nl: 'Dit is onze buurman. Hij woont naast ons.', en: 'This is our neighbour. He lives next door to us.', image: 'old-man' },
      { nl: 'De buurman zit elke dag op de bank en leest.', en: 'The neighbour sits on the bench every day and reads.', image: 'old-man' },
      { nl: 'Dit is de buurvrouw, zijn vrouw.', en: 'This is the neighbour — his wife.', image: 'old-woman' },
      { nl: 'De buurman en de buurvrouw zijn onze buren.', en: 'The neighbour and his wife are our neighbours.', image: 'neighbours' },
      { nl: 'De buren hebben twee katten.', en: 'The neighbours have two cats.', image: 'cats-two' },
      { nl: 'In de winter leest de buurman thuis, in de zomer op de bank.', en: 'In winter the neighbour reads at home, in summer on the bench.', image: 'old-man' },
      { nl: 'Bram helpt de oude buurman in de tuin.', en: 'Bram helps the old neighbour in the garden.', image: 'man-helping' },
      { nl: 'De buurman is de man die altijd leest.', en: 'The neighbour is the man who always reads.', image: 'old-man' },
      { nl: 'Noor is het kind dat in onze straat woont.', en: 'Noor is the child who lives in our street.', image: 'child' },
      { nl: 'Kennen jullie de mensen die in jullie straat wonen?', en: 'Do you know the people who live in your street?', image: 'neighbourhood' },
    ],
    note: '“de buurman” is a man next door, “de buurvrouw” a woman; together they are “de buren”. “naast” = next to — naast ons: next door to us. “de mensen” = people (one person: “een mens”). After a noun, “die” and “dat” mean who / which / that — the grammar pages explain which one to use. kennen = to know a person or a place.',
  },
  {
    type: 'observe', title: 'University and office', grammar: ['er-is-zijn', 'days-op-om', 'over-geleden'],
    instruction: 'Lotte’s week and Bram’s office. Listen for the stress: u-ni-ver-si-TEIT, le-RAAR, col-LE-ga, stu-DENT.',
    cards: [
      { nl: 'Lotte is student. Zij studeert aan de universiteit in Leuven.', en: 'Lotte is a student. She studies at the university in Leuven.', image: 'students' },
      { nl: 'De universiteit is heel oud en heel groot.', en: 'The university is very old and very big.', image: 'university' },
      { nl: 'Er zijn veel studenten in Leuven.', en: 'There are a lot of students in Leuven.', image: 'students' },
      { nl: 'Lotte heeft dit jaar vijf vakken: vier zijn makkelijk, maar één vak is heel moeilijk.', en: 'Lotte has five subjects this year: four are easy, but one subject is very difficult.', image: 'woman-studying' },
      { nl: 'Lotte leert elke avond in haar kamer.', en: 'Lotte studies in her room every evening.', image: 'woman-studying' },
      { nl: 'Op dinsdag, donderdag en vrijdag heeft zij ook les.', en: 'She also has class on Tuesday, Thursday and Friday.', image: 'students' },
      { nl: 'Zij is twee weken geleden met een nieuwe cursus begonnen.', en: 'Two weeks ago she started a new course.', image: 'classroom' },
      { nl: 'De leraar van de cursus geeft elke maandag om zeven uur les.', en: 'The course teacher teaches every Monday at seven o’clock.', image: 'classroom' },
      { nl: 'Bram werkt in Brussel, in een groot kantoor met veel collega’s.', en: 'Bram works in Brussels, in a big office with a lot of colleagues.', image: 'colleagues' },
      { nl: 'Op maandag, dinsdag, woensdag en donderdag reist hij met de trein naar Brussel.', en: 'On Monday, Tuesday, Wednesday and Thursday he travels to Brussels by train.', image: 'train' },
      { nl: 'Bram heeft een collega die ook in Leuven woont.', en: 'Bram has a colleague who also lives in Leuven.', image: 'colleagues' },
      { nl: 'Weet jij het antwoord? — Nee, ik weet het niet.', en: 'Do you know the answer? — No, I don’t know.', image: 'exam' },
    ],
    note: 'studeren = to study at a university (leren = to learn, to study for a test). “Lotte is student” — no “een” before a job or a study, as in “Hij is leraar”. de les = the lesson, the class: “les hebben” = to have class, “les geven” = to teach (geven = to give). het vak = a subject, het kantoor = the office (op kantoor = at the office), het antwoord = the answer. de collega is a de-word; its plural is de collega’s — a word ending in a long vowel (a, o, u, i) takes ’s, as in ’s ochtends: de foto’s, de oma’s.',
  },
  {
    type: 'observe', title: 'Knowing and meeting people', grammar: ['kennen-weten', 'participle-no-ge', 'perfect-hebben', 'pijn-hebben'],
    instruction: 'Short conversations. Notice that Dutch has two verbs for “to know”, and that “ontmoet” has no ge-.',
    cards: [
      { nl: 'Ken jij de buurman? — Ja, die ken ik goed.', en: 'Do you know the neighbour? — Yes, I know him well.', image: 'old-man' },
      { nl: 'Weet jij hoe de buurman heet? — Nee, dat weet ik niet.', en: 'Do you know what the neighbour is called? — No, I don’t know.', image: 'old-man' },
      { nl: 'Lotte kent Leuven heel goed.', en: 'Lotte knows Leuven very well.', image: 'city' },
      { nl: 'Ik heb de buurvrouw gisteren ontmoet.', en: 'I met the neighbour yesterday.', image: 'old-woman' },
      { nl: 'Bram ontmoet zijn collega om negen uur op het station.', en: 'Bram is meeting his colleague at nine at the station.', image: 'station' },
      { nl: 'Zondag bezoeken wij de buren.', en: 'On Sunday we are visiting the neighbours.', image: 'neighbours' },
      { nl: 'De buurman vertelt graag over vroeger.', en: 'The neighbour likes to talk about the old days.', image: 'old-man' },
      { nl: 'Wat is er gebeurd? — Bram heeft pijn aan zijn rug.', en: 'What happened? — Bram has a pain in his back.', image: 'back-pain' },
    ],
    note: 'kennen = to know a person or a place; weten = to know a fact. “Die ken ik” = I know him / her — die points back to the person, the usual short answer in speech (“Ik ken hem”, “Ik ken haar” are just as correct). ontmoeten = to meet; its participle is simply “ontmoet”. bezoeken = to visit, vertellen = to tell, gebeuren = to happen (“wat is er gebeurd?” = what happened?). None of these four takes ge- in the perfect — the grammar pages explain why.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['dit-is', 'plural'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Dit zijn onze buren: de buurman en de buurvrouw.', en: 'These are our neighbours: the man and the woman next door.', answer: 'neighbours',
    choices: [{ image: 'colleagues', nl: 'Bram en twee collega’s' }, { image: 'neighbours', nl: 'de buren' }, { image: 'students', nl: 'studenten' }, { image: 'family', nl: 'een familie' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['possessives'],
    instruction: 'Listen without reading. Where is Bram?',
    nl: 'Bram praat op kantoor met zijn collega’s.', en: 'Bram is talking with his colleagues at the office.', answer: 'colleagues',
    choices: [{ image: 'couple-talking', nl: 'Bram en Lotte praten.' }, { image: 'colleagues', nl: 'Bram op kantoor' }, { image: 'classroom', nl: 'een les' }, { image: 'neighbours', nl: 'de buren' }],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['present-regular'],
    instruction: 'Listen. A square full of students, or a lesson?',
    nl: 'De leraar geeft les aan de studenten.', en: 'The teacher is teaching the students.', answer: 'classroom',
    choices: [{ image: 'students', nl: 'studenten op straat' }, { image: 'university', nl: 'de universiteit' }, { image: 'classroom', nl: 'de leraar en de studenten' }, { image: 'school', nl: 'een school' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['de-het', 'plural'],
    instruction: 'Type the Dutch. Nouns with their article.',
    items: [
      { image: 'old-man', en: 'the neighbour (a man)', answer: 'de buurman' },
      { image: 'old-woman', en: 'the neighbour (a woman)', answer: 'de buurvrouw' },
      { image: 'neighbours', en: 'the neighbours', answer: 'de buren' },
      { image: 'students', en: 'the students', answer: 'de studenten' },
      { image: 'classroom', en: 'the teacher', answer: 'de leraar' },
      { en: 'the teachers', answer: 'de leraren' },
      { en: 'the answer', answer: 'het antwoord' },
      { en: 'the answers', answer: 'de antwoorden' },
      { en: 'the lessons', answer: 'de lessen' },
      { image: 'colleagues', en: 'the colleagues', answer: 'de collega’s' },
      { en: 'the office', answer: 'het kantoor' },
      { en: 'the subject (at school)', answer: 'het vak' },
      { en: 'the people', answer: 'de mensen' },
    ],
    explanation: 'Three het-words: het antwoord, het kantoor, het vak — every other noun here is a de-word, and every plural takes de. les → lessen (short e, so the s doubles); leraar → leraren (le-ra-ren: an open syllable needs only one a); collega → collega’s (a long a at the end: ’s, so the a keeps its sound); buurman → buren is irregular.',
  },
  {
    type: 'drill', title: 'Hear and spell', grammar: ['kennen-weten'],
    instruction: 'Play each one and type it. “uu” in buurman is the sound of the French u; “ui” in huis is a different sound.',
    items: [
      { listen: 'universiteit' },
      { listen: 'buurvrouw' },
      { listen: 'ontmoeten' },
      { listen: 'Ik ken de buurman.' },
      { listen: 'Die ken ik niet.' },
      { listen: 'Wat is er gebeurd?' },
    ],
    explanation: 'universiteit ends in “teit”: the ei of trein. buurvrouw: first uu, then ouw. ontmoeten: ont-MOE-ten, with the oe of boek.',
  },

  // ——— Grammar: the new verbs ———
  {
    part: 'Grammar', type: 'grammar', title: 'kennen, ontmoeten and five more verbs', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'inversion', 'imperfect-weak', 'imperfect-strong'],
    body: [
      'Two target verbs — **kennen** (to know a person or a place) and **ontmoeten** (to meet) — and five extra ones: **studeren** (to study at university), **geven** (to give), **bezoeken** (to visit), **vertellen** (to tell) and **gebeuren** (to happen). In the present they all follow the pattern of lesson 3: **ik** + stem, **jij / hij / zij** + stem + **t**, **wij / jullie / zij** = the infinitive. In a question jij takes the bare stem: ***Ken** jij de buurman? **Studeer** jij in Leuven?*',
      'The stem follows the spelling rules you know. *ken-nen* → **ik ken** (one n at the end of a word), *stu-de-ren* → **ik studeer** (a long e in a closed syllable needs two letters), *be-zoe-ken* → **ik bezoek**, *ver-tel-len* → **ik vertel**. *ge-ven* → **ik geef**: v becomes f at the end, as in *schrijven → ik schrijf*.',
      '**ontmoeten** is the trap of this lesson. Its stem, **ontmoet**, already ends in t, so jij and hij add nothing: *jij ontmoet, hij ontmoet* — like *praten → hij praat* and *weten → hij weet*. In the question nothing changes either: ***Ontmoet** jij Emma vandaag?*',
      '**gebeuren** is almost always said of a thing, not a person, so you mostly meet the hij / het form, often with **er**: *Wat **gebeurt** er?* (What is happening?) *Het gebeurt elke dag.*',
      '**The simple past** (lesson 15). ’t kofschip decides: *kennen → **kende**, kenden* (n is not in ’t kofschip), *studeren → studeerde, vertellen → vertelde, gebeuren → gebeurde*. *ontmoeten → **ontmoette**, ontmoetten*: t is in ’t kofschip, so -te — and the stem already ends in t, which gives a double t. Two are irregular: *geven → **gaf**, gaven* (a strong verb), and *bezoeken → **bezocht**, bezochten* (like *kopen → kocht*).',
    ],
    tables: [
      { caption: 'kennen · ontmoeten', rows: [
        { nl: 'ik ken · ik ontmoet', en: 'I know · I meet' },
        { nl: 'jij ken[t] · jij ontmoet', en: 'you know · you meet — ontmoet has no extra t' },
        { nl: 'hij ken[t] · hij ontmoet', en: 'he knows · he meets' },
        { nl: 'wij kenn[en] · wij ontmoet[en]', en: 'we know · we meet' },
        { nl: 'ken jij? · ontmoet jij?', en: 'do you know? · are you meeting?' },
      ] },
      { caption: 'studeren · geven · bezoeken · vertellen', rows: [
        { nl: 'ik studeer · ik geef · ik bezoek · ik vertel', en: 'I study · give · visit · tell' },
        { nl: 'zij studeer[t] · zij geef[t] · zij bezoek[t] · zij vertel[t]', en: 'she studies · gives · visits · tells' },
        { nl: 'jullie studer[en] · jullie gev[en] · jullie bezoek[en] · jullie vertell[en]', en: 'you (plural) study · give · visit · tell' },
        { nl: 'wat gebeur[t] er?', en: 'what is happening?' },
      ] },
      { caption: 'The simple past', rows: [
        { nl: 'Vroeger [kende] Bram veel mensen in Oostende.', en: 'Bram used to know a lot of people in Ostend.' },
        { nl: 'Lotte [ontmoette] haar leraar in de stad.', en: 'Lotte met her teacher in town.' },
        { nl: 'De leraar [gaf] elke dag les.', en: 'The teacher taught every day.' },
        { nl: 'Wij [bezochten] elke zomer oma en opa.', en: 'We visited grandma and grandpa every summer.' },
      ] },
    ],
    examples: [
      { nl: 'Ken jij de buurvrouw?', en: 'Do you know the neighbour?' },
      { nl: 'Waar ontmoet jij Emma?', en: 'Where are you meeting Emma?' },
      { nl: 'Lotte studeert aan de universiteit.', en: 'Lotte studies at the university.' },
      { nl: 'De leraar geeft elke maandag les.', en: 'The teacher teaches every Monday.' },
      { nl: 'Wat gebeurt er?', en: 'What is happening?' },
      { nl: 'Bram belt zijn vader en moeder en vertelt over de reis die Lotte en hij in de winter naar Oostende maken.', en: 'Bram calls his father and mother and tells them about the trip Lotte and he are making to Ostend in the winter.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate kennen', grammar: ['present-regular', 'spelling-stem', 'subject-pronouns'],
    instruction: 'Type the form of kennen for every person. Say “ik ken, jij kent …” out loud.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'ken' },
      { label: 'jij', gloss: 'you', answer: 'kent' },
      { label: 'hij', gloss: 'he', answer: 'kent' },
      { label: 'zij', gloss: 'she', answer: 'kent' },
      { label: 'wij', gloss: 'we', answer: 'kennen' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'kennen' },
      { label: 'zij', gloss: 'they', answer: 'kennen' },
      { label: 'de buren', gloss: 'they', answer: 'kennen' },
    ],
    explanation: 'ken with one n, kennen with two: the double n only appears between two vowels, like zit — zitten.',
  },
  {
    type: 'drill', layout: 'table', title: 'ontmoeten, studeren, geven, bezoeken, vertellen', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'subject-pronouns'],
    instruction: 'Mixed persons. The small word under each person is the verb to use. Type the form.',
    items: [
      { label: 'ik', gloss: 'ontmoeten', answer: 'ontmoet' },
      { label: 'jij', gloss: 'ontmoeten', answer: 'ontmoet' },
      { label: 'wij', gloss: 'ontmoeten', answer: 'ontmoeten' },
      { label: 'ik', gloss: 'studeren', answer: 'studeer' },
      { label: 'zij', gloss: 'she · studeren', answer: 'studeert' },
      { label: 'ik', gloss: 'geven', answer: 'geef' },
      { label: 'hij', gloss: 'geven', answer: 'geeft' },
      { label: 'jullie', gloss: 'geven', answer: 'geven' },
      { label: 'ik', gloss: 'bezoeken', answer: 'bezoek' },
      { label: 'zij', gloss: 'they · bezoeken', answer: 'bezoeken' },
      { label: 'hij', gloss: 'vertellen', answer: 'vertelt' },
      { label: 'het', gloss: 'gebeuren', answer: 'gebeurt' },
    ],
    explanation: 'jij ontmoet, hij ontmoet: never “ontmoett”. geef with f, geven with v — the rule of schrijf and schrijven. studeer with ee, studeren with one e.',
  },
  {
    type: 'drill', title: 'Present and past', grammar: ['present-regular', 'inversion', 'v2-inversion', 'imperfect-weak', 'imperfect-strong', 'toen-past'],
    instruction: 'Type the missing form. When the English is in the past, use the simple past. Watch jij before and after the verb.',
    items: [
      { nl: 'Ik ___ de buurman al jaren.', cue: 'kennen', en: 'I have known the neighbour for years.', answer: 'ken' },
      { nl: '___ jij de buurvrouw?', cue: 'kennen', answer: 'Ken' },
      { nl: 'Lotte ___ Emma om acht uur in de stad.', cue: 'ontmoeten', en: 'Lotte is meeting Emma in town at eight.', answer: 'ontmoet' },
      { nl: 'Waar ___ jij Emma?', cue: 'ontmoeten', answer: 'ontmoet' },
      { nl: 'De leraar ___ elke maandag les.', cue: 'geven', answer: 'geeft' },
      { nl: 'Woensdag ___ wij de buren.', cue: 'bezoeken', en: 'On Wednesday we are visiting the neighbours.', answer: 'bezoeken' },
      { nl: 'Vroeger ___ de buurman veel studenten.', cue: 'kennen', en: 'The neighbour used to know a lot of students.', answer: 'kende' },
      { nl: 'Gisteren ___ Lotte haar nieuwe leraar.', cue: 'ontmoeten', en: 'Yesterday Lotte met her new teacher.', answer: 'ontmoette' },
      { nl: 'Toen Bram klein was, ___ hij elke zondag oma en opa.', cue: 'bezoeken', en: 'When Bram was little, he visited grandma and grandpa every Sunday.', answer: 'bezocht' },
      { nl: 'De leraar ___ de studenten een moeilijk examen.', cue: 'geven', en: 'The teacher gave the students a difficult exam.', answer: 'gaf' },
    ],
    explanation: 'Waar ontmoet jij? — the jij-question of a stem in t looks just like the statement. ontmoette: -te after t, so two t’s. gaf and bezocht are irregular: learn them as they are.',
  },

  // ——— Grammar: die and dat ———
  {
    type: 'grammar', title: 'die and dat: the relative clause', grammar: ['relative-clause', 'verb-final', 'de-het', 'plural', 'dat-clause'],
    body: [
      'A **relative clause** tells you *which* person or thing you mean: *de man **die** op de bank zit* — the man **who** is sitting on the bench; *het boek **dat** de buurman leest* — the book **that** the neighbour is reading. English chooses between who, which and that. Dutch has only **die** and **dat**, and the choice depends on one thing: the noun in front of it.',
      '**die** for every **de**-word — a person, an animal or a thing — and for **every plural**, because every plural is a de-word. **dat** for a **het**-word in the singular. That is the whole rule. Now you see why every noun has been learnt with its article: *de student **die** …, de studenten **die** …, het antwoord **dat** …, de antwoorden **die** …*',
      'The trap: a person can be a het-word. Noor is a girl, but she is *het kind* — so *het kind **dat** in onze straat woont*. Words in -je are always het-words: *het ijsje **dat** Noor eet*. The meaning does not help you; only the article does.',
      'A relative clause is a subordinate clause, like the clauses after omdat and dat in lesson 12, so its **conjugated verb goes to the end**: *De buurman leest altijd* → *de buurman die altijd **leest***. Everything else keeps its order: *de student die elke dag om acht uur naar de universiteit **gaat***.',
      'Do not mix up the two dats. *Ik weet **dat** de buurman altijd leest* — dat after a verb like weten, denken or zeggen: the “that” of lesson 12. *Het boek **dat** de buurman leest* — dat after a het-word: “which”. Both send the verb to the end, so the word order is the same; only the job is different. And where English can leave the word out (“the book I am reading”), Dutch never drops die or dat.',
    ],
    tables: [
      { caption: 'die — de-words and all plurals', rows: [
        { nl: 'de man [die] op de bank zit', en: 'the man who is sitting on the bench' },
        { nl: 'de vrouw [die] naast ons woont', en: 'the woman who lives next door to us' },
        { nl: 'de collega [die] ook in Leuven woont', en: 'the colleague who also lives in Leuven' },
        { nl: 'de studenten [die] in Leuven studeren', en: 'the students who study in Leuven' },
        { nl: 'de collega’s [die] met Bram in Brussel werken', en: 'the colleagues who work with Bram in Brussels' },
        { nl: 'de huizen [die] in onze straat staan', en: 'the houses that stand in our street' },
        { nl: 'de tafel [die] in de keuken staat', en: 'the table that stands in the kitchen' },
      ] },
      { caption: 'dat — het-words (singular)', rows: [
        { nl: 'het kind [dat] in onze straat woont', en: 'the child who lives in our street' },
        { nl: 'het kantoor [dat] in Brussel is', en: 'the office that is in Brussels' },
        { nl: 'het huis [dat] naast ons staat', en: 'the house that stands next to ours' },
        { nl: 'het antwoord [dat] goed is', en: 'the answer that is right' },
        { nl: 'het hotel [dat] aan zee is', en: 'the hotel that is by the sea' },
        { nl: 'het vliegtuig [dat] wij volgende zomer nemen', en: 'the plane we are taking next summer' },
        { nl: 'het ontbijt [dat] Bram elke dag maakt', en: 'the breakfast Bram makes every day' },
      ] },
    ],
    examples: [
      { nl: 'De buurman is de man die altijd leest.', en: 'The neighbour is the man who always reads.' },
      { nl: 'Noor is het kind dat in onze straat woont.', en: 'Noor is the child who lives in our street.' },
      { nl: 'Lotte heeft een leraar die heel goed Engels spreekt.', en: 'Lotte has a teacher who speaks very good English.' },
      { nl: 'Ik weet dat de buurman altijd leest.', en: 'I know that the neighbour always reads. (the other dat)' },
    ],
  },
  {
    type: 'drill', title: 'die or dat?', grammar: ['relative-clause', 'de-het', 'plural'], choices: ['die', 'dat'],
    instruction: 'Look at the noun before the gap: de-word or plural → die, het-word → dat.',
    items: [
      { nl: 'de buurman ___ altijd leest', answer: 'die' },
      { nl: 'het kind ___ in onze straat woont', answer: 'dat' },
      { nl: 'het antwoord ___ Lotte geschreven heeft', answer: 'dat' },
      { nl: 'de studenten ___ in Leuven wonen', answer: 'die' },
      { nl: 'het ijsje ___ Noor eet', answer: 'dat' },
      { nl: 'het vak ___ Lotte het makkelijkst vindt', answer: 'dat' },
      { nl: 'de universiteit ___ Lotte zo mooi vindt', answer: 'die' },
      { nl: 'de collega’s ___ met Bram in Brussel werken', answer: 'die' },
    ],
    explanation: 'het kind dat, het ijsje dat: a het-word, even when it is a person. de studenten die: every plural takes die.',
  },
  {
    type: 'drill', title: 'Type die or dat', grammar: ['relative-clause', 'de-het', 'plural', 'separable-together', 'comparative', 'perfect-hebben', 'reflexive'],
    instruction: 'Now type it. Nouns from the whole book — think of the article first.',
    items: [
      { nl: 'Max is de hond ___ altijd in het park wil lopen.', answer: 'die' },
      { nl: 'Mimi is de kat ___ altijd op het bed slaapt.', answer: 'die' },
      { nl: 'Wij wachten op de trein ___ om acht uur aankomt.', answer: 'die' },
      { nl: 'Het ontbijt ___ Bram gemaakt heeft, is heel goed.', answer: 'dat' },
      { nl: 'Lotte koopt de appels ___ goedkoper zijn.', answer: 'die' },
      { nl: 'Het medicijn ___ de dokter Bram gegeven heeft, helpt.', answer: 'dat' },
      { nl: 'De foto ___ oma heeft, is heel oud.', answer: 'die' },
      { nl: 'Het strand ___ Bram zich herinnert, is in Oostende.', answer: 'dat' },
      { nl: 'De kinderen ___ op het strand spelen, zijn blij.', answer: 'die' },
      { nl: 'Het hotel ___ zij gevonden hebben, is aan zee.', answer: 'dat' },
      { nl: 'Noor is het kind ___ vijf jaar is.', answer: 'dat' },
      { nl: 'De mensen ___ naast ons wonen, zijn heel lief.', answer: 'die' },
    ],
    explanation: 'de hond, de kat, de trein, de appels, de foto, de kinderen, de mensen → die. het ontbijt, het medicijn, het strand, het hotel, het kind → dat. When the noun with its clause comes first, the main verb follows straight after the comma: …, is heel goed.',
  },
  {
    type: 'drill', title: 'Join with die or dat', grammar: ['relative-clause', 'verb-final', 'adverb-position', 'separable-together', 'hij-het-things', 'adjective-e'],
    task: 'Join with die or dat',
    instruction: 'Make one sentence. hij, zij or het in the second sentence becomes die or dat, and its verb goes to the end.',
    items: [
      { nl: 'Dit is de buurman. Hij leest altijd.', answer: 'Dit is de buurman die altijd leest.' },
      { nl: 'Noor is een kind. Het woont in onze straat.', answer: 'Noor is een kind dat in onze straat woont.' },
      { nl: 'Bram heeft een collega. Hij woont ook in Leuven.', answer: 'Bram heeft een collega die ook in Leuven woont.' },
      { nl: 'Lotte heeft een leraar. Hij spreekt heel goed Engels.', answer: 'Lotte heeft een leraar die heel goed Engels spreekt.' },
      { nl: 'Bram werkt in een kantoor. Het heeft vier grote ramen.', answer: 'Bram werkt in een kantoor dat vier grote ramen heeft.' },
      { nl: 'Wij hebben buren. Zij hebben twee katten.', answer: 'Wij hebben buren die twee katten hebben.' },
      { nl: 'Emma is een vriendin. Zij gaat graag uit.', answer: 'Emma is een vriendin die graag uitgaat.' },
      { nl: 'Lotte heeft een broer. Hij woont in Antwerpen.', answer: 'Lotte heeft een broer die in Antwerpen woont.' },
    ],
    explanation: 'een kind → dat, because it is het kind. Zij (they) → die: a plural. “gaat graag uit” becomes “graag uitgaat”: at the end of a subordinate clause a separable verb is one word again.',
  },
  {
    type: 'drill', title: 'The verb at the end', grammar: ['relative-clause', 'verb-final', 'present-regular', 'zijn', 'hebben', 'dt-rule', 'spelling-z-s'],
    instruction: 'Type the verb form. It stands at the end of the relative clause — and a jij before it keeps its -t.',
    items: [
      { nl: 'Ken jij de man die op de bank ___?', cue: 'zitten', answer: 'zit' },
      { nl: 'De buurvrouw is de vrouw die elke dag thee ___.', cue: 'drinken', answer: 'drinkt' },
      { nl: 'Bram heeft een collega die met de auto naar Brussel ___.', cue: 'rijden', answer: 'rijdt' },
      { nl: 'Is dat de collega die altijd moe ___?', cue: 'zijn', answer: 'is' },
      { nl: 'De buren zijn de mensen die twee katten ___.', cue: 'hebben', answer: 'hebben' },
      { nl: 'De leraar leest het antwoord dat jij ___.', cue: 'schrijven', answer: 'schrijft' },
      { nl: 'Is dat de man die jij ___?', cue: 'kennen', answer: 'kent' },
      { nl: 'Het boek dat de buurman ___, is heel oud.', cue: 'lezen', answer: 'leest' },
      { nl: 'Jonas is de vriend die elke zaterdag met Bram ___.', cue: 'zwemmen', answer: 'zwemt' },
      { nl: 'Het kind dat met Max ___, is Noor.', cue: 'spelen', answer: 'speelt' },
    ],
    explanation: 'die jij kent, dat jij schrijft: jij stands before its verb, so the t stays. rijdt: stem rijd + t. And in “Het boek dat de buurman leest, is heel oud” the verb of the main clause comes straight after the comma.',
  },
  {
    type: 'arrange', title: 'The man on the bench', grammar: ['relative-clause', 'verb-final', 'adjective-e'],
    instruction: 'Build: “The neighbour is the old man who always reads on the bench.” Two tiles are traps.',
    nl: 'De buurman is de oude man die altijd op de bank leest.', en: 'The neighbour is the old man who always reads on the bench.', image: 'old-man', distractors: ['dat', 'lees'],
    accept: ['De oude man die altijd op de bank leest, is de buurman.'],
  },
  {
    type: 'grammar', title: 'die as the object, two verbs, and the clause in front', grammar: ['relative-clause', 'verb-final', 'perfect-hebben', 'modals', 'separable-together', 'als-inversion', 'zullen-future', 'te-infinitive'],
    body: [
      'So far die and dat were the **subject** of their clause: *de man die op de bank zit* — he sits. They can also be the **object**: *de man **die ik ken*** — I know him; *het boek **dat Lotte leest*** — she reads it. The order is the same: die or dat, then the subject, then the rest, and the verb at the end.',
      'The verb tells you who does what. *de studenten die Lotte **kent*** — Lotte knows the students: kent agrees with Lotte. *de studenten die Lotte **kennen*** — the students know Lotte: kennen agrees with de studenten. When both are singular, as in *de man die de vrouw ziet*, only the context tells you who sees whom.',
      '**Two verbs.** A relative clause works exactly like an omdat-clause: all the verbs go to the end. A modal and its infinitive: *de student die goed Nederlands **kan spreken***. A perfect: *de man die ik gisteren **ontmoet heb*** — or *heb ontmoet*; both are correct, and this course writes the participle first, as in lesson 12. A separable verb is one word again: *de trein die te laat **aankomt***, *de buurman die altijd vroeg **opstaat***. zullen and te as well: *de reis die wij volgende zomer **zullen maken***, *de student die Nederlands **probeert te spreken***.',
      'jij keeps its -t, because in a relative clause it always stands before its verb: *de man die jij **kent***, *het boek dat jij **leest***.',
      '**Where does the clause go?** Straight after its noun. When that noun is at the front of the sentence, the noun and its clause together are the first element — so the main verb comes right after the comma: *De man die op de bank zit, **is** onze buurman.* You know the sound from als in lesson 12: verb, comma, verb — *zit, is*.',
      'One exception you will hear all the time: when the main clause ends with a participle, an infinitive or a separable particle, Dutch prefers to say that word first and put the relative clause after it. *Ik heb de vrouw **ontmoet** die naast ons woont* sounds more natural than *Ik heb de vrouw die naast ons woont ontmoet*. Both are correct and both are accepted.',
      'For a place, Dutch often uses **waar** instead of die or dat: *de stad **waar** Bram werkt*, *het huis waar oma en opa woonden*.',
    ],
    tables: [
      { caption: 'die or dat as the object', rows: [
        { nl: 'de man [die] ik ken', en: 'the man (whom) I know' },
        { nl: 'het boek [dat] Lotte leest', en: 'the book (that) Lotte is reading' },
        { nl: 'de studenten die Lotte [kent]', en: 'the students Lotte knows' },
        { nl: 'de studenten die Lotte [kennen]', en: 'the students who know Lotte' },
      ] },
      { caption: 'two verbs at the end', rows: [
        { nl: 'de man die ik gisteren [ontmoet heb]', en: 'the man I met yesterday (also: heb ontmoet)' },
        { nl: 'de student die goed Nederlands [kan spreken]', en: 'the student who can speak Dutch well' },
        { nl: 'de trein die te laat [aankomt]', en: 'the train that arrives late' },
        { nl: 'de reis die wij volgende zomer [zullen maken]', en: 'the trip we will make next summer' },
      ] },
      { caption: 'the clause in front', rows: [
        { nl: 'De man die op de bank zit, [is] onze buurman.', en: 'The man who is sitting on the bench is our neighbour.' },
        { nl: 'Het boek dat ik lees, [is] heel mooi.', en: 'The book I am reading is very beautiful.' },
        { nl: 'De collega die naast Bram werkt, [woont] ook in Leuven.', en: 'The colleague who works next to Bram also lives in Leuven.' },
      ] },
    ],
    examples: [
      { nl: 'Ik heb de vrouw ontmoet die naast ons woont.', en: 'I have met the woman who lives next door to us.' },
      { nl: 'Ik heb de vrouw die naast ons woont ontmoet.', en: 'The same — also correct, but heavier.' },
      { nl: 'Is dat de man die jij kent?', en: 'Is that the man you know?' },
      { nl: 'Ik ken een student die Nederlands probeert te spreken.', en: 'I know a student who is trying to speak Dutch.' },
      { nl: 'De reis die wij volgende zomer maken, is lang.', en: 'The trip we are making next summer is long.' },
    ],
  },
  {
    type: 'drill', title: 'die and dat as the object', grammar: ['relative-clause', 'verb-final', 'perfect-hebben', 'separable-together', 'participle'],
    task: 'Join with die or dat',
    instruction: 'Make one sentence. The second sentence becomes the relative clause: die or dat first, then its subject, the verbs at the end.',
    items: [
      { nl: 'Dit is het boek. Lotte leest het.', answer: 'Dit is het boek dat Lotte leest.' },
      { nl: 'Dit is de buurvrouw. Ik heb haar gisteren ontmoet.', answer: 'Dit is de buurvrouw die ik gisteren ontmoet heb.', accept: ['Dit is de buurvrouw die ik gisteren heb ontmoet.'] },
      { nl: 'Dat zijn de studenten. Lotte kent ze.', answer: 'Dat zijn de studenten die Lotte kent.' },
      { nl: 'Emma is de vriendin. Lotte belt haar elke dag op.', answer: 'Emma is de vriendin die Lotte elke dag opbelt.' },
      { nl: 'Dit is het antwoord. Jij hebt het geschreven.', answer: 'Dit is het antwoord dat jij geschreven hebt.', accept: ['Dit is het antwoord dat jij hebt geschreven.'] },
      { nl: 'Dat is de jas. Lotte heeft hem gekocht.', answer: 'Dat is de jas die Lotte gekocht heeft.', accept: ['Dat is de jas die Lotte heeft gekocht.'] },
      { nl: 'Dit is het medicijn. De dokter heeft het aan Bram gegeven.', answer: 'Dit is het medicijn dat de dokter aan Bram gegeven heeft.', accept: ['Dit is het medicijn dat de dokter aan Bram heeft gegeven.'] },
      { nl: 'Dat is de buurman. Jij kent hem al.', answer: 'Dat is de buurman die jij al kent.' },
    ],
    explanation: 'hem, haar, het, ze disappear: die or dat takes their place at the front of the clause. Lotte kent ze → die Lotte kent (Lotte knows them — kent, singular). belt … op → opbelt, one word at the end.',
  },
  {
    type: 'drill', title: 'Two verbs at the end of the clause', grammar: ['relative-clause', 'verb-final', 'modals', 'infinitive-end', 'perfect-hebben', 'perfect-zijn', 'separable-together', 'reflexive', 'zullen-future', 'imperfect-weak'],
    instruction: 'Type what goes in the gap. The cue gives the verbs; put them in order at the end (the other order is accepted where Dutch allows it).',
    items: [
      { nl: 'Bram is de man die heel goed ___.', cue: 'kunnen + zwemmen', answer: 'kan zwemmen', accept: ['zwemmen kan'] },
      { nl: 'Dat is de man die ik gisteren ___.', cue: 'hebben + ontmoeten', answer: 'ontmoet heb', accept: ['heb ontmoet'] },
      { nl: 'Bram neemt de trein die om half negen in Brussel ___.', cue: 'aankomen', answer: 'aankomt' },
      { nl: 'Is dat de buurman die altijd zo vroeg ___?', cue: 'opstaan', answer: 'opstaat' },
      { nl: 'Wij praten over de reis die wij volgende zomer ___.', cue: 'zullen + maken', answer: 'zullen maken', accept: ['maken zullen'] },
      { nl: 'Oma en opa zijn de mensen die vroeger in Oostende ___.', cue: 'wonen', en: 'Grandma and grandpa are the people who used to live in Ostend.', answer: 'woonden' },
      { nl: 'De dokter is de vrouw die Bram een medicijn ___.', cue: 'hebben + geven', answer: 'gegeven heeft', accept: ['heeft gegeven'] },
      { nl: 'Dat is de collega die zich altijd ___.', cue: 'haasten', answer: 'haast' },
      { nl: 'Noor is het kind dat morgen met Max ___ spelen.', cue: 'mogen', answer: 'mag' },
      { nl: 'Het examen dat Lotte ___, was moeilijk.', cue: 'hebben + maken', answer: 'gemaakt heeft', accept: ['heeft gemaakt'] },
      { nl: 'Jonas is de vriend die gisteren met Bram naar de film ___.', cue: 'zijn + gaan', answer: 'gegaan is', accept: ['is gegaan'] },
    ],
    explanation: 'kan zwemmen, zullen maken: the conjugated verb first, then the infinitive. ontmoet heb, gegeven heeft, gegaan is: participle first in this course. aankomt, opstaat: one word. die zich haast: the reflexive pronoun stays right after the subject.',
  },
  {
    type: 'drill', title: 'The clause in front', grammar: ['relative-clause', 'als-inversion', 'v2-inversion', 'superlative', 'separable-together', 'imperfect-strong', 'modals'],
    instruction: 'Rewrite as the task says. The noun and its relative clause become the first element — so the main verb comes straight after the comma.',
    items: [
      { nl: 'Onze buurman is de man die op de bank zit.', task: 'Start with “De man die …”', answer: 'De man die op de bank zit, is onze buurman.' },
      { nl: 'Noor is het kind dat met Max speelt.', task: 'Start with “Het kind dat …”', answer: 'Het kind dat met Max speelt, is Noor.' },
      { nl: 'Lotte is de student die het snelst leest.', task: 'Start with “De student die …”', answer: 'De student die het snelst leest, is Lotte.' },
      { nl: 'Het boek is heel mooi. Ik lees het.', task: 'Start with “Het boek dat …”', answer: 'Het boek dat ik lees, is heel mooi.' },
      { nl: 'De collega woont ook in Leuven. Hij werkt naast Bram.', task: 'Start with “De collega die …”', answer: 'De collega die naast Bram werkt, woont ook in Leuven.' },
      { nl: 'De trein is te laat. Hij komt om acht uur aan.', task: 'Start with “De trein die …”', answer: 'De trein die om acht uur aankomt, is te laat.' },
      { nl: 'De jas was te duur. Lotte wilde hem kopen.', task: 'Start with “De jas die …”', answer: 'De jas die Lotte wilde kopen, was te duur.', accept: ['De jas die Lotte kopen wilde, was te duur.'] },
      { nl: 'De buren zijn heel lief. Wij bezoeken ze zondag.', task: 'Start with “De buren die …”', answer: 'De buren die wij zondag bezoeken, zijn heel lief.' },
    ],
    explanation: 'zit, is · speelt, is · leest, is: verb, comma, verb — the pattern of “Als het regent, gaan wij …”. The main clause never starts with its subject here.',
  },
  {
    type: 'arrange', title: 'The woman I met', grammar: ['relative-clause', 'perfect-hebben', 'participle-no-ge'],
    instruction: 'Build: “The woman I met yesterday is the neighbour.” Two tiles are traps.',
    nl: 'De vrouw die ik gisteren ontmoet heb, is de buurvrouw.', en: 'The woman I met yesterday is the neighbour.', image: 'old-woman', distractors: ['dat', 'hebt'],
    accept: ['De vrouw die ik gisteren heb ontmoet, is de buurvrouw.', 'De buurvrouw is de vrouw die ik gisteren ontmoet heb.', 'De buurvrouw is de vrouw die ik gisteren heb ontmoet.'],
  },

  // ——— Grammar: kennen or weten ———
  {
    type: 'grammar', title: 'kennen or weten?', grammar: ['kennen-weten', 'dat-clause', 'question-word', 'verb-final', 'imperfect-strong'],
    body: [
      'English has one verb, *to know*. Dutch has two. **kennen** = to be acquainted with, to be familiar with: a person, a place, or a thing you have met — a book, a film, a street. **weten** = to have a piece of information: a fact.',
      'What follows the verb decides. After **kennen** comes a noun or a name: *Ik ken de buurman. Ken jij Leuven? Lotte kent dat boek.* After **weten** comes a fact: a dat-clause, a clause with a question word (wie, wat, waar, wanneer, hoe, hoeveel), or het or dat standing for a fact: *Ik weet dat hij altijd leest. Weet jij waar de buurman woont? Ik weet het niet.*',
      'A quick test: if English could say “be familiar with”, use kennen. If “know that / know where / know who / know when” fits, use weten. *I know the neighbour, but I don’t know his name* → *Ik **ken** de buurman, maar ik **weet** zijn naam niet.* A noun that stands for a piece of information goes with weten: ***het antwoord** weten, **zijn naam** weten* — Weet jij het antwoord? This course always uses weten there.',
      'Short answers follow the same split. *Ken jij Tom? — Ja, **die** ken ik.* In speech that is the usual short answer; *Ja, ik ken **hem**.* (him) and *Ja, ik ken **haar**.* (her) are just as correct. (die for a person or a de-word; *dat* for a het-word or a place: *Ken jij Gent? — Ja, dat ken ik goed.*) *Weet jij waar Tom woont? — Ja, **dat** weet ik.* or *Ja, ik weet **het**.*',
      'For a language, *spreken* is the usual verb: *Lotte spreekt Engels.* kennen is also correct: *Lotte kent Engels.* Never weten.',
      'The forms. kennen is regular: *ik ken, jij kent, wij kennen*, past *kende, kenden*, participle *gekend*. weten is not: *ik weet, jij weet, hij weet* (no extra t), past ***wist**, wisten*, participle *geweten*.',
    ],
    tables: [
      { caption: 'kennen — a person, a place, a thing', rows: [
        { nl: 'Ik [ken] de buurman.', en: 'I know the neighbour.' },
        { nl: 'Ken jij Leuven?', en: 'Do you know Leuven?' },
        { nl: 'Lotte [kent] dat boek.', en: 'Lotte knows that book.' },
        { nl: 'Ken jij de man op de foto?', en: 'Do you know the man in the photo?' },
        { nl: 'Die [ken] ik niet.', en: 'I don’t know him / her.' },
      ] },
      { caption: 'weten — a fact', rows: [
        { nl: 'Ik [weet] dat hij altijd leest.', en: 'I know that he always reads.' },
        { nl: 'Weet jij waar de buurman woont?', en: 'Do you know where the neighbour lives?' },
        { nl: 'Noor [weet] het antwoord.', en: 'Noor knows the answer.' },
        { nl: 'Dat [weet] ik niet.', en: 'I don’t know (that).' },
      ] },
      { caption: 'in the past', rows: [
        { nl: 'Wij [kenden] de buren nog niet.', en: 'We didn’t know the neighbours yet.' },
        { nl: 'Bram [wist] het antwoord niet.', en: 'Bram didn’t know the answer.' },
        { nl: 'Ik heb het altijd [geweten].', en: 'I have always known it.' },
      ] },
    ],
    examples: [
      { nl: 'Ik ken de buurman, maar ik weet zijn naam niet.', en: 'I know the neighbour, but I don’t know his name.' },
      { nl: 'Ken jij de man die op de bank zit? — Ja, die ken ik.', en: 'Do you know the man sitting on the bench? — Yes, I know him.' },
      { nl: 'Weet jij wie dat is? — Nee, dat weet ik niet.', en: 'Do you know who that is? — No, I don’t know.' },
      { nl: 'Ken jij zijn zus Sofie? — Ja, ik ken haar goed.', en: 'Do you know his sister Sofie? — Yes, I know her well.' },
      { nl: 'Kent Lotte zijn familie in Gent? — Ja, die kent zij goed.', en: 'Does Lotte know his family in Ghent? — Yes, she knows them well.' },
    ],
  },
  {
    type: 'drill', title: 'kennen or weten?', grammar: ['kennen-weten', 'present-regular', 'inversion'], choices: ['ken', 'kent', 'kennen', 'weet', 'weten'],
    instruction: 'Choose the right verb in the right form. A person or a place → kennen; a fact → weten.',
    items: [
      { nl: 'Ik ___ de buurman al jaren.', answer: 'ken' },
      { nl: '___ jij waar de buurman woont?', answer: 'weet' },
      { nl: 'Lotte ___ haar leraar nog niet goed.', answer: 'kent' },
      { nl: 'Bram ___ niet hoe de buurvrouw heet.', answer: 'weet' },
      { nl: '___ jij Tom? Hij woont in Antwerpen.', answer: 'ken' },
      { nl: 'Wij ___ dat Lotte morgen les heeft.', answer: 'weten' },
      { nl: '___ jullie wanneer de les begint?', answer: 'weten' },
    ],
    explanation: 'A noun or a name after the verb (de buurman, Tom, Leuven, het boek) → kennen. A clause (waar …, hoe …, dat …, wanneer …) or a fact like het antwoord → weten.',
  },
  {
    type: 'drill', title: 'kennen or weten — type it', grammar: ['kennen-weten', 'imperfect-weak', 'imperfect-strong', 'perfect-hebben', 'v2-inversion', 'relative-clause'],
    instruction: 'Type the form of kennen or weten. Decide the verb first, then the person and the tense.',
    items: [
      { nl: 'Ik ___ de vrouw die naast ons woont.', cue: 'kennen / weten', answer: 'ken' },
      { nl: 'Ik ___ niet waar zij werkt.', cue: 'kennen / weten', answer: 'weet' },
      { nl: '___ jij de leraar die Noor op school heeft?', cue: 'kennen / weten', answer: 'Ken' },
      { nl: 'Bram ___ dat zijn collega in Leuven woont.', cue: 'kennen / weten', answer: 'weet' },
      { nl: 'Lotte ___ Antwerpen heel goed: zij is er opgegroeid.', cue: 'kennen / weten', answer: 'kent' },
      { nl: '___ jullie Gent?', cue: 'kennen / weten', answer: 'Kennen' },
      { nl: 'Vroeger ___ oma veel mensen in Oostende.', cue: 'kennen / weten', en: 'Grandma used to know a lot of people in Ostend.', answer: 'kende' },
      { nl: 'Bram ___ het antwoord niet.', cue: 'kennen / weten', en: 'Bram didn’t know the answer.', answer: 'wist' },
      { nl: 'Dat heb ik altijd ___.', cue: 'kennen / weten', en: 'I have always known that.', answer: 'geweten' },
    ],
    explanation: 'wist and wisten, the past of weten, look nothing like the present — learn them. kende is regular: n is not in ’t kofschip, so -de.',
  },
  {
    type: 'drill', title: 'Say it in Dutch: to know', grammar: ['kennen-weten', 'dat-clause', 'question-word', 'relative-clause'],
    instruction: 'Translate. First decide: kennen or weten? “You” is one person unless it says plural.',
    items: [
      { en: 'I know the neighbour.', answer: 'Ik ken de buurman.' },
      { en: 'Do you know where the neighbour lives?', answer: 'Weet jij waar de buurman woont?' },
      { en: 'I don’t know.', answer: 'Ik weet het niet.', accept: ['Dat weet ik niet.'] },
      { en: 'I don’t know him.', answer: 'Ik ken hem niet.', accept: ['Die ken ik niet.'] },
      { en: 'Do you know the man who is sitting on the bench?', answer: 'Ken jij de man die op de bank zit?' },
      { en: 'Lotte knows that Bram is tired.', answer: 'Lotte weet dat Bram moe is.' },
      { en: 'Do you (plural) know when the lesson begins?', answer: 'Weten jullie wanneer de les begint?' },
      { en: 'I know the neighbour, but I don’t know his name.', answer: 'Ik ken de buurman, maar ik weet zijn naam niet.', accept: ['Ik ken de buurman, maar ik ken zijn naam niet.'] },
      { en: 'Does Noor know the answer?', answer: 'Weet Noor het antwoord?' },
    ],
    explanation: '“Ik ken hem niet” or, as people often say it, “Die ken ik niet”: then die is the first element, so the verb comes second and ik follows it. “het antwoord” and “zijn naam” are facts: weten.',
  },

  // ——— Grammar: no ge- ———
  {
    type: 'grammar', title: 'ontmoet, begrepen, herinnerd: no ge-', grammar: ['participle-no-ge', 'participle', 'perfect-hebben', 'perfect-zijn', 'separable-perfect'],
    body: [
      'Since lesson 11 you have built participles with ge-: *gewerkt, gekocht, gelezen*. One group of verbs never takes ge-: verbs that begin with the unstressed prefixes **be-, ge-, her-, ont-** and **ver-**. You know several already: *begrijpen → begrepen, beginnen → begonnen, herinneren → herinnerd*. New in this lesson: *ontmoeten → ontmoet, bezoeken → bezocht, vertellen → verteld, gebeuren → gebeurd*.',
      'Why? ge- is an unstressed syllable placed in front of the stressed part of the verb. These verbs already start with an unstressed prefix — be-ZOE-ken, ont-MOE-ten, ver-TEL-len, her-IN-ne-ren — and Dutch does not put a second one in front. So you never write *gebezocht* or *geontmoet*.',
      'Everything else about the participle stays the same. Regular verbs follow ’t kofschip: *verteld, gebeurd, herinnerd* take -d (l and r are not in ’t kofschip). A stem that already ends in t gets nothing extra: *ontmoeten → **ontmoet***, just as *praten → gepraat* — only without ge-. So **ontmoet** is three forms at once: *ik ontmoet, hij ontmoet, ik heb ontmoet*. Strong and irregular verbs change their vowel as usual: *begrepen, begonnen, bezocht*.',
      'Do not overdo it. A verb whose own first syllable is ge- — not a prefix — takes a normal ge-: *geven → **gegeven*** (GE-ven: the stress is on ge). *studeren → gestudeerd*, *kennen → gekend*, *proberen → geprobeerd*: no prefix, so ge- as always.',
      'Compare the separable verbs of lesson 13. Their first part is **stressed** (OP-staan, MEE-nemen) and comes loose; ge- goes between the parts: *opgestaan, meegenomen*. An inseparable prefix is unstressed, never comes loose, and takes no ge- at all: *ik ontmoet haar, ik heb haar ontmoet*.',
      'hebben or zijn? The usual rules. Most take hebben: *ik heb haar ontmoet, wij hebben de buren bezocht, hij heeft het verteld*. beginnen and gebeuren take zijn: *de les **is** begonnen, wat **is** er gebeurd?*',
      'Watch d and t: *hij vertel**t*** (present: stem + t) but *hij heeft vertel**d*** (participle). *Wat gebeur**t** er?* (now) but *Wat is er gebeur**d**?* (it has happened). You cannot hear the difference; you must write it.',
    ],
    tables: [
      { caption: 'no ge-', rows: [
        { nl: 'begrijpen — [begrepen]', en: 'understand' },
        { nl: 'beginnen — [begonnen]', en: 'begin (with zijn)' },
        { nl: 'herinneren — [herinnerd]', en: 'remember' },
        { nl: 'ontmoeten — [ontmoet]', en: 'meet' },
        { nl: 'bezoeken — [bezocht]', en: 'visit' },
        { nl: 'vertellen — [verteld]', en: 'tell' },
        { nl: 'gebeuren — [gebeurd]', en: 'happen (with zijn)' },
      ] },
      { caption: 'ge- as always', rows: [
        { nl: 'geven — [ge]geven', en: 'give — ge is part of the verb itself' },
        { nl: 'studeren — [ge]studeerd', en: 'study' },
        { nl: 'kennen — [ge]kend', en: 'know' },
        { nl: 'opstaan — op[ge]staan', en: 'get up — separable: ge- in the middle' },
      ] },
      { caption: 'd or t?', rows: [
        { nl: 'hij vertel[t] · hij heeft vertel[d]', en: 'he tells · he has told' },
        { nl: 'wat gebeur[t] er? · wat is er gebeur[d]?', en: 'what is happening? · what has happened?' },
        { nl: 'ik ontmoet · ik heb ontmoet', en: 'I meet · I have met' },
      ] },
    ],
    examples: [
      { nl: 'Ik heb de buurvrouw gisteren ontmoet.', en: 'I met the neighbour yesterday.' },
      { nl: 'Wij hebben zondag de buren bezocht.', en: 'We visited the neighbours on Sunday.' },
      { nl: 'De buurman heeft ons veel over vroeger verteld.', en: 'The neighbour told us a lot about the old days.' },
      { nl: 'Wat is er gebeurd?', en: 'What happened?' },
      { nl: 'De les is om negen uur begonnen.', en: 'The lesson started at nine.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Make the participle', grammar: ['participle-no-ge', 'participle', 'separable-perfect'],
    instruction: 'The infinitive is on the left. Type its participle. No ge- after be-, ge-, her-, ont-, ver- — but ge- everywhere else.',
    items: [
      { label: 'ontmoeten', gloss: 'meet', answer: 'ontmoet' },
      { label: 'bezoeken', gloss: 'visit', answer: 'bezocht' },
      { label: 'vertellen', gloss: 'tell', answer: 'verteld' },
      { label: 'gebeuren', gloss: 'happen', answer: 'gebeurd' },
      { label: 'begrijpen', gloss: 'understand', answer: 'begrepen' },
      { label: 'beginnen', gloss: 'begin', answer: 'begonnen' },
      { label: 'herinneren', gloss: 'remember', answer: 'herinnerd' },
      { label: 'geven', gloss: 'give', answer: 'gegeven' },
      { label: 'studeren', gloss: 'study', answer: 'gestudeerd' },
      { label: 'kennen', gloss: 'know', answer: 'gekend' },
      { label: 'opbellen', gloss: 'ring up', answer: 'opgebeld' },
      { label: 'meenemen', gloss: 'take along', answer: 'meegenomen' },
    ],
    explanation: 'Seven without ge-, three with ge- in front, two with ge- in the middle. geven is the trap: its ge is not a prefix, so gegeven.',
  },
  {
    type: 'drill', title: 'Participles in sentences', grammar: ['participle-no-ge', 'participle', 'perfect-hebben', 'perfect-zijn', 'separable-perfect', 'te-infinitive'],
    instruction: 'Type the participle of the verb given. The helper — hebben or zijn — is already there.',
    items: [
      { nl: 'Ik heb de buurvrouw gisteren ___.', cue: 'ontmoeten', answer: 'ontmoet' },
      { nl: 'Wij hebben vorig weekend de buren ___.', cue: 'bezoeken', answer: 'bezocht' },
      { nl: 'De buurman heeft veel over vroeger ___.', cue: 'vertellen', answer: 'verteld' },
      { nl: 'Wat is er ___?', cue: 'gebeuren', answer: 'gebeurd' },
      { nl: 'De les is om negen uur ___.', cue: 'beginnen', answer: 'begonnen' },
      { nl: 'De leraar heeft Lotte een goed boek ___.', cue: 'geven', answer: 'gegeven' },
      { nl: 'Heb jij je sleutel ___?', cue: 'meenemen', answer: 'meegenomen' },
      { nl: 'Bram heeft oma en opa heel goed ___.', cue: 'kennen', en: 'Bram knew grandma and grandpa very well.', answer: 'gekend' },
      { nl: 'Bram heeft ___ beter te koken.', cue: 'proberen', answer: 'geprobeerd' },
    ],
    explanation: 'is begonnen, is gebeurd — with zijn. Every other verb here takes hebben. “Bram heeft geprobeerd beter te koken”: te + infinitive after the participle.',
  },
  {
    type: 'drill', title: 'd or t? Now, or already done?', grammar: ['participle-no-ge', 'present-regular', 'perfect-hebben', 'perfect-zijn', 'reflexive', 'inversion'],
    instruction: 'Type the form of the verb given: the present, or the participle when there is a helper. Many pairs sound exactly the same.',
    items: [
      { nl: 'De buurman ___ graag over vroeger.', cue: 'vertellen', answer: 'vertelt' },
      { nl: 'Hij heeft gisteren veel over zijn vrouw ___.', cue: 'vertellen', answer: 'verteld' },
      { nl: 'Wat ___ er nu?', cue: 'gebeuren', answer: 'gebeurt' },
      { nl: 'Wat is er gisteren ___?', cue: 'gebeuren', answer: 'gebeurd' },
      { nl: '___ jij je oma nog?', cue: 'herinneren', en: 'Do you still remember grandma?', answer: 'Herinner' },
      { nl: 'Bram ___ zich zijn opa heel goed.', cue: 'herinneren', answer: 'herinnert' },
      { nl: 'Zondag ___ Lotte haar broer in Antwerpen.', cue: 'bezoeken', answer: 'bezoekt' },
      { nl: 'Vorige week heeft Lotte Tom in Antwerpen ___.', cue: 'bezoeken', answer: 'bezocht' },
      { nl: 'Hij ___ het antwoord niet.', cue: 'begrijpen', answer: 'begrijpt' },
      { nl: 'Hij heeft het antwoord niet ___.', cue: 'begrijpen', answer: 'begrepen' },
    ],
    explanation: 'vertelt / verteld, gebeurt / gebeurd, herinnert / herinnerd: the present has t, the participle of these verbs has d (ontmoet, whose stem ends in t, is both). Herinner jij je …? — jij after the verb loses its t, as always.',
  },
  {
    type: 'arrange', title: 'A Sunday visit', grammar: ['participle-no-ge', 'perfect-hebben', 'time-place'],
    instruction: 'Build: “On Sunday we visited the neighbours.” Two tiles are traps.',
    nl: 'Wij hebben zondag de buren bezocht.', en: 'On Sunday we visited the neighbours.', image: 'neighbours', distractors: ['bezoeken', 'hebt'],
    accept: ['Zondag hebben wij de buren bezocht.', 'Wij hebben de buren zondag bezocht.'],
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', layout: 'table', title: 'Every verb you know, part one', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'zijn', 'hebben', 'gaan', 'subject-pronouns', 'dt-rule', 'modals'],
    instruction: 'The verbs of lessons 1–9, mixed. The small word under each person is the verb. Type the form.',
    items: [
      { label: 'ik', gloss: 'zijn', answer: 'ben' },
      { label: 'jij', gloss: 'hebben', answer: 'hebt' },
      { label: 'zij', gloss: 'she · gaan', answer: 'gaat' },
      { label: 'ik', gloss: 'komen', answer: 'kom' },
      { label: 'hij', gloss: 'wonen', answer: 'woont' },
      { label: 'jij', gloss: 'lopen', answer: 'loopt' },
      { label: 'zij', gloss: 'she · zitten', answer: 'zit' },
      { label: 'hij', gloss: 'slapen', answer: 'slaapt' },
      { label: 'ik', gloss: 'koken', answer: 'kook' },
      { label: 'hij', gloss: 'praten', answer: 'praat' },
      { label: 'jij', gloss: 'werken', answer: 'werkt' },
      { label: 'hij', gloss: 'drinken', answer: 'drinkt' },
      { label: 'ik', gloss: 'helpen', answer: 'help' },
      { label: 'jij', gloss: 'wachten', answer: 'wacht' },
      { label: 'zij', gloss: 'she · lezen', answer: 'leest' },
      { label: 'hij', gloss: 'eten', answer: 'eet' },
      { label: 'ik', gloss: 'schrijven', answer: 'schrijf' },
      { label: 'hij', gloss: 'heten', answer: 'heet' },
      { label: 'jij', gloss: 'kunnen', answer: 'kunt', accept: ['kan'] },
      { label: 'hij', gloss: 'rijden', answer: 'rijdt' },
      { label: 'zij', gloss: 'she · spreken', answer: 'spreekt' },
    ],
    explanation: 'zit (one t), loopt and slaapt (double vowel back), leest and schrijf (z → s, v → f), praat, wacht, eet and heet (no second t), rijdt (d + t).',
  },
  {
    type: 'drill', layout: 'table', title: 'Every verb you know, part two', grammar: ['present-regular', 'spelling-stem', 'dt-rule', 'subject-pronouns', 'zullen-future', 'separable', 'reflexive'],
    instruction: 'The verbs of lessons 11–18. Type the present-tense form.',
    items: [
      { label: 'hij', gloss: 'maken', answer: 'maakt' },
      { label: 'ik', gloss: 'kopen', answer: 'koop' },
      { label: 'jij', gloss: 'zien', answer: 'ziet' },
      { label: 'hij', gloss: 'doen', answer: 'doet' },
      { label: 'ik', gloss: 'denken', answer: 'denk' },
      { label: 'jij', gloss: 'vinden', answer: 'vindt' },
      { label: 'ik', gloss: 'zeggen', answer: 'zeg' },
      { label: 'jij', gloss: 'weten', answer: 'weet' },
      { label: 'zij', gloss: 'she · vragen', answer: 'vraagt' },
      { label: 'hij', gloss: 'staan', answer: 'staat' },
      { label: 'ik', gloss: 'nemen', answer: 'neem' },
      { label: 'hij', gloss: 'reizen', answer: 'reist' },
      { label: 'jij', gloss: 'voelen', answer: 'voelt' },
      { label: 'ik', gloss: 'zullen', answer: 'zal' },
      { label: 'jij', gloss: 'zullen', answer: 'zult', accept: ['zal'] },
      { label: 'hij', gloss: 'vliegen', answer: 'vliegt' },
      { label: 'ik', gloss: 'proberen', answer: 'probeer' },
      { label: 'zij', gloss: 'she · beginnen', answer: 'begint' },
      { label: 'jij', gloss: 'kennen', answer: 'kent' },
      { label: 'hij', gloss: 'ontmoeten', answer: 'ontmoet' },
      { label: 'hij', gloss: 'geven', answer: 'geeft' },
    ],
    explanation: 'vindt (d + t), weet and ontmoet (no second t), reist (z → s: reizen, hij reist), probeer (ee in a closed syllable), zal / zult.',
  },
  {
    type: 'drill', title: 'The past, inside the clause', grammar: ['imperfect-weak', 'imperfect-strong', 'toen-past', 'relative-clause', 'verb-final'],
    instruction: 'Type the simple past of the verb given. It stands at the end of a relative clause or a toen-clause.',
    items: [
      { nl: 'De buurman is de man die vroeger aan de universiteit ___.', cue: 'werken', answer: 'werkte' },
      { nl: 'Toen Bram klein was, ___ hij elke zomer met oma en opa op vakantie.', cue: 'gaan', answer: 'ging' },
      { nl: 'Bram was een kind dat elke dag op het strand ___.', cue: 'spelen', answer: 'speelde' },
      { nl: 'De dokter is de vrouw die zei dat Bram ___ rusten.', cue: 'moeten', answer: 'moest' },
      { nl: 'Het boek dat Lotte gisteren ___, was heel mooi.', cue: 'lezen', answer: 'las' },
      { nl: 'De film die wij vorig weekend ___, was te lang.', cue: 'zien', answer: 'zagen' },
      { nl: 'De jas die Lotte ___, was niet duur.', cue: 'kopen', answer: 'kocht' },
      { nl: 'Toen Bram klein was, ___ hij nooit met het vliegtuig.', cue: 'reizen', answer: 'reisde' },
      { nl: 'Toen ik de buurvrouw ___, was zij in de tuin.', cue: 'ontmoeten', answer: 'ontmoette' },
      { nl: 'De student die het antwoord ___, was Lotte.', cue: 'weten', answer: 'wist' },
    ],
    explanation: 'Weak verbs by ’t kofschip: werkte, ontmoette with -te; speelde, reisde with -de (reizen: the stem is reis, but the z of the infinitive decides — z is not in ’t kofschip). Strong verbs change the vowel: ging, las, zagen, kocht, wist, moest.',
  },
  {
    type: 'drill', title: 'Ken jij …? Everyone in the book', grammar: ['relative-clause', 'kennen-weten', 'separable-together', 'toen-past', 'modals', 'infinitive-end', 'adjective-e', 'possessives', 'imperfect-strong'],
    instruction: 'Translate. Every person you have met in two volumes, each with a relative clause.',
    items: [
      { en: 'Max is the big dog that always wants to walk in the park.', answer: 'Max is de grote hond die altijd in het park wil lopen.', accept: ['Max is de grote hond die altijd in het park lopen wil.'] },
      { en: 'Mimi is the small cat that is allowed to sleep on the bed.', answer: 'Mimi is de kleine kat die op het bed mag slapen.', accept: ['Mimi is de kleine kat die op het bed slapen mag.'] },
      { en: 'Emma is the friend who goes out with Lotte on Friday.', answer: 'Emma is de vriendin die vrijdag met Lotte uitgaat.', accept: ['Emma is de vriendin die op vrijdag met Lotte uitgaat.'] },
      { en: 'Jonas is the friend (whom) Bram has known for years.', answer: 'Jonas is de vriend die Bram al jaren kent.' },
      { en: 'Tom is the brother who lives in Antwerp.', answer: 'Tom is de broer die in Antwerpen woont.' },
      { en: 'Sofie is the sister (whom) Bram rings up every week.', answer: 'Sofie is de zus die Bram elke week opbelt.', accept: ['Sofie is de zus die Bram elke week belt.'] },
      { en: 'Noor is the child who lives in our street.', answer: 'Noor is het kind dat in onze straat woont.' },
      { en: 'His father and mother are the people who live in Ghent.', answer: 'Zijn vader en moeder zijn de mensen die in Gent wonen.' },
      { en: 'Grandma and grandpa are the people who went on holiday with Bram every summer.', answer: 'Oma en opa zijn de mensen die elke zomer met Bram op vakantie gingen.', accept: ['Oma en opa zijn de mensen die met Bram elke zomer op vakantie gingen.'] },
      { en: 'The doctor is the woman who said that Bram had to rest.', answer: 'De dokter is de vrouw die zei dat Bram moest rusten.', accept: ['De dokter is de vrouw die zei dat Bram rusten moest.'] },
    ],
    explanation: 'Noor is het kind dat …: a het-word, even for a girl. die Bram al jaren kent: Bram knows him — kent agrees with Bram. zei dat Bram moest rusten: a dat-clause inside a relative clause, each with its verb at the end.',
  },
  {
    type: 'drill', title: 'Why, if, and which one', grammar: ['want-omdat', 'als-inversion', 'verb-final', 'dat-clause', 'relative-clause', 'geen', 'geen-niet', 'niet', 'gaan', 'clock-time', 'days-op-om', 'wie-hoe', 'pijn-hebben'],
    instruction: 'The clauses of lesson 12, now with the people of this lesson. Rewrite as the task says: want keeps the normal order, omdat, als and dat send the verb to the end.',
    items: [
      { nl: 'Lotte gaat vandaag niet naar de universiteit. Zij is ziek.', task: 'Join with omdat', answer: 'Lotte gaat vandaag niet naar de universiteit, omdat zij ziek is.' },
      { nl: 'Bram koopt brood en kaas. Wij hebben geen brood meer.', task: 'Join with want', answer: 'Bram koopt brood en kaas, want wij hebben geen brood meer.' },
      { nl: 'Het regent. Wij gaan niet naar het park.', task: 'Start with “Als het regent,”', answer: 'Als het regent, gaan wij niet naar het park.' },
      { nl: 'De les is kort.', task: 'Start with “Lotte hoopt dat”', answer: 'Lotte hoopt dat de les kort is.' },
      { nl: 'Het is koud in de winter. De buurman zit niet op de bank.', task: 'Start with “Als het in de winter koud is,”', answer: 'Als het in de winter koud is, zit de buurman niet op de bank.' },
      { nl: 'Het is warm. De buurman leest in de tuin.', task: 'Start with “Als het warm is,”', answer: 'Als het warm is, leest de buurman in de tuin.' },
      { nl: 'De buurman loopt langzaam. Hij is heel oud.', task: 'Join with want', answer: 'De buurman loopt langzaam, want hij is heel oud.' },
      { nl: 'Noor vraagt: “Wie is de man die op de bank zit?”', task: 'Start with “Noor vraagt wie”', answer: 'Noor vraagt wie de man is die op de bank zit.', accept: ['Noor vraagt wie de man die op de bank zit is.'] },
      { nl: 'De collega die in Leuven woont, is nog heel jong.', task: 'Start with “Bram denkt dat”', answer: 'Bram denkt dat de collega die in Leuven woont, nog heel jong is.' },
      { nl: 'Mijn hoofd doet pijn. Ik ga naar de apotheek.', task: 'Join with omdat: “Ik ga …”', answer: 'Ik ga naar de apotheek, omdat mijn hoofd pijn doet.' },
      { nl: 'Noor heeft pijn in haar buik. Zij gaat niet naar school.', task: 'Join with want: “Noor gaat …”', answer: 'Noor gaat niet naar school, want zij heeft pijn in haar buik.', accept: ['Noor gaat niet naar school, want zij heeft buikpijn.'] },
      { nl: 'Lotte staat op donderdag vroeg op. Zij heeft om acht uur les.', task: 'Join with want', answer: 'Lotte staat op donderdag vroeg op, want zij heeft om acht uur les.' },
    ],
    explanation: 'want: the second half is a normal main clause (want wij hebben …). omdat, als, dat: the verb goes to the end (omdat zij ziek is, omdat mijn hoofd pijn doet). A clause at the front counts as one element: Als het warm is, leest de buurman … And “Noor vraagt wie de man is die …”: the relative clause may follow the verb.',
  },
  {
    type: 'drill', title: 'Point and say it: dit is de … die …', grammar: ['relative-clause', 'dit-is', 'plural', 'numbers', 'perfect-hebben', 'adjective-e', 'imperative', 'comparative', 'dan-als', 'kennen-weten'],
    instruction: 'Each picture comes with an English sentence. Say it in Dutch — and choose die or dat by the article of the noun.',
    items: [
      { image: 'tree', en: 'This is the tree that stands in our garden.', answer: 'Dit is de boom die in onze tuin staat.' },
      { image: 'door', en: 'This is the door that goes to the kitchen.', answer: 'Dit is de deur die naar de keuken gaat.' },
      { image: 'chairs-four', en: 'These are the four chairs that stand in the kitchen.', answer: 'Dit zijn de vier stoelen die in de keuken staan.' },
      { image: 'table', en: 'This is the table that stands in her room.', answer: 'Dit is de tafel die in haar kamer staat.' },
      { image: 'phone', en: 'This is the cheap phone that Lotte has bought.', answer: 'Dit is de goedkope telefoon die Lotte gekocht heeft.', accept: ['Dit is de goedkope telefoon die Lotte heeft gekocht.'] },
      { image: 'apple', en: 'This is the apple that Noor is eating.', answer: 'Dit is de appel die Noor eet.' },
      { image: 'shop', en: 'This is the shop that is next to the station.', answer: 'Dit is de winkel die naast het station is.' },
      { image: 'tea', en: 'This is the tea that the neighbour (a woman) drinks every day.', answer: 'Dit is de thee die de buurvrouw elke dag drinkt.' },
      { image: 'dog-big', en: 'This is the dog that is bigger than Mimi.', answer: 'Dit is de hond die groter is dan Mimi.', accept: ['Dit is de hond die groter dan Mimi is.'] },
      { image: 'plane', en: 'This is the plane that flies to Spain.', answer: 'Dit is het vliegtuig dat naar Spanje vliegt.' },
      { image: 'hotel', en: 'This is the hotel that Bram and Lotte have found.', answer: 'Dit is het hotel dat Bram en Lotte gevonden hebben.', accept: ['Dit is het hotel dat Bram en Lotte hebben gevonden.'] },
      { image: 'key', en: 'Do you know where my key is?', answer: 'Weet jij waar mijn sleutel is?' },
      { image: 'water', en: 'Take the medicine with water!', answer: 'Neem het medicijn met water!' },
    ],
    explanation: 'de boom, de deur, de tafel, de telefoon, de appel, de winkel, de thee, de hond → die; de stoelen (plural) → die; het vliegtuig, het hotel → dat. “Dit zijn” for a plural. A fact (where the key is) → weten.',
  },
  {
    type: 'drill', title: 'Everything so far, inside relative clauses', grammar: ['plural', 'numbers', 'er-is-zijn', 'possessives', 'wie-hoe', 'clock-time', 'days-op-om', 'adjective-e', 'geen-niet', 'geen', 'niet', 'adverb-position', 'hij-het-things', 'dit-is', 'de-het', 'question-word', 'yes-no-question'],
    instruction: 'Type the missing word. Every grammar point of volumes zero and one, now around die and dat.',
    items: [
      { nl: 'Ik ken de ___ die in Leuven Nederlands leren.', cue: 'student', answer: 'studenten' },
      { nl: 'De buren hebben twee ___ die altijd in de tuin zitten.', cue: 'kat', answer: 'katten' },
      { nl: 'In de keuken ___ vier stoelen die Bram mooi vindt.', cue: 'er is / er zijn', answer: 'zijn er' },
      { nl: 'Bram koopt brood en kaas in de ___ die naast het station is.', en: 'Bram buys bread and cheese in the shop next to the station.', answer: 'winkel' },
      { nl: 'Lotte heeft een leraar die ___ auto heeft.', en: 'Lotte has a teacher who has no car.', answer: 'geen' },
      { nl: 'Ken jij het boek dat Lotte leest? ___ is heel mooi.', cue: 'hij / het', answer: 'Het' },
      { nl: 'Is dat de buurvrouw die ___ in de tuin werkt?', en: 'Is that the neighbour who likes working in the garden?', answer: 'graag' },
      { nl: 'Dat is ___ buurman.', en: 'That is our neighbour.', answer: 'onze' },
      { nl: 'Dat is ___ kantoor.', en: 'That is our office.', answer: 'ons' },
      { nl: '___ is de man die op de bank zit?', en: 'Who is the man sitting on the bench?', answer: 'Wie' },
      { nl: '___ heet de leraar die Noor op school heeft?', en: 'What is the name of Noor’s teacher at school?', answer: 'Hoe' },
      { nl: 'De les die ___ negen uur begint, is lang.', cue: 'op / om', answer: 'om' },
      { nl: 'Lotte heeft ___ dinsdag een les die heel moeilijk is.', cue: 'op / om', answer: 'op' },
      { nl: 'De buurman is een ___ man die altijd leest.', cue: 'oud', answer: 'oude' },
      { nl: 'Bram werkt in een ___ kantoor.', cue: 'groot', answer: 'groot' },
      { image: 'university', nl: 'Wat is dit?', answer: 'Dit is de universiteit.', accept: ['Dit is een universiteit.', 'Dat is de universiteit.', 'Dat is een universiteit.', 'Het is de universiteit.', 'Het is een universiteit.'] },
    ],
    explanation: 'In de keuken zijn er …: after a place in first position, er follows the verb. onze buurman (a de-word), ons kantoor (a het-word). een groot kantoor: een + het-word, no -e. om + clock time, op + day. het boek → het.',
  },
  {
    type: 'drill', title: 'Volume two in one page', grammar: ['separable', 'separable-together', 'separable-perfect', 'comparative', 'superlative', 'dan-als', 'imperfect-weak', 'imperfect-strong', 'toen-past', 'reflexive', 'imperative', 'pijn-hebben', 'zullen-future', 'te-infinitive', 'over-geleden'],
    instruction: 'Every grammar point of lessons 13–17. Rewrite as the task says.',
    items: [
      { nl: 'Bram staat om zeven uur op.', task: 'Start with “Ik weet dat”', answer: 'Ik weet dat Bram om zeven uur opstaat.' },
      { nl: 'Bram neemt zijn tas mee.', task: 'Use the perfect', answer: 'Bram heeft zijn tas meegenomen.' },
      { nl: 'In de winter gaan wij met de trein naar Oostende.', task: 'Use zullen', answer: 'In de winter zullen wij met de trein naar Oostende gaan.', accept: ['Wij zullen in de winter met de trein naar Oostende gaan.'] },
      { nl: 'Max is groot. Mimi is klein.', task: 'Make one sentence: “Max is … dan Mimi.”', answer: 'Max is groter dan Mimi.' },
      { nl: 'Leuven is mooi. Gent is ook mooi.', task: 'Use “even … als”: “Gent is …”', answer: 'Gent is even mooi als Leuven.' },
      { nl: 'Lotte leest snel. Zij leest het snelst.', task: 'Make one sentence: “Lotte is de student die …”', answer: 'Lotte is de student die het snelst leest.' },
      { nl: 'Bram woont in Oostende.', task: 'Start with “Toen Bram klein was,” — simple past', answer: 'Toen Bram klein was, woonde hij in Oostende.' },
      { nl: 'Wij gaan elke zomer naar zee.', task: 'Start with “Vroeger” — simple past', answer: 'Vroeger gingen wij elke zomer naar zee.' },
      { nl: 'Ik voel me niet goed.', task: 'Change ik to Lotte', answer: 'Lotte voelt zich niet goed.' },
      { nl: 'Bram haast zich naar de trein.', task: 'Change Bram to wij', answer: 'Wij haasten ons naar de trein.' },
      { nl: 'Jij neemt een medicijn met water.', task: 'Make it an imperative', answer: 'Neem een medicijn met water!' },
      { nl: 'Mijn rug doet pijn.', task: 'Say it with hebben: “Ik heb …”', answer: 'Ik heb rugpijn.', accept: ['Ik heb pijn aan mijn rug.', 'Ik heb pijn in mijn rug.'] },
      { nl: 'Wij vliegen volgende zomer naar Spanje.', task: 'Use zullen', answer: 'Wij zullen volgende zomer naar Spanje vliegen.', accept: ['Volgende zomer zullen wij naar Spanje vliegen.'] },
      { nl: 'Bram kookt beter.', task: 'Start with “Bram probeert”', answer: 'Bram probeert beter te koken.' },
      { nl: 'De cursus begint over drie weken.', task: 'It began three weeks ago: use geleden and the perfect', answer: 'De cursus is drie weken geleden begonnen.', accept: ['Drie weken geleden is de cursus begonnen.'] },
    ],
    explanation: 'opstaat: one word at the end of a subclause; meegenomen: ge- in the middle. groter dan, even mooi als, het snelst. zich, ons: the reflexive follows the person. Neem!: the imperative is the stem. over drie weken (future) — drie weken geleden (past).',
  },
  {
    type: 'arrange', title: 'Lotte’s teacher', grammar: ['relative-clause', 'kennen-weten', 'verb-final'],
    instruction: 'Build: “I know the teacher who teaches Lotte.” Two tiles are traps.',
    nl: 'Ik ken de leraar die Lotte les geeft.', en: 'I know the teacher who teaches Lotte.', image: 'classroom', distractors: ['weet', 'dat'],
    accept: ['De leraar die Lotte les geeft, ken ik.'],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'De buurman die altijd leest', image: 'neighbours', grammar: ['relative-clause', 'kennen-weten', 'imperfect-strong', 'perfect-hebben', 'modals', 'v2-inversion', 'dat-clause'],
    instruction: 'The last story of volume two. Read and listen to every line, then read it again without the English. Find every die and dat, and decide each time which noun it belongs to.',
    lines: [
      { nl: 'Het is vrijdag, vier uur. Bram werkt vandaag thuis.', en: 'It is Friday, four o’clock. Bram is working at home today.', image: 'man-working' },
      { nl: 'Lotte komt met de fiets thuis. Zij heeft vandaag twee lessen gehad.', en: 'Lotte comes home on her bike. She has had two classes today.', image: 'woman-bike' },
      { nl: 'Op de bank naast de grote boom zit de buurman. Hij leest weer een boek.', en: 'The neighbour is sitting on the bench next to the big tree. He is reading a book again.', image: 'old-man' },
      { speaker: 'De buurman', nl: 'Dag Lotte! Hoe waren je lessen?', en: 'Hello Lotte! How were your classes?', image: 'old-man' },
      { speaker: 'Lotte', nl: 'Heel goed! Ik heb een leraar die heel goed les geeft.', en: 'Very good! I have a teacher who teaches very well.', image: 'classroom' },
      { speaker: 'De buurman', nl: 'Hoe heet die leraar? Die ken ik misschien.', en: 'What is that teacher called? Maybe I know him.', image: 'old-man' },
      { speaker: 'Lotte', nl: 'Ik weet zijn naam niet meer! Het is een lange man die altijd met de fiets komt.', en: 'I can’t remember his name! He is a tall man who always comes by bike.', image: 'woman' },
      { speaker: 'De buurman', nl: 'Die ken ik! Hij was vroeger mijn student.', en: 'I know him! He used to be my student.', image: 'old-man' },
      { speaker: 'Lotte', nl: 'Jouw student? Heb jij aan de universiteit gewerkt?', en: 'Your student? Did you work at the university?', image: 'university' },
      { speaker: 'De buurman', nl: 'Ja, heel lang. Hij was een student die altijd het antwoord wist.', en: 'Yes, for a very long time. He was a student who always knew the answer.', image: 'students' },
      { nl: 'Bram ziet Lotte en komt ook naar buiten. Dan staat de buurvrouw aan de deur, met haar twee katten.', en: 'Bram sees Lotte and comes out of the house too. Then the neighbour’s wife appears at the door, with her two cats.', image: 'old-woman' },
      { speaker: 'De buurvrouw', nl: 'Bram, wie was de jonge man die gisteren met jullie in de tuin zat?', en: 'Bram, who was the young man who sat in the garden with you yesterday?', image: 'old-woman' },
      { speaker: 'Bram', nl: 'Dat was een collega. Hij werkt ook in Brussel, maar hij woont nu in Leuven.', en: 'That was a colleague. He works in Brussels too, but he lives in Leuven now.', image: 'colleagues' },
      { speaker: 'De buurvrouw', nl: 'Kent hij hier al mensen?', en: 'Does he know anyone here yet?', image: 'old-woman' },
      { speaker: 'Bram', nl: 'Nee, nog niet. Hij kent in Leuven nog geen mensen.', en: 'No, not yet. He doesn’t know anyone in Leuven yet.', image: 'man' },
      { speaker: 'De buurvrouw', nl: 'Dan moet hij volgende zaterdag koffie komen drinken! Ik hoop dat hij komt.', en: 'Then he must come for coffee next Saturday! I hope he comes.', image: 'coffee' },
      { nl: 'Noor loopt ook naar de bank. Zij eet een ijsje en is heel blij.', en: 'Noor walks to the bench too. She is eating an ice cream and is very happy.', image: 'child' },
      { speaker: 'Noor', nl: 'Buurman, ik heb een nieuwe leraar op school! Ken jij die ook?', en: 'Neighbour, I have a new teacher at school! Do you know him too?', image: 'school' },
      { speaker: 'De buurman', nl: 'Nee, die ken ik niet. Maar ik weet dat jouw school heel goede leraren heeft.', en: 'No, I don’t know him. But I know that your school has very good teachers.', image: 'old-man' },
      { speaker: 'Lotte', nl: 'Bram, wij kennen de buurman nu al een jaar, maar ik weet zijn naam niet!', en: 'Bram, we have known the neighbour for a year now, but I don’t know his name!', image: 'couple-talking' },
      { speaker: 'Bram', nl: 'Ik weet het ook niet. Hij is de buurman die altijd leest!', en: 'I don’t know it either. He is the neighbour who always reads!', image: 'man' },
      { nl: '“Dat is een mooie naam,” zegt de buurman, en hij leest weer.', en: '“That is a nice name,” says the neighbour, and he goes back to his book.', image: 'old-man' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'inversion', 'kennen-weten'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the story. Answer without looking back.',
    items: [
      { nl: 'Werkt Bram vandaag in Brussel?', answer: 'Nee' },
      { nl: 'Heeft Lotte vandaag twee lessen gehad?', answer: 'Ja' },
      { nl: 'Weet Lotte hoe haar leraar heet?', answer: 'Nee' },
      { nl: 'Kent de buurman de leraar die Lotte heeft?', answer: 'Ja' },
      { nl: 'Heeft de buurman vroeger aan de universiteit gewerkt?', answer: 'Ja' },
      { nl: 'Was de jonge man in de tuin Jonas?', answer: 'Nee' },
      { nl: 'Kent de buurman de nieuwe leraar die Noor heeft?', answer: 'Nee' },
    ],
  },
  {
    type: 'drill', title: 'Answer in full', grammar: ['relative-clause', 'kennen-weten', 'perfect-hebben', 'imperfect-strong', 'question-word', 'modals'],
    instruction: 'Answer each question about the story with a complete sentence. When the task gives a start, use it.',
    items: [
      { nl: 'Wat heeft Lotte vandaag gehad?', answer: 'Lotte heeft vandaag twee lessen gehad.', accept: ['Zij heeft vandaag twee lessen gehad.', 'Lotte heeft twee lessen gehad.', 'Zij heeft twee lessen gehad.', 'Twee lessen.'] },
      { nl: 'Wat doet de buurman op de bank?', answer: 'De buurman leest een boek.', accept: ['Hij leest een boek.', 'Hij leest.', 'De buurman leest.', 'Hij leest weer een boek.', 'De buurman leest weer een boek.'] },
      { nl: 'Waar heeft de buurman vroeger gewerkt?', answer: 'De buurman heeft vroeger aan de universiteit gewerkt.', accept: ['Hij heeft vroeger aan de universiteit gewerkt.', 'Hij heeft aan de universiteit gewerkt.', 'De buurman heeft aan de universiteit gewerkt.', 'Vroeger heeft hij aan de universiteit gewerkt.', 'Aan de universiteit.', 'Hij werkte vroeger aan de universiteit.', 'De buurman werkte vroeger aan de universiteit.', 'Vroeger werkte hij aan de universiteit.'] },
      { nl: 'Hoe was de leraar als student?', task: 'Start with “Hij was een student die …”', answer: 'Hij was een student die altijd het antwoord wist.', accept: ['Hij was een student die het antwoord altijd wist.'] },
      { nl: 'Wie was de jonge man in de tuin?', answer: 'Dat was een collega.', accept: ['Het was een collega.', 'Dat was zijn collega.', 'Het was zijn collega.', 'Een collega.', 'Dat was een collega van Bram.', 'Het was een collega van Bram.', 'Een collega van Bram.','Dat was een collega die ook in Brussel werkt.', 'Het was een collega die ook in Brussel werkt.'] },
      { nl: 'Wanneer moet de collega koffie komen drinken?', answer: 'Hij moet volgende zaterdag koffie komen drinken.', accept: ['De collega moet volgende zaterdag koffie komen drinken.', 'Volgende zaterdag moet hij koffie komen drinken.', 'Hij moet volgende zaterdag komen.', 'Volgende zaterdag.'] },
      { nl: 'Kent de buurman de nieuwe leraar die Noor heeft?', task: 'Answer with “Nee, die …”', answer: 'Nee, die kent hij niet.', accept: ['Nee, die kent de buurman niet.'] },
      { nl: 'Weet Lotte hoe de buurman heet?', task: 'Answer with “Nee, dat …”', answer: 'Nee, dat weet zij niet.', accept: ['Nee, dat weet Lotte niet.'] },
      { nl: 'Hoe lang kennen Bram en Lotte de buurman al?', answer: 'Zij kennen de buurman al een jaar.', accept: ['Bram en Lotte kennen de buurman al een jaar.', 'Zij kennen de buurman nu al een jaar.', 'Bram en Lotte kennen de buurman nu al een jaar.', 'Zij kennen hem al een jaar.', 'Zij kennen hem nu al een jaar.', 'Bram en Lotte kennen hem al een jaar.', 'Bram en Lotte kennen hem nu al een jaar.', 'Al een jaar.', 'Een jaar.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['relative-clause', 'kennen-weten', 'participle-no-ge'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'De buurman is de man die altijd leest.' },
      { listen: 'Noor is het kind dat in onze straat woont.' },
      { listen: 'Ken jij de vrouw die naast ons woont?' },
      { listen: 'Ik heb de buurvrouw gisteren ontmoet.' },
      { listen: 'Weet jij waar de universiteit is?' },
      { listen: 'Lotte heeft een leraar die heel goed les geeft.' },
      { listen: 'Wat is er gebeurd?' },
      { listen: 'De collega die ik ken, woont ook in Leuven.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['relative-clause', 'kennen-weten', 'participle-no-ge', 'perfect-hebben', 'separable-together', 'days-op-om', 'time-place'],
    instruction: 'Translate. “You” is one person unless it says plural.',
    items: [
      { en: 'Do you know the child who is playing with Max?', answer: 'Ken jij het kind dat met Max speelt?' },
      { en: 'Lotte is a student at the university in Leuven.', answer: 'Lotte is student aan de universiteit in Leuven.', accept: ['Lotte is een student aan de universiteit in Leuven.'] },
      { en: 'Bram has a colleague who also lives in Leuven.', answer: 'Bram heeft een collega die ook in Leuven woont.' },
      { en: 'I don’t know where my phone is.', answer: 'Ik weet niet waar mijn telefoon is.' },
      { en: 'The book I am reading is very beautiful.', answer: 'Het boek dat ik lees, is heel mooi.' },
      { en: 'The teacher knows the answer.', answer: 'De leraar weet het antwoord.', accept: ['De leraar kent het antwoord.'] },
      { en: 'We visited the neighbours on Sunday.', answer: 'Wij hebben zondag de buren bezocht.', accept: ['Zondag hebben wij de buren bezocht.', 'Wij hebben op zondag de buren bezocht.', 'Op zondag hebben wij de buren bezocht.', 'Wij hebben de buren zondag bezocht.', 'Wij hebben de buren op zondag bezocht.', 'Wij bezochten zondag de buren.', 'Zondag bezochten wij de buren.', 'Wij bezochten de buren op zondag.', 'Op zondag bezochten wij de buren.'] },
      { en: 'I have met the woman who lives next door to us.', answer: 'Ik heb de vrouw ontmoet die naast ons woont.', accept: ['Ik heb de vrouw die naast ons woont ontmoet.'] },
      { en: 'The neighbour (a woman) wants to meet the colleague who lives in Leuven.', answer: 'De buurvrouw wil de collega ontmoeten die in Leuven woont.', accept: ['De buurvrouw wil de collega die in Leuven woont ontmoeten.'] },
      { en: 'The man I met yesterday is a teacher.', answer: 'De man die ik gisteren ontmoet heb, is leraar.', accept: ['De man die ik gisteren heb ontmoet, is leraar.', 'De man die ik gisteren ontmoet heb, is een leraar.', 'De man die ik gisteren heb ontmoet, is een leraar.'] },
      { en: 'Do you know the students who live next door to us?', answer: 'Ken jij de studenten die naast ons wonen?' },
      { en: 'The lesson that begins at nine is difficult.', answer: 'De les die om negen uur begint, is moeilijk.' },
      { en: 'Do you know when the plane arrives?', answer: 'Weet jij wanneer het vliegtuig aankomt?' },
      { en: 'The neighbour has told us a lot about the old days.', answer: 'De buurman heeft ons veel over vroeger verteld.', accept: ['De buurman heeft ons over vroeger veel verteld.', 'De buurman heeft veel over vroeger verteld.', 'De buurman heeft over vroeger veel verteld.'] },
    ],
  },
  {
    type: 'drill', title: 'Volume two in one round', grammar: ['relative-clause', 'kennen-weten', 'participle-no-ge', 'want-omdat', 'verb-final', 'plural', 'present-regular', 'inversion', 'v2-inversion', 'separable-together', 'perfect-hebben'],
    instruction: 'The final round of volume two: everything mixed. Type every answer. No hints beyond the task.',
    items: [
      { nl: 'drie ___', cue: 'les', answer: 'lessen' },
      { nl: 'de buurman ___ altijd leest', answer: 'die' },
      { nl: 'het kind ___ met Max speelt', answer: 'dat' },
      { nl: 'Ik ___ de buurvrouw niet.', cue: 'kennen / weten', answer: 'ken' },
      { nl: 'Ik ___ niet waar zij woont.', cue: 'kennen / weten', answer: 'weet' },
      { nl: 'Ik heb haar gisteren ___.', cue: 'ontmoeten', answer: 'ontmoet' },
      { nl: 'Dit is het boek. De buurman leest het.', task: 'Join with die or dat', answer: 'Dit is het boek dat de buurman leest.' },
      { nl: 'De man zit op de bank. Hij is onze buurman.', task: 'Make one sentence: start with “De man die …”', answer: 'De man die op de bank zit, is onze buurman.' },
      { nl: 'Wij bezoeken de buren.', task: 'Use the perfect', answer: 'Wij hebben de buren bezocht.' },
      { nl: 'Bram staat om zeven uur op.', task: 'Start with “Bram is de man die …”', answer: 'Bram is de man die om zeven uur opstaat.' },
      { en: 'Do you know Tom? — Yes, I know him.', answer: 'Ken jij Tom? Ja, die ken ik.', accept: ['Ken jij Tom? Ja, ik ken hem.'] },
      { en: 'Lotte is at home, because she is ill. (use omdat)', answer: 'Lotte is thuis, omdat zij ziek is.' },
      { en: 'The hotel that Bram has found is by the sea.', answer: 'Het hotel dat Bram gevonden heeft, is aan zee.', accept: ['Het hotel dat Bram heeft gevonden, is aan zee.'] },
      { listen: 'Ken jij de man die ik gisteren ontmoet heb?' },
    ],
  },
  {
    type: 'complete', title: 'Volume two: done',
    instruction: 'Separable verbs, comparisons, the simple past, reflexives and the imperative, plans with zullen — and now die and dat, the two verbs for “to know”, and the participles without ge-. You can say who everyone is, what you know about them, and whom you have met. Jij bent een student die heel goed Nederlands leert.',
  },
];
