/**
 * Lesson 23 — Terwijl Lotte studeert … Volume three (A2+ → B1).
 * Targets: terwijl, voordat, nadat, zodra, hoewel, zodat, sinds, eindigen, tijd, project.
 * Structure: tot, totdat, dus, daarom.
 * Extra vocabulary (vocabulary/terwijl.js): groep, opdracht, verslag, bespreken, afspreken, samenwerken, eerst,
 * daarna, uiteindelijk, meteen, pauze, deadline, verdelen, deel, indienen, mail, ander, elkaar, idee, minuut,
 * tijdens, druk, hard, genoeg, weinig, vanavond, regen, paraplu.
 * Grammar: time conjunctions (terwijl, voordat, nadat, zodra, sinds, totdat — with als, toen, wanneer from earlier) ·
 * hoewel and zodat (verb to the end) against dus and daarom (adverbs: the verb follows) · “Ik weet niet of …”.
 * Story: Lotte does a group project for her course with three other students — Ines, Pieter and Yasmine — about the
 * languages of Leuven. They arrange to meet, divide the work and write a report; while Lotte studies, Bram cooks;
 * before the deadline they work late; as soon as it is handed in they celebrate. Although it rains, Bram walks to
 * the station: he still has no bike.
 */
import { listenPages, recallPages } from '../review-pages.js';

export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Een project met vier', grammar: ['time-conjunctions', 'hoewel-zodat', 'verb-final', 'separable'],
    instruction: 'Lotte’s group project, from the first meeting to the deadline. Look and listen, and say every sentence out loud after the voice — twice. Listen for the word that joins the two parts of each sentence.',
    cards: [
      { nl: 'Lotte doet een project voor haar cursus, samen met drie andere studenten.', en: 'Lotte is doing a project for her course, together with three other students.', image: 'students-group' },
      { nl: 'Zij heten Ines, Pieter en Yasmine. Het is een groep van vier.', en: 'They are called Ines, Pieter and Yasmine. It is a group of four.', image: 'students' },
      { nl: 'Het project gaat over de talen van Leuven.', en: 'The project is about the languages of Leuven.', image: 'university' },
      { nl: 'Voordat zij beginnen, spreken zij af in de bibliotheek.', en: 'Before they begin, they arrange to meet in the library.', image: 'classroom' },
      { nl: 'Zij verdelen het werk, zodat elke student een deel heeft.', en: 'They divide the work, so that every student has a part.', image: 'students-group' },
      { nl: 'Terwijl Lotte studeert, kookt Bram.', en: 'While Lotte studies, Bram cooks.', image: 'man-cooking' },
      { nl: 'Sinds maandag werkt Lotte elke avond aan het verslag.', en: 'Since Monday Lotte has been working on the report every evening.', image: 'woman-studying' },
      { nl: 'Zij heeft weinig tijd: de deadline is vrijdag.', en: 'She has little time: the deadline is Friday.', image: 'clock' },
      { nl: 'Hoewel het regent, loopt Bram naar het station. Hij heeft nog altijd geen fiets.', en: 'Although it is raining, Bram walks to the station. He still has no bike.', image: 'rain' },
      { nl: 'Zodra het verslag klaar is, vieren zij het met een feest.', en: 'As soon as the report is finished, they celebrate with a party.', image: 'night-out' },
    ],
    note: 'Seven little words that join two sentences about time and reasons: terwijl = while, voordat = before, nadat = after, zodra = as soon as, sinds = since, hoewel = although, zodat = so that. The verb in the part they start goes to the end — the rule you know from omdat and dat. het project, de projecten. de tijd = time (not the clock time: that is het uur). eindigen = to end. de groep = group; het verslag = report; de deadline = deadline (in English).',
  },
  {
    type: 'observe', title: 'Group work', grammar: ['separable', 'separable-perfect', 'perfect-hebben', 'hoewel-zodat', 'of-whether'],
    instruction: 'The words of group work. Two verbs are separable: afspreken (spreek … af) and samenwerken (werk … samen); indienen means to hand in.',
    cards: [
      { nl: 'Eerst bespreken zij het idee. Daarna verdelen zij het werk.', en: 'First they discuss the idea. After that they divide the work.', image: 'students-group' },
      { nl: 'Zij werken goed samen. Zij helpen elkaar.', en: 'They work well together. They help each other.', image: 'students' },
      { nl: 'Elke student schrijft een deel van het verslag.', en: 'Every student writes a part of the report.', image: 'man-writing' },
      { nl: 'Pieter stuurt de andere studenten een mail.', en: 'Pieter sends the other students an e-mail.', image: 'phone' },
      { nl: 'Tijdens de pauze drinken zij koffie.', en: 'During the break they drink coffee.', image: 'coffee' },
      { nl: 'Zij werken hard, want zij hebben niet genoeg tijd.', en: 'They work hard, because they don’t have enough time.', image: 'woman-working' },
      { nl: 'Ik weet niet of het verslag op tijd klaar is.', en: 'I don’t know whether the report will be ready in time.', image: 'clock' },
      { nl: 'Uiteindelijk dienen zij het verslag op vrijdag in.', en: 'In the end they hand in the report on Friday.', image: 'university' },
      { nl: 'Het is laat. Daarom gaat Lotte meteen slapen.', en: 'It is late. That’s why Lotte goes to sleep straight away.', image: 'woman-sleeping' },
      { nl: 'Vanavond is er een feest. De les eindigt om vier uur, dus wij hebben tijd.', en: 'Tonight there is a party. The lesson ends at four, so we have time.', image: 'night-out' },
    ],
    note: 'eerst = first, daarna = after that, uiteindelijk = in the end, meteen = straight away. bespreken = to discuss; afspreken = to arrange (to meet); samenwerken = to work together; elkaar = each other. de opdracht = assignment, de pauze = break, de mail = e-mail. tijdens = during (with a noun). op tijd = in time, on time. dus = so, daarom = that is why: both are followed by the verb, not sent to the end.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['time-conjunctions'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Terwijl Lotte aan het verslag werkt, kookt Bram in de keuken.', en: 'While Lotte works on the report, Bram cooks in the kitchen.', answer: 'man-cooking',
    choices: [{ image: 'man-cooking', nl: 'Bram kookt.' }, { image: 'woman-sleeping', nl: 'Lotte slaapt.' }, { image: 'rain', nl: 'Het regent.' }, { image: 'night-out', nl: 'een feest' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['hoewel-zodat'],
    instruction: 'Listen without reading. What is the weather like?',
    nl: 'Hoewel het regent, loopt Bram naar het station.', en: 'Although it is raining, Bram walks to the station.', answer: 'rain',
    choices: [{ image: 'sun', nl: 'zon' }, { image: 'rain', nl: 'regen' }, { image: 'snow', nl: 'sneeuw' }, { image: 'station', nl: 'het station' }],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['time-conjunctions'],
    instruction: 'Listen. What do they do as soon as the report is finished?',
    nl: 'Zodra het verslag klaar is, gaan zij samen uit.', en: 'As soon as the report is finished, they go out together.', answer: 'night-out',
    choices: [{ image: 'classroom', nl: 'een les' }, { image: 'night-out', nl: 'uitgaan' }, { image: 'woman-studying', nl: 'studeren' }, { image: 'man-sleeping', nl: 'slapen' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['de-het', 'plural'],
    instruction: 'Type the Dutch. Nouns with their article.',
    items: [
      { image: 'students-group', en: 'the group', answer: 'de groep' },
      { en: 'the project', answer: 'het project' },
      { en: 'the projects', answer: 'de projecten' },
      { en: 'the report', answer: 'het verslag' },
      { en: 'the assignment', answer: 'de opdracht' },
      { image: 'clock', en: 'the time (that you have)', answer: 'de tijd' },
      { en: 'the break', answer: 'de pauze' },
      { en: 'the deadline', answer: 'de deadline' },
      { en: 'the part', answer: 'het deel' },
      { en: 'the idea', answer: 'het idee' },
      { en: 'the e-mail', answer: 'de mail' },
      { image: 'rain', en: 'the umbrella', answer: 'de paraplu' },
    ],
    explanation: 'Four het-words: het project, het verslag, het deel, het idee. idee → ideeën, with two dots (lesson 21: tweeëntwintig).',
  },
  {
    type: 'drill', title: 'Hear and spell', grammar: ['time-conjunctions', 'hoewel-zodat', 'of-whether'],
    instruction: 'Play each one and type it.',
    items: [
      { listen: 'terwijl' },
      { listen: 'voordat' },
      { listen: 'zodra' },
      { listen: 'hoewel' },
      { listen: 'Terwijl Lotte studeert, kookt Bram.' },
      { listen: 'Hoewel het regent, gaat hij lopen.' },
      { listen: 'Ik weet niet of hij komt.' },
      { listen: 'Wij hebben weinig tijd.' },
    ],
    explanation: 'ter-WIJL, voor-DAT, zo-DRA, hoe-WEL: the stress falls on the second part.',
  },

  // ——— Grammar: time ———
  {
    part: 'Grammar', type: 'grammar', title: 'Terwijl, voordat, nadat, zodra, sinds, totdat', grammar: ['time-conjunctions', 'verb-final', 'v2-inversion', 'als-inversion', 'toen-past', 'perfect-hebben'],
    body: [
      'You already join sentences with **als**, **toen** and **wanneer** (lessons 12 and 15). Six more words tell you **when** something happens compared with something else: **terwijl** (while — at the same time), **voordat** (before), **nadat** (after), **zodra** (as soon as), **sinds** (since) and **totdat** (until). They all start a subordinate clause, so the verb goes to the **end**: *terwijl Lotte **studeert**, voordat de les **begint**, nadat zij **gegeten hebben***.',
      'The clause can come second or first. **Second:** *Bram kookt, **terwijl** Lotte studeert.* **First:** then the whole clause takes the first place, and the main clause continues with its verb — exactly as with als: ***Terwijl** Lotte studeert, **kookt** Bram. **Voordat** de les begint, **drinken** wij koffie.* The comma between the two verbs is usual.',
      '**nadat** normally takes the perfect, because the first thing is finished: ***Nadat** zij het verslag **geschreven hebben**, gaan zij uit.* **sinds** takes the present when the situation still continues — English uses *has been*: ***Sinds** Tom in Leuven **woont**, is hij minder moe.* (since he has been living in Leuven).',
      '**Prepositions and conjunctions.** English uses *before, after, until* both before a noun and before a sentence. Dutch has two forms: **voor** / **na** / **tot** before a noun — *voor de les, na het eten, tot vrijdag* — and **voordat** / **nadat** / **totdat** before a sentence — *voordat de les begint, nadat wij gegeten hebben, totdat het klaar is*. (In speech you also hear voor and tot before a sentence.) **sinds** is both: *sinds maandag, sinds Tom hier woont*. **tijdens** (during) only goes before a noun: *tijdens de pauze*.',
      '**eindigen** = to end (intransitive): *De les **eindigt** om vier uur. Het feest is om twee uur **geëindigd*** — with zijn when it means to come to an end, and with two dots on the e of geëindigd.',
    ],
    tables: [
      { caption: 'The time words', rows: [
        { nl: 'Bram kookt, [terwijl] Lotte studeert.', en: 'while' },
        { nl: '[Voordat] de les begint, drinken wij koffie.', en: 'before' },
        { nl: '[Nadat] zij gegeten hebben, gaan zij uit.', en: 'after (+ perfect)' },
        { nl: '[Zodra] het verslag klaar is, vieren wij het.', en: 'as soon as' },
        { nl: '[Sinds] Tom in Leuven woont, slaapt hij beter.', en: 'since (+ present)' },
        { nl: 'Wij werken, [totdat] het klaar is.', en: 'until' },
      ] },
      { caption: 'Before a noun — before a sentence', rows: [
        { nl: '[voor] de les — [voordat] de les begint', en: 'before' },
        { nl: '[na] het eten — [nadat] wij gegeten hebben', en: 'after' },
        { nl: '[tot] vrijdag — [totdat] het klaar is', en: 'until' },
        { nl: '[tijdens] de pauze — [terwijl] wij pauze hebben', en: 'during — while' },
      ] },
    ],
    examples: [
      { nl: 'Terwijl Bram kookt, luistert hij naar de radio.', en: 'While Bram cooks, he listens to the radio.' },
      { nl: 'Zodra de les eindigt, gaat Lotte naar de bibliotheek.', en: 'As soon as the lesson ends, Lotte goes to the library.' },
      { nl: 'Sinds maandag regent het.', en: 'It has been raining since Monday.' },
      { nl: 'Lotte werkt tot tien uur.', en: 'Lotte works until ten o’clock.' },
    ],
  },
  {
    type: 'drill', title: 'Which time word?', grammar: ['time-conjunctions'], choices: ['terwijl', 'voordat', 'nadat', 'zodra', 'sinds', 'totdat'],
    instruction: 'First contact. Choose the word that fits the meaning.',
    items: [
      { nl: 'Bram kookt, ___ Lotte studeert.', answer: 'terwijl' },
      { nl: 'Wij drinken koffie, ___ de les begint.', answer: 'voordat' },
      { nl: 'Zij gaan uit, ___ zij gegeten hebben.', answer: 'nadat' },
      { nl: 'Wij vieren het, ___ het verslag klaar is.', answer: 'zodra' },
      { nl: 'Tom slaapt beter, ___ hij in Leuven woont.', answer: 'sinds' },
      { nl: 'Wij werken, ___ het verslag klaar is.', answer: 'totdat' },
    ],
    explanation: 'At the same time: terwijl. Before: voordat. After, with the perfect: nadat. Straight after: zodra. From then on: sinds. Up to then: totdat.',
  },
  {
    type: 'drill', title: 'Join the sentences', grammar: ['time-conjunctions', 'verb-final', 'separable-together', 'perfect-hebben'],
    instruction: 'Join the two sentences with the word the task gives. Keep the order of the sentences; the verb of the second part goes to the end.',
    items: [
      { nl: 'Bram kookt. Lotte studeert.', task: 'Join with terwijl', answer: 'Bram kookt, terwijl Lotte studeert.' },
      { nl: 'Wij drinken koffie. De les begint.', task: 'Join with voordat', answer: 'Wij drinken koffie, voordat de les begint.' },
      { nl: 'Zij gaan uit. Zij hebben het verslag ingediend.', task: 'Join with nadat', answer: 'Zij gaan uit, nadat zij het verslag ingediend hebben.', accept: ['Zij gaan uit, nadat zij het verslag hebben ingediend.'] },
      { nl: 'Lotte belt Tom. Het verslag is klaar.', task: 'Join with zodra', answer: 'Lotte belt Tom, zodra het verslag klaar is.' },
      { nl: 'Tom slaapt beter. Hij woont in Leuven.', task: 'Join with sinds', answer: 'Tom slaapt beter, sinds hij in Leuven woont.' },
      { nl: 'Zij werken. Het project is klaar.', task: 'Join with totdat', answer: 'Zij werken, totdat het project klaar is.' },
      { nl: 'Lotte luistert naar muziek. Zij schrijft.', task: 'Join with terwijl', answer: 'Lotte luistert naar muziek, terwijl zij schrijft.' },
      { nl: 'Pieter stuurt een mail. Hij gaat slapen.', task: 'Join with voordat', answer: 'Pieter stuurt een mail, voordat hij gaat slapen.' },
      { nl: 'Bram doet de afwas. Zij hebben gegeten.', task: 'Join with nadat', answer: 'Bram doet de afwas, nadat zij gegeten hebben.', accept: ['Bram doet de afwas, nadat zij hebben gegeten.'] },
      { nl: 'Wij gaan naar huis. De les eindigt.', task: 'Join with zodra', answer: 'Wij gaan naar huis, zodra de les eindigt.' },
    ],
    explanation: 'The verb of the subordinate clause goes to the end: terwijl Lotte studeert, nadat zij het verslag ingediend hebben (ingediend heeft and heeft ingediend are both right).',
  },
  {
    type: 'drill', title: 'Start with the time clause', grammar: ['time-conjunctions', 'als-inversion', 'v2-inversion', 'verb-final'],
    instruction: 'Rewrite the sentence so that it starts with the time clause. The main clause then begins with its verb.',
    items: [
      { nl: 'Bram kookt, terwijl Lotte studeert.', answer: 'Terwijl Lotte studeert, kookt Bram.' },
      { nl: 'Wij drinken koffie, voordat de les begint.', answer: 'Voordat de les begint, drinken wij koffie.', accept: ['Voordat de les begint, drinken we koffie.'] },
      { nl: 'Zij gaan uit, nadat zij gegeten hebben.', answer: 'Nadat zij gegeten hebben, gaan zij uit.', accept: ['Nadat zij hebben gegeten, gaan zij uit.'] },
      { nl: 'Lotte belt Tom, zodra het verslag klaar is.', answer: 'Zodra het verslag klaar is, belt Lotte Tom.' },
      { nl: 'Tom slaapt beter, sinds hij in Leuven woont.', answer: 'Sinds hij in Leuven woont, slaapt Tom beter.', accept: ['Sinds Tom in Leuven woont, slaapt hij beter.'] },
      { nl: 'Max slaapt, terwijl wij werken.', answer: 'Terwijl wij werken, slaapt Max.', accept: ['Terwijl we werken, slaapt Max.'] },
      { nl: 'Ik bel je, zodra ik thuis ben.', answer: 'Zodra ik thuis ben, bel ik je.', accept: ['Zodra ik thuis ben, bel ik jou.'] },
      { nl: 'Wij bespreken het idee, voordat wij het werk verdelen.', answer: 'Voordat wij het werk verdelen, bespreken wij het idee.', accept: ['Voordat we het werk verdelen, bespreken we het idee.'] },
    ],
    explanation: 'The clause is position one, so the verb comes next: Terwijl Lotte studeert, kookt Bram — never “…, Bram kookt”.',
  },
  {
    type: 'drill', title: 'voor or voordat, na or nadat, tot or totdat?', grammar: ['time-conjunctions', 'van-voor-bij'],
    instruction: 'Type the right word: before a noun voor, na, tot, tijdens; before a sentence voordat, nadat, totdat, terwijl.',
    items: [
      { nl: '___ de les drinken wij koffie.', en: 'Before the lesson we drink coffee.', answer: 'Voor' },
      { nl: '___ de les begint, drinken wij koffie.', en: 'Before the lesson starts, we drink coffee.', answer: 'Voordat' },
      { nl: '___ het eten doet Bram de afwas.', en: 'After the meal Bram does the washing-up.', answer: 'Na' },
      { nl: '___ zij gegeten hebben, doet Bram de afwas.', en: 'After they have eaten, Bram does the washing-up.', answer: 'Nadat' },
      { nl: 'Lotte werkt ___ tien uur.', en: 'Lotte works until ten o’clock.', answer: 'tot' },
      { nl: 'Lotte werkt, ___ het verslag klaar is.', en: 'Lotte works until the report is finished.', answer: 'totdat' },
      { nl: '___ de pauze drinken zij koffie.', en: 'During the break they drink coffee.', answer: 'Tijdens' },
      { nl: '___ zij pauze hebben, drinken zij koffie.', en: 'While they have a break, they drink coffee.', answer: 'Terwijl' },
      { nl: 'Tom woont in Leuven ___ november.', en: 'Tom has lived in Leuven since November.', answer: 'sinds' },
    ],
    explanation: 'A noun follows: voor, na, tot, tijdens, sinds. A sentence with its own verb follows: voordat, nadat, totdat, terwijl, sinds.',
  },

  // ——— Grammar: although, so that ———
  {
    type: 'grammar', title: 'Hoewel and zodat — dus and daarom', grammar: ['hoewel-zodat', 'want-omdat', 'verb-final', 'v2-inversion'],
    body: [
      'Four more words for reasons and results. Two are **conjunctions** like omdat — the verb goes to the end: **hoewel** (although) and **zodat** (so that). Two are **adverbs** — they count as the first element of a main clause, so the verb comes straight after them: **daarom** (that is why) and **dus** (so).',
      '**hoewel** gives a contrast: something happens in spite of something else. *Bram loopt naar het station, **hoewel** het **regent**. **Hoewel** het **regent**, **loopt** Bram naar het station.* It means the same as a sentence with *maar*: *Het regent, maar Bram loopt naar het station.*',
      '**zodat** gives a result or purpose: *Zij verdelen het werk, **zodat** elke student een deel **heeft**.* — so that every student has a part. It usually comes second.',
      '**daarom** = that is why: the reason comes first, in its own sentence, and daarom starts the next one: *Het is laat. **Daarom gaat** Lotte meteen slapen.* Do not confuse it with **omdat**: *Lotte gaat slapen, **omdat** het laat **is**.* — the same meaning, the other way round.',
      '**dus** = so, therefore. After dus both orders are heard; the course writes the normal main-clause order after a comma — *De les eindigt om vier uur, **dus** wij **hebben** tijd* — and accepts the inverted one (*dus hebben wij tijd*), which is also correct, above all when dus begins a new sentence: ***Dus hebben** wij tijd.*',
    ],
    tables: [
      { caption: 'Verb to the end', rows: [
        { nl: 'Bram loopt, [hoewel] het [regent].', en: 'although' },
        { nl: '[Hoewel] het regent, [loopt] Bram.', en: 'clause first: verb follows' },
        { nl: 'Zij verdelen het werk, [zodat] elke student een deel [heeft].', en: 'so that' },
      ] },
      { caption: 'Verb straight after', rows: [
        { nl: 'Het is laat. [Daarom gaat] Lotte slapen.', en: 'that is why' },
        { nl: 'De les eindigt om vier uur, [dus] wij [hebben] tijd.', en: 'so (also: dus hebben wij)' },
      ] },
    ],
    examples: [
      { nl: 'Hoewel Tom moe is, gaat hij mee naar het feest.', en: 'Although Tom is tired, he goes to the party too.' },
      { nl: 'Bram neemt een paraplu mee, zodat hij droog blijft.', en: 'Bram takes an umbrella, so that he stays dry.' },
      { nl: 'Bram heeft geen fiets. Daarom loopt hij naar het station.', en: 'Bram has no bike. That’s why he walks to the station.' },
    ],
  },
  {
    type: 'drill', title: 'Join with hoewel, zodat, daarom or dus', grammar: ['hoewel-zodat', 'verb-final', 'v2-inversion', 'want-omdat'],
    instruction: 'Join or rewrite with the word the task gives. hoewel and zodat send the verb to the end; after daarom the verb comes straight away.',
    items: [
      { nl: 'Bram loopt naar het station. Het regent.', task: 'Join with hoewel', answer: 'Bram loopt naar het station, hoewel het regent.' },
      { nl: 'Bram loopt naar het station. Het regent.', task: 'Start with “Hoewel het regent,”', answer: 'Hoewel het regent, loopt Bram naar het station.' },
      { nl: 'Zij verdelen het werk. Elke student heeft een deel.', task: 'Join with zodat', answer: 'Zij verdelen het werk, zodat elke student een deel heeft.' },
      { nl: 'Bram neemt een paraplu mee. Hij blijft droog.', task: 'Join with zodat', answer: 'Bram neemt een paraplu mee, zodat hij droog blijft.' },
      { nl: 'Het is laat. Lotte gaat meteen slapen.', task: 'Start the second sentence with Daarom', answer: 'Het is laat. Daarom gaat Lotte meteen slapen.' },
      { nl: 'Bram heeft geen fiets. Hij loopt naar het station.', task: 'Start the second sentence with Daarom', answer: 'Bram heeft geen fiets. Daarom loopt hij naar het station.' },
      { nl: 'De les eindigt om vier uur. Wij hebben tijd.', task: 'Join with dus', answer: 'De les eindigt om vier uur, dus wij hebben tijd.', accept: ['De les eindigt om vier uur, dus hebben wij tijd.', 'De les eindigt om vier uur, dus we hebben tijd.'] },
      { nl: 'Tom is moe. Hij gaat mee naar het feest.', task: 'Start with “Hoewel Tom moe is,”', answer: 'Hoewel Tom moe is, gaat hij mee naar het feest.' },
      { nl: 'Lotte gaat slapen, omdat het laat is.', task: 'Say the same with Daarom: “Het is laat. Daarom …”', answer: 'Het is laat. Daarom gaat Lotte slapen.' },
      { nl: 'Pieter stuurt een mail. Elke student weet het.', task: 'Join with zodat', answer: 'Pieter stuurt een mail, zodat elke student het weet.' },
    ],
    explanation: 'hoewel het regent, zodat … heeft: verb to the end. Daarom gaat Lotte: the verb straight after daarom. dus: both orders are correct.',
  },
  {
    type: 'drill', title: 'Type the missing word', grammar: ['hoewel-zodat', 'time-conjunctions', 'want-omdat'],
    instruction: 'Type hoewel, zodat, daarom, dus, omdat or maar. The English tells you the meaning.',
    items: [
      { nl: '___ het regent, gaat Bram lopen.', en: 'Although it is raining, Bram goes on foot.', answer: 'Hoewel' },
      { nl: 'Zij werken samen, ___ het sneller gaat.', en: 'They work together, so that it goes faster.', answer: 'zodat' },
      { nl: 'Het is laat. ___ gaat Lotte slapen.', en: 'It is late. That’s why Lotte goes to sleep.', answer: 'Daarom' },
      { nl: 'De deadline is morgen, ___ wij moeten vandaag werken.', en: 'The deadline is tomorrow, so we have to work today.', answer: 'dus' },
      { nl: 'Lotte gaat slapen, ___ het laat is.', en: 'Lotte goes to sleep because it is late.', answer: 'omdat' },
      { nl: 'Het regent, ___ Bram loopt naar het station.', en: 'It is raining, but Bram walks to the station.', answer: 'maar' },
      { nl: 'Tom komt naar het feest, ___ hij moe is.', en: 'Tom comes to the party, although he is tired.', answer: 'hoewel' },
      { nl: 'Bram heeft een paraplu, ___ hij droog blijft.', en: 'Bram has an umbrella, so that he stays dry.', answer: 'zodat' },
    ],
    explanation: 'Verb to the end after hoewel, zodat, omdat. Normal order after maar and dus (dus can also invert). Daarom + verb.',
  },
  {
    type: 'arrange', title: 'Although it rains', grammar: ['hoewel-zodat', 'als-inversion'],
    instruction: 'Build: “Although it is raining, Bram walks to the station.” Two tiles are traps.',
    nl: 'Hoewel het regent, loopt Bram naar het station.', en: 'Although it is raining, Bram walks to the station.', image: 'rain', distractors: ['daarom', 'regenen'],
  },

  // ——— Grammar: of ———
  {
    type: 'grammar', title: 'Ik weet niet of …', grammar: ['of-whether', 'dat-clause', 'verb-final', 'question-word', 'kennen-weten'],
    body: [
      'A question can sit inside a longer sentence: *I don’t know **whether** he is coming.* For a question with a question word you know the pattern from lesson 18: *Ik weet niet **waar** hij woont.* For a **yes/no question** Dutch uses **of** — the same little word as *or*: *Komt hij? → Ik weet niet **of** hij **komt**.*',
      'The verb goes to the end, as in every subordinate clause: *Is het verslag klaar? → Lotte weet niet **of** het verslag klaar **is**. Heeft Pieter de mail gestuurd? → Ik weet niet **of** Pieter de mail **gestuurd heeft**.*',
      'Typical openings: *Ik weet niet of …, Ik vraag me af of …* (I wonder whether — only the beginning of it here: *Ik weet het niet*), ***Weet jij of** …?*, *Lotte vraagt **of** …* (asks whether), *Het hangt ervan af of …*.',
      'Do not mix up **of** and **als**. English *if* covers both; Dutch does not. **als** = if, on condition that (*Als het regent, …*); **of** = whether, after verbs of asking and knowing (*Ik weet niet of het regent*). And **dat** reports a fact, not a question: *Ik weet **dat** hij komt* (I know he is coming) — *Ik weet niet **of** hij komt* (I don’t know whether he is coming).',
    ],
    tables: [
      { caption: 'A yes/no question inside a sentence', rows: [
        { nl: 'Komt Pieter? → Ik weet niet [of] Pieter [komt].', en: 'whether' },
        { nl: 'Is het klaar? → Lotte vraagt [of] het klaar [is].', en: 'asks whether' },
        { nl: 'Weet jij [of] de les om vier uur [eindigt]?', en: 'Do you know whether …?' },
        { nl: 'Ik weet [dat] hij komt. — Ik weet niet [of] hij komt.', en: 'that (a fact) — whether (a question)' },
        { nl: '[Als] het regent, neem ik een paraplu.', en: 'if (a condition): als' },
      ] },
    ],
    examples: [
      { nl: 'Ik weet niet of wij genoeg tijd hebben.', en: 'I don’t know whether we have enough time.' },
      { nl: 'Bram vraagt of Lotte vanavond thuis is.', en: 'Bram asks whether Lotte is at home tonight.' },
      { nl: 'Weet jij of de deadline op vrijdag is?', en: 'Do you know whether the deadline is on Friday?' },
    ],
  },
  {
    type: 'drill', title: 'Put the question inside', grammar: ['of-whether', 'verb-final', 'question-word', 'perfect-hebben', 'separable-together'],
    instruction: 'Put the question inside the sentence the task gives: of for a yes/no question, the question word for the others.',
    items: [
      { nl: 'Komt Pieter vanavond?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet of Pieter vanavond komt.' },
      { nl: 'Is het verslag klaar?', task: 'Start with “Lotte vraagt”', answer: 'Lotte vraagt of het verslag klaar is.' },
      { nl: 'Heeft Ines de mail gestuurd?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet of Ines de mail gestuurd heeft.', accept: ['Ik weet niet of Ines de mail heeft gestuurd.'] },
      { nl: 'Eindigt de les om vier uur?', task: 'Start with “Weet jij”', answer: 'Weet jij of de les om vier uur eindigt?', accept: ['Weet je of de les om vier uur eindigt?'] },
      { nl: 'Hebben wij genoeg tijd?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet of wij genoeg tijd hebben.', accept: ['Ik weet niet of we genoeg tijd hebben.'] },
      { nl: 'Waar spreken wij af?', task: 'Start with “Yasmine vraagt”', answer: 'Yasmine vraagt waar wij afspreken.', accept: ['Yasmine vraagt waar we afspreken.'] },
      { nl: 'Wanneer is de deadline?', task: 'Start with “Weet jij”', answer: 'Weet jij wanneer de deadline is?', accept: ['Weet je wanneer de deadline is?'] },
      { nl: 'Werkt Bram vanavond thuis?', task: 'Start with “Lotte vraagt”', answer: 'Lotte vraagt of Bram vanavond thuis werkt.' },
      { nl: 'Dient de groep het verslag op vrijdag in?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet of de groep het verslag op vrijdag indient.' },
    ],
    explanation: 'of … komt, of … klaar is, of … indient: the verb last, and a separable verb joins up again. A question word stays: waar wij afspreken, wanneer de deadline is.',
  },
  {
    type: 'drill', title: 'of, als or dat?', grammar: ['of-whether', 'als-inversion', 'dat-clause'],
    instruction: 'Type of, als or dat.',
    items: [
      { nl: 'Ik weet niet ___ hij komt.', en: 'I don’t know whether he is coming.', answer: 'of' },
      { nl: 'Ik weet ___ hij komt.', en: 'I know that he is coming.', answer: 'dat' },
      { nl: '___ het regent, neem ik een paraplu.', en: 'If it rains, I take an umbrella.', answer: 'Als' },
      { nl: 'Lotte vraagt ___ Bram thuis is.', en: 'Lotte asks whether Bram is at home.', answer: 'of' },
      { nl: 'Bram zegt ___ hij thuis is.', en: 'Bram says that he is at home.', answer: 'dat' },
      { nl: 'Weet jij ___ de bibliotheek open is?', en: 'Do you know whether the library is open?', answer: 'of' },
      { nl: '___ de bibliotheek open is, werken wij daar.', en: 'If the library is open, we work there.', answer: 'Als' },
      { nl: 'Ik hoop ___ het verslag goed is.', en: 'I hope that the report is good.', answer: 'dat' },
    ],
    explanation: 'of: whether (a yes/no question). als: if (a condition). dat: that (a statement).',
  },

  {
    type: 'drill', title: 'The project week in short', grammar: ['time-conjunctions', 'separable', 'separable-perfect', 'perfect-hebben', 'question-word', 'clock-time', 'days-op-om'],
    instruction: 'Answer each question with a complete sentence, using the information in brackets.',
    items: [
      { nl: 'Wat is de opdracht van de groep? (een project over talen)', answer: 'De opdracht van de groep is een project over talen.', accept: ['De opdracht is een project over talen.'] },
      { nl: 'Is de opdracht moeilijk? (ja, maar leuk)', answer: 'Ja, de opdracht is moeilijk, maar leuk.' },
      { nl: 'Waar hebben de studenten afgesproken? (in de bibliotheek)', answer: 'De studenten hebben in de bibliotheek afgesproken.', accept: ['Zij hebben in de bibliotheek afgesproken.'] },
      { nl: 'Wat doen zij eerst? (zij bespreken het idee)', answer: 'Eerst bespreken zij het idee.', accept: ['Zij bespreken eerst het idee.'] },
      { nl: 'Wat doen zij daarna? (zij verdelen het werk)', answer: 'Daarna verdelen zij het werk.', accept: ['Zij verdelen daarna het werk.'] },
      { nl: 'Hoeveel minuten pauze hebben zij? (tien minuten)', answer: 'Zij hebben tien minuten pauze.' },
      { nl: 'Hoeveel minuten voor de deadline is het verslag klaar? (zestig minuten)', answer: 'Het verslag is zestig minuten voor de deadline klaar.', accept: ['Zestig minuten voor de deadline.'] },
      { nl: 'Heeft Lotte het druk? (ja, heel druk)', answer: 'Ja, Lotte heeft het heel druk.', accept: ['Ja, zij heeft het heel druk.'] },
      { nl: 'Is het druk in de bibliotheek? (ja)', answer: 'Ja, het is druk in de bibliotheek.' },
      { nl: 'Werken de studenten hard? (ja, heel hard)', answer: 'Ja, de studenten werken heel hard.', accept: ['Ja, zij werken heel hard.'] },
      { nl: 'Wat neemt Bram mee in de regen? (een paraplu)', answer: 'Bram neemt een paraplu mee in de regen.', accept: ['In de regen neemt Bram een paraplu mee.'] },
      { nl: 'Houdt Bram van de regen? (nee)', answer: 'Nee, Bram houdt niet van de regen.', accept: ['Nee, hij houdt niet van de regen.'] },
      { nl: 'Hebben zij het verslag uiteindelijk op tijd ingediend? (ja)', answer: 'Ja, uiteindelijk hebben zij het verslag op tijd ingediend.', accept: ['Ja, zij hebben het verslag uiteindelijk op tijd ingediend.'] },
      { nl: 'Was het project uiteindelijk goed? (ja, heel goed)', answer: 'Ja, uiteindelijk was het project heel goed.', accept: ['Ja, het project was uiteindelijk heel goed.'] },
      { nl: 'Sinds wanneer werken zij aan het project? (sinds maandag)', answer: 'Zij werken sinds maandag aan het project.', accept: ['Sinds maandag werken zij aan het project.'] },
    ],
    explanation: 'het druk hebben = to be busy (a person); het is druk = it is busy (a place). sinds maandag: present tense for something that still goes on.',
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', layout: 'table', title: 'Every verb you know', grammar: ['present-regular', 'spelling-stem', 'zijn', 'hebben', 'gaan', 'subject-pronouns', 'dt-rule', 'modals', 'reflexive', 'separable'],
    instruction: 'Verbs from lessons 1–23. The small word under each subject is the verb. Type the present-tense form (for a separable verb, only the first part).',
    items: [
      { label: 'de les', gloss: 'it · eindigen', answer: 'eindigt' },
      { label: 'ik', gloss: 'verdelen', answer: 'verdeel' },
      { label: 'Pieter', gloss: 'he · bespreken', answer: 'bespreekt' },
      { label: 'wij', gloss: 'afspreken', answer: 'spreken' },
      { label: 'Ines', gloss: 'she · indienen', answer: 'dient' },
      { label: 'jij', gloss: 'houden', answer: 'houdt' },
      { label: 'Tom', gloss: 'he · zorgen', answer: 'zorgt' },
      { label: 'ik', gloss: 'betalen', answer: 'betaal' },
      { label: 'het boek', gloss: 'it · liggen', answer: 'ligt' },
      { label: 'Emma', gloss: 'she · sturen', answer: 'stuurt' },
      { label: 'hij', gloss: 'weten', answer: 'weet' },
      { label: 'jij', gloss: 'vinden', answer: 'vindt' },
      { label: 'Lotte', gloss: 'she · zich interesseren', answer: 'interesseert' },
      { label: 'ik', gloss: 'zich haasten', answer: 'haast' },
    ],
    explanation: 'verdeel: ver-de-len, long e. wij spreken … af, Ines dient … in: separable verbs split in a main clause.',
  },
  {
    type: 'drill', title: 'Time words with every verb form', grammar: ['time-conjunctions', 'hoewel-zodat', 'perfect-hebben', 'perfect-zijn', 'modals', 'infinitive-end', 'zullen-future', 'imperfect-weak', 'imperfect-strong', 'separable', 'separable-together', 'separable-perfect', 'verb-preposition', 'participle-no-ge'],
    instruction: 'Rewrite as the task says.',
    items: [
      { nl: 'Zij spreken af in de bibliotheek.', task: 'Use the perfect', answer: 'Zij hebben in de bibliotheek afgesproken.', accept: ['Zij hebben afgesproken in de bibliotheek.'] },
      { nl: 'Zij verdelen het werk.', task: 'Use the perfect', answer: 'Zij hebben het werk verdeeld.' },
      { nl: 'De groep dient het verslag in.', task: 'Use the perfect', answer: 'De groep heeft het verslag ingediend.' },
      { nl: 'Het feest eindigt om twee uur.', task: 'Use the perfect (with zijn)', answer: 'Het feest is om twee uur geëindigd.' },
      { nl: 'Wij werken samen.', task: 'Start with “Wij moeten”', answer: 'Wij moeten samenwerken.' },
      { nl: 'Terwijl Lotte studeert, kookt Bram.', task: 'Use the simple past', answer: 'Terwijl Lotte studeerde, kookte Bram.' },
      { nl: 'Zodra het klaar is, bel ik je.', task: 'Use zullen in the main clause', answer: 'Zodra het klaar is, zal ik je bellen.' },
      { nl: 'Hoewel het regent, loopt Bram naar het station.', task: 'Use the simple past', answer: 'Hoewel het regende, liep Bram naar het station.' },
      { nl: 'Voordat zij beginnen, bespreken zij het idee.', task: 'Use the simple past', answer: 'Voordat zij begonnen, bespraken zij het idee.' },
      { nl: 'Pieter wacht op een mail van Ines.', task: 'Use the perfect, with lang', answer: 'Pieter heeft lang op een mail van Ines gewacht.' },
    ],
    explanation: 'afgesproken, ingediend: ge- in the middle. verdeeld: ver-, no ge-. geëindigd with zijn and two dots. liep, begonnen, bespraken: strong pasts.',
  },
  {
    type: 'drill', title: 'Everything so far', grammar: ['plural', 'adjective-e', 'comparative', 'superlative', 'dan-als', 'object-pronouns', 'indirect-object', 'van-voor-bij', 'position-verbs', 'place-prepositions', 'er-daar-place', 'numbers-big', 'dates', 'er-quantity', 'verb-preposition', 'er-preposition', 'waar-preposition', 'possessives', 'geen-niet'],
    instruction: 'Type the missing word. Grammar from the whole book, now about the project.',
    items: [
      { nl: 'De vier ___ werken samen.', cue: 'student', answer: 'studenten' },
      { nl: 'Zij hebben veel ___.', cue: 'idee', answer: 'ideeën' },
      { nl: 'Het is een ___ verslag.', cue: 'goed', answer: 'goed' },
      { nl: 'Het ___ deel is van Lotte.', cue: 'lang', answer: 'lange' },
      { nl: 'Het deel van Pieter is ___ dan het deel van Ines.', cue: 'kort', answer: 'korter' },
      { nl: 'Lotte stuurt ___ een mail.', en: 'Lotte sends them an e-mail.', answer: 'ze', accept: ['hun'] },
      { nl: 'Het verslag ___ op het bureau.', cue: 'liggen', answer: 'ligt' },
      { nl: 'De deadline is op de ___ december.', en: 'the third of December', answer: 'derde' },
      { nl: 'Hoeveel delen zijn er? Er zijn ___ vier.', answer: 'er' },
      { nl: 'Lotte denkt ___ de deadline.', answer: 'aan' },
      { nl: 'De deadline? Lotte denkt ___ elke dag aan.', answer: 'er' },
      { nl: '___ wacht je op? — Op een mail van Pieter.', answer: 'Waar' },
    ],
    explanation: 'een goed verslag (een + het-word); het lange deel; korter dan. ze or hun for “them” as receivers. er aan, waar … op: the forms of lesson 22.',
  },
  {
    type: 'arrange', title: 'As soon as it is finished', grammar: ['time-conjunctions', 'als-inversion'],
    instruction: 'Build: “As soon as the report is finished, we celebrate.” Two tiles are traps.',
    nl: 'Zodra het verslag klaar is, vieren wij het.', en: 'As soon as the report is finished, we celebrate.', image: 'night-out', distractors: ['wij', 'zodat'],
  },

  {
    type: 'drill', title: 'Who does what while …?', grammar: ['verb-preposition', 'time-conjunctions', 'reflexive', 'er-preposition'],
    instruction: 'Answer each question with a complete sentence.',
    items: [
      { nl: 'Voor wie zorgt Tom in het ziekenhuis?', answer: 'Tom zorgt voor de patiënten.', accept: ['Hij zorgt voor de patiënten.'] },
      { nl: 'Wie zorgt voor het eten, terwijl Lotte studeert?', answer: 'Bram zorgt voor het eten, terwijl Lotte studeert.', accept: ['Bram zorgt voor het eten.'] },
      { nl: 'Wie zorgt voor Max, terwijl Bram werkt?', answer: 'Lotte zorgt voor Max, terwijl Bram werkt.', accept: ['Lotte zorgt voor Max.'] },
      { nl: 'Waar luistert Lotte naar, terwijl zij schrijft? (muziek)', answer: 'Lotte luistert naar muziek, terwijl zij schrijft.', accept: ['Zij luistert naar muziek, terwijl zij schrijft.'] },
      { nl: 'Houdt Tom van muziek?', answer: 'Ja, Tom houdt van muziek.', accept: ['Ja, hij houdt van muziek.'] },
      { nl: 'Interesseert Pieter zich voor talen? (nee, voor sport)', answer: 'Nee, Pieter interesseert zich voor sport.', accept: ['Nee, hij interesseert zich voor sport.'] },
      { nl: 'Kijkt Bram naar sport op televisie, terwijl Lotte studeert?', answer: 'Ja, Bram kijkt naar sport op televisie, terwijl Lotte studeert.', accept: ['Ja, hij kijkt naar sport op televisie, terwijl Lotte studeert.'] },
      { nl: 'Is er een televisie in het appartement van Tom?', answer: 'Ja, er is een televisie in het appartement van Tom.', accept: ['Ja, er is een televisie in zijn appartement.'] },
      { nl: 'Is Noor bang voor Max?', answer: 'Nee, Noor is niet bang voor Max.', accept: ['Nee, zij is niet bang voor Max.', 'Nee, zij is niet bang voor hem.'] },
      { nl: 'Waar is Noor bang voor?', answer: 'Noor is bang voor grote honden.', accept: ['Zij is bang voor grote honden.'] },
      { nl: 'Hoeveel patiënten heeft Tom in het ziekenhuis? (twintig)', answer: 'Tom heeft twintig patiënten in het ziekenhuis.', accept: ['Hij heeft twintig patiënten in het ziekenhuis.', 'Tom heeft er twintig.'] },
      { nl: 'Gaat Tom naar het ziekenhuis, zodra zijn dienst begint?', answer: 'Ja, Tom gaat naar het ziekenhuis, zodra zijn dienst begint.', accept: ['Ja, hij gaat naar het ziekenhuis, zodra zijn dienst begint.'] },
      { nl: 'Praten de patiënten graag met Tom?', answer: 'Ja, de patiënten praten graag met Tom.', accept: ['Ja, zij praten graag met hem.'] },
      { nl: 'Kijkt Max naar de televisie?', answer: 'Nee, Max kijkt niet naar de televisie.', accept: ['Nee, hij kijkt niet naar de televisie.'] },
    ],
  },
  ...recallPages(["boom", "bank", "man", "vrouw", "kind", "deur", "raam", "auto", "straat", "groot", "klein", "oud", "jong", "blij", "ziek", "mooi", "nieuw", "lief", "zitten", "spelen", "leren", "praten", "hond", "kat", "tas", "sleutel", "telefoon", "jas", "bed", "lezen", "thee", "water", "brood", "kaas", "appel", "park", "winkel", "school", "stad", "trein", "kamer", "tafel", "stoel", "tuin", "vader", "moeder", "broer", "zus", "vriend", "vriendin", "familie", "naam", "jaar", "kunnen", "willen", "mogen", "zwemmen", "rijden", "Nederlands", "dinsdag", "zaterdag", "zondag", "vinden", "zeggen", "hopen", "uitgaan", "kort", "haasten", "zullen", "krijgen", "betalen", "gisteren", "vorige", "weekend", "maken", "kopen", "zien", "film", "begrijpen", "examen", "staan", "opstaan", "opbellen", "meenemen", "aankomen", "vroeg", "ontbijt", "duur", "goedkoop", "langzaam", "warm", "koud", "makkelijk", "toen", "vroeger", "geleden", "vakantie", "zee", "strand", "reizen", "foto", "oma", "opa", "voelen", "herinneren", "hoofd", "buik", "rug", "pijn", "dokter", "apotheek", "medicijn", "volgende", "zomer", "winter", "reis", "vliegen", "vliegtuig", "hotel", "proberen", "buurman", "buurvrouw", "collega", "universiteit", "leraar", "antwoord", "kennen", "ontmoeten", "verrassen", "wensen", "cadeau", "verjaardag", "bloem", "taart", "kaart", "leggen", "zetten", "hangen", "kast", "lamp", "muur", "vloer", "doos", "verhuizen", "huren", "zoeken", "verdienen", "sparen", "lenen", "geld", "bedrag", "rekening", "eigenaar"]),
  ...listenPages(["gisteren", "vorige", "weekend", "maken", "kopen", "zien", "film", "begrijpen", "examen", "staan", "opstaan", "opbellen", "meenemen", "aankomen", "vroeg", "ontbijt", "duur", "goedkoop", "langzaam", "warm", "koud", "makkelijk", "toen", "vroeger", "geleden", "vakantie", "zee", "strand", "reizen", "foto", "oma", "opa", "voelen", "herinneren", "hoofd", "buik", "rug", "pijn", "dokter", "apotheek", "medicijn", "volgende", "zomer", "winter", "reis", "vliegen", "vliegtuig", "hotel", "proberen", "buurman", "buurvrouw", "collega", "universiteit", "leraar", "antwoord", "kennen", "ontmoeten", "verrassen", "wensen", "cadeau", "verjaardag", "bloem", "taart", "kaart", "leggen", "zetten", "hangen", "kast", "lamp", "muur", "vloer", "doos", "verhuizen", "huren", "zoeken", "verdienen", "sparen", "lenen", "geld", "bedrag", "rekening", "eigenaar"]),

  {
    type: 'drill', title: 'Grammar from the whole book (1)', grammar: ['dit-is', 'geen', 'niet', 'hij-het-things', 'spelling-z-s', 'adverb-position', 'time-place', 'er-is-zijn', 'numbers', 'wie-hoe', 'participle', 'comparative', 'superlative', 'dan-als', 'imperfect-weak', 'imperfect-strong', 'toen-past', 'imperative', 'pijn-hebben', 'te-infinitive', 'over-geleden', 'relative-clause'],
    instruction: 'A mixed round of grammar from every volume, all about the project week. Type the missing word.',
    items: [
      { nl: '___ is het verslag van de groep.', en: 'This is the group’s report.', answer: 'Dit' },
      { nl: 'Pieter heeft ___ laptop.', en: 'Pieter has no laptop.', answer: 'geen' },
      { nl: 'Het verslag is nog ___ klaar.', en: 'The report isn’t ready yet.', answer: 'niet' },
      { nl: 'De laptop van Ines? ___ is kapot.', en: 'Ines’s laptop? It’s broken.', answer: 'Hij' },
      { nl: 'Lotte ___ elke avond een boek.', cue: 'lezen', answer: 'leest' },
      { nl: 'Lotte werkt ___ hard.', en: 'Lotte always works hard.', answer: 'altijd' },
      { nl: 'Zij werken elke avond ___ de bibliotheek.', en: 'They work in the library every evening.', answer: 'in' },
      { nl: 'Er ___ vier studenten in de groep.', cue: 'er is / er zijn', answer: 'zijn' },
      { nl: 'De groep heeft ___ dagen tot de deadline.', en: 'four', answer: 'vier' },
      { nl: '___ heet de leraar?', en: 'What is the teacher called?', answer: 'Hoe' },
      { nl: 'Zij hebben het idee ___.', cue: 'bespreken', answer: 'besproken' },
      { nl: 'Het deel van Lotte is ___ dan het deel van Pieter.', cue: 'lang', answer: 'langer' },
      { nl: 'Het deel van Lotte is het ___.', cue: 'lang', answer: 'langst', accept: ['langste'] },
      { nl: 'Vroeger ___ Lotte veel.', cue: 'reizen', en: 'Lotte used to travel a lot.', answer: 'reisde' },
      { nl: 'Gisteren ___ Lotte tot één uur.', cue: 'blijven', en: 'Yesterday Lotte stayed until one o’clock.', answer: 'bleef' },
      { nl: 'Toen Lotte klein ___, las zij veel.', cue: 'zijn', en: 'When Lotte was little, she read a lot.', answer: 'was' },
      { nl: '___ het verslag op tijd in!', cue: 'indienen', en: 'Hand in the report on time!', answer: 'Dien' },
      { nl: 'Lotte heeft ___ in haar hoofd.', en: 'Lotte has a headache.', answer: 'pijn' },
      { nl: 'Zij probeert het verslag op tijd klaar ___ maken.', en: 'She tries to finish the report in time.', answer: 'te' },
      { nl: 'Twee dagen ___ heeft Pieter een mail gestuurd.', en: 'Two days ago Pieter sent an e-mail.', answer: 'geleden' },
      { nl: 'Het verslag ___ zij schrijven, gaat over talen.', en: 'The report that they are writing is about languages.', answer: 'dat' },
    ],
    explanation: 'Grammar from the whole book: dit is, geen and niet, hij for a masculine thing, lezen → leest, altijd after the verb, er zijn, Hoe heet …?, besproken, langer and het langst, reisde and bleef, Dien … in!, pijn in, te + infinitive, geleden, het verslag dat ….',
  },
  {
    type: 'drill', title: 'Grammar from the whole book (2)', grammar: ['participle', 'participle-no-ge', 'imperative', 'pijn-hebben', 'te-infinitive', 'over-geleden', 'relative-clause', 'zullen-future', 'object-pronouns', 'indirect-object', 'position-verbs', 'place-prepositions', 'er-daar-place', 'numbers-big', 'dates', 'er-quantity', 'waar-preposition'],
    instruction: 'A second mixed round. Type the missing word.',
    items: [
      { nl: 'Ines heeft het verslag ___.', cue: 'schrijven', answer: 'geschreven' },
      { nl: 'Zij hebben het werk ___.', cue: 'verdelen', answer: 'verdeeld' },
      { nl: '___ niet te laat naar bed!', cue: 'gaan', en: 'Don’t go to bed too late!', answer: 'Ga' },
      { nl: 'Pieter heeft pijn in zijn ___.', en: 'Pieter has backache.', answer: 'rug' },
      { nl: 'Bram vergeet niet een paraplu mee ___ nemen.', en: 'Bram doesn’t forget to take an umbrella.', answer: 'te' },
      { nl: '___ twee dagen is de deadline.', en: 'In two days it’s the deadline.', answer: 'Over' },
      { nl: 'De student ___ het lange deel schrijft, is Lotte.', en: 'The student who writes the long part is Lotte.', answer: 'die' },
      { nl: 'Ik ___ je morgen bellen.', cue: 'zullen', answer: 'zal' },
      { nl: 'Lotte stuurt ___ het verslag.', en: 'Lotte sends him the report.', answer: 'hem' },
      { nl: 'Pieter geeft ___ een kop koffie.', en: 'Pieter gives her a cup of coffee.', answer: 'haar' },
      { nl: 'Het verslag ___ op het bureau.', cue: 'liggen', answer: 'ligt' },
      { nl: 'De laptop staat ___ het verslag en de boeken.', en: 'between', answer: 'tussen' },
      { nl: 'De bibliotheek? Zij werken ___ elke avond.', en: 'They work there every evening.', answer: 'er' },
      { nl: 'Het boek voor de cursus kost ___ euro.', en: 'twenty-five (in words)', answer: 'vijfentwintig' },
      { nl: 'Het feest is op de ___ december.', en: 'first', answer: 'eerste' },
      { nl: 'Hoeveel studenten zijn er? Er zijn ___ vier.', answer: 'er' },
      { nl: '___ werken zij aan? — Aan het verslag.', en: 'What are they working on?', answer: 'Waar' },
    ],
    explanation: 'geschreven (strong), verdeeld (ver-: no ge-). Ga …! Over twee dagen: future; geleden: past. de student die …. hem, haar for people. er = there; er vier; Waar … aan?',
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'De deadline', image: 'students-group', grammar: ['time-conjunctions', 'hoewel-zodat', 'of-whether', 'separable', 'perfect-hebben', 'verb-preposition', 'er-preposition'],
    instruction: 'One busy week, from the first meeting to the party. Read and listen to every line, then read it again without the English. Find every word that joins two sentences.',
    lines: [
      { nl: 'Op maandag spreken Lotte, Ines, Pieter en Yasmine af in de bibliotheek.', en: 'On Monday Lotte, Ines, Pieter and Yasmine meet in the library.', image: 'students-group' },
      { speaker: 'Pieter', nl: 'De deadline is vrijdag om vijf uur. Wij hebben weinig tijd!', en: 'The deadline is Friday at five. We have little time!', image: 'clock' },
      { speaker: 'Ines', nl: 'Dan moeten wij het werk meteen verdelen, zodat elke student weet wat hij moet doen.', en: 'Then we must divide the work straight away, so that everyone knows what to do.', image: 'students' },
      { nl: 'Eerst bespreken zij het idee: het project gaat over de talen van de studenten in Leuven.', en: 'First they discuss the idea: the project is about the languages of the students in Leuven.', image: 'university' },
      { nl: 'Daarna krijgt elke student een deel. Lotte schrijft het lange deel, want zij interesseert zich voor talen.', en: 'After that everyone gets a part. Lotte writes the long part, because she is interested in languages.', image: 'woman-studying' },
      { nl: 'Sinds maandag werkt Lotte elke avond aan het verslag. Terwijl zij schrijft, kookt Bram.', en: 'Since Monday Lotte has worked on the report every evening. While she writes, Bram cooks.', image: 'man-cooking' },
      { speaker: 'Bram', nl: 'Het eten is klaar! Kom je eten, of werk je nog?', en: 'Dinner is ready! Are you coming to eat, or are you still working?', image: 'man-cooking' },
      { speaker: 'Lotte', nl: 'Ik kom, zodra ik klaar ben met mijn zin.', en: 'I’m coming as soon as I’ve finished my sentence.', image: 'woman-studying' },
      { nl: 'Op woensdag regent het. Hoewel het regent, loopt Bram naar het station. Hij heeft nog altijd geen fiets.', en: 'On Wednesday it rains. Although it is raining, Bram walks to the station. He still has no bike.', image: 'rain' },
      { nl: 'Hij neemt een paraplu mee, zodat hij droog blijft.', en: 'He takes an umbrella, so that he stays dry.', image: 'rain' },
      { nl: 'Op donderdag stuurt Pieter een mail: Zijn jullie allemaal klaar? Ik weet niet of wij het halen.', en: 'On Thursday Pieter sends an e-mail: Are you all finished? I don’t know whether we will make it.', image: 'phone' },
      { nl: 'Dus werken zij die avond samen, totdat het verslag klaar is.', en: 'So that evening they work together until the report is finished.', image: 'students-group' },
      { nl: 'Het is één uur in de nacht, voordat Lotte thuiskomt. Daarom gaat zij meteen slapen.', en: 'It is one o’clock at night before Lotte comes home. That’s why she goes to sleep straight away.', image: 'woman-sleeping' },
      { nl: 'Op vrijdag dienen zij het verslag om vier uur in: een uur voor de deadline.', en: 'On Friday they hand in the report at four: an hour before the deadline.', image: 'university' },
      { speaker: 'Yasmine', nl: 'Zodra de les eindigt, gaan wij het vieren!', en: 'As soon as the lesson ends, we’re going to celebrate!', image: 'classroom' },
      { nl: 'Nadat de les geëindigd is, gaan de vier studenten met Bram, Emma en Jonas naar een café.', en: 'After the lesson has ended, the four students go to a café with Bram, Emma and Jonas.', image: 'night-out' },
      { speaker: 'Lotte', nl: 'Wat een week! Maar wij hebben goed samengewerkt.', en: 'What a week! But we worked well together.', image: 'friends' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'inversion', 'time-conjunctions'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the story. Answer without looking back.',
    items: [
      { nl: 'Spreken de studenten op maandag af?', answer: 'Ja' },
      { nl: 'Is de deadline op donderdag?', answer: 'Nee' },
      { nl: 'Schrijft Lotte het lange deel?', answer: 'Ja' },
      { nl: 'Heeft Bram een fiets?', answer: 'Nee' },
      { nl: 'Dienen zij het verslag te laat in?', answer: 'Nee' },
      { nl: 'Gaan zij na de les naar een café?', answer: 'Ja' },
    ],
  },
  {
    type: 'drill', title: 'Answer in full', grammar: ['time-conjunctions', 'hoewel-zodat', 'of-whether', 'want-omdat', 'verb-final', 'question-word'],
    instruction: 'Answer each question about the story with a complete sentence. Use the joining word the task gives.',
    items: [
      { nl: 'Wanneer is de deadline?', answer: 'De deadline is vrijdag om vijf uur.', accept: ['De deadline is op vrijdag om vijf uur.', 'Vrijdag om vijf uur.'] },
      { nl: 'Waarom verdelen zij het werk?', task: 'Answer with zodat', answer: 'Zij verdelen het werk, zodat elke student weet wat hij moet doen.', accept: ['Zodat elke student weet wat hij moet doen.'] },
      { nl: 'Waarom schrijft Lotte het lange deel?', task: 'Answer with omdat', answer: 'Lotte schrijft het lange deel, omdat zij zich voor talen interesseert.', accept: ['Omdat zij zich voor talen interesseert.', 'Lotte schrijft het lange deel, omdat ze zich voor talen interesseert.'] },
      { nl: 'Wat doet Bram, terwijl Lotte schrijft?', answer: 'Terwijl Lotte schrijft, kookt Bram.', accept: ['Bram kookt, terwijl Lotte schrijft.', 'Bram kookt.'] },
      { nl: 'Loopt Bram naar het station, hoewel het regent?', answer: 'Ja, hoewel het regent, loopt Bram naar het station.', accept: ['Ja, Bram loopt naar het station, hoewel het regent.'] },
      { nl: 'Waarom neemt Bram een paraplu mee?', task: 'Answer with zodat', answer: 'Bram neemt een paraplu mee, zodat hij droog blijft.', accept: ['Zodat hij droog blijft.'] },
      { nl: 'Wat weet Pieter niet?', answer: 'Pieter weet niet of zij het halen.', accept: ['Hij weet niet of zij het halen.', 'Pieter weet niet of ze het halen.'] },
      { nl: 'Hoe laat dienen zij het verslag in?', answer: 'Zij dienen het verslag om vier uur in.', accept: ['Zij dienen het om vier uur in.', 'Om vier uur.'] },
      { nl: 'Wat doen zij, nadat de les geëindigd is?', answer: 'Nadat de les geëindigd is, gaan zij naar een café.', accept: ['Zij gaan naar een café.'] },
    ],
  },
  {
    type: 'drill', title: 'Ask and answer about the week', grammar: ['time-conjunctions', 'of-whether', 'dat-clause', 'kennen-weten', 'verb-preposition', 'reflexive', 'perfect-zijn', 'separable-perfect'],
    instruction: 'Answer each question with a complete sentence. Some ask about the story, some about Lotte, Bram and their friends in earlier lessons.',
    items: [
      { nl: 'Met hoeveel studenten doet Lotte het project?', answer: 'Lotte doet het project met drie andere studenten.', accept: ['Zij doet het project met drie andere studenten.', 'Met drie andere studenten.'] },
      { nl: 'Hoe heten de andere studenten?', answer: 'Zij heten Ines, Pieter en Yasmine.', accept: ['De andere studenten heten Ines, Pieter en Yasmine.'] },
      { nl: 'Waar gaat het project over?', answer: 'Het project gaat over de talen van de studenten in Leuven.', accept: ['Het gaat over de talen van de studenten in Leuven.', 'Over de talen van de studenten in Leuven.', 'Het project gaat over talen.'] },
      { nl: 'Wat doen de studenten tijdens de pauze?', answer: 'Tijdens de pauze drinken de studenten koffie.', accept: ['Zij drinken koffie.', 'Tijdens de pauze drinken zij koffie.'] },
      { nl: 'Helpen de studenten elkaar?', answer: 'Ja, de studenten helpen elkaar.', accept: ['Ja, zij helpen elkaar.'] },
      { nl: 'Is Lotte op tijd thuisgekomen?', answer: 'Nee, Lotte is om één uur in de nacht thuisgekomen.', accept: ['Nee, zij is om één uur in de nacht thuisgekomen.', 'Nee, zij is laat thuisgekomen.'] },
      { nl: 'Weet Bram of Lotte vanavond thuis eet?', answer: 'Nee, Bram weet niet of Lotte vanavond thuis eet.', accept: ['Nee, hij weet niet of Lotte vanavond thuis eet.', 'Nee, hij weet het niet.'] },
      { nl: 'Heeft de groep goed samengewerkt?', answer: 'Ja, de groep heeft goed samengewerkt.', accept: ['Ja, zij hebben goed samengewerkt.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['time-conjunctions', 'hoewel-zodat', 'of-whether'],
    instruction: 'Listen to each sentence and write it. Capitals and punctuation do not matter.',
    items: [
      { listen: 'Terwijl Lotte studeert, kookt Bram.' },
      { listen: 'Voordat de les begint, drinken wij koffie.' },
      { listen: 'Zodra het klaar is, bel ik je.' },
      { listen: 'Hoewel het regent, loopt hij naar het station.' },
      { listen: 'Zij verdelen het werk, zodat elke student een deel heeft.' },
      { listen: 'Het is laat. Daarom gaat Lotte slapen.' },
      { listen: 'Ik weet niet of hij komt.' },
      { listen: 'Sinds maandag regent het.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['time-conjunctions', 'hoewel-zodat', 'of-whether', 'als-inversion', 'verb-final', 'perfect-hebben', 'separable'],
    instruction: 'Translate. “You” is one person.',
    items: [
      { en: 'While Lotte writes, Bram cooks.', answer: 'Terwijl Lotte schrijft, kookt Bram.' },
      { en: 'Before the lesson starts, we drink coffee.', answer: 'Voordat de les begint, drinken wij koffie.', accept: ['Voordat de les begint, drinken we koffie.'] },
      { en: 'After they have eaten, they go out.', answer: 'Nadat zij gegeten hebben, gaan zij uit.', accept: ['Nadat zij hebben gegeten, gaan zij uit.', 'Nadat ze gegeten hebben, gaan ze uit.'] },
      { en: 'As soon as the report is finished, I’ll ring you.', answer: 'Zodra het verslag klaar is, bel ik je.', accept: ['Zodra het verslag klaar is, bel ik jou.', 'Zodra het verslag klaar is, zal ik je bellen.'] },
      { en: 'Although it is raining, Bram walks to the station.', answer: 'Hoewel het regent, loopt Bram naar het station.' },
      { en: 'They divide the work, so that everyone has a part.', answer: 'Zij verdelen het werk, zodat elke student een deel heeft.' },
      { en: 'Bram has no bike. That is why he walks.', answer: 'Bram heeft geen fiets. Daarom loopt hij.' },
      { en: 'I don’t know whether we have enough time.', answer: 'Ik weet niet of wij genoeg tijd hebben.', accept: ['Ik weet niet of we genoeg tijd hebben.'] },
      { en: 'Tom has lived in Leuven since November.', answer: 'Tom woont sinds november in Leuven.', accept: ['Sinds november woont Tom in Leuven.', 'Tom woont in Leuven sinds november.'] },
      { en: 'The lesson ends at four, so we have time.', answer: 'De les eindigt om vier uur, dus wij hebben tijd.', accept: ['De les eindigt om vier uur, dus hebben wij tijd.', 'De les eindigt om vier uur, dus we hebben tijd.'] },
    ],
    explanation: 'Tom woont sinds november in Leuven: a present tense for something that still continues.',
  },
  {
    type: 'drill', title: 'The whole lesson in one round', grammar: ['time-conjunctions', 'hoewel-zodat', 'of-whether', 'verb-final'],
    instruction: 'A final round: every point of this lesson, mixed. Type every answer.',
    items: [
      { nl: '___ Lotte studeert, kookt Bram.', en: 'While', answer: 'Terwijl' },
      { nl: '___ de les begint, drinken wij koffie.', en: 'Before', answer: 'Voordat' },
      { nl: '___ het verslag klaar is, vieren wij het.', en: 'As soon as', answer: 'Zodra' },
      { nl: '___ het regent, gaat Bram lopen.', en: 'Although', answer: 'Hoewel' },
      { nl: 'Zij werken samen, ___ het sneller gaat.', en: 'so that', answer: 'zodat' },
      { nl: 'Ik weet niet ___ hij komt.', en: 'whether', answer: 'of' },
      { nl: 'De les ___ om vier uur.', cue: 'eindigen', answer: 'eindigt' },
      { nl: 'Het is laat. Lotte gaat slapen.', task: 'Start the second sentence with Daarom', answer: 'Het is laat. Daarom gaat Lotte slapen.' },
      { nl: 'Komt Ines?', task: 'Start with “Ik weet niet”', answer: 'Ik weet niet of Ines komt.' },
      { en: 'during the break', answer: 'tijdens de pauze' },
      { listen: 'Nadat de les geëindigd is, gaan wij naar een café.' },
    ],
  },
  {
    type: 'complete', title: 'Op tijd klaar',
    instruction: 'terwijl, voordat, nadat, zodra, sinds, totdat; hoewel and zodat against dus and daarom; and Ik weet niet of …. You can tell what happens when, in spite of what, and so that — in Dutch.',
  },
];
