/**
 * Lesson 24 — Naar de markt om groenten te kopen.
 * Targets: markt, groente, fruit, vlees, vis, ei, soep, recept, hoeven, snijden.
 * Structure: deze, welk (welke), zonder. Extra vocabulary (vocabulary/om-te.js): kilo, stuk, tomaat,
 * aardappel, ui, wortel, prei, zout, peper, kraam, vers, lekker, proeven, bakken, pan, mes, boodschap,
 * verkoper, minuut, vanavond, genoeg, gezond, honger, vallen, voorzichtig, smakelijk — and the forms
 * “halve” (een halve kilo) and “groentesoep”.
 * Grammar: om … te for a purpose (and zonder … te) · niet hoeven te · deze, die, dit, dat, welk(e).
 * The capstone of volume three: object pronouns, place, numbers and prices, verbs with a preposition
 * and the conjunctions of lessons 19–23 return inside the new grammar.
 * Story: a Saturday in spring. Lotte's project (lesson 23) is finished. Bram and Lotte go to the market
 * in Leuven for vegetables, fruit, fish and eggs; which tomatoes, these or those; the fish comes from
 * Oostende, where Bram grew up (lesson 15). In the evening Bram cooks his mother's vegetable soup for
 * Tom, Emma and Jonas; Lotte cuts the vegetables — carefully, because Max is waiting under the table.
 * Emma eats no meat, so the soup is without meat.
 * Teaching choices: hoeven is taught only with niet, geen, nooit and maar (“iets / niets” arrive in
 * lesson 25, so “you don’t have to bring anything” is “geen eten”); “Dat had niet gehoeven” is taught
 * as a fixed phrase. After “het is + adjective” both “om … te” and plain “te” are accepted. In a
 * subordinate clause the course writes “niet hoeft te koken” and accepts “niet te koken hoeft”.
 * de soep is traditionally feminine, so it is “ze” (as in Flanders).
 */
export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Saturday: market day', grammar: ['om-te', 'hoeven-te', 'demonstratives', 'v2-inversion', 'er-is-zijn'],
    instruction: 'Look and listen. Say every sentence out loud after the voice — twice. Listen for three new things: “om … te”, “hoeven”, and “deze”.',
    cards: [
      { nl: 'Op zaterdag is er markt in Leuven.', en: 'On Saturday there is a market in Leuven.', image: 'market' },
      { nl: 'Bram en Lotte gaan naar de markt om groenten en fruit te kopen.', en: 'Bram and Lotte go to the market to buy vegetables and fruit.', image: 'market' },
      { nl: 'Op de markt koop je groenten, fruit, vlees, vis en eieren.', en: 'At the market you buy vegetables, fruit, meat, fish and eggs.', image: 'market' },
      { nl: 'Deze groenten zijn vers: tomaten, wortels en prei.', en: 'These vegetables are fresh: tomatoes, carrots and leeks.', image: 'vegetables' },
      { nl: 'Welke vis is het lekkerst? Deze of die?', en: 'Which fish is the tastiest? This one or that one?', image: 'fish' },
      { nl: 'Lotte koopt zes eieren voor het ontbijt.', en: 'Lotte buys six eggs for breakfast.', image: 'woman-buying' },
      { nl: 'Vanavond maakt Bram soep voor Tom, Emma en Jonas.', en: 'Tonight Bram is making soup for Tom, Emma and Jonas.', image: 'soup' },
      { nl: 'Het recept is van zijn moeder.', en: 'The recipe is his mother’s.', image: 'mother' },
      { nl: 'Bram snijdt de groenten met een groot mes.', en: 'Bram cuts the vegetables with a big knife.', image: 'man-cutting' },
      { nl: 'Emma eet geen vlees. Deze soep is zonder vlees.', en: 'Emma doesn’t eat meat. This soup is without meat.', image: 'soup' },
      { nl: 'Jullie hoeven niet te koken. Bram kookt!', en: 'You don’t have to cook. Bram is cooking!', image: 'man-cooking' },
    ],
    note: 'New: de markt, de markten (market) · de groente, de groenten (vegetable — mostly used in the plural; groentes is heard too) · het fruit (fruit — no plural: veel fruit) · het vlees (meat) · de vis, de vissen (fish) · het ei, de eieren (egg — an irregular plural) · de soep (soup) · het recept, de recepten (recipe — and a doctor’s prescription) · hoeven (niet hoeven te: not to have to) · snijden (to cut) · deze (this, these) · welk, welke (which) · zonder (without). “om … te” = in order to — the first grammar page.',
  },
  {
    type: 'observe', title: 'At the stall', grammar: ['demonstratives', 'er-quantity', 'numbers-big', 'comparative'],
    instruction: 'Buying at a market stall. Listen to how the seller asks, and how Lotte answers with “graag”.',
    cards: [
      { nl: 'Het kraam van de verkoopster is groot. Er liggen groenten en fruit.', en: 'The seller’s stall is big. There are vegetables and fruit on it.', image: 'market' },
      { nl: 'De verkoopster vraagt: “Wat mag het zijn?”', en: 'The seller asks: “What can I get you?”', image: 'market' },
      { nl: 'Twee kilo aardappelen en een halve kilo tomaten, graag.', en: 'Two kilos of potatoes and half a kilo of tomatoes, please.', image: 'vegetables' },
      { nl: 'Een kilo tomaten kost drie euro vijftig.', en: 'A kilo of tomatoes costs three euros fifty.', image: 'money' },
      { nl: 'Deze tomaten komen uit België, die komen uit Spanje.', en: 'These tomatoes come from Belgium, those come from Spain.', image: 'vegetables' },
      { nl: 'Die uit Spanje zijn goedkoper, maar deze zijn lekkerder.', en: 'The ones from Spain are cheaper, but these are tastier.', image: 'vegetables' },
      { nl: 'De verkoopster zegt: “Proef maar!”', en: 'The seller says: “Go on, taste one!”', image: 'market' },
      { nl: 'Hoeveel uien heb je nodig? — Ik heb er drie nodig.', en: 'How many onions do you need? — I need three.', image: 'vegetables' },
      { nl: 'Bram en Lotte doen elke zaterdag boodschappen.', en: 'Bram and Lotte do the shopping every Saturday.', image: 'woman-buying' },
      { nl: 'De verkoper heeft verse vis uit Oostende.', en: 'The fish seller has fresh fish from Ostend.', image: 'fish' },
      { nl: 'Twee stukken vis, graag. Dat is genoeg voor twee mensen.', en: 'Two pieces of fish, please. That is enough for two people.', image: 'fish' },
    ],
    note: 'het kraam, de kramen (market stall — in the Netherlands de kraam) · de verkoper (seller); a woman is de verkoopster · de kilo: after a number no plural (twee kilo, drie euro) and no “of”: een kilo tomaten · een halve kilo (half a kilo) · het stuk, de stukken (piece); het stukje, de stukjes (small piece) · de tomaat, de tomaten · de aardappel, de aardappelen (or aardappels) · de ui, de uien (onion) · de wortel, de wortels (carrot) · de prei (leek) · vers, verse (fresh) · lekker (tasty) · proeven (to taste) · genoeg (enough) · boodschappen doen (to do the shopping). “Wat mag het zijn?” is what a seller says. “… graag” is the easiest polite way to ask for something.',
  },
  {
    type: 'observe', title: 'In the kitchen', grammar: ['imperative', 'position-verbs', 'hoeven-te', 'place-prepositions'],
    instruction: 'The evening: soup. Listen and repeat. Notice the orders of a recipe — the imperative of lesson 16.',
    cards: [
      { nl: 'Bram snijdt een ui in kleine stukjes.', en: 'Bram cuts an onion into small pieces.', image: 'man-cutting' },
      { nl: 'Dan bakt hij de ui vijf minuten in de pan.', en: 'Then he fries the onion in the pan for five minutes.', image: 'man-cooking' },
      { nl: 'Doe de groenten in de pan en kook de soep twintig minuten.', en: 'Put the vegetables in the pan and cook the soup for twenty minutes.', image: 'soup' },
      { nl: 'Bram proeft de soep. Er moet nog wat zout en peper bij.', en: 'Bram tastes the soup. It needs a bit more salt and pepper.', image: 'soup' },
      { nl: 'Snijd voorzichtig met dat grote mes!', en: 'Cut carefully with that big knife!', image: 'man-cutting' },
      { nl: 'Max heeft honger. Hij ligt onder de tafel en wacht.', en: 'Max is hungry. He is lying under the table, waiting.', image: 'dog-big' },
      { nl: 'Hij hoopt dat er een stukje vlees op de vloer valt.', en: 'He hopes a little piece of meat will fall on the floor.', image: 'dog-big' },
      { nl: 'Soep met veel groenten is gezond.', en: 'Soup with lots of vegetables is healthy.', image: 'soup' },
      { nl: 'Moet ik helpen? — Nee, dank je, dat hoeft niet.', en: 'Do I have to help? — No, thanks, there’s no need.', image: 'couple-talking' },
      { nl: 'De soep staat op tafel. Smakelijk!', en: 'The soup is on the table. Enjoy your meal!', image: 'soup' },
    ],
    note: 'de pan, de pannen · het mes, de messen (knife) · het zout (salt) · de peper (pepper) · de minuut, de minuten · bakken (to fry, to bake: ik bak, hij bakt) · koken (to cook — and to boil: het water kookt) · honger hebben (to be hungry: ik heb honger) · vallen (to fall: het valt; the past is viel) · voorzichtig (careful, carefully) · gezond (healthy) · vanavond (this evening, tonight) · Smakelijk! (said before a meal). “Er moet nog wat zout bij” = it needs a bit more salt: “wat” here means “some”. In Dutch you “doen” food into a pan: Doe de groenten in de pan.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['om-te'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Bram en Lotte gaan naar de markt om groenten en fruit te kopen.', en: 'Bram and Lotte go to the market to buy vegetables and fruit.', answer: 'market',
    choices: [{ image: 'shop', nl: 'een winkel' }, { image: 'market', nl: 'de markt' }, { image: 'kitchen', nl: 'de keuken' }, { image: 'station', nl: 'het station' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['demonstratives'],
    instruction: 'Listen without reading. What comes from Ostend today?',
    nl: 'Deze vis komt vandaag uit Oostende.', en: 'This fish comes from Ostend today.', answer: 'fish',
    choices: [{ image: 'soup', nl: 'de soep' }, { image: 'vegetables', nl: 'de groenten' }, { image: 'fish', nl: 'de vis' }, { image: 'bread', nl: 'het brood' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['de-het', 'plural'],
    instruction: 'Type the Dutch. Nouns with their article.',
    items: [
      { image: 'market', answer: 'de markt' },
      { image: 'vegetables', en: 'the vegetables', answer: 'de groenten', accept: ['de groentes'] },
      { image: 'fish', answer: 'de vis' },
      { image: 'soup', answer: 'de soep' },
      { en: 'the fruit', answer: 'het fruit' },
      { en: 'the meat', answer: 'het vlees' },
      { en: 'the egg', answer: 'het ei' },
      { en: 'the eggs', answer: 'de eieren' },
      { en: 'the recipe', answer: 'het recept' },
      { image: 'man-cutting', en: 'the knife', answer: 'het mes' },
      { en: 'the market stall (in Flanders)', answer: 'het kraam' },
      { en: 'the tomatoes', answer: 'de tomaten' },
      { en: 'the potatoes', answer: 'de aardappelen', accept: ['de aardappels'] },
      { en: 'the onions', answer: 'de uien' },
    ],
    explanation: 'het fruit, het vlees, het ei, het recept, het mes, het kraam: six het-words. Every plural takes de — de eieren, de tomaten. ei → eieren is irregular; tomaat → tomaten loses one a (to-ma-ten: an open syllable).',
  },
  {
    type: 'drill', title: 'Hear and spell', grammar: ['dt-rule', 'demonstratives'],
    instruction: 'Play each one and type it. “ui” is the sound of huis; the ij of snijden is the ij of rijden; the d of “ik snijd” is silent.',
    items: [
      { listen: 'de groenten' },
      { listen: 'zes eieren' },
      { listen: 'een halve kilo' },
      { listen: 'Ik snijd de ui.' },
      { listen: 'Hij snijdt de prei.' },
      { listen: 'Welke vis?' },
      { listen: 'voorzichtig' },
    ],
    explanation: 'ik snijd and hij snijdt sound the same — the spelling follows the rule, not the ear. voorzichtig: voor-ZICH-tig, and the g at the end is soft.',
  },

  // ——— Grammar: the new verbs ———
  {
    part: 'Grammar', type: 'grammar', title: 'snijden, hoeven and four kitchen verbs', grammar: ['present-regular', 'dt-rule', 'spelling-z-s', 'imperfect-weak', 'imperfect-strong', 'perfect-zijn', 'imperative'],
    body: [
      'Two target verbs — **snijden** (to cut) and **hoeven** (to need to) — and four more for the kitchen: **proeven** (to taste), **bakken** (to fry, to bake), **vallen** (to fall) and **koken** (to cook, to boil), which you know. In the present they follow the rule of lesson 3: ik + stem, jij / hij + stem + t, the plural = the infinitive.',
      '**snijden** is the d + t verb of this lesson, like rijden and vinden (lesson 9). The stem is **snijd**, with a d you cannot hear: *ik snijd, jij snijdt, hij snijdt* — three spellings, one sound. In a question jij loses the t, but the d stays: ***Snijd** jij de uien?* The imperative is the stem: ***Snijd** de prei in stukjes!*',
      '**proeven** and **hoeven**: v becomes f at the end of the stem, as in schrijven → ik schrijf and beloven → ik beloof: *ik proef, hij proeft; ik hoef, hij hoeft; hoef jij?* **bakken** and **vallen** keep one consonant at the end: *ik bak, hij bakt; het valt*.',
      '**The past.** ’t kofschip looks at the infinitive: *proeven → proefde, hoeven → hoefde* (v is not in ’t kofschip), *bakken → bakte* (k is). **snijden** and **vallen** are strong: *sneed, sneden, gesneden* and *viel, vielen, gevallen* — and vallen, a movement, takes **zijn**: *Er **is** een ei **gevallen**.* **bakken** is half and half: the past is regular (*bakte*), the participle strong (***gebakken***). A fried egg is *een gebakken ei*.',
      'What makes **hoeven** special is not its forms but its meaning: it is the negative of moeten, and it only appears with niet, geen, nooit or maar. It has its own grammar page after om … te.',
    ],
    tables: [
      { caption: 'snijden — d + t', rows: [
        { nl: 'ik snijd', en: 'I cut' },
        { nl: 'jij snijd[t] · hij snijd[t]', en: 'you cut · he cuts — the same sound' },
        { nl: 'snijd jij?', en: 'do you cut? — no t behind the verb, but the d stays' },
        { nl: 'wij snijd[en] · jullie snijd[en] · zij snijd[en]', en: 'we · you · they cut' },
        { nl: 'Snijd de prei!', en: 'Cut the leek! — the imperative is the stem' },
      ] },
      { caption: 'proeven · hoeven · bakken · vallen', rows: [
        { nl: 'ik proef · hij proef[t]', en: 'I taste · he tastes (v → f)' },
        { nl: 'ik hoef · hij hoef[t] · hoef jij?', en: 'I need · he needs · do you need?' },
        { nl: 'ik bak · hij bak[t]', en: 'I fry · he fries' },
        { nl: 'ik val · het val[t]', en: 'I fall · it falls' },
      ] },
      { caption: 'The past', rows: [
        { nl: 'Bram [sneed] de prei. · Hij heeft de prei [gesneden].', en: 'Bram cut the leek. · He has cut the leek.' },
        { nl: 'Lotte [proefde] de soep. · Zij heeft de soep [geproefd].', en: 'Lotte tasted the soup.' },
        { nl: 'Bram [bakte] een ei. · Hij heeft een ei [gebakken].', en: 'Bram fried an egg.' },
        { nl: 'Het ei [viel] op de vloer. · Het ei is op de vloer [gevallen].', en: 'The egg fell on the floor — zijn.' },
        { nl: 'Wij [hoefden] niet te koken.', en: 'We didn’t have to cook.' },
      ] },
    ],
    examples: [
      { nl: 'Snijd jij de uien? Dan snijd ik de wortels.', en: 'Will you cut the onions? Then I’ll cut the carrots.' },
      { nl: 'Lotte proeft de soep en zegt: “Lekker!”', en: 'Lotte tastes the soup and says: “Tasty!”' },
      { nl: 'Morgen bakt Bram de vis in de pan.', en: 'Tomorrow Bram will fry the fish in the pan.' },
      { nl: 'Er is een stukje wortel op de vloer gevallen.', en: 'A piece of carrot has fallen on the floor.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate snijden', grammar: ['present-regular', 'dt-rule', 'subject-pronouns'],
    instruction: 'Type the form of snijden for every person. Think of rijden: the d stays in every form.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'snijd' },
      { label: 'jij', gloss: 'you', answer: 'snijdt' },
      { label: 'hij', gloss: 'he', answer: 'snijdt' },
      { label: 'zij', gloss: 'she', answer: 'snijdt' },
      { label: 'wij', gloss: 'we', answer: 'snijden' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'snijden' },
      { label: 'zij', gloss: 'they', answer: 'snijden' },
      { label: 'Lotte', gloss: 'she', answer: 'snijdt' },
      { label: 'Lotte en ik', gloss: 'we', answer: 'snijden' },
    ],
    explanation: 'snijd + t = snijdt: never “snijt” and never “snijdd”. ik snijd has no t — like ik rijd, ik vind.',
  },
  {
    type: 'drill', layout: 'table', title: 'hoeven, proeven, bakken, vallen, koken', grammar: ['present-regular', 'spelling-z-s', 'spelling-stem', 'subject-pronouns'],
    instruction: 'Mixed persons. The small word under each person is the verb. Type the present-tense form.',
    items: [
      { label: 'ik', gloss: 'hoeven', answer: 'hoef' },
      { label: 'jij', gloss: 'hoeven', answer: 'hoeft' },
      { label: 'wij', gloss: 'hoeven', answer: 'hoeven' },
      { label: 'ik', gloss: 'proeven', answer: 'proef' },
      { label: 'Bram', gloss: 'he · proeven', answer: 'proeft' },
      { label: 'ik', gloss: 'bakken', answer: 'bak' },
      { label: 'hij', gloss: 'bakken', answer: 'bakt' },
      { label: 'jullie', gloss: 'bakken', answer: 'bakken' },
      { label: 'het ei', gloss: 'it · vallen', answer: 'valt' },
      { label: 'ik', gloss: 'vallen', answer: 'val' },
      { label: 'het water', gloss: 'it · koken', answer: 'kookt' },
      { label: 'ik', gloss: 'koken', answer: 'kook' },
    ],
    explanation: 'hoef and proef with f, hoeven and proeven with v. bak and val: one consonant at the end of a word (bak-ken → bak). koken → kook: the long o needs two letters in a closed syllable.',
  },
  {
    type: 'drill', title: 'Present and past in the kitchen', grammar: ['present-regular', 'inversion', 'imperfect-weak', 'imperfect-strong', 'perfect-hebben', 'perfect-zijn', 'toen-past', 'dt-rule'],
    instruction: 'Type the form of the verb given. When the sentence or the English is in the past, use the past.',
    items: [
      { nl: '___ jij de uien?', cue: 'snijden', en: 'Are you cutting the onions?', answer: 'Snijd' },
      { nl: 'Mijn moeder ___ de prei altijd in kleine stukjes.', cue: 'snijden', answer: 'snijdt' },
      { nl: 'Gisteren ___ Bram de vis in de pan.', cue: 'bakken', en: 'Yesterday Bram fried the fish in the pan.', answer: 'bakte' },
      { nl: 'Lotte heeft de groenten ___.', cue: 'snijden', answer: 'gesneden' },
      { nl: 'Er is een stukje wortel op de vloer ___.', cue: 'vallen', answer: 'gevallen' },
      { nl: 'Het mes ___ op de vloer.', cue: 'vallen', en: 'The knife fell on the floor.', answer: 'viel' },
      { nl: 'Toen Bram klein was, ___ zijn moeder elke zaterdag soep.', cue: 'maken', answer: 'maakte' },
      { nl: 'Vroeger ___ oma de soep altijd twee keer.', cue: 'proeven', en: 'Grandma always used to taste the soup twice.', answer: 'proefde' },
      { nl: 'Wie ___ vanavond de vis?', cue: 'bakken', en: 'Who is frying the fish tonight?', answer: 'bakt' },
      { nl: 'Wij ___ gisteren niet te koken.', cue: 'hoeven', en: 'We didn’t have to cook yesterday.', answer: 'hoefden' },
    ],
    explanation: 'Snijd jij? — jij behind the verb: no t, the d stays. sneed, viel: strong. bakte but gebakken. proefde, hoefden: -de, because the infinitive has a v.',
  },

  // ——— Grammar: om … te ———
  {
    type: 'grammar', title: 'om … te: to, in order to', grammar: ['om-te', 'te-infinitive', 'separable', 'reflexive', 'v2-inversion', 'perfect-zijn'],
    body: [
      'To say **what for** someone does something — the purpose — English uses *to* or *in order to*: *They go to the market to buy vegetables.* Dutch uses **om … te** + infinitive: *Zij gaan naar de markt **om** groenten **te kopen**.*',
      '**The shape.** om opens the group, **te + infinitive** closes it, and everything that belongs to the infinitive — its object, a place, a time, niet — stands **between** them: *om **verse vis** te kopen, om **op de markt** groenten te kopen, om **morgen vroeg** op te staan, om de soep **niet** te vergeten.* The infinitive is always last. Never *om te kopen groenten* — that is English order.',
      '**Separable verbs split around te**, exactly as after proberen in lesson 17: *om vroeg **op te staan**, om brood **mee te nemen**, om **uit te gaan***. A reflexive pronoun comes straight after om: *Tom neemt een medicijn **om zich** beter **te voelen**.*',
      '**Where does it go?** Usually at the end: *Bram belt zijn moeder op **om het recept te vragen**.* It may also come first; then the whole group is position one, and the verb follows at once: ***Om goede vis te kopen**, gaan zij vroeg naar de markt.* In the perfect the om-group stays outside the verbs at the end: *Zij zijn naar de markt **gegaan** om groenten te kopen.*',
      '**Waarom? — Om …** A short answer to *waarom* can be the om-group alone: *Waarom sta je zo vroeg op? — **Om** naar de markt **te gaan**.* A reason with a full clause uses omdat: *— **Omdat** ik naar de markt wil gaan.* Both are correct; om … te is shorter.',
      '**The trap: English *to* is not always om … te.** After a modal, zullen or gaan there is no te at all: *Ik **wil** soep **maken**.* After proberen, beginnen, vergeten, beloven and hopen there is te **without** om: *Ik **probeer** soep **te maken**.* om … te is for a **purpose** — the answer to *what for?*',
    ],
    tables: [
      { caption: 'om … te: the purpose', rows: [
        { nl: 'Zij gaan naar de markt [om] groenten [te] kopen.', en: 'They go to the market to buy vegetables.' },
        { nl: 'Bram belt zijn moeder op [om] het recept [te] vragen.', en: 'Bram rings his mother to ask for the recipe.' },
        { nl: 'Bram neemt een groot mes [om] de prei [te] snijden.', en: 'Bram takes a big knife to cut the leek.' },
        { nl: 'Max ligt onder de tafel [om] een stukje vlees [te] krijgen.', en: 'Max lies under the table to get a piece of meat.' },
      ] },
      { caption: 'Separable and reflexive verbs', rows: [
        { nl: 'Bram zet een wekker [om] vroeg op [te] staan.', en: 'Bram sets an alarm to get up early.' },
        { nl: 'Jonas komt naar Leuven [om] met zijn vrienden uit [te] gaan.', en: 'Jonas comes to Leuven to go out with his friends.' },
        { nl: 'Tom neemt een medicijn [om] zich beter [te] voelen.', en: 'Tom takes a medicine to feel better.' },
      ] },
      { caption: 'First, in the perfect, as an answer', rows: [
        { nl: '[Om] goede vis [te] kopen, gaan zij vroeg naar de markt.', en: 'To buy good fish, they go to the market early.' },
        { nl: 'Zij zijn naar de markt gegaan [om] groenten [te] kopen.', en: 'They went to the market to buy vegetables.' },
        { nl: 'Waarom sta je zo vroeg op? — [Om] naar de markt [te] gaan.', en: 'Why are you getting up so early? — To go to the market.' },
      ] },
    ],
    examples: [
      { nl: 'Lotte belt Tom op om te vragen of hij vanavond komt eten.', en: 'Lotte rings Tom to ask whether he is coming to dinner tonight.' },
      { nl: 'Om op tijd op de markt te zijn, staan zij om zeven uur op.', en: 'To be at the market in time, they get up at seven.' },
      { nl: 'Ik leer Nederlands om in Leuven te studeren.', en: 'I am learning Dutch to study in Leuven.' },
    ],
  },
  {
    type: 'drill', title: 'Join with om … te', grammar: ['om-te', 'separable', 'reflexive', 'niet', 'infinitive-end'], task: 'Join with om … te',
    instruction: 'Make one sentence. “Hij wil …” becomes om … te: drop the subject and willen, keep the rest in order, and put te + the infinitive last.',
    items: [
      { nl: 'Bram gaat naar de markt. Hij wil vis kopen.', answer: 'Bram gaat naar de markt om vis te kopen.' },
      { nl: 'Lotte gaat naar het kraam. Zij wil de tomaten proeven.', answer: 'Lotte gaat naar het kraam om de tomaten te proeven.' },
      { nl: 'Bram belt zijn moeder op. Hij wil het recept vragen.', answer: 'Bram belt zijn moeder op om het recept te vragen.' },
      { nl: 'Bram neemt een groot mes. Hij wil de prei snijden.', answer: 'Bram neemt een groot mes om de prei te snijden.' },
      { nl: 'Wij staan om zeven uur op. Wij willen vroeg op de markt zijn.', answer: 'Wij staan om zeven uur op om vroeg op de markt te zijn.' },
      { nl: 'Lotte neemt een grote tas mee. Zij wil de boodschappen dragen.', answer: 'Lotte neemt een grote tas mee om de boodschappen te dragen.' },
      { nl: 'Tom zet een wekker. Hij wil vroeg opstaan.', answer: 'Tom zet een wekker om vroeg op te staan.' },
      { nl: 'Jonas komt naar Leuven. Hij wil met zijn vrienden uitgaan.', answer: 'Jonas komt naar Leuven om met zijn vrienden uit te gaan.' },
      { nl: 'Lotte spaart geld. Zij wil volgende zomer naar Spanje vliegen.', answer: 'Lotte spaart geld om volgende zomer naar Spanje te vliegen.' },
      { nl: 'Bram zet een wekker. Hij wil de soep niet vergeten.', answer: 'Bram zet een wekker om de soep niet te vergeten.' },
    ],
    explanation: 'op te staan, uit te gaan: a separable verb splits around te. niet stays in front of te: om de soep niet te vergeten. Everything else keeps its old order between om and te.',
  },
  {
    type: 'drill', title: 'Waarom? — Om …', grammar: ['om-te', 'question-word', 'want-omdat', 'verb-final', 'separable'], task: 'Answer with om … te',
    instruction: 'Answer each question with a short om-group, using the words given. The last one asks for omdat instead.',
    items: [
      { nl: 'Waarom gaan Bram en Lotte naar de markt?', cue: 'groenten kopen', answer: 'Om groenten te kopen.' },
      { nl: 'Waarom belt Bram zijn moeder op?', cue: 'het recept vragen', answer: 'Om het recept te vragen.' },
      { nl: 'Waarom staat Bram zo vroeg op?', cue: 'op tijd op de markt zijn', answer: 'Om op tijd op de markt te zijn.' },
      { nl: 'Waarom neemt Lotte een mes?', cue: 'de wortels snijden', answer: 'Om de wortels te snijden.' },
      { nl: 'Waarom ligt Max onder de tafel?', cue: 'een stukje vlees krijgen', answer: 'Om een stukje vlees te krijgen.' },
      { nl: 'Waarom komt Jonas vanavond naar Leuven?', cue: 'soep eten bij Bram en Lotte', answer: 'Om soep te eten bij Bram en Lotte.', accept: ['Om bij Bram en Lotte soep te eten.'] },
      { nl: 'Waarom leer jij Nederlands?', cue: 'in Leuven studeren', answer: 'Om in Leuven te studeren.' },
      { nl: 'Waarom gaat Tom om negen uur naar bed?', cue: 'vroeg opstaan', answer: 'Om vroeg op te staan.' },
      { nl: 'Waarom spaart Lotte geld?', cue: 'naar Spanje vliegen', answer: 'Om naar Spanje te vliegen.' },
      { nl: 'Waarom gaan Bram en Lotte naar de markt?', task: 'Answer with omdat + willen', answer: 'Omdat zij groenten willen kopen.', accept: ['Omdat Bram en Lotte groenten willen kopen.'] },
    ],
    explanation: 'Om … te: a purpose, no subject, no conjugated verb. Omdat …: a full clause with a subject, and the conjugated verb at the end — willen kopen.',
  },
  {
    type: 'drill', title: 'te, om … te — or neither?', grammar: ['om-te', 'te-infinitive', 'modals', 'zullen-future', 'separable-together', 'separable', 'imperative'],
    instruction: 'Type the verb in the shape the sentence needs: a bare infinitive after a modal, zullen or gaan; te + infinitive after proberen, vergeten, beginnen, hopen; te + infinitive to close an om-group. A separable verb splits around te.',
    items: [
      { nl: 'Bram wil vanavond soep ___.', cue: 'maken', answer: 'maken' },
      { nl: 'Bram probeert de soep van zijn moeder ___.', cue: 'maken', answer: 'te maken' },
      { nl: 'Bram gaat naar de markt om groenten ___.', cue: 'kopen', answer: 'te kopen' },
      { nl: 'Vergeet niet de eieren ___!', cue: 'meenemen', answer: 'mee te nemen' },
      { nl: 'Wij moeten morgen vroeg ___.', cue: 'opstaan', answer: 'opstaan' },
      { nl: 'Wij zetten een wekker om vroeg ___.', cue: 'opstaan', answer: 'op te staan' },
      { nl: 'Het begint ___.', cue: 'regenen', answer: 'te regenen' },
      { nl: 'Zal ik de uien ___?', cue: 'snijden', answer: 'snijden' },
      { nl: 'Tom komt vanavond om soep ___.', cue: 'eten', answer: 'te eten' },
      { nl: 'Jonas hoopt om zeven uur in Leuven ___.', cue: 'aankomen', answer: 'aan te komen' },
      { nl: 'Emma gaat naar de winkel om bloemen ___.', cue: 'kopen', answer: 'te kopen' },
      { nl: 'Lotte gaat de groenten ___.', cue: 'snijden', answer: 'snijden' },
    ],
    explanation: 'wil, moeten, zal, gaat: no te. probeert, vergeet, begint, hoopt: te, without om. A purpose (om …): te to close it. Every te splits a separable verb: mee te nemen, op te staan, aan te komen.',
  },
  {
    type: 'arrange', title: 'To the market', grammar: ['om-te', 'adjective-e'],
    instruction: 'Build: “Bram and Lotte go to the market to buy fresh vegetables.” Two tiles are traps.',
    nl: 'Bram en Lotte gaan naar de markt om verse groenten te kopen.', en: 'Bram and Lotte go to the market to buy fresh vegetables.', image: 'market', distractors: ['voor', 'vers'],
  },
  {
    type: 'grammar', title: 'om … te or zodat? — and zonder … te', grammar: ['om-te', 'hoewel-zodat', 'want-omdat', 'dat-clause', 'of-whether', 'clock-time'],
    body: [
      '**One subject.** An om-group has no subject of its own: the person who does the te-verb is the subject of the main clause. *Bram gaat naar de markt om vis te kopen* — Bram buys the fish. When **someone else** does it, you need a full clause with **zodat** (lesson 23): *Bram kookt, **zodat** Lotte kan studeren.* Compare *Bram kookt **om** Lotte **te** helpen* — here Bram helps.',
      '**om after a noun or an adjective.** Many nouns take om … te: *Ik heb geen **tijd om** te koken. Het is **tijd om** te eten. Heb jij **zin om** mee te gaan?* After *het is* + an adjective, the om-group says what is easy, difficult or nice: *Het is **makkelijk om** soep te maken.* Here om may be dropped — *Het is makkelijk soep te maken* — both are correct.',
      '**zonder … te** = without …ing. It works exactly like om … te: *Max eet de wortel **zonder te kijken**.* English uses -ing; Dutch never does — not *zonder kijken*, but *zonder te kijken*. With a noun, zonder is simply a preposition: *soep **zonder vlees**, Bram **zonder fiets***.',
      '**om … te or omdat?** om … te is a purpose (what for?), omdat a reason (why? because of what?): *Ik ga naar de markt **om** vis **te** kopen. Ik ga naar de markt, **omdat** de vis daar verser is.*',
      'So **om** now has three jobs, and they can meet in one sentence: **om** + a clock time (*om zeven uur*), **om … te** (purpose), and inside **waarom** (why). *Waarom sta je om zes uur op? — Om op tijd op de markt te zijn.*',
    ],
    tables: [
      { caption: 'om … te or zodat?', rows: [
        { nl: 'Bram kookt [om] zijn vrienden [te] verrassen.', en: 'Bram cooks to surprise his friends — Bram surprises.' },
        { nl: 'Bram kookt, [zodat] Lotte kan studeren.', en: 'Bram cooks so that Lotte can study — someone else: zodat.' },
        { nl: 'Lotte snijdt de groenten, [zodat] Bram de soep kan maken.', en: 'Lotte cuts the vegetables so that Bram can make the soup.' },
      ] },
      { caption: 'om after a noun or an adjective', rows: [
        { nl: 'Ik heb geen tijd [om] [te] koken.', en: 'I have no time to cook.' },
        { nl: 'Het is tijd [om] [te] eten.', en: 'It is time to eat.' },
        { nl: 'Het is makkelijk [om] soep [te] maken.', en: 'It is easy to make soup. — also: Het is makkelijk soep te maken.' },
      ] },
      { caption: 'zonder', rows: [
        { nl: 'Max eet de wortel [zonder] [te] kijken.', en: 'Max eats the carrot without looking.' },
        { nl: 'Tom is weggegaan [zonder] [te] eten.', en: 'Tom left without eating.' },
        { nl: 'soep [zonder] vlees', en: 'soup without meat' },
      ] },
    ],
    examples: [
      { nl: 'Bram belt Emma op om te vragen of zij vlees eet.', en: 'Bram rings Emma to ask whether she eats meat.' },
      { nl: 'Emma eet geen vlees, dus Bram maakt soep zonder vlees.', en: 'Emma doesn’t eat meat, so Bram is making soup without meat.' },
      { nl: 'Hoewel het regent, gaan zij naar de markt om vis te kopen.', en: 'Although it is raining, they go to the market to buy fish.' },
      { nl: 'Zonder recept kan Bram geen soep maken.', en: 'Without a recipe Bram can’t make soup.' },
    ],
  },
  {
    type: 'drill', title: 'om … te or zodat?', grammar: ['om-te', 'hoewel-zodat', 'verb-final', 'modals', 'of-whether', 'object-pronouns'], task: 'Join: om … te or zodat',
    instruction: 'Make one sentence. Same person → om … te. Someone else → zodat, with the verbs at the end of its clause.',
    items: [
      { nl: 'Bram kookt. Lotte kan studeren.', answer: 'Bram kookt, zodat Lotte kan studeren.', accept: ['Bram kookt, zodat Lotte studeren kan.'] },
      { nl: 'Bram kookt. Hij wil zijn vrienden verrassen.', answer: 'Bram kookt om zijn vrienden te verrassen.' },
      { nl: 'Lotte snijdt de groenten. Bram kan de soep maken.', answer: 'Lotte snijdt de groenten, zodat Bram de soep kan maken.', accept: ['Lotte snijdt de groenten, zodat Bram de soep maken kan.'] },
      { nl: 'Lotte neemt een mes. Zij wil de groenten snijden.', answer: 'Lotte neemt een mes om de groenten te snijden.' },
      { nl: 'Bram koopt veel groenten. Er is genoeg soep voor vijf mensen.', answer: 'Bram koopt veel groenten, zodat er genoeg soep voor vijf mensen is.', accept: ['Bram koopt veel groenten, zodat er voor vijf mensen genoeg soep is.'] },
      { nl: 'Tom slaapt na zijn nachtdienst. Hij wil vanavond niet moe zijn.', answer: 'Tom slaapt na zijn nachtdienst om vanavond niet moe te zijn.' },
      { nl: 'Bram zet de soep op tafel. Zijn vrienden kunnen eten.', answer: 'Bram zet de soep op tafel, zodat zijn vrienden kunnen eten.', accept: ['Bram zet de soep op tafel, zodat zijn vrienden eten kunnen.'] },
      { nl: 'Lotte gaat naar de markt. Zij wil verse vis kopen.', answer: 'Lotte gaat naar de markt om verse vis te kopen.' },
      { nl: 'Bram belt Emma op. Hij wil vragen of zij vlees eet.', answer: 'Bram belt Emma op om te vragen of zij vlees eet.' },
      { nl: 'Emma belt Bram op. Hij weet dan dat zij geen vlees eet.', answer: 'Emma belt Bram op, zodat hij weet dat zij geen vlees eet.' },
    ],
    explanation: 'zodat Lotte kan studeren: a new subject, so a full clause with the verbs at the end. om vanavond niet moe te zijn: Tom himself, so om … te — with niet in front of te.',
  },
  {
    type: 'drill', title: 'zonder, tijd om, makkelijk om', grammar: ['om-te', 'perfect-zijn', 'imperfect-strong', 'geen-niet', 'imperative', 'modals'],
    instruction: 'Translate. “without …ing” is zonder te + infinitive; “time to”, “easy to” take om … te. “You” is one person.',
    items: [
      { en: 'Emma eats soup without meat.', answer: 'Emma eet soep zonder vlees.' },
      { en: 'Max eats the carrot without looking.', answer: 'Max eet de wortel zonder te kijken.' },
      { en: 'Don’t cut without looking!', answer: 'Snijd niet zonder te kijken!' },
      { en: 'Tom went home without eating. (perfect)', answer: 'Tom is naar huis gegaan zonder te eten.' },
      { en: 'Bram cooks without a recipe.', answer: 'Bram kookt zonder recept.', accept: ['Bram kookt zonder een recept.'] },
      { en: 'I have no time to cook.', answer: 'Ik heb geen tijd om te koken.' },
      { en: 'It is time to eat.', answer: 'Het is tijd om te eten.' },
      { en: 'It is easy to make soup.', answer: 'Het is makkelijk om soep te maken.', accept: ['Het is makkelijk soep te maken.'] },
      { en: 'Do you feel like going to the market? (use zin)', answer: 'Heb jij zin om naar de markt te gaan?' },
      { en: 'Lotte left without paying. — No: Lotte never leaves without paying!', answer: 'Lotte gaat nooit weg zonder te betalen!' },
    ],
    explanation: 'zonder te kijken, zonder te eten, zonder te betalen: te is never missing. zonder recept, zonder vlees: a noun needs no te. “zin hebben om …” (lesson 22: zin hebben in) = to feel like doing.',
  },
  {
    type: 'drill', title: 'om-groups in longer sentences', grammar: ['om-te', 'v2-inversion', 'perfect-zijn', 'separable-perfect', 'imperfect-strong', 'dat-clause', 'inversion', 'zullen-future', 'time-conjunctions'],
    instruction: 'Rewrite as the task says. Whatever happens to the main verb, the om-group stays in one piece — and when it comes first, the verb follows straight after it.',
    items: [
      { nl: 'Zij gaan vroeg naar de markt om goede vis te kopen.', task: 'Start with the om-group', answer: 'Om goede vis te kopen, gaan zij vroeg naar de markt.' },
      { nl: 'Bram staat om zeven uur op om naar de markt te gaan.', task: 'Start with the om-group', answer: 'Om naar de markt te gaan, staat Bram om zeven uur op.' },
      { nl: 'Bram gaat naar de markt om vis te kopen.', task: 'Put it in the perfect', answer: 'Bram is naar de markt gegaan om vis te kopen.' },
      { nl: 'Lotte belt Tom op om te vragen of hij komt.', task: 'Put it in the perfect', answer: 'Lotte heeft Tom opgebeld om te vragen of hij komt.', accept: ['Lotte heeft Tom opgebeld om te vragen of hij kwam.'] },
      { nl: 'Bram neemt een groot mes om de prei te snijden.', task: 'Put it in the simple past', answer: 'Bram nam een groot mes om de prei te snijden.' },
      { nl: 'Bram gaat naar de markt om vis te kopen.', task: 'Start with “Ik weet dat”', answer: 'Ik weet dat Bram naar de markt gaat om vis te kopen.' },
      { nl: 'Jij gaat naar de markt om groenten te kopen.', task: 'Make it a question', answer: 'Ga jij naar de markt om groenten te kopen?' },
      { nl: 'Wij gaan morgen naar de markt om vis te kopen.', task: 'Use zullen', answer: 'Wij zullen morgen naar de markt gaan om vis te kopen.' },
      { nl: 'Lotte snijdt de groenten om Bram te helpen.', task: 'Start with “Terwijl Bram kookt,”', answer: 'Terwijl Bram kookt, snijdt Lotte de groenten om hem te helpen.', accept: ['Terwijl Bram kookt, snijdt Lotte de groenten om Bram te helpen.'] },
    ],
    explanation: 'Om goede vis te kopen, gaan zij …: the om-group is position one, so gaan comes next. is gegaan om …, heeft opgebeld om …: the om-group stays after the participle. dat Bram naar de markt gaat om …: the verb of the dat-clause goes to the end of its clause, before the om-group.',
  },
  {
    type: 'arrange', title: 'Good fish, early', grammar: ['om-te', 'v2-inversion', 'adjective-e'],
    instruction: 'Build: “To buy good fish, they go to the market early.” Two tiles are traps.',
    nl: 'Om goede vis te kopen, gaan zij vroeg naar de markt.', en: 'To buy good fish, they go to the market early.', image: 'fish', distractors: ['gaat', 'goed'],
  },

  // ——— Grammar: niet hoeven te ———
  {
    type: 'grammar', title: 'niet hoeven te: you don’t have to', grammar: ['hoeven-te', 'modals', 'geen-niet', 'te-infinitive', 'separable', 'verb-final', 'imperfect-weak'],
    body: [
      '**moeten** means *must, have to*: *Ik moet werken.* Its negative is not what an English speaker expects. *I don’t have to work* is: *Ik **hoef niet te** werken.* **niet hoeven te** = there is no need to, it is not necessary: *Jullie **hoeven** geen eten mee **te nemen**.* (You don’t have to bring any food.)',
      '**hoeven only lives in negative sentences** — with niet, geen or nooit — or with **maar** (only, just): *Je **hoeft maar** één kilo te kopen.* (You only need to buy one kilo.) *Je hoeft maar te bellen.* (Just call.) Without one of those words hoeven is wrong, and you use moeten: *Ik moet koken* — never *ik hoef te koken*.',
      '**te.** Unlike moeten, hoeven takes **te** + infinitive, at the end: *Je hoeft niet **te koken**.* A separable verb splits around te: *Tom hoeft morgen niet vroeg **op te staan**. Jullie hoeven geen taart **mee te nemen**.* In a subordinate clause hoeven goes to the end, before the te-group: *Tom is blij, omdat hij morgen niet **hoeft te werken**.* (You will also hear *niet te werken hoeft*.) With a place and no verb, the infinitive can go, as with moeten: *Bram hoeft vandaag niet naar Brussel.*',
      '**niet or geen?** The rule of lesson 4 still decides. A noun with een or without an article → **geen**: *Je hoeft **geen** brood mee te nemen.* A noun with de, het, dit, mijn … → **niet**, after the noun: *Je hoeft **de groenten niet** te snijden.*',
      '**hoeven niet or mogen niet?** Keep them apart. *Je **hoeft** niet te koken* = you don’t need to (but you may). *Je **mag** niet koken* = you are not allowed to. *Max **mag** geen vlees van de tafel eten* — it is forbidden. A note on *moeten niet*: in the Netherlands *Je moet niet koken* means “you shouldn’t cook”; in Flanders it is also heard for “you don’t need to”. The standard, everywhere, is **hoeven niet te**.',
      '**Short answers.** *Moet ik brood meenemen? — Nee, **dat hoeft niet**.* (No, there’s no need.) — one of the most useful sentences in Dutch. And when a guest brings flowers anyway: *Dank je wel, maar **dat had niet gehoeven**!* — you shouldn’t have! Learn it as a fixed phrase; the tense behind it comes in the next volume.',
      '**The forms.** *ik hoef, jij hoeft, hoef jij?, hij hoeft, wij / jullie / zij hoeven*. The past: *hoefde, hoefden*: *Wij **hoefden** niet te betalen.*',
    ],
    tables: [
      { caption: 'moeten · niet hoeven · niet mogen', rows: [
        { nl: 'Ik [moet] vandaag koken.', en: 'I have to cook today.' },
        { nl: 'Ik [hoef] vandaag niet [te] koken.', en: 'I don’t have to cook today.' },
        { nl: 'Ik [mag] vandaag niet koken.', en: 'I am not allowed to cook today.' },
        { nl: 'Moet ik brood meenemen? — Nee, dat [hoeft] niet.', en: 'Do I have to bring bread? — No, there’s no need.' },
      ] },
      { caption: 'hoeven with niet, geen, nooit, maar', rows: [
        { nl: 'Jij [hoeft] niet [te] helpen.', en: 'You don’t have to help.' },
        { nl: 'Jullie [hoeven] geen taart mee [te] nemen.', en: 'You don’t have to bring a cake.' },
        { nl: 'Tom [hoeft] morgen niet vroeg op [te] staan.', en: 'Tom doesn’t have to get up early tomorrow.' },
        { nl: 'Noor [hoeft] nooit [te] koken.', en: 'Noor never has to cook.' },
        { nl: 'Je [hoeft] maar één kilo [te] kopen.', en: 'You only need to buy one kilo.' },
        { nl: 'Wij [hoefden] niet [te] betalen.', en: 'We didn’t have to pay.' },
      ] },
      { caption: 'The forms', rows: [
        { nl: 'ik hoef', en: 'I need' },
        { nl: 'jij hoef[t] · hoef jij?', en: 'you need · do you need?' },
        { nl: 'hij hoef[t] · zij hoef[t]', en: 'he needs · she needs' },
        { nl: 'wij hoev[en] · jullie hoev[en] · zij hoev[en]', en: 'we · you · they need' },
      ] },
    ],
    examples: [
      { nl: 'Moet jij morgen werken? — Nee, ik hoef morgen niet te werken.', en: 'Do you have to work tomorrow? — No, I don’t have to work tomorrow.' },
      { nl: 'Hoef jij vanavond niet te koken? — Nee, Bram kookt.', en: 'Don’t you have to cook tonight? — No, Bram is cooking.' },
      { nl: 'Tom is blij, omdat hij morgen niet hoeft te werken.', en: 'Tom is happy because he doesn’t have to work tomorrow.' },
      { nl: 'Max mag geen vlees eten, en hij hoeft ook geen soep te eten.', en: 'Max is not allowed to eat meat, and he doesn’t have to eat soup either.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate hoeven', grammar: ['present-regular', 'spelling-z-s', 'subject-pronouns', 'imperfect-weak'],
    instruction: 'Type the form of hoeven. The last two rows are the simple past.',
    items: [
      { label: 'ik', gloss: 'I', answer: 'hoef' },
      { label: 'jij', gloss: 'you', answer: 'hoeft' },
      { label: 'hij', gloss: 'he', answer: 'hoeft' },
      { label: 'zij', gloss: 'she', answer: 'hoeft' },
      { label: 'wij', gloss: 'we', answer: 'hoeven' },
      { label: 'jullie', gloss: 'you (plural)', answer: 'hoeven' },
      { label: 'zij', gloss: 'they', answer: 'hoeven' },
      { label: 'ik', gloss: 'I · past', answer: 'hoefde' },
      { label: 'wij', gloss: 'we · past', answer: 'hoefden' },
    ],
    explanation: 'hoef, hoeft — hoeven: f at the end of a word, v between two vowels. The past takes -de (v is not in ’t kofschip).',
  },
  {
    type: 'drill', title: 'No need: answer with hoeven', grammar: ['hoeven-te', 'geen-niet', 'separable', 'object-pronouns', 'subject-pronouns'], task: 'Answer “Nee” with hoeven',
    instruction: 'Each question asks “do I / we / you have to …?”. Answer no — in a full sentence with hoeven and te. Change the person where you need to.',
    items: [
      { nl: 'Moet ik brood meenemen?', answer: 'Nee, je hoeft geen brood mee te nemen.' },
      { nl: 'Moet ik helpen?', answer: 'Nee, je hoeft niet te helpen.' },
      { nl: 'Moet Tom morgen werken?', answer: 'Nee, hij hoeft morgen niet te werken.', accept: ['Nee, Tom hoeft morgen niet te werken.'] },
      { nl: 'Moeten wij de tomaten snijden?', answer: 'Nee, jullie hoeven de tomaten niet te snijden.', accept: ['Nee, wij hoeven de tomaten niet te snijden.'] },
      { nl: 'Moet Emma een taart meenemen?', answer: 'Nee, zij hoeft geen taart mee te nemen.', accept: ['Nee, Emma hoeft geen taart mee te nemen.'] },
      { nl: 'Moeten jullie morgen vroeg opstaan?', answer: 'Nee, wij hoeven morgen niet vroeg op te staan.' },
      { nl: 'Moet ik de soep proeven?', answer: 'Nee, je hoeft de soep niet te proeven.' },
      { nl: 'Moet Bram vandaag naar Brussel?', answer: 'Nee, hij hoeft vandaag niet naar Brussel.', accept: ['Nee, hij hoeft vandaag niet naar Brussel te gaan.', 'Nee, Bram hoeft vandaag niet naar Brussel.', 'Nee, Bram hoeft vandaag niet naar Brussel te gaan.'] },
      { nl: 'Moet ik je opbellen?', answer: 'Nee, je hoeft me niet op te bellen.', accept: ['Nee, je hoeft mij niet op te bellen.'] },
      { nl: 'Moeten wij voor de soep betalen?', answer: 'Nee, jullie hoeven niet voor de soep te betalen.', accept: ['Nee, jullie hoeven voor de soep niet te betalen.', 'Nee, wij hoeven niet voor de soep te betalen.', 'Nee, wij hoeven voor de soep niet te betalen.'] },
    ],
    explanation: 'geen brood, geen taart: a noun without de or het → geen. de tomaten, de soep, me → niet after them. mee te nemen, op te staan, op te bellen: te splits the separable verb.',
  },
  {
    type: 'drill', title: 'hoeven, moeten or mogen?', grammar: ['hoeven-te', 'modals', 'inversion', 'imperfect-weak', 'imperfect-strong'],
    instruction: 'Type the right verb in the right form. The English decides: must, don’t have to, or not allowed. Watch for te: only hoeven takes it.',
    items: [
      { nl: 'Max ___ geen vlees van de tafel eten.', cue: 'hoeven / moeten / mogen', en: 'Max is not allowed to eat meat from the table.', answer: 'mag' },
      { nl: 'Jullie ___ niet te koken: Bram kookt.', cue: 'hoeven / moeten / mogen', en: 'You don’t have to cook: Bram is cooking.', answer: 'hoeven' },
      { nl: 'Bram ___ vandaag nog vis kopen.', cue: 'hoeven / moeten / mogen', en: 'Bram still has to buy fish today.', answer: 'moet' },
      { nl: '___ jij morgen niet te werken?', cue: 'hoeven / moeten / mogen', en: 'Don’t you have to work tomorrow?', answer: 'Hoef' },
      { nl: 'Tom ___ om zes uur in het ziekenhuis zijn.', cue: 'hoeven / moeten / mogen', en: 'Tom has to be at the hospital at six.', answer: 'moet' },
      { nl: 'Je ___ maar één kilo te kopen.', cue: 'hoeven / moeten / mogen', en: 'You only need to buy one kilo.', answer: 'hoeft' },
      { nl: 'Noor ___ nog niet met het grote mes snijden.', cue: 'hoeven / moeten / mogen', en: 'Noor is not allowed to cut with the big knife yet.', answer: 'mag' },
      { nl: 'Wij ___ gisteren niet te betalen.', cue: 'hoeven / moeten / mogen', en: 'We didn’t have to pay yesterday.', answer: 'hoefden' },
      { nl: 'Lotte ___ haar project niet meer te schrijven: het is klaar.', cue: 'hoeven / moeten / mogen', en: 'Lotte doesn’t have to write her project any more: it is finished.', answer: 'hoeft' },
      { nl: 'Voor dit medicijn ___ je een recept van de dokter hebben.', cue: 'hoeven / moeten / mogen', en: 'For this medicine you must have a prescription from the doctor.', answer: 'moet' },
    ],
    explanation: 'mag niet / mag geen: forbidden. hoeft niet te / hoeft geen … te: not necessary. moet: necessary — and moet, like mag, never takes te. Hoef jij …? — jij behind the verb, no t. “het recept” is also the prescription you take to the pharmacy.',
  },
  {
    type: 'drill', title: 'Say it in Dutch: no need', grammar: ['hoeven-te', 'modals', 'want-omdat', 'verb-final', 'separable', 'inversion', 'imperfect-weak'],
    instruction: 'Translate. “You” is one person unless it says plural.',
    items: [
      { en: 'You don’t have to cook tonight.', answer: 'Jij hoeft vanavond niet te koken.', accept: ['Vanavond hoef jij niet te koken.'] },
      { en: 'You (plural) don’t have to bring a cake.', answer: 'Jullie hoeven geen taart mee te nemen.' },
      { en: 'Do I have to help? — No, there’s no need.', answer: 'Moet ik helpen? Nee, dat hoeft niet.' },
      { en: 'Tom doesn’t have to get up early tomorrow.', answer: 'Tom hoeft morgen niet vroeg op te staan.', accept: ['Morgen hoeft Tom niet vroeg op te staan.'] },
      { en: 'Max is not allowed to eat meat.', answer: 'Max mag geen vlees eten.' },
      { en: 'Don’t you have to work tomorrow?', answer: 'Hoef jij morgen niet te werken?' },
      { en: 'We didn’t have to pay. (simple past)', answer: 'Wij hoefden niet te betalen.' },
      { en: 'Lotte is happy, because she doesn’t have to study tonight. (use omdat)', answer: 'Lotte is blij, omdat zij vanavond niet hoeft te studeren.', accept: ['Lotte is blij, omdat zij vanavond niet te studeren hoeft.', 'Lotte is blij, omdat zij vanavond niet hoeft te leren.', 'Lotte is blij, omdat zij vanavond niet te leren hoeft.'] },
      { en: 'You only need to buy one kilo of tomatoes.', answer: 'Je hoeft maar één kilo tomaten te kopen.' },
      { en: 'Thank you, but you shouldn’t have! (the fixed phrase)', answer: 'Dank je wel, maar dat had niet gehoeven!', accept: ['Dank je, maar dat had niet gehoeven!'] },
    ],
    explanation: 'omdat zij … niet hoeft te studeren: in a subclause hoeft goes to the end, before its te-group. hoefden: the past of hoeven. Mag geen, not hoeft geen, when something is forbidden.',
  },
  {
    type: 'arrange', title: 'No cake needed', grammar: ['hoeven-te', 'separable', 'geen-niet'],
    instruction: 'Build: “You (plural) don’t have to bring a cake.” Two tiles are traps.',
    nl: 'Jullie hoeven geen taart mee te nemen.', en: 'You don’t have to bring a cake.', image: 'birthday', distractors: ['moeten', 'niet'],
  },

  // ——— Grammar: deze, die, dit, dat, welk ———
  {
    type: 'grammar', title: 'deze, die, dit, dat — and welk, welke', grammar: ['demonstratives', 'de-het', 'plural', 'adjective-e', 'dit-is', 'relative-clause', 'dat-clause', 'kennen-weten'],
    body: [
      '**deze, die, dit, dat** point at something: *this* and *that*, *these* and *those*. As with die and dat in lesson 18, the choice depends on the article of the noun — and on whether it is near or far.',
      '**de**-words and **all plurals**: **deze** (this, these — near) and **die** (that, those — further away). **het**-words in the singular: **dit** (this) and **dat** (that). *deze tomaat, deze tomaten, die vis, die vissen* — *dit ei, dat mes* — but *deze eieren, die messen*: a plural is always a de-word.',
      '**Near and far** work as in English: *deze tomaten hier* (in front of me), *die tomaten daar* (over there). Time works the same way: *deze week, dit jaar* (now) — *die dag, dat jaar* (back then).',
      '**Without a noun** they stand for one, and the article still decides: *Welke tomaten wil je? — **Deze**. Welk mes neem je? — **Dit**. Deze of die?* You know this use from lesson 18: *Ken jij Tom? — Ja, **die** ken ik.*',
      '**An adjective after deze, die, dit or dat always takes -e**, as after de and het: *deze **verse** vis, dit **verse** ei, dat **grote** mes*. The trap: *een groot mes* (een + het-word: no -e), but *dit grot**e** mes*.',
      '**Presenting: dit is, dit zijn.** When you introduce or show something, Dutch uses **dit** or **dat** — never deze or die — whatever the article: *Dit is mijn broer. Dit is de soep. Dat is de markt.* With a plural the verb becomes plural, but dit stays: ***Dit zijn** mijn vrienden. **Dat zijn** de tomaten uit Spanje.* English says *these are*, Dutch *dit zijn*.',
      '**welk and welke** (which) split the same way: **welke** + a de-word or a plural, **welk** + a het-word in the singular: *Welke vis? Welke tomaten? Welke eieren?* but *Welk mes? Welk recept? Welk fruit?* Welk(e) + noun is position one of the question, so the verb follows: *Welke tomaten **zijn** het lekkerst?*',
      'You now know **die** and **dat** in three jobs. Pointing: *Die tomaten zijn duur.* Relative (lesson 18): *de tomaten **die** ik gekocht heb*. And dat as a conjunction (lesson 12): *Ik weet **dat** ze duur zijn.* They can meet in one sentence: *Die tomaten die jij gekocht hebt, zijn lekker.*',
    ],
    tables: [
      { caption: 'this · that', rows: [
        { nl: '[deze] tomaat · [die] tomaat', en: 'de tomaat: this tomato · that tomato' },
        { nl: '[dit] ei · [dat] ei', en: 'het ei: this egg · that egg' },
        { nl: '[deze] eieren · [die] eieren', en: 'plural: these eggs · those eggs' },
        { nl: '[deze] week · [dit] jaar', en: 'this week · this year' },
        { nl: '[die] dag · [dat] jaar', en: 'that day · that year (back then)' },
      ] },
      { caption: 'welke · welk', rows: [
        { nl: 'welk[e] vis? · welk[e] soep?', en: 'which fish? which soup? — de-words' },
        { nl: 'welk[e] tomaten? · welk[e] eieren?', en: 'which tomatoes? which eggs? — plurals' },
        { nl: 'welk mes? · welk recept? · welk fruit?', en: 'which knife? recipe? fruit? — het-words' },
      ] },
      { caption: 'Presenting and pointing', rows: [
        { nl: '[Dit] is mijn broer Tom.', en: 'This is my brother Tom.' },
        { nl: '[Dit] zijn mijn vrienden Emma en Jonas.', en: 'These are my friends Emma and Jonas.' },
        { nl: '[Dat] zijn de tomaten uit Spanje.', en: 'Those are the tomatoes from Spain.' },
        { nl: 'Welke wil je? — [Deze].', en: 'Which ones do you want? — These.' },
      ] },
      { caption: 'An adjective after deze, dit …', rows: [
        { nl: 'deze vers[e] vis', en: 'this fresh fish' },
        { nl: 'dit vers[e] ei', en: 'this fresh egg' },
        { nl: 'dat grot[e] mes · een groot mes', en: 'that big knife · a big knife' },
      ] },
    ],
    examples: [
      { nl: 'Welke tomaten zijn het lekkerst, deze of die?', en: 'Which tomatoes are the tastiest, these or those?' },
      { nl: 'Deze hier komen uit België, die daar uit Spanje.', en: 'These here come from Belgium, those over there from Spain.' },
      { nl: 'Dit is het recept van mijn moeder.', en: 'This is my mother’s recipe.' },
      { nl: 'Die tomaten die jij gekocht hebt, zijn heel lekker.', en: 'Those tomatoes you bought are very tasty.' },
    ],
  },
  {
    type: 'drill', title: 'deze or dit?', grammar: ['demonstratives', 'de-het', 'plural'], choices: ['deze', 'dit'],
    instruction: 'First contact. de-word or plural → deze; het-word → dit.',
    items: [
      { nl: '___ tomaat', answer: 'deze' },
      { nl: '___ ei', answer: 'dit' },
      { nl: '___ eieren', answer: 'deze' },
      { nl: '___ vis', answer: 'deze' },
      { nl: '___ recept', answer: 'dit' },
      { nl: '___ fruit', answer: 'dit' },
      { nl: '___ groenten', answer: 'deze' },
      { nl: '___ mes', answer: 'dit' },
      { nl: '___ week', answer: 'deze' },
      { nl: '___ jaar', answer: 'dit' },
    ],
    explanation: 'dit ei, but deze eieren: every plural is a de-word. het recept, het fruit, het mes, het jaar → dit.',
  },
  {
    type: 'drill', title: 'deze, die, dit or dat?', grammar: ['demonstratives', 'dit-is', 'de-het', 'plural', 'kennen-weten', 'imperfect-strong'],
    instruction: 'Type the word. The English tells you near (this, these) or far (that, those).',
    items: [
      { nl: '___ tomaten zijn lekker.', en: 'These tomatoes are tasty.', answer: 'Deze' },
      { nl: '___ ei is niet vers.', en: 'That egg is not fresh.', answer: 'Dat' },
      { nl: 'Proef ___ soep!', en: 'Taste this soup!', answer: 'deze' },
      { nl: '___ mes is te groot.', en: 'This knife is too big.', answer: 'Dit' },
      { nl: 'Wie is ___ man daar?', en: 'Who is that man over there?', answer: 'die' },
      { nl: '___ fruit komt uit Spanje.', en: 'This fruit comes from Spain.', answer: 'Dit' },
      { nl: '___ recept heb ik van mijn moeder gekregen.', en: 'I got this recipe from my mother.', answer: 'Dit' },
      { nl: 'Ken jij ___ verkoper?', en: 'Do you know that seller?', answer: 'die' },
      { nl: '___ week kookt Bram elke dag.', en: 'This week Bram cooks every day.', answer: 'Deze' },
      { nl: '___ jaar woonden Lotte en Tom nog in Antwerpen.', en: 'That year Lotte and Tom still lived in Antwerp.', answer: 'Dat' },
      { nl: '___ zijn mijn vrienden Emma en Jonas.', en: 'These are my friends Emma and Jonas.', answer: 'Dit' },
      { nl: 'Welke vis wil je? — ___ daar.', en: 'That one over there.', answer: 'Die' },
    ],
    explanation: 'Dit zijn mijn vrienden: presenting takes dit, even with a plural. Die daar: de vis, far away. Dat jaar: het jaar, back then.',
  },
  {
    type: 'drill', title: 'welk or welke?', grammar: ['demonstratives', 'question-word', 'de-het', 'superlative', 'days-op-om'], task: 'welk or welke',
    instruction: 'Type welk or welke. welk only before a het-word in the singular.',
    items: [
      { nl: '___ tomaten wil je?', answer: 'Welke' },
      { nl: '___ mes neem jij?', answer: 'Welk' },
      { nl: '___ vis is vandaag vers?', answer: 'Welke' },
      { nl: '___ fruit eet Noor graag?', answer: 'Welk' },
      { nl: '___ recept is het makkelijkst?', answer: 'Welk' },
      { nl: '___ eieren zijn het goedkoopst?', answer: 'Welke' },
      { nl: 'In ___ ziekenhuis werkt Tom?', answer: 'welk' },
      { nl: 'Op ___ dag is er markt in Leuven?', answer: 'welke' },
    ],
    explanation: 'het mes, het fruit, het recept, het ziekenhuis → welk. de vis, de dag and every plural → welke.',
  },
  {
    type: 'drill', title: 'Say it in Dutch: this one, that one, which?', grammar: ['demonstratives', 'adjective-e', 'comparative', 'superlative', 'relative-clause', 'possessives', 'van-voor-bij', 'hoeven-te'],
    instruction: 'Translate. “You” is one person.',
    items: [
      { en: 'These are my friends.', answer: 'Dit zijn mijn vrienden.' },
      { en: 'Which tomatoes do you want? — These.', answer: 'Welke tomaten wil jij? Deze.', accept: ['Welke tomaten wil jij? Deze hier.'] },
      { en: 'This fresh egg is for Lotte.', answer: 'Dit verse ei is voor Lotte.' },
      { en: 'That big knife is too heavy.', answer: 'Dat grote mes is te zwaar.' },
      { en: 'Those tomatoes are cheaper than these.', answer: 'Die tomaten zijn goedkoper dan deze.' },
      { en: 'Which recipe is the easiest?', answer: 'Welk recept is het makkelijkst?', accept: ['Welk recept is het makkelijkste?'] },
      { en: 'This is the soup that Bram has made.', answer: 'Dit is de soep die Bram gemaakt heeft.', accept: ['Dit is de soep die Bram heeft gemaakt.'] },
      { en: 'That was a good year.', answer: 'Dat was een goed jaar.' },
      { en: 'Is this your knife? — No, that is Lotte’s knife.', answer: 'Is dit jouw mes? Nee, dat is het mes van Lotte.', accept: ['Is dit je mes? Nee, dat is het mes van Lotte.'] },
      { en: 'This week Bram doesn’t have to go to Brussels.', answer: 'Deze week hoeft Bram niet naar Brussel.', accept: ['Deze week hoeft Bram niet naar Brussel te gaan.', 'Bram hoeft deze week niet naar Brussel.', 'Bram hoeft deze week niet naar Brussel te gaan.'] },
    ],
    explanation: 'dit verse ei, dat grote mes: -e after every demonstrative. een goed jaar: een + het-word, no -e. het mes van Lotte: “Lotte’s” is van + name. Dit is de soep die …: dit presents, die links the clause.',
  },
  {
    type: 'arrange', title: 'These or those?', grammar: ['demonstratives', 'superlative'],
    instruction: 'Build: “Which tomatoes are the tastiest, these or those?” Two tiles are traps.',
    nl: 'Welke tomaten zijn het lekkerst, deze of die?', en: 'Which tomatoes are the tastiest, these or those?', image: 'vegetables', distractors: ['welk', 'dit'],
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', layout: 'table', title: 'Every verb you know, part one', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'zijn', 'hebben', 'gaan', 'modals', 'dt-rule', 'reflexive', 'zullen-future'],
    instruction: 'Verbs from lessons 1 to 17, with the people of the market. The small word under each person is the verb. Type the present-tense form; for a reflexive verb, only the verb.',
    items: [
      { label: 'ik', gloss: 'zijn', answer: 'ben' },
      { label: 'de verkoopster', gloss: 'she · hebben', answer: 'heeft' },
      { label: 'Tom', gloss: 'he · wonen', answer: 'woont' },
      { label: 'de kat', gloss: 'it · zitten', answer: 'zit' },
      { label: 'Max', gloss: 'he · slapen', answer: 'slaapt' },
      { label: 'zij', gloss: 'she · lezen', answer: 'leest' },
      { label: 'hij', gloss: 'eten', answer: 'eet' },
      { label: 'ik', gloss: 'schrijven', answer: 'schrijf' },
      { label: 'jij', gloss: 'gaan', answer: 'gaat' },
      { label: 'jij', gloss: 'kunnen', answer: 'kunt', accept: ['kan'] },
      { label: 'de verkoper', gloss: 'he · rijden', answer: 'rijdt' },
      { label: 'zij', gloss: 'she · vinden', answer: 'vindt' },
      { label: 'jij', gloss: 'weten', answer: 'weet' },
      { label: 'ik', gloss: 'vragen', answer: 'vraag' },
      { label: 'de soep', gloss: 'it · staan', answer: 'staat' },
      { label: 'jij', gloss: 'nemen', answer: 'neemt' },
      { label: 'hij', gloss: 'reizen', answer: 'reist' },
      { label: 'Tom', gloss: 'he · zich voelen', answer: 'voelt' },
      { label: 'ik', gloss: 'zich herinneren', answer: 'herinner' },
      { label: 'hij', gloss: 'zich haasten', answer: 'haast' },
      { label: 'jij', gloss: 'zullen', answer: 'zult', accept: ['zal'] },
      { label: 'ik', gloss: 'vliegen', answer: 'vlieg' },
    ],
    explanation: 'zit (one t), slaapt (double a back), leest and schrijf (z → s, v → f), eet and weet (no second t), rijdt and vindt (d + t), reist (reizen: z → s), herinner (no double r), haast (the stem already ends in t), jij zult.',
  },
  {
    type: 'drill', layout: 'table', title: 'Every verb you know, part two', grammar: ['present-regular', 'spelling-stem', 'spelling-z-s', 'subject-pronouns', 'position-verbs', 'verb-preposition'],
    instruction: 'Verbs from lessons 17 to 23. Type the present-tense form.',
    items: [
      { label: 'jij', gloss: 'proberen', answer: 'probeert' },
      { label: 'de markt', gloss: 'it · beginnen', answer: 'begint' },
      { label: 'jij', gloss: 'kennen', answer: 'kent' },
      { label: 'hij', gloss: 'ontmoeten', answer: 'ontmoet' },
      { label: 'ik', gloss: 'krijgen', answer: 'krijg' },
      { label: 'zij', gloss: 'she · sturen', answer: 'stuurt' },
      { label: 'hij', gloss: 'wensen', answer: 'wenst' },
      { label: 'jij', gloss: 'verrassen', answer: 'verrast' },
      { label: 'het mes', gloss: 'it · liggen', answer: 'ligt' },
      { label: 'ik', gloss: 'leggen', answer: 'leg' },
      { label: 'hij', gloss: 'zetten', answer: 'zet' },
      { label: 'de lamp', gloss: 'it · hangen', answer: 'hangt' },
      { label: 'Tom', gloss: 'he · verhuizen', answer: 'verhuist' },
      { label: 'ik', gloss: 'betalen', answer: 'betaal' },
      { label: 'jij', gloss: 'huren', answer: 'huurt' },
      { label: 'hij', gloss: 'zoeken', answer: 'zoekt' },
      { label: 'zij', gloss: 'she · verdienen', answer: 'verdient' },
      { label: 'ik', gloss: 'sparen', answer: 'spaar' },
      { label: 'jij', gloss: 'lenen', answer: 'leent' },
      { label: 'ik', gloss: 'houden', answer: 'hou', accept: ['houd'] },
      { label: 'Tom', gloss: 'he · luisteren', answer: 'luistert' },
      { label: 'Bram', gloss: 'he · zorgen', answer: 'zorgt' },
      { label: 'de markt', gloss: 'it · eindigen', answer: 'eindigt' },
    ],
    explanation: 'ontmoet (no extra t), verrast (verras + t: one s at the end of the stem), verhuist (z → s), betaal, spaar, huurt (long vowel, two letters in a closed syllable), ik hou (in speech; ik houd is the written form).',
  },
  {
    type: 'drill', title: 'Past, present and future at the market', grammar: ['imperfect-weak', 'imperfect-strong', 'perfect-hebben', 'participle', 'zullen-future', 'toen-past', 'time-conjunctions'],
    instruction: 'Type the verb given in the tense the sentence needs. The time word and the English decide. One word only.',
    items: [
      { nl: 'Vroeger ___ Bram elke zaterdag met zijn moeder naar de markt.', cue: 'gaan', en: 'Bram used to go …', answer: 'ging' },
      { nl: 'Toen Bram klein was, ___ hij nooit vis.', cue: 'eten', answer: 'at' },
      { nl: 'Vorige week ___ het project van Lotte.', cue: 'eindigen', en: 'Last week Lotte’s project ended.', answer: 'eindigde' },
      { nl: 'Wat ___ de verkoopster?', cue: 'zeggen', en: 'What did the seller say?', answer: 'zei' },
      { nl: 'Bram ___ niet dat Emma geen vlees eet.', cue: 'weten', en: 'Bram didn’t know that Emma doesn’t eat meat.', answer: 'wist' },
      { nl: 'Lotte heeft zes eieren ___.', cue: 'kopen', answer: 'gekocht' },
      { nl: 'Wij hebben de verkoper ___ of de vis vers is.', cue: 'vragen', answer: 'gevraagd' },
      { nl: 'Volgende week ___ wij weer naar de markt gaan.', cue: 'zullen', answer: 'zullen' },
      { nl: 'Terwijl Lotte de wortels ___, viel er een stukje op de vloer.', cue: 'snijden', en: 'While Lotte was cutting the carrots …', answer: 'sneed' },
      { nl: 'Bram ___ het recept niet goed, dus hij belde zijn moeder op.', cue: 'begrijpen', en: 'Bram didn’t understand the recipe well …', answer: 'begreep' },
      { nl: 'Max ___ de vis niet proeven.', cue: 'mogen', en: 'Max wasn’t allowed to taste the fish.', answer: 'mocht' },
      { nl: 'Vroeger ___ Bram zijn moeder in de keuken.', cue: 'helpen', en: 'Bram used to help his mother in the kitchen.', answer: 'hielp' },
    ],
    explanation: 'Strong: ging, at, zei, wist, sneed, begreep, mocht, hielp — learn them as they are. Weak: eindigde (g is not in ’t kofschip). Perfect: gekocht, gevraagd.',
  },
  {
    type: 'drill', title: 'Volume three in the kitchen', grammar: ['object-pronouns', 'indirect-object', 'van-voor-bij', 'position-verbs', 'place-prepositions', 'er-daar-place', 'numbers-big', 'dates', 'er-quantity', 'verb-preposition', 'er-preposition', 'waar-preposition'],
    instruction: 'Every grammar point of lessons 19–23, now at the market and in the kitchen. Type the missing word.',
    items: [
      { nl: 'Lotte geeft ___ een stukje wortel.', en: 'Lotte gives him (Max) a piece of carrot.', answer: 'hem' },
      { nl: 'Waar zijn de eieren? — Ik heb ___ in de keuken gezet.', en: 'I put them in the kitchen.', answer: 'ze' },
      { nl: 'Het mes ___ op de tafel.', cue: 'staan / liggen / hangen', answer: 'ligt' },
      { nl: 'Max ___ onder de tafel.', cue: 'staan / liggen / zitten', en: 'Max is lying under the table.', answer: 'ligt' },
      { nl: 'Bram ___ de pan op de tafel.', cue: 'zetten / leggen', answer: 'zet' },
      { nl: 'Lotte ___ het mes naast de pan.', cue: 'zetten / leggen', answer: 'legt' },
      { nl: 'Hoeveel eieren heb je gekocht? — Ik heb ___ zes gekocht.', answer: 'er' },
      { nl: 'Deze vis kost ___ euro per kilo.', cue: '25', answer: 'vijfentwintig' },
      { nl: 'Bram is jarig op ___ maart.', cue: '14', answer: 'veertien' },
      { nl: 'Max wacht ___ een stukje vlees.', answer: 'op' },
      { nl: 'Hij wacht er al een uur ___.', en: 'He has been waiting for it for an hour.', answer: 'op' },
      { nl: '___ denk je aan? — Aan de soep.', en: 'What are you thinking of?', answer: 'Waar' },
      { nl: 'Tom houdt ___ soep.', en: 'Tom loves soup.', answer: 'van' },
      { nl: 'Vanavond eten Tom, Emma en Jonas ___ Bram en Lotte.', en: 'Tonight Tom, Emma and Jonas are eating at Bram and Lotte’s.', answer: 'bij' },
    ],
    explanation: 'hem for Max, ze for the eggs (things in the plural: ze, never hen). The knife ligt, the pan staat — zetten upright, leggen flat. Ik heb er zes: er stands for “eieren”. wachten op → er … op, waar … aan: the preposition stays at the end.',
  },
  {
    type: 'drill', title: 'While, before, as soon as — whether', grammar: ['time-conjunctions', 'hoewel-zodat', 'of-whether', 'verb-final', 'als-inversion', 'perfect-zijn', 'question-word'],
    instruction: 'Rewrite as the task says. After terwijl, voordat, nadat, zodra, hoewel, zodat, sinds, totdat and of the verb goes to the end; a clause in front is position one.',
    items: [
      { nl: 'Lotte snijdt de groenten. Bram kookt.', task: 'Join with terwijl', answer: 'Lotte snijdt de groenten, terwijl Bram kookt.' },
      { nl: 'De gasten komen. Bram proeft de soep.', task: 'Start with “Voordat de gasten komen,”', answer: 'Voordat de gasten komen, proeft Bram de soep.' },
      { nl: 'Zij zijn op de markt geweest. Zij gaan naar huis.', task: 'Start with “Nadat”', answer: 'Nadat zij op de markt geweest zijn, gaan zij naar huis.', accept: ['Nadat zij op de markt zijn geweest, gaan zij naar huis.'] },
      { nl: 'De soep is klaar. Wij eten.', task: 'Start with “Zodra”', answer: 'Zodra de soep klaar is, eten wij.' },
      { nl: 'Het regent. Zij gaan naar de markt.', task: 'Start with “Hoewel”', answer: 'Hoewel het regent, gaan zij naar de markt.' },
      { nl: 'Emma eet geen vlees. Bram maakt soep zonder vlees.', task: 'Join with dus', answer: 'Emma eet geen vlees, dus Bram maakt soep zonder vlees.' },
      { nl: 'Emma eet geen vlees. Bram maakt soep zonder vlees.', task: 'Start the second sentence with daarom', answer: 'Emma eet geen vlees. Daarom maakt Bram soep zonder vlees.' },
      { nl: 'Haar project is klaar. Lotte heeft weer tijd.', task: 'Start with “Sinds”', answer: 'Sinds haar project klaar is, heeft Lotte weer tijd.' },
      { nl: 'Max wacht onder de tafel. Er valt een stukje wortel.', task: 'Join with totdat', answer: 'Max wacht onder de tafel, totdat er een stukje wortel valt.' },
      { nl: 'Eet Emma vlees?', task: 'Start with “Bram weet niet of”', answer: 'Bram weet niet of Emma vlees eet.' },
      { nl: 'Is de vis vers?', task: 'Start with “Lotte vraagt of”', answer: 'Lotte vraagt of de vis vers is.' },
      { nl: 'Wanneer eindigt de markt?', task: 'Start with “Weet jij wanneer”', answer: 'Weet jij wanneer de markt eindigt?' },
    ],
    explanation: 'Voordat de gasten komen, proeft Bram …: the clause is position one, the verb comes next. dus keeps the normal order; daarom is position one, so the verb follows it. of for a yes/no question inside a sentence, a question word for the others.',
  },
  {
    type: 'drill', title: 'Everything so far, on market day', grammar: ['plural', 'numbers', 'er-is-zijn', 'adjective-e', 'geen-niet', 'geen', 'niet', 'hij-het-things', 'question-word', 'wie-hoe', 'clock-time', 'days-op-om', 'possessives', 'adverb-position', 'perfect-zijn', 'perfect-hebben', 'participle', 'dit-is', 'de-het', 'yes-no-question', 'time-place', 'infinitive-end'],
    instruction: 'Type the missing word. Every grammar point of volumes zero and one, now at the market.',
    items: [
      { nl: 'Op de markt ___ tien kramen.', cue: 'er is / er zijn', answer: 'zijn er' },
      { nl: 'Bram koopt drie ___.', cue: 'ui', answer: 'uien' },
      { nl: 'Wij hebben twee ___ nodig.', cue: 'mes', answer: 'messen' },
      { nl: 'Dit is een ___ mes.', cue: 'groot', answer: 'groot' },
      { nl: 'Dit is het ___ mes van Bram.', cue: 'groot', answer: 'grote' },
      { nl: 'Lotte koopt ___ vlees.', en: 'Lotte doesn’t buy any meat.', answer: 'geen' },
      { nl: 'De vis is ___ duur.', en: 'The fish is not expensive.', answer: 'niet' },
      { nl: 'Ik neem de vis. ___ komt uit Oostende.', cue: 'hij / het', answer: 'Hij' },
      { nl: 'Ik neem het ei. ___ is vers.', cue: 'hij / het', answer: 'Het' },
      { nl: '___ heet de verkoopster?', en: 'What is the seller called?', answer: 'Hoe' },
      { nl: 'De markt begint ___ acht uur.', cue: 'op / om', answer: 'om' },
      { nl: 'Wij gaan ___ zaterdag naar de markt.', cue: 'op / om', answer: 'op' },
      { nl: 'Bram en Lotte eten met ___ vrienden.', en: 'with their friends', answer: 'hun' },
      { nl: 'Bram drinkt op de markt ___ koffie.', en: 'Bram always drinks coffee at the market.', answer: 'altijd' },
      { nl: 'Wij zijn gisteren naar de markt ___.', cue: 'gaan', answer: 'gegaan' },
      { image: 'fish', nl: 'Wat is dit?', answer: 'Dit is een vis.', accept: ['Het is een vis.', 'Dit is vis.', 'Dit is de vis.'] },
    ],
    explanation: 'Op de markt zijn er …: a place first, then the verb, then er. een groot mes (een + het-word) but het grote mes. geen vlees, niet duur. de vis → hij, het ei → het. om + clock time, op + day.',
  },
  {
    type: 'drill', title: 'Volume two, at the market', grammar: ['separable-perfect', 'separable-together', 'comparative', 'superlative', 'dan-als', 'imperfect-strong', 'toen-past', 'imperative', 'reflexive', 'zullen-future', 'te-infinitive', 'relative-clause', 'pijn-hebben', 'over-geleden', 'kennen-weten', 'participle-no-ge'],
    instruction: 'Every grammar point of lessons 13–18. Rewrite as the task says, or type the missing word.',
    items: [
      { nl: 'Lotte neemt een grote tas mee.', task: 'Use the perfect', answer: 'Lotte heeft een grote tas meegenomen.' },
      { nl: 'Bram staat om zeven uur op.', task: 'Start with “Bram moet”', answer: 'Bram moet om zeven uur opstaan.' },
      { nl: 'De tomaten uit Spanje zijn goedkoop. De tomaten uit België zijn duur.', task: 'One sentence: “De tomaten uit Spanje zijn … dan …”', answer: 'De tomaten uit Spanje zijn goedkoper dan de tomaten uit België.', accept: ['De tomaten uit Spanje zijn goedkoper dan die uit België.'] },
      { nl: 'Deze tomaten zijn lekker.', task: 'Use the superlative: “Deze tomaten zijn het …”', answer: 'Deze tomaten zijn het lekkerst.' },
      { nl: 'De soep van Bram is lekker. De soep van zijn moeder is ook lekker.', task: 'Use “even … als”: “De soep van Bram is …”', answer: 'De soep van Bram is even lekker als de soep van zijn moeder.', accept: ['De soep van Bram is even lekker als die van zijn moeder.'] },
      { nl: 'Bram is klein. Zijn moeder maakt elke week soep.', task: 'Start with “Toen Bram klein was,” — simple past', answer: 'Toen Bram klein was, maakte zijn moeder elke week soep.' },
      { nl: 'Jij snijdt de groenten voorzichtig.', task: 'Make it an order', answer: 'Snijd de groenten voorzichtig!' },
      { nl: 'Bram haast zich naar de markt.', task: 'Change Bram to wij', answer: 'Wij haasten ons naar de markt.' },
      { nl: 'Ik bak morgen de vis.', task: 'Use zullen', answer: 'Ik zal morgen de vis bakken.' },
      { nl: 'Bram kookt beter.', task: 'Start with “Bram probeert”', answer: 'Bram probeert beter te koken.' },
      { nl: 'Dit is het recept. Bram heeft het van zijn moeder gekregen.', task: 'Join with die or dat', answer: 'Dit is het recept dat Bram van zijn moeder gekregen heeft.', accept: ['Dit is het recept dat Bram van zijn moeder heeft gekregen.'] },
      { nl: 'Twee weken geleden zijn wij naar de markt gegaan.', task: 'Make it future: “over”, present tense', answer: 'Over twee weken gaan wij naar de markt.' },
      { nl: 'Bram ___ de verkoper al jaren.', cue: 'kennen / weten', answer: 'kent' },
      { nl: 'Wij hebben de verkoopster op de markt ___.', cue: 'ontmoeten', answer: 'ontmoet' },
    ],
    explanation: 'meegenomen: ge- in the middle; moet … opstaan: together again after a modal. goedkoper dan, even lekker als, het lekkerst. Snijd …!: the stem. dat Bram … gekregen heeft: het recept → dat. ontmoet: no ge-, no extra t.',
  },
  {
    type: 'arrange', title: 'While Lotte cuts', grammar: ['time-conjunctions', 'position-verbs', 'place-prepositions'],
    instruction: 'Build: “While Lotte is cutting the vegetables, Max lies under the table.” Two tiles are traps.',
    nl: 'Terwijl Lotte de groenten snijdt, ligt Max onder de tafel.', en: 'While Lotte is cutting the vegetables, Max lies under the table.', image: 'dog-big', distractors: ['legt', 'snijd'],
  },

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Het recept van moeder', image: 'soup', grammar: ['imperative', 'hoeven-te', 'om-te', 'demonstratives', 'time-conjunctions', 'waar-preposition', 'toen-past', 'indirect-object'],
    instruction: 'A written text. On Friday a card came in the post from Bram’s mother in Ghent, with her recipe. Read it, listen to every line, then read it again without the English. Find the imperatives, the om-group and every hoeven.',
    lines: [
      { nl: 'Lieve Bram,', en: 'Dear Bram,', image: 'card' },
      { nl: 'Hier is het recept waar je om vroeg. Ik heb het van mijn moeder gekregen, en toen jij klein was, vond je deze soep heel lekker.', en: 'Here is the recipe you asked for. I got it from my mother, and when you were little, you loved this soup.', image: 'mother' },
      { nl: 'Groentesoep voor zes mensen', en: 'Vegetable soup for six people', image: 'soup' },
      { nl: 'Je hebt nodig: twee uien, drie wortels, één prei, vier aardappelen en een halve kilo tomaten.', en: 'You need: two onions, three carrots, one leek, four potatoes and half a kilo of tomatoes.', image: 'vegetables' },
      { nl: 'En ook: water, zout en peper.', en: 'And also: water, salt and pepper.', image: 'water' },
      { nl: 'Snijd eerst de uien in kleine stukjes en bak ze vijf minuten in een grote pan.', en: 'First cut the onions into small pieces and fry them in a big pan for five minutes.', image: 'man-cutting' },
      { nl: 'Snijd daarna de wortels, de prei en de aardappelen in stukken.', en: 'Then cut the carrots, the leek and the potatoes into pieces.', image: 'vegetables' },
      { nl: 'De tomaten hoef je niet klein te snijden: grote stukken zijn genoeg.', en: 'You don’t need to cut the tomatoes small: big pieces are enough.', image: 'vegetables' },
      { nl: 'Doe de groenten in de pan en doe er water bij.', en: 'Put the vegetables in the pan and add water.', image: 'soup' },
      { nl: 'Kook de soep twintig minuten, totdat de aardappelen klaar zijn.', en: 'Cook the soup for twenty minutes, until the potatoes are done.', image: 'soup' },
      { nl: 'Doe er dan zout en peper bij, en proef de soep voordat je ze op tafel zet.', en: 'Then add salt and pepper, and taste the soup before you put it on the table.', image: 'soup' },
      { nl: 'Je hoeft er geen vlees in te doen: zonder vlees is deze soep ook lekker, en heel gezond.', en: 'You don’t have to put any meat in it: without meat this soup is tasty too, and very healthy.', image: 'soup' },
      { nl: 'Neem een goed mes om de groenten te snijden, en snijd voorzichtig! Vroeger sneed jij altijd te snel.', en: 'Take a good knife to cut the vegetables, and cut carefully! You always used to cut too fast.', image: 'man-cutting' },
      { nl: 'Je hoeft me niet op te bellen: dit recept is heel makkelijk.', en: 'You don’t need to ring me: this recipe is very easy.', image: 'phone' },
      { nl: 'Ik hoop dat jullie vrienden de soep lekker vinden. En geef Max een stukje wortel van mij!', en: 'I hope your friends like the soup. And give Max a piece of carrot from me!', image: 'dog-big' },
      { nl: 'Je moeder', en: 'Your mother', image: 'mother' },
    ],
  },
  {
    type: 'drill', title: 'About the recipe: answer in full', grammar: ['hoeven-te', 'om-te', 'er-quantity', 'indirect-object', 'modals', 'van-voor-bij'],
    instruction: 'Answer each question about the card with a complete sentence. When the task says “with hoeven”, use it.',
    items: [
      { nl: 'Van wie heeft de moeder van Bram het recept gekregen?', answer: 'Zij heeft het recept van haar moeder gekregen.', accept: ['Zij heeft het van haar moeder gekregen.', 'De moeder van Bram heeft het recept van haar moeder gekregen.', 'Van haar moeder.', 'Zij heeft het recept van de oma van Bram gekregen.', 'Van de oma van Bram.'] },
      { nl: 'Voor hoeveel mensen is de soep?', answer: 'De soep is voor zes mensen.', accept: ['Het recept is voor zes mensen.', 'Zij is voor zes mensen.', 'Voor zes mensen.'] },
      { nl: 'Hoeveel tomaten heb je nodig?', answer: 'Je hebt een halve kilo tomaten nodig.', accept: ['Een halve kilo.', 'Een halve kilo tomaten.'] },
      { nl: 'Wat moet je eerst doen?', answer: 'Je moet eerst de uien in kleine stukjes snijden.', accept: ['Eerst moet je de uien in kleine stukjes snijden.', 'Je moet de uien eerst in kleine stukjes snijden.', 'Je moet eerst de uien snijden.', 'Eerst moet je de uien snijden.', 'Snijd eerst de uien in kleine stukjes.', 'De uien in kleine stukjes snijden.'] },
      { nl: 'Moet je de tomaten klein snijden?', task: 'Answer with hoeven', answer: 'Nee, je hoeft de tomaten niet klein te snijden.', accept: ['Nee, de tomaten hoef je niet klein te snijden.'] },
      { nl: 'Hoe lang moet de soep koken?', answer: 'De soep moet twintig minuten koken.', accept: ['Zij moet twintig minuten koken.', 'Twintig minuten.', 'De soep moet twintig minuten koken, totdat de aardappelen klaar zijn.'] },
      { nl: 'Wat moet je doen voordat je de soep op tafel zet?', answer: 'Je moet de soep proeven.', accept: ['Je moet de soep proeven voordat je ze op tafel zet.', 'Je moet zout en peper erbij doen en de soep proeven.', 'Proeven.', 'De soep proeven.'] },
      { nl: 'Moet er vlees in de soep?', task: 'Answer with hoeven', answer: 'Nee, je hoeft er geen vlees in te doen.', accept: ['Nee, je hoeft geen vlees in de soep te doen.', 'Nee, er hoeft geen vlees in de soep.', 'Nee, er hoeft geen vlees in.'] },
      { nl: 'Waarom heb je een goed mes nodig?', answer: 'Om de groenten te snijden.', accept: ['Je hebt een goed mes nodig om de groenten te snijden.'] },
      { nl: 'Wat moet Bram aan Max geven?', answer: 'Hij moet Max een stukje wortel geven.', accept: ['Bram moet Max een stukje wortel geven.', 'Hij moet hem een stukje wortel geven.', 'Hij moet een stukje wortel aan Max geven.', 'Een stukje wortel.'] },
    ],
  },
  {
    type: 'story', title: 'Zaterdag op de markt', image: 'market', grammar: ['om-te', 'demonstratives', 'hoeven-te', 'time-conjunctions', 'hoewel-zodat', 'superlative', 'er-daar-place', 'waar-preposition', 'zitten-te-free'].filter((g) => g !== 'zitten-te-free'),
    instruction: 'Saturday, from the market to the soup. Read and listen to every line, then read it again without the English. Find every deze, die, dit, welke — and every om … te.',
    lines: [
      { nl: 'Het is zaterdag, en het is lente in Leuven. Sinds haar project klaar is, heeft Lotte weer tijd.', en: 'It is Saturday, and it is spring in Leuven. Since her project has been finished, Lotte has time again.', image: 'market' },
      { nl: 'Om negen uur gaan Bram en Lotte met Max naar de markt om boodschappen te doen. Hoewel het een beetje regent, zijn er veel mensen.', en: 'At nine o’clock Bram and Lotte go to the market with Max to do the shopping. Although it is raining a little, there are lots of people.', image: 'market' },
      { speaker: 'Lotte', nl: 'Wat hebben we nodig voor de soep van vanavond?', en: 'What do we need for tonight’s soup?', image: 'woman' },
      { speaker: 'Bram', nl: 'Uien, wortels, aardappelen en tomaten. Prei hebben we nog thuis. Het recept van mijn moeder is heel makkelijk.', en: 'Onions, carrots, potatoes and tomatoes. We still have leeks at home. My mother’s recipe is very easy.', image: 'vegetables' },
      { speaker: 'De verkoopster', nl: 'Dag! Wat mag het zijn?', en: 'Hello! What can I get you?', image: 'market' },
      { speaker: 'Lotte', nl: 'Twee kilo aardappelen, drie uien en een kilo wortels, graag.', en: 'Two kilos of potatoes, three onions and a kilo of carrots, please.', image: 'vegetables' },
      { speaker: 'De verkoopster', nl: 'En tomaten? Deze komen uit België, die daar uit Spanje.', en: 'And tomatoes? These come from Belgium, those over there from Spain.', image: 'vegetables' },
      { speaker: 'Bram', nl: 'Welke zijn het lekkerst?', en: 'Which ones are the tastiest?', image: 'man' },
      { speaker: 'De verkoopster', nl: 'Deze hier. Ze zijn wat duurder, maar vandaag zijn ze heel vers. Proef maar!', en: 'These here. They are a bit more expensive, but today they are very fresh. Go on, taste one!', image: 'vegetables' },
      { speaker: 'Lotte', nl: 'Die zijn heel lekker! Een halve kilo van deze, graag.', en: 'They are really tasty! Half a kilo of these, please.', image: 'woman-buying' },
      { nl: 'Terwijl Lotte betaalt, kijkt Bram naar het kraam met vis. Morgen wil hij vis bakken.', en: 'While Lotte pays, Bram looks at the fish stall. Tomorrow he wants to fry fish.', image: 'fish' },
      { speaker: 'Bram', nl: 'Welke vis is vandaag het best?', en: 'Which fish is best today?', image: 'fish' },
      { speaker: 'De verkoper', nl: 'Mijn vis is altijd vers! Maar deze komt vandaag uit Oostende.', en: 'My fish is always fresh! But this one comes from Ostend today.', image: 'fish' },
      { speaker: 'Bram', nl: 'Uit Oostende? Daar ben ik opgegroeid! Twee stukken van die vis, graag.', en: 'From Ostend? That’s where I grew up! Two pieces of that fish, please.', image: 'sea' },
      { nl: 'Max wil de vis ook proeven, maar dat mag niet. Lotte koopt nog appels en zes eieren voor het ontbijt, en dan gaan zij naar huis.', en: 'Max wants to taste the fish too, but he isn’t allowed. Lotte buys some apples and six eggs for breakfast, and then they go home.', image: 'woman-buying' },
      { nl: 'Om zes uur staat Bram in de keuken. Lotte snijdt de groenten, heel voorzichtig, want Max ligt onder de tafel te wachten.', en: 'At six o’clock Bram is in the kitchen. Lotte cuts the vegetables, very carefully, because Max is lying under the table, waiting.', image: 'kitchen' },
      { speaker: 'Lotte', nl: 'Max, waar wacht jij op? Er zit geen vlees in deze soep!', en: 'Max, what are you waiting for? There is no meat in this soup!', image: 'dog-big' },
      { speaker: 'Bram', nl: 'Hij wacht op een stukje eten. Voor Max is een wortel ook goed.', en: 'He is waiting for a bit of food. For Max a carrot will do too.', image: 'man' },
      { nl: 'En ja: er valt een stukje wortel op de vloer. Max eet het meteen, zonder te kijken.', en: 'And yes: a piece of carrot falls on the floor. Max eats it at once, without looking.', image: 'dog-big' },
      { nl: 'Om zeven uur komen Tom, Emma en Jonas. Bram heeft gezegd dat zij geen eten hoeven mee te nemen, maar Emma heeft bloemen meegenomen.', en: 'At seven Tom, Emma and Jonas arrive. Bram said they didn’t have to bring any food, but Emma has brought flowers.', image: 'flowers' },
      { speaker: 'Bram', nl: 'Bloemen? Dank je wel, Emma, maar dat had niet gehoeven!', en: 'Flowers? Thank you, Emma, but you shouldn’t have!', image: 'flowers' },
      { speaker: 'Emma', nl: 'Ik weet het. Maar ik kom niet graag zonder cadeau.', en: 'I know. But I don’t like coming without a present.', image: 'friends' },
      { speaker: 'Tom', nl: 'Ik heb honger! Na mijn nachtdienst heb ik tot vier uur geslapen.', en: 'I’m hungry! After my night shift I slept until four.', image: 'friends' },
      { speaker: 'Bram', nl: 'Dit is de soep van mijn moeder. Smakelijk!', en: 'This is my mother’s soup. Enjoy!', image: 'soup' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'inversion'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the story. Answer without looking back.',
    items: [
      { nl: 'Regent het een beetje?', answer: 'Ja' },
      { nl: 'Moeten Bram en Lotte prei kopen?', answer: 'Nee' },
      { nl: 'Komen de lekkerste tomaten uit Spanje?', answer: 'Nee' },
      { nl: 'Is Bram in Oostende opgegroeid?', answer: 'Ja' },
      { nl: 'Mag Max de vis proeven?', answer: 'Nee' },
      { nl: 'Zit er vlees in de soep?', answer: 'Nee' },
      { nl: 'Heeft Emma bloemen meegenomen?', answer: 'Ja' },
    ],
  },
  {
    type: 'drill', title: 'Answer in full', grammar: ['om-te', 'hoeven-te', 'want-omdat', 'verb-final', 'demonstratives', 'waar-preposition', 'time-conjunctions', 'perfect-hebben'],
    instruction: 'Answer each question about the story with a complete sentence.',
    items: [
      { nl: 'Waarom gaan Bram en Lotte naar de markt?', answer: 'Zij gaan naar de markt om boodschappen te doen.', accept: ['Bram en Lotte gaan naar de markt om boodschappen te doen.', 'Om boodschappen te doen.', 'Zij gaan naar de markt om groenten te kopen.', 'Om groenten te kopen.', 'Om groenten, fruit en vis te kopen.'] },
      { nl: 'Waarom hoeven zij geen prei te kopen?', answer: 'Omdat zij nog prei thuis hebben.', accept: ['Omdat zij thuis nog prei hebben.', 'Zij hebben nog prei thuis.', 'Zij hebben thuis nog prei.', 'Want zij hebben nog prei thuis.', 'Want zij hebben thuis nog prei.'] },
      { nl: 'Welke tomaten koopt Lotte?', answer: 'Zij koopt de tomaten uit België.', accept: ['Lotte koopt de tomaten uit België.', 'Zij koopt een halve kilo tomaten uit België.', 'Zij koopt de lekkerste tomaten.', 'De tomaten uit België.'] },
      { nl: 'Wat doet Bram terwijl Lotte betaalt?', answer: 'Hij kijkt naar het kraam met vis.', accept: ['Bram kijkt naar het kraam met vis.', 'Terwijl Lotte betaalt, kijkt Bram naar het kraam met vis.', 'Terwijl Lotte betaalt, kijkt hij naar het kraam met vis.'] },
      { nl: 'Uit welke stad komt de vis?', answer: 'De vis komt uit Oostende.', accept: ['Hij komt uit Oostende.', 'Uit Oostende.'] },
      { nl: 'Wat vertelt Bram over Oostende?', answer: 'Hij is daar opgegroeid.', accept: ['Bram is daar opgegroeid.', 'Hij is in Oostende opgegroeid.', 'Bram is in Oostende opgegroeid.', 'Daar is hij opgegroeid.'] },
      { nl: 'Waarom snijdt Lotte de groenten heel voorzichtig?', answer: 'Omdat Max onder de tafel ligt te wachten.', accept: ['Omdat Max onder de tafel ligt.', 'Want Max ligt onder de tafel te wachten.', 'Want Max ligt onder de tafel.', 'Max ligt onder de tafel te wachten.'] },
      { nl: 'Waar wacht Max op?', answer: 'Hij wacht op een stukje eten.', accept: ['Max wacht op een stukje eten.', 'Op een stukje eten.'] },
      { nl: 'Wat zegt Bram als Emma bloemen meeneemt?', answer: 'Dank je wel, Emma, maar dat had niet gehoeven!', accept: ['Hij zegt: dank je wel, Emma, maar dat had niet gehoeven!', 'Bram zegt: dank je wel, Emma, maar dat had niet gehoeven!', 'Dank je wel, maar dat had niet gehoeven!', 'Dat had niet gehoeven!'] },
      { nl: 'Tot hoe laat heeft Tom geslapen?', answer: 'Hij heeft tot vier uur geslapen.', accept: ['Tom heeft tot vier uur geslapen.', 'Tot vier uur.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['om-te', 'hoeven-te', 'demonstratives', 'dit-is'],
    instruction: 'Listen to each sentence and write it. Use slow audio if you need it; capitals and punctuation do not matter.',
    items: [
      { listen: 'Zij gaan naar de markt om groenten te kopen.' },
      { listen: 'Welke tomaten zijn het lekkerst?' },
      { listen: 'Dit zijn mijn vrienden Emma en Jonas.' },
      { listen: 'Jullie hoeven geen eten mee te nemen.' },
      { listen: 'Lotte snijdt de groenten heel voorzichtig.' },
      { listen: 'Een halve kilo tomaten kost twee euro.' },
      { listen: 'Max eet de wortel zonder te kijken.' },
      { listen: 'Hoef jij morgen niet te werken?' },
      { listen: 'Deze eieren zijn vers.' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['om-te', 'hoeven-te', 'demonstratives', 'time-conjunctions', 'hoewel-zodat', 'of-whether', 'relative-clause', 'position-verbs', 'separable-perfect', 'v2-inversion', 'want-omdat'],
    instruction: 'Translate. Long sentences now: build them clause by clause. “You” is one person unless it says plural.',
    items: [
      { en: 'On Saturday Bram and Lotte go to the market to buy vegetables, fruit and fish.', answer: 'Op zaterdag gaan Bram en Lotte naar de markt om groenten, fruit en vis te kopen.', accept: ['Zaterdag gaan Bram en Lotte naar de markt om groenten, fruit en vis te kopen.', 'Bram en Lotte gaan op zaterdag naar de markt om groenten, fruit en vis te kopen.', 'Bram en Lotte gaan zaterdag naar de markt om groenten, fruit en vis te kopen.'] },
      { en: 'Which tomatoes are the tastiest, these or those?', answer: 'Welke tomaten zijn het lekkerst, deze of die?', accept: ['Welke tomaten zijn het lekkerste, deze of die?'] },
      { en: 'Bram rang his mother to ask for her recipe. (perfect)', answer: 'Bram heeft zijn moeder opgebeld om haar recept te vragen.', accept: ['Bram heeft zijn moeder opgebeld om het recept te vragen.'] },
      { en: 'You (plural) don’t have to bring any food, because Bram is cooking. (use want)', answer: 'Jullie hoeven geen eten mee te nemen, want Bram kookt.' },
      { en: 'While Lotte cuts the vegetables, Max lies under the table.', answer: 'Terwijl Lotte de groenten snijdt, ligt Max onder de tafel.', accept: ['Max ligt onder de tafel, terwijl Lotte de groenten snijdt.'] },
      { en: 'This egg is not fresh; take that one.', answer: 'Dit ei is niet vers; neem dat.', accept: ['Dit ei is niet vers; neem dat ei.', 'Dit ei is niet vers; neem dat daar.'] },
      { en: 'Bram cooks so that Lotte doesn’t have to cook.', answer: 'Bram kookt, zodat Lotte niet hoeft te koken.', accept: ['Bram kookt, zodat Lotte niet te koken hoeft.'] },
      { en: 'Max is not allowed to eat meat from the table.', answer: 'Max mag geen vlees van de tafel eten.' },
      { en: 'These are the vegetables that we bought at the market.', answer: 'Dit zijn de groenten die wij op de markt gekocht hebben.', accept: ['Dit zijn de groenten die wij op de markt hebben gekocht.'] },
      { en: 'To buy good fish, they go to the market early.', answer: 'Om goede vis te kopen, gaan zij vroeg naar de markt.', accept: ['Zij gaan vroeg naar de markt om goede vis te kopen.'] },
      { en: 'I don’t know whether Emma eats meat.', answer: 'Ik weet niet of Emma vlees eet.' },
      { en: 'As soon as the soup is ready, we eat.', answer: 'Zodra de soep klaar is, eten wij.', accept: ['Zodra de soep klaar is, gaan wij eten.', 'Zodra de soep klaar is, zullen wij eten.', 'Wij eten zodra de soep klaar is.'] },
      { en: 'Although the fish is expensive, Bram buys two pieces.', answer: 'Hoewel de vis duur is, koopt Bram twee stukken.', accept: ['Bram koopt twee stukken, hoewel de vis duur is.'] },
      { en: 'Tom slept until four o’clock after his night shift. (perfect)', answer: 'Tom heeft na zijn nachtdienst tot vier uur geslapen.', accept: ['Na zijn nachtdienst heeft Tom tot vier uur geslapen.'] },
    ],
  },
  {
    type: 'drill', title: 'The whole lesson in one round', grammar: ['om-te', 'hoeven-te', 'demonstratives', 'dt-rule', 'perfect-zijn', 'hoewel-zodat', 'dit-is', 'inversion', 'separable'],
    instruction: 'A final, demanding round: every point of this lesson, mixed with what came before. Type every answer.',
    items: [
      { nl: 'Ik ___ de prei.', cue: 'snijden', answer: 'snijd' },
      { nl: '___ jij de uien?', cue: 'snijden', answer: 'Snijd' },
      { nl: 'Hij ___ de soep.', cue: 'proeven', answer: 'proeft' },
      { nl: 'Er is een ei op de vloer ___.', cue: 'vallen', answer: 'gevallen' },
      { nl: 'Jij ___ niet te koken.', cue: 'hoeven', answer: 'hoeft' },
      { nl: '___ tomaten zijn lekker.', en: 'These tomatoes …', answer: 'Deze' },
      { nl: '___ ei is vers.', en: 'This egg …', answer: 'Dit' },
      { nl: '___ mes neem jij?', en: 'Which knife …', answer: 'Welk' },
      { nl: '___ zijn mijn vrienden.', en: 'These are my friends.', answer: 'Dit' },
      { nl: 'Bram gaat naar de markt. Hij wil vis kopen.', task: 'Join with om … te', answer: 'Bram gaat naar de markt om vis te kopen.' },
      { nl: 'Moet ik brood meenemen?', task: 'Answer “Nee” with hoeven', answer: 'Nee, je hoeft geen brood mee te nemen.' },
      { nl: 'Bram kookt. Lotte kan studeren.', task: 'Join with zodat', answer: 'Bram kookt, zodat Lotte kan studeren.', accept: ['Bram kookt, zodat Lotte studeren kan.'] },
      { en: 'Max eats the carrot without looking.', answer: 'Max eet de wortel zonder te kijken.' },
      { en: 'Which fish is fresh today?', answer: 'Welke vis is vandaag vers?' },
      { image: 'soup', nl: 'Wat is dit?', answer: 'Dit is soep.', accept: ['Dit is de soep.', 'Het is soep.'] },
      { en: 'You don’t have to get up early tomorrow.', answer: 'Jij hoeft morgen niet vroeg op te staan.', accept: ['Morgen hoef jij niet vroeg op te staan.'] },
      { listen: 'Om goede vis te kopen, gaan zij vroeg naar de markt.' },
    ],
  },
  {
    type: 'complete', title: 'Volume three: done',
    instruction: 'om … te for a purpose, zonder … te, niet hoeven te — and deze, die, dit, dat and welke to point at exactly what you mean. Volume three is finished: you can give and get, place things, count money, talk about what you like and wait for, and join your sentences with terwijl, voordat and zodra. Deze les was lang, maar je hoeft niet te stoppen: de volgende les wacht op jou.',
  },
];
