/**
 * Lesson 26 — Kunt u mij even helpen?
 * Targets: gemeente, formulier, invullen, adres, afspraak, loket, inschrijven, ondertekenen, brief, identiteitskaart.
 * Structure: u, uw, meneer, mevrouw, eens, toch.
 * Extra vocabulary (vocabulary/kunt-u.js): stadhuis, bediende, nummer, handtekening, pasfoto, postcode, bestellen,
 * ober, alstublieft, alsjeblieft, sorry, excuseren, bedoelen, herhalen, uitleggen; zou / zouden.
 * Grammar: the formal u (u + the jij-form with -t, also in questions; uw) · polite requests with zou / zouden ·
 * the particles even, eens, maar, toch.
 * Story: Tom has moved to Leuven and must register his new address at the gemeente. He makes an appointment, waits
 * at the loket, fills in a form, shows his identity card and signs. The clerk speaks u; Tom asks her to repeat.
 * Afterwards a café with Bram and Lotte and a waiter: “Ik zou graag een koffie willen.”
 */
import { listenPages, recallPages } from '../review-pages.js';

export default [
  // ——— Words ———
  {
    part: 'Words', type: 'observe', title: 'Naar het stadhuis', grammar: ['formal-u', 'polite-zou', 'modal-particles', 'reflexive', 'separable'],
    instruction: 'Tom has moved to Leuven. Now he has to tell the town. Look and listen, and say every sentence out loud after the voice — twice. Listen for u and uw.',
    cards: [
      { nl: 'Tom krijgt een brief van de gemeente.', en: 'Tom gets a letter from the municipality.', image: 'practice-brief' },
      { nl: 'Hij moet zich inschrijven op zijn nieuwe adres.', en: 'He has to register at his new address.', image: 'practice-adres' },
      { nl: 'Daarvoor heeft hij een afspraak nodig.', en: 'For that he needs an appointment.', image: 'practice-afspraak' },
      { nl: 'Op het stadhuis wacht hij bij het loket.', en: 'At the town hall he waits at the counter.', image: 'town-hall' },
      { speaker: 'De bediende', nl: 'Goedemorgen, meneer. Kan ik u helpen?', en: 'Good morning, sir. Can I help you?', image: 'woman-working' },
      { nl: 'Tom vult een formulier in.', en: 'Tom fills in a form.', image: 'form' },
      { speaker: 'De bediende', nl: 'Mag ik uw identiteitskaart, alstublieft?', en: 'May I have your identity card, please?', image: 'practice-identiteitskaart' },
      { nl: 'Tom ondertekent het formulier: dat is zijn handtekening.', en: 'Tom signs the form: that is his signature.', image: 'form' },
      { nl: 'Kunt u dat even herhalen, mevrouw?', en: 'Could you just repeat that, madam?', image: 'woman-working' },
      { nl: 'Ik zou graag een koffie willen.', en: 'I would like a coffee, please.', image: 'coffee' },
    ],
    note: 'de gemeente = the municipality (the town as an office); het stadhuis = the town hall. het formulier = form; invullen = to fill in (vult … in, ingevuld). het adres; de afspraak = appointment; het loket = counter; zich inschrijven = to register; ondertekenen = to sign (ondertekend). de brief = letter; de identiteitskaart = identity card. u = you (polite), uw = your (polite). meneer = sir, Mr; mevrouw = madam, Mrs, Ms. zou = would.',
  },
  {
    type: 'observe', title: 'Polite words', grammar: ['formal-u', 'polite-zou', 'modal-particles'],
    instruction: 'The small words that make Dutch polite — and a few you will need at any office.',
    cards: [
      { nl: 'Excuseer, meneer. Waar is het loket?', en: 'Excuse me, sir. Where is the counter?', image: 'practice-balie' },
      { speaker: 'De bediende', nl: 'Neemt u eerst een nummer, alstublieft.', en: 'First take a number, please.', image: 'practice-nummer' },
      { speaker: 'De bediende', nl: 'Wacht u maar even in de wachtkamer.', en: 'Just wait in the waiting room.', image: 'practice-wachtkamer' },
      { speaker: 'Tom', nl: 'Sorry, wat bedoelt u?', en: 'Sorry, what do you mean?', image: 'man-thinking' },
      { speaker: 'De bediende', nl: 'Ik leg het u uit.', en: 'I’ll explain it to you.', image: 'woman-working' },
      { speaker: 'De bediende', nl: 'Heeft u een pasfoto bij u?', en: 'Do you have a passport photo with you?', image: 'photo' },
      { speaker: 'De bediende', nl: 'Kijk eens: hier zet u uw handtekening.', en: 'Look: you put your signature here.', image: 'man-writing' },
      { speaker: 'Lotte', nl: 'Je komt toch ook, Tom?', en: 'You are coming too, aren’t you, Tom?', image: 'woman-phoning' },
      { speaker: 'De ober', nl: 'Wat wilt u bestellen?', en: 'What would you like to order?', image: 'practice-ober' },
      { speaker: 'Lotte', nl: 'Bram, geef mij maar de suiker, alsjeblieft.', en: 'Bram, just pass me the sugar, please.', image: 'coffee' },
    ],
    note: 'Excuseer! = excuse me (Belgium; also Pardon!). de bediende = the clerk (in Belgium, an office employee). het nummer, de postcode, de pasfoto = passport photo, de handtekening = signature. bedoelen = to mean; herhalen = to repeat; uitleggen = to explain (legt … uit). de ober = waiter; bestellen = to order. alstublieft with u, alsjeblieft with jij. even, eens, maar and toch: small words that make a sentence softer or friendlier.',
  },
  {
    type: 'picture', title: 'Read and point', grammar: ['formal-u'],
    instruction: 'Read the sentence and choose its picture.',
    nl: 'Mag ik uw identiteitskaart, alstublieft?', en: 'May I have your identity card, please?', answer: 'practice-identiteitskaart',
    choices: [{ image: 'practice-identiteitskaart', nl: 'de identiteitskaart' }, { image: 'practice-brief', nl: 'de brief' }, { image: 'practice-portemonnee', nl: 'de portemonnee' }, { image: 'key', nl: 'de sleutel' }],
  },
  {
    type: 'picture', listen: true, title: 'Listen and point', grammar: ['formal-u', 'polite-zou'],
    instruction: 'Listen without reading. Where is Tom?',
    nl: 'Tom wacht op het stadhuis bij het loket.', en: 'Tom is waiting at the counter in the town hall.', answer: 'practice-stadhuis',
    choices: [{ image: 'station', nl: 'het station' }, { image: 'practice-stadhuis', nl: 'het stadhuis' }, { image: 'hospital', nl: 'het ziekenhuis' }, { image: 'market', nl: 'de markt' }],
  },
  {
    type: 'picture', listen: true, title: 'Once more, by ear', grammar: ['polite-zou'],
    instruction: 'Listen. Who asks the question?',
    nl: 'De ober vraagt: wat wilt u bestellen?', en: 'The waiter asks: what would you like to order?', answer: 'practice-ober',
    choices: [{ image: 'doctor', nl: 'de dokter' }, { image: 'woman-working', nl: 'de bediende' }, { image: 'practice-ober', nl: 'de ober' }, { image: 'landlady', nl: 'de eigenaar' }],
  },
  {
    type: 'drill', title: 'Write the words', grammar: ['de-het', 'plural'],
    instruction: 'Type the Dutch. Nouns with their article.',
    items: [
      { en: 'the municipality', answer: 'de gemeente' },
      { en: 'the form', answer: 'het formulier' },
      { en: 'the forms', answer: 'de formulieren' },
      { image: 'practice-adres', en: 'the address', answer: 'het adres' },
      { en: 'the addresses', answer: 'de adressen' },
      { image: 'practice-afspraak', en: 'the appointment', answer: 'de afspraak' },
      { en: 'the appointments', answer: 'de afspraken' },
      { en: 'the counter (at an office)', answer: 'het loket' },
      { en: 'the counters', answer: 'de loketten' },
      { image: 'practice-brief', en: 'the letter', answer: 'de brief' },
      { en: 'the letters', answer: 'de brieven' },
      { image: 'practice-identiteitskaart', en: 'the identity card', answer: 'de identiteitskaart' },
      { en: 'the signature', answer: 'de handtekening' },
      { en: 'the passport photo', answer: 'de pasfoto' },
      { en: 'the clerk', answer: 'de bediende' },
      { image: 'practice-stadhuis', en: 'the town hall', answer: 'het stadhuis' },
    ],
    explanation: 'adres → adressen, loket → loketten: a short vowel keeps its double consonant. afspraak → afspraken: the long aa needs one a. brief → brieven: f → v. formulier and loket are het-words.',
  },
  {
    type: 'drill', title: 'Hear and spell', grammar: ['formal-u', 'polite-zou'],
    instruction: 'Play each one and type it.',
    items: [
      { listen: 'het formulier' },
      { listen: 'de identiteitskaart' },
      { listen: 'Kunt u mij even helpen?' },
      { listen: 'Mag ik uw adres?' },
      { listen: 'Ik zou graag een afspraak maken.' },
      { listen: 'Excuseer, meneer.' },
      { listen: 'Wat bedoelt u?' },
      { listen: 'de handtekening' },
    ],
    explanation: 'for-mu-LIER, i-den-ti-TEITS-kaart, HAND-te-ke-ning. ex-cu-SEER: the stress at the end. zou rhymes with “now” — ou sounds like au.',
  },

  // ——— Grammar: target verbs ———
  {
    part: 'Grammar', type: 'grammar', title: 'Filling in, registering, signing', grammar: ['separable', 'separable-perfect', 'separable-together', 'participle-no-ge', 'reflexive', 'present-regular', 'imperfect-weak', 'imperfect-strong'],
    body: [
      'Three target verbs for every office. **invullen** (to fill in) is separable, like opstaan: *Tom **vult** het formulier **in**. Hij heeft het formulier **ingevuld**. Hij moet het formulier **invullen**.* **inschrijven** (to register) is separable and reflexive: *Tom **schrijft zich in**. Hij heeft **zich ingeschreven**.* Past: *schreef zich in*.',
      '**ondertekenen** (to sign) is **not** separable: the stress is on *te*, and onder- stays in front. *Tom **ondertekent** het formulier. Hij heeft het **ondertekend**.* No ge-, as with verbs on be-, ge-, her-, ont-, ver-. The same for **herhalen** (to repeat): *herhaalt, heeft **herhaald***, and **bedoelen** (to mean): *bedoelt, heeft **bedoeld***.',
      '**uitleggen** (to explain) is separable: *Zij **legt** het **uit**. Zij heeft het **uitgelegd**.* **excuseren** (to excuse) is mostly used as **Excuseer!** (excuse me) — in Belgium more often than Pardon.',
    ],
    tables: [
      { caption: 'Separable: the prefix goes to the end', rows: [
        { nl: 'Tom [vult] het formulier [in]. — heeft [ingevuld]', en: 'fill in' },
        { nl: 'Tom [schrijft] zich [in]. — heeft zich [ingeschreven]', en: 'register' },
        { nl: 'Zij [legt] het [uit]. — heeft [uitgelegd]', en: 'explain' },
      ] },
      { caption: 'Not separable: no ge-', rows: [
        { nl: 'Tom [ondertekent] het formulier. — heeft [ondertekend]', en: 'sign' },
        { nl: 'Zij [herhaalt] de vraag. — heeft [herhaald]', en: 'repeat' },
        { nl: 'Wat [bedoelt] u? — Wat heeft u [bedoeld]?', en: 'mean' },
      ] },
    ],
    examples: [
      { nl: 'Wilt u dit formulier invullen?', en: 'Would you fill in this form?' },
      { nl: 'Tom heeft zich op het stadhuis ingeschreven.', en: 'Tom registered at the town hall.' },
      { nl: 'Vergeet niet het formulier te ondertekenen.', en: 'Don’t forget to sign the form.' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'The office verbs', grammar: ['present-regular', 'separable', 'spelling-stem', 'subject-pronouns'],
    instruction: 'The small word under each subject is the verb. Type the present-tense verb form — for a separable verb, only the part that stays in second place.',
    items: [
      { label: 'ik', gloss: 'invullen', answer: 'vul' },
      { label: 'Tom', gloss: 'he · invullen', answer: 'vult' },
      { label: 'ik', gloss: 'ondertekenen', answer: 'onderteken' },
      { label: 'hij', gloss: 'ondertekenen', answer: 'ondertekent' },
      { label: 'ik', gloss: 'herhalen', answer: 'herhaal' },
      { label: 'de bediende', gloss: 'she · herhalen', answer: 'herhaalt' },
      { label: 'ik', gloss: 'bedoelen', answer: 'bedoel' },
      { label: 'jij', gloss: 'bedoelen', answer: 'bedoelt' },
      { label: 'zij', gloss: 'she · uitleggen', answer: 'legt' },
      { label: 'wij', gloss: 'bestellen', answer: 'bestellen' },
      { label: 'ik', gloss: 'bestellen', answer: 'bestel' },
    ],
    explanation: 'vul (… in), legt (… uit): the prefix goes to the end of the sentence. onderteken, herhaal, bedoel: the whole verb stays together. bestel: one l at the end.',
  },
  {
    type: 'drill', title: 'Participles at the town hall', grammar: ['separable-perfect', 'participle-no-ge', 'perfect-hebben', 'reflexive'],
    instruction: 'Rewrite in the perfect.',
    items: [
      { nl: 'Tom vult het formulier in.', answer: 'Tom heeft het formulier ingevuld.' },
      { nl: 'Tom schrijft zich in.', answer: 'Tom heeft zich ingeschreven.' },
      { nl: 'Tom ondertekent het formulier.', answer: 'Tom heeft het formulier ondertekend.' },
      { nl: 'De bediende herhaalt de vraag.', answer: 'De bediende heeft de vraag herhaald.' },
      { nl: 'Zij legt het formulier uit.', answer: 'Zij heeft het formulier uitgelegd.' },
      { nl: 'Bram bestelt een koffie.', answer: 'Bram heeft een koffie besteld.' },
      { nl: 'Tom maakt een afspraak.', answer: 'Tom heeft een afspraak gemaakt.' },
      { nl: 'De gemeente stuurt een brief.', answer: 'De gemeente heeft een brief gestuurd.' },
    ],
    explanation: 'ingevuld, ingeschreven, uitgelegd: ge- in the middle. ondertekend, herhaald, besteld: no ge- at all. gestuurd: an ordinary participle.',
  },
  {
    type: 'arrange', title: 'Fill it in', grammar: ['separable', 'formal-u'],
    instruction: 'Build: “Tom fills in the form at the counter.” Two tiles are traps.',
    nl: 'Tom vult het formulier in bij het loket.', en: 'Tom fills in the form at the counter.', image: 'man-writing', distractors: ['ingevuld', 'de'],
  },

  // ——— Grammar: formal u ———
  {
    type: 'grammar', title: 'u and uw: the polite you', grammar: ['formal-u', 'subject-pronouns', 'present-regular', 'possessives', 'inversion', 'zijn', 'hebben', 'modals', 'object-pronouns'],
    body: [
      'Dutch has two words for *you*: **jij / je** for family, friends, children and people your own age, and **u** for people you don’t know, older people and anyone in an office, a shop or a letter. In Flanders you will also hear **ge** and **gij** in everyday speech; this course uses jij and u, which are always right — and at the gemeente, in a shop or with the doctor, u is the safe choice.',
      '**u takes the jij-form with -t**: *u **woont**, u **werkt**, u **komt***. The difference with jij: when the verb comes first, the -t **stays** with u. *Woon **jij** in Leuven? — Woon**t** **u** in Leuven?* *Kom jij? — Kom**t** u?* Two irregular forms: **u bent** (always), and **u heeft** or **u hebt** (both correct; heeft is more usual). Modal verbs: *u **kunt**, u **wilt**, u **mag**, u **moet**, u **zou***.',
      '**uw** is the polite *your*: *Mag ik **uw** identiteitskaart? Wat is **uw** adres?* **u** is also the object form: *Kan ik **u** helpen? Ik leg het **u** uit.* With u you say **alstublieft**; with jij **alsjeblieft**. To address someone: **meneer** (sir, Mr) and **mevrouw** (madam, Mrs, Ms): *Goedemorgen, mevrouw. Dag, meneer Claes.*',
      'And the imperative? Normally the stem: *Wacht! Kijk!* With u, an office often adds **u** after the verb, which sounds friendlier: *Neemt u een nummer. Wacht u maar even.*',
    ],
    tables: [
      { caption: 'jij → u', rows: [
        { nl: 'jij woont → u [woont]', en: 'you live' },
        { nl: 'Woon jij …? → [Woont u] …?', en: 'Do you live …? (-t stays)' },
        { nl: 'jij bent → u [bent]', en: 'you are' },
        { nl: 'jij hebt → u [heeft] / u [hebt]', en: 'you have' },
        { nl: 'Kun jij …? → [Kunt u] …?', en: 'Can you …?' },
        { nl: 'Wil jij …? → [Wilt u] …?', en: 'Do you want …?' },
        { nl: 'jouw adres → [uw] adres', en: 'your address' },
        { nl: 'alsjeblieft → [alstublieft]', en: 'please' },
      ] },
    ],
    examples: [
      { nl: 'Goedemorgen, mevrouw. Heeft u een afspraak?', en: 'Good morning, madam. Do you have an appointment?' },
      { nl: 'Woont u al lang in Leuven, meneer?', en: 'Have you lived in Leuven long, sir?' },
      { nl: 'Wat is uw postcode?', en: 'What is your postcode?' },
    ],
  },
  {
    type: 'drill', layout: 'table', title: 'Conjugate with u', grammar: ['formal-u', 'present-regular', 'zijn', 'hebben', 'modals'],
    instruction: 'Type the form with u. In the second half, u comes after the verb, in a question.',
    items: [
      { label: 'u', gloss: 'wonen', answer: 'woont' },
      { label: 'u', gloss: 'zijn', answer: 'bent' },
      { label: 'u', gloss: 'hebben', answer: 'heeft', accept: ['hebt'] },
      { label: 'u', gloss: 'kunnen', answer: 'kunt' },
      { label: 'u', gloss: 'willen', answer: 'wilt' },
      { label: 'u', gloss: 'invullen', answer: 'vult' },
      { label: '… u?', gloss: 'wonen', answer: 'Woont' },
      { label: '… u?', gloss: 'kunnen', answer: 'Kunt' },
      { label: '… u?', gloss: 'hebben', answer: 'Heeft', accept: ['Hebt'] },
      { label: '… u?', gloss: 'zijn', answer: 'Bent' },
      { label: '… u?', gloss: 'bedoelen', answer: 'Bedoelt' },
    ],
    explanation: 'With u the -t stays, also in a question: Woont u? Kunt u? — while jij loses it: Woon jij? Kun jij?',
  },
  {
    type: 'drill', title: 'Make it polite: jij → u', grammar: ['formal-u', 'possessives', 'inversion', 'object-pronouns'],
    instruction: 'Rewrite the sentence with u instead of jij / je, and uw instead of jouw / je.',
    items: [
      { nl: 'Woon jij in Leuven?', answer: 'Woont u in Leuven?' },
      { nl: 'Kun jij mij helpen?', answer: 'Kunt u mij helpen?' },
      { nl: 'Heb jij een afspraak?', answer: 'Heeft u een afspraak?', accept: ['Hebt u een afspraak?'] },
      { nl: 'Wat is jouw adres?', answer: 'Wat is uw adres?' },
      { nl: 'Ben jij Tom Claes?', answer: 'Bent u Tom Claes?' },
      { nl: 'Wil jij dit formulier invullen?', answer: 'Wilt u dit formulier invullen?' },
      { nl: 'Mag ik jouw identiteitskaart, alsjeblieft?', answer: 'Mag ik uw identiteitskaart, alstublieft?' },
      { nl: 'Ik help jou graag.', answer: 'Ik help u graag.' },
      { nl: 'Wat bedoel jij?', answer: 'Wat bedoelt u?' },
      { nl: 'Jij moet hier je handtekening zetten.', answer: 'U moet hier uw handtekening zetten.' },
    ],
    explanation: 'Woont u, Kunt u, Bent u: u keeps the -t after the verb. jouw → uw, jou → u, alsjeblieft → alstublieft.',
  },
  {
    type: 'drill', title: 'u or jij?', grammar: ['formal-u', 'subject-pronouns'], choices: ['u', 'jij'],
    instruction: 'Who is talking to whom? Choose u or jij.',
    items: [
      { nl: 'De bediende aan Tom: Heeft ___ een afspraak?', answer: 'u' },
      { nl: 'Lotte aan Tom: Kom ___ vanavond eten?', answer: 'jij' },
      { nl: 'De ober aan Bram: Wat wilt ___ bestellen?', answer: 'u' },
      { nl: 'Bram aan Max: Wil ___ een koekje?', answer: 'jij' },
      { nl: 'Tom aan de bediende: Kunt ___ dat herhalen?', answer: 'u' },
      { nl: 'Bram aan zijn zus: Heb ___ mijn brief gekregen?', answer: 'jij' },
      { nl: 'Lotte aan een oude vrouw in de bus: Wilt ___ zitten?', answer: 'u' },
      { nl: 'Tom aan Emma: Ben ___ al thuis?', answer: 'jij' },
    ],
    explanation: 'Offices, waiters, strangers, older people: u. Friends, family, children and Max: jij. The verb form tells you too: heeft, wilt, kunt with u; kom, wil, heb, ben with jij in a question.',
  },

  // ——— Grammar: polite zou ———
  {
    type: 'grammar', title: 'Zou u … kunnen? — I would like', grammar: ['polite-zou', 'formal-u', 'modals', 'infinitive-end', 'zullen-future', 'adverb-position'],
    body: [
      '**zou** (plural **zouden**) is the past form of zullen. Like English *would*, it makes a question or a wish softer and more polite. The forms are easy: *ik zou, jij zou, u zou, hij zou — wij, jullie, zij **zouden***. No -t, ever: *jij zou*, *u zou*.',
      'For a polite **question**: *Zou u … kunnen?* — *Could you …?* zou stands in second place (or first, in a yes/no question), and the other verbs go to the end: ***Zou** u dit formulier even **kunnen invullen**?* Without zou it is still polite but more direct: *Kunt u dit formulier even invullen?*',
      'For a polite **wish**: *Ik zou graag … willen* — *I would like …*. ***Ik zou graag** een afspraak **willen maken**.* In a café: *Ik zou graag een koffie willen.* Just as polite and a little shorter: *Mag ik een koffie?*',
      'And **zou ik … mogen?** asks permission: ***Zou ik** even uw pen **mogen** gebruiken?* — *Could I just use your pen?*',
    ],
    tables: [
      { caption: 'More polite, step by step', rows: [
        { nl: 'Vul het formulier in.', en: 'Fill in the form. (an order)' },
        { nl: '[Kunt u] het formulier invullen?', en: 'Can you fill in the form?' },
        { nl: '[Zou u] het formulier even [kunnen invullen]?', en: 'Could you just fill in the form?' },
      ] },
      { caption: 'Wishes and permission', rows: [
        { nl: 'Ik [zou] graag een afspraak [willen maken].', en: 'I would like to make an appointment.' },
        { nl: 'Wij [zouden] graag betalen.', en: 'We would like to pay.' },
        { nl: '[Zou] ik uw pen [mogen gebruiken]?', en: 'Could I use your pen?' },
      ] },
    ],
    examples: [
      { nl: 'Zou u dat even kunnen herhalen?', en: 'Could you just repeat that?' },
      { nl: 'Ik zou graag een thee willen.', en: 'I’d like a tea.' },
      { nl: 'Zouden jullie hier even willen wachten?', en: 'Would you mind waiting here for a moment?' },
    ],
  },
  {
    type: 'drill', title: 'Ask it more politely', grammar: ['polite-zou', 'formal-u', 'modals', 'infinitive-end'],
    instruction: 'Rewrite the question with “Zou u … kunnen?”',
    items: [
      { nl: 'Kunt u dat herhalen?', answer: 'Zou u dat kunnen herhalen?' },
      { nl: 'Kunt u mij helpen?', answer: 'Zou u mij kunnen helpen?' },
      { nl: 'Kunt u dit formulier invullen?', answer: 'Zou u dit formulier kunnen invullen?' },
      { nl: 'Kunt u hier tekenen?', answer: 'Zou u hier kunnen tekenen?' },
      { nl: 'Kunt u het uitleggen?', answer: 'Zou u het kunnen uitleggen?' },
      { nl: 'Kunt u even wachten?', answer: 'Zou u even kunnen wachten?' },
      { nl: 'Kunt u uw adres herhalen?', answer: 'Zou u uw adres kunnen herhalen?' },
      { nl: 'Kunt u mij een brief sturen?', answer: 'Zou u mij een brief kunnen sturen?' },
    ],
    explanation: 'zou comes first in the question; kunnen and the other infinitive go to the end: kunnen herhalen, kunnen invullen (invullen stays one word).',
  },
  {
    type: 'drill', title: 'I would like …', grammar: ['polite-zou', 'modals', 'infinitive-end', 'adverb-position'],
    instruction: 'Type the missing word: zou, zouden, willen, kunnen or mogen.',
    items: [
      { nl: 'Ik ___ graag een afspraak maken.', answer: 'zou' },
      { nl: 'Ik zou graag een koffie ___.', answer: 'willen' },
      { nl: 'Wij ___ graag betalen.', answer: 'zouden' },
      { nl: '___ u dat even kunnen herhalen?', answer: 'Zou' },
      { nl: 'Zou ik uw pen ___ gebruiken?', en: 'May I use your pen?', answer: 'mogen' },
      { nl: 'Zou u het formulier ___ invullen?', en: 'Could you fill in the form?', answer: 'kunnen' },
      { nl: 'Bram en Lotte ___ graag in Leuven blijven.', answer: 'zouden' },
      { nl: 'Jij ___ dat toch ook doen?', en: 'You would do that too, wouldn’t you?', answer: 'zou' },
    ],
    explanation: 'zou with ik, jij, u, hij, zij (she); zouden with wij, jullie, zij (they). No -t: jij zou, u zou.',
  },
  {
    type: 'drill', title: 'Say it politely', grammar: ['polite-zou', 'formal-u', 'modals'],
    instruction: 'Translate. Use u and zou.',
    items: [
      { en: 'I would like to make an appointment.', answer: 'Ik zou graag een afspraak willen maken.', accept: ['Ik zou graag een afspraak maken.'] },
      { en: 'Could you repeat that?', answer: 'Zou u dat kunnen herhalen?', accept: ['Zou u dat even kunnen herhalen?'] },
      { en: 'Could you help me?', answer: 'Zou u mij kunnen helpen?', accept: ['Zou u me kunnen helpen?'] },
      { en: 'I would like a coffee.', answer: 'Ik zou graag een koffie willen.' },
      { en: 'Could I use your pen?', answer: 'Zou ik uw pen mogen gebruiken?' },
      { en: 'We would like to pay.', answer: 'Wij zouden graag betalen.', accept: ['We zouden graag betalen.', 'Wij zouden graag willen betalen.', 'We zouden graag willen betalen.'] },
    ],
    explanation: 'Ik zou graag … willen; Zou u … kunnen?; Zou ik … mogen?',
  },
  {
    type: 'arrange', title: 'A polite question', grammar: ['polite-zou', 'formal-u'],
    instruction: 'Build: “Could you just repeat that?” Two tiles are traps.',
    nl: 'Zou u dat even kunnen herhalen?', en: 'Could you just repeat that?', image: 'woman-working', distractors: ['jij', 'zouden'],
  },

  // ——— Grammar: particles ———
  {
    type: 'grammar', title: 'even, eens, maar, toch', grammar: ['modal-particles', 'imperative', 'formal-u', 'yes-no-question'],
    body: [
      'Dutch speakers put small words in a sentence that English expresses with tone of voice or with *just*, *please* or *…, right?*. They don’t change the facts; they change the feeling. Without them a request can sound blunt.',
      '**even** = *just, for a moment*: it makes a request small. *Wacht **even**. Kunt u mij **even** helpen?* **eens** = *(just) … for once, have a …*: it makes a suggestion friendly. *Kijk **eens**! Probeer het **eens**.* **maar** = *go ahead, feel free*: it gives permission or encourages. *Kom **maar** binnen. Gaat u **maar** zitten.* (*Geef mij maar een koffie* = I’ll just have a coffee.)',
      '**toch** in a statement asks for agreement, like *…, right? / …, aren’t you?*: *Je komt **toch**?* — You are coming, aren’t you? *Dat is **toch** jouw portemonnee?* — That’s your wallet, isn’t it? (toch also means *still, after all*: *Het regende, maar wij zijn **toch** gegaan.* — It rained, but we went anyway.)',
      'Where do they go? After the verb and the subject, before most other words: *Wacht u **maar even**. Kijk **eens** hier.* Two together are common: **maar even**, **eens even**.',
    ],
    tables: [
      { caption: 'Softer and friendlier', rows: [
        { nl: 'Wacht. → Wacht [even].', en: 'Wait. → Just wait a moment.' },
        { nl: 'Kijk. → Kijk [eens].', en: 'Look. → Have a look.' },
        { nl: 'Kom binnen. → Kom [maar] binnen.', en: 'Come in. → Do come in.' },
        { nl: 'Je komt? → Je komt [toch]?', en: 'You’re coming? → You’re coming, aren’t you?' },
      ] },
    ],
    examples: [
      { nl: 'Gaat u maar zitten, meneer.', en: 'Please take a seat, sir.' },
      { nl: 'Probeer het nog eens.', en: 'Try it once more.' },
      { nl: 'Jij hebt toch een identiteitskaart?', en: 'You do have an identity card, don’t you?' },
    ],
  },
  {
    type: 'drill', title: 'even, eens, maar or toch?', grammar: ['modal-particles', 'imperative', 'formal-u'], choices: ['even', 'eens', 'maar', 'toch'],
    instruction: 'Choose the little word that fits the English.',
    items: [
      { nl: 'Wacht u ___ in de wachtkamer.', en: 'Just wait in the waiting room (go ahead).', answer: 'maar' },
      { nl: 'Kunt u mij ___ helpen?', en: 'Could you help me for a moment?', answer: 'even' },
      { nl: 'Kijk ___, hier is uw nummer.', en: 'Have a look, here is your number.', answer: 'eens' },
      { nl: 'Je komt ___ ook?', en: 'You’re coming too, aren’t you?', answer: 'toch' },
      { nl: 'Komt u ___ binnen.', en: 'Do come in.', answer: 'maar' },
      { nl: 'Dat is ___ jouw sleutel?', en: 'That’s your key, isn’t it?', answer: 'toch' },
      { nl: 'Probeer het nog ___.', en: 'Try it once more.', answer: 'eens' },
      { nl: 'Mag ik ___ uw pen?', en: 'May I have your pen for a moment?', answer: 'even' },
      { nl: 'Het regende, maar wij zijn ___ gegaan.', en: 'It rained, but we went anyway.', answer: 'toch' },
      { nl: 'Geef mij ___ een thee.', en: 'I’ll just have a tea.', answer: 'maar' },
    ],
    explanation: 'even: for a moment. eens: have a go, once. maar: go ahead, feel free. toch: …, right? or anyway.',
  },
  {
    type: 'drill', title: 'Soften it', grammar: ['modal-particles', 'imperative', 'formal-u', 'polite-zou'],
    instruction: 'Rewrite as the task says.',
    items: [
      { nl: 'Wacht.', task: 'Add even', answer: 'Wacht even.' },
      { nl: 'Kijk.', task: 'Add eens', answer: 'Kijk eens.' },
      { nl: 'Kom binnen.', task: 'Add maar', answer: 'Kom maar binnen.' },
      { nl: 'Je hebt een pasfoto.', task: 'Add toch — make it “…, don’t you?”', answer: 'Je hebt toch een pasfoto?' },
      { nl: 'Neem een nummer.', task: 'Make it polite with u and maar', answer: 'Neemt u maar een nummer.' },
      { nl: 'Help mij.', task: 'Make it a polite question: “Kunt u … even …?”', answer: 'Kunt u mij even helpen?' },
      { nl: 'Vul het formulier in.', task: 'Make it a polite question: “Zou u …?” with even', answer: 'Zou u het formulier even kunnen invullen?' },
      { nl: 'Ga zitten.', task: 'Make it polite with u and maar', answer: 'Gaat u maar zitten.' },
    ],
    explanation: 'The particle comes after the verb (and u): Wacht even, Kom maar binnen, Neemt u maar …. Je hebt toch …? asks for agreement.',
  },

  // ——— Combine ———
  {
    part: 'Combine', type: 'drill', title: 'At the loket', grammar: ['formal-u', 'polite-zou', 'modal-particles', 'question-word', 'possessives'],
    instruction: 'You are the clerk. Ask Tom for each thing politely, with u or uw.',
    items: [
      { en: 'Ask for his name.', answer: 'Wat is uw naam?', accept: ['Hoe heet u?', 'Mag ik uw naam?'] },
      { en: 'Ask for his address.', answer: 'Wat is uw adres?', accept: ['Mag ik uw adres?'] },
      { en: 'Ask for his postcode.', answer: 'Wat is uw postcode?', accept: ['Mag ik uw postcode?'] },
      { en: 'Ask for his identity card.', answer: 'Mag ik uw identiteitskaart?', accept: ['Mag ik uw identiteitskaart, alstublieft?', 'Heeft u uw identiteitskaart?'] },
      { en: 'Ask if he has an appointment.', answer: 'Heeft u een afspraak?', accept: ['Hebt u een afspraak?'] },
      { en: 'Ask him to fill in the form. (Zou u …)', answer: 'Zou u het formulier kunnen invullen?', accept: ['Zou u het formulier even kunnen invullen?', 'Zou u dit formulier kunnen invullen?', 'Zou u dit formulier even kunnen invullen?'] },
      { en: 'Ask him to sign the form here. (Wilt u …)', answer: 'Wilt u het formulier hier ondertekenen?', accept: ['Wilt u het formulier hier even ondertekenen?', 'Wilt u hier ondertekenen?', 'Wilt u hier even ondertekenen?'] },
      { en: 'Ask if he lives in Leuven.', answer: 'Woont u in Leuven?' },
      { en: 'Ask what his phone number is.', answer: 'Wat is uw telefoonnummer?', accept: ['Wat is uw nummer?'] },
      { en: 'Tell him to just wait a moment. (maar even)', answer: 'Wacht u maar even.' },
    ],
    explanation: 'uw for your; Heeft u, Woont u, Wilt u: the -t stays. Zou u … kunnen invullen?',
  },
  {
    type: 'drill', title: 'At the gemeente', grammar: ['formal-u', 'polite-zou', 'modal-particles', 'question-word', 'place-prepositions'],
    instruction: 'Answer each question with a complete sentence, using the words in brackets.',
    items: [
      { nl: 'Waar schrijft u zich in? (bij de gemeente)', answer: 'Ik schrijf mij in bij de gemeente.', accept: ['Ik schrijf me in bij de gemeente.', 'Bij de gemeente.'] },
      { nl: 'Waar is de gemeente in Leuven? (in het stadhuis)', answer: 'De gemeente is in het stadhuis.', accept: ['In het stadhuis.'] },
      { nl: 'Waar wacht Tom? (bij het loket)', answer: 'Tom wacht bij het loket.', accept: ['Hij wacht bij het loket.'] },
      { nl: 'Welk loket is het? (loket drie)', answer: 'Het is loket drie.', accept: ['Loket drie.'] },
      { nl: 'Wie werkt er aan het loket? (een bediende)', answer: 'Er werkt een bediende aan het loket.', accept: ['Een bediende werkt aan het loket.', 'Een bediende.'] },
      { nl: 'Hoe vraagt u de weg naar het loket? (Excuseer, mevrouw …)', answer: 'Excuseer, mevrouw, waar is het loket?', accept: ['Excuseer mevrouw, waar is het loket?', 'Excuseer, mevrouw. Waar is het loket?'] },
      { nl: 'Wat zegt u, als u een vraag heeft voor een vrouw die u niet kent? (Excuseer)', answer: 'Excuseer, mevrouw.', accept: ['Excuseer!', 'Excuseer.', 'Excuseer mevrouw.'] },
      { nl: 'Van wie krijgt Tom een brief? (van de gemeente)', answer: 'Tom krijgt een brief van de gemeente.', accept: ['Hij krijgt een brief van de gemeente.', 'Van de gemeente.'] },
      { nl: 'Is het loket op zondag open? (nee, gesloten)', answer: 'Nee, het loket is op zondag gesloten.', accept: ['Nee, op zondag is het loket gesloten.', 'Nee, het is op zondag gesloten.'] },
      { nl: 'Belt Tom de gemeente voor een afspraak? (ja)', answer: 'Ja, Tom belt de gemeente voor een afspraak.', accept: ['Ja, hij belt de gemeente voor een afspraak.'] },
    ],
    explanation: 'de gemeente: the town as an office, often in het stadhuis. het loket: the counter where a bediende works. Excuseer: excuse me.',
  },
  {
    type: 'drill', title: 'Everything you know, at the town hall', grammar: ['pluperfect', 'indefinite-pronouns', 'niet-meer', 'formal-u', 'om-te', 'hoeven-te', 'want-omdat', 'verb-final', 'time-conjunctions', 'separable-perfect'],
    instruction: 'Rewrite as the task says.',
    items: [
      { nl: 'Tom heeft het formulier ingevuld.', task: 'Use the pluperfect', answer: 'Tom had het formulier ingevuld.' },
      { nl: 'Tom gaat naar het stadhuis. Hij schrijft zich in.', task: 'Join with om … te', answer: 'Tom gaat naar het stadhuis om zich in te schrijven.' },
      { nl: 'U neemt een pasfoto mee.', task: 'Say: you don’t have to bring a photo. Use hoeven', answer: 'U hoeft geen pasfoto mee te nemen.' },
      { nl: 'Tom moet naar de gemeente. Hij is verhuisd.', task: 'Join with omdat', answer: 'Tom moet naar de gemeente, omdat hij verhuisd is.', accept: ['Tom moet naar de gemeente, omdat hij is verhuisd.'] },
      { nl: 'Tom ondertekent het formulier. Hij geeft het aan de bediende.', task: 'Start with “Nadat Tom het formulier ondertekend heeft,”', answer: 'Nadat Tom het formulier ondertekend heeft, geeft hij het aan de bediende.' },
      { nl: 'Heeft iemand een pen?', task: 'Answer: nobody has a pen', answer: 'Niemand heeft een pen.' },
      { nl: 'Heeft Tom nog vragen?', task: 'Answer: no more questions', answer: 'Nee, Tom heeft geen vragen meer.', accept: ['Nee, hij heeft geen vragen meer.'] },
      { nl: 'Tom kwam aan. De bediende was al vertrokken.', task: 'Join: start with “Toen Tom aankwam,”', answer: 'Toen Tom aankwam, was de bediende al vertrokken.' },
    ],
    explanation: 'om zich in te schrijven: zich stays before in te. hoeft geen … mee te nemen. omdat … verhuisd is. Nadat …, geeft hij. was … gesloten.',
  },
  {
    type: 'drill', title: 'Last lesson, now with u', grammar: ['pluperfect', 'indefinite-pronouns', 'niet-meer', 'formal-u', 'imperfect-strong', 'toen-past', 'perfect-zijn'],
    instruction: 'Lesson 25 again — Bram’s bad day — now with u. Type the missing word.',
    items: [
      { nl: 'Bent u iets ___, meneer?', en: 'Have you lost something, sir?', answer: 'kwijt' },
      { nl: 'Heeft u ___ verloren?', en: 'Have you lost anything?', answer: 'iets' },
      { nl: 'Ja, ik heb mijn portemonnee ___.', cue: 'verliezen', answer: 'verloren' },
      { nl: 'Heeft ___ hem gevonden?', en: 'Has anyone found it?', answer: 'iemand' },
      { nl: 'Nee, ___ heeft hem gevonden.', en: 'No, nobody has found it.', answer: 'niemand' },
      { nl: 'Toen Bram bij de halte kwam, ___ de bus al vertrokken.', answer: 'was' },
      { nl: 'Bram is naar de bus ___.', cue: 'rennen', answer: 'gerend' },
      { nl: 'Bram ___ naar het station.', cue: 'rennen', en: 'simple past', answer: 'rende' },
      { nl: 'U hoeft niet te ___, meneer.', cue: 'rennen', answer: 'rennen' },
      { nl: 'De trein ___ pas om negen uur.', cue: 'vertrekken', answer: 'vertrekt' },
      { nl: 'Heeft u de trein ___?', cue: 'missen', answer: 'gemist' },
      { nl: 'Bram ___ zijn portemonnee in de bus.', cue: 'verliezen', en: 'simple past', answer: 'verloor' },
      { nl: 'Was er iemand thuis? — Nee, er was ___.', en: 'nobody', answer: 'niemand' },
      { nl: 'Kent u ___ in Leuven?', en: 'Do you know anyone in Leuven?', answer: 'iemand' },
    ],
    explanation: 'kwijt zijn, verloren, verloor. was vertrokken: the past before the past. gerend, rende, niet te rennen. iemand / niemand, iets / niets.',
  },
  {
    type: 'drill', title: 'Everything so far, at the town hall', grammar: ['dit-is', 'geen', 'niet', 'hij-het-things', 'geen-niet', 'adjective-e', 'spelling-z-s', 'gaan', 'v2-inversion', 'time-place', 'er-is-zijn', 'numbers', 'wie-hoe', 'dt-rule', 'clock-time', 'days-op-om', 'participle', 'perfect-zijn', 'dat-clause', 'als-inversion', 'imperfect-weak', 'imperfect-strong', 'zullen-future'],
    instruction: 'Type the missing word. Every grammar point of volumes zero and one, at the town hall.',
    items: [
      { image: 'practice-brief', nl: 'Wat is dit?', answer: 'Dit is een brief.', accept: ['Het is een brief.', 'Dit is de brief.'] },
      { nl: 'Tom heeft ___ pen.', en: 'Tom doesn’t have a pen.', answer: 'geen' },
      { nl: 'Het loket is ___ open.', en: 'The counter is not open.', answer: 'niet' },
      { nl: 'Waar is het formulier? — ___ ligt op de tafel.', cue: 'hij / het', answer: 'Het' },
      { nl: 'Waar is de brief? — ___ ligt op de tafel.', cue: 'hij / het', answer: 'Hij' },
      { nl: 'Tom heeft een ___ adres.', cue: 'nieuw', answer: 'nieuw' },
      { nl: 'Dat is zijn ___ adres.', cue: 'nieuw', answer: 'nieuwe' },
      { nl: 'Tom ___ het formulier.', cue: 'lezen', answer: 'leest' },
      { nl: 'Morgen ___ Tom naar het stadhuis.', cue: 'gaan', answer: 'gaat' },
      { nl: 'Op het stadhuis ___ drie loketten.', cue: 'er is / er zijn', answer: 'zijn er' },
      { nl: '___ heet u? — Ik heet Tom.', en: 'What is your name?', answer: 'Hoe' },
      { nl: '___ helpt Tom? — De bediende.', en: 'Who helps Tom?', answer: 'Wie' },
      { nl: 'De bediende ___ het formulier.', cue: 'houden', answer: 'houdt' },
      { nl: 'De afspraak is ___ tien uur.', cue: 'op / om', answer: 'om' },
      { nl: 'Tom gaat ___ dinsdag naar de gemeente.', cue: 'op / om', answer: 'op' },
      { nl: 'Tom is naar het stadhuis ___.', cue: 'gaan', answer: 'gegaan' },
      { nl: 'Tom weet ___ hij een afspraak nodig heeft.', en: 'Tom knows that he needs an appointment.', answer: 'dat' },
      { nl: 'Als Tom verhuist, ___ hij zich inschrijven.', cue: 'moeten', answer: 'moet' },
      { nl: 'Vroeger ___ Tom in Gent.', cue: 'wonen', en: 'simple past', answer: 'woonde' },
      { nl: 'De bediende ___ hem een formulier.', cue: 'geven', en: 'simple past', answer: 'gaf' },
      { nl: 'Ik ___ u morgen bellen.', cue: 'zullen', answer: 'zal' },
    ],
    explanation: 'geen pen, niet open. het formulier → het, de brief → hij. een nieuw adres (een + het-word) but zijn nieuwe adres. houdt: d + t. om + clock time, op + day. Als …, moet hij: the clause is position one.',
  },
  {
    type: 'drill', title: 'Volume two, at the office', grammar: ['separable', 'separable-perfect', 'separable-together', 'comparative', 'superlative', 'dan-als', 'toen-past', 'imperative', 'pijn-hebben', 'te-infinitive', 'over-geleden', 'relative-clause', 'kennen-weten', 'reflexive'],
    instruction: 'Every grammar point of lessons 13–18. Rewrite as the task says, or type the missing word.',
    items: [
      { nl: 'Tom staat om zeven uur op.', task: 'Start with “Tom moet”', answer: 'Tom moet om zeven uur opstaan.' },
      { nl: 'Tom belt de gemeente op.', task: 'Use the perfect', answer: 'Tom heeft de gemeente opgebeld.' },
      { nl: 'Tom neemt zijn identiteitskaart mee.', task: 'Start with “Tom vergeet niet”', answer: 'Tom vergeet niet zijn identiteitskaart mee te nemen.', accept: ['Tom vergeet niet om zijn identiteitskaart mee te nemen.'] },
      { nl: 'Het stadhuis van Leuven is mooi. Het stadhuis van Gent is ook mooi.', task: 'Use “even … als”: “Het stadhuis van Leuven is …”', answer: 'Het stadhuis van Leuven is even mooi als het stadhuis van Gent.', accept: ['Het stadhuis van Leuven is even mooi als dat van Gent.'] },
      { nl: 'Dit formulier is moeilijk. Dat formulier is makkelijk.', task: 'One sentence: “Dit formulier is … dan dat formulier.”', answer: 'Dit formulier is moeilijker dan dat formulier.' },
      { nl: 'Dit loket is snel.', task: 'Use the superlative: “Dit loket is het …”', answer: 'Dit loket is het snelst.' },
      { nl: 'Tom is klein. Hij woont in Gent.', task: 'Start with “Toen Tom klein was,” — simple past', answer: 'Toen Tom klein was, woonde hij in Gent.' },
      { nl: 'Jij vult het formulier in.', task: 'Make it an order', answer: 'Vul het formulier in!' },
      { nl: 'Tom heeft ___ in zijn hoofd.', en: 'Tom has a headache.', answer: 'pijn' },
      { nl: 'Tom schrijft zich in.', task: 'Start with “Tom probeert”', answer: 'Tom probeert zich in te schrijven.' },
      { nl: 'Twee weken geleden is Tom verhuisd.', task: 'Make it future: “over”, present tense', answer: 'Over twee weken verhuist Tom.' },
      { nl: 'Dit is het formulier. Tom heeft het ingevuld.', task: 'Join with die or dat', answer: 'Dit is het formulier dat Tom ingevuld heeft.', accept: ['Dit is het formulier dat Tom heeft ingevuld.'] },
      { nl: 'Tom ___ de bediende niet.', cue: 'kennen / weten', answer: 'kent' },
      { nl: 'Tom ___ zijn postcode niet meer.', cue: 'kennen / weten', answer: 'weet' },
      { nl: 'Tom haast zich naar het stadhuis.', task: 'Change Tom to wij', answer: 'Wij haasten ons naar het stadhuis.' },
    ],
    explanation: 'moet … opstaan, opgebeld, mee te nemen, zich in te schrijven. even mooi als, moeilijker dan, het snelst. Vul … in!: the stem with the prefix at the end. het formulier → dat. kennen a person, weten a fact.',
  },
  {
    type: 'drill', title: 'Volume three, at the office', grammar: ['object-pronouns', 'indirect-object', 'van-voor-bij', 'position-verbs', 'place-prepositions', 'er-daar-place', 'numbers-big', 'dates', 'er-quantity', 'verb-preposition', 'er-preposition', 'waar-preposition', 'time-conjunctions', 'hoewel-zodat', 'of-whether', 'hoeven-te', 'demonstratives', 'comparative', 'superlative', 'dan-als', 'toen-past', 'relative-clause', 'kennen-weten', 'niet-meer', 'te-infinitive', 'pijn-hebben', 'over-geleden'],
    instruction: 'Every grammar point of lessons 19–25. Type the missing word.',
    items: [
      { nl: 'Heeft u het formulier? — Ja, ik heb ___ hier.', en: 'I have it here.', answer: 'het' },
      { nl: 'De bediende geeft ___ een pen.', en: 'The clerk gives him (Tom) a pen.', answer: 'hem' },
      { nl: 'Het formulier is ___ de gemeente.', en: 'from the municipality', answer: 'van' },
      { nl: 'De brief ___ op de tafel.', cue: 'staan / liggen / hangen', answer: 'ligt' },
      { nl: 'De jas van Tom ___ aan de muur.', cue: 'staan / liggen / hangen', answer: 'hangt' },
      { nl: 'Tom zit ___ het loket.', en: 'in front of the counter', answer: 'voor' },
      { nl: 'Bent u op het stadhuis geweest? — Ja, ik ben ___ gisteren geweest.', en: 'I was there yesterday.', answer: 'daar', accept: ['er'] },
      { nl: 'Hoeveel loketten zijn er? — Er zijn ___ vier.', answer: 'er' },
      { nl: 'Tom woont op nummer ___.', cue: '35', answer: 'vijfendertig' },
      { nl: 'De afspraak is op ___ maart.', cue: '21', answer: 'eenentwintig' },
      { nl: 'Tom wacht ___ zijn nummer.', answer: 'op' },
      { nl: 'Hij wacht ___ al een uur op.', en: 'He has been waiting for it for an hour.', answer: 'er' },
      { nl: '___ denkt u aan? — Aan mijn afspraak.', en: 'What are you thinking of?', answer: 'Waar' },
      { nl: 'Terwijl Tom wacht, ___ hij de brief.', cue: 'lezen', answer: 'leest' },
      { nl: 'Hoewel het loket gesloten ___, wacht Tom.', cue: 'zijn', answer: 'is' },
      { nl: 'Tom vraagt ___ hij een pasfoto nodig heeft.', en: 'Tom asks whether he needs a passport photo.', answer: 'of' },
      { nl: 'U ___ geen pasfoto mee te nemen.', en: 'You don’t have to bring a photo.', answer: 'hoeft' },
      { nl: '___ formulier moet u invullen.', en: 'This form …', answer: 'Dit' },
      { nl: '___ brief is van de gemeente.', en: 'This letter …', answer: 'Deze' },
    ],
    explanation: 'het for het formulier, hem for Tom. ligt flat, hangt on the wall. er zijn er vier: er for “loketten”. wachten op → er … op. terwijl, hoewel: the verb at the end. of = whether. dit for a het-word, deze for a de-word.',
  },
  {
    type: 'drill', title: 'Tom’s new flat', grammar: ['indirect-object', 'van-voor-bij', 'position-verbs', 'er-daar-place', 'numbers-big', 'dates', 'er-quantity', 'verb-preposition', 'er-preposition', 'waar-preposition', 'demonstratives', 'formal-u'],
    instruction: 'Lotte asks Tom about his new flat in Leuven. Answer each question with a complete sentence, using the words in brackets.',
    items: [
      { nl: 'Op welk nummer woon je? (nummer vijfendertig)', answer: 'Ik woon op nummer vijfendertig.' },
      { nl: 'Sinds wanneer woon je daar? (sinds één maart)', answer: 'Ik woon daar sinds één maart.', accept: ['Ik woon er sinds één maart.', 'Sinds één maart.', 'Ik woon daar sinds een maart.'] },
      { nl: 'Hoeveel kamers zijn er? (twee)', answer: 'Er zijn er twee.', accept: ['Er zijn twee kamers.'] },
      { nl: 'Van wie is het appartement? (van een oude vrouw)', answer: 'Het appartement is van een oude vrouw.', accept: ['Het is van een oude vrouw.', 'Van een oude vrouw.'] },
      { nl: 'Waar staat je bed? (in de kleine kamer)', answer: 'Mijn bed staat in de kleine kamer.', accept: ['Het staat in de kleine kamer.'] },
      { nl: 'Waar liggen je boeken? (op de vloer)', answer: 'Mijn boeken liggen op de vloer.', accept: ['Ze liggen op de vloer.'] },
      { nl: 'Wat geef je de eigenaar elke maand? (de huur)', answer: 'Ik geef de eigenaar elke maand de huur.', accept: ['Ik geef haar elke maand de huur.', 'Ik geef de eigenaar de huur.'] },
      { nl: 'Waar wacht je nog op? (op een brief van de gemeente)', answer: 'Ik wacht nog op een brief van de gemeente.' },
      { nl: 'Wacht je er al lang op? (nee, een week)', answer: 'Nee, ik wacht er een week op.', accept: ['Nee, ik wacht er pas een week op.', 'Nee, een week.'] },
      { nl: 'Welke kamer is het mooist? (deze kamer)', answer: 'Deze kamer is het mooist.' },
      { nl: 'Kook je in je nieuwe keuken? (ja, soep met groenten)', answer: 'Ja, ik kook soep met groenten.', accept: ['Ja, ik kook soep met groenten in mijn nieuwe keuken.'] },
    ],
    explanation: 'Er zijn er twee: er for “kamers”. staat upright, liggen flat. de eigenaar de huur: the person before the thing. wachten op → waar … op, er … op. deze for a de-word close by.',
  },
  {
    type: 'drill', title: 'Before, after and as soon as', grammar: ['time-conjunctions', 'hoewel-zodat', 'of-whether', 'verb-final', 'perfect-zijn', 'pluperfect', 'formal-u'],
    instruction: 'Rewrite as the task says. After voordat, nadat, zodra, zodat, sinds, terwijl and of the verb goes to the end.',
    items: [
      { nl: 'U gaat naar het loket. U neemt een nummer.', task: 'Start with “Voordat u naar het loket gaat,”', answer: 'Voordat u naar het loket gaat, neemt u een nummer.' },
      { nl: 'Tom heeft het formulier ingevuld. Hij ondertekent het.', task: 'Start with “Nadat”', answer: 'Nadat Tom het formulier ingevuld heeft, ondertekent hij het.', accept: ['Nadat Tom het formulier heeft ingevuld, ondertekent hij het.'] },
      { nl: 'Het loket is open. Tom gaat naar de bediende.', task: 'Start with “Zodra”', answer: 'Zodra het loket open is, gaat Tom naar de bediende.' },
      { nl: 'Tom schrijft langzaam. De bediende kan het lezen.', task: 'Join with zodat', answer: 'Tom schrijft langzaam, zodat de bediende het kan lezen.' },
      { nl: 'Tom woont in Leuven. Hij heeft een nieuw adres.', task: 'Start with “Sinds”', answer: 'Sinds Tom in Leuven woont, heeft hij een nieuw adres.' },
      { nl: 'Tom wacht. Hij leest de brief.', task: 'Join with terwijl: “Terwijl Tom wacht, …”', answer: 'Terwijl Tom wacht, leest hij de brief.' },
      { nl: 'Is het loket open?', task: 'Start with “Weet u of”', answer: 'Weet u of het loket open is?' },
    ],
    explanation: 'Voordat …, neemt u: the clause is position one, then the verb. Nadat … ingevuld heeft. zodat … kan lezen. Weet u of … open is?',
  },
  {
    type: 'arrange', title: 'Registering', grammar: ['om-te', 'reflexive', 'separable'],
    instruction: 'Build: “Tom goes to the town hall to register.” Two tiles are traps.',
    nl: 'Tom gaat naar het stadhuis om zich in te schrijven.', en: 'Tom goes to the town hall to register.', image: 'practice-stadhuis', distractors: ['ingeschreven', 'hem'],
  },

  ...recallPages(["huis", "boom", "bank", "man", "kind", "deur", "raam", "auto", "straat", "groot", "jong", "moe", "blij", "ziek", "lief", "lopen", "slapen", "spelen", "leren", "praten", "hond", "kat", "fiets", "tas", "telefoon", "water", "brood", "kaas", "park", "winkel", "school", "stad", "vijf", "stoel", "tuin", "veel", "vader", "moeder", "broer", "vriend", "vriendin", "familie", "jaar", "zwemmen", "rijden", "Nederlands", "goed", "maandag", "woensdag", "donderdag", "vrijdag", "zaterdag", "weekend", "kopen", "zien", "film", "want", "hopen", "examen", "meenemen", "uitgaan", "vroeg", "ontbijt", "makkelijk", "geleden", "hoofd", "pijn", "dokter", "hangen", "muur", "zoeken", "houden", "ziekenhuis", "voordat", "zodra", "hoewel", "zodat", "markt", "kwijt", "missen", "rennen", "niemand", "duur", "goedkoop", "warm", "koud", "kort", "vakantie", "zee", "strand", "reizen", "foto", "oma", "opa", "voelen", "herinneren", "buik", "rug", "apotheek", "medicijn", "volgende", "zomer", "winter", "reis", "vliegen", "vliegtuig", "hotel", "beginnen", "buurman", "buurvrouw", "collega", "student", "universiteit", "les", "leraar", "antwoord", "ontmoeten", "verrassen", "wensen", "cadeau", "verjaardag", "feest", "bloem", "kaart", "kast", "lamp", "doos", "verdienen", "sparen", "lenen", "geld", "bedrag", "interesseren", "luisteren", "zorgen", "muziek", "sport", "televisie", "patiënt", "bang", "eindigen", "project", "fruit", "vlees", "vis", "ei", "recept", "snijden"], { size: 15 }),
  ...listenPages(["duur", "goedkoop", "warm", "koud", "kort", "vakantie", "zee", "strand", "reizen", "foto", "oma", "opa", "voelen", "herinneren", "buik", "rug", "apotheek", "medicijn", "volgende", "zomer", "winter", "reis", "vliegen", "vliegtuig", "hotel", "beginnen", "buurman", "buurvrouw", "collega", "student", "universiteit", "les", "leraar", "antwoord", "ontmoeten", "verrassen", "wensen", "cadeau", "verjaardag", "feest", "bloem", "kaart", "kast", "lamp", "doos", "verdienen", "sparen", "lenen", "geld", "bedrag", "interesseren", "luisteren", "zorgen", "muziek", "sport", "televisie", "patiënt", "bang", "eindigen", "project", "fruit", "vlees", "vis", "ei", "recept", "snijden"], { size: 16 }),

  // ——— Read ———
  {
    part: 'Read', type: 'story', title: 'Op het stadhuis', image: 'town-hall', grammar: ['formal-u', 'polite-zou', 'modal-particles', 'pluperfect', 'separable'],
    instruction: 'Tom registers his new address. Read and listen to every line, then read it again without the English. Listen for every u and uw.',
    lines: [
      { nl: 'Tom woont nu in Leuven. Op een dag krijgt hij een brief van de gemeente.', en: 'Tom lives in Leuven now. One day he gets a letter from the municipality.', image: 'practice-brief' },
      { nl: 'In de brief staat: u moet zich op uw nieuwe adres inschrijven. Maak eerst een afspraak.', en: 'The letter says: you have to register at your new address. Make an appointment first.', image: 'practice-brief' },
      { nl: 'Tom belt de gemeente en maakt een afspraak voor dinsdag om tien uur.', en: 'Tom calls the municipality and makes an appointment for Tuesday at ten.', image: 'phone' },
      { nl: 'Op dinsdag is Tom op tijd. Hij heeft de bus niet gemist!', en: 'On Tuesday Tom is on time. He didn’t miss the bus!', image: 'practice-stadhuis' },
      { speaker: 'De bediende', nl: 'Goedemorgen, meneer. Heeft u een afspraak?', en: 'Good morning, sir. Do you have an appointment?', image: 'woman-working' },
      { speaker: 'Tom', nl: 'Ja, om tien uur. Ik ben verhuisd, en ik zou mij graag willen inschrijven.', en: 'Yes, at ten. I’ve moved, and I would like to register.', image: 'man' },
      { speaker: 'De bediende', nl: 'Gaat u maar zitten. Mag ik uw identiteitskaart, alstublieft?', en: 'Please take a seat. May I have your identity card, please?', image: 'woman-working' },
      { nl: 'Tom zoekt in zijn portemonnee. Even denkt hij: ik ben hem kwijt! Maar nee, daar is hij.', en: 'Tom looks in his wallet. For a moment he thinks: I’ve lost it! But no, there it is.', image: 'practice-identiteitskaart' },
      { speaker: 'De bediende', nl: 'Zou u dit formulier even kunnen invullen? Uw naam, uw nieuwe adres en uw telefoonnummer.', en: 'Could you just fill in this form? Your name, your new address and your phone number.', image: 'man-writing' },
      { speaker: 'Tom', nl: 'Sorry, mevrouw, ik begrijp het niet helemaal. Kunt u dat even herhalen?', en: 'Sorry, madam, I don’t quite understand. Could you repeat that?', image: 'man-thinking' },
      { speaker: 'De bediende', nl: 'Ja, dat kan. Ik leg het u uit. Hier schrijft u uw adres, en hier de postcode.', en: 'Yes, of course. I’ll explain it to you. Here you write your address, and here the postcode.', image: 'woman-working' },
      { speaker: 'Tom', nl: 'En wat bedoelt u met “vorig adres”?', en: 'And what do you mean by “previous address”?', image: 'man-thinking' },
      { speaker: 'De bediende', nl: 'Dat is het adres waar u vroeger woonde. Kijk eens: zo.', en: 'That is the address where you used to live. Have a look: like this.', image: 'woman-working' },
      { nl: 'Tom vult alles in. Dan ondertekent hij het formulier: daar staat nu zijn handtekening.', en: 'Tom fills everything in. Then he signs the form: his signature is there now.', image: 'form' },
      { speaker: 'De bediende', nl: 'Dank u, meneer. U krijgt binnen twee weken een brief van ons. Dan bent u ingeschreven.', en: 'Thank you, sir. You’ll get a letter from us within two weeks. Then you are registered.', image: 'woman-working' },
      { speaker: 'Tom', nl: 'Bedankt, mevrouw. Een fijne dag nog!', en: 'Thank you, madam. Have a nice day!', image: 'man-happy' },
    ],
  },
  {
    type: 'story', title: 'In het café', image: 'coffee', grammar: ['formal-u', 'polite-zou', 'modal-particles', 'indefinite-pronouns'],
    instruction: 'After the town hall Tom meets Bram and Lotte. Read and listen. Who says u, and who says jij?',
    lines: [
      { speaker: 'Lotte', nl: 'Dag Tom! En, ben je nu ingeschreven?', en: 'Hi Tom! So, are you registered now?', image: 'woman' },
      { speaker: 'Tom', nl: 'Bijna. Ik heb een formulier ingevuld en ondertekend. De bediende was heel aardig.', en: 'Almost. I filled in and signed a form. The clerk was very nice.', image: 'man-happy' },
      { speaker: 'Bram', nl: 'Je had toch je identiteitskaart bij je?', en: 'You did have your identity card with you, didn’t you?', image: 'man' },
      { speaker: 'Tom', nl: 'Ja, hij zat in mijn portemonnee. Ik verlies nooit iets, Bram!', en: 'Yes, it was in my wallet. I never lose anything, Bram!', image: 'man-happy' },
      { speaker: 'De ober', nl: 'Goedemiddag. Wat mag het zijn?', en: 'Good afternoon. What can I get you?', image: 'practice-ober' },
      { speaker: 'Bram', nl: 'Ik zou graag een koffie willen, alstublieft.', en: 'I’d like a coffee, please.', image: 'coffee' },
      { speaker: 'Lotte', nl: 'En voor mij een thee, alstublieft.', en: 'And a tea for me, please.', image: 'tea' },
      { speaker: 'Tom', nl: 'Geeft u mij maar een koffie. En zou u ook iets lekkers hebben?', en: 'I’ll have a coffee. And would you have something nice to eat too?', image: 'coffee' },
      { speaker: 'De ober', nl: 'Wij hebben taart met appels. Wilt u een stuk?', en: 'We have cake with apples. Would you like a piece?', image: 'practice-taart' },
      { speaker: 'Tom', nl: 'Graag! Lotte, jij wil toch ook een stuk?', en: 'Yes, please! Lotte, you want a piece too, don’t you?', image: 'woman' },
      { speaker: 'Lotte', nl: 'Nee, dank je. Nu niet.', en: 'No, thank you. Not now.', image: 'woman' },
      { speaker: 'Bram', nl: 'Mag ik ook de rekening, meneer? Vandaag betaal ik — mijn portemonnee is terug!', en: 'Could I have the bill too, sir? Today I’m paying — my wallet is back!', image: 'practice-rekening' },
    ],
  },
  {
    type: 'drill', title: 'Did you follow?', grammar: ['yes-no-question', 'inversion', 'formal-u'], choices: ['Ja', 'Nee'],
    instruction: 'Questions about the two stories. Answer without looking back.',
    items: [
      { nl: 'Krijgt Tom een brief van de gemeente?', answer: 'Ja' },
      { nl: 'Heeft Tom de bus gemist?', answer: 'Nee' },
      { nl: 'Is Tom zijn identiteitskaart kwijt?', answer: 'Nee' },
      { nl: 'Zegt de bediende u tegen Tom?', answer: 'Ja' },
      { nl: 'Drinkt Lotte koffie?', answer: 'Nee' },
      { nl: 'Wil Lotte een stuk taart?', answer: 'Nee' },
    ],
  },
  {
    type: 'drill', title: 'Answer in full', grammar: ['formal-u', 'polite-zou', 'perfect-hebben', 'separable-perfect', 'question-word', 'want-omdat'],
    instruction: 'Answer each question about the stories with a complete sentence.',
    items: [
      { nl: 'Waarom moet Tom naar het stadhuis?', answer: 'Tom moet zich op zijn nieuwe adres inschrijven.', accept: ['Hij moet zich op zijn nieuwe adres inschrijven.', 'Omdat hij verhuisd is.', 'Tom moet naar het stadhuis, omdat hij verhuisd is.', 'Hij moet zich inschrijven.'] },
      { nl: 'Wanneer is de afspraak van Tom?', answer: 'De afspraak is op dinsdag om tien uur.', accept: ['Op dinsdag om tien uur.', 'Zijn afspraak is op dinsdag om tien uur.'] },
      { nl: 'Wat vraagt de bediende eerst?', answer: 'Zij vraagt of Tom een afspraak heeft.', accept: ['De bediende vraagt of Tom een afspraak heeft.', 'Heeft u een afspraak?'] },
      { nl: 'Wat moet Tom op het formulier schrijven?', answer: 'Tom moet zijn naam, zijn nieuwe adres en zijn telefoonnummer schrijven.', accept: ['Zijn naam, zijn nieuwe adres en zijn telefoonnummer.', 'Hij moet zijn naam, zijn nieuwe adres en zijn telefoonnummer schrijven.'] },
      { nl: 'Wat vraagt Tom aan de bediende?', answer: 'Tom vraagt of zij dat kan herhalen.', accept: ['Kunt u dat even herhalen?', 'Hij vraagt of zij dat kan herhalen.', 'Tom vraagt of zij het kan herhalen.'] },
      { nl: 'Wat is een “vorig adres”?', answer: 'Dat is het adres waar Tom vroeger woonde.', accept: ['Het adres waar Tom vroeger woonde.', 'Het adres waar hij vroeger woonde.', 'Dat is het adres waar hij vroeger woonde.'] },
      { nl: 'Wanneer krijgt Tom een brief?', answer: 'Tom krijgt binnen twee weken een brief.', accept: ['Binnen twee weken.', 'Hij krijgt binnen twee weken een brief.'] },
      { nl: 'Wat bestelt Bram in het café?', answer: 'Bram bestelt een koffie.', accept: ['Een koffie.', 'Hij bestelt een koffie.'] },
      { nl: 'Wie betaalt de rekening?', answer: 'Bram betaalt de rekening.', accept: ['Bram.', 'Bram betaalt.'] },
    ],
  },
  {
    type: 'drill', title: 'More questions, more u', grammar: ['formal-u', 'polite-zou', 'perfect-hebben', 'separable-perfect', 'participle-no-ge', 'reflexive'],
    instruction: 'Answer each question with a complete sentence.',
    items: [
      { nl: 'Heeft Tom het formulier ingevuld?', answer: 'Ja, Tom heeft het formulier ingevuld.', accept: ['Ja, hij heeft het formulier ingevuld.', 'Ja, hij heeft het ingevuld.'] },
      { nl: 'Heeft Tom het formulier ondertekend?', answer: 'Ja, Tom heeft het formulier ondertekend.', accept: ['Ja, hij heeft het formulier ondertekend.', 'Ja, hij heeft het ondertekend.'] },
      { nl: 'Heeft de bediende het uitgelegd?', answer: 'Ja, de bediende heeft het uitgelegd.', accept: ['Ja, zij heeft het uitgelegd.'] },
      { nl: 'Heeft Tom zich al ingeschreven?', answer: 'Ja, Tom heeft zich al ingeschreven.', accept: ['Ja, hij heeft zich al ingeschreven.', 'Ja, Tom heeft zich ingeschreven.'] },
      { nl: 'Was Tom op tijd voor zijn afspraak?', answer: 'Ja, Tom was op tijd voor zijn afspraak.', accept: ['Ja, hij was op tijd.', 'Ja, Tom was op tijd.'] },
      { nl: 'Spreekt de bediende Nederlands met Tom?', answer: 'Ja, de bediende spreekt Nederlands met Tom.', accept: ['Ja, zij spreekt Nederlands met Tom.', 'Ja, zij spreekt Nederlands met hem.'] },
      { nl: 'Zegt de ober u of jij tegen Bram?', answer: 'De ober zegt u tegen Bram.', accept: ['Hij zegt u tegen Bram.', 'Hij zegt u.'] },
      { nl: 'Bestelt Lotte koffie of thee?', answer: 'Lotte bestelt thee.', accept: ['Zij bestelt thee.', 'Lotte bestelt een thee.'] },
      { nl: 'Heeft Bram zijn portemonnee terug?', answer: 'Ja, Bram heeft zijn portemonnee terug.', accept: ['Ja, hij heeft zijn portemonnee terug.'] },
    ],
  },

  // ——— Write ———
  {
    part: 'Write', type: 'drill', title: 'Dictation', grammar: ['formal-u', 'polite-zou', 'modal-particles'],
    instruction: 'Listen to each sentence and write it. Capitals and punctuation do not matter.',
    items: [
      { listen: 'Kunt u mij even helpen?' },
      { listen: 'Mag ik uw identiteitskaart, alstublieft?' },
      { listen: 'Zou u dit formulier kunnen invullen?' },
      { listen: 'Ik zou graag een afspraak willen maken.' },
      { listen: 'Tom heeft het formulier ondertekend.' },
      { listen: 'Wacht u maar even.' },
      { listen: 'Wat bedoelt u, meneer?' },
      { listen: 'Je komt toch ook?' },
    ],
  },
  {
    type: 'drill', title: 'Now say it in Dutch', grammar: ['formal-u', 'polite-zou', 'modal-particles', 'separable-perfect', 'participle-no-ge', 'reflexive'],
    instruction: 'Translate. With strangers, use u.',
    items: [
      { en: 'Good morning, madam. Can you help me?', answer: 'Goedemorgen, mevrouw. Kunt u mij helpen?', accept: ['Goedemorgen mevrouw, kunt u mij helpen?', 'Goedemorgen, mevrouw. Kunt u me helpen?'] },
      { en: 'I would like to register.', answer: 'Ik zou mij graag willen inschrijven.', accept: ['Ik zou me graag willen inschrijven.', 'Ik zou mij graag inschrijven.', 'Ik zou me graag inschrijven.'] },
      { en: 'Do you have an appointment, sir?', answer: 'Heeft u een afspraak, meneer?', accept: ['Hebt u een afspraak, meneer?'] },
      { en: 'What is your address? (polite)', answer: 'Wat is uw adres?' },
      { en: 'Could you repeat that?', answer: 'Zou u dat kunnen herhalen?', accept: ['Kunt u dat herhalen?', 'Zou u dat even kunnen herhalen?', 'Kunt u dat even herhalen?'] },
      { en: 'Tom has filled in the form.', answer: 'Tom heeft het formulier ingevuld.' },
      { en: 'He has signed the form.', answer: 'Hij heeft het formulier ondertekend.' },
      { en: 'Sorry, what do you mean? (polite)', answer: 'Sorry, wat bedoelt u?' },
      { en: 'Do come in. (polite, maar)', answer: 'Komt u maar binnen.' },
      { en: 'You’re coming too, aren’t you? (to a friend)', answer: 'Je komt toch ook?', accept: ['Jij komt toch ook?'] },
    ],
  },
  {
    type: 'drill', title: 'The whole lesson in one round', grammar: ['formal-u', 'polite-zou', 'modal-particles', 'separable-perfect', 'participle-no-ge'],
    instruction: 'A final round: every point of this lesson, mixed. Type every answer.',
    items: [
      { nl: '___ u in Leuven?', cue: 'wonen', answer: 'Woont' },
      { nl: 'Wat is ___ adres?', en: 'your (polite)', answer: 'uw' },
      { nl: '___ u mij kunnen helpen?', en: 'Could you help me?', answer: 'Zou' },
      { nl: 'Ik zou graag een koffie ___.', answer: 'willen' },
      { nl: 'Tom heeft het formulier ___.', cue: 'invullen', answer: 'ingevuld' },
      { nl: 'Tom heeft het formulier ___.', cue: 'ondertekenen', answer: 'ondertekend' },
      { nl: 'Tom heeft zich ___.', cue: 'inschrijven', answer: 'ingeschreven' },
      { nl: 'Komt u ___ binnen.', en: 'Do come in.', answer: 'maar' },
      { nl: 'Je komt ___?', en: 'You’re coming, aren’t you?', answer: 'toch' },
      { en: 'please (polite)', answer: 'alstublieft' },
      { en: 'the counter (at an office)', answer: 'het loket' },
      { listen: 'Zou u dat even kunnen uitleggen?' },
    ],
  },
  {
    type: 'complete', title: 'U bent ingeschreven',
    instruction: 'u and uw for strangers and offices, with the -t that stays; zou for a polite question or wish; even, eens, maar and toch to soften. Tom is registered — and you can ask for anything, politely.',
  },
];
