/** Lesson 20 — extra vocabulary: Tom's new flat, moving in, and where everything goes. */
export default {
  words: [
    { id: 'appartement', dutch: 'appartement', article: 'het', english: 'flat / apartment', image: 'flat', forms: ['appartementen'] },
    { id: 'verdieping', dutch: 'verdieping', article: 'de', english: 'floor (storey)', forms: ['verdiepingen'] },
    { id: 'trap', dutch: 'trap', article: 'de', english: 'stairs (de trap op: up the stairs)', forms: ['trappen'] },
    { id: 'spiegel', dutch: 'spiegel', article: 'de', english: 'mirror', forms: ['spiegels'] },
    { id: 'schilderij', dutch: 'schilderij', article: 'het', english: 'painting', forms: ['schilderijen'] },
    { id: 'plant', dutch: 'plant', article: 'de', english: 'plant', image: 'bookcase', forms: ['planten'] },
    { id: 'bureau', dutch: 'bureau', article: 'het', english: 'desk', forms: ['bureaus'] },
    { id: 'hoek', dutch: 'hoek', article: 'de', english: 'corner (in de hoek: in the corner of a room; op de hoek: on the street corner)', forms: ['hoeken'] },
    { id: 'plank', dutch: 'plank', article: 'de', english: 'shelf / plank', forms: ['planken'] },
    { id: 'midden', dutch: 'midden', english: 'middle (in het midden)' },
    { id: 'links', dutch: 'links', english: 'on the left / to the left' },
    { id: 'rechts', dutch: 'rechts', english: 'on the right / to the right' },
    { id: 'binnen', dutch: 'binnen', english: 'inside / indoors' },
    { id: 'beneden', dutch: 'beneden', english: 'downstairs / below' },
    { id: 'dragen', dutch: 'dragen', english: 'to carry / to wear', forms: ['draag', 'draagt', 'gedragen', 'droeg', 'droegen'] },
    { id: 'zwaar', dutch: 'zwaar', english: 'heavy', forms: ['zware', 'zwaarder', 'zwaarst', 'zwaarste'] },
    { id: 'leeg', dutch: 'leeg', english: 'empty', forms: ['lege'] },
    { id: 'vol', dutch: 'vol', english: 'full', forms: ['volle'] },
    { id: 'klaar', dutch: 'klaar', english: 'ready / finished' },
    { id: 'alle', dutch: 'alle', english: 'all (alle dozen: all the boxes)' },
    { id: 'spullen', dutch: 'spullen', article: 'de', english: 'things, stuff (always plural)' },
    { id: 'uitpakken', dutch: 'uitpakken', english: 'to unpack (Tom pakt de dozen uit)', forms: ['pak', 'pakt', 'uitpak', 'uitpakt', 'uitgepakt', 'pakte', 'pakten', 'uitpakte', 'uitpakten'] },
    { id: 'ophangen', dutch: 'ophangen', english: 'to hang up, to put up (a lamp, a mirror)', forms: ['ophang', 'ophangt', 'opgehangen', 'ophing', 'ophingen'] },
    { id: 'plafond', dutch: 'plafond', article: 'het', english: 'ceiling', image: 'lamp', forms: ['plafonds'] },
    { id: 'glas', dutch: 'glas', article: 'het', english: 'glass', image: 'water', forms: ['glazen'] },
    { id: 'koelkast', dutch: 'koelkast', article: 'de', english: 'fridge', forms: ['koelkasten'] },
    { id: 'kleren', dutch: 'kleren', article: 'de', english: 'clothes (always plural)' },
    { id: 'vaas', dutch: 'vaas', article: 'de', english: 'vase', image: 'flowers', forms: ['vazen'] },
    { id: 'zak', dutch: 'zak', article: 'de', english: 'pocket / (plastic or paper) bag', forms: ['zakken'] },
    { id: 'gezellig', dutch: 'gezellig', english: 'cosy, pleasant (of a place or an evening)', forms: ['gezellige', 'gezelliger'] },
  ],
};
