/** Lesson 23 — extra vocabulary: study, group work and the order of events. */
export default {
  words: [
    { id: 'groep', dutch: 'groep', article: 'de', english: 'group', image: 'students-group', forms: ['groepen', 'groepswerk'] },
    { id: 'opdracht', dutch: 'opdracht', article: 'de', english: 'assignment / task', forms: ['opdrachten'] },
    { id: 'verslag', dutch: 'verslag', article: 'het', english: 'report', forms: ['verslagen'] },
    { id: 'bespreken', dutch: 'bespreken', english: 'to discuss', forms: ['bespreek', 'bespreekt', 'besproken', 'besprak', 'bespraken'] },
    { id: 'afspreken', dutch: 'afspreken', english: 'to arrange / to agree to meet', forms: ['afspreekt', 'afgesproken'] },
    { id: 'samenwerken', dutch: 'samenwerken', english: 'to work together', forms: ['samenwerkt', 'samengewerkt'] },
    { id: 'eerst', dutch: 'eerst', english: 'first (adverb)' },
    { id: 'daarna', dutch: 'daarna', english: 'after that / afterwards' },
    { id: 'uiteindelijk', dutch: 'uiteindelijk', english: 'in the end / finally' },
    { id: 'meteen', dutch: 'meteen', english: 'immediately' },
    { id: 'pauze', dutch: 'pauze', article: 'de', english: 'break', forms: ['pauzes'] },
    { id: 'deadline', dutch: 'deadline', article: 'de', english: 'deadline', forms: ['deadlines'] },
    { id: 'verdelen', dutch: 'verdelen', english: 'to divide / to share out', forms: ['verdeel', 'verdeelt', 'verdeeld', 'verdeelde', 'verdeelden'] },
    { id: 'deel', dutch: 'deel', article: 'het', english: 'part (plural delen — also the verb delen, to share)', forms: ['delen'] },
    { id: 'indienen', dutch: 'indienen', english: 'to hand in / to submit (Belgium; NL also inleveren)', forms: ['dien', 'dient', 'dienen', 'indien', 'indient', 'ingediend', 'diende', 'dienden'] },
    { id: 'mail', dutch: 'mail', article: 'de', english: 'e-mail (mailen: to e-mail)', forms: ['mails', 'mailen', 'mailt', 'gemaild', 'mailde', 'mailden'] },
    { id: 'ander', dutch: 'ander', english: 'other (de andere studenten, een ander idee)', forms: ['andere'] },
    { id: 'elkaar', dutch: 'elkaar', english: 'each other' },
    { id: 'idee', dutch: 'idee', article: 'het', english: 'idea', forms: ['ideeën'] },
    { id: 'minuut', dutch: 'minuut', article: 'de', english: 'minute', image: 'clock', forms: ['minuten'] },
    { id: 'tijdens', dutch: 'tijdens', english: 'during (+ a noun)' },
    { id: 'druk', dutch: 'druk', english: 'busy (het druk hebben: to be busy)' },
    { id: 'hard', dutch: 'hard', english: 'hard (hard werken)', forms: ['harde', 'harder'] },
    { id: 'genoeg', dutch: 'genoeg', english: 'enough' },
    { id: 'weinig', dutch: 'weinig', english: 'little / few (weinig tijd)' },
    { id: 'vanavond', dutch: 'vanavond', english: 'this evening / tonight' },
    { id: 'regen', dutch: 'regen', article: 'de', english: 'rain (the noun; the verb is regenen)', image: 'rain' },
    { id: 'paraplu', dutch: 'paraplu', article: 'de', english: 'umbrella', image: 'rain' },
  ],
};
