import React, { useState } from 'react';
import { ArrowRight, RotateCcw, Check, Sprout } from 'lucide-react';
import { words } from './content.js';
import { getDueWords, isAnswerCorrect } from './learning.js';
import { AudioButton, useAudio } from './audio.jsx';

export default function Review({ state, encounter, navigate }) {
  const { stop } = useAudio();
  const [queue, setQueue] = useState(null);
  const [index, setIndex] = useState(0);
  const [typed, setTyped] = useState('');
  const [revealed, setRevealed] = useState(false);
  const [correct, setCorrect] = useState(false);
  const [sessionId, setSessionId] = useState('');
  const [results, setResults] = useState({ recalled: 0, again: 0 });
  const due = getDueWords(state, words);
  const encountered = words.filter(w => state.words[w.id]?.encounters > 0);
  const word = queue?.[index];
  function start(practice = false) { stop(); setQueue((practice ? encountered : due).slice(0, 11)); setIndex(0); setTyped(''); setRevealed(false); setSessionId(String(Date.now())); setResults({ recalled: 0, again: 0 }); }
  function check(e, show = false) { e?.preventDefault(); if (revealed) return; const right = !show && isAnswerCorrect(typed, word.dutch); setCorrect(right); setRevealed(true); encounter([word.id], right, `review:${sessionId}:${index}`); setResults(r => ({ recalled: r.recalled + Number(right), again: r.again + Number(!right) })); }
  function next() { stop(); setIndex(index + 1); setTyped(''); setRevealed(false); }
  if (queue && index === queue.length) return <div className="standard-page review-page page-enter"><div className="review-complete-mark"><Sprout size={40} strokeWidth={1.3} /></div><h1>A little more familiar.</h1><p className="page-intro">{results.recalled} {results.recalled === 1 ? 'word recalled' : 'words recalled'}. {results.again ? `${results.again} to meet again soon.` : 'A good place to pause.'}<br />Every return is part of learning.</p><button className="primary-button" onClick={() => navigate('book')}>Back to the book <ArrowRight size={17} /></button>{results.again > 0 && <button className="text-link review-again" onClick={() => start(false)}><RotateCcw size={15} /> Revisit the tricky words</button>}</div>;
  return <div className="standard-page review-page page-enter"><div className="eyebrow">FAMILIAR THINGS, MET AGAIN</div><h1>A little review.</h1><p className="page-intro">No timer. No pressure.<br />Just a few words finding their way into your memory.</p>{word ? <div className="review-card"><div className="review-card-top"><span className="small-caps">BRING THE DUTCH TO MIND</span><span>{index + 1} / {queue.length}</span></div>{word.image ? <img src={`/images/${word.image}.svg`} alt="" /> : <div className="review-type-art"><span>abc</span><Sprout size={25} /></div>}<h2>{word.english}</h2><form onSubmit={check}><label className="sr-only" htmlFor="review-word">Dutch word for {word.english}</label><input id="review-word" lang="nl" autoComplete="off" spellCheck="false" autoFocus value={typed} onChange={e => setTyped(e.target.value)} disabled={revealed} placeholder="The Dutch word…" />{revealed ? <div className={`review-answer ${correct ? 'correct' : ''}`} role="status"><span>{correct ? <Check size={19} /> : <RotateCcw size={19} />}</span><div><strong lang="nl">{word.dutch}</strong><small>{correct ? 'Yes. A little more familiar.' : 'You’ll meet this word again soon.'}</small></div><AudioButton text={word.dutch} /></div> : <button type="button" className="subtle-link" onClick={e => check(e, true)}>I don’t remember yet</button>}{revealed ? <button type="button" className="primary-button full-width" onClick={next}>{index + 1 === queue.length ? 'Finish this review' : 'Another familiar word'}<ArrowRight size={17} /></button> : <button className="primary-button full-width" type="submit" disabled={!typed.trim()}>Check the word <Check size={17} /></button>}</form></div> : <div className="review-start"><div className="review-icon"><RotateCcw size={30} strokeWidth={1.3} /></div><h2>{due.length ? `${due.length} familiar ${due.length === 1 ? 'word is' : 'words are'} waiting.` : encountered.length ? 'Everything has had a little attention.' : 'First, a small beginning.'}</h2><p>{due.length ? 'Recall the Dutch word, then hear it once more.' : encountered.length ? 'Your next review will be ready after a little time has passed. You can also practise now.' : 'Your review shelf fills as you read. Meet a few words in the first lesson, then return here.'}</p>{due.length ? <button className="primary-button" onClick={() => start()}>Begin a little review <ArrowRight size={17} /></button> : encountered.length ? <button className="primary-button" onClick={() => start(true)}>Practise familiar words <ArrowRight size={17} /></button> : <button className="primary-button" onClick={() => navigate('book')}>Open the book <ArrowRight size={17} /></button>}<div className="review-explanation">Words return after 10 minutes, then at gradually longer intervals.<br />A difficult word comes back sooner. Early practice stays welcome.</div></div>}</div>;
}
