import { entry as w, line, question } from './entry.js';

export default {
  id: 'a1-doen', after: 'vandaag', volume: 0,
  title: 'Vandaag tekenen en wandelen we', subtitle: 'Ten everyday actions and ten useful objects. Practise present endings and verb-second order.', image: 'woman-walking',
  reviewGrammar: ['present-regular', 'spelling-stem', 'yes-no-question', 'v2-inversion', 'adverb-position'],
  reminders: [
    'These verbs follow the present pattern: ik fiets, jij fietst, wij fietsen; ik luister, jij luistert, wij luisteren. A question with jij loses -t: fiets jij? Other examples are ik kijk, zoek, open, draag, haal, pak, teken and wandel. Add -t with hij/zij; use the infinitive with wij/jullie/zij (they).',
    'Keep the long vowel in dragen → draag and halen → haal; remove one consonant in pakken → pak. Begin with Vandaag or Morgen and the verb still comes second: vandaag tekent Lotte. Use luisteren naar and kijken naar when saying what you listen to or look at.',
  ],
  entries: [
    w('fietsen', null, 'to cycle', ['Lotte fietst naar het park.', 'Lotte cycles to the park.'], ['Vandaag fiets ik naar school.', 'Today I cycle to school.'], { forms: ['fiets', 'fietst'] }),
    w('luisteren', null, 'to listen', ['Ik luister naar de radio.', 'I listen to the radio.'], ['Vandaag luistert Bram naar muziek.', 'Today Bram listens to music.'], { forms: ['luister', 'luistert'] }),
    w('kijken', null, 'to look; to watch', ['Wij kijken naar de trein.', 'We look at the train.'], ['Het kind kijkt naar de kat.', 'The child looks at the cat.'], { forms: ['kijk', 'kijkt'] }),
    w('zoeken', null, 'to look for; to search', ['Ik zoek mijn sleutel.', 'I am looking for my key.'], ['Bram zoekt een pen.', 'Bram is looking for a pen.'], { forms: ['zoek', 'zoekt'] }),
    w('openen', null, 'to open', ['Lotte opent de deur.', 'Lotte opens the door.'], ['Ik open het raam.', 'I open the window.'], { forms: ['open', 'opent'], laterForms: { 'wordt-gebouwd': ['geopend', 'opende'] } }),
    w('dragen', null, 'to wear; to carry', ['Bram draagt een wit hemd.', 'Bram wears a white button-up shirt.'], ['Ik draag een grote tas.', 'I carry a big bag.'], { forms: ['draag', 'draagt'] }),
    w('halen', null, 'to fetch; to get', ['Ik haal melk.', 'I get milk.'], ['Morgen haalt Lotte brood.', 'Tomorrow Lotte gets bread.'], { forms: ['haal', 'haalt'] }),
    w('pakken', null, 'to take; to grab', ['Bram pakt de krant.', 'Bram picks up the newspaper.'], ['Ik pak mijn jas.', 'I take my coat.'], { forms: ['pak', 'pakt'] }),
    w('tekenen', null, 'to draw', ['Het kind tekent een huis.', 'The child draws a house.'], ['Vandaag tekenen wij een boom.', 'Today we draw a tree.'], { forms: ['teken', 'tekent'] }),
    w('wandelen', null, 'to walk; to go for a walk', ['Wij wandelen in het park.', 'We walk in the park.'], ['Morgen wandelt Lotte met Max.', 'Tomorrow Lotte walks with Max.'], { forms: ['wandel', 'wandelt'] }),
    w('muziek', 'de', 'music', ['Bram luistert graag naar muziek.', 'Bram likes listening to music.'], ['De muziek is mooi.', 'The music is beautiful.']),
    w('radio', 'de', 'radio', ['Ik luister naar de radio.', 'I listen to the radio.'], ['De radio is niet kapot.', 'The radio is not broken.']),
    w('televisie', 'de', 'television', ['Bram kijkt graag televisie.', 'Bram likes watching television.'], ['De televisie is groot.', 'The television is big.']),
    w('krant', 'de', 'newspaper', ['Lotte leest de krant.', 'Lotte reads the newspaper.'], ['De krant is oud.', 'The newspaper is old.']),
    w('brief', 'de', 'letter (message)', ['Ik schrijf een brief.', 'I write a letter.'], ['Bram leest de brief.', 'Bram reads the letter.']),
    w('pen', 'de', 'pen', ['Ik schrijf met een blauwe pen.', 'I write with a blue pen.'], ['Mijn pen is kapot.', 'My pen is broken.']),
    w('potlood', 'het', 'pencil', ['Het kind tekent met een potlood.', 'The child draws with a pencil.'], ['Het potlood is geel.', 'The pencil is yellow.']),
    w('papier', 'het', 'paper', ['Ik teken op papier.', 'I draw on paper.'], ['Het papier is wit.', 'The paper is white.']),
    w('fles', 'de', 'bottle', ['Dit is een fles water.', 'This is a bottle of water.'], ['De fles is leeg.', 'The bottle is empty.']),
    w('glas', 'het', 'glass (drinking vessel)', ['Bram drinkt een glas water.', 'Bram drinks a glass of water.'], ['Het glas is vol.', 'The glass is full.']),
  ],
  grammarItems: [
    { nl: 'Ik ___ naar school.', cue: 'fietsen', answer: 'fiets', en: 'I cycle to school.' },
    { nl: 'Jij ___ naar de radio.', cue: 'luisteren', answer: 'luistert', en: 'You listen to the radio.' },
    { nl: '___ jij naar de trein?', cue: 'kijken', answer: 'Kijk', en: 'Do you look at the train?' },
    { nl: 'Bram ___ de pen.', cue: 'zoeken', answer: 'zoekt', en: 'Bram is looking for the pen.' },
    { nl: 'Lotte ___ het raam.', cue: 'openen', answer: 'opent', en: 'Lotte opens the window.' },
    { nl: 'Wij ___ een jas.', cue: 'dragen', answer: 'dragen', en: 'We wear a coat.' },
    { nl: 'Jullie ___ brood.', cue: 'halen', answer: 'halen', en: 'You all get bread.' },
    { nl: 'Het kind ___ een potlood.', cue: 'pakken', answer: 'pakt', en: 'The child takes a pencil.' },
    { nl: 'Ik ___ een boom.', cue: 'tekenen', answer: 'teken', en: 'I draw a tree.' },
    { nl: 'Zij ___ in het park.', cue: 'wandelen', answer: 'wandelen', en: 'They walk in the park.' },
    { nl: 'Lotte fietst vandaag naar school.', task: 'Begin with Vandaag.', answer: 'Vandaag fietst Lotte naar school.' },
    { nl: 'Ik luister nu naar muziek.', task: 'Begin with Nu.', answer: 'Nu luister ik naar muziek.' },
    { nl: 'Bram zoekt vandaag de krant.', task: 'Begin with Vandaag.', answer: 'Vandaag zoekt Bram de krant.' },
    { nl: 'Wij tekenen morgen een huis.', task: 'Begin with Morgen.', answer: 'Morgen tekenen wij een huis.' },
    { nl: 'Jij pakt de fles.', task: 'Make a yes/no question.', answer: 'Pak jij de fles?' },
    { nl: 'Ik draag een jas.', task: 'Make the sentence negative.', answer: 'Ik draag geen jas.' },
    { nl: 'Bram opent de deur.', task: 'Make a yes/no question.', answer: 'Opent Bram de deur?' },
    { nl: 'Lotte leest de krant.', task: 'Add graag in the usual position.', answer: 'Lotte leest graag de krant.' },
    { nl: 'Het glas is vol.', task: 'Make the sentence negative.', answer: 'Het glas is niet vol.' },
    { nl: 'Ik schrijf met een pen.', task: 'Make a yes/no question.', answer: 'Schrijf ik met een pen?' },
  ],
  story: [
    line('Vandaag werkt Lotte thuis. Zij draagt een rode trui.', 'Today Lotte works at home. She wears a red sweater.'),
    line('Zij opent het raam en pakt de krant.', 'She opens the window and picks up the newspaper.'),
    line('Bram luistert naar de radio. Dan zoekt hij de pen.', 'Bram listens to the radio. Then he looks for the pen.'),
    line('Ik schrijf een brief met een blauwe pen.', 'I write a letter with a blue pen.'),
    line('Het kind tekent een boom op wit papier.', 'The child draws a tree on white paper.'),
    line('Het kind heeft een geel potlood.', 'The child has a yellow pencil.'),
    line('Morgen haalt Lotte brood. Dan wandelt zij met Max in het park.', 'Tomorrow Lotte gets bread. Then she walks with Max in the park.'),
    line('Bram drinkt een glas water. De fles is leeg.', 'Bram drinks a glass of water. The bottle is empty.'),
  ],
  questions: [
    question('Waar werkt Lotte vandaag?', 'Lotte werkt vandaag thuis.', 'Where does Lotte work today?', ['Lotte werkt thuis.']),
    question('Wat opent Lotte?', 'Lotte opent het raam.', 'What does Lotte open?'),
    question('Wat zoekt Bram?', 'Bram zoekt de pen.', 'What is Bram looking for?', ['Bram zoekt een pen.', 'Bram zoekt de pen.']),
    question('Wat tekent het kind?', 'Het kind tekent een boom.', 'What does the child draw?'),
    question('Is het potlood geel?', 'Ja, het potlood is geel.', 'Is the pencil yellow?'),
    question('Wat haalt Lotte morgen?', 'Lotte haalt morgen brood.', 'What does Lotte get tomorrow?', ['Lotte haalt brood.']),
    question('Waar wandelt Lotte met Max?', 'Lotte wandelt met Max in het park.', 'Where does Lotte walk with Max?', ['Lotte wandelt in het park.']),
    question('Is de fles vol?', 'Nee, de fles is leeg.', 'Is the bottle full?', ['Nee, de fles is niet vol.']),
  ],
};
