import { entry as w, line, question } from './entry.js';

export default {
  id: 'a1-lichaam', after: 'ik-kan', volume: 0,
  title: 'Waar heb jij pijn?', subtitle: 'Twenty body and health words. Revisit possessives, plurals, questions and modal verbs.', image: 'doctor',
  reviewGrammar: ['possessives', 'plural', 'question-word', 'modals', 'adjective-e'],
  reminders: [
    'Use hebben with pain: ik heb pijn in mijn rug; waar heb jij pijn? Use zijn with healthy or ill: ik ben gezond; ik ben ziek. These are vocabulary examples for describing how you feel.',
    'Keep the familiar word order with modal verbs: ik wil naar de dokter gaan; de dokter kan helpen. Practise irregular plurals too: het been → de benen, het oog → de ogen, de voet → de voeten, de tand → de tanden. A noun stays one vocabulary entry when its form changes.',
  ],
  entries: [
    w('hoofd', 'het', 'head', ['Dit is mijn hoofd.', 'This is my head.'], ['Het kind heeft een klein hoofd.', 'The child has a small head.'], { forms: ['hoofden'] }),
    w('buik', 'de', 'belly; abdomen', ['Ik heb pijn in mijn buik.', 'I have pain in my belly.'], ['Mijn buik is niet groot.', 'My belly is not big.'], { forms: ['buiken'] }),
    w('rug', 'de', 'back (body)', ['Ik heb pijn in mijn rug.', 'I have pain in my back.'], ['De dokter kijkt naar mijn rug.', 'The doctor looks at my back.'], { forms: ['ruggen'] }),
    w('hand', 'de', 'hand', ['Ik heb twee handen.', 'I have two hands.'], ['Mijn handen zijn schoon.', 'My hands are clean.'], { forms: ['handen'] }),
    w('arm', 'de', 'arm', ['Bram heeft pijn in zijn arm.', 'Bram has pain in his arm.'], ['Ik heb twee armen.', 'I have two arms.'], { forms: ['armen'] }),
    w('been', 'het', 'leg', ['Ik heb pijn in mijn been.', 'I have pain in my leg.'], ['Mijn benen zijn moe.', 'My legs are tired.'], { forms: ['benen'] }),
    w('voet', 'de', 'foot', ['Mijn voet is niet schoon.', 'My foot is not clean.'], ['Ik heb twee voeten.', 'I have two feet.'], { forms: ['voeten'] }),
    w('oog', 'het', 'eye', ['Ik heb twee ogen.', 'I have two eyes.'], ['Mijn ogen zijn groen.', 'My eyes are green.'], { forms: ['ogen'] }),
    w('oor', 'het', 'ear', ['Dit is mijn oor.', 'This is my ear.'], ['Mijn oren zijn klein.', 'My ears are small.'], { forms: ['oren'] }),
    w('neus', 'de', 'nose', ['Mijn neus is klein.', 'My nose is small.'], ['De neus is rood.', 'The nose is red.'], { forms: ['neuzen'] }),
    w('mond', 'de', 'mouth', ['Dit is mijn mond.', 'This is my mouth.'], ['Mijn mond is niet groot.', 'My mouth is not big.'], { forms: ['monden'] }),
    w('keel', 'de', 'throat', ['Ik heb pijn in mijn keel.', 'I have pain in my throat.'], ['De dokter kijkt in mijn keel.', 'The doctor looks in my throat.'], { forms: ['kelen'] }),
    w('tand', 'de', 'tooth', ['Mijn tand is wit.', 'My tooth is white.'], ['Ik heb schone tanden.', 'I have clean teeth.'], { forms: ['tanden'] }),
    w('gezicht', 'het', 'face', ['Mijn gezicht is schoon.', 'My face is clean.'], ['Het kind heeft een blij gezicht.', 'The child has a happy face.'], { forms: ['gezichten'] }),
    w('lichaam', 'het', 'body', ['Mijn lichaam is moe.', 'My body is tired.'], ['Ik heb pijn in mijn lichaam.', 'I have pain in my body.'], { forms: ['lichamen'] }),
    w('pijn', 'de', 'pain', ['Ik heb pijn in mijn rug.', 'I have pain in my back.'], ['Waar heb jij pijn?', 'Where do you have pain?']),
    w('dokter', 'de', 'doctor', ['Ik ga naar de dokter.', 'I am going to the doctor.'], ['De dokter wil helpen.', 'The doctor wants to help.'], { forms: ['dokters'] }),
    w('apotheek', 'de', 'pharmacy', ['Waar is de apotheek?', 'Where is the pharmacy?'], ['Vandaag ga ik naar de apotheek.', 'Today I am going to the pharmacy.'], { forms: ['apotheken'] }),
    w('medicijn', 'het', 'medicine (a medication)', ['Het medicijn is in de doos.', 'The medicine is in the box.'], ['Ik heb mijn medicijn.', 'I have my medicine.'], { forms: ['medicijnen'] }),
    w('gezond', null, 'healthy', ['Dit is een gezond kind.', 'This is a healthy child.'], ['Mijn moeder is gezond.', 'My mother is healthy.'], { forms: ['gezonde'] }),
  ],
  grammarItems: [
    { nl: 'Ik ___ pijn in mijn rug.', cue: 'hebben', answer: 'heb', en: 'I have pain in my back.' },
    { nl: 'Waar ___ jij pijn?', cue: 'hebben', answer: 'heb', en: 'Where do you have pain?' },
    { nl: 'Bram heeft pijn in ___ arm.', answer: 'zijn', en: 'Bram has pain in his arm.' },
    { nl: 'Lotte heeft pijn in ___ voet.', answer: 'haar', en: 'Lotte has pain in her foot.' },
    { nl: 'Ik heb twee ___.', cue: 'hand', answer: 'handen', en: 'I have two hands.' },
    { nl: 'Mijn ___ zijn groen.', cue: 'oog', answer: 'ogen', en: 'My eyes are green.' },
    { nl: 'Ik heb twee ___.', cue: 'been', answer: 'benen', en: 'I have two legs.' },
    { nl: 'Mijn twee ___ zijn schoon.', cue: 'voet', answer: 'voeten', en: 'My two feet are clean.' },
    { nl: 'Mijn ___ zijn wit.', cue: 'tand', answer: 'tanden', en: 'My teeth are white.' },
    { nl: 'Dit is een ___ kind.', cue: 'gezond', answer: 'gezond', en: 'This is a healthy child.' },
    { nl: 'Jij hebt pijn in jouw buik.', task: 'Ask where jij has pain, beginning with Waar.', answer: 'Waar heb jij pijn?' },
    { nl: 'De dokter kan helpen.', task: 'Make a yes/no question.', answer: 'Kan de dokter helpen?' },
    { nl: 'Ik ben gezond.', task: 'Make the sentence negative.', answer: 'Ik ben niet gezond.' },
    { nl: 'Ik heb pijn.', task: 'Make the sentence negative.', answer: 'Ik heb geen pijn.' },
    { nl: 'Ik wil naar de dokter ___.', cue: 'gaan', answer: 'gaan', en: 'I want to go to the doctor.' },
    { nl: 'De dokter ___ helpen.', cue: 'kunnen', answer: 'kan', en: 'The doctor can help.' },
    { nl: 'Vandaag ___ ik naar de apotheek.', cue: 'gaan', answer: 'ga', en: 'Today I am going to the pharmacy.' },
    { nl: 'Dit is een ___ hand.', cue: 'schoon', answer: 'schone', en: 'This is a clean hand.' },
    { nl: 'Het ___ gezicht is mooi.', cue: 'blij', answer: 'blije', en: 'The happy face is beautiful.' },
    { nl: 'De twee ___ zijn klein.', cue: 'oor', answer: 'oren', en: 'The two ears are small.' },
  ],
  story: [
    line('Vandaag heeft Bram pijn in zijn rug.', 'Today Bram has pain in his back.'),
    line('Hij wil naar de dokter gaan.', 'He wants to go to the doctor.'),
    line('De dokter: waar heb jij pijn?', 'The doctor: where do you have pain?'),
    line('Ik heb pijn in mijn rug. Mijn benen zijn ook moe.', 'I have pain in my back. My legs are tired too.'),
    line('De dokter kijkt naar zijn rug.', 'The doctor looks at his back.'),
    line('Lotte is gezond. Zij heeft geen pijn.', 'Lotte is healthy. She has no pain.'),
    line('Noor heeft groene ogen en een klein gezicht.', 'Noor has green eyes and a small face.'),
    line('De apotheek is in de stad. Bram gaat naar de apotheek.', 'The pharmacy is in town. Bram goes to the pharmacy.'),
  ],
  questions: [
    question('Waar heeft Bram pijn?', 'Bram heeft pijn in zijn rug.', 'Where does Bram have pain?'),
    question('Wil Bram naar de dokter gaan?', 'Ja, Bram wil naar de dokter gaan.', 'Does Bram want to go to the doctor?', ['Ja, Bram wil naar de dokter.']),
    question('Zijn zijn benen moe?', 'Ja, zijn benen zijn moe.', 'Are his legs tired?'),
    question('Is Lotte gezond?', 'Ja, Lotte is gezond.', 'Is Lotte healthy?'),
    question('Heeft Lotte pijn?', 'Nee, Lotte heeft geen pijn.', 'Does Lotte have pain?'),
    question('Zijn de ogen groen?', 'Ja, de ogen zijn groen.', 'Are the eyes green?'),
    question('Is het gezicht groot?', 'Nee, het gezicht is klein.', 'Is the face big?', ['Nee, het gezicht is niet groot.']),
    question('Waar is de apotheek?', 'De apotheek is in de stad.', 'Where is the pharmacy?'),
  ],
};
