import { entry as w, line, question } from './entry.js';

export default {
  id: 'a1-kleuren', after: 'ik-heb', volume: 0,
  title: 'Een rode jas, een leeg huis', subtitle: 'Twenty colours and descriptions. Practise adjective endings, zijn and negation.', image: 'coat',
  reviewGrammar: ['adjective-e', 'zijn', 'hebben', 'geen-niet', 'yes-no-question'],
  reminders: [
    'After is, use the plain adjective: de jas is rood. Before a noun, usually add -e: een rode jas, de rode jas, het rode shirt. With een and a singular het-word, use the plain form: een rood shirt.',
    'Watch spelling: rood → rode, wit → witte, grijs → grijze, schoon → schone, leeg → lege, kapot → kapotte. Roze and oranje keep the same form here: een roze trui, een oranje pet. Licht here means light in colour or bright, not a lamp.',
  ],
  entries: [
    w('rood', null, 'red', ['Lotte heeft een rode jas.', 'Lotte has a red coat.'], ['Het shirt is rood.', 'The shirt is red.'], { forms: ['rode'] }),
    w('blauw', null, 'blue', ['Ik heb een blauwe broek.', 'I have blue trousers.'], ['De sjaal is blauw.', 'The scarf is blue.'], { forms: ['blauwe'] }),
    w('groen', null, 'green', ['De deur is groen.', 'The door is green.'], ['Dit is een groen hemd.', 'This is a green button-up shirt.'], { forms: ['groene'] }),
    w('geel', null, 'yellow', ['Bram heeft een gele pet.', 'Bram has a yellow cap.'], ['Het gele shirt is nieuw.', 'The yellow shirt is new.'], { forms: ['gele'] }),
    w('zwart', null, 'black', ['De kat is zwart.', 'The cat is black.'], ['Ik heb een zwarte hoed.', 'I have a black hat.'], { forms: ['zwarte'] }),
    w('wit', null, 'white', ['Het hemd is wit.', 'The button-up shirt is white.'], ['De witte sok is klein.', 'The white sock is small.'], { forms: ['witte'] }),
    w('bruin', null, 'brown', ['De hond is bruin.', 'The dog is brown.'], ['Bram heeft een bruine riem.', 'Bram has a brown belt.'], { forms: ['bruine'] }),
    w('grijs', null, 'grey', ['De oude man heeft een grijze hoed.', 'The old man has a grey hat.'], ['De muur is grijs.', 'The wall is grey.'], { forms: ['grijze'] }),
    w('oranje', null, 'orange (colour)', ['Het kind heeft een oranje pet.', 'The child has an orange cap.'], ['De paraplu is oranje.', 'The umbrella is orange.']),
    w('roze', null, 'pink', ['Lotte heeft een roze trui.', 'Lotte has a pink sweater.'], ['De rok is roze.', 'The skirt is pink.']),
    w('paars', null, 'purple', ['Mijn sjaal is paars.', 'My scarf is purple.'], ['Dit is een paarse jurk.', 'This is a purple dress.'], { forms: ['paarse'] }),
    w('licht', null, 'light (colour); bright', ['De kamer is licht.', 'The room is bright.'], ['Ik heb een lichte broek.', 'I have light-coloured trousers.'], { forms: ['lichte'] }),
    w('donker', null, 'dark', ['De slaapkamer is donker.', 'The bedroom is dark.'], ['Bram heeft een donker vest.', 'Bram has a dark cardigan.'], { forms: ['donkere'] }),
    w('schoon', null, 'clean', ['De keuken is schoon.', 'The kitchen is clean.'], ['Dit is een schoon shirt.', 'This is a clean shirt.'], { forms: ['schone'] }),
    w('vuil', null, 'dirty', ['De vloer is vuil.', 'The floor is dirty.'], ['Ik heb een vuile schoen.', 'I have a dirty shoe.'], { forms: ['vuile'] }),
    w('leeg', null, 'empty', ['De portemonnee is leeg.', 'The wallet is empty.'], ['Dit is een leeg huis.', 'This is an empty house.'], { forms: ['lege'] }),
    w('vol', null, 'full', ['De kast is vol.', 'The cupboard is full.'], ['Mijn volle tas is groot.', 'My full bag is big.'], { forms: ['volle'] }),
    w('zacht', null, 'soft', ['De trui is zacht.', 'The sweater is soft.'], ['Lotte heeft een zachte sjaal.', 'Lotte has a soft scarf.'], { forms: ['zachte'] }),
    w('hard', null, 'hard; firmly', ['De stoel is hard.', 'The chair is hard.'], ['Dit is een hard bed.', 'This is a hard bed.'], { forms: ['harde'] }),
    w('kapot', null, 'broken', ['Mijn telefoon is kapot.', 'My phone is broken.'], ['Bram heeft een kapot horloge.', 'Bram has a broken watch.'], { forms: ['kapotte'] }),
  ],
  grammarItems: [
    { nl: 'Ik heb een ___ jas.', cue: 'rood', answer: 'rode', en: 'I have a red coat.' },
    { nl: 'Dit is een ___ shirt.', cue: 'rood', answer: 'rood', en: 'This is a red shirt.' },
    { nl: 'Het ___ shirt is nieuw.', cue: 'blauw', answer: 'blauwe', en: 'The blue shirt is new.' },
    { nl: 'De deur is ___.', cue: 'groen', answer: 'groen', en: 'The door is green.' },
    { nl: 'Dit is een ___ sok.', cue: 'wit', answer: 'witte', en: 'This is a white sock.' },
    { nl: 'Bram heeft een ___ hoed.', cue: 'grijs', answer: 'grijze', en: 'Bram has a grey hat.' },
    { nl: 'Het kind heeft een ___ pet.', cue: 'oranje', answer: 'oranje', en: 'The child has an orange cap.' },
    { nl: 'Ik heb een ___ trui.', cue: 'roze', answer: 'roze', en: 'I have a pink sweater.' },
    { nl: 'Dit is een ___ hemd.', cue: 'schoon', answer: 'schoon', en: 'This is a clean button-up shirt.' },
    { nl: 'De ___ portemonnee is oud.', cue: 'leeg', answer: 'lege', en: 'The empty wallet is old.' },
    { nl: 'Het horloge is kapot.', task: 'Make a yes/no question.', answer: 'Is het horloge kapot?' },
    { nl: 'De keuken is schoon.', task: 'Make the sentence negative.', answer: 'De keuken is niet schoon.' },
    { nl: 'Jij hebt een witte sok.', task: 'Make a yes/no question.', answer: 'Heb jij een witte sok?' },
    { nl: 'Bram heeft een paarse sjaal.', task: 'Say that Bram does not have a purple scarf.', answer: 'Bram heeft geen paarse sjaal.' },
    { nl: 'De kamer is donker.', task: 'Make the sentence negative.', answer: 'De kamer is niet donker.' },
    { nl: 'De stoel is zacht.', task: 'Make a yes/no question.', answer: 'Is de stoel zacht?' },
    { nl: 'Dit ___ een volle tas.', answer: 'is', en: 'This is a full bag.' },
    { nl: 'Wij ___ een lege kast.', answer: 'hebben', en: 'We have an empty cupboard.' },
    { nl: 'De ___ telefoon is oud.', cue: 'kapot', answer: 'kapotte', en: 'The broken phone is old.' },
    { nl: 'Lotte heeft een ___ sjaal.', cue: 'zacht', answer: 'zachte', en: 'Lotte has a soft scarf.' },
  ],
  story: [
    line('Lotte heeft een rode jas en een zachte sjaal.', 'Lotte has a red coat and a soft scarf.'),
    line('De sjaal is paars. De jas is nieuw.', 'The scarf is purple. The coat is new.'),
    line('Bram heeft een wit hemd en een blauwe broek.', 'Bram has a white button-up shirt and blue trousers.'),
    line('Het hemd is schoon, maar de broek is vuil.', 'The button-up shirt is clean, but the trousers are dirty.'),
    line('De portemonnee is leeg. De kast is vol.', 'The wallet is empty. The cupboard is full.'),
    line('De keuken is licht. De slaapkamer is donker.', 'The kitchen is bright. The bedroom is dark.'),
    line('Het kind heeft een oranje pet en een roze trui.', 'The child has an orange cap and a pink sweater.'),
    line('Mijn telefoon is kapot, maar mijn horloge is niet kapot.', 'My phone is broken, but my watch is not broken.'),
  ],
  questions: [
    question('Is de jas blauw?', 'Nee, de jas is rood.', 'Is the coat blue?', ['Nee, de jas is niet blauw.']),
    question('Is de sjaal zacht?', 'Ja, de sjaal is zacht.', 'Is the scarf soft?'),
    question('Is het hemd schoon?', 'Ja, het hemd is schoon.', 'Is the button-up shirt clean?'),
    question('Is de broek schoon?', 'Nee, de broek is vuil.', 'Are the trousers clean?', ['Nee, de broek is niet schoon.']),
    question('Is de portemonnee vol?', 'Nee, de portemonnee is leeg.', 'Is the wallet full?', ['Nee, de portemonnee is niet vol.']),
    question('Is de slaapkamer licht?', 'Nee, de slaapkamer is donker.', 'Is the bedroom bright?', ['Nee, de slaapkamer is niet licht.']),
    question('Heeft het kind een oranje pet?', 'Ja, het kind heeft een oranje pet.', 'Does the child have an orange cap?'),
    question('Is het horloge kapot?', 'Nee, het horloge is niet kapot.', 'Is the watch broken?'),
  ],
};
