import { entry as w, line, question } from './entry.js';

export default {
  id: 'a1-eten', after: 'ik-lees', volume: 0,
  title: 'Wat kopen en eten we?', subtitle: 'Twenty food and shopping words. Revisit the present tense, graag and geen.', image: 'bread',
  reviewGrammar: ['present-regular', 'spelling-stem', 'adverb-position', 'geen-niet', 'yes-no-question'],
  reminders: [
    'Kopen follows the present-tense pattern you know: ik koop, jij koopt, hij/zij koopt, wij/jullie/zij kopen. A question with jij loses -t: koop jij? Keep the long vowel in koop, as in wonen → woon.',
    'Use no een with an unspecified amount: ik drink melk, ik eet rijst. Use een for one countable item: een ei, een tomaat. Geen makes both negative: geen melk, geen ei. Put graag after the finite verb in these statements: ik eet graag vis.',
  ],
  entries: [
    w('kopen', null, 'to buy', ['Ik koop brood.', 'I buy bread.'], ['Bram koopt kaas.', 'Bram buys cheese.'], { forms: ['koop', 'koopt'] }),
    w('melk', 'de', 'milk', ['Het kind drinkt melk.', 'The child drinks milk.'], ['Ik koop geen melk.', 'I do not buy milk.']),
    w('sap', 'het', 'juice', ['Lotte drinkt sap.', 'Lotte drinks juice.'], ['Het sap is oranje.', 'The juice is orange.']),
    w('bier', 'het', 'beer', ['De man drinkt bier.', 'The man drinks beer.'], ['Bram koopt geen bier.', 'Bram does not buy beer.']),
    w('wijn', 'de', 'wine', ['Ik koop rode wijn.', 'I buy red wine.'], ['De wijn is wit.', 'The wine is white.']),
    w('suiker', 'de', 'sugar', ['Ik heb geen suiker.', 'I do not have any sugar.'], ['De suiker is wit.', 'The sugar is white.']),
    w('zout', 'het', 'salt', ['Bram koopt zout.', 'Bram buys salt.'], ['Het zout is wit.', 'The salt is white.']),
    w('boter', 'de', 'butter', ['Ik heb geen boter.', 'I do not have any butter.'], ['Lotte koopt boter.', 'Lotte buys butter.']),
    w('rijst', 'de', 'rice', ['Wij eten graag rijst.', 'We like eating rice.'], ['Bram kookt rijst.', 'Bram cooks rice.']),
    w('pasta', 'de', 'pasta', ['Lotte kookt pasta.', 'Lotte cooks pasta.'], ['Ik eet graag pasta.', 'I like eating pasta.']),
    w('kip', 'de', 'chicken', ['Bram eet kip.', 'Bram eats chicken.'], ['Wij kopen geen kip.', 'We do not buy chicken.']),
    w('vlees', 'het', 'meat', ['Lotte eet geen vlees.', 'Lotte does not eat meat.'], ['Bram koopt vlees.', 'Bram buys meat.']),
    w('vis', 'de', 'fish', ['Ik eet graag vis.', 'I like eating fish.'], ['Bram koopt een vis.', 'Bram buys a fish.']),
    w('ei', 'het', 'egg', ['Het kind eet een ei.', 'The child eats an egg.'], ['Dit is een bruin ei.', 'This is a brown egg.']),
    w('aardappel', 'de', 'potato', ['Ik kook een aardappel.', 'I cook a potato.'], ['De aardappel is groot.', 'The potato is big.']),
    w('tomaat', 'de', 'tomato', ['Lotte eet een tomaat.', 'Lotte eats a tomato.'], ['De tomaat is rood.', 'The tomato is red.']),
    w('wortel', 'de', 'carrot', ['Het kind eet een wortel.', 'The child eats a carrot.'], ['De wortel is oranje.', 'The carrot is orange.']),
    w('banaan', 'de', 'banana', ['Ik eet een banaan.', 'I eat a banana.'], ['De banaan is geel.', 'The banana is yellow.']),
    w('peer', 'de', 'pear', ['Lotte koopt een peer.', 'Lotte buys a pear.'], ['De peer is groen.', 'The pear is green.']),
    w('sinaasappel', 'de', 'orange (fruit)', ['Bram koopt een sinaasappel.', 'Bram buys an orange.'], ['Het kind eet een sinaasappel.', 'The child eats an orange.']),
  ],
  grammarItems: [
    { nl: 'Ik ___ brood.', cue: 'kopen', answer: 'koop', en: 'I buy bread.' },
    { nl: 'Jij ___ melk.', cue: 'kopen', answer: 'koopt', en: 'You buy milk.' },
    { nl: '___ jij kaas?', cue: 'kopen', answer: 'Koop', en: 'Do you buy cheese?' },
    { nl: 'Hij ___ rijst.', cue: 'kopen', answer: 'koopt', en: 'He buys rice.' },
    { nl: 'Zij ___ boter.', cue: 'kopen', answer: 'koopt', en: 'She buys butter.' },
    { nl: 'Wij ___ pasta.', cue: 'kopen', answer: 'kopen', en: 'We buy pasta.' },
    { nl: 'Jullie ___ zout.', cue: 'kopen', answer: 'kopen', en: 'You all buy salt.' },
    { nl: 'Bram en Lotte ___ suiker.', cue: 'kopen', answer: 'kopen', en: 'Bram and Lotte buy sugar.' },
    { nl: 'Het kind ___ een ei.', cue: 'eten', answer: 'eet', en: 'The child eats an egg.' },
    { nl: 'Wij ___ vis.', cue: 'eten', answer: 'eten', en: 'We eat fish.' },
    { nl: 'Ik eet rijst.', task: 'Add graag in the usual position.', answer: 'Ik eet graag rijst.' },
    { nl: 'Bram drinkt wijn.', task: 'Make the sentence negative.', answer: 'Bram drinkt geen wijn.' },
    { nl: 'Lotte koopt een peer.', task: 'Make a yes/no question.', answer: 'Koopt Lotte een peer?' },
    { nl: 'Jij eet een wortel.', task: 'Make a yes/no question.', answer: 'Eet jij een wortel?' },
    { nl: 'Ik heb een tomaat.', task: 'Make the sentence negative.', answer: 'Ik heb geen tomaat.' },
    { nl: 'Bram koopt ___ bier.', answer: 'geen', en: 'Bram does not buy beer.' },
    { nl: 'De banaan is ___ groen.', answer: 'niet', en: 'The banana is not green.' },
    { nl: 'Lotte ___ een aardappel.', cue: 'koken', answer: 'kookt', en: 'Lotte cooks a potato.' },
    { nl: '___ jij melk?', cue: 'drinken', answer: 'Drink', en: 'Do you drink milk?' },
    { nl: 'Wij drinken ___.', answer: 'sap', en: 'We drink juice.' },
  ],
  story: [
    line('Bram en Lotte kopen brood, kaas en melk.', 'Bram and Lotte buy bread, cheese and milk.'),
    line('Lotte koopt ook een rode tomaat en een groene peer.', 'Lotte also buys a red tomato and a green pear.'),
    line('Bram koopt rijst en kip. Hij koopt geen bier.', 'Bram buys rice and chicken. He does not buy beer.'),
    line('Thuis kookt Bram de rijst. Lotte kookt pasta.', 'At home Bram cooks the rice. Lotte cooks pasta.'),
    line('Het kind eet een ei en een wortel.', 'The child eats an egg and a carrot.'),
    line('De wortel is oranje. Het ei is bruin.', 'The carrot is orange. The egg is brown.'),
    line('Bram drinkt koffie. Lotte drinkt sap.', 'Bram drinks coffee. Lotte drinks juice.'),
    line('Het kind heeft ook een gele banaan. De banaan is niet groen.', 'The child also has a yellow banana. The banana is not green.'),
  ],
  questions: [
    question('Wat koken Bram en Lotte?', 'Bram en Lotte koken rijst en pasta.', 'What do Bram and Lotte cook?', ['Bram en Lotte koken pasta en rijst.']),
    question('Is de tomaat rood?', 'Ja, de tomaat is rood.', 'Is the tomato red?'),
    question('Koopt Bram bier?', 'Nee, Bram koopt geen bier.', 'Does Bram buy beer?'),
    question('Wat kookt Bram?', 'Bram kookt rijst.', 'What does Bram cook?', ['Bram kookt de rijst.']),
    question('Wat kookt Lotte?', 'Lotte kookt pasta.', 'What does Lotte cook?'),
    question('Is het ei wit?', 'Nee, het ei is bruin.', 'Is the egg white?', ['Nee, het ei is niet wit.']),
    question('Wat drinkt Lotte?', 'Lotte drinkt sap.', 'What does Lotte drink?'),
    question('Is de banaan groen?', 'Nee, de banaan is geel.', 'Is the banana green?', ['Nee, de banaan is niet groen.']),
  ],
};
