import { entry as w, line, question } from './entry.js';

export default {
  id: 'a1-thuis', after: 'ik-ben', volume: 0,
  title: 'Een kamer in huis', subtitle: 'Twenty things at home. Practise de/het, zijn, questions and negation.',
  image: 'living-room',
  reviewGrammar: ['dit-is', 'de-het', 'zijn', 'geen', 'niet', 'yes-no-question'],
  reminders: [
    'Learn the article with the noun: de tafel, but het bed. Een works with both. Dutch names a staircase as de trap, even though English often says “the stairs”.',
    'Use geen instead of een to say “not a”: Dit is geen slaapkamer. Use niet before an adjective: De slaapkamer is niet klein. In a yes/no question, is comes first.',
  ],
  entries: [
    w('tafel', 'de', 'table', ['Dit is een tafel.', 'This is a table.'], ['De tafel is groot.', 'The table is big.']),
    w('stoel', 'de', 'chair', ['Dit is een stoel.', 'This is a chair.'], ['De stoel is niet nieuw.', 'The chair is not new.']),
    w('kamer', 'de', 'room', ['Dit is een kamer.', 'This is a room.'], ['De kamer is klein.', 'The room is small.']),
    w('keuken', 'de', 'kitchen', ['Dit is een keuken.', 'This is a kitchen.'], ['De keuken is mooi.', 'The kitchen is beautiful.']),
    w('tuin', 'de', 'garden', ['Dit is een tuin.', 'This is a garden.'], ['De tuin is groot.', 'The garden is big.']),
    w('bed', 'het', 'bed', ['Dit is een bed.', 'This is a bed.'], ['Het bed is niet klein.', 'The bed is not small.']),
    w('kast', 'de', 'cupboard', ['Dit is een kast.', 'This is a cupboard.'], ['De kast is oud.', 'The cupboard is old.']),
    w('lamp', 'de', 'lamp', ['Dit is een lamp.', 'This is a lamp.'], ['De lamp is nieuw.', 'The lamp is new.']),
    w('muur', 'de', 'wall', ['Dit is een muur.', 'This is a wall.'], ['De muur is niet nieuw.', 'The wall is not new.']),
    w('vloer', 'de', 'floor', ['Dit is een vloer.', 'This is a floor.'], ['De vloer is mooi.', 'The floor is beautiful.']),
    w('dak', 'het', 'roof', ['Dit is een dak.', 'This is a roof.'], ['Het dak is oud.', 'The roof is old.'], { laterForms: { 'twee-katten': ['daken'] } }),
    w('trap', 'de', 'staircase', ['Dit is een trap.', 'This is a staircase.'], ['De trap is niet groot.', 'The staircase is not big.']),
    w('badkamer', 'de', 'bathroom', ['Dit is een badkamer.', 'This is a bathroom.'], ['De badkamer is klein.', 'The bathroom is small.']),
    w('slaapkamer', 'de', 'bedroom', ['Dit is een slaapkamer.', 'This is a bedroom.'], ['De slaapkamer is mooi.', 'The bedroom is beautiful.']),
    w('woonkamer', 'de', 'living room', ['Dit is een woonkamer.', 'This is a living room.'], ['De woonkamer is groot.', 'The living room is big.']),
    w('spiegel', 'de', 'mirror', ['Dit is een spiegel.', 'This is a mirror.'], ['De spiegel is oud.', 'The mirror is old.']),
    w('douche', 'de', 'shower', ['Dit is een douche.', 'This is a shower.'], ['De douche is nieuw.', 'The shower is new.'], { laterForms: { 'twee-katten': ['douches'] } }),
    w('toilet', 'het', 'toilet', ['Dit is een toilet.', 'This is a toilet.'], ['Het toilet is niet nieuw.', 'The toilet is not new.'], { laterForms: { 'twee-katten': ['toiletten'] } }),
    w('balkon', 'het', 'balcony', ['Dit is een balkon.', 'This is a balcony.'], ['Het balkon is klein.', 'The balcony is small.'], { laterForms: { 'twee-katten': ['balkons'] } }),
    w('gordijn', 'het', 'curtain', ['Dit is een gordijn.', 'This is a curtain.'], ['Het gordijn is mooi.', 'The curtain is beautiful.'], { laterForms: { 'twee-katten': ['gordijnen'] } }),
  ],
  grammarItems: [
    { nl: 'Dit is een tafel.', task: 'Make a yes/no question.', answer: 'Is dit een tafel?' },
    { nl: 'De stoel is nieuw.', task: 'Make a yes/no question.', answer: 'Is de stoel nieuw?' },
    { nl: 'Dit is een slaapkamer.', task: 'Say that this is not a bedroom.', answer: 'Dit is geen slaapkamer.' },
    { nl: 'De keuken is klein.', task: 'Make the sentence negative.', answer: 'De keuken is niet klein.' },
    { nl: 'Het bed is groot.', task: 'Make a yes/no question.', answer: 'Is het bed groot?' },
    { nl: 'Dit is een badkamer.', task: 'Say that this is not a bathroom.', answer: 'Dit is geen badkamer.' },
    { nl: 'De lamp is mooi.', task: 'Make the sentence negative.', answer: 'De lamp is niet mooi.' },
    { nl: 'Dit is een gordijn.', task: 'Make a yes/no question.', answer: 'Is dit een gordijn?' },
    { nl: 'Het balkon is klein.', task: 'Make the sentence negative.', answer: 'Het balkon is niet klein.' },
    { nl: 'Dit is een spiegel.', task: 'Say that this is not a mirror.', answer: 'Dit is geen spiegel.' },
    { nl: 'Ik ___ blij.', answer: 'ben', en: 'I am happy.' },
    { nl: '___ jij moe?', answer: 'Ben', en: 'Are you tired?' },
    { nl: 'Wij ___ niet ziek.', answer: 'zijn', en: 'We are not ill.' },
    { nl: 'Jij ___ lief.', answer: 'bent', en: 'You are kind.' },
    { nl: 'Zij ___ jong.', answer: 'is', en: 'She is young.' },
    { nl: 'Dit is ___ bed.', answer: 'een', en: 'This is a bed.' },
    { nl: '___ vloer is mooi.', answer: 'De', en: 'The floor is beautiful.' },
    { nl: '___ dak is oud.', answer: 'Het', en: 'The roof is old.' },
    { nl: 'Dit is ___ auto.', answer: 'geen', en: 'This is not a car.' },
    { nl: 'De boom is ___ klein.', answer: 'niet', en: 'The tree is not small.' },
  ],
  story: [
    line('Dit is een huis. Het huis is oud.', 'This is a house. The house is old.'),
    line('De woonkamer is groot. De keuken is klein.', 'The living room is big. The kitchen is small.'),
    line('De tafel is nieuw. De stoel is niet nieuw.', 'The table is new. The chair is not new.'),
    line('Dit is geen badkamer. Dit is een slaapkamer.', 'This is not a bathroom. This is a bedroom.'),
    line('Het bed is groot en de lamp is mooi.', 'The bed is big and the lamp is beautiful.'),
    line('De spiegel is oud. Het gordijn is nieuw.', 'The mirror is old. The curtain is new.'),
    line('Het balkon is klein. De tuin is groot.', 'The balcony is small. The garden is big.'),
    line('Bram en Lotte zijn blij. Het huis is mooi.', 'Bram and Lotte are happy. The house is beautiful.'),
  ],
  questions: [
    question('Is het huis nieuw?', 'Nee, het huis is oud.', 'Is the house new?', ['Nee, het huis is niet nieuw.']),
    question('Is de woonkamer groot?', 'Ja, de woonkamer is groot.', 'Is the living room big?'),
    question('Is de keuken groot?', 'Nee, de keuken is klein.', 'Is the kitchen big?', ['Nee, de keuken is niet groot.']),
    question('Is de tafel nieuw?', 'Ja, de tafel is nieuw.', 'Is the table new?'),
    question('Is de stoel nieuw?', 'Nee, de stoel is niet nieuw.', 'Is the chair new?'),
    question('Is de spiegel oud?', 'Ja, de spiegel is oud.', 'Is the mirror old?'),
    question('Is het balkon groot?', 'Nee, het balkon is klein.', 'Is the balcony big?', ['Nee, het balkon is niet groot.']),
    question('Zijn Bram en Lotte blij?', 'Ja, Bram en Lotte zijn blij.', 'Are Bram and Lotte happy?', ['Ja, zij zijn blij.']),
  ],
};
