import { entry as w, line, question } from './entry.js';

export default {
  id: 'a1-tellen', after: 'op-maandag', volume: 0,
  title: 'Dertien stoelen en twintig euro', subtitle: 'Twenty number and counting words. Revisit plurals, prices, questions and present tense.', image: 'money',
  reviewGrammar: ['numbers', 'plural', 'er-is-zijn', 'question-word', 'present-regular'],
  reminders: [
    'Learn the number words as vocabulary. Notice the spellings zestien, zeventien, achttien, twintig, veertig, tachtig and honderd. This lesson practises thirteen to twenty, the tens, one hundred and one thousand; numbers such as twenty-one return later.',
    'Use the plural with things you count: dertien stoelen, twintig boeken. Keep euro singular in a price: twintig euro. Use hoeveel to ask a quantity or a price. De helft means half: de prijs is twintig euro; de helft is tien euro. Tellen is a regular verb: ik tel, jij telt, wij tellen.',
  ],
  entries: [
    w('dertien', null, 'thirteen', ['Er zijn dertien stoelen.', 'There are thirteen chairs.'], ['Ik heb dertien boeken.', 'I have thirteen books.']),
    w('veertien', null, 'fourteen', ['Lotte heeft veertien boeken.', 'Lotte has fourteen books.'], ['De jas kost veertien euro.', 'The coat costs fourteen euros.']),
    w('vijftien', null, 'fifteen', ['Bram koopt vijftien appels.', 'Bram buys fifteen apples.'], ['Er zijn vijftien stoelen.', 'There are fifteen chairs.']),
    w('zestien', null, 'sixteen', ['Er zijn zestien huizen in de straat.', 'There are sixteen houses in the street.'], ['De schoenen kosten zestien euro.', 'The shoes cost sixteen euros.']),
    w('zeventien', null, 'seventeen', ['Ik heb zeventien euro.', 'I have seventeen euros.'], ['Er zijn zeventien boeken op tafel.', 'There are seventeen books on the table.']),
    w('achttien', null, 'eighteen', ['Mijn zus is achttien jaar.', 'My sister is eighteen years old.'], ['De trui kost achttien euro.', 'The sweater costs eighteen euros.']),
    w('negentien', null, 'nineteen', ['Er zijn negentien stoelen in de kamer.', 'There are nineteen chairs in the room.'], ['Bram heeft negentien euro.', 'Bram has nineteen euros.']),
    w('twintig', null, 'twenty', ['De jas kost twintig euro.', 'The coat costs twenty euros.'], ['Ik heb twintig boeken.', 'I have twenty books.']),
    w('dertig', null, 'thirty', ['Mijn broer is dertig jaar.', 'My brother is thirty years old.'], ['De tafel kost dertig euro.', 'The table costs thirty euros.']),
    w('veertig', null, 'forty', ['De stoel kost veertig euro.', 'The chair costs forty euros.'], ['Er zijn veertig huizen in de straat.', 'There are forty houses in the street.']),
    w('vijftig', null, 'fifty', ['Ik betaal vijftig euro.', 'I pay fifty euros.'], ['Mijn moeder is vijftig jaar.', 'My mother is fifty years old.']),
    w('zestig', null, 'sixty', ['De kast kost zestig euro.', 'The cupboard costs sixty euros.'], ['Mijn vader is zestig jaar.', 'My father is sixty years old.']),
    w('zeventig', null, 'seventy', ['De fiets kost zeventig euro.', 'The bicycle costs seventy euros.'], ['Lotte heeft zeventig euro.', 'Lotte has seventy euros.']),
    w('tachtig', null, 'eighty', ['Het bed kost tachtig euro.', 'The bed costs eighty euros.'], ['Er zijn tachtig boeken in de kast.', 'There are eighty books in the cupboard.']),
    w('negentig', null, 'ninety', ['Bram betaalt negentig euro.', 'Bram pays ninety euros.'], ['Er zijn negentig stoelen in de school.', 'There are ninety chairs in the school.']),
    w('honderd', null, 'one hundred', ['Ik heb honderd euro.', 'I have one hundred euros.'], ['Er zijn honderd boeken in de school.', 'There are one hundred books in the school.']),
    w('duizend', null, 'one thousand', ['De auto kost duizend euro.', 'The car costs one thousand euros.'], ['Ik heb duizend euro nodig.', 'I need one thousand euros.']),
    w('nul', null, 'zero', ['De prijs is nul euro.', 'The price is zero euros.'], ['Ik betaal nul euro.', 'I pay zero euros.']),
    w('helft', 'de', 'half (one of two equal parts)', ['De helft is tien euro.', 'Half is ten euros.'], ['Ik betaal de helft.', 'I pay half.']),
    w('tellen', null, 'to count', ['Ik tel mijn geld.', 'I count my money.'], ['Bram telt de stoelen.', 'Bram counts the chairs.'], { forms: ['tel', 'telt'] }),
  ],
  grammarItems: [
    { nl: 'Er ___ dertien stoelen.', answer: 'zijn', en: 'There are thirteen chairs.' },
    { nl: 'Er ___ één stoel.', answer: 'is', en: 'There is one chair.' },
    { nl: 'Ik heb veertien ___.', cue: 'boek', answer: 'boeken', en: 'I have fourteen books.' },
    { nl: 'Bram koopt vijftien ___.', cue: 'appel', answer: 'appels', en: 'Bram buys fifteen apples.' },
    { nl: 'Er zijn zestien ___.', cue: 'huis', answer: 'huizen', en: 'There are sixteen houses.' },
    { nl: 'Er zijn zeventien ___.', cue: 'stoel', answer: 'stoelen', en: 'There are seventeen chairs.' },
    { nl: 'Ik ___ mijn geld.', cue: 'tellen', answer: 'tel', en: 'I count my money.' },
    { nl: 'Bram ___ de stoelen.', cue: 'tellen', answer: 'telt', en: 'Bram counts the chairs.' },
    { nl: 'Wij ___ de boeken.', cue: 'tellen', answer: 'tellen', en: 'We count the books.' },
    { nl: '___ jij de stoelen?', cue: 'tellen', answer: 'Tel', en: 'Do you count the chairs?' },
    { nl: 'De jas kost twintig euro.', task: 'Ask the price, beginning with Hoeveel.', answer: 'Hoeveel kost de jas?' },
    { nl: 'Er zijn dertig stoelen.', task: 'Ask the number, beginning with Hoeveel.', answer: 'Hoeveel stoelen zijn er?' },
    { nl: 'Mijn broer is dertig jaar.', task: 'Ask his age, beginning with Hoe.', answer: 'Hoe oud is mijn broer?' },
    { nl: 'Ik betaal vijftig euro.', task: 'Begin the sentence with Vandaag.', answer: 'Vandaag betaal ik vijftig euro.' },
    { nl: 'Jij hebt honderd euro.', task: 'Make a yes/no question.', answer: 'Heb jij honderd euro?' },
    { nl: 'De schoenen ___ zestien euro.', cue: 'kosten', answer: 'kosten', en: 'The shoes cost sixteen euros.' },
    { nl: 'De auto ___ duizend euro.', cue: 'kosten', answer: 'kost', en: 'The car costs one thousand euros.' },
    { nl: 'Mijn zus ___ achttien jaar.', cue: 'zijn', answer: 'is', en: 'My sister is eighteen years old.' },
    { nl: 'Bram ___ negentig euro.', cue: 'betalen', answer: 'betaalt', en: 'Bram pays ninety euros.' },
    { nl: 'De helft ___ tien euro.', cue: 'zijn', answer: 'is', en: 'Half is ten euros.' },
  ],
  story: [
    line('Er zijn dertien stoelen in de kamer.', 'There are thirteen chairs in the room.'),
    line('Lotte heeft veertien boeken.', 'Lotte has fourteen books.'),
    line('Bram koopt vijftien appels.', 'Bram buys fifteen apples.'),
    line('De appels kosten zes euro.', 'The apples cost six euros.'),
    line('De jas kost twintig euro. Lotte betaalt de helft.', 'The coat costs twenty euros. Lotte pays half.'),
    line('De helft is tien euro.', 'Half is ten euros.'),
    line('De auto kost duizend euro.', 'The car costs one thousand euros.'),
    line('Bram telt zijn geld. Hij heeft genoeg geld.', 'Bram counts his money. He has enough money.'),
  ],
  questions: [
    question('Hoeveel stoelen zijn er?', 'Er zijn dertien stoelen.', 'How many chairs are there?'),
    question('Hoeveel boeken heeft Lotte?', 'Lotte heeft veertien boeken.', 'How many books does Lotte have?'),
    question('Hoeveel appels koopt Bram?', 'Bram koopt vijftien appels.', 'How many apples does Bram buy?'),
    question('Hoeveel kosten de appels?', 'De appels kosten zes euro.', 'How much do the apples cost?'),
    question('Hoeveel kost de jas?', 'De jas kost twintig euro.', 'How much does the coat cost?'),
    question('Hoeveel betaalt Lotte?', 'Lotte betaalt tien euro.', 'How much does Lotte pay?', ['Lotte betaalt de helft.']),
    question('Hoeveel kost de auto?', 'De auto kost duizend euro.', 'How much does the car cost?'),
    question('Wie telt zijn geld?', 'Bram telt zijn geld.', 'Who counts his money?'),
  ],
};
