import { entry as w, line, question } from './entry.js';

export default {
  id: 'a1-stad', after: 'vandaag', volume: 0,
  title: 'Vandaag ga ik naar de stad', subtitle: 'Twenty places and ways to travel. Revisit naar, met, questions and time-first sentences.', image: 'city',
  reviewGrammar: ['gaan', 'v2-inversion', 'time-place', 'question-word', 'geen-niet'],
  reminders: [
    'Use naar for a destination and in for a location: ik ga naar het museum; ik ben in het museum. Say op het plein and op de markt. Learn each noun with its article: het ziekenhuis, het politiebureau, het stadhuis.',
    'Use met for transport: met de bus, met de tram, met de metro. Put the verb second after a time word: morgen gaan wij naar de markt. In a question it comes before the subject: ga jij vandaag naar de stad?',
  ],
  entries: [
    w('bakker', 'de', 'baker; baker’s shop', ['Ik ga naar de bakker.', 'I am going to the baker’s.'], ['De bakker heeft brood.', 'The baker has bread.']),
    w('supermarkt', 'de', 'supermarket', ['Lotte koopt melk in de supermarkt.', 'Lotte buys milk in the supermarket.'], ['De supermarkt is groot.', 'The supermarket is big.']),
    w('slager', 'de', 'butcher; butcher’s shop', ['Bram gaat naar de slager.', 'Bram goes to the butcher’s.'], ['De slager heeft een winkel.', 'The butcher has a shop.']),
    w('markt', 'de', 'market', ['Wij kopen kaas op de markt.', 'We buy cheese at the market.'], ['Morgen gaat Lotte naar de markt.', 'Tomorrow Lotte goes to the market.']),
    w('restaurant', 'het', 'restaurant', ['Wij eten in het restaurant.', 'We eat in the restaurant.'], ['Het restaurant is niet groot.', 'The restaurant is not big.']),
    w('café', 'het', 'café; pub', ['Bram drinkt koffie in het café.', 'Bram drinks coffee in the café.'], ['Het café is klein.', 'The café is small.']),
    w('winkelcentrum', 'het', 'shopping centre', ['Lotte koopt een jas in het winkelcentrum.', 'Lotte buys a coat in the shopping centre.'], ['Het winkelcentrum is nieuw.', 'The shopping centre is new.']),
    w('bushalte', 'de', 'bus stop', ['Ik loop naar de bushalte.', 'I walk to the bus stop.'], ['De bushalte is in mijn straat.', 'The bus stop is in my street.']),
    w('bus', 'de', 'bus', ['Ik ga met de bus naar school.', 'I go to school by bus.'], ['De bus is vol.', 'The bus is full.']),
    w('tram', 'de', 'tram', ['In Brussel gaan wij met de tram.', 'In Brussels we travel by tram.'], ['De tram is rood.', 'The tram is red.']),
    w('metro', 'de', 'metro; underground railway', ['Bram gaat in Brussel met de metro.', 'Bram travels by metro in Brussels.'], ['De metro is niet leeg.', 'The metro is not empty.']),
    w('plein', 'het', 'square (in a town)', ['Het kind speelt op het plein.', 'The child plays in the square.'], ['Het plein is groot.', 'The square is big.']),
    w('museum', 'het', 'museum', ['Wij gaan morgen naar het museum.', 'We are going to the museum tomorrow.'], ['Het museum is in de stad.', 'The museum is in the city.']),
    w('zwembad', 'het', 'swimming pool', ['Het kind gaat naar het zwembad.', 'The child goes to the swimming pool.'], ['Het zwembad is nieuw.', 'The swimming pool is new.']),
    w('sporthal', 'de', 'sports hall', ['De school heeft een sporthal.', 'The school has a sports hall.'], ['Morgen gaan wij naar de sporthal.', 'Tomorrow we go to the sports hall.']),
    w('ziekenhuis', 'het', 'hospital', ['De vrouw werkt in het ziekenhuis.', 'The woman works in the hospital.'], ['Het ziekenhuis is groot.', 'The hospital is big.']),
    w('postkantoor', 'het', 'post office', ['Ik ga naar het postkantoor.', 'I go to the post office.'], ['Het postkantoor is in de stad.', 'The post office is in the city.']),
    w('politiebureau', 'het', 'police station', ['De man werkt in het politiebureau.', 'The man works in the police station.'], ['Het politiebureau is niet oud.', 'The police station is not old.']),
    w('stadhuis', 'het', 'town hall', ['Het stadhuis is mooi.', 'The town hall is beautiful.'], ['Lotte gaat naar het stadhuis.', 'Lotte goes to the town hall.']),
    w('bioscoop', 'de', 'cinema', ['Bram en Lotte gaan naar de bioscoop.', 'Bram and Lotte go to the cinema.'], ['De bioscoop is in de stad.', 'The cinema is in the city.']),
  ],
  grammarItems: [
    { nl: 'Ik ___ naar de bakker.', cue: 'gaan', answer: 'ga', en: 'I go to the baker’s.' },
    { nl: 'Jij ___ naar de supermarkt.', cue: 'gaan', answer: 'gaat', en: 'You go to the supermarket.' },
    { nl: '___ jij naar de markt?', cue: 'gaan', answer: 'Ga', en: 'Are you going to the market?' },
    { nl: 'Bram ___ naar het café.', cue: 'gaan', answer: 'gaat', en: 'Bram goes to the café.' },
    { nl: 'Wij ___ naar het museum.', cue: 'gaan', answer: 'gaan', en: 'We go to the museum.' },
    { nl: 'Ik ga ___ de bus.', answer: 'met', en: 'I travel by bus.' },
    { nl: 'Lotte koopt kaas ___ de markt.', answer: 'op', en: 'Lotte buys cheese at the market.' },
    { nl: 'De vrouw werkt ___ het ziekenhuis.', answer: 'in', en: 'The woman works in the hospital.' },
    { nl: 'Morgen gaan wij ___ de bioscoop.', answer: 'naar', en: 'Tomorrow we go to the cinema.' },
    { nl: 'Het kind speelt ___ het plein.', answer: 'op', en: 'The child plays in the square.' },
    { nl: 'Lotte gaat morgen naar de markt.', task: 'Begin with Morgen.', answer: 'Morgen gaat Lotte naar de markt.' },
    { nl: 'Wij eten vandaag in het restaurant.', task: 'Begin with Vandaag.', answer: 'Vandaag eten wij in het restaurant.' },
    { nl: 'Ik ga nu naar het postkantoor.', task: 'Begin with Nu.', answer: 'Nu ga ik naar het postkantoor.' },
    { nl: 'Bram gaat morgen naar het stadhuis.', task: 'Begin with Morgen.', answer: 'Morgen gaat Bram naar het stadhuis.' },
    { nl: 'De bus is vol.', task: 'Make a yes/no question.', answer: 'Is de bus vol?' },
    { nl: 'De school heeft een zwembad.', task: 'Make the sentence negative.', answer: 'De school heeft geen zwembad.' },
    { nl: 'Het museum is groot.', task: 'Make the sentence negative.', answer: 'Het museum is niet groot.' },
    { nl: 'Wij gaan met de tram.', task: 'Make a yes/no question.', answer: 'Gaan wij met de tram?' },
    { nl: 'Het winkelcentrum is nieuw.', task: 'Make a yes/no question.', answer: 'Is het winkelcentrum nieuw?' },
    { nl: 'Jij werkt in de sporthal.', task: 'Ask where jij works, beginning with Waar.', answer: 'Waar werk jij?' },
  ],
  story: [
    line('Vandaag gaat Lotte naar de markt. Zij koopt kaas en een appel.', 'Today Lotte goes to the market. She buys cheese and an apple.'),
    line('Dan gaat zij naar de bakker. Zij koopt brood.', 'Then she goes to the baker’s. She buys bread.'),
    line('Bram gaat met de trein naar Brussel. In Brussel gaat hij met de metro.', 'Bram goes to Brussels by train. In Brussels he travels by metro.'),
    line('Hij drinkt koffie in een klein café.', 'He drinks coffee in a small café.'),
    line('Het kind speelt op het plein. Morgen gaat het kind naar het zwembad.', 'The child plays in the square. Tomorrow the child goes to the swimming pool.'),
    line('De vrouw werkt in het ziekenhuis. Zij gaat met de bus.', 'The woman works in the hospital. She travels by bus.'),
    line('Morgen gaan Bram en Lotte naar het museum.', 'Tomorrow Bram and Lotte go to the museum.'),
    line('Dan eten zij in een restaurant in de stad.', 'Then they eat in a restaurant in the city.'),
  ],
  questions: [
    question('Waar koopt Lotte kaas?', 'Lotte koopt kaas op de markt.', 'Where does Lotte buy cheese?'),
    question('Koopt Lotte brood?', 'Ja, Lotte koopt brood.', 'Does Lotte buy bread?'),
    question('Gaat Bram met de trein naar Brussel?', 'Ja, Bram gaat met de trein naar Brussel.', 'Does Bram go to Brussels by train?'),
    question('Is het café groot?', 'Nee, het café is klein.', 'Is the café big?', ['Nee, het café is niet groot.']),
    question('Waar speelt het kind?', 'Het kind speelt op het plein.', 'Where does the child play?'),
    question('Waar werkt de vrouw?', 'De vrouw werkt in het ziekenhuis.', 'Where does the woman work?'),
    question('Gaan Bram en Lotte morgen naar het museum?', 'Ja, Bram en Lotte gaan morgen naar het museum.', 'Do Bram and Lotte go to the museum tomorrow?'),
    question('Waar eten Bram en Lotte morgen?', 'Bram en Lotte eten morgen in een restaurant.', 'Where do Bram and Lotte eat tomorrow?', ['Bram en Lotte eten in een restaurant.']),
  ],
};
