import { entry as w, line, question } from './entry.js';
export default {
  id: 'a1-school-werk', after: 'op-maandag', volume: 0,
  title: 'Op school en op kantoor', subtitle: 'Twenty study and work words. Revisit questions, possessives, plurals and modal verbs.', image: 'school',
  reviewGrammar: ['question-word', 'possessives', 'plural', 'modals', 'v2-inversion'],
  reminders: ['Use familiar location phrases: op school, op kantoor, in de les. Ask Wat is jouw beroep? about an occupation and Waar werk jij? about a workplace. Een baan is a job; een beroep is an occupation.', 'Use the grammar you know with new nouns: mijn schrift, onze les, twee leerlingen. Keep a second verb at the end: ik wil Nederlands leren; ik moet naar school gaan; de leraar kan helpen.'],
  entries: [
    w('beroep', 'het', 'occupation; profession', ['Wat is jouw beroep?', 'What is your occupation?'], ['Leraar is een beroep.', 'Teacher is an occupation.'], { forms: ['beroepen'] }),
    w('baan', 'de', 'job', ['Ik zoek een baan.', 'I am looking for a job.'], ['Lotte heeft een nieuwe baan.', 'Lotte has a new job.'], { forms: ['banen'] }),
    w('kantoor', 'het', 'office', ['Bram werkt op kantoor.', 'Bram works at the office.'], ['Het kantoor is naast het station.', 'The office is next to the station.'], { forms: ['kantoren'] }),
    w('bedrijf', 'het', 'company; business', ['Ik werk bij een klein bedrijf.', 'I work at a small company.'], ['Het bedrijf is in Leuven.', 'The company is in Leuven.'], { forms: ['bedrijven'] }),
    w('collega', 'de', 'colleague', ['Mijn collega heet Lotte.', 'My colleague is called Lotte.'], ['Bram praat met zijn collega.', 'Bram talks to his colleague.']),
    w('leraar', 'de', 'teacher', ['De leraar spreekt Nederlands.', 'The teacher speaks Dutch.'], ['Mijn leraar helpt graag.', 'My teacher likes to help.'], { forms: ['leraren'] }),
    w('leerling', 'de', 'pupil; learner', ['De leerling leest een boek.', 'The pupil reads a book.'], ['Er zijn twintig leerlingen in de school.', 'There are twenty pupils in the school.'], { forms: ['leerlingen'] }),
    w('student', 'de', 'student', ['De student leert Nederlands.', 'The student is learning Dutch.'], ['Er zijn twee studenten in de school.', 'There are two students in the school.'], { forms: ['studenten'] }),
    w('les', 'de', 'lesson; class', ['De les is op maandag.', 'The lesson is on Monday.'], ['Ik lees in de les.', 'I read in class.'], { forms: ['lessen'] }),
    w('cursus', 'de', 'course', ['De cursus is in september.', 'The course is in September.'], ['De cursus kost honderd euro.', 'The course costs one hundred euros.'], { forms: ['cursussen'] }),
    w('huiswerk', 'het', 'homework', ['Ik heb veel huiswerk.', 'I have a lot of homework.'], ['Mijn huiswerk is in mijn tas.', 'My homework is in my bag.']),
    w('oefening', 'de', 'exercise; practice task', ['Dit is een oefening.', 'This is an exercise.'], ['De oefening is in het boek.', 'The exercise is in the book.'], { forms: ['oefeningen'] }),
    w('toets', 'de', 'test (school)', ['De toets is op vrijdag.', 'The test is on Friday.'], ['Ik heb morgen een toets.', 'I have a test tomorrow.'], { forms: ['toetsen'] }),
    w('examen', 'het', 'exam', ['Het examen is in juni.', 'The exam is in June.'], ['Ik leer voor mijn examen.', 'I study for my exam.'], { forms: ['examens'] }),
    w('computer', 'de', 'computer', ['Mijn computer is nieuw.', 'My computer is new.'], ['Ik werk met een computer.', 'I work with a computer.'], { forms: ['computers'] }),
    w('laptop', 'de', 'laptop', ['Mijn laptop is in mijn tas.', 'My laptop is in my bag.'], ['Ik heb een nieuwe laptop.', 'I have a new laptop.'], { forms: ['laptops'] }),
    w('scherm', 'het', 'screen', ['Het scherm is groot.', 'The screen is big.'], ['Ik kijk naar het scherm.', 'I look at the screen.'], { forms: ['schermen'] }),
    w('toetsenbord', 'het', 'keyboard', ['Het toetsenbord is zwart.', 'The keyboard is black.'], ['Ik heb een nieuw toetsenbord.', 'I have a new keyboard.'], { forms: ['toetsenborden'] }),
    w('schrift', 'het', 'exercise book; notebook', ['Ik schrijf in mijn schrift.', 'I write in my notebook.'], ['Mijn schrift is blauw.', 'My notebook is blue.'], { forms: ['schriften'] }),
    w('agenda', 'de', 'diary; planner', ['Ik schrijf de datum in mijn agenda.', 'I write the date in my diary.'], ['Mijn agenda is in mijn tas.', 'My diary is in my bag.']),
  ],
  grammarItems: [
    { nl: 'Wat ___ jouw beroep?', answer: 'is', en: 'What is your occupation?' },
    { nl: 'Waar ___ jij?', cue: 'werken', answer: 'werk', en: 'Where do you work?' },
    { nl: 'Lotte heeft ___ laptop.', answer: 'haar', en: 'Lotte has her laptop.' },
    { nl: 'Bram schrijft in ___ schrift.', answer: 'zijn', en: 'Bram writes in his notebook.' },
    { nl: '___ kantoor is klein.', answer: 'Ons', en: 'Our office is small.' },
    { nl: '___ les is op maandag.', answer: 'Onze', en: 'Our lesson is on Monday.' },
    { nl: 'Er zijn twee ___.', cue: 'student', answer: 'studenten', en: 'There are two students.' },
    { nl: 'Ik heb drie ___.', cue: 'schrift', answer: 'schriften', en: 'I have three notebooks.' },
    { nl: 'Er zijn twintig ___.', cue: 'leerling', answer: 'leerlingen', en: 'There are twenty pupils.' },
    { nl: 'De leraar ___ Nederlands.', cue: 'spreken', answer: 'spreekt', en: 'The teacher speaks Dutch.' },
    { nl: 'Ik werk op kantoor.', task: 'Begin with Vandaag.', answer: 'Vandaag werk ik op kantoor.' },
    { nl: 'Jij hebt huiswerk.', task: 'Make a yes/no question.', answer: 'Heb jij huiswerk?' },
    { nl: 'De computer is kapot.', task: 'Make the sentence negative.', answer: 'De computer is niet kapot.' },
    { nl: 'Ik heb een laptop.', task: 'Make the sentence negative.', answer: 'Ik heb geen laptop.' },
    { nl: 'Ik moet naar school ___.', cue: 'gaan', answer: 'gaan', en: 'I have to go to school.' },
    { nl: 'De leraar kan ___.', cue: 'helpen', answer: 'helpen', en: 'The teacher can help.' },
    { nl: 'Ik wil Nederlands ___.', cue: 'leren', answer: 'leren', en: 'I want to learn Dutch.' },
    { nl: 'Dit is een ___ bedrijf.', cue: 'klein', answer: 'klein', en: 'This is a small company.' },
    { nl: 'Het ___ scherm is mooi.', cue: 'groot', answer: 'grote', en: 'The big screen is beautiful.' },
    { nl: '___ is de les?', answer: 'Waar', en: 'Where is the lesson?' },
  ],
  story: [
    line('Bram werkt bij een klein bedrijf. Zijn kantoor is in Leuven.', 'Bram works at a small company. His office is in Leuven.'),
    line('Zijn collega heet Lotte. Zij heeft een nieuwe laptop.', 'His colleague is called Lotte. She has a new laptop.'),
    line('Het scherm is groot en het toetsenbord is zwart.', 'The screen is big and the keyboard is black.'),
    line('Op maandag leert Bram Nederlands. Zijn leraar helpt graag.', 'On Monday Bram learns Dutch. His teacher likes to help.'),
    line('Er zijn twintig leerlingen in de les.', 'There are twenty pupils in the class.'),
    line('Bram schrijft in een blauw schrift. Hij heeft veel huiswerk.', 'Bram writes in a blue notebook. He has a lot of homework.'),
    line('De toets is op vrijdag. Het examen is in juni.', 'The test is on Friday. The exam is in June.'),
    line('Bram schrijft de datum in zijn agenda.', 'Bram writes the date in his diary.'),
  ],
  questions: [
    question('Waar is het kantoor?', 'Het kantoor is in Leuven.', 'Where is the office?'),
    question('Hoe heet zijn collega?', 'Zijn collega heet Lotte.', 'What is his colleague called?'),
    question('Is de laptop nieuw?', 'Ja, de laptop is nieuw.', 'Is the laptop new?'),
    question('Is het toetsenbord zwart?', 'Ja, het toetsenbord is zwart.', 'Is the keyboard black?'),
    question('Hoeveel leerlingen zijn er in de les?', 'Er zijn twintig leerlingen in de les.', 'How many pupils are in the class?', ['Er zijn twintig leerlingen.']),
    question('Is het schrift blauw?', 'Ja, het schrift is blauw.', 'Is the notebook blue?'),
    question('Is de toets op vrijdag?', 'Ja, de toets is op vrijdag.', 'Is the test on Friday?'),
    question('Waar schrijft Bram de datum?', 'Bram schrijft de datum in zijn agenda.', 'Where does Bram write the date?'),
  ],
};
