import { entry as w, line, question } from './entry.js';
export default {
  id: 'a1-op-reis', after: 'op-maandag', volume: 0,
  title: 'Met de trein naar zee', subtitle: 'Twenty travel words. Revisit questions, time, plurals and modal verbs.', image: 'train',
  reviewGrammar: ['question-word', 'modals', 'v2-inversion', 'plural', 'days-op-om'],
  reminders: ['Use the location phrases you know: naar het hotel, op het perron, in het vliegtuig. Reizen means to travel; de reis is a trip. Bagage is a mass noun here. Use singular is: mijn bagage is in de koffer.', 'Ask a question with the verb first: kan ik een kamer reserveren? Keep the infinitive at the end after a modal. Use om with a departure time: het vertrek is om acht uur. To reserve is reserveren; paying to use something temporarily is huren.'],
  entries: [
    w('reis', 'de', 'trip; journey', ['De reis is mooi.', 'The trip is beautiful.'], ['Ik wil een reis maken.', 'I want to make a trip.']),
    w('reizen', null, 'to travel', ['Ik reis met de trein.', 'I travel by train.'], ['Bram reist naar Gent.', 'Bram travels to Ghent.'], { forms: ['reis', 'reist'] }),
    w('vakantie', 'de', 'holiday; vacation', ['In juli heb ik vakantie.', 'In July I am on holiday.'], ['Mijn vakantie is in de zomer.', 'My holiday is in summer.'], { forms: ['vakanties'] }),
    w('zee', 'de', 'sea', ['Ik ga naar zee.', 'I go to the sea.'], ['De zee is blauw.', 'The sea is blue.']),
    w('strand', 'het', 'beach', ['Ik wandel op het strand.', 'I walk on the beach.'], ['Het strand is groot.', 'The beach is big.'], { forms: ['stranden'] }),
    w('vliegtuig', 'het', 'aeroplane', ['Het vliegtuig is groot.', 'The aeroplane is big.'], ['Ik zit in het vliegtuig.', 'I am sitting in the aeroplane.'], { forms: ['vliegtuigen'] }),
    w('vliegen', null, 'to fly', ['Het vliegtuig vliegt.', 'The aeroplane flies.'], ['Ik wil niet vliegen.', 'I do not want to fly.'], { forms: ['vlieg', 'vliegt'] }),
    w('vliegveld', 'het', 'airport', ['Waar is het vliegveld?', 'Where is the airport?'], ['Ik neem de bus naar het vliegveld.', 'I take the bus to the airport.'], { forms: ['vliegvelden'] }),
    w('hotel', 'het', 'hotel', ['Het hotel is bij het station.', 'The hotel is near the station.'], ['Ik slaap in het hotel.', 'I sleep in the hotel.'], { forms: ['hotels'] }),
    w('paspoort', 'het', 'passport', ['Mijn paspoort is in mijn tas.', 'My passport is in my bag.'], ['Ik heb mijn paspoort nodig.', 'I need my passport.'], { forms: ['paspoorten'] }),
    w('ticket', 'het', 'ticket', ['Ik koop een ticket.', 'I buy a ticket.'], ['Het ticket kost twintig euro.', 'The ticket costs twenty euros.'], { forms: ['tickets'] }),
    w('koffer', 'de', 'suitcase', ['Mijn koffer is vol.', 'My suitcase is full.'], ['Lotte draagt een blauwe koffer.', 'Lotte carries a blue suitcase.'], { forms: ['koffers'] }),
    w('bagage', 'de', 'luggage', ['Mijn bagage is in de koffer.', 'My luggage is in the suitcase.'], ['Waar is jouw bagage?', 'Where is your luggage?']),
    w('perron', 'het', 'platform (railway)', ['Ik wacht op het perron.', 'I wait on the platform.'], ['Het perron is naast de trein.', 'The platform is beside the train.'], { forms: ['perrons'] }),
    w('vertrek', 'het', 'departure', ['Het vertrek is om acht uur.', 'The departure is at eight o’clock.'], ['Ik wacht op het vertrek.', 'I wait for the departure.']),
    w('aankomst', 'de', 'arrival', ['De aankomst is om negen uur.', 'The arrival is at nine o’clock.'], ['De aankomst is in Gent.', 'The arrival is in Ghent.']),
    w('vertraging', 'de', 'delay', ['De trein heeft vertraging.', 'The train is delayed.'], ['Er is tien minuten vertraging.', 'There is a ten-minute delay.']),
    w('reserveren', null, 'to book; to reserve', ['Ik wil een kamer reserveren.', 'I want to book a room.'], ['Bram reserveert een tafel.', 'Bram reserves a table.'], { forms: ['reserveer', 'reserveert'] }),
    w('huren', null, 'to rent; to hire', ['Ik huur een fiets.', 'I rent a bicycle.'], ['Lotte wil een auto huren.', 'Lotte wants to hire a car.'], { forms: ['huur', 'huurt'] }),
    w('toerist', 'de', 'tourist', ['De toerist bezoekt het museum.', 'The tourist visits the museum.'], ['Er zijn veel toeristen in de stad.', 'There are many tourists in the city.'], { forms: ['toeristen'] }),
  ],
  grammarItems: [
    { nl: 'Ik ___ met de trein.', cue: 'reizen', answer: 'reis', en: 'I travel by train.' },
    { nl: 'Bram ___ naar Gent.', cue: 'reizen', answer: 'reist', en: 'Bram travels to Ghent.' },
    { nl: '___ jij met de trein?', cue: 'reizen', answer: 'Reis', en: 'Do you travel by train?' },
    { nl: 'Ik wil een kamer ___.', cue: 'reserveren', answer: 'reserveren', en: 'I want to book a room.' },
    { nl: 'Lotte wil een auto ___.', cue: 'huren', answer: 'huren', en: 'Lotte wants to hire a car.' },
    { nl: 'Ik heb twee ___.', cue: 'ticket', answer: 'tickets', en: 'I have two tickets.' },
    { nl: 'Er zijn drie ___.', cue: 'koffer', answer: 'koffers', en: 'There are three suitcases.' },
    { nl: 'De ___ bezoeken het museum.', cue: 'toerist', answer: 'toeristen', en: 'The tourists visit the museum.' },
    { nl: 'Mijn bagage ___ in de koffer.', answer: 'is', en: 'My luggage is in the suitcase.' },
    { nl: 'Het vertrek is ___ acht uur.', answer: 'om', en: 'The departure is at eight o’clock.' },
    { nl: 'Jij hebt jouw paspoort.', task: 'Make a yes/no question.', answer: 'Heb jij jouw paspoort?' },
    { nl: 'Ik heb een ticket.', task: 'Make the sentence negative.', answer: 'Ik heb geen ticket.' },
    { nl: 'De koffer is vol.', task: 'Make the sentence negative.', answer: 'De koffer is niet vol.' },
    { nl: 'Ik reis naar Gent.', task: 'Begin with Morgen.', answer: 'Morgen reis ik naar Gent.' },
    { nl: 'Bram reserveert een tafel.', task: 'Begin with Vandaag.', answer: 'Vandaag reserveert Bram een tafel.' },
    { nl: '___ is het perron?', answer: 'Waar', en: 'Where is the platform?' },
    { nl: '___ kost het ticket?', answer: 'Hoeveel', en: 'How much does the ticket cost?' },
    { nl: 'Het vliegtuig ___.', cue: 'vliegen', answer: 'vliegt', en: 'The aeroplane flies.' },
    { nl: 'Ik ___ een fiets.', cue: 'huren', answer: 'huur', en: 'I rent a bicycle.' },
    { nl: 'De ___ koffer is vol.', cue: 'blauw', answer: 'blauwe', en: 'The blue suitcase is full.' },
  ],
  story: [
    line('Het is juli. Bram en Lotte hebben vakantie.', 'It is July. Bram and Lotte are on holiday.'),
    line('Zij reizen met de trein naar zee.', 'They travel to the sea by train.'),
    line('Lotte heeft een blauwe koffer. Haar paspoort is in haar tas.', 'Lotte has a blue suitcase. Her passport is in her bag.'),
    line('Het vertrek is om acht uur. De trein heeft tien minuten vertraging.', 'The departure is at eight o’clock. The train has a ten-minute delay.'),
    line('Bram en Lotte wachten op het perron.', 'Bram and Lotte wait on the platform.'),
    line('Het ticket kost twintig euro. Het hotel is bij het station.', 'The ticket costs twenty euros. The hotel is near the station.'),
    line('Bram reserveert een kamer. Lotte huurt een fiets.', 'Bram books a room. Lotte rents a bicycle.'),
    line('In de middag wandelen zij op het strand.', 'In the afternoon they walk on the beach.'),
  ],
  questions: [
    question('Hebben Bram en Lotte vakantie?', 'Ja, Bram en Lotte hebben vakantie.', 'Are Bram and Lotte on holiday?'),
    question('Reizen zij met de trein?', 'Ja, zij reizen met de trein.', 'Do they travel by train?'),
    question('Is de koffer blauw?', 'Ja, de koffer is blauw.', 'Is the suitcase blue?'),
    question('Waar is haar paspoort?', 'Haar paspoort is in haar tas.', 'Where is her passport?'),
    question('Hoeveel minuten vertraging heeft de trein?', 'De trein heeft tien minuten vertraging.', 'How many minutes is the train delayed?'),
    question('Waar wachten Bram en Lotte?', 'Bram en Lotte wachten op het perron.', 'Where do Bram and Lotte wait?'),
    question('Hoeveel kost het ticket?', 'Het ticket kost twintig euro.', 'How much does the ticket cost?'),
    question('Wat huurt Lotte?', 'Lotte huurt een fiets.', 'What does Lotte rent?'),
  ],
};
