import { entry as w, line, question } from './entry.js';

export default {
  id: 'a1-weer', after: 'op-maandag', volume: 0,
  title: 'Vandaag is het weer mooi', subtitle: 'Twenty weather and season words. Revisit present tense, inversion, adjectives and time.', image: 'sun',
  reviewGrammar: ['present-regular', 'v2-inversion', 'adjective-e', 'days-op-om', 'geen-niet'],
  reminders: [
    'Use het for the weather: het is warm; het regent. Put the verb second when today or a season comes first: vandaag is het koud; in de herfst regent het. Use in with a season and op with a weekday: in de zomer, op maandag.',
    'Keep the familiar adjective endings: een warme dag, een koude winter, een droog shirt, het droge shirt, een natte jas. Here het weer means the weather; weer without het can also mean again in other contexts. Regen is a noun, regenen a verb: er is regen; het regent.',
  ],
  entries: [
    w('weer', 'het', 'weather', ['Het weer is mooi.', 'The weather is beautiful.'], ['Vandaag is het weer goed.', 'Today the weather is good.']),
    w('zon', 'de', 'sun', ['De zon is geel.', 'The sun is yellow.'], ['Ik zit in de zon.', 'I am sitting in the sun.']),
    w('regen', 'de', 'rain (noun)', ['Er is veel regen.', 'There is a lot of rain.'], ['Ik fiets in de regen.', 'I cycle in the rain.']),
    w('wind', 'de', 'wind', ['Er is veel wind.', 'There is a lot of wind.'], ['De wind is koud.', 'The wind is cold.']),
    w('wolk', 'de', 'cloud', ['Er is een grijze wolk.', 'There is a grey cloud.'], ['De wolken zijn wit.', 'The clouds are white.'], { forms: ['wolken'] }),
    w('sneeuw', 'de', 'snow', ['De sneeuw is wit.', 'The snow is white.'], ['Het kind speelt in de sneeuw.', 'The child plays in the snow.']),
    w('mist', 'de', 'fog', ['Er is mist.', 'There is fog.'], ['Ik wandel niet in de mist.', 'I do not walk in the fog.']),
    w('storm', 'de', 'storm', ['Er is een storm.', 'There is a storm.'], ['De storm is op maandag.', 'The storm is on Monday.'], { forms: ['stormen'] }),
    w('warm', null, 'warm; hot', ['Vandaag is het warm.', 'Today it is warm.'], ['Dit is een warme dag.', 'This is a warm day.'], { forms: ['warme'] }),
    w('koud', null, 'cold', ['Het water is koud.', 'The water is cold.'], ['Dit is een koude winter.', 'This is a cold winter.'], { forms: ['koude'] }),
    w('droog', null, 'dry', ['Mijn shirt is droog.', 'My shirt is dry.'], ['Ik heb een droge jas.', 'I have a dry coat.'], { forms: ['droge'] }),
    w('nat', null, 'wet', ['Mijn jas is nat.', 'My coat is wet.'], ['Ik heb natte schoenen.', 'I have wet shoes.'], { forms: ['natte'] }),
    w('lente', 'de', 'spring (season)', ['De lente is mooi.', 'Spring is beautiful.'], ['In de lente wandel ik graag.', 'In spring I like to walk.']),
    w('zomer', 'de', 'summer', ['De zomer is warm.', 'Summer is warm.'], ['In de zomer zwem ik graag.', 'In summer I like to swim.']),
    w('herfst', 'de', 'autumn', ['In de herfst is er veel wind.', 'In autumn there is a lot of wind.'], ['Ik fiets graag in de herfst.', 'I like to cycle in autumn.']),
    w('winter', 'de', 'winter', ['De winter is koud.', 'Winter is cold.'], ['In de winter draag ik een warme jas.', 'In winter I wear a warm coat.']),
    w('seizoen', 'het', 'season', ['De lente is een seizoen.', 'Spring is a season.'], ['Er zijn vier seizoenen.', 'There are four seasons.'], { forms: ['seizoenen'] }),
    w('buiten', null, 'outside; outdoors', ['Het kind speelt buiten.', 'The child plays outside.'], ['Buiten is het koud.', 'Outside it is cold.']),
    w('binnen', null, 'inside; indoors', ['Ik zit binnen.', 'I am sitting inside.'], ['Binnen is het warm.', 'Inside it is warm.']),
    w('regenen', null, 'to rain', ['Het regent vandaag.', 'It is raining today.'], ['Op maandag regent het.', 'On Monday it rains.'], { forms: ['regent'] }),
  ],
  grammarItems: [
    { nl: 'Vandaag ___ het warm.', answer: 'is', en: 'Today it is warm.' },
    { nl: 'Vandaag ___ het.', cue: 'regenen', answer: 'regent', en: 'Today it is raining.' },
    { nl: 'In de zomer ___ ik graag.', cue: 'zwemmen', answer: 'zwem', en: 'In summer I like to swim.' },
    { nl: 'In de herfst ___ ik graag.', cue: 'fietsen', answer: 'fiets', en: 'In autumn I like to cycle.' },
    { nl: 'Er ___ twee wolken.', answer: 'zijn', en: 'There are two clouds.' },
    { nl: 'De ___ jas is nieuw.', cue: 'nat', answer: 'natte', en: 'The wet coat is new.' },
    { nl: 'Dit is een ___ shirt.', cue: 'droog', answer: 'droog', en: 'This is a dry shirt.' },
    { nl: 'Het ___ shirt is mooi.', cue: 'droog', answer: 'droge', en: 'The dry shirt is beautiful.' },
    { nl: 'Dit is een ___ dag.', cue: 'warm', answer: 'warme', en: 'This is a warm day.' },
    { nl: 'De ___ wind is hier.', cue: 'koud', answer: 'koude', en: 'The cold wind is here.' },
    { nl: 'Het is warm.', task: 'Begin the sentence with Vandaag.', answer: 'Vandaag is het warm.' },
    { nl: 'Het regent.', task: 'Begin the sentence with Op maandag.', answer: 'Op maandag regent het.' },
    { nl: 'De jas is nat.', task: 'Make a yes/no question.', answer: 'Is de jas nat?' },
    { nl: 'Het kind speelt buiten.', task: 'Make a yes/no question.', answer: 'Speelt het kind buiten?' },
    { nl: 'Er is mist.', task: 'Make the sentence negative.', answer: 'Er is geen mist.' },
    { nl: 'Het regent.', task: 'Make the sentence negative.', answer: 'Het regent niet.' },
    { nl: '___ de winter is het koud.', answer: 'In', en: 'In winter it is cold.' },
    { nl: '___ dinsdag wandel ik buiten.', answer: 'Op', en: 'On Tuesday I walk outside.' },
    { nl: 'Er zijn vier ___.', cue: 'seizoen', answer: 'seizoenen', en: 'There are four seasons.' },
    { nl: 'Mijn ___ zijn nat.', cue: 'schoen', answer: 'schoenen', en: 'My shoes are wet.' },
  ],
  story: [
    line('Het is maandag. Het regent en er is veel wind.', 'It is Monday. It is raining and there is a lot of wind.'),
    line('Bram fietst in de regen. Zijn jas is nat.', 'Bram cycles in the rain. His coat is wet.'),
    line('Zijn schoenen zijn ook nat.', 'His shoes are wet too.'),
    line('Lotte zit binnen. Zij drinkt warme thee.', 'Lotte is sitting inside. She drinks warm tea.'),
    line('Op dinsdag is het weer mooi. Er is geen mist.', 'On Tuesday the weather is beautiful. There is no fog.'),
    line('Bram en Lotte wandelen buiten. De zon is geel.', 'Bram and Lotte walk outside. The sun is yellow.'),
    line('De lente is mooi. In de zomer wil Bram zwemmen.', 'Spring is beautiful. In summer Bram wants to swim.'),
    line('In de winter is het koud. Noor speelt graag in de sneeuw.', 'In winter it is cold. Noor likes to play in the snow.'),
  ],
  questions: [
    question('Regent het op maandag?', 'Ja, het regent op maandag.', 'Is it raining on Monday?'),
    question('Is de jas droog?', 'Nee, de jas is nat.', 'Is the coat dry?', ['Nee, de jas is niet droog.']),
    question('Zijn de schoenen nat?', 'Ja, de schoenen zijn nat.', 'Are the shoes wet?'),
    question('Zit Lotte binnen?', 'Ja, Lotte zit binnen.', 'Is Lotte sitting inside?'),
    question('Is er mist op dinsdag?', 'Nee, er is geen mist op dinsdag.', 'Is there fog on Tuesday?', ['Nee, er is op dinsdag geen mist.']),
    question('Wandelen Bram en Lotte buiten?', 'Ja, Bram en Lotte wandelen buiten.', 'Do Bram and Lotte walk outside?'),
    question('Wat wil Bram in de zomer?', 'Bram wil in de zomer zwemmen.', 'What does Bram want to do in summer?', ['Bram wil zwemmen in de zomer.']),
    question('Is het in de winter warm?', 'Nee, het is in de winter koud.', 'Is it warm in winter?', ['Nee, in de winter is het koud.', 'Nee, het is koud in de winter.', 'Nee, het is in de winter niet warm.']),
  ],
};
