import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-dieren', after: 'die-dat', volume: 2,
  title: 'Op de boerderij en in de dierentuin',
  subtitle: 'Twenty animal words. Practise plurals, relative clauses and comparisons on a day at the farm.',
  image: 'dog-big',
  reviewGrammar: ['plural', 'er-is-zijn', 'relative-clause', 'comparative', 'superlative', 'perfect-hebben', 'imperfect-strong'],
  reminders: [
    'Learn each animal with its article and plural: het paard → de paarden, de koe → de koeien, het varken → de varkens, het konijn → de konijnen. A long vowel keeps its sound in the plural with one letter: het schaap → de schapen, de aap → de apen. A short vowel doubles the consonant: de vos → de vossen. Use er is for one animal and er zijn for more: er is een geit; er zijn twee geiten.',
    'Use die after a de-word or a plural, and dat after a singular het-word: de koe die gras eet; de koeien die gras eten; het paard dat bij de boerderij staat. The verb goes to the end of the relative clause. Het schaap and het varken are het-words, so they also take dat.',
    'Compare animals with -er and dan: de olifant is groter dan het paard; het paard loopt sneller dan de koe. With het … -st you say which one is the most: de olifant is het grootst. Before a noun, the superlative takes -e: het grootste dier. To say that someone feeds an animal, use geven: Noor geeft de geiten brood; Noor heeft de geiten brood gegeven. Learn de poot → de poten for an animal’s leg or paw.',
  ],
  entries: [
    w('dier', 'het', 'animal', ['Op de boerderij zijn veel dieren.', 'There are many animals on the farm.', ['Er zijn veel dieren op de boerderij.']], ['Een olifant is een groot dier.', 'An elephant is a large animal.'], { forms: ['dieren'] }),
    w('boerderij', 'de', 'farm', ['De boerderij is oud.', 'The farm is old.'], ['Wij zijn naar een boerderij bij Leuven gegaan.', 'We went to a farm near Leuven.'], { forms: ['boerderijen'] }),
    w('boer', 'de', 'farmer', ['De boer werkt op de boerderij.', 'The farmer works on the farm.'], ['De boer heeft twintig koeien.', 'The farmer has twenty cows.'], { forms: ['boeren'] }),
    w('paard', 'het', 'horse', ['Het paard is bruin.', 'The horse is brown.'], ['Het paard loopt sneller dan de koe.', 'The horse runs faster than the cow.'], { forms: ['paarden'] }),
    w('koe', 'de', 'cow', ['De koe is zwart en wit.', 'The cow is black and white.'], ['De koeien eten gras.', 'The cows are eating grass.'], { forms: ['koeien'] }),
    w('varken', 'het', 'pig', ['Het varken is roze.', 'The pig is pink.'], ['De boer heeft tien varkens.', 'The farmer has ten pigs.'], { forms: ['varkens'] }),
    w('schaap', 'het', 'sheep', ['Het schaap is wit.', 'The sheep is white.'], ['Er staan vijf schapen op de heuvel.', 'There are five sheep on the hill.', ['Er zijn vijf schapen op de heuvel.', 'Op de heuvel staan vijf schapen.']], { forms: ['schapen'] }),
    w('geit', 'de', 'goat', ['De geit eet gras.', 'The goat is eating grass.'], ['De geit is kleiner dan het paard.', 'The goat is smaller than the horse.'], { forms: ['geiten'] }),
    w('konijn', 'het', 'rabbit', ['Het konijn eet een wortel.', 'The rabbit is eating a carrot.'], ['Vroeger hadden wij een konijn.', 'We used to have a rabbit.', ['Wij hadden vroeger een konijn.']], { forms: ['konijnen'] }),
    w('vogel', 'de', 'bird', ['De vogel zit in de boom.', 'The bird is sitting in the tree.'], ['In de lente zingen de vogels.', 'In spring the birds sing.', ['De vogels zingen in de lente.']], { forms: ['vogels'] }),
    w('eend', 'de', 'duck', ['De eend zwemt in de rivier.', 'The duck is swimming in the river.'], ['Het kind geeft de eenden brood.', 'The child gives the ducks bread.'], { forms: ['eenden'] }),
    w('vlinder', 'de', 'butterfly', ['De vlinder is geel.', 'The butterfly is yellow.'], ['Ik heb een mooie vlinder gefotografeerd.', 'I have photographed a beautiful butterfly.'], { forms: ['vlinders'] }),
    w('kikker', 'de', 'frog', ['De kikker is groen.', 'The frog is green.'], ['Bij de rivier zagen wij een kikker.', 'By the river we saw a frog.', ['Wij zagen een kikker bij de rivier.']], { forms: ['kikkers'] }),
    w('vos', 'de', 'fox', ['De vos woont in het bos.', 'The fox lives in the forest.'], ['Gisteren zag Bram een vos in de tuin.', 'Yesterday Bram saw a fox in the garden.', ['Bram zag gisteren een vos in de tuin.']], { forms: ['vossen'] }),
    w('dierentuin', 'de', 'zoo', ['De dierentuin is in Antwerpen.', 'The zoo is in Antwerp.'], ['Zaterdag gaan wij naar de dierentuin.', 'On Saturday we are going to the zoo.', ['Wij gaan zaterdag naar de dierentuin.']], { forms: ['dierentuinen'] }),
    w('olifant', 'de', 'elephant', ['De olifant is groot en grijs.', 'The elephant is large and grey.'], ['De olifant is het grootste dier in de dierentuin.', 'The elephant is the largest animal in the zoo.'], { forms: ['olifanten'] }),
    w('leeuw', 'de', 'lion', ['De leeuw slaapt in de zon.', 'The lion is sleeping in the sun.'], ['Het kind is bang voor de leeuw.', 'The child is afraid of the lion.'], { forms: ['leeuwen'] }),
    w('aap', 'de', 'monkey', ['De aap eet een banaan.', 'The monkey is eating a banana.'], ['De apen spelen in de boom.', 'The monkeys are playing in the tree.'], { forms: ['apen'] }),
    w('staart', 'de', 'tail', ['De kat heeft een lange staart.', 'The cat has a long tail.'], ['Het varken heeft een korte staart.', 'The pig has a short tail.'], { forms: ['staarten'] }),
    w('poot', 'de', 'paw; leg (of an animal)', ['De hond heeft vier poten.', 'The dog has four legs.'], ['De kat heeft een witte poot.', 'The cat has a white paw.'], { forms: ['poten'] }),
  ],
  grammarItems: [
    { nl: 'Er is één koe op de boerderij.', task: 'Replace één with drie and make the necessary plural changes.', answer: 'Er zijn drie koeien op de boerderij.' },
    { nl: 'Er is één schaap op de heuvel.', task: 'Replace één with vijf and make the necessary plural changes.', answer: 'Er zijn vijf schapen op de heuvel.' },
    { nl: 'Het paard is groot. Het paard staat bij de boerderij.', task: 'Join the sentences with a relative clause. Begin with Het paard.', answer: 'Het paard dat bij de boerderij staat, is groot.' },
    { nl: 'De koe is zwart. De koe eet gras.', task: 'Join the sentences with a relative clause. Begin with De koe.', answer: 'De koe die gras eet, is zwart.' },
    { nl: 'De apen zijn blij. De apen spelen in de boom.', task: 'Join the sentences with a relative clause. Begin with De apen.', answer: 'De apen die in de boom spelen, zijn blij.' },
    { nl: 'De boer geeft de varkens eten.', task: 'Change the sentence to the perfect tense.', answer: 'De boer heeft de varkens eten gegeven.' },
    { nl: 'Wij hebben een konijn.', task: 'Change the sentence to the simple past.', answer: 'Wij hadden een konijn.' },
    { nl: 'Wij zien een vos in het bos.', task: 'Change the sentence to the simple past.', answer: 'Wij zagen een vos in het bos.' },
    { nl: 'De olifant is groot.', task: 'Say that the elephant is bigger than the horse.', answer: 'De olifant is groter dan het paard.' },
    { nl: 'Jij geeft de eenden brood.', task: 'Make a yes/no question.', answer: 'Geef jij de eenden brood?' },
    { nl: 'Op de boerderij zijn twintig ___.', cue: 'koe', en: 'There are twenty cows on the farm.', answer: 'koeien' },
    { nl: 'De ___ eten een banaan.', cue: 'aap', en: 'The monkeys are eating a banana.', answer: 'apen' },
    { nl: 'Er zijn twee ___ in het bos.', cue: 'vos', en: 'There are two foxes in the forest.', answer: 'vossen' },
    { nl: 'Het kind geeft de ___ brood.', cue: 'schaap', en: 'The child gives the sheep bread.', answer: 'schapen' },
    { nl: 'Het konijn ___ ik zie, is wit.', en: 'The rabbit that I see is white.', answer: 'dat' },
    { nl: 'De vogels ___ in de boom zitten, zingen.', en: 'The birds that are sitting in the tree are singing.', answer: 'die' },
    { nl: 'De leeuw is ___ dan de vos.', cue: 'groot', en: 'The lion is bigger than the fox.', answer: 'groter' },
    { nl: 'De olifant is het ___ dier.', cue: 'groot', en: 'The elephant is the largest animal.', answer: 'grootste' },
    { nl: 'Vroeger ___ wij een paard.', cue: 'hebben', en: 'We used to have a horse.', answer: 'hadden' },
    { nl: 'Noor heeft de geiten brood ___.', cue: 'geven', en: 'Noor has given the goats bread.', answer: 'gegeven' },
  ],
  story: [
    line('Zaterdag gaan Bram en Lotte met Noor naar een boerderij bij Leuven.', 'On Saturday Bram and Lotte go to a farm near Leuven with Noor.'),
    line('De boer heeft koeien, varkens, schapen en twee paarden.', 'The farmer has cows, pigs, sheep and two horses.'),
    line('Noor geeft de geiten brood. De geiten eten graag brood.', 'Noor gives the goats bread. The goats like eating bread.'),
    line('Het konijn dat in de tuin zit, is wit. Het eet een wortel.', 'The rabbit that is sitting in the garden is white. It is eating a carrot.'),
    line('Bij de rivier zwemmen drie eenden. Noor geeft de eenden ook brood.', 'Three ducks are swimming by the river. Noor gives the ducks bread too.'),
    line('Lotte ziet een gele vlinder. Zij fotografeert de vlinder.', 'Lotte sees a yellow butterfly. She photographs the butterfly.'),
    line('Noor zegt: vroeger had ik een konijn, maar nu wil ik een paard!', 'Noor says: I used to have a rabbit, but now I want a horse!'),
    line('Volgende maand gaan zij naar de dierentuin in Antwerpen. Noor wil de olifanten en de apen zien.', 'Next month they are going to the zoo in Antwerp. Noor wants to see the elephants and the monkeys.'),
  ],
  questions: [
    question('Met wie gaan Bram en Lotte naar de boerderij?', 'Bram en Lotte gaan met Noor naar de boerderij.', 'Who do Bram and Lotte go to the farm with?'),
    question('Hoeveel paarden heeft de boer?', 'De boer heeft twee paarden.', 'How many horses does the farmer have?'),
    question('Wie geeft de geiten brood?', 'Noor geeft de geiten brood.', 'Who gives the goats bread?'),
    question('Wat eten de geiten graag?', 'De geiten eten graag brood.', 'What do the goats like eating?'),
    question('Is het konijn zwart?', 'Nee, het konijn is wit.', 'Is the rabbit black?', ['Nee, het konijn is niet zwart.']),
    question('Hoeveel eenden zwemmen er bij de rivier?', 'Er zwemmen drie eenden bij de rivier.', 'How many ducks are swimming by the river?', ['Bij de rivier zwemmen drie eenden.', 'Drie eenden zwemmen bij de rivier.']),
    question('Wat fotografeert Lotte?', 'Lotte fotografeert een gele vlinder.', 'What does Lotte photograph?', ['Lotte fotografeert een vlinder.', 'Lotte fotografeert de vlinder.']),
    question('Wat wil Noor in de dierentuin zien?', 'Noor wil de olifanten en de apen zien.', 'What does Noor want to see at the zoo?', ['Noor wil in de dierentuin de olifanten en de apen zien.', 'Noor wil de apen en de olifanten zien.']),
  ],
};
