import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-huishouden', after: 'ik-sta-op', volume: 2,
  title: 'Het huis is weer schoon',
  subtitle: 'Twenty words for household jobs. Combine separable verbs, the perfect tense and because-clauses.',
  image: 'kitchen',
  reviewGrammar: ['separable', 'separable-together', 'separable-perfect', 'perfect-hebben', 'verb-final', 'modals'],
  reminders: [
    'The familiar separable-verb pattern also works for household jobs: ik maak de keuken schoon; ik ruim de kamer op; ik was de borden af; ik droog de glazen af. After a modal, keep the infinitive together: ik moet de kamer opruimen. In an omdat-clause, keep it together at the end: omdat ik de kamer opruim.',
    'Use hebben for these completed jobs. Put ge between the parts of a separable verb: schoongemaakt, opgeruimd, afgewassen, afgedroogd. Learn the other participles with the verb: stofzuigen → gestofzuigd, vegen → geveegd, dweilen → gedweild, strijken → gestreken. In a perfect-tense subclause, both omdat ik heb afgewassen and omdat ik afgewassen heb are possible.',
    'De afwas means the dishes that need washing, or the washing-up as a job: ik doe de afwas. Het wasgoed means laundry. Both are used as singular collective nouns here. Remember the articles of the tools: de bezem, de emmer and de spons, but het strijkijzer and het wasrek.',
  ],
  entries: [
    w('stofzuiger', 'de', 'vacuum cleaner', ['De stofzuiger staat in de kast.', 'The vacuum cleaner is standing in the cupboard.'], ['Bram heeft een nieuwe stofzuiger gekocht.', 'Bram has bought a new vacuum cleaner.'], { forms: ['stofzuigers'] }),
    w('bezem', 'de', 'broom', ['De bezem staat bij de deur.', 'The broom is standing by the door.'], ['Lotte gebruikt een bezem in de keuken.', 'Lotte uses a broom in the kitchen.'], { forms: ['bezems'] }),
    w('emmer', 'de', 'bucket', ['De emmer is vol water.', 'The bucket is full of water.'], ['Bram draagt een lege emmer naar de tuin.', 'Bram carries an empty bucket to the garden.'], { forms: ['emmers'] }),
    w('spons', 'de', 'sponge', ['De spons is nog nat.', 'The sponge is still wet.'], ['Ik maak de tafel schoon met een spons.', 'I clean the table with a sponge.', ['Ik maak met een spons de tafel schoon.']], { forms: ['sponzen'] }),
    w('doek', 'de', 'cleaning cloth', ['De doek is schoon.', 'The cleaning cloth is clean.'], ['Lotte heeft een schone doek nodig.', 'Lotte needs a clean cloth.'], { forms: ['doeken'] }),
    w('vaatwasser', 'de', 'dishwasher', ['De vaatwasser is vol.', 'The dishwasher is full.'], ['Wij hebben geen vaatwasser in de keuken.', 'We do not have a dishwasher in the kitchen.', ['In de keuken hebben wij geen vaatwasser.', 'Wij hebben in de keuken geen vaatwasser.']], { forms: ['vaatwassers'] }),
    w('afwas', 'de', 'washing-up; dishes to wash', ['Bram heeft de afwas nog niet gedaan.', 'Bram has not done the washing-up yet.', ['Bram heeft nog niet de afwas gedaan.']], ['Bram doet de afwas in de avond.', 'Bram does the washing-up in the evening.', ['In de avond doet Bram de afwas.', 'Bram doet in de avond de afwas.']]),
    w('wasgoed', 'het', 'laundry', ['Het wasgoed is schoon.', 'The laundry is clean.'], ['Lotte draagt het natte wasgoed naar de tuin.', 'Lotte carries the wet laundry to the garden.']),
    w('strijkijzer', 'het', 'iron (for clothes)', ['Het strijkijzer is warm.', 'The iron is warm.'], ['Bram koopt een nieuw strijkijzer.', 'Bram buys a new iron.'], { forms: ['strijkijzers'] }),
    w('wasrek', 'het', 'drying rack', ['Het wasrek staat in de tuin.', 'The drying rack is standing in the garden.'], ['Ik heb een klein wasrek in de badkamer.', 'I have a small drying rack in the bathroom.'], { forms: ['wasrekken'] }),
    w('wasknijper', 'de', 'clothes peg', ['De wasknijper is niet kapot.', 'The clothes peg is not broken.'], ['Lotte koopt tien wasknijpers.', 'Lotte buys ten clothes pegs.'], { forms: ['wasknijpers'] }),
    w('vuilniszak', 'de', 'rubbish bag', ['De vuilniszak is vol.', 'The rubbish bag is full.'], ['Bram draagt een vuilniszak naar buiten.', 'Bram carries a rubbish bag outside.'], { forms: ['vuilniszakken'] }),
    w('schoonmaken', null, 'to clean', ['Bram heeft de badkamer schoongemaakt.', 'Bram has cleaned the bathroom.'], ['Ik wil de keuken schoonmaken.', 'I want to clean the kitchen.'], { forms: ['schoonmaak', 'schoonmaakt', 'schoongemaakt'] }),
    w('opruimen', null, 'to tidy up', ['Lotte heeft de woonkamer opgeruimd.', 'Lotte has tidied up the living room.'], ['Wij moeten de kamer opruimen.', 'We have to tidy up the room.'], { forms: ['ruim', 'ruimt', 'ruimen', 'opruim', 'opruimt', 'opgeruimd'] }),
    w('afwassen', null, 'to wash the dishes; to wash up', ['Bram heeft de borden afgewassen.', 'Bram has washed the plates.'], ['Ik wil de koppen afwassen.', 'I want to wash the cups.'], { forms: ['afwast', 'afgewassen'] }),
    w('afdrogen', null, 'to dry with a cloth', ['Lotte heeft de kommen afgedroogd.', 'Lotte has dried the bowls with a cloth.'], ['Ik moet de koppen afdrogen.', 'I have to dry the cups with a cloth.'], { forms: ['droogt', 'afdroog', 'afdroogt', 'afgedroogd'] }),
    w('stofzuigen', null, 'to vacuum', ['Bram heeft de woonkamer gestofzuigd.', 'Bram has vacuumed the living room.'], ['Wij willen de slaapkamer stofzuigen.', 'We want to vacuum the bedroom.'], { forms: ['stofzuig', 'stofzuigt', 'gestofzuigd'] }),
    w('vegen', null, 'to sweep', ['Ik veeg de vloer met een bezem.', 'I sweep the floor with a broom.', ['Ik veeg met een bezem de vloer.']], ['Lotte heeft de keuken geveegd.', 'Lotte has swept the kitchen.'], { forms: ['veeg', 'veegt', 'geveegd'] }),
    w('dweilen', null, 'to mop', ['Bram dweilt de vloer.', 'Bram mops the floor.'], ['Wij hebben de keuken gedweild.', 'We have mopped the kitchen.'], { forms: ['dweil', 'dweilt', 'gedweild'] }),
    w('strijken', null, 'to iron', ['Lotte strijkt een hemd.', 'Lotte irons a button-up shirt.'], ['Bram heeft zijn broek gestreken.', 'Bram has ironed his trousers.'], { forms: ['strijk', 'strijkt', 'gestreken'] }),
  ],
  grammarItems: [
    { nl: 'Ik maak de keuken schoon.', task: 'Change the subject to Wij.', answer: 'Wij maken de keuken schoon.' },
    { nl: 'Jij ruimt de kamer op.', task: 'Make a yes/no question.', answer: 'Ruim jij de kamer op?' },
    { nl: 'Lotte heeft de kommen afgedroogd.', task: 'Begin with Vandaag.', answer: 'Vandaag heeft Lotte de kommen afgedroogd.' },
    { nl: 'Bram heeft de borden afgewassen.', task: 'Make a yes/no question.', answer: 'Heeft Bram de borden afgewassen?' },
    { nl: 'Wij ruimen de woonkamer op.', task: 'Put the sentence in the perfect tense.', answer: 'Wij hebben de woonkamer opgeruimd.' },
    { nl: 'Ik strijk mijn hemd.', task: 'Put the sentence in the perfect tense.', answer: 'Ik heb mijn hemd gestreken.' },
    { nl: 'Bram stofzuigt de slaapkamer.', task: 'Say that Bram has to do this. Use moeten.', answer: 'Bram moet de slaapkamer stofzuigen.' },
    { nl: 'Lotte is thuis. Zij maakt de badkamer schoon.', task: 'Join the sentences with omdat. Begin with Lotte is thuis.', answer: 'Lotte is thuis, omdat zij de badkamer schoonmaakt.' },
    { nl: 'Ik ben thuis. Ik ruim de kamer op.', task: 'Join the sentences with omdat. Begin with Ik ben thuis.', answer: 'Ik ben thuis, omdat ik de kamer opruim.' },
    { nl: 'Wij hebben de keuken gedweild.', task: 'Make a yes/no question.', answer: 'Hebben wij de keuken gedweild?' },
    { nl: '___ jij de vloer?', cue: 'vegen', answer: 'Veeg', en: 'Do you sweep the floor?' },
    { nl: 'Lotte ___ haar hemd.', cue: 'strijken', answer: 'strijkt', en: 'Lotte irons her button-up shirt.' },
    { nl: 'Wij hebben de vloer ___.', cue: 'vegen', answer: 'geveegd', en: 'We have swept the floor.' },
    { nl: 'Bram heeft de kamer ___.', cue: 'stofzuigen', answer: 'gestofzuigd', en: 'Bram has vacuumed the room.' },
    { nl: 'Ik heb de kommen ___.', cue: 'afdrogen', answer: 'afgedroogd', en: 'I have dried the bowls with a cloth.' },
    { nl: 'Lotte is thuis, omdat zij de keuken ___.', cue: 'schoonmaken', answer: 'schoonmaakt', en: 'Lotte is at home because she is cleaning the kitchen.' },
    { nl: 'Ik weet dat Bram de kamer ___.', cue: 'opruimen', answer: 'opruimt', en: 'I know that Bram is tidying up the room.' },
    { nl: 'Bram wil de vloer ___.', cue: 'dweilen', answer: 'dweilen', en: 'Bram wants to mop the floor.' },
    { nl: 'Wij ___ de afwas al gedaan.', cue: 'hebben', answer: 'hebben', en: 'We have already done the washing-up.' },
    { nl: 'Lotte heeft haar broek ___.', cue: 'strijken', answer: 'gestreken', en: 'Lotte has ironed her trousers.' },
  ],
  story: [
    line('Het is zaterdag. Bram en Lotte willen het huis schoonmaken.', 'It is Saturday. Bram and Lotte want to clean the house.'),
    line('Bram heeft de woonkamer gestofzuigd. De stofzuiger staat nu in de kast.', 'Bram has vacuumed the living room. The vacuum cleaner is now in the cupboard.'),
    line('Lotte heeft de keuken geveegd. Nu dweilt zij de vloer.', 'Lotte has swept the kitchen. Now she is mopping the floor.'),
    line('De vaatwasser is kapot. Bram wil de borden afwassen en Lotte wil de koppen afdrogen.', 'The dishwasher is broken. Bram wants to wash the plates and Lotte wants to dry the cups.'),
    line('Het wasgoed is schoon, maar nog nat. Het wasrek staat in de tuin.', 'The laundry is clean but still wet. The drying rack is in the garden.'),
    line('Lotte heeft tien wasknijpers gekocht, omdat de oude wasknijpers kapot zijn.', 'Lotte has bought ten clothes pegs because the old clothes pegs are broken.'),
    line('Bram wil zijn hemd strijken. Het strijkijzer is al warm.', 'Bram wants to iron his button-up shirt. The iron is already warm.'),
    line('De vuilniszak is vol. Bram neemt de vuilniszak mee naar buiten.', 'The rubbish bag is full. Bram takes the rubbish bag outside with him.'),
  ],
  questions: [
    question('Wat heeft Bram gestofzuigd?', 'Bram heeft de woonkamer gestofzuigd.', 'What has Bram vacuumed?'),
    question('Waar staat de stofzuiger nu?', 'De stofzuiger staat nu in de kast.', 'Where is the vacuum cleaner now?', ['Nu staat de stofzuiger in de kast.', 'De stofzuiger staat in de kast.']),
    question('Wat heeft Lotte geveegd?', 'Lotte heeft de keuken geveegd.', 'What has Lotte swept?'),
    question('Is de vaatwasser kapot?', 'Ja, de vaatwasser is kapot.', 'Is the dishwasher broken?'),
    question('Waar staat het wasrek?', 'Het wasrek staat in de tuin.', 'Where is the drying rack?'),
    question('Hoeveel wasknijpers heeft Lotte gekocht?', 'Lotte heeft tien wasknijpers gekocht.', 'How many clothes pegs has Lotte bought?'),
    question('Wat wil Bram strijken?', 'Bram wil zijn hemd strijken.', 'What does Bram want to iron?', ['Bram wil een hemd strijken.']),
    question('Neemt Bram de vuilniszak mee naar buiten?', 'Ja, Bram neemt de vuilniszak mee naar buiten.', 'Does Bram take the rubbish bag outside with him?', ['Ja, Bram neemt de vuilniszak naar buiten mee.']),
  ],
};
