import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-kleding-kiezen', after: 'groter', volume: 2,
  title: 'Lotte kiest een nieuwe jas',
  subtitle: 'Twenty clothing and shopping words. Compare sizes, describe details and explain your choice.',
  image: 'shop',
  reviewGrammar: ['comparative', 'superlative', 'dan-als', 'adjective-e', 'perfect-hebben', 'verb-final', 'modals'],
  reminders: [
    'Compare two things with a comparative and dan: de ring is duurder dan de ketting; de mouw is langer dan mijn arm. For equal sizes, use even … als: de ring is even groot als mijn ring. After zijn, the adjective has no extra -e: de mouw is langer. Before a noun, remember the usual ending: een langere mouw, but een kleiner patroon.',
    'Use het with a superlative after zijn: de blauwe jas is het goedkoopst. Liever expresses a preference: ik draag liever katoen. Say your clothing size without an article: ik draag maat veertig. Passen has two useful meanings: ik pas de broek means I try on the trousers; de broek past means the trousers fit. Its perfect form is gepast.',
    'Learn de stof for fabric; het stof means dust and is a different meaning. Katoen and wol name materials, so use them without een when buying an amount: ik koop katoen; ik koop wol. De zak means a pocket in this lesson. Clothing can have one zak or several zakken; a jas can have a rits and knopen.',
  ],
  entries: [
    w('maat', 'de', 'clothing size', ['De maat staat op het etiket.', 'The size is on the label.'], ['Ik draag maat veertig.', 'I wear size forty.', ['Mijn maat is veertig.']], { forms: ['maten'] }),
    w('mouw', 'de', 'sleeve', ['De mouw is langer dan mijn arm.', 'The sleeve is longer than my arm.'], ['Het hemd heeft korte mouwen.', 'The button-up shirt has short sleeves.'], { forms: ['mouwen'] }),
    w('kraag', 'de', 'collar', ['De kraag is wit.', 'The collar is white.'], ['Ik zoek een hemd met een kleine kraag.', 'I am looking for a button-up shirt with a small collar.'], { forms: ['kragen'] }),
    w('knoop', 'de', 'button (on clothing)', ['De knoop is niet kapot.', 'The button is not broken.'], ['Mijn jas heeft vier grote knopen.', 'My coat has four large buttons.'], { forms: ['knopen'] }),
    w('rits', 'de', 'zip', ['De rits is open.', 'The zip is open.'], ['Bram heeft een jas met een lange rits.', 'Bram has a coat with a long zip.'], { forms: ['ritsen'] }),
    w('zak', 'de', 'pocket', ['De zak is leeg.', 'The pocket is empty.'], ['Mijn broek heeft twee kleine zakken.', 'My trousers have two small pockets.'], { forms: ['zakken'] }),
    w('stof', 'de', 'fabric', ['De stof is zacht.', 'The fabric is soft.'], ['Lotte koopt blauwe stof voor een jurk.', 'Lotte buys blue fabric for a dress.'], { forms: ['stoffen'] }),
    w('katoen', 'het', 'cotton', ['Het katoen is wit.', 'The cotton is white.'], ['Ik draag liever katoen.', 'I prefer to wear cotton.']),
    w('wol', 'de', 'wool', ['De wol is zacht.', 'The wool is soft.'], ['Ik koop wol voor een warme sjaal.', 'I buy wool for a warm scarf.']),
    w('patroon', 'het', 'pattern (on fabric)', ['Het patroon is groen en wit.', 'The pattern is green and white.'], ['Ik kies een hemd met een klein patroon.', 'I choose a button-up shirt with a small pattern.'], { forms: ['patronen'] }),
    w('streep', 'de', 'stripe', ['De streep op het shirt is blauw.', 'The stripe on the T-shirt is blue.'], ['Lotte kiest een broek met zwarte strepen.', 'Lotte chooses trousers with black stripes.'], { forms: ['strepen'] }),
    w('stip', 'de', 'dot (on fabric)', ['De stip is rood.', 'The dot is red.'], ['De jurk heeft witte stippen.', 'The dress has white dots.'], { forms: ['stippen'] }),
    w('etiket', 'het', 'label (on clothing)', ['Het etiket is klein.', 'The label is small.'], ['Lotte leest het etiket in haar nieuwe jas.', 'Lotte reads the label inside her new coat.'], { forms: ['etiketten'] }),
    w('paskamer', 'de', 'fitting room', ['De paskamer is naast de kassa.', 'The fitting room is next to the checkout.'], ['Lotte gaat naar de paskamer.', 'Lotte goes to the fitting room.'], { forms: ['paskamers'] }),
    w('oorbel', 'de', 'earring', ['De oorbel is klein.', 'The earring is small.'], ['Lotte draagt twee blauwe oorbellen.', 'Lotte wears two blue earrings.'], { forms: ['oorbellen'] }),
    w('ketting', 'de', 'necklace', ['De ketting is duurder dan de ring.', 'The necklace is more expensive than the ring.'], ['Lotte draagt een lange ketting.', 'Lotte wears a long necklace.'], { forms: ['kettingen'] }),
    w('ring', 'de', 'ring (jewellery)', ['De ring is groter dan de knoop.', 'The ring is bigger than the button.'], ['Bram koopt een ring voor Lotte.', 'Bram buys a ring for Lotte.'], { forms: ['ringen'] }),
    w('pyjama', 'de', 'pyjamas (one set)', ['Mijn pyjama is warm.', 'My pyjamas are warm.'], ['Ik wil een warmere pyjama kopen.', 'I want to buy warmer pyjamas.'], { forms: ['pyjama’s'] }),
    w('sandaal', 'de', 'sandal', ['De sandaal is licht.', 'The sandal is light.'], ['Ik draag graag sandalen in de zomer.', 'I like to wear sandals in the summer.', ['In de zomer draag ik graag sandalen.', 'Ik draag in de zomer graag sandalen.']], { forms: ['sandalen'] }),
    w('passen', null, 'to try on; to fit (clothing)', ['Lotte past een blauwe jas.', 'Lotte tries on a blue coat.'], ['De schoenen passen goed.', 'The shoes fit well.'], { forms: ['pas', 'past', 'gepast'] }),
  ],
  grammarItems: [
    { nl: 'De ring is duur.', task: 'Say that the ring is more expensive than the necklace.', answer: 'De ring is duurder dan de ketting.' },
    { nl: 'De mouw is lang.', task: 'Say that the sleeve is longer than my arm.', answer: 'De mouw is langer dan mijn arm.' },
    { nl: 'De oorbel is groot.', task: 'Say that the earring is as big as the button. Use even.', answer: 'De oorbel is even groot als de knoop.' },
    { nl: 'De blauwe jas is goedkoop.', task: 'Use the superlative: the blue coat is the cheapest.', answer: 'De blauwe jas is het goedkoopst.', accept: ['De blauwe jas is het goedkoopste.', 'De blauwe jas is de goedkoopste.'] },
    { nl: 'Ik wil een warme pyjama.', task: 'Use the comparative: you want warmer pyjamas.', answer: 'Ik wil een warmere pyjama.' },
    { nl: 'Ik kies een klein patroon.', task: 'Use the comparative: you choose a smaller pattern.', answer: 'Ik kies een kleiner patroon.' },
    { nl: 'Jij past een hemd.', task: 'Make a yes/no question.', answer: 'Pas jij een hemd?' },
    { nl: 'Lotte past de blauwe jas.', task: 'Put the sentence in the perfect tense.', answer: 'Lotte heeft de blauwe jas gepast.' },
    { nl: 'Ik koop de pyjama. De pyjama is warm.', task: 'Join the sentences with omdat. Keep the noun in both clauses.', answer: 'Ik koop de pyjama, omdat de pyjama warm is.', accept: ['Omdat de pyjama warm is, koop ik de pyjama.'] },
    { nl: 'De schoenen passen goed.', task: 'Make the sentence negative.', answer: 'De schoenen passen niet goed.' },
    { nl: 'De ketting is ___ dan de ring.', cue: 'duur', answer: 'duurder', en: 'The necklace is more expensive than the ring.' },
    { nl: 'De mouw is ___ dan mijn arm.', cue: 'lang', answer: 'langer', en: 'The sleeve is longer than my arm.' },
    { nl: 'Ik wil een ___ pyjama kopen.', cue: 'warm', answer: 'warmere', en: 'I want to buy warmer pyjamas.' },
    { nl: 'Ik kies het ___ patroon.', cue: 'klein', answer: 'kleinere', en: 'I choose the smaller pattern.' },
    { nl: 'De ring is even groot ___ de knoop.', answer: 'als', en: 'The ring is as big as the button.' },
    { nl: 'De blauwe jas is goedkoper ___ de rode jas.', answer: 'dan', en: 'The blue coat is cheaper than the red coat.' },
    { nl: 'De blauwe jas is het ___.', cue: 'goedkoop', answer: 'goedkoopst', accept: ['goedkoopste'], en: 'The blue coat is the cheapest.' },
    { nl: 'Lotte heeft de broek ___.', cue: 'passen', answer: 'gepast', en: 'Lotte has tried on the trousers.' },
    { nl: 'Ik draag ___ katoen.', cue: 'graag', answer: 'liever', en: 'I prefer to wear cotton.' },
    { nl: 'Ik weet dat de schoenen goed ___.', cue: 'passen', answer: 'passen', en: 'I know that the shoes fit well.' },
  ],
  story: [
    line('Op zaterdag gaan Bram en Lotte naar de winkel. Lotte zoekt een warme jas.', 'On Saturday Bram and Lotte go to the shop. Lotte is looking for a warm coat.'),
    line('Lotte leest het etiket. De blauwe jas heeft maat veertig.', 'Lotte reads the label. The blue coat is size forty.'),
    line('De blauwe jas kost zestig euro. De rode jas kost tachtig euro.', 'The blue coat costs sixty euros. The red coat costs eighty euros.'),
    line('Lotte gaat naar de paskamer. Zij past de blauwe jas.', 'Lotte goes to the fitting room. She tries on the blue coat.'),
    line('De jas past goed. De mouwen zijn lang en de kraag is zacht.', 'The coat fits well. The sleeves are long and the collar is soft.'),
    line('De jas heeft twee grote zakken en een rits. De rits is niet kapot.', 'The coat has two large pockets and a zip. The zip is not broken.'),
    line('Bram past een hemd met strepen. Hij wil een hemd met korte mouwen.', 'Bram tries on a striped button-up shirt. He wants a button-up shirt with short sleeves.'),
    line('Lotte koopt de blauwe jas, omdat de jas goed past. Bram koopt het hemd.', 'Lotte buys the blue coat because the coat fits well. Bram buys the button-up shirt.'),
  ],
  questions: [
    question('Wat zoekt Lotte?', 'Lotte zoekt een warme jas.', 'What is Lotte looking for?', ['Lotte zoekt een jas.']),
    question('Heeft de blauwe jas maat veertig?', 'Ja, de blauwe jas heeft maat veertig.', 'Is the blue coat size forty?'),
    question('Hoeveel kost de blauwe jas?', 'De blauwe jas kost zestig euro.', 'How much does the blue coat cost?'),
    question('Is de blauwe jas goedkoper dan de rode jas?', 'Ja, de blauwe jas is goedkoper dan de rode jas.', 'Is the blue coat cheaper than the red coat?'),
    question('Waar past Lotte de blauwe jas?', 'Lotte past de blauwe jas in de paskamer.', 'Where does Lotte try on the blue coat?', ['In de paskamer past Lotte de blauwe jas.']),
    question('Hoeveel zakken heeft de blauwe jas?', 'De blauwe jas heeft twee zakken.', 'How many pockets does the blue coat have?', ['De blauwe jas heeft twee grote zakken.']),
    question('Is de rits kapot?', 'Nee, de rits is niet kapot.', 'Is the zip broken?'),
    question('Wat koopt Bram?', 'Bram koopt het hemd.', 'What does Bram buy?', ['Bram koopt een hemd.', 'Bram koopt een hemd met strepen.', 'Bram koopt het hemd met strepen.']),
  ],
};
