import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-verzorging', after: 'die-dat', volume: 2,
  title: 'Bram scheert zich',
  subtitle: 'Twenty words for the body and the bathroom. Describe a morning routine with reflexive and separable verbs.',
  image: 'man-waking',
  reviewGrammar: ['reflexive', 'separable', 'perfect-hebben', 'pijn-hebben', 'imperative', 'plural', 'v2-inversion'],
  reminders: [
    'Some daily-care verbs are reflexive: ik scheer me, jij scheert je, hij scheert zich, wij scheren ons, jullie scheren je, zij scheren zich. Wassen and aankleden work in the same way: ik was me; Bram kleedt zich aan. In the perfect tense the pronoun stays after hebben: Bram heeft zich geschoren. The participle of scheren is geschoren.',
    'Name the place of pain with pijn hebben in: ik heb pijn in mijn nek. Learn the plurals: de vinger → de vingers, de teen → de tenen, de nagel → de nagels, de lip → de lippen, de wang → de wangen, de elleboog → de ellebogen. Put on jewellery and scarves with om: een sjaal om mijn nek, een horloge om mijn pols.',
    'In an instruction, drop the subject: poets je tanden! In this phrase je means your. Tandpasta, deodorant and parfum are amounts, so use no een: ik koop parfum. A washandje is a small bath mitt for washing; the wastafel is the washbasin.',
  ],
  entries: [
    w('vinger', 'de', 'finger', ['Ik heb vijf vingers aan mijn hand.', 'I have five fingers on my hand.'], ['Lotte heeft een pleister op haar vinger.', 'Lotte has a plaster on her finger.'], { forms: ['vingers'] }),
    w('teen', 'de', 'toe', ['Ik heb tien tenen.', 'I have ten toes.'], ['Mijn grote teen doet pijn.', 'My big toe hurts.'], { forms: ['tenen'] }),
    w('nagel', 'de', 'nail (on a finger or toe)', ['Mijn nagels zijn kort.', 'My nails are short.'], ['Lotte heeft rode nagels.', 'Lotte has red nails.'], { forms: ['nagels'] }),
    w('lip', 'de', 'lip', ['Mijn lippen zijn droog.', 'My lips are dry.'], ['Bram heeft een wond op zijn lip.', 'Bram has a cut on his lip.'], { forms: ['lippen'] }),
    w('wang', 'de', 'cheek', ['Het kind heeft rode wangen.', 'The child has red cheeks.'], ['Na het sporten zijn mijn wangen rood.', 'After exercising my cheeks are red.'], { forms: ['wangen'] }),
    w('nek', 'de', 'neck; back of the neck', ['Ik heb pijn in mijn nek.', 'I have pain in my neck.', ['Mijn nek doet pijn.']], ['Ik draag een sjaal om mijn nek.', 'I wear a scarf around my neck.'], { forms: ['nekken'] }),
    w('elleboog', 'de', 'elbow', ['Bram heeft pijn in zijn elleboog.', 'Bram has pain in his elbow.'], ['Mijn elleboog doet pijn na het tennis.', 'My elbow hurts after tennis.'], { forms: ['ellebogen'] }),
    w('pols', 'de', 'wrist', ['Het horloge zit om mijn pols.', 'The watch is around my wrist.'], ['Lotte heeft pijn in haar pols.', 'Lotte has pain in her wrist.'], { forms: ['polsen'] }),
    w('huid', 'de', 'skin', ['De baby heeft een zachte huid.', 'The baby has soft skin.'], ['In de zomer is mijn huid bruin.', 'In summer my skin is tanned.', ['Mijn huid is bruin in de zomer.']]),
    w('tandenborstel', 'de', 'toothbrush', ['Mijn tandenborstel is blauw.', 'My toothbrush is blue.'], ['Ik koop een nieuwe tandenborstel.', 'I am buying a new toothbrush.'], { forms: ['tandenborstels'] }),
    w('tandpasta', 'de', 'toothpaste', ['De tandpasta staat bij de wastafel.', 'The toothpaste is by the washbasin.'], ['Ik poets mijn tanden met tandpasta.', 'I brush my teeth with toothpaste.']),
    w('kam', 'de', 'comb', ['De kam is klein.', 'The comb is small.'], ['Ik heb een kam in mijn tas.', 'I have a comb in my bag.']),
    w('borstel', 'de', 'brush (for hair or cleaning)', ['De borstel is zacht.', 'The brush is soft.'], ['Lotte gebruikt een borstel.', 'Lotte uses a brush.'], { forms: ['borstels'] }),
    w('scheren', null, 'to shave (zich scheren: to shave oneself)', ['Bram scheert zich.', 'Bram is shaving.'], ['Bram heeft zich vandaag niet geschoren.', 'Bram has not shaved today.', ['Vandaag heeft Bram zich niet geschoren.']], { forms: ['scheer', 'scheert', 'geschoren'] }),
    w('scheermes', 'het', 'razor', ['Het scheermes is nieuw.', 'The razor is new.'], ['Bram scheert zich met een scheermes.', 'Bram shaves with a razor.'], { forms: ['scheermessen'] }),
    w('deodorant', 'de', 'deodorant', ['De deodorant staat in de badkamer.', 'The deodorant is in the bathroom.'], ['Na het sporten gebruik ik deodorant.', 'After exercising I use deodorant.']),
    w('wastafel', 'de', 'washbasin; sink (in a bathroom)', ['De wastafel is wit.', 'The washbasin is white.'], ['Ik was mijn handen aan de wastafel.', 'I wash my hands at the washbasin.'], { forms: ['wastafels'] }),
    w('washandje', 'het', 'washcloth; bath mitt', ['Het washandje is nat.', 'The washcloth is wet.'], ['Ik was mijn gezicht met een washandje.', 'I wash my face with a washcloth.'], { forms: ['washandjes'] }),
    w('badjas', 'de', 'bathrobe', ['De badjas is wit en zacht.', 'The bathrobe is white and soft.'], ['Na de douche draagt Lotte een badjas.', 'After the shower Lotte wears a bathrobe.'], { forms: ['badjassen'] }),
    w('parfum', 'het', 'perfume', ['Het parfum is duur.', 'The perfume is expensive.'], ['Lotte koopt parfum voor haar moeder.', 'Lotte buys perfume for her mother.']),
  ],
  grammarItems: [
    { nl: 'Ik scheer me.', task: 'Change the subject to Bram. Use the correct reflexive pronoun.', answer: 'Bram scheert zich.' },
    { nl: 'Wij wassen ons.', task: 'Change the subject to Lotte. Use the correct reflexive pronoun.', answer: 'Lotte wast zich.' },
    { nl: 'Bram scheert zich.', task: 'Change the sentence to the perfect tense.', answer: 'Bram heeft zich geschoren.' },
    { nl: 'Ik kleed me aan.', task: 'Begin with Om zeven uur. Keep all the words.', answer: 'Om zeven uur kleed ik me aan.' },
    { nl: 'Jij poetst je tanden.', task: 'Give a direct instruction with the imperative. Omit the subject.', answer: 'Poets je tanden!', accept: ['Poets jouw tanden!'] },
    { nl: 'Mijn nek doet pijn.', task: 'Say the same thing. Begin with Ik heb pijn in.', answer: 'Ik heb pijn in mijn nek.' },
    { nl: 'Mijn vinger is koud.', task: 'Make the subject plural: begin with Mijn vingers.', answer: 'Mijn vingers zijn koud.' },
    { nl: 'Mijn lip is droog.', task: 'Make the subject plural: begin with Mijn lippen.', answer: 'Mijn lippen zijn droog.' },
    { nl: 'Lotte draagt een badjas.', task: 'Begin with Na de douche. Keep all the words.', answer: 'Na de douche draagt Lotte een badjas.' },
    { nl: 'Bram scheert zich elke dag.', task: 'Make the sentence negative. Put niet before elke dag.', answer: 'Bram scheert zich niet elke dag.' },
    { nl: 'Bram scheert ___.', en: 'Bram is shaving.', answer: 'zich' },
    { nl: 'Ik was ___ aan de wastafel.', en: 'I wash at the washbasin.', answer: 'me' },
    { nl: 'Wij kleden ___ aan.', en: 'We get dressed.', answer: 'ons' },
    { nl: 'Ik heb tien ___.', cue: 'teen', en: 'I have ten toes.', answer: 'tenen' },
    { nl: 'Het kind heeft rode ___.', cue: 'wang', en: 'The child has red cheeks.', answer: 'wangen' },
    { nl: 'Mijn ___ zijn kort.', cue: 'nagel', en: 'My nails are short.', answer: 'nagels' },
    { nl: 'Bram heeft zich niet ___.', cue: 'scheren', en: 'Bram has not shaved.', answer: 'geschoren' },
    { nl: '___ je tanden met tandpasta!', cue: 'poetsen', en: 'Brush your teeth with toothpaste!', answer: 'Poets' },
    { nl: 'Ik heb pijn ___ mijn pols.', en: 'I have pain in my wrist.', answer: 'in' },
    { nl: 'Ik draag een sjaal ___ mijn nek.', en: 'I wear a scarf around my neck.', answer: 'om' },
  ],
  story: [
    line('Het is zeven uur. Bram staat op en gaat naar de badkamer.', 'It is seven o’clock. Bram gets up and goes to the bathroom.'),
    line('Hij wast zijn gezicht met een washandje aan de wastafel.', 'He washes his face with a washcloth at the washbasin.'),
    line('Dan scheert hij zich. Zijn scheermes is nieuw.', 'Then he shaves. His razor is new.'),
    line('Bram wil zijn tanden poetsen. Zijn tandenborstel is blauw, maar de tandpasta is op.', 'Bram wants to brush his teeth. His toothbrush is blue, but the toothpaste has run out.'),
    line('Lotte geeft Bram haar tandpasta.', 'Lotte gives Bram her toothpaste.'),
    line('Lotte draagt een badjas. Zij gebruikt een borstel en een kam.', 'Lotte is wearing a bathrobe. She uses a brush and a comb.'),
    line('Bram heeft pijn in zijn nek, want hij heeft slecht geslapen.', 'Bram has pain in his neck because he has slept badly.'),
    line('Om half acht kleedt Bram zich aan. Dan neemt hij de trein naar Brussel.', 'At half past seven Bram gets dressed. Then he takes the train to Brussels.'),
  ],
  questions: [
    question('Hoe laat staat Bram op?', 'Bram staat om zeven uur op.', 'What time does Bram get up?', ['Om zeven uur staat Bram op.']),
    question('Wast Bram zijn gezicht met een washandje?', 'Ja, Bram wast zijn gezicht met een washandje.', 'Does Bram wash his face with a washcloth?'),
    question('Is het scheermes oud?', 'Nee, het scheermes is nieuw.', 'Is the razor old?', ['Nee, het scheermes is niet oud.']),
    question('Is de tandenborstel van Bram blauw?', 'Ja, de tandenborstel van Bram is blauw.', 'Is Bram’s toothbrush blue?', ['Ja, zijn tandenborstel is blauw.']),
    question('Wie geeft Bram tandpasta?', 'Lotte geeft Bram tandpasta.', 'Who gives Bram toothpaste?', ['Lotte geeft Bram haar tandpasta.']),
    question('Wat draagt Lotte?', 'Lotte draagt een badjas.', 'What is Lotte wearing?'),
    question('Waar heeft Bram pijn?', 'Bram heeft pijn in zijn nek.', 'Where does Bram have pain?'),
    question('Hoe laat kleedt Bram zich aan?', 'Bram kleedt zich om half acht aan.', 'What time does Bram get dressed?', ['Om half acht kleedt Bram zich aan.']),
  ],
};
