import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-koken', after: 'die-dat', volume: 2,
  title: 'Bram bakt pannenkoeken',
  subtitle: 'Twenty kitchen words. Give cooking instructions, name quantities and say what you have made.',
  image: 'man-cooking',
  reviewGrammar: ['imperative', 'perfect-hebben', 'participle', 'plural', 'geen-niet', 'comparative', 'separable'],
  reminders: [
    'Give a cooking instruction with the imperative: use the ik-form and leave out the subject. Schil de appels! Roer de soep! Meng het meel en de melk! Bak de pannenkoeken in de pan! Bakken, schillen, roeren, mengen and raspen are regular: ik bak, hij bakt; ik schil, hij schilt; ik rasp, hij raspt.',
    'The participles are gebakken, geschild, geroerd, gemengd and geraspt: Lotte heeft een taart gebakken; Bram heeft de kaas geraspt. Use hebben with all of them. Bakken covers both baking in an oven and frying in a pan: pannenkoeken bakken.',
    'Meel, room, honing, jam, mosterd and chocolade are amounts, so use no een: ik eet brood met honing; ik heb geen jam. Gram and liter stay singular after a number, just like euro: honderd gram meel, twee liter melk. Countable things take a plural: één koekje, vier koekjes; één boterham, twee boterhammen.',
  ],
  entries: [
    w('bakken', null, 'to bake; to fry', ['Lotte bakt een taart.', 'Lotte is baking a cake.'], ['Bram heeft pannenkoeken gebakken.', 'Bram has made pancakes.'], { forms: ['bak', 'bakt', 'gebakken'] }),
    w('schillen', null, 'to peel', ['Ik schil een appel.', 'I am peeling an apple.'], ['Bram heeft twee appels geschild.', 'Bram has peeled two apples.'], { forms: ['schil', 'schilt', 'geschild'] }),
    w('roeren', null, 'to stir', ['Bram roert de soep.', 'Bram is stirring the soup.'], ['Roer de saus met een lepel!', 'Stir the sauce with a spoon!'], { forms: ['roer', 'roert', 'geroerd'] }),
    w('mengen', null, 'to mix', ['Lotte mengt het meel en de melk.', 'Lotte mixes the flour and the milk.'], ['Ik heb de room en de suiker gemengd.', 'I have mixed the cream and the sugar.'], { forms: ['meng', 'mengt', 'gemengd'] }),
    w('raspen', null, 'to grate', ['Bram raspt de kaas.', 'Bram is grating the cheese.'], ['Ik heb een wortel geraspt.', 'I have grated a carrot.'], { forms: ['rasp', 'raspt', 'geraspt'] }),
    w('meel', 'het', 'flour', ['Het meel is wit.', 'The flour is white.'], ['Wij hebben honderd gram meel nodig.', 'We need one hundred grams of flour.']),
    w('deeg', 'het', 'dough; batter', ['Het deeg is zacht.', 'The dough is soft.'], ['Lotte maakt deeg voor een taart.', 'Lotte is making dough for a cake.']),
    w('room', 'de', 'cream', ['De room is in de koelkast.', 'The cream is in the fridge.'], ['Ik drink koffie met room.', 'I drink coffee with cream.']),
    w('honing', 'de', 'honey', ['De honing staat op tafel.', 'The honey is on the table.', ['De honing staat op de tafel.']], ['Ik eet brood met honing.', 'I eat bread with honey.']),
    w('jam', 'de', 'jam', ['De jam is rood.', 'The jam is red.'], ['Noor eet een boterham met jam.', 'Noor eats a sandwich with jam.']),
    w('mosterd', 'de', 'mustard', ['De mosterd is geel.', 'The mustard is yellow.'], ['Bram eet kaas met mosterd.', 'Bram eats cheese with mustard.']),
    w('chocolade', 'de', 'chocolate', ['De chocolade is bruin.', 'The chocolate is brown.'], ['België heeft lekkere chocolade.', 'Belgium has tasty chocolate.']),
    w('koekje', 'het', 'biscuit; cookie', ['Het koekje is klein.', 'The biscuit is small.'], ['Oma heeft koekjes gebakken.', 'Grandma has baked biscuits.'], { forms: ['koekjes'] }),
    w('pannenkoek', 'de', 'pancake', ['De pannenkoek is warm.', 'The pancake is warm.'], ['Wij eten pannenkoeken met suiker.', 'We eat pancakes with sugar.'], { forms: ['pannenkoeken'] }),
    w('boterham', 'de', 'slice of bread; sandwich', ['Ik maak een boterham met kaas.', 'I am making a sandwich with cheese.'], ['Bram neemt twee boterhammen mee naar zijn werk.', 'Bram takes two sandwiches to work.'], { forms: ['boterhammen'] }),
    w('ingrediënt', 'het', 'ingredient', ['De ingrediënten staan op tafel.', 'The ingredients are on the table.', ['De ingrediënten staan op de tafel.']], ['Melk is een ingrediënt voor pannenkoeken.', 'Milk is an ingredient for pancakes.'], { forms: ['ingrediënten'] }),
    w('gram', 'de', 'gram', ['Ik koop honderd gram kaas.', 'I buy one hundred grams of cheese.'], ['Wij hebben vijftig gram boter nodig.', 'We need fifty grams of butter.']),
    w('liter', 'de', 'litre', ['Ik koop een liter melk.', 'I buy a litre of milk.'], ['Wij drinken elke dag twee liter water.', 'We drink two litres of water every day.', ['Elke dag drinken wij twee liter water.']]),
    w('snijplank', 'de', 'chopping board', ['Het mes is op de snijplank.', 'The knife is on the chopping board.'], ['Ik heb een nieuwe snijplank gekocht.', 'I have bought a new chopping board.'], { forms: ['snijplanken'] }),
    w('waterkoker', 'de', 'kettle', ['De waterkoker is warm.', 'The kettle is hot.'], ['Lotte maakt thee met de waterkoker.', 'Lotte makes tea with the kettle.'], { forms: ['waterkokers'] }),
  ],
  grammarItems: [
    { nl: 'Jij schilt de appels.', task: 'Give a direct instruction with the imperative. Omit the subject.', answer: 'Schil de appels!' },
    { nl: 'Jij roert de soep.', task: 'Give a direct instruction with the imperative. Omit the subject.', answer: 'Roer de soep!' },
    { nl: 'Jij mengt het meel en de melk.', task: 'Give a direct instruction with the imperative. Omit the subject.', answer: 'Meng het meel en de melk!' },
    { nl: 'Jij bakt de pannenkoeken in de pan.', task: 'Give a direct instruction with the imperative. Omit the subject.', answer: 'Bak de pannenkoeken in de pan!' },
    { nl: 'Lotte bakt een taart.', task: 'Change the sentence to the perfect tense.', answer: 'Lotte heeft een taart gebakken.' },
    { nl: 'Bram raspt de kaas.', task: 'Change the sentence to the perfect tense.', answer: 'Bram heeft de kaas geraspt.' },
    { nl: 'Wij mengen de room en de suiker.', task: 'Change the sentence to the perfect tense.', answer: 'Wij hebben de room en de suiker gemengd.' },
    { nl: 'Ik maak een boterham met jam.', task: 'Begin with Nu. Keep all the words.', answer: 'Nu maak ik een boterham met jam.' },
    { nl: 'Ik heb honing.', task: 'Make the sentence negative.', answer: 'Ik heb geen honing.' },
    { nl: 'Bram eet een pannenkoek.', task: 'Replace een with drie and make the necessary plural changes.', answer: 'Bram eet drie pannenkoeken.' },
    { nl: '___ de soep met een lepel!', cue: 'roeren', en: 'Stir the soup with a spoon!', answer: 'Roer' },
    { nl: '___ de appels!', cue: 'schillen', en: 'Peel the apples!', answer: 'Schil' },
    { nl: 'Oma heeft koekjes ___.', cue: 'bakken', en: 'Grandma has baked biscuits.', answer: 'gebakken' },
    { nl: 'Ik heb de appel ___.', cue: 'schillen', en: 'I have peeled the apple.', answer: 'geschild' },
    { nl: 'Lotte heeft het deeg ___.', cue: 'mengen', en: 'Lotte has mixed the dough.', answer: 'gemengd' },
    { nl: 'Ik koop twee ___ melk.', cue: 'liter', en: 'I buy two litres of milk.', answer: 'liter' },
    { nl: 'Wij hebben honderd ___ meel nodig.', cue: 'gram', en: 'We need one hundred grams of flour.', answer: 'gram' },
    { nl: 'Bram neemt twee ___ mee.', cue: 'boterham', en: 'Bram takes two sandwiches with him.', answer: 'boterhammen' },
    { nl: 'De kinderen eten vier ___.', cue: 'koekje', en: 'The children eat four biscuits.', answer: 'koekjes' },
    { nl: 'Lotte ___ de kaas.', cue: 'raspen', en: 'Lotte grates the cheese.', answer: 'raspt' },
  ],
  story: [
    line('Het is zondag. Bram wil pannenkoeken bakken voor Lotte.', 'It is Sunday. Bram wants to make pancakes for Lotte.'),
    line('De ingrediënten staan op tafel: meel, melk, een ei en boter.', 'The ingredients are on the table: flour, milk, an egg and butter.'),
    line('Bram heeft honderd gram meel nodig. Hij mengt het meel en de melk in een kom.', 'Bram needs one hundred grams of flour. He mixes the flour and the milk in a bowl.'),
    line('Lotte kijkt en zegt: roer goed, Bram!', 'Lotte watches and says: stir well, Bram!'),
    line('Bram bakt de pannenkoeken in een grote pan. Eén pannenkoek is kapot.', 'Bram cooks the pancakes in a large pan. One pancake is broken.'),
    line('Lotte maakt thee met de waterkoker.', 'Lotte makes tea with the kettle.'),
    line('Zij eten de pannenkoeken met suiker, jam en honing.', 'They eat the pancakes with sugar, jam and honey.'),
    line('Lotte lacht en zegt: jij kookt nu beter dan vroeger!', 'Lotte laughs and says: you cook better now than before!'),
  ],
  questions: [
    question('Wat wil Bram bakken?', 'Bram wil pannenkoeken bakken.', 'What does Bram want to make?', ['Bram wil pannenkoeken voor Lotte bakken.', 'Bram wil pannenkoeken bakken voor Lotte.']),
    question('Hoeveel gram meel heeft Bram nodig?', 'Bram heeft honderd gram meel nodig.', 'How many grams of flour does Bram need?'),
    question('Waar mengt Bram het meel en de melk?', 'Bram mengt het meel en de melk in een kom.', 'Where does Bram mix the flour and the milk?', ['In een kom mengt Bram het meel en de melk.']),
    question('Waar bakt Bram de pannenkoeken?', 'Bram bakt de pannenkoeken in een grote pan.', 'Where does Bram cook the pancakes?', ['Bram bakt de pannenkoeken in een pan.']),
    question('Hoeveel pannenkoeken zijn kapot?', 'Eén pannenkoek is kapot.', 'How many pancakes are broken?', ['Er is één pannenkoek kapot.']),
    question('Wat maakt Lotte met de waterkoker?', 'Lotte maakt thee met de waterkoker.', 'What does Lotte make with the kettle?', ['Lotte maakt thee.']),
    question('Eten Bram en Lotte de pannenkoeken met mosterd?', 'Nee, Bram en Lotte eten de pannenkoeken met suiker, jam en honing.', 'Do Bram and Lotte eat the pancakes with mustard?', ['Nee, Bram en Lotte eten de pannenkoeken niet met mosterd.']),
    question('Kookt Bram nu beter dan vroeger?', 'Ja, Bram kookt nu beter dan vroeger.', 'Does Bram cook better now than before?'),
  ],
};
