import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-digitaal', after: 'die-dat', volume: 2,
  title: 'Een bericht met een bijlage',
  subtitle: 'Twenty words for everyday digital tasks. Describe devices, exchange messages and explain what you have done.',
  image: 'colleagues',
  reviewGrammar: ['relative-clause', 'kennen-weten', 'separable', 'separable-together', 'separable-perfect', 'perfect-hebben', 'verb-final'],
  reminders: [
    'Use die after a de-word or a plural, and dat after a singular het-word: de printer die ik gebruik; het bericht dat ik lees; de bestanden die ik nodig heb. The verb goes to the end of the relative clause. Learn each noun together with its article so you can choose the right relative pronoun.',
    'Keep separable verbs together after a modal and at the end of a subordinate clause: ik wil inloggen; ik weet dat Bram het bestand opslaat. In a main clause, separate the parts: ik log in; ik sla het bestand op; ik druk het bericht af. Their participles are ingelogd, opgeslagen and afgedrukt. Use hebben for completed digital tasks: ik heb het bestand opgeslagen.',
    'Kennen expresses familiarity: ik ken de website. Weten introduces a fact: ik weet dat de website werkt. Ontvangen has no extra ge- in its participle: ik heb een bericht ontvangen. Downloaden does take ge-: ik heb het bestand gedownload. Het bestand is a digital file; de bijlage is a file attached to a message. De muis means the computer mouse here.',
  ],
  entries: [
    w('smartphone', 'de', 'smartphone', ['Mijn smartphone is nieuw.', 'My smartphone is new.'], ['De man die hier werkt, heeft een smartphone.', 'The man who works here has a smartphone.'], { forms: ['smartphones'] }),
    w('tablet', 'de', 'tablet (computer)', ['De tablet is op tafel.', 'The tablet is on the table.'], ['Lotte heeft een tablet gekocht.', 'Lotte has bought a tablet.'], { forms: ['tablets'] }),
    w('website', 'de', 'website', ['Ik ken de website.', 'I know the website.'], ['De studenten die hier wonen, gebruiken de website.', 'The students who live here use the website.'], { forms: ['websites'] }),
    w('wachtwoord', 'het', 'password', ['Mijn wachtwoord is lang.', 'My password is long.'], ['Ik heb het wachtwoord nodig voor de website.', 'I need the password for the website.'], { forms: ['wachtwoorden'] }),
    w('bericht', 'het', 'message', ['Het bericht is kort.', 'The message is short.'], ['Ik heb het bericht op mijn smartphone gelezen.', 'I have read the message on my smartphone.'], { forms: ['berichten'] }),
    w('bijlage', 'de', 'attachment (to a message)', ['De bijlage is een foto.', 'The attachment is a photo.'], ['Bram wil de bijlage openen.', 'Bram wants to open the attachment.'], { forms: ['bijlagen'] }),
    w('oplader', 'de', 'charger', ['Mijn oplader is op mijn tafel.', 'My charger is on my table.'], ['Ik zoek een witte oplader.', 'I am looking for a white charger.'], { forms: ['opladers'] }),
    w('batterij', 'de', 'battery', ['De batterij is leeg.', 'The battery is empty.'], ['Ik heb twee nieuwe batterijen nodig.', 'I need two new batteries.'], { forms: ['batterijen'] }),
    w('bestand', 'het', 'digital file', ['Het bestand staat op mijn computer.', 'The file is on my computer.'], ['Ik weet dat het bestand groot is.', 'I know that the file is large.'], { forms: ['bestanden'] }),
    w('printer', 'de', 'printer', ['De printer staat naast mijn tafel.', 'The printer is standing next to my table.'], ['Lotte weet dat de printer op kantoor staat.', 'Lotte knows that the printer is at the office.'], { forms: ['printers'] }),
    w('muis', 'de', 'computer mouse', ['De muis is naast het toetsenbord.', 'The mouse is next to the keyboard.'], ['Ik heb een nieuwe muis gekocht.', 'I have bought a new mouse.'], { forms: ['muizen'] }),
    w('kabel', 'de', 'cable', ['De kabel is lang.', 'The cable is long.'], ['Ik heb een lange kabel gekocht.', 'I have bought a long cable.'], { forms: ['kabels'] }),
    w('koptelefoon', 'de', 'headphones', ['Mijn koptelefoon is zwart.', 'My headphones are black.'], ['Ik luister met mijn koptelefoon naar muziek.', 'I listen to music with my headphones.', ['Ik luister naar muziek met mijn koptelefoon.']], { forms: ['koptelefoons'] }),
    w('verbinding', 'de', 'connection', ['De verbinding is goed.', 'The connection is good.'], ['Wij hebben thuis een snelle verbinding.', 'We have a fast connection at home.', ['Thuis hebben wij een snelle verbinding.']], { forms: ['verbindingen'] }),
    w('sturen', null, 'to send', ['Ik stuur een bericht naar Lotte.', 'I send a message to Lotte.'], ['Bram heeft een foto naar zijn zus gestuurd.', 'Bram has sent a photo to his sister.'], { forms: ['stuur', 'stuurt', 'gestuurd'] }),
    w('ontvangen', null, 'to receive', ['Ik ontvang een bericht.', 'I receive a message.'], ['Lotte heeft twee berichten ontvangen.', 'Lotte has received two messages.'], { forms: ['ontvang', 'ontvangt'] }),
    w('downloaden', null, 'to download', ['Ik wil het bestand downloaden.', 'I want to download the file.'], ['Bram heeft de foto gedownload.', 'Bram has downloaded the photo.'], { forms: ['download', 'downloadt', 'gedownload'] }),
    w('opslaan', null, 'to save (a file)', ['Ik moet het bestand opslaan.', 'I have to save the file.'], ['Lotte heeft de foto op haar computer opgeslagen.', 'Lotte has saved the photo on her computer.'], { forms: ['sla', 'slaat', 'slaan', 'opsla', 'opslaat', 'opgeslagen'] }),
    w('inloggen', null, 'to log in', ['Ik wil op de website inloggen.', 'I want to log in to the website.', ['Ik wil inloggen op de website.']], ['Bram heeft met zijn wachtwoord ingelogd.', 'Bram has logged in with his password.'], { forms: ['log', 'logt', 'loggen', 'inlog', 'inlogt', 'ingelogd'] }),
    w('afdrukken', null, 'to print', ['Ik wil het bericht afdrukken.', 'I want to print the message.'], ['Lotte heeft de uitnodiging afgedrukt.', 'Lotte has printed the invitation.'], { forms: ['afdruk', 'afdrukt', 'afgedrukt'] }),
  ],
  grammarItems: [
    { nl: 'De printer is kapot. Ik gebruik de printer.', task: 'Join the sentences with a relative clause. Begin with De printer.', answer: 'De printer die ik gebruik, is kapot.' },
    { nl: 'Het bestand is groot. Ik download het bestand.', task: 'Join the sentences with a relative clause. Begin with Het bestand.', answer: 'Het bestand dat ik download, is groot.' },
    { nl: 'De berichten zijn kort. Lotte leest de berichten.', task: 'Join the sentences with a relative clause. Begin with De berichten.', answer: 'De berichten die Lotte leest, zijn kort.' },
    { nl: 'Ik stuur een bericht naar Bram.', task: 'Change the sentence to the perfect tense.', answer: 'Ik heb een bericht naar Bram gestuurd.' },
    { nl: 'Ik sla het bestand op.', task: 'Change the sentence to the perfect tense.', answer: 'Ik heb het bestand opgeslagen.' },
    { nl: 'Bram logt in.', task: 'Make a yes/no question.', answer: 'Logt Bram in?' },
    { nl: 'Lotte wil de uitnodiging afdrukken.', task: 'Say that Lotte has completed this task. Use the perfect tense and omit willen.', answer: 'Lotte heeft de uitnodiging afgedrukt.' },
    { nl: 'Wij hebben het bericht gelezen.', task: 'Begin with Vandaag.', answer: 'Vandaag hebben wij het bericht gelezen.' },
    { nl: 'Bram slaat het bestand op.', task: 'Write a full sentence beginning with Ik weet dat.', answer: 'Ik weet dat Bram het bestand opslaat.' },
    { nl: 'Ik heb een bericht ontvangen.', task: 'Make a yes/no question.', answer: 'Heb ik een bericht ontvangen?' },
    { nl: 'De website ___ ik gebruik, werkt goed.', en: 'The website that I use works well.', answer: 'die' },
    { nl: 'Het bericht ___ ik lees, is kort.', en: 'The message that I read is short.', answer: 'dat' },
    { nl: 'De bestanden ___ ik nodig heb, zijn groot.', en: 'The files that I need are large.', answer: 'die' },
    { nl: 'Ik ___ de website al.', cue: 'kennen', en: 'I already know the website.', answer: 'ken' },
    { nl: 'Ik ___ dat de printer kapot is.', cue: 'weten', en: 'I know that the printer is broken.', answer: 'weet' },
    { nl: 'Bram heeft de foto ___.', cue: 'downloaden', en: 'Bram has downloaded the photo.', answer: 'gedownload' },
    { nl: 'Ik heb het bestand ___.', cue: 'opslaan', en: 'I have saved the file.', answer: 'opgeslagen' },
    { nl: 'Lotte heeft op de website ___.', cue: 'inloggen', en: 'Lotte has logged in to the website.', answer: 'ingelogd' },
    { nl: 'Wij hebben de uitnodiging ___.', cue: 'afdrukken', en: 'We have printed the invitation.', answer: 'afgedrukt' },
    { nl: 'Bram heeft twee berichten ___.', cue: 'ontvangen', en: 'Bram has received two messages.', answer: 'ontvangen' },
  ],
  story: [
    line('Lotte zit thuis met haar laptop. Zij wil een uitnodiging naar Bram sturen.', 'Lotte is sitting at home with her laptop. She wants to send an invitation to Bram.'),
    line('De website die zij gebruikt, werkt goed. Zij logt in met haar wachtwoord.', 'The website that she uses works well. She logs in with her password.'),
    line('Zij schrijft een kort bericht. De bijlage is de uitnodiging voor haar verjaardag.', 'She writes a short message. The attachment is the invitation to her birthday celebration.'),
    line('Lotte stuurt het bericht naar Bram. Bram ontvangt het bericht op zijn smartphone.', 'Lotte sends the message to Bram. Bram receives the message on his smartphone.'),
    line('De batterij van zijn smartphone is leeg. Zijn oplader is op zijn tafel.', 'His smartphone’s battery is empty. His charger is on his table.'),
    line('Bram opent zijn laptop. Hij heeft thuis een goede verbinding en downloadt de bijlage.', 'Bram opens his laptop. He has a good connection at home and downloads the attachment.'),
    line('Hij slaat het bestand op zijn computer op. De printer die naast zijn tafel staat, werkt goed.', 'He saves the file on his computer. The printer that stands next to his table works well.'),
    line('Bram heeft de uitnodiging afgedrukt. Hij weet dat het feest op zaterdag is.', 'Bram has printed the invitation. He knows that the party is on Saturday.'),
  ],
  questions: [
    question('Waar zit Lotte?', 'Lotte zit thuis.', 'Where is Lotte sitting?', ['Lotte zit thuis met haar laptop.']),
    question('Werkt de website goed?', 'Ja, de website werkt goed.', 'Does the website work well?'),
    question('Naar wie stuurt Lotte het bericht?', 'Lotte stuurt het bericht naar Bram.', 'To whom does Lotte send the message?'),
    question('Wat is de bijlage?', 'De bijlage is de uitnodiging voor haar verjaardag.', 'What is the attachment?', ['De bijlage is een uitnodiging.', 'De bijlage is de uitnodiging.']),
    question('Is de batterij vol?', 'Nee, de batterij is leeg.', 'Is the battery full?', ['Nee, de batterij is niet vol.']),
    question('Waar is de oplader?', 'De oplader is op zijn tafel.', 'Where is the charger?', ['De oplader is op de tafel.']),
    question('Werkt de printer goed?', 'Ja, de printer werkt goed.', 'Does the printer work well?'),
    question('Wanneer is het feest?', 'Het feest is op zaterdag.', 'When is the party?', ['Op zaterdag is het feest.']),
  ],
};
