import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-tuin', after: 'die-dat', volume: 2,
  title: 'Een zaterdag in de tuin',
  subtitle: 'Twenty garden words. Say what grows, what you have picked and what still needs to be done.',
  image: 'garden',
  reviewGrammar: ['perfect-hebben', 'perfect-zijn', 'participle', 'zullen-future', 'relative-clause', 'imperative', 'plural'],
  reminders: [
    'Maaien and plukken take hebben in the perfect tense: Bram heeft het gras gemaaid; Lotte heeft rozen geplukt. Groeien describes a change, so it takes zijn: de appelboom is veel gegroeid. To water a plant, Dutch says water geven: Lotte geeft de rozen water. As an instruction: geef de tulpen water!',
    'Learn the plurals with the words: het blad → de bladeren, de tak → de takken, de heg → de heggen, het zaad → de zaden, de roos → de rozen, de tulp → de tulpen, de appelboom → de appelbomen. Onkruid means weeds; it is one collective word: het onkruid is hoog.',
    'Use die after a de-word or a plural and dat after a singular het-word: de roos die Lotte plukt; het zaad dat Lotte koopt. In the relative clause the verbs go to the end: de roos die Lotte geplukt heeft. Use zullen for a plan: Bram zal het gazon maaien.',
  ],
  entries: [
    w('blad', 'het', 'leaf', ['Het blad is groen.', 'The leaf is green.'], ['In de herfst zijn de bladeren geel en bruin.', 'In autumn the leaves are yellow and brown.', ['De bladeren zijn geel en bruin in de herfst.']], { forms: ['bladeren'] }),
    w('tak', 'de', 'branch', ['De vogel zit op een tak.', 'The bird is sitting on a branch.'], ['De tak is lang en dun.', 'The branch is long and thin.'], { forms: ['takken'] }),
    w('struik', 'de', 'bush; shrub', ['De struik is groen.', 'The bush is green.'], ['Achter de struik zit de kat.', 'The cat is sitting behind the bush.', ['De kat zit achter de struik.']], { forms: ['struiken'] }),
    w('heg', 'de', 'hedge', ['De heg is hoog.', 'The hedge is tall.'], ['Een heg staat tussen onze tuin en de tuin van de buurman.', 'A hedge stands between our garden and the neighbour’s garden.', ['Tussen onze tuin en de tuin van de buurman staat een heg.']], { forms: ['heggen'] }),
    w('zaad', 'het', 'seed', ['Het zaad is klein.', 'The seed is small.'], ['Lotte koopt zaden voor de tuin.', 'Lotte buys seeds for the garden.'], { forms: ['zaden'] }),
    w('onkruid', 'het', 'weeds', ['Er is veel onkruid in de tuin.', 'There are a lot of weeds in the garden.', ['In de tuin is er veel onkruid.']], ['Onkruid kan snel groeien.', 'Weeds can grow quickly.']),
    w('roos', 'de', 'rose', ['De roos is rood.', 'The rose is red.'], ['Lotte heeft drie rozen geplukt.', 'Lotte has picked three roses.'], { forms: ['rozen'] }),
    w('tulp', 'de', 'tulip', ['De tulp is geel.', 'The tulip is yellow.'], ['In april zijn er veel tulpen in het park.', 'In April there are many tulips in the park.', ['Er zijn in april veel tulpen in het park.']], { forms: ['tulpen'] }),
    w('zonnebloem', 'de', 'sunflower', ['De zonnebloem is hoog en geel.', 'The sunflower is tall and yellow.'], ['De zonnebloem is groter dan Noor.', 'The sunflower is taller than Noor.'], { forms: ['zonnebloemen'] }),
    w('appelboom', 'de', 'apple tree', ['De appelboom staat achter het huis.', 'The apple tree is behind the house.'], ['Wij plukken appels van de appelboom.', 'We pick apples from the apple tree.'], { forms: ['appelbomen'] }),
    w('gazon', 'het', 'lawn', ['Het gazon is groen.', 'The lawn is green.'], ['Noor speelt op het gazon.', 'Noor is playing on the lawn.'], { forms: ['gazons'] }),
    w('grasmaaier', 'de', 'lawnmower', ['De grasmaaier staat in de schuur.', 'The lawnmower is in the shed.'], ['De grasmaaier is kapot.', 'The lawnmower is broken.'], { forms: ['grasmaaiers'] }),
    w('hark', 'de', 'rake', ['De hark staat bij de schuur.', 'The rake is by the shed.'], ['Lotte werkt met een hark in de tuin.', 'Lotte works with a rake in the garden.'], { forms: ['harken'] }),
    w('gieter', 'de', 'watering can', ['De gieter is vol water.', 'The watering can is full of water.'], ['Lotte geeft de rozen water met de gieter.', 'Lotte waters the roses with the watering can.'], { forms: ['gieters'] }),
    w('schep', 'de', 'spade; shovel', ['Bram werkt met een schep.', 'Bram is working with a spade.'], ['De schep is zwaar.', 'The spade is heavy.'], { forms: ['scheppen'] }),
    w('tuinslang', 'de', 'garden hose', ['De tuinslang is groen en lang.', 'The garden hose is green and long.'], ['In de zomer gebruiken wij de tuinslang.', 'In summer we use the garden hose.', ['Wij gebruiken de tuinslang in de zomer.']], { forms: ['tuinslangen'] }),
    w('bloempot', 'de', 'flowerpot', ['De bloempot staat op het balkon.', 'The flowerpot is on the balcony.'], ['Ik heb een nieuwe bloempot gekocht.', 'I have bought a new flowerpot.'], { forms: ['bloempotten'] }),
    w('maaien', null, 'to mow', ['Bram maait het gras.', 'Bram mows the grass.'], ['Wij hebben het gazon gemaaid.', 'We have mowed the lawn.'], { forms: ['maai', 'maait', 'gemaaid'] }),
    w('plukken', null, 'to pick (fruit or flowers)', ['Noor plukt een appel.', 'Noor picks an apple.'], ['Wij hebben kersen geplukt.', 'We have picked cherries.'], { forms: ['pluk', 'plukt', 'geplukt'] }),
    w('groeien', null, 'to grow', ['De tulpen groeien in de tuin.', 'The tulips are growing in the garden.'], ['De appelboom is dit jaar veel gegroeid.', 'The apple tree has grown a lot this year.', ['Dit jaar is de appelboom veel gegroeid.']], { forms: ['gegroeid'] }),
  ],
  grammarItems: [
    { nl: 'Bram maait het gras.', task: 'Change the sentence to the perfect tense.', answer: 'Bram heeft het gras gemaaid.' },
    { nl: 'Lotte plukt drie rozen.', task: 'Change the sentence to the perfect tense.', answer: 'Lotte heeft drie rozen geplukt.' },
    { nl: 'De zonnebloemen groeien snel.', task: 'Change the sentence to the perfect tense.', answer: 'De zonnebloemen zijn snel gegroeid.' },
    { nl: 'Jij geeft de rozen water.', task: 'Give a direct instruction with the imperative. Omit the subject.', answer: 'Geef de rozen water!' },
    { nl: 'De tulpen groeien.', task: 'Begin with In april. Keep all the words.', answer: 'In april groeien de tulpen.' },
    { nl: 'Bram maait het gazon.', task: 'Use zullen to say what will happen.', answer: 'Bram zal het gazon maaien.' },
    { nl: 'De roos is mooi. Lotte heeft de roos geplukt.', task: 'Join the sentences with a relative clause. Begin with De roos.', answer: 'De roos die Lotte geplukt heeft, is mooi.', accept: ['De roos die Lotte heeft geplukt, is mooi.'] },
    { nl: 'Het zaad is klein. Lotte koopt het zaad.', task: 'Join the sentences with a relative clause. Begin with Het zaad.', answer: 'Het zaad dat Lotte koopt, is klein.' },
    { nl: 'Er is één tulp in de tuin.', task: 'Replace één with vijf and make the necessary plural changes.', answer: 'Er zijn vijf tulpen in de tuin.' },
    { nl: 'Ik heb een grasmaaier.', task: 'Make the sentence negative.', answer: 'Ik heb geen grasmaaier.' },
    { nl: 'De appelboom is veel ___.', cue: 'groeien', en: 'The apple tree has grown a lot.', answer: 'gegroeid' },
    { nl: 'De appelboom ___ veel gegroeid.', cue: 'zijn', en: 'The apple tree has grown a lot.', answer: 'is' },
    { nl: 'Wij hebben kersen ___.', cue: 'plukken', en: 'We have picked cherries.', answer: 'geplukt' },
    { nl: 'Bram ___ het gazon.', cue: 'maaien', en: 'Bram mows the lawn.', answer: 'maait' },
    { nl: 'In de herfst zijn de ___ geel.', cue: 'blad', en: 'In autumn the leaves are yellow.', answer: 'bladeren' },
    { nl: 'Lotte koopt drie ___.', cue: 'roos', en: 'Lotte buys three roses.', answer: 'rozen' },
    { nl: 'Er zijn twee ___ in de tuin.', cue: 'appelboom', en: 'There are two apple trees in the garden.', answer: 'appelbomen' },
    { nl: 'De ___ zijn hoog.', cue: 'heg', en: 'The hedges are tall.', answer: 'heggen' },
    { nl: '___ de tulpen water!', cue: 'geven', en: 'Water the tulips!', answer: 'Geef' },
    { nl: 'De roos ___ Lotte plukt, is rood.', en: 'The rose that Lotte is picking is red.', answer: 'die' },
  ],
  story: [
    line('Het is zaterdag en het weer is mooi. Bram en Lotte werken in de tuin.', 'It is Saturday and the weather is beautiful. Bram and Lotte are working in the garden.'),
    line('Bram haalt de grasmaaier uit de schuur en maait het gazon.', 'Bram gets the lawnmower out of the shed and mows the lawn.'),
    line('Lotte werkt met een hark. Er is veel onkruid bij de heg.', 'Lotte works with a rake. There are a lot of weeds by the hedge.'),
    line('Bij de appelboom staan drie zonnebloemen. Zij zijn groter dan Bram!', 'By the apple tree there are three sunflowers. They are taller than Bram!'),
    line('Lotte plukt rozen voor de buurvrouw. De buurvrouw is blij.', 'Lotte picks roses for the neighbour. The neighbour is happy.'),
    line('Dan geeft Bram de tulpen water met de gieter.', 'Then Bram waters the tulips with the watering can.'),
    line('Noor kijkt over de heg en vraagt: mag ik een appel plukken?', 'Noor looks over the hedge and asks: may I pick an apple?'),
    line('Lotte zegt: ja, dat mag!', 'Lotte says: yes, you may!'),
  ],
  questions: [
    question('Waar werken Bram en Lotte?', 'Bram en Lotte werken in de tuin.', 'Where are Bram and Lotte working?'),
    question('Wat maait Bram?', 'Bram maait het gazon.', 'What does Bram mow?'),
    question('Waar is veel onkruid?', 'Er is veel onkruid bij de heg.', 'Where are there a lot of weeds?', ['Bij de heg is veel onkruid.', 'Bij de heg is er veel onkruid.']),
    question('Hoeveel zonnebloemen staan er bij de appelboom?', 'Er staan drie zonnebloemen bij de appelboom.', 'How many sunflowers are there by the apple tree?', ['Bij de appelboom staan drie zonnebloemen.']),
    question('Zijn de zonnebloemen kleiner dan Bram?', 'Nee, de zonnebloemen zijn groter dan Bram.', 'Are the sunflowers smaller than Bram?', ['Nee, de zonnebloemen zijn niet kleiner dan Bram.']),
    question('Voor wie plukt Lotte rozen?', 'Lotte plukt rozen voor de buurvrouw.', 'Who does Lotte pick roses for?'),
    question('Geeft Bram de tulpen water met de gieter?', 'Ja, Bram geeft de tulpen water met de gieter.', 'Does Bram water the tulips with the watering can?'),
    question('Wat wil Noor plukken?', 'Noor wil een appel plukken.', 'What does Noor want to pick?'),
  ],
};
