import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-vrije-tijd', after: 'omdat', volume: 1,
  title: 'Wat doe jij graag?',
  subtitle: 'Twenty words for hobbies, music and sport. Talk about preferences, practise and make plans with friends.',
  image: 'man-music',
  reviewGrammar: ['modals', 'infinitive-end', 'adverb-position', 'want-omdat', 'verb-final', 'als-inversion', 'perfect-hebben', 'v2-inversion'],
  reminders: [
    'Talk about what you enjoy with graag: ik speel graag gitaar; Lotte leest graag. To say what you want or can do, keep the infinitive at the end: ik wil gitaar oefenen; ik kan piano spelen. Dutch normally uses no article in gitaar spelen, piano spelen, viool spelen, voetbal spelen, tennis spelen and basketbal spelen. The vocabulary cards still show each noun’s article.',
    'Explain a preference with omdat and the verb at the end: ik ga naar de bibliotheek, omdat ik graag lees. If an als-clause comes first, the main clause begins with its verb: als het regent, oefenen wij binnen. The same inversion follows a time word: zaterdag speelt ons team.',
    'Learn the new verbs with their useful forms: oefenen → ik oefen, jij oefent, wij oefenen, ik heb geoefend; fotograferen → ik fotografeer, jij fotografeert, wij fotograferen, ik heb gefotografeerd; winnen → ik win, jij wint, wij winnen, ik heb gewonnen. The spelling of fotografeer keeps its long vowel. De speler is one player; het team is the group. Here het toneel means the stage, while het theater is the theatre.',
  ],
  entries: [
    w('hobby', 'de', 'hobby', ['Mijn hobby is tekenen.', 'My hobby is drawing.'], ['Wat is jouw hobby?', 'What is your hobby?']),
    w('voetbal', 'het', 'football (the sport)', ['Bram speelt graag voetbal.', 'Bram likes playing football.'], ['Ik kijk naar voetbal op televisie.', 'I watch football on television.']),
    w('tennis', 'het', 'tennis', ['Lotte speelt tennis op zaterdag.', 'Lotte plays tennis on Saturday.', ['Op zaterdag speelt Lotte tennis.']], ['Ik wil tennis leren spelen.', 'I want to learn to play tennis.']),
    w('basketbal', 'het', 'basketball (the sport)', ['Wij spelen basketbal in de sporthal.', 'We play basketball in the sports hall.', ['In de sporthal spelen wij basketbal.']], ['Bram wil basketbal spelen.', 'Bram wants to play basketball.']),
    w('wedstrijd', 'de', 'match; competition', ['De wedstrijd begint om drie uur.', 'The match starts at three o’clock.', ['Om drie uur begint de wedstrijd.']], ['Ons team heeft de wedstrijd gewonnen.', 'Our team has won the match.'], { forms: ['wedstrijden'] }),
    w('team', 'het', 'team', ['Ons team speelt op zondag.', 'Our team plays on Sunday.', ['Op zondag speelt ons team.']], ['Het team heeft vijf spelers.', 'The team has five players.'], { forms: ['teams'] }),
    w('speler', 'de', 'player', ['De speler draagt een groen shirt.', 'The player wears a green T-shirt.'], ['De spelers zijn blij.', 'The players are happy.'], { forms: ['spelers'] }),
    w('bal', 'de', 'ball', ['De bal is rood.', 'The ball is red.'], ['Lotte heeft een nieuwe bal gekocht.', 'Lotte has bought a new ball.'], { forms: ['ballen'] }),
    w('gitaar', 'de', 'guitar', ['Bram speelt gitaar.', 'Bram plays guitar.'], ['De gitaar staat naast de kast.', 'The guitar is standing next to the cupboard.'], { forms: ['gitaren'] }),
    w('piano', 'de', 'piano', ['De piano is oud.', 'The piano is old.'], ['Ik wil graag piano spelen.', 'I would like to play piano.']),
    w('viool', 'de', 'violin', ['Lotte speelt viool.', 'Lotte plays violin.'], ['De viool is klein.', 'The violin is small.'], { forms: ['violen'] }),
    w('lied', 'het', 'song', ['Wij zingen een lied.', 'We sing a song.'], ['Bram oefent een nieuw lied.', 'Bram practises a new song.'], { forms: ['liederen'] }),
    w('concert', 'het', 'concert', ['Het concert begint om acht uur.', 'The concert starts at eight o’clock.', ['Om acht uur begint het concert.']], ['Ik wil naar het concert gaan.', 'I want to go to the concert.'], { forms: ['concerten'] }),
    w('toneel', 'het', 'stage (in a theatre)', ['De piano staat op het toneel.', 'The piano is standing on the stage.'], ['Op het toneel staan drie stoelen.', 'There are three chairs on the stage.', ['Er staan drie stoelen op het toneel.']]),
    w('theater', 'het', 'theatre', ['Het theater is in de stad.', 'The theatre is in the city.'], ['Wij gaan zaterdag naar het theater.', 'We go to the theatre on Saturday.', ['Zaterdag gaan wij naar het theater.']], { forms: ['theaters'] }),
    w('bibliotheek', 'de', 'library', ['De bibliotheek is naast de school.', 'The library is next to the school.'], ['Ik ga naar de bibliotheek, omdat ik graag lees.', 'I go to the library because I like reading.'], { forms: ['bibliotheken'] }),
    w('schilderij', 'het', 'painting', ['Het schilderij is mooi.', 'The painting is beautiful.'], ['Lotte kijkt naar een schilderij in het museum.', 'Lotte looks at a painting in the museum.'], { forms: ['schilderijen'] }),
    w('fotograferen', null, 'to photograph', ['Bram fotografeert de stad.', 'Bram photographs the city.'], ['Ik heb de bomen gefotografeerd.', 'I have photographed the trees.'], { forms: ['fotografeer', 'fotografeert', 'gefotografeerd'] }),
    w('oefenen', null, 'to practise', ['Lotte oefent elke dag.', 'Lotte practises every day.', ['Elke dag oefent Lotte.']], ['Wij hebben in de woonkamer geoefend.', 'We have practised in the living room.'], { forms: ['oefen', 'oefent', 'geoefend'] }),
    w('winnen', null, 'to win', ['Ons team wil winnen.', 'Our team wants to win.'], ['Bram heeft de wedstrijd gewonnen.', 'Bram has won the match.'], { forms: ['win', 'wint', 'gewonnen'] }),
  ],
  grammarItems: [
    { nl: 'Ik speel gitaar.', task: 'Add graag to say that you enjoy playing guitar.', answer: 'Ik speel graag gitaar.' },
    { nl: 'Jij oefent elke dag.', task: 'Make a yes/no question.', answer: 'Oefen jij elke dag?' },
    { nl: 'Bram fotografeert de stad.', task: 'Put the sentence in the perfect tense.', answer: 'Bram heeft de stad gefotografeerd.' },
    { nl: 'Ons team wint de wedstrijd.', task: 'Put the sentence in the perfect tense.', answer: 'Ons team heeft de wedstrijd gewonnen.' },
    { nl: 'Lotte oefent in de woonkamer.', task: 'Put the sentence in the perfect tense.', answer: 'Lotte heeft in de woonkamer geoefend.' },
    { nl: 'Wij gaan naar de bibliotheek. Wij lezen graag.', task: 'Join with omdat. Begin with Wij gaan naar de bibliotheek.', answer: 'Wij gaan naar de bibliotheek, omdat wij graag lezen.' },
    { nl: 'Wij oefenen binnen, als het regent.', task: 'Begin with Als het regent. Keep all the words.', answer: 'Als het regent, oefenen wij binnen.' },
    { nl: 'Ons team speelt zondag.', task: 'Begin with Zondag. Keep all the words.', answer: 'Zondag speelt ons team.' },
    { nl: 'Bram speelt piano.', task: 'Say that Bram can play piano. Use kunnen.', answer: 'Bram kan piano spelen.' },
    { nl: 'Ik ga naar het concert.', task: 'Say that you want to go. Use willen.', answer: 'Ik wil naar het concert gaan.' },
    { nl: '___ jij elke dag?', cue: 'oefenen', en: 'Do you practise every day?', answer: 'Oefen' },
    { nl: 'Lotte ___ graag viool.', cue: 'spelen', en: 'Lotte likes playing violin.', answer: 'speelt' },
    { nl: 'Wij ___ de stad.', cue: 'fotograferen', en: 'We photograph the city.', answer: 'fotograferen' },
    { nl: 'Bram heeft de bomen ___.', cue: 'fotograferen', en: 'Bram has photographed the trees.', answer: 'gefotografeerd' },
    { nl: 'Ons team heeft ___.', cue: 'winnen', en: 'Our team has won.', answer: 'gewonnen' },
    { nl: 'Lotte heeft vandaag ___.', cue: 'oefenen', en: 'Lotte has practised today.', answer: 'geoefend' },
    { nl: 'Ik ga naar de bibliotheek, omdat ik graag ___.', cue: 'lezen', en: 'I go to the library because I like reading.', answer: 'lees' },
    { nl: 'Als het regent, ___ wij binnen.', cue: 'oefenen', en: 'If it rains, we practise indoors.', answer: 'oefenen' },
    { nl: 'Bram kan gitaar ___.', cue: 'spelen', en: 'Bram can play guitar.', answer: 'spelen' },
    { nl: 'Het concert begint ___ acht uur.', en: 'The concert starts at eight o’clock.', answer: 'om' },
  ],
  story: [
    line('Het is zaterdag. Lotte speelt tennis met een vriendin.', 'It is Saturday. Lotte plays tennis with a friend.'),
    line('Bram gaat naar het museum. Hij kijkt naar een mooi schilderij.', 'Bram goes to the museum. He looks at a beautiful painting.'),
    line('In de middag fotografeert Bram de stad. Hij fotografeert ook de bomen in het park.', 'In the afternoon Bram photographs the city. He also photographs the trees in the park.'),
    line('Lotte gaat naar de bibliotheek, omdat zij graag leest. Zij leest een Nederlands boek.', 'Lotte goes to the library because she likes reading. She reads a Dutch book.'),
    line('In de avond oefenen Bram en Lotte thuis. Bram speelt gitaar en Lotte speelt viool.', 'In the evening Bram and Lotte practise at home. Bram plays guitar and Lotte plays violin.'),
    line('Zij oefenen een nieuw lied. Het lied is nog moeilijk.', 'They practise a new song. The song is still difficult.'),
    line('Zondag gaan zij naar een concert in het theater. Het concert begint om acht uur.', 'On Sunday they go to a concert in the theatre. The concert starts at eight o’clock.'),
    line('Als het regent, nemen zij de bus. Zij willen om acht uur in het theater zijn.', 'If it rains, they take the bus. They want to be at the theatre at eight o’clock.'),
  ],
  questions: [
    question('Wat speelt Lotte op zaterdag?', 'Lotte speelt tennis op zaterdag.', 'What does Lotte play on Saturday?', ['Op zaterdag speelt Lotte tennis.', 'Lotte speelt tennis.']),
    question('Waar kijkt Bram naar een schilderij?', 'Bram kijkt in het museum naar een schilderij.', 'Where does Bram look at a painting?', ['Bram kijkt naar een schilderij in het museum.', 'In het museum kijkt Bram naar een schilderij.']),
    question('Fotografeert Bram de stad?', 'Ja, Bram fotografeert de stad.', 'Does Bram photograph the city?'),
    question('Gaat Lotte naar de bibliotheek?', 'Ja, Lotte gaat naar de bibliotheek.', 'Does Lotte go to the library?'),
    question('Waar oefenen Bram en Lotte?', 'Bram en Lotte oefenen thuis.', 'Where do Bram and Lotte practise?', ['Bram en Lotte oefenen in de avond thuis.']),
    question('Wat speelt Bram?', 'Bram speelt gitaar.', 'What does Bram play?'),
    question('Is het nieuwe lied makkelijk?', 'Nee, het nieuwe lied is nog moeilijk.', 'Is the new song easy?', ['Nee, het nieuwe lied is moeilijk.', 'Nee, het nieuwe lied is niet makkelijk.']),
    question('Hoe laat begint het concert?', 'Het concert begint om acht uur.', 'What time does the concert start?', ['Om acht uur begint het concert.']),
  ],
};
