import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-wonen', after: 'gisteren', volume: 1,
  title: 'Een woning zoeken',
  subtitle: 'Twenty words for a home and a rental visit. Combine questions, descriptions and the perfect tense.',
  image: 'flat',
  reviewGrammar: ['perfect-hebben', 'perfect-zijn', 'participle', 'v2-inversion', 'adjective-e', 'plural', 'modals', 'geen-niet'],
  reminders: [
    'Describe a home with the article and adjective together: de droge kelder, het mooie appartement, but een mooi appartement. A woning is a home or dwelling; an appartement is a flat. Een verdieping is a storey of a building; de vloer is the surface you walk on. In Belgium, a rental security deposit is called de waarborg.',
    'Keep the perfect-tense frame: Emma heeft het contract gelezen; Emma is naar het appartement gegaan. Put a time word first and the helper stays second: gisteren heeft Emma het contract gelezen. In a question, the helper comes before the subject: heb jij het contract gelezen? After a modal, use an infinitive: ik wil een appartement huren.',
  ],
  entries: [
    w('woning', 'de', 'home; dwelling', ['Ik zoek een woning in Leuven.', 'I am looking for a home in Leuven.'], ['Wij hebben een mooie woning gevonden.', 'We have found a beautiful home.'], { forms: ['woningen'] }),
    w('appartement', 'het', 'flat; apartment', ['Het appartement heeft twee kamers.', 'The flat has two rooms.'], ['Ik wil een appartement huren.', 'I want to rent a flat.'], { forms: ['appartementen'] }),
    w('contract', 'het', 'contract', ['Ik lees het contract.', 'I am reading the contract.'], ['Heb jij het contract al gelezen?', 'Have you already read the contract?'], { forms: ['contracten'] }),
    w('waarborg', 'de', 'security deposit (Belgian Dutch)', ['Ik moet een waarborg betalen.', 'I have to pay a security deposit.'], ['De waarborg is duizend euro.', 'The security deposit is one thousand euros.'], { forms: ['waarborgen'] }),
    w('kelder', 'de', 'cellar; basement', ['De kelder is onder het huis.', 'The cellar is below the house.'], ['De kelder is droog.', 'The cellar is dry.'], { forms: ['kelders'] }),
    w('zolder', 'de', 'attic', ['De zolder heeft een klein raam.', 'The attic has a small window.'], ['Wij slapen op zolder.', 'We sleep in the attic.', ['Wij slapen op de zolder.']], { forms: ['zolders'] }),
    w('gang', 'de', 'hallway; corridor', ['De gang is smal.', 'The hallway is narrow.'], ['In de gang staat een kast.', 'There is a cupboard in the hallway.', ['Er staat een kast in de gang.', 'Een kast staat in de gang.']], { forms: ['gangen'] }),
    w('brievenbus', 'de', 'letterbox', ['De brief is in de brievenbus.', 'The letter is in the letterbox.'], ['Ik heb een nieuwe brievenbus gekocht.', 'I have bought a new letterbox.'], { forms: ['brievenbussen'] }),
    w('deurbel', 'de', 'doorbell', ['De deurbel is naast de voordeur.', 'The doorbell is beside the front door.'], ['De deurbel werkt niet.', 'The doorbell does not work.'], { forms: ['deurbellen'] }),
    w('stopcontact', 'het', 'electrical socket', ['Het stopcontact is onder de tafel.', 'The electrical socket is under the table.'], ['De keuken heeft vier stopcontacten.', 'The kitchen has four electrical sockets.'], { forms: ['stopcontacten'] }),
    w('verwarming', 'de', 'heating', ['De verwarming is warm.', 'The heating is warm.'], ['Wij hebben geen verwarming in de garage.', 'We have no heating in the garage.', ['In de garage hebben wij geen verwarming.']]),
    w('lift', 'de', 'lift; elevator', ['Ik neem de lift.', 'I take the lift.'], ['Wij mogen de lift niet gebruiken.', 'We are not allowed to use the lift.'], { forms: ['liften'] }),
    w('verdieping', 'de', 'floor; storey', ['Het huis heeft drie verdiepingen.', 'The house has three storeys.'], ['Op elke verdieping is een raam.', 'There is a window on every floor.', ['Er is een raam op elke verdieping.']], { forms: ['verdiepingen'] }),
    w('schuur', 'de', 'shed', ['De fiets staat in de schuur.', 'The bicycle is in the shed.', ['De fiets is in de schuur.']], ['Bram heeft een schuur gemaakt.', 'Bram has built a shed.'], { forms: ['schuren'] }),
    w('garage', 'de', 'garage', ['De auto staat in de garage.', 'The car is in the garage.', ['De auto is in de garage.']], ['De garage heeft een brede deur.', 'The garage has a wide door.'], { forms: ['garages'] }),
    w('hek', 'het', 'gate; fence', ['Het hek is gesloten.', 'The gate is closed.'], ['Ik heb een wit hek gekocht.', 'I have bought a white gate.'], { forms: ['hekken'] }),
    w('terras', 'het', 'terrace; patio', ['Wij zitten op het terras.', 'We are sitting on the terrace.'], ['Het terras is achter het huis.', 'The terrace is behind the house.'], { forms: ['terrassen'] }),
    w('voordeur', 'de', 'front door', ['De voordeur is rood.', 'The front door is red.'], ['Ik kan de voordeur niet openen.', 'I cannot open the front door.'], { forms: ['voordeuren'] }),
    w('plafond', 'het', 'ceiling', ['Het plafond is hoog.', 'The ceiling is high.'], ['Het plafond in de keuken is laag.', 'The ceiling in the kitchen is low.', ['In de keuken is het plafond laag.']], { forms: ['plafonds'] }),
    w('dakraam', 'het', 'roof window; skylight', ['De slaapkamer heeft een dakraam.', 'The bedroom has a roof window.'], ['Ik wil het dakraam openen.', 'I want to open the roof window.'], { forms: ['dakramen'] }),
  ],
  grammarItems: [
    { nl: 'Ik lees het contract.', task: 'Rewrite in the perfect tense. Keep the same subject.', answer: 'Ik heb het contract gelezen.' },
    { nl: 'Emma gaat naar het appartement.', task: 'Rewrite in the perfect tense. Keep the same subject.', answer: 'Emma is naar het appartement gegaan.' },
    { nl: 'Jij hebt de woning gevonden.', task: 'Make a yes/no question.', answer: 'Heb jij de woning gevonden?' },
    { nl: 'Ik kan de voordeur openen.', task: 'Say that you cannot open the front door.', answer: 'Ik kan de voordeur niet openen.' },
    { nl: 'De kelder is droog.', task: 'Make the sentence negative using niet.', answer: 'De kelder is niet droog.' },
    { nl: 'Ik heb een garage.', task: 'Make the sentence negative using geen.', answer: 'Ik heb geen garage.' },
    { nl: 'Wij zitten op het terras.', task: 'Add Vandaag at the beginning. Keep the present tense.', answer: 'Vandaag zitten wij op het terras.' },
    { nl: 'Ik heb gisteren de zolder gezien.', task: 'Begin with Gisteren. Keep all the other words.', answer: 'Gisteren heb ik de zolder gezien.' },
    { nl: 'Het appartement is mooi.', task: 'Describe the flat in a sentence beginning Ik huur een. Put mooi before appartement.', answer: 'Ik huur een mooi appartement.' },
    { nl: 'Er is één stopcontact in de keuken.', task: 'Replace één with vier and make the necessary plural changes.', answer: 'Er zijn vier stopcontacten in de keuken.' },
    { nl: 'Emma ___ het contract gelezen.', cue: 'hebben', answer: 'heeft', en: 'Emma has read the contract.' },
    { nl: 'Wij ___ naar het appartement gegaan.', cue: 'zijn', answer: 'zijn', en: 'We have gone to the flat.' },
    { nl: '___ jij de woning al gezien?', cue: 'hebben', answer: 'Heb', en: 'Have you already seen the home?' },
    { nl: 'Ik heb het contract ___.', cue: 'lezen', answer: 'gelezen', en: 'I have read the contract.' },
    { nl: 'Bram heeft een schuur ___.', cue: 'maken', answer: 'gemaakt', en: 'Bram has built a shed.' },
    { nl: 'Emma is in het appartement ___.', cue: 'zijn', answer: 'geweest', en: 'Emma has been in the flat.' },
    { nl: 'Het huis heeft twee ___.', cue: 'verdieping', answer: 'verdiepingen', en: 'The house has two storeys.' },
    { nl: 'Er zijn drie ___.', cue: 'dakraam', answer: 'dakramen', en: 'There are three roof windows.' },
    { nl: 'Ik zoek een ___ woning.', cue: 'mooi', answer: 'mooie', en: 'I am looking for a beautiful home.' },
    { nl: 'Het ___ appartement heeft een terras.', cue: 'nieuw', answer: 'nieuwe', en: 'The new flat has a terrace.' },
  ],
  story: [
    line('Gisteren heeft Emma een appartement in Leuven gezien.', 'Yesterday Emma viewed a flat in Leuven.'),
    line('De woning heeft twee kamers en een groot terras.', 'The home has two rooms and a large terrace.'),
    line('In de gang is een lift. De lift werkt goed.', 'There is a lift in the hallway. The lift works well.'),
    line('De keuken heeft vier stopcontacten. De verwarming werkt ook.', 'The kitchen has four electrical sockets. The heating works too.'),
    line('Onder het appartement is een droge kelder.', 'There is a dry cellar below the flat.'),
    line('Er is geen garage, maar er is een schuur.', 'There is no garage, but there is a shed.'),
    line('Emma heeft het contract gelezen. De waarborg is duizend euro.', 'Emma has read the contract. The security deposit is one thousand euros.'),
    line('Vandaag praat Emma met Lotte. Emma wil het appartement huren.', 'Today Emma talks to Lotte. Emma wants to rent the flat.'),
  ],
  questions: [
    question('Wie heeft gisteren een appartement gezien?', 'Emma heeft gisteren een appartement gezien.', 'Who viewed a flat yesterday?', ['Gisteren heeft Emma een appartement gezien.', 'Emma heeft een appartement gezien.']),
    question('Hoeveel kamers heeft de woning?', 'De woning heeft twee kamers.', 'How many rooms does the home have?'),
    question('Waar is de lift?', 'De lift is in de gang.', 'Where is the lift?', ['De lift staat in de gang.', 'In de gang is de lift.']),
    question('Hoeveel stopcontacten heeft de keuken?', 'De keuken heeft vier stopcontacten.', 'How many electrical sockets does the kitchen have?'),
    question('Is de kelder nat?', 'Nee, de kelder is droog.', 'Is the cellar wet?', ['Nee, de kelder is niet nat.']),
    question('Is er een garage?', 'Nee, er is geen garage.', 'Is there a garage?', ['Nee, de woning heeft geen garage.']),
    question('Heeft Emma het contract gelezen?', 'Ja, Emma heeft het contract gelezen.', 'Has Emma read the contract?'),
    question('Hoeveel is de waarborg?', 'De waarborg is duizend euro.', 'How much is the security deposit?'),
  ],
};
