import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-hotel', after: 'omdat', volume: 1,
  title: 'Ik heb een reservering',
  subtitle: 'Twenty words for a hotel stay. Ask about your room, explain what you need and describe completed actions.',
  image: 'hotel',
  reviewGrammar: ['modals', 'question-word', 'perfect-hebben', 'perfect-zijn', 'want-omdat', 'verb-final', 'adjective-e'],
  reminders: [
    'At reception, use familiar questions: is er een eenpersoonskamer? Waar is het ontbijt? Kan ik de sleutelkaart gebruiken? A modal keeps the other verb at the end: ik wil een kamer reserveren. State what you need with nodig hebben: ik heb een haardroger nodig.',
    'Explain a request with omdat and put the verb at the end: ik ga naar de receptie, omdat de airconditioning niet werkt. With want, keep main-clause order: ik ga naar de receptie, want de airconditioning werkt niet. Use the perfect tense for completed actions: ik heb de bevestiging gelezen; wij zijn naar het hotel gegaan.',
    'Learn de reservering, de bevestiging and de sleutelkaart, but het ontbijt, het buffet and het uitzicht. An eenpersoonskamer is a room for one person; a tweepersoonskamer is for two people. Beddengoed is a collective word for bed linen and takes singular agreement: het beddengoed is schoon. Distinguish a thick dekbed from a thin laken.',
  ],
  entries: [
    w('reservering', 'de', 'reservation; booking', ['Ik heb een reservering.', 'I have a reservation.'], ['Mijn reservering is voor twee nachten.', 'My reservation is for two nights.'], { forms: ['reserveringen'] }),
    w('bevestiging', 'de', 'confirmation', ['De bevestiging staat op mijn telefoon.', 'The confirmation is on my phone.'], ['Ik heb de bevestiging gelezen.', 'I have read the confirmation.'], { forms: ['bevestigingen'] }),
    w('receptie', 'de', 'reception (hotel)', ['De receptie is bij de ingang.', 'Reception is near the entrance.'], ['Lotte wacht bij de receptie.', 'Lotte is waiting at reception.'], { forms: ['recepties'] }),
    w('receptionist', 'de', 'receptionist', ['De receptionist helpt Lotte.', 'The receptionist helps Lotte.'], ['Ik praat met de receptionist.', 'I am talking to the receptionist.'], { forms: ['receptionisten'] }),
    w('eenpersoonskamer', 'de', 'single room', ['Ik wil een eenpersoonskamer.', 'I would like a single room.'], ['De eenpersoonskamer heeft een klein bed.', 'The single room has a small bed.'], { forms: ['eenpersoonskamers'] }),
    w('tweepersoonskamer', 'de', 'double room; room for two', ['De tweepersoonskamer is groot.', 'The double room is large.'], ['Wij slapen twee nachten in een tweepersoonskamer.', 'We are staying in a double room for two nights.', ['Wij slapen in een tweepersoonskamer voor twee nachten.']], { forms: ['tweepersoonskamers'] }),
    w('overnachting', 'de', 'overnight stay', ['De overnachting kost zestig euro.', 'The overnight stay costs sixty euros.'], ['Wij betalen voor twee overnachtingen.', 'We are paying for two overnight stays.'], { forms: ['overnachtingen'] }),
    w('ontbijt', 'het', 'breakfast', ['Het ontbijt is om acht uur.', 'Breakfast is at eight o’clock.'], ['Bij het ontbijt drink ik koffie.', 'At breakfast I drink coffee.', ['Ik drink koffie bij het ontbijt.']]),
    w('buffet', 'het', 'buffet', ['Het buffet staat in het restaurant.', 'The buffet is in the restaurant.'], ['Bij het buffet pak ik een bord.', 'At the buffet I take a plate.', ['Ik pak een bord bij het buffet.']], { forms: ['buffetten'] }),
    w('identiteitskaart', 'de', 'identity card', ['Mijn identiteitskaart is in mijn tas.', 'My identity card is in my bag.'], ['Ik heb mijn identiteitskaart nodig.', 'I need my identity card.'], { forms: ['identiteitskaarten'] }),
    w('sleutelkaart', 'de', 'key card', ['Mijn sleutelkaart is in mijn jas.', 'My key card is in my coat.'], ['Ik open de deur met mijn sleutelkaart.', 'I open the door with my key card.', ['Met mijn sleutelkaart open ik de deur.']], { forms: ['sleutelkaarten'] }),
    w('shampoo', 'de', 'shampoo', ['De shampoo staat in de badkamer.', 'The shampoo is in the bathroom.'], ['Lotte gebruikt shampoo.', 'Lotte uses shampoo.'], { forms: ['shampoos'] }),
    w('haardroger', 'de', 'hairdryer', ['De haardroger is klein.', 'The hairdryer is small.'], ['Ik heb een haardroger nodig.', 'I need a hairdryer.'], { forms: ['haardrogers'] }),
    w('uitzicht', 'het', 'view', ['Het uitzicht is mooi.', 'The view is beautiful.'], ['Wij hebben een kamer met uitzicht op de tuin.', 'We have a room with a view of the garden.'], { forms: ['uitzichten'] }),
    w('airconditioning', 'de', 'air conditioning', ['De airconditioning werkt goed.', 'The air conditioning works well.'], ['Er is airconditioning in onze kamer.', 'There is air conditioning in our room.', ['In onze kamer is er airconditioning.']]),
    w('beddengoed', 'het', 'bed linen; bedding', ['Het beddengoed is schoon.', 'The bed linen is clean.'], ['Wij hebben schoon beddengoed nodig.', 'We need clean bed linen.']),
    w('dekbed', 'het', 'duvet', ['Het dekbed is warm.', 'The duvet is warm.'], ['Op het bed is een wit dekbed.', 'There is a white duvet on the bed.', ['Er is een wit dekbed op het bed.']], { forms: ['dekbedden'] }),
    w('laken', 'het', 'bedsheet', ['Het laken is wit.', 'The sheet is white.'], ['Ik heb een schoon laken nodig.', 'I need a clean sheet.'], { forms: ['lakens'] }),
    w('bad', 'het', 'bathtub; bath', ['Het bad is groot.', 'The bathtub is large.'], ['Onze kamer heeft een badkamer met een bad.', 'Our room has a bathroom with a bathtub.'], { forms: ['baden'] }),
    w('kluis', 'de', 'safe (for valuables)', ['De kluis staat in de kast.', 'The safe is in the cupboard.'], ['Mijn paspoort is in de kluis.', 'My passport is in the safe.'], { forms: ['kluizen'] }),
  ],
  grammarItems: [
    { nl: 'Er is een eenpersoonskamer.', task: 'Make a yes/no question.', answer: 'Is er een eenpersoonskamer?' },
    { nl: 'Ik kan de sleutelkaart gebruiken.', task: 'Make a yes/no question.', answer: 'Kan ik de sleutelkaart gebruiken?' },
    { nl: 'Lotte leest de bevestiging.', task: 'Change the sentence to the perfect tense.', answer: 'Lotte heeft de bevestiging gelezen.' },
    { nl: 'Wij gaan naar het hotel.', task: 'Change the sentence to the perfect tense.', answer: 'Wij zijn naar het hotel gegaan.' },
    { nl: 'Ik ga naar de receptie. Ik heb een haardroger nodig.', task: 'Join the sentences with omdat. Begin with Ik ga.', answer: 'Ik ga naar de receptie, omdat ik een haardroger nodig heb.' },
    { nl: 'Wij kiezen de tweepersoonskamer. Het uitzicht is mooi.', task: 'Join the sentences with omdat. Begin with Wij kiezen.', answer: 'Wij kiezen de tweepersoonskamer, omdat het uitzicht mooi is.' },
    { nl: 'Ik ga naar de receptie. De airconditioning werkt niet.', task: 'Join the sentences with want. Begin with Ik ga.', answer: 'Ik ga naar de receptie, want de airconditioning werkt niet.' },
    { nl: 'Ik drink koffie bij het ontbijt.', task: 'Begin with Bij het ontbijt. Keep all the words.', answer: 'Bij het ontbijt drink ik koffie.' },
    { nl: 'Ik heb een identiteitskaart.', task: 'Make the sentence negative.', answer: 'Ik heb geen identiteitskaart.' },
    { nl: 'De receptionist heeft Lotte geholpen.', task: 'Make a yes/no question.', answer: 'Heeft de receptionist Lotte geholpen?' },
    { nl: 'De receptionist ___ Lotte helpen.', cue: 'kunnen', en: 'The receptionist can help Lotte.', answer: 'kan' },
    { nl: '___ er een tweepersoonskamer?', cue: 'zijn', en: 'Is there a double room?', answer: 'Is' },
    { nl: 'Ik heb de bevestiging ___.', cue: 'lezen', en: 'I have read the confirmation.', answer: 'gelezen' },
    { nl: 'Wij ___ naar de receptie gegaan.', cue: 'zijn', en: 'We have gone to reception.', answer: 'zijn' },
    { nl: 'Ik ga naar de receptie, omdat ik een haardroger nodig ___.', cue: 'hebben', en: 'I am going to reception because I need a hairdryer.', answer: 'heb' },
    { nl: 'De receptionist heeft Lotte ___.', cue: 'helpen', en: 'The receptionist has helped Lotte.', answer: 'geholpen' },
    { nl: 'Ik wil een kamer met een ___ uitzicht.', cue: 'mooi', en: 'I would like a room with a beautiful view.', answer: 'mooi' },
    { nl: 'Wij hebben ___ beddengoed nodig.', cue: 'schoon', en: 'We need clean bed linen.', answer: 'schoon' },
    { nl: 'Het ontbijt is ___ acht uur.', en: 'Breakfast is at eight o’clock.', answer: 'om' },
    { nl: 'In de kamer staan twee ___.', cue: 'bed', en: 'There are two beds in the room.', answer: 'bedden' },
  ],
  story: [
    line('Lotte en Bram zijn naar Gent gegaan. Zij slapen twee nachten in een hotel.', 'Lotte and Bram have gone to Ghent. They are staying at a hotel for two nights.'),
    line('Bij de receptie zegt Lotte: ik heb een reservering voor een tweepersoonskamer. De bevestiging staat op mijn telefoon.', 'At reception Lotte says: I have a reservation for a double room. The confirmation is on my phone.'),
    line('De receptionist wil de identiteitskaart zien. Lotte pakt haar identiteitskaart.', 'The receptionist wants to see the identity card. Lotte takes out her identity card.'),
    line('De receptionist geeft Lotte een sleutelkaart. Het ontbijt is om acht uur in het restaurant.', 'The receptionist gives Lotte a key card. Breakfast is at eight o’clock in the restaurant.'),
    line('De kamer heeft uitzicht op de tuin. Er is een badkamer met een groot bad.', 'The room has a view of the garden. There is a bathroom with a large bathtub.'),
    line('Het beddengoed is schoon en het dekbed is wit. Bram doet zijn tas in de kast.', 'The bed linen is clean and the duvet is white. Bram puts his bag in the cupboard.'),
    line('Lotte wil een haardroger gebruiken. In de badkamer is geen haardroger.', 'Lotte wants to use a hairdryer. There is no hairdryer in the bathroom.'),
    line('Lotte gaat naar de receptie en vraagt: mag ik een haardroger gebruiken? De receptionist zegt: ja, ik kan helpen.', 'Lotte goes to reception and asks: may I use a hairdryer? The receptionist says: yes, I can help.'),
  ],
  questions: [
    question('Waar is het hotel?', 'Het hotel is in Gent.', 'Where is the hotel?'),
    question('Hoeveel nachten slapen Lotte en Bram in het hotel?', 'Lotte en Bram slapen twee nachten in het hotel.', 'How many nights are Lotte and Bram staying at the hotel?'),
    question('Heeft Lotte een reservering voor een eenpersoonskamer?', 'Nee, Lotte heeft een reservering voor een tweepersoonskamer.', 'Does Lotte have a reservation for a single room?', ['Nee, Lotte heeft geen reservering voor een eenpersoonskamer.']),
    question('Waar staat de bevestiging?', 'De bevestiging staat op haar telefoon.', 'Where is the confirmation?', ['De bevestiging staat op de telefoon.']),
    question('Hoe laat is het ontbijt?', 'Het ontbijt is om acht uur.', 'What time is breakfast?'),
    question('Heeft de badkamer een bad?', 'Ja, de badkamer heeft een groot bad.', 'Does the bathroom have a bathtub?', ['Ja, de badkamer heeft een bad.']),
    question('Is het beddengoed schoon?', 'Ja, het beddengoed is schoon.', 'Is the bed linen clean?'),
    question('Wat heeft Lotte nodig?', 'Lotte heeft een haardroger nodig.', 'What does Lotte need?'),
  ],
};
