import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-beroepen', after: 'die-dat', volume: 2,
  title: 'Mijn tante is kunstenaar',
  subtitle: 'Twenty words for jobs and work. Say what people do, who you call for help and what will happen.',
  image: 'colleagues',
  reviewGrammar: ['present-regular', 'relative-clause', 'zullen-future', 'perfect-hebben', 'want-omdat', 'dat-clause', 'v2-inversion'],
  reminders: [
    'After zijn, Dutch usually names a job without een: mijn tante is kunstenaar; Bram is geen kok. With werken, use als: Lotte werkt als advocaat. Many job words are used for everyone, whatever their gender: de tandarts, de piloot, de dierenarts.',
    'Maken can also mean to repair: de loodgieter maakt de douche; de monteur heeft mijn auto gemaakt. Naar de kapper and naar de tandarts mean to the hairdresser’s and to the dentist’s. De werkgever pays het salaris; de werknemers work for the company.',
    'Use die after a de-word or a plural and dat after a singular het-word: de kok die wij kennen; het uniform dat de piloot draagt. Use zullen for a plan or expectation, with the infinitive at the end: de elektricien zal morgen komen. Omdat sends its verb to the end: ik bel de loodgieter, omdat het toilet kapot is.',
  ],
  entries: [
    w('kok', 'de', 'cook; chef', ['De kok werkt in een restaurant.', 'The cook works in a restaurant.'], ['De kok heeft een lekker gerecht gemaakt.', 'The cook has made a tasty dish.'], { forms: ['koks'] }),
    w('kapper', 'de', 'hairdresser; barber', ['De kapper werkt in een kleine winkel.', 'The hairdresser works in a small shop.'], ['Ik ga morgen naar de kapper.', 'I am going to the hairdresser’s tomorrow.', ['Morgen ga ik naar de kapper.']], { forms: ['kappers'] }),
    w('schilder', 'de', 'painter (of houses)', ['De schilder staat op een trap.', 'The painter is standing on a stepladder.'], ['Wij hebben een schilder nodig voor de keuken.', 'We need a painter for the kitchen.'], { forms: ['schilders'] }),
    w('loodgieter', 'de', 'plumber', ['De loodgieter maakt de douche.', 'The plumber is repairing the shower.'], ['Ik bel de loodgieter, omdat het toilet kapot is.', 'I am phoning the plumber because the toilet is broken.'], { forms: ['loodgieters'] }),
    w('elektricien', 'de', 'electrician', ['De elektricien werkt aan het stopcontact.', 'The electrician is working on the socket.'], ['De elektricien zal morgen komen.', 'The electrician will come tomorrow.', ['Morgen zal de elektricien komen.']], { forms: ['elektriciens'] }),
    w('politieagent', 'de', 'police officer', ['De politieagent staat op het kruispunt.', 'The police officer is standing at the crossroads.'], ['De politieagent helpt het kind.', 'The police officer helps the child.'], { forms: ['politieagenten'] }),
    w('brandweerman', 'de', 'firefighter', ['De brandweerman is sterk.', 'The firefighter is strong.'], ['De brandweerman heeft de kat uit de boom geholpen.', 'The firefighter has helped the cat out of the tree.'], { forms: ['brandweermannen'] }),
    w('piloot', 'de', 'pilot', ['De piloot zit in het vliegtuig.', 'The pilot is sitting in the aeroplane.'], ['De piloot vliegt morgen naar Spanje.', 'The pilot is flying to Spain tomorrow.', ['Morgen vliegt de piloot naar Spanje.']], { forms: ['piloten'] }),
    w('tandarts', 'de', 'dentist', ['De tandarts kijkt naar mijn tanden.', 'The dentist looks at my teeth.'], ['Ik heb morgen een afspraak bij de tandarts.', 'I have an appointment at the dentist’s tomorrow.', ['Morgen heb ik een afspraak bij de tandarts.']], { forms: ['tandartsen'] }),
    w('dierenarts', 'de', 'vet', ['De dierenarts helpt de hond.', 'The vet helps the dog.'], ['Lotte gaat met Mimi naar de dierenarts.', 'Lotte goes to the vet with Mimi.'], { forms: ['dierenartsen'] }),
    w('advocaat', 'de', 'lawyer', ['De advocaat leest het contract.', 'The lawyer is reading the contract.'], ['Mijn zus werkt als advocaat in Brussel.', 'My sister works as a lawyer in Brussels.'], { forms: ['advocaten'] }),
    w('postbode', 'de', 'postman; postwoman', ['De postbode heeft een pakket voor ons.', 'The postman has a parcel for us.'], ['De postbode doet de brief in de brievenbus.', 'The postman puts the letter in the letterbox.'], { forms: ['postbodes'] }),
    w('kassier', 'de', 'cashier', ['De kassier werkt bij de kassa.', 'The cashier works at the checkout.'], ['Ik betaal contant bij de kassier.', 'I pay in cash at the cashier.'], { forms: ['kassiers'] }),
    w('monteur', 'de', 'mechanic', ['De monteur maakt mijn auto.', 'The mechanic is repairing my car.'], ['De monteur werkt in een garage.', 'The mechanic works in a garage.'], { forms: ['monteurs'] }),
    w('kunstenaar', 'de', 'artist', ['De kunstenaar maakt een schilderij.', 'The artist is making a painting.'], ['Mijn tante is kunstenaar.', 'My aunt is an artist.'], { forms: ['kunstenaars'] }),
    w('schoonmaker', 'de', 'cleaner', ['De schoonmaker maakt het kantoor schoon.', 'The cleaner cleans the office.'], ['De schoonmaker begint om zes uur.', 'The cleaner starts at six o’clock.', ['Om zes uur begint de schoonmaker.']], { forms: ['schoonmakers'] }),
    w('uniform', 'het', 'uniform', ['Het uniform is blauw.', 'The uniform is blue.'], ['De politieagent draagt een blauw uniform.', 'The police officer wears a blue uniform.'], { forms: ['uniformen'] }),
    w('salaris', 'het', 'salary; pay', ['Mijn salaris is niet hoog.', 'My salary is not high.'], ['De piloot heeft een hoog salaris.', 'The pilot has a high salary.'], { forms: ['salarissen'] }),
    w('werkgever', 'de', 'employer', ['Mijn werkgever is een groot bedrijf.', 'My employer is a large company.'], ['De werkgever betaalt het salaris.', 'The employer pays the salary.'], { forms: ['werkgevers'] }),
    w('werknemer', 'de', 'employee', ['Het bedrijf heeft honderd werknemers.', 'The company has one hundred employees.'], ['De werknemers beginnen om acht uur.', 'The employees start at eight o’clock.', ['Om acht uur beginnen de werknemers.']], { forms: ['werknemers'] }),
  ],
  grammarItems: [
    { nl: 'Ik werk als kok.', task: 'Change the subject to Bram.', answer: 'Bram werkt als kok.' },
    { nl: 'De loodgieter maakt de douche.', task: 'Change the sentence to the perfect tense.', answer: 'De loodgieter heeft de douche gemaakt.' },
    { nl: 'De brandweerman helpt de kat uit de boom.', task: 'Change the sentence to the perfect tense.', answer: 'De brandweerman heeft de kat uit de boom geholpen.' },
    { nl: 'De elektricien komt morgen.', task: 'Use zullen to say what will happen.', answer: 'De elektricien zal morgen komen.' },
    { nl: 'De politieagent is jong. De politieagent staat op het plein.', task: 'Join the sentences with a relative clause. Begin with De politieagent.', answer: 'De politieagent die op het plein staat, is jong.' },
    { nl: 'Het uniform is blauw. De piloot draagt het uniform.', task: 'Join the sentences with a relative clause. Begin with Het uniform.', answer: 'Het uniform dat de piloot draagt, is blauw.' },
    { nl: 'Ik bel de loodgieter. Het toilet is kapot.', task: 'Join the sentences with omdat. Begin with Ik bel de loodgieter.', answer: 'Ik bel de loodgieter, omdat het toilet kapot is.' },
    { nl: 'De kapper werkt op zaterdag.', task: 'Begin with Op zaterdag. Keep all the words.', answer: 'Op zaterdag werkt de kapper.' },
    { nl: 'Jij werkt als kassier.', task: 'Make a yes/no question.', answer: 'Werk jij als kassier?' },
    { nl: 'Het salaris is hoog.', task: 'Report your thought. Begin with Ik denk dat.', answer: 'Ik denk dat het salaris hoog is.' },
    { nl: 'Mijn tante is ___.', en: 'My aunt is an artist.', answer: 'kunstenaar' },
    { nl: 'Lotte werkt ___ advocaat.', en: 'Lotte works as a lawyer.', answer: 'als' },
    { nl: 'De piloot ___ naar Spanje.', cue: 'vliegen', en: 'The pilot flies to Spain.', answer: 'vliegt' },
    { nl: 'Het bedrijf heeft honderd ___.', cue: 'werknemer', en: 'The company has one hundred employees.', answer: 'werknemers' },
    { nl: 'De twee ___ werken in Gent.', cue: 'advocaat', en: 'The two lawyers work in Ghent.', answer: 'advocaten' },
    { nl: 'De monteur heeft mijn auto ___.', cue: 'maken', en: 'The mechanic has repaired my car.', answer: 'gemaakt' },
    { nl: 'De kok ___ wij kennen, werkt in Gent.', en: 'The cook we know works in Ghent.', answer: 'die' },
    { nl: 'Het uniform ___ hij draagt, is nieuw.', en: 'The uniform that he is wearing is new.', answer: 'dat' },
    { nl: 'De elektricien ___ morgen komen.', cue: 'zullen', en: 'The electrician will come tomorrow.', answer: 'zal' },
    { nl: 'Ik weet ___ de postbode om tien uur komt.', en: 'I know that the postman comes at ten o’clock.', answer: 'dat' },
  ],
  story: [
    line('Het is zaterdag. De douche van Bram en Lotte is kapot.', 'It is Saturday. Bram and Lotte’s shower is broken.'),
    line('Lotte belt de loodgieter. De loodgieter zal om tien uur komen.', 'Lotte phones the plumber. The plumber will come at ten o’clock.'),
    line('Om tien uur staat de loodgieter bij de voordeur. Hij draagt een blauwe broek.', 'At ten o’clock the plumber is standing at the front door. He is wearing blue trousers.'),
    line('De loodgieter maakt de douche. Na een uur werkt de douche weer goed.', 'The plumber repairs the shower. After an hour the shower works well again.'),
    line('De postbode heeft een pakket voor Lotte. Het pakket is van haar tante.', 'The postman has a parcel for Lotte. The parcel is from her aunt.'),
    line('Haar tante is kunstenaar. Zij heeft een klein schilderij voor Lotte gemaakt.', 'Her aunt is an artist. She has made a small painting for Lotte.'),
    line('In de middag gaat Bram naar de kapper. Zijn kapper werkt ook op zaterdag.', 'In the afternoon Bram goes to the hairdresser’s. His hairdresser also works on Saturday.'),
    line('Lotte lacht en zegt: een loodgieter heeft een goed salaris!', 'Lotte laughs and says: a plumber has a good salary!'),
  ],
  questions: [
    question('Wat is er kapot?', 'De douche is kapot.', 'What is broken?', ['De douche van Bram en Lotte is kapot.']),
    question('Wie belt de loodgieter?', 'Lotte belt de loodgieter.', 'Who phones the plumber?'),
    question('Hoe laat zal de loodgieter komen?', 'De loodgieter zal om tien uur komen.', 'What time will the plumber come?', ['Om tien uur zal de loodgieter komen.', 'De loodgieter komt om tien uur.']),
    question('Wat draagt de loodgieter?', 'De loodgieter draagt een blauwe broek.', 'What is the plumber wearing?'),
    question('Wat heeft de postbode voor Lotte?', 'De postbode heeft een pakket voor Lotte.', 'What does the postman have for Lotte?'),
    question('Is haar tante advocaat?', 'Nee, haar tante is kunstenaar.', 'Is her aunt a lawyer?', ['Nee, haar tante is geen advocaat.']),
    question('Wat doet Bram in de middag?', 'Bram gaat in de middag naar de kapper.', 'What does Bram do in the afternoon?', ['In de middag gaat Bram naar de kapper.', 'Bram gaat naar de kapper.']),
    question('Heeft een loodgieter een goed salaris?', 'Ja, een loodgieter heeft een goed salaris.', 'Does a plumber have a good salary?'),
  ],
};
