import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-markt', after: 'gisteren', volume: 1,
  title: 'Wat heb jij op de markt gekocht?',
  subtitle: 'Twenty fruit and vegetable words. Ask for food, practise plurals and describe what you bought or cooked.',
  image: 'market',
  reviewGrammar: ['perfect-hebben', 'perfect-zijn', 'participle', 'plural', 'modals', 'v2-inversion', 'geen-niet'],
  reminders: [
    'Describe a completed purchase with hebben and gekocht: ik heb een komkommer gekocht; wij hebben twee paprika’s gekocht. Use the other familiar participles to talk about food: gegeten and gekookt. With travel to a destination, use zijn: wij zijn naar de markt gegaan.',
    'A time phrase can come first, but the finite verb stays second: gisteren heb ik champignons gekocht. Questions also move the finite verb: heb jij een citroen gekocht? Ask politely with mag ik: mag ik twee courgettes? After willen, put the infinitive at the end: ik wil een pompoen kopen.',
    'Learn the plural with the word: ui → uien, druif → druiven, aardbei → aardbeien, kers → kersen, perzik → perziken. Paprika takes an apostrophe: paprika’s. Knoflook, broccoli and spinazie are used as uncountable foods here. Say ik koop knoflook and wij eten spinazie, without een.',
  ],
  entries: [
    w('komkommer', 'de', 'cucumber', ['De komkommer is groen.', 'The cucumber is green.'], ['Bram heeft een komkommer gekocht.', 'Bram has bought a cucumber.'], { forms: ['komkommers'] }),
    w('ui', 'de', 'onion', ['Ik koop een ui.', 'I am buying an onion.'], ['Wij hebben twee uien nodig.', 'We need two onions.'], { forms: ['uien'] }),
    w('knoflook', 'de', 'garlic', ['Ik kook met knoflook.', 'I cook with garlic.'], ['Lotte heeft knoflook gekocht.', 'Lotte has bought garlic.']),
    w('paprika', 'de', 'bell pepper', ['De paprika is rood.', 'The bell pepper is red.'], ['Ik heb drie paprika\'s gekocht.', 'I have bought three bell peppers.'], { forms: ["paprika's"] }),
    w('courgette', 'de', 'courgette; zucchini', ['Mag ik twee courgettes?', 'May I have two courgettes?'], ['Bram heeft een courgette gekookt.', 'Bram has cooked a courgette.'], { forms: ['courgettes'] }),
    w('aubergine', 'de', 'aubergine; eggplant', ['De aubergine is paars.', 'The aubergine is purple.'], ['Wij hebben aubergines gegeten.', 'We have eaten aubergines.'], { forms: ['aubergines'] }),
    w('broccoli', 'de', 'broccoli', ['Wij eten broccoli.', 'We eat broccoli.'], ['Lotte heeft broccoli gekookt.', 'Lotte has cooked broccoli.']),
    w('bloemkool', 'de', 'cauliflower', ['Ik koop een bloemkool.', 'I am buying a cauliflower.'], ['De bloemkool kost drie euro.', 'The cauliflower costs three euros.'], { forms: ['bloemkolen'] }),
    w('spinazie', 'de', 'spinach', ['Bram eet graag spinazie.', 'Bram likes eating spinach.'], ['Wij hebben spinazie gegeten.', 'We have eaten spinach.']),
    w('champignon', 'de', 'button mushroom', ['De champignon is klein.', 'The mushroom is small.'], ['Ik heb champignons gekocht.', 'I have bought mushrooms.'], { forms: ['champignons'] }),
    w('druif', 'de', 'grape', ['Ik eet een druif.', 'I am eating a grape.'], ['De druiven zijn lekker.', 'The grapes are tasty.'], { forms: ['druiven'] }),
    w('aardbei', 'de', 'strawberry', ['De aardbei is rood.', 'The strawberry is red.'], ['Lotte heeft aardbeien op de markt gekocht.', 'Lotte has bought strawberries at the market.', ['Op de markt heeft Lotte aardbeien gekocht.']], { forms: ['aardbeien'] }),
    w('citroen', 'de', 'lemon', ['De citroen is geel.', 'The lemon is yellow.'], ['Ik heb twee citroenen nodig.', 'I need two lemons.'], { forms: ['citroenen'] }),
    w('kers', 'de', 'cherry', ['De kers is rood.', 'The cherry is red.'], ['Wij hebben kersen gegeten.', 'We have eaten cherries.'], { forms: ['kersen'] }),
    w('perzik', 'de', 'peach', ['De perzik is lekker.', 'The peach is tasty.'], ['Ik wil vier perziken kopen.', 'I want to buy four peaches.'], { forms: ['perziken'] }),
    w('meloen', 'de', 'melon', ['De meloen is lekker.', 'The melon is tasty.'], ['Bram heeft een kleine meloen gekocht.', 'Bram has bought a small melon.'], { forms: ['meloenen'] }),
    w('watermeloen', 'de', 'watermelon', ['De watermeloen is groot.', 'The watermelon is large.'], ['Wij eten watermeloen in de zomer.', 'We eat watermelon in summer.', ['In de zomer eten wij watermeloen.']], { forms: ['watermeloenen'] }),
    w('pompoen', 'de', 'pumpkin', ['De pompoen is oranje.', 'The pumpkin is orange.'], ['Lotte wil een pompoen kopen.', 'Lotte wants to buy a pumpkin.'], { forms: ['pompoenen'] }),
    w('erwt', 'de', 'pea', ['De erwt is groen.', 'The pea is green.'], ['Wij hebben erwten gekookt.', 'We have cooked peas.'], { forms: ['erwten'] }),
    w('sperzieboon', 'de', 'green bean', ['De sperzieboon is lang.', 'The green bean is long.'], ['Ik eet sperziebonen met rijst.', 'I eat green beans with rice.'], { forms: ['sperziebonen'] }),
  ],
  grammarItems: [
    { nl: 'Bram koopt een komkommer.', task: 'Change the sentence to the perfect tense.', answer: 'Bram heeft een komkommer gekocht.' },
    { nl: 'Wij eten aardbeien.', task: 'Change the sentence to the perfect tense.', answer: 'Wij hebben aardbeien gegeten.' },
    { nl: 'Lotte kookt broccoli.', task: 'Change the sentence to the perfect tense.', answer: 'Lotte heeft broccoli gekookt.' },
    { nl: 'Wij gaan naar de markt.', task: 'Change the sentence to the perfect tense.', answer: 'Wij zijn naar de markt gegaan.' },
    { nl: 'Jij hebt een citroen gekocht.', task: 'Make a yes/no question.', answer: 'Heb jij een citroen gekocht?' },
    { nl: 'Ik heb gisteren champignons gekocht.', task: 'Begin with Gisteren. Keep all the words.', answer: 'Gisteren heb ik champignons gekocht.' },
    { nl: 'Ik heb een bloemkool.', task: 'Make the sentence negative.', answer: 'Ik heb geen bloemkool.' },
    { nl: 'Wij hebben kersen gekocht.', task: 'Make the sentence negative.', answer: 'Wij hebben geen kersen gekocht.' },
    { nl: 'Bram koopt een pompoen.', task: 'Say that Bram wants to do this. Use willen.', answer: 'Bram wil een pompoen kopen.' },
    { nl: 'Ik heb een ui nodig.', task: 'Ask a yes/no question with jij instead of ik.', answer: 'Heb jij een ui nodig?' },
    { nl: 'Wij hebben twee ___.', cue: 'ui', en: 'We have two onions.', answer: 'uien' },
    { nl: 'De ___ zijn lekker.', cue: 'druif', en: 'The grapes are tasty.', answer: 'druiven' },
    { nl: 'Lotte koopt rode ___.', cue: 'aardbei', en: 'Lotte buys red strawberries.', answer: 'aardbeien' },
    { nl: 'Ik wil vier ___ kopen.', cue: 'perzik', en: 'I want to buy four peaches.', answer: 'perziken' },
    { nl: 'Wij eten groene ___.', cue: 'sperzieboon', en: 'We eat green beans.', answer: 'sperziebonen' },
    { nl: 'Bram ___ een meloen gekocht.', cue: 'hebben', en: 'Bram has bought a melon.', answer: 'heeft' },
    { nl: 'Wij ___ naar de markt gegaan.', cue: 'zijn', en: 'We have gone to the market.', answer: 'zijn' },
    { nl: 'Lotte heeft spinazie ___.', cue: 'eten', en: 'Lotte has eaten spinach.', answer: 'gegeten' },
    { nl: 'Ik heb broccoli ___.', cue: 'koken', en: 'I have cooked broccoli.', answer: 'gekookt' },
    { nl: 'Gisteren ___ ik een komkommer gekocht.', cue: 'hebben', en: 'Yesterday I bought a cucumber.', answer: 'heb' },
  ],
  story: [
    line('Zaterdag zijn Bram en Lotte naar de markt gegaan. Zij hebben een grote tas.', 'On Saturday Bram and Lotte went to the market. They have a large bag.'),
    line('Bram heeft een komkommer en drie paprika\'s gekocht. De paprika\'s zijn rood.', 'Bram has bought a cucumber and three bell peppers. The bell peppers are red.'),
    line('Lotte heeft twee uien en een bloemkool gekocht. Zij wil ook spinazie kopen.', 'Lotte has bought two onions and a cauliflower. She also wants to buy spinach.'),
    line('Zij hebben ook aardbeien en druiven gekocht. De aardbeien kosten vier euro.', 'They have also bought strawberries and grapes. The strawberries cost four euros.'),
    line('Bram wil een watermeloen kopen. De watermeloen is groot en zwaar.', 'Bram wants to buy a watermelon. The watermelon is large and heavy.'),
    line('Lotte zegt: onze tas is vol. Wij kopen vandaag geen watermeloen.', 'Lotte says: our bag is full. We are not buying a watermelon today.'),
    line('Thuis kookt Lotte de bloemkool met rijst. Bram eet druiven.', 'At home Lotte cooks the cauliflower with rice. Bram eats grapes.'),
    line('In de avond eten zij de bloemkool en de rijst. De aardbeien zijn voor morgen.', 'In the evening they eat the cauliflower and rice. The strawberries are for tomorrow.'),
  ],
  questions: [
    question('Waar hebben Bram en Lotte de aardbeien gekocht?', 'Bram en Lotte hebben de aardbeien op de markt gekocht.', 'Where have Bram and Lotte bought the strawberries?', ['Op de markt hebben Bram en Lotte de aardbeien gekocht.']),
    question('Hoeveel paprika\'s heeft Bram gekocht?', 'Bram heeft drie paprika\'s gekocht.', 'How many bell peppers has Bram bought?'),
    question('Zijn de paprika\'s groen?', 'Nee, de paprika\'s zijn rood.', 'Are the bell peppers green?', ['Nee, de paprika\'s zijn niet groen.']),
    question('Hoeveel uien heeft Lotte gekocht?', 'Lotte heeft twee uien gekocht.', 'How many onions has Lotte bought?'),
    question('Hoeveel kosten de aardbeien?', 'De aardbeien kosten vier euro.', 'How much do the strawberries cost?'),
    question('Kopen Bram en Lotte een watermeloen?', 'Nee, Bram en Lotte kopen geen watermeloen.', 'Are Bram and Lotte buying a watermelon?'),
    question('Is de tas leeg?', 'Nee, de tas is vol.', 'Is the bag empty?', ['Nee, de tas is niet leeg.']),
    question('Wat kookt Lotte thuis?', 'Lotte kookt de bloemkool met rijst.', 'What does Lotte cook at home?', ['Lotte kookt thuis de bloemkool met rijst.', 'Lotte kookt bloemkool met rijst.']),
  ],
};
