import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-sport', after: 'die-dat', volume: 2,
  title: 'Gent is kampioen!',
  subtitle: 'Twenty sport words. Talk about training, a match and what you can or want to do.',
  image: 'man-swimming',
  reviewGrammar: ['modals', 'infinitive-end', 'perfect-hebben', 'participle', 'comparative', 'want-omdat', 'verb-final', 'v2-inversion'],
  reminders: [
    'After gaan, kunnen, willen and moeten, put the second verb at the end as an infinitive: Lotte gaat elke ochtend hardlopen; Noor kan nog niet schaatsen; Lotte wil leren skiën. Hardlopen is usually used as an infinitive or a participle: wij hebben in het park hardgelopen.',
    'Learn the new verbs with their forms: gooien → ik gooi, hij gooit, gegooid; vangen → ik vang, hij vangt, gevangen; springen → ik spring, hij springt, gesprongen; schaatsen → ik schaats, geschaatst; skiën → ik ski, hij skiet, geskied. Een doelpunt maken means to score a goal.',
    'As with jobs, say Ons team is kampioen without een. Compare with dan: Lotte springt beter dan Bram; goed has the irregular comparative beter. Explain with omdat and put the verb at the end: Bram is moe, omdat hij heeft hardgelopen. Learn het stadion, het veld, het racket, het badpak and het doelpunt as het-words.',
  ],
  entries: [
    w('sportschool', 'de', 'gym; fitness centre', ['Bram gaat naar de sportschool.', 'Bram goes to the gym.'], ['In de sportschool is het druk.', 'It is busy in the gym.', ['Het is druk in de sportschool.']], { forms: ['sportscholen'] }),
    w('training', 'de', 'training session; practice', ['De training begint om zeven uur.', 'The training session starts at seven o’clock.', ['Om zeven uur begint de training.']], ['Na de training is Bram moe.', 'After training Bram is tired.'], { forms: ['trainingen'] }),
    w('trainer', 'de', 'coach; trainer', ['De trainer helpt het team.', 'The coach helps the team.'], ['Onze trainer is streng, maar aardig.', 'Our coach is strict but nice.'], { forms: ['trainers'] }),
    w('hardlopen', null, 'to run (as a sport); to jog', ['Lotte gaat elke ochtend hardlopen.', 'Lotte goes running every morning.', ['Elke ochtend gaat Lotte hardlopen.']], ['Wij hebben in het park hardgelopen.', 'We have been running in the park.'], { forms: ['hardgelopen'] }),
    w('schaatsen', null, 'to skate', ['In de winter schaatsen wij op het ijs.', 'In winter we skate on the ice.', ['Wij schaatsen in de winter op het ijs.']], ['Noor kan nog niet schaatsen.', 'Noor cannot skate yet.'], { forms: ['schaats', 'schaatst', 'geschaatst'] }),
    w('skiën', null, 'to ski', ['Bram skiet in de bergen.', 'Bram skis in the mountains.'], ['Lotte wil leren skiën.', 'Lotte wants to learn to ski.'], { forms: ['ski', 'skiet', 'geskied'] }),
    w('zwembroek', 'de', 'swimming trunks', ['Bram heeft een blauwe zwembroek.', 'Bram has blue swimming trunks.'], ['Ik neem mijn zwembroek mee naar het zwembad.', 'I take my swimming trunks with me to the swimming pool.'], { forms: ['zwembroeken'] }),
    w('badpak', 'het', 'swimsuit', ['Het badpak is rood.', 'The swimsuit is red.'], ['Lotte draagt een badpak in het zwembad.', 'Lotte wears a swimsuit at the swimming pool.'], { forms: ['badpakken'] }),
    w('helm', 'de', 'helmet', ['De helm is wit.', 'The helmet is white.'], ['Ik draag een helm op de fiets.', 'I wear a helmet on my bike.'], { forms: ['helmen'] }),
    w('racket', 'het', 'racket (for tennis)', ['Het racket is nieuw.', 'The racket is new.'], ['Lotte speelt tennis met een nieuw racket.', 'Lotte plays tennis with a new racket.'], { forms: ['rackets'] }),
    w('doelpunt', 'het', 'goal (a score)', ['Het team maakt een doelpunt.', 'The team scores a goal.'], ['Bram heeft twee doelpunten gemaakt.', 'Bram has scored two goals.'], { forms: ['doelpunten'] }),
    w('scheidsrechter', 'de', 'referee', ['De scheidsrechter draagt een zwart shirt.', 'The referee wears a black shirt.'], ['De scheidsrechter geeft een gele kaart.', 'The referee gives a yellow card.'], { forms: ['scheidsrechters'] }),
    w('supporter', 'de', 'fan; supporter', ['De supporters zingen in het stadion.', 'The fans are singing in the stadium.', ['In het stadion zingen de supporters.']], ['Bram is een supporter van Gent.', 'Bram is a Ghent supporter.'], { forms: ['supporters'] }),
    w('stadion', 'het', 'stadium', ['Het stadion is groot.', 'The stadium is large.'], ['Wij gaan zondag naar het stadion.', 'We are going to the stadium on Sunday.', ['Zondag gaan wij naar het stadion.']], { forms: ['stadions'] }),
    w('veld', 'het', 'field; pitch', ['Het veld is groen.', 'The pitch is green.'], ['De spelers lopen over het veld.', 'The players run across the pitch.'], { forms: ['velden'] }),
    w('medaille', 'de', 'medal', ['De medaille is mooi.', 'The medal is beautiful.'], ['Lotte heeft een medaille gewonnen.', 'Lotte has won a medal.'], { forms: ['medailles'] }),
    w('kampioen', 'de', 'champion', ['Ons team is kampioen!', 'Our team is champion!'], ['De kampioen is blij.', 'The champion is happy.'], { forms: ['kampioenen'] }),
    w('gooien', null, 'to throw', ['Bram gooit de bal.', 'Bram throws the ball.'], ['Noor heeft de bal naar Max gegooid.', 'Noor has thrown the ball to Max.'], { forms: ['gooi', 'gooit', 'gegooid'] }),
    w('vangen', null, 'to catch', ['Max vangt de bal.', 'Max catches the ball.'], ['Ik heb de bal niet gevangen.', 'I have not caught the ball.'], { forms: ['vang', 'vangt', 'gevangen'] }),
    w('springen', null, 'to jump', ['Het kind springt in het water.', 'The child jumps into the water.'], ['Lotte springt beter dan Bram.', 'Lotte jumps better than Bram.'], { forms: ['spring', 'springt', 'gesprongen'] }),
  ],
  grammarItems: [
    { nl: 'Ik ga naar de sportschool.', task: 'Say that you have to do this. Use moeten.', answer: 'Ik moet naar de sportschool gaan.' },
    { nl: 'Noor schaatst.', task: 'Say that Noor cannot do this yet. Use kunnen and nog niet.', answer: 'Noor kan nog niet schaatsen.' },
    { nl: 'Lotte skiet.', task: 'Say that Lotte wants to learn this. Begin with Lotte wil leren.', answer: 'Lotte wil leren skiën.' },
    { nl: 'Bram maakt twee doelpunten.', task: 'Change the sentence to the perfect tense.', answer: 'Bram heeft twee doelpunten gemaakt.' },
    { nl: 'Noor gooit de bal naar Max.', task: 'Change the sentence to the perfect tense.', answer: 'Noor heeft de bal naar Max gegooid.' },
    { nl: 'Max vangt de bal.', task: 'Change the sentence to the perfect tense.', answer: 'Max heeft de bal gevangen.' },
    { nl: 'Lotte springt goed.', task: 'Say that Lotte jumps better than Bram.', answer: 'Lotte springt beter dan Bram.' },
    { nl: 'Bram is moe. Hij heeft hardgelopen.', task: 'Join the sentences with omdat. Begin with Bram is moe.', answer: 'Bram is moe, omdat hij heeft hardgelopen.', accept: ['Bram is moe, omdat hij hardgelopen heeft.'] },
    { nl: 'De supporters zingen in het stadion.', task: 'Begin with In het stadion. Keep all the words.', answer: 'In het stadion zingen de supporters.' },
    { nl: 'Het team is kampioen.', task: 'Make a yes/no question.', answer: 'Is het team kampioen?' },
    { nl: 'Bram ___ de bal.', cue: 'gooien', en: 'Bram throws the ball.', answer: 'gooit' },
    { nl: 'Max ___ de bal.', cue: 'vangen', en: 'Max catches the ball.', answer: 'vangt' },
    { nl: 'Ik heb de bal niet ___.', cue: 'vangen', en: 'I have not caught the ball.', answer: 'gevangen' },
    { nl: 'Het kind ___ in het water.', cue: 'springen', en: 'The child jumps into the water.', answer: 'springt' },
    { nl: 'Wij hebben in het park ___.', cue: 'hardlopen', en: 'We have been running in the park.', answer: 'hardgelopen' },
    { nl: 'Bram heeft twee ___ gemaakt.', cue: 'doelpunt', en: 'Bram has scored two goals.', answer: 'doelpunten' },
    { nl: 'De ___ zingen in het stadion.', cue: 'supporter', en: 'The fans are singing in the stadium.', answer: 'supporters' },
    { nl: 'Lotte heeft een medaille ___.', cue: 'winnen', en: 'Lotte has won a medal.', answer: 'gewonnen' },
    { nl: 'Lotte springt ___ dan Bram.', cue: 'goed', en: 'Lotte jumps better than Bram.', answer: 'beter' },
    { nl: 'Ons team is ___!', en: 'Our team is champion!', answer: 'kampioen' },
  ],
  story: [
    line('Op zondag gaan Bram en Jonas naar het stadion in Gent.', 'On Sunday Bram and Jonas go to the stadium in Ghent.'),
    line('Het stadion is vol. De supporters zingen en dragen blauw.', 'The stadium is full. The fans are singing and wearing blue.'),
    line('De spelers lopen over het veld. De scheidsrechter draagt een zwart shirt.', 'The players run across the pitch. The referee is wearing a black shirt.'),
    line('Na tien minuten maakt Gent een doelpunt. Bram springt en lacht.', 'After ten minutes Ghent scores a goal. Bram jumps and laughs.'),
    line('Gent wint de wedstrijd en is kampioen!', 'Ghent wins the match and is champion!'),
    line('In de ochtend gaat Lotte hardlopen in het park.', 'In the morning Lotte goes running in the park.'),
    line('Na de training is zij moe, maar blij.', 'After training she is tired but happy.'),
    line('In de avond vertelt Bram over de wedstrijd. Lotte zegt: volgende week ga ik mee naar het stadion!', 'In the evening Bram talks about the match. Lotte says: next week I am coming to the stadium too!'),
  ],
  questions: [
    question('Gaan Bram en Jonas op zondag naar het stadion?', 'Ja, Bram en Jonas gaan op zondag naar het stadion.', 'Do Bram and Jonas go to the stadium on Sunday?', ['Ja, op zondag gaan Bram en Jonas naar het stadion.']),
    question('Is het stadion leeg?', 'Nee, het stadion is vol.', 'Is the stadium empty?', ['Nee, het stadion is niet leeg.']),
    question('Dragen de supporters blauw?', 'Ja, de supporters dragen blauw.', 'Are the fans wearing blue?'),
    question('Wat draagt de scheidsrechter?', 'De scheidsrechter draagt een zwart shirt.', 'What is the referee wearing?'),
    question('Wanneer maakt Gent een doelpunt?', 'Gent maakt na tien minuten een doelpunt.', 'When does Ghent score a goal?', ['Na tien minuten maakt Gent een doelpunt.']),
    question('Is Gent kampioen?', 'Ja, Gent is kampioen.', 'Is Ghent champion?'),
    question('Waar gaat Lotte hardlopen?', 'Lotte gaat in het park hardlopen.', 'Where does Lotte go running?', ['Lotte gaat hardlopen in het park.', 'In de ochtend gaat Lotte hardlopen in het park.']),
    question('Is Lotte na de training moe?', 'Ja, Lotte is na de training moe.', 'Is Lotte tired after training?', ['Ja, na de training is Lotte moe.', 'Ja, Lotte is moe.', 'Ja, Lotte is moe, maar blij.']),
  ],
};
