import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-familie-feest', after: 'gisteren', volume: 1,
  title: 'Een feest met de familie',
  subtitle: 'Twenty words for relatives, guests and celebrations. Practise possessives, questions and the perfect tense.',
  image: 'birthday',
  reviewGrammar: ['possessives', 'perfect-hebben', 'perfect-zijn', 'participle', 'v2-inversion', 'plural', 'adjective-e', 'question-word'],
  reminders: [
    'Learn family words with their articles: het gezin, de baby, de oom, de tante. Gezin usually means parents and their children; familie can include more relatives. Neef can mean a male cousin or a nephew; nicht can mean a female cousin or a niece. In this lesson, the English cues use cousin. Use mijn, jouw, zijn or haar without an extra article: mijn tante, haar neef.',
    'Keep time, subject and verb in order: vandaag is mijn verjaardag; mijn verjaardag is in oktober. Use in with a month, op with a day and om with a time. For completed actions, use the familiar perfect tense: ik heb een cadeau gekocht; wij zijn naar het feest gegaan. Ask with the helper first: heeft jouw tante een taart gemaakt?',
  ],
  entries: [
    w('gezin', 'het', 'family; parents and their children', ['Ons gezin woont in Leuven.', 'Our family lives in Leuven.'], ['Het gezin heeft een klein huis.', 'The family has a small house.'], { forms: ['gezinnen'] }),
    w('baby', 'de', 'baby', ['De baby slaapt in bed.', 'The baby is sleeping in bed.', ['De baby slaapt in het bed.']], ['Mijn zus heeft een baby.', 'My sister has a baby.']),
    w('oom', 'de', 'uncle', ['Mijn oom woont in Gent.', 'My uncle lives in Ghent.'], ['Ik heb met mijn oom gepraat.', 'I have talked to my uncle.'], { forms: ['ooms'] }),
    w('tante', 'de', 'aunt', ['Mijn tante komt op zondag.', 'My aunt is coming on Sunday.', ['Op zondag komt mijn tante.']], ['Mijn tante heeft een taart gemaakt.', 'My aunt has made a cake.'], { forms: ['tantes'] }),
    w('neef', 'de', 'cousin (male)', ['Mijn neef is zes jaar.', 'My male cousin is six years old.', ['Mijn neef is zes jaar oud.']], ['Ik speel met mijn neef.', 'I play with my male cousin.'], { forms: ['neven'] }),
    w('nicht', 'de', 'cousin (female)', ['Mijn nicht spreekt Nederlands.', 'My female cousin speaks Dutch.'], ['Mijn nicht heeft een boek gelezen.', 'My female cousin has read a book.'], { forms: ['nichten'] }),
    w('oma', 'de', 'grandma', ['Mijn oma woont in Gent.', 'My grandma lives in Ghent.'], ['Ik ga op zondag naar mijn oma.', 'I go to my grandma on Sunday.', ['Op zondag ga ik naar mijn oma.']]),
    w('opa', 'de', 'grandpa', ['Mijn opa leest de krant.', 'My grandpa is reading the newspaper.'], ['Mijn opa heeft in de tuin gewerkt.', 'My grandpa has worked in the garden.']),
    w('cadeau', 'het', 'present; gift', ['Ik heb een cadeau gekocht.', 'I have bought a present.'], ['Het cadeau is een boek.', 'The present is a book.'], { forms: ['cadeaus'] }),
    w('verjaardag', 'de', 'birthday', ['Vandaag is mijn verjaardag.', 'Today is my birthday.', ['Mijn verjaardag is vandaag.']], ['Mijn verjaardag is in oktober.', 'My birthday is in October.', ['In oktober is mijn verjaardag.']], { forms: ['verjaardagen'] }),
    w('feest', 'het', 'party; celebration', ['Het feest begint om drie uur.', 'The party starts at three o’clock.', ['Om drie uur begint het feest.']], ['Wij zijn naar het feest gegaan.', 'We have gone to the party.'], { forms: ['feesten'] }),
    w('gast', 'de', 'guest', ['De gast drinkt een glas water.', 'The guest is drinking a glass of water.'], ['Er zijn tien gasten op het feest.', 'There are ten guests at the party.', ['Op het feest zijn er tien gasten.']], { forms: ['gasten'] }),
    w('taart', 'de', 'cake; tart', ['Mijn tante heeft een taart gemaakt.', 'My aunt has made a cake.'], ['De taart staat op tafel.', 'The cake is on the table.', ['De taart staat op de tafel.', 'De taart is op de tafel.']], { forms: ['taarten'] }),
    w('kaars', 'de', 'candle', ['De kaars staat op tafel.', 'The candle is on the table.', ['De kaars staat op de tafel.', 'De kaars is op de tafel.']], ['Er zijn zes kaarsen op de taart.', 'There are six candles on the cake.', ['Op de taart zijn er zes kaarsen.', 'Er staan zes kaarsen op de taart.']], { forms: ['kaarsen'] }),
    w('ballon', 'de', 'balloon', ['De ballon is rood.', 'The balloon is red.'], ['Ik heb drie ballonnen gekocht.', 'I have bought three balloons.'], { forms: ['ballonnen'] }),
    w('slinger', 'de', 'party garland', ['De slinger is groen en geel.', 'The party garland is green and yellow.'], ['Wij hebben slingers gemaakt.', 'We have made party garlands.'], { forms: ['slingers'] }),
    w('boeket', 'het', 'bouquet', ['Ik koop een boeket.', 'I am buying a bouquet.'], ['Het boeket is mooi.', 'The bouquet is beautiful.'], { forms: ['boeketten'] }),
    w('uitnodiging', 'de', 'invitation', ['Ik schrijf een uitnodiging.', 'I am writing an invitation.'], ['Op de uitnodiging staat mijn adres.', 'My address is on the invitation.', ['Mijn adres staat op de uitnodiging.', 'Mijn adres is op de uitnodiging.']], { forms: ['uitnodigingen'] }),
    w('bruiloft', 'de', 'wedding celebration', ['Wij gaan naar een bruiloft.', 'We are going to a wedding celebration.'], ['De bruiloft is op zaterdag.', 'The wedding celebration is on Saturday.', ['Op zaterdag is de bruiloft.']], { forms: ['bruiloften'] }),
    w('bruid', 'de', 'bride', ['De bruid draagt een witte jurk.', 'The bride is wearing a white dress.'], ['De bruid heeft een boeket.', 'The bride has a bouquet.'], { forms: ['bruiden'] }),
  ],
  grammarItems: [
    { nl: 'Mijn tante maakt een taart.', task: 'Rewrite in the perfect tense. Keep the same subject.', answer: 'Mijn tante heeft een taart gemaakt.' },
    { nl: 'Wij gaan naar het feest.', task: 'Rewrite in the perfect tense. Keep the same subject.', answer: 'Wij zijn naar het feest gegaan.' },
    { nl: 'Jij hebt een cadeau gekocht.', task: 'Make a yes/no question.', answer: 'Heb jij een cadeau gekocht?' },
    { nl: 'Mijn oom heeft in de tuin gewerkt.', task: 'Make a yes/no question.', answer: 'Heeft mijn oom in de tuin gewerkt?' },
    { nl: 'Ik koop een boeket.', task: 'Add Vandaag at the beginning. Keep the present tense.', answer: 'Vandaag koop ik een boeket.' },
    { nl: 'Het feest begint om drie uur.', task: 'Begin with Om drie uur. Keep all the other words.', answer: 'Om drie uur begint het feest.' },
    { nl: 'Er is één gast in de tuin.', task: 'Replace één with tien and make the necessary plural changes.', answer: 'Er zijn tien gasten in de tuin.' },
    { nl: 'Ik heb een cadeau.', task: 'Make the sentence negative using geen.', answer: 'Ik heb geen cadeau.' },
    { nl: 'De jurk is wit.', task: 'Describe the dress in a sentence beginning De bruid draagt een. Put wit before jurk.', answer: 'De bruid draagt een witte jurk.' },
    { nl: 'Mijn verjaardag is in oktober.', task: 'Begin with In oktober. Keep all the other words.', answer: 'In oktober is mijn verjaardag.' },
    { nl: 'Mijn tante ___ een taart gemaakt.', cue: 'hebben', answer: 'heeft', en: 'My aunt has made a cake.' },
    { nl: 'Mijn neef ___ naar het feest gegaan.', cue: 'zijn', answer: 'is', en: 'My male cousin has gone to the party.' },
    { nl: '___ jij met jouw oom gepraat?', cue: 'hebben', answer: 'Heb', en: 'Have you talked to your uncle?' },
    { nl: 'Ik heb een cadeau ___.', cue: 'kopen', answer: 'gekocht', en: 'I have bought a present.' },
    { nl: 'Mijn nicht heeft het boek ___.', cue: 'lezen', answer: 'gelezen', en: 'My female cousin has read the book.' },
    { nl: 'Wij zijn naar de bruiloft ___.', cue: 'gaan', answer: 'gegaan', en: 'We have gone to the wedding celebration.' },
    { nl: 'Er zijn vijf ___ in de tuin.', cue: 'gast', answer: 'gasten', en: 'There are five guests in the garden.' },
    { nl: 'Op de taart staan zes ___.', cue: 'kaars', answer: 'kaarsen', en: 'There are six candles on the cake.' },
    { nl: '___ gezin woont in Leuven.', answer: 'Ons', en: 'Our family lives in Leuven.' },
    { nl: 'Mijn tante heeft een ___ jurk.', cue: 'mooi', answer: 'mooie', en: 'My aunt has a beautiful dress.' },
  ],
  story: [
    line('Vandaag is er een feest in Gent. Lotte is naar haar tante gegaan.', 'Today there is a party in Ghent. Lotte has gone to her aunt.'),
    line('Haar neef is zes jaar. Het is zijn verjaardag.', 'Her male cousin is six years old. It is his birthday.'),
    line('Haar tante heeft een taart gemaakt. Er zijn zes kaarsen op de taart.', 'Her aunt has made a cake. There are six candles on the cake.'),
    line('Haar oom heeft rode ballonnen gekocht. De slingers zijn blauw.', 'Her uncle has bought red balloons. The party garlands are blue.'),
    line('Oma en opa zitten in de tuin. Lotte praat met haar nicht.', 'Grandma and grandpa are sitting in the garden. Lotte talks to her female cousin.'),
    line('De gasten eten taart. Lotte drinkt thee en haar oom drinkt koffie.', 'The guests eat cake. Lotte drinks tea and her uncle drinks coffee.'),
    line('Lotte heeft een cadeau gekocht. Het cadeau is een boek.', 'Lotte has bought a present. The present is a book.'),
    line('Haar neef leest het boek. Het gezin is blij.', 'Her male cousin reads the book. The family is happy.'),
  ],
  questions: [
    question('Waar is het feest?', 'Het feest is in Gent.', 'Where is the party?', ['In Gent is het feest.']),
    question('Hoe oud is haar neef?', 'Haar neef is zes jaar.', 'How old is her male cousin?', ['Haar neef is zes jaar oud.']),
    question('Heeft haar tante een taart gemaakt?', 'Ja, haar tante heeft een taart gemaakt.', 'Has her aunt made a cake?'),
    question('Hoeveel kaarsen zijn er op de taart?', 'Er zijn zes kaarsen op de taart.', 'How many candles are there on the cake?', ['Op de taart zijn er zes kaarsen.', 'Er staan zes kaarsen op de taart.', 'Op de taart staan zes kaarsen.']),
    question('Zijn de ballonnen blauw?', 'Nee, de ballonnen zijn rood.', 'Are the balloons blue?', ['Nee, de ballonnen zijn niet blauw.']),
    question('Waar zitten oma en opa?', 'Oma en opa zitten in de tuin.', 'Where are grandma and grandpa sitting?', ['Opa en oma zitten in de tuin.', 'In de tuin zitten oma en opa.', 'In de tuin zitten opa en oma.']),
    question('Wat drinkt Lotte?', 'Lotte drinkt thee.', 'What does Lotte drink?'),
    question('Wat is het cadeau?', 'Het cadeau is een boek.', 'What is the present?'),
  ],
};
