import { entry as w, line, question } from './entry.js';

export default {
  id: 'a2-onweer', after: 'die-dat', volume: 2,
  title: 'Morgen komt er onweer',
  subtitle: 'Twenty weather words. Read a forecast, compare temperatures and say what you do when it rains or freezes.',
  image: 'rain',
  reviewGrammar: ['zullen-future', 'als-inversion', 'comparative', 'adjective-e', 'dat-clause', 'perfect-hebben', 'er-is-zijn'],
  reminders: [
    'Weather verbs use het as their subject: het regent, het vriest, het waait. Vriezen and waaien take hebben in the perfect tense: het heeft gevroren; het heeft hard gewaaid. Use zullen for a forecast: morgen zal het vriezen. Hard with waaien means strongly: het waait hard.',
    'An als-clause that comes first takes the first place in the sentence, so the main verb follows straight after the comma: als het regent, draag ik een regenjas; als het vriest, draagt Noor een muts. A report with dat sends the verb to the end: het weerbericht zegt dat er morgen onweer komt.',
    'Before a noun, add -e: een zonnige dag, een bewolkte dag. Unlike euro and gram, graad takes its plural after a number: het is twintig graden. Say aan de hemel for things you see in the sky: er zijn veel sterren aan de hemel.',
  ],
  entries: [
    w('onweer', 'het', 'thunderstorm', ['Er is onweer.', 'There is a thunderstorm.'], ['Bij onweer blijven wij binnen.', 'During a thunderstorm we stay inside.', ['Wij blijven binnen bij onweer.']]),
    w('bliksem', 'de', 'lightning', ['Ik zie de bliksem.', 'I see the lightning.'], ['Gisteren zag Bram de bliksem boven de stad.', 'Yesterday Bram saw the lightning above the city.', ['Bram zag gisteren de bliksem boven de stad.']]),
    w('donder', 'de', 'thunder', ['De hond is bang voor de donder.', 'The dog is afraid of the thunder.'], ['Na de bliksem komt de donder.', 'After the lightning comes the thunder.']),
    w('hagel', 'de', 'hail', ['De hagel is wit.', 'The hail is white.'], ['In april is er vaak hagel.', 'In April there is often hail.', ['Er is vaak hagel in april.']]),
    w('regenboog', 'de', 'rainbow', ['De regenboog is mooi.', 'The rainbow is beautiful.'], ['Na de regen zien wij een regenboog.', 'After the rain we see a rainbow.'], { forms: ['regenbogen'] }),
    w('plas', 'de', 'puddle', ['Er is een grote plas op straat.', 'There is a big puddle in the street.', ['Op straat is er een grote plas.']], ['Het kind speelt in de plassen.', 'The child is playing in the puddles.'], { forms: ['plassen'] }),
    w('druppel', 'de', 'drop (of water)', ['Er is een druppel op het raam.', 'There is a drop on the window.'], ['Ik voel een druppel.', 'I feel a drop.'], { forms: ['druppels'] }),
    w('hemel', 'de', 'sky', ['De hemel is blauw.', 'The sky is blue.'], ['In de nacht is de hemel donker.', 'At night the sky is dark.']),
    w('ster', 'de', 'star', ['Er is één ster aan de hemel.', 'There is one star in the sky.'], ['In de winter zien wij veel sterren.', 'In winter we see many stars.', ['Wij zien veel sterren in de winter.']], { forms: ['sterren'] }),
    w('maan', 'de', 'moon', ['De maan schijnt.', 'The moon is shining.'], ['In de nacht zie ik de maan en de sterren.', 'At night I see the moon and the stars.']),
    w('weerbericht', 'het', 'weather forecast', ['Ik kijk naar het weerbericht.', 'I am watching the weather forecast.'], ['Het weerbericht zegt dat het morgen zal regenen.', 'The weather forecast says that it will rain tomorrow.', ['Het weerbericht zegt dat het morgen regenen zal.']], { forms: ['weerberichten'] }),
    w('graad', 'de', 'degree (of temperature)', ['Het is twintig graden.', 'It is twenty degrees.'], ['Vandaag is het tien graden kouder dan gisteren.', 'Today it is ten degrees colder than yesterday.'], { forms: ['graden'] }),
    w('hitte', 'de', 'heat', ['De hitte is zwaar voor de oude man.', 'The heat is hard for the old man.'], ['In de hitte drinken wij veel water.', 'In the heat we drink a lot of water.', ['Wij drinken veel water in de hitte.']]),
    w('vorst', 'de', 'frost', ['Er is vorst.', 'There is frost.'], ['Na de vorst is het gras wit.', 'After the frost the grass is white.']),
    w('zonnig', null, 'sunny', ['Het is zonnig.', 'It is sunny.'], ['Morgen is een zonnige dag.', 'Tomorrow is a sunny day.'], { forms: ['zonnige'] }),
    w('bewolkt', null, 'cloudy', ['Het is bewolkt.', 'It is cloudy.'], ['Het is een bewolkte dag.', 'It is a cloudy day.'], { forms: ['bewolkte'] }),
    w('vriezen', null, 'to freeze (het vriest: it is freezing)', ['Het vriest.', 'It is freezing.'], ['Morgen zal het vriezen.', 'Tomorrow it will freeze.'], { forms: ['vriest', 'gevroren'] }),
    w('waaien', null, 'to blow (het waait: it is windy)', ['Het waait hard.', 'It is very windy.'], ['Gisteren heeft het hard gewaaid.', 'Yesterday it was very windy.', ['Het heeft gisteren hard gewaaid.']], { forms: ['waait', 'gewaaid'] }),
    w('regenjas', 'de', 'raincoat', ['Mijn regenjas is geel.', 'My raincoat is yellow.'], ['Als het regent, draag ik een regenjas.', 'If it rains, I wear a raincoat.'], { forms: ['regenjassen'] }),
    w('muts', 'de', 'woolly hat; beanie', ['De muts is warm.', 'The woolly hat is warm.'], ['Als het vriest, draagt Noor een muts.', 'When it freezes, Noor wears a woolly hat.'], { forms: ['mutsen'] }),
  ],
  grammarItems: [
    { nl: 'Het vriest.', task: 'Use zullen to say what will happen. Begin with Morgen.', answer: 'Morgen zal het vriezen.' },
    { nl: 'Het waait hard.', task: 'Change the sentence to the perfect tense. Begin with Gisteren.', answer: 'Gisteren heeft het hard gewaaid.' },
    { nl: 'Ik draag een regenjas, als het regent.', task: 'Begin with Als het regent. Keep all the words.', answer: 'Als het regent, draag ik een regenjas.' },
    { nl: 'Noor draagt een muts, als het vriest.', task: 'Begin with Als het vriest. Keep all the words.', answer: 'Als het vriest, draagt Noor een muts.' },
    { nl: 'De dag is zonnig.', task: 'Describe the day in a sentence beginning Het is een. Put zonnig before dag.', answer: 'Het is een zonnige dag.' },
    { nl: 'Vandaag is het koud.', task: 'Say that today it is colder than yesterday.', answer: 'Vandaag is het kouder dan gisteren.' },
    { nl: 'Het weerbericht zegt: het zal morgen regenen.', task: 'Report it with dat. Begin with Het weerbericht zegt dat.', answer: 'Het weerbericht zegt dat het morgen zal regenen.', accept: ['Het weerbericht zegt dat het morgen regenen zal.'] },
    { nl: 'De hond is bang voor de donder.', task: 'Make a yes/no question.', answer: 'Is de hond bang voor de donder?' },
    { nl: 'Er is een plas op straat.', task: 'Replace een with drie and make the necessary plural changes.', answer: 'Er zijn drie plassen op straat.' },
    { nl: 'Er is vorst.', task: 'Make the sentence negative.', answer: 'Er is geen vorst.' },
    { nl: 'Morgen ___ het vriezen.', cue: 'zullen', en: 'Tomorrow it will freeze.', answer: 'zal' },
    { nl: 'Het ___ hard.', cue: 'waaien', en: 'It is very windy.', answer: 'waait' },
    { nl: 'Gisteren heeft het hard ___.', cue: 'waaien', en: 'Yesterday it was very windy.', answer: 'gewaaid' },
    { nl: 'Het is vijf ___.', cue: 'graad', en: 'It is five degrees.', answer: 'graden' },
    { nl: 'Er zijn veel ___ aan de hemel.', cue: 'ster', en: 'There are many stars in the sky.', answer: 'sterren' },
    { nl: 'Het kind speelt in de ___.', cue: 'plas', en: 'The child is playing in the puddles.', answer: 'plassen' },
    { nl: 'Het is een ___ dag.', cue: 'bewolkt', en: 'It is a cloudy day.', answer: 'bewolkte' },
    { nl: 'Als het vriest, ___ ik een muts.', cue: 'dragen', en: 'When it freezes, I wear a woolly hat.', answer: 'draag' },
    { nl: 'Vandaag is het ___ dan gisteren.', cue: 'warm', en: 'Today it is warmer than yesterday.', answer: 'warmer' },
    { nl: 'Het weerbericht zegt ___ het morgen zonnig is.', en: 'The weather forecast says that it is sunny tomorrow.', answer: 'dat' },
  ],
  story: [
    line('Bram kijkt naar het weerbericht. Het weerbericht zegt dat er morgen onweer komt.', 'Bram watches the weather forecast. The forecast says that a thunderstorm is coming tomorrow.'),
    line('In de ochtend is het zonnig en twintig graden.', 'In the morning it is sunny and twenty degrees.'),
    line('In de middag is het bewolkt. Het waait hard.', 'In the afternoon it is cloudy. It is very windy.'),
    line('Dan komt het onweer. Lotte ziet de bliksem en Max is bang voor de donder.', 'Then the thunderstorm comes. Lotte sees the lightning and Max is afraid of the thunder.'),
    line('Er is ook hagel. Bram en Lotte blijven binnen.', 'There is hail too. Bram and Lotte stay inside.'),
    line('Na het onweer zijn er grote plassen in de straat. Noor speelt in de plassen met haar regenjas.', 'After the thunderstorm there are big puddles in the street. Noor plays in the puddles in her raincoat.'),
    line('Lotte kijkt naar de hemel en ziet een regenboog.', 'Lotte looks at the sky and sees a rainbow.'),
    line('In de avond is de hemel donker. Bram en Lotte zien de maan en de sterren.', 'In the evening the sky is dark. Bram and Lotte see the moon and the stars.'),
  ],
  questions: [
    question('Wat zegt het weerbericht?', 'Het weerbericht zegt dat er morgen onweer komt.', 'What does the weather forecast say?'),
    question('Hoeveel graden is het in de ochtend?', 'Het is twintig graden in de ochtend.', 'How many degrees is it in the morning?', ['In de ochtend is het twintig graden.']),
    question('Waait het hard in de middag?', 'Ja, het waait hard in de middag.', 'Is it very windy in the afternoon?', ['Ja, in de middag waait het hard.']),
    question('Wie is bang voor de donder?', 'Max is bang voor de donder.', 'Who is afraid of the thunder?'),
    question('Blijven Bram en Lotte binnen?', 'Ja, Bram en Lotte blijven binnen.', 'Do Bram and Lotte stay inside?'),
    question('Waar speelt Noor?', 'Noor speelt in de plassen.', 'Where does Noor play?', ['Noor speelt in de plassen met haar regenjas.', 'Noor speelt in de plassen in de straat.']),
    question('Wat ziet Lotte?', 'Lotte ziet een regenboog.', 'What does Lotte see?', ['Lotte ziet een regenboog aan de hemel.']),
    question('Wat zien Bram en Lotte in de avond?', 'Bram en Lotte zien de maan en de sterren.', 'What do Bram and Lotte see in the evening?', ['In de avond zien Bram en Lotte de maan en de sterren.']),
  ],
};
