/** Reviewed sprite sheets: each cell is one vocabulary illustration, in reading order. */
const sheets = [
  { file: 'sport.svg', aspect: 1600 / 1500, entries: [
    ['sportschool', 'Bram with a sports bag in a gym with dumbbells and an exercise bike'], ['training', 'a training session: cones and a ball on a pitch with a clock showing seven'],
    ['trainer', 'a coach in a tracksuit and cap with a whistle and a clipboard'], ['hardlopen', 'Lotte running in sports clothes in the park'],
    ['schaatsen', 'a pair of ice skates on a frozen pond'], ['skiën', 'Bram skiing down a snowy slope between mountains'],
    ['zwembroek', 'a pair of blue swimming trunks'], ['badpak', 'a red one-piece swimsuit'],
    ['helm', 'a white bicycle helmet with air vents'], ['racket', 'a tennis racket with a yellow tennis ball'],
    ['doelpunt', 'a football flying into the net of a goal'], ['scheidsrechter', 'a referee in a black shirt with a whistle holding up a yellow card'],
    ['supporter', 'three cheering fans with blue scarves in the stands'], ['stadion', 'a large football stadium with full stands around a green pitch'],
    ['veld', 'a green football pitch with white lines'], ['medaille', 'a shiny gold medal on a blue ribbon'],
    ['kampioen', 'a winners’ trophy cup with confetti around it'], ['gooien', 'Bram throwing a ball high into the air'],
    ['vangen', 'Max the dog jumping to catch a ball in his mouth'], ['springen', 'Noor jumping into the water of a swimming pool with a splash'],
  ] },
  { file: 'weather.svg', aspect: 1600 / 1500, entries: [
    ['onweer', 'a thunderstorm: a dark cloud with lightning and heavy rain over a house'], ['bliksem', 'a bright bolt of lightning striking down from a cloud'],
    ['donder', 'Max the dog cowering under a dark cloud that booms with thunder'], ['hagel', 'white hailstones falling from a grey cloud and lying on the ground'],
    ['regenboog', 'a rainbow over green hills after the rain'], ['plas', 'a large puddle on the street with rain drops making rings in it'],
    ['druppel', 'one big drop of water running down a window pane'], ['hemel', 'a wide blue sky with a few white clouds above a low landscape'],
    ['ster', 'a dark night sky with one bright star'], ['maan', 'a full moon shining over dark hills at night'],
    ['weerbericht', 'a television showing a weather forecast map with sun and rain symbols'], ['graad', 'a thermometer showing twenty degrees beside the sun'],
    ['hitte', 'the old man sweating under a blazing sun with heat waves'], ['vorst', 'white frost on blades of grass and a leaf, with ice crystals'],
    ['zonnig', 'a bright sun shining over a green landscape'], ['bewolkt', 'a sky full of grey clouds'],
    ['vriezen', 'icicles hanging from a roof and a thermometer below zero'], ['waaien', 'a tree bending in a strong wind with leaves blowing away'],
    ['regenjas', 'a yellow hooded raincoat'], ['muts', 'a warm knitted woolly hat with a bobble on top'],
  ] },
  { file: 'garden.svg', aspect: 1600 / 1500, entries: [
    ['blad', 'a single green leaf with its veins'], ['tak', 'a bird sitting on a branch, the branch highlighted'],
    ['struik', 'a round green bush'], ['heg', 'a tall neatly trimmed green hedge'],
    ['zaad', 'a few small seeds on an open hand next to a seed packet'], ['onkruid', 'weeds and dandelions growing between garden tiles'],
    ['roos', 'one red rose with leaves on its stem'], ['tulp', 'one yellow tulip'],
    ['zonnebloem', 'a tall yellow sunflower'], ['appelboom', 'an apple tree with red apples behind a house'],
    ['gazon', 'a green lawn with mown stripes in front of a low fence'], ['grasmaaier', 'a red push lawnmower on the grass'],
    ['hark', 'a garden rake with a long wooden handle'], ['gieter', 'a green watering can full of water'],
    ['schep', 'a spade stuck into a heap of soil'], ['tuinslang', 'a coiled green garden hose spraying water'],
    ['bloempot', 'a terracotta flowerpot with pink flowers on a balcony railing'], ['maaien', 'Bram pushing a lawnmower across the lawn'],
    ['plukken', 'Noor reaching up to pick a red apple from a branch'], ['groeien', 'three tulips in a row, each one taller, with an arrow showing them growing'],
  ] },
  { file: 'care.svg', aspect: 1600 / 1500, entries: [
    ['vinger', 'an open hand showing its five fingers'], ['teen', 'two bare feet seen from above with the toes highlighted'],
    ['nagel', 'a hand with short, neatly cut nails highlighted'], ['lip', 'a close-up of a mouth with dry, slightly cracked lips'],
    ['wang', 'a child’s face with rosy red cheeks highlighted'], ['nek', 'a man rubbing the back of his sore neck, which is highlighted'],
    ['elleboog', 'a bent arm in a short sleeve with the elbow highlighted'], ['pols', 'a wrist with a watch around it, the wrist highlighted'],
    ['huid', 'a smiling baby with soft skin and a few sparkles'], ['tandenborstel', 'a blue toothbrush with a little toothpaste on the bristles'],
    ['tandpasta', 'a tube of toothpaste standing in a cup on the edge of a washbasin'], ['kam', 'a plain comb with long teeth'],
    ['borstel', 'a hairbrush with a wooden handle and soft bristles'], ['scheren', 'Bram shaving, with white foam on his cheeks and a razor in his hand'],
    ['scheermes', 'a razor with a blue handle'], ['deodorant', 'a deodorant spray can giving a small puff of spray'],
    ['wastafel', 'a white washbasin with a tap and a mirror above it'], ['washandje', 'a wet washcloth mitt with drops of water'],
    ['badjas', 'a soft white bathrobe hanging on a hook'], ['parfum', 'an elegant perfume bottle with an expensive price tag'],
  ] },
  { file: 'cooking.svg', aspect: 1600 / 1500, entries: [
    ['bakken', 'Lotte beside an oven with a cake baking inside'], ['schillen', 'a knife peeling a green apple, a long strip of peel curling down'],
    ['roeren', 'a spoon stirring soup in a pot on the stove, with a circular arrow and steam'], ['mengen', 'a whisk mixing flour and milk in a bowl, next to a flour bag and a milk carton'],
    ['raspen', 'a piece of cheese being grated on a grater, with shreds falling'], ['meel', 'a bag of white flour with a wheat ear on it and a little spilled flour'],
    ['deeg', 'a soft ball of dough on a floured board with a rolling pin'], ['room', 'an open fridge with a carton of cream highlighted on a shelf'],
    ['honing', 'a jar of golden honey with a wooden dipper, honey dripping'], ['jam', 'a jar of red jam with a spoon beside it'],
    ['mosterd', 'a pot of yellow mustard with a small spoon'], ['chocolade', 'a brown chocolate bar partly unwrapped with two broken pieces'],
    ['koekje', 'a plate of small round biscuits'], ['pannenkoek', 'a stack of warm pancakes on a plate with steam rising'],
    ['boterham', 'a slice of bread with cheese on a plate'], ['ingrediënt', 'baking ingredients on a table: flour, milk, an egg, butter and sugar'],
    ['gram', 'a piece of cheese on a kitchen scale whose dial points to one hundred'], ['liter', 'a one-litre measuring jug filled with milk to the top line'],
    ['snijplank', 'a wooden chopping board with a knife and a sliced tomato on it'], ['waterkoker', 'an electric kettle on its base with steam coming out of the spout'],
  ] },
  { file: 'character.svg', aspect: 1600 / 1500, entries: [
    ['karakter', 'Max the big dog with a small red heart above his head'], ['vrolijk', 'Noor laughing happily with sparkles around her'],
    ['verdrietig', 'a sad child with a tear on her cheek'], ['jaloers', 'Max the dog sulking under a dark scribble while Lotte cuddles her cat'],
    ['verlegen', 'a shy blushing child half hidden behind a door, looking down'], ['aardig', 'the kind old neighbour smiling and offering a plate of biscuits'],
    ['grappig', 'Jonas pulling a funny face, winking with his tongue out'], ['slim', 'Lotte with a book and a light bulb above her head'],
    ['dom', 'a man slapping his forehead and thinking of the key he has forgotten'], ['lui', 'a cat sleeping lazily on a cushion'],
    ['geduldig', 'a calm teacher with a book and an hourglass, waiting patiently'], ['nieuwsgierig', 'a curious cat peeking into an open cardboard box'],
    ['teleurgesteld', 'Lotte standing disappointed in front of a closed shop with a small grey cloud above her'], ['verbaasd', 'Bram surprised with raised eyebrows and an open mouth, holding a present'],
    ['bezorgd', 'a worried mother with her hand at her chin and a clock showing it is late'], ['eenzaam', 'the old man sitting alone on a long bench with autumn leaves falling'],
    ['beleefd', 'a polite child holding out a flower and saying please'], ['streng', 'a strict father frowning and raising his index finger'],
    ['eerlijk', 'an honest man handing a lost wallet back to a woman'], ['glimlachen', 'Lotte smiling warmly'],
  ] },
  { file: 'jobs.svg', aspect: 1600 / 1500, entries: [
    ['kok', 'a cook in a white jacket, apron and tall chef’s hat holding a steaming pan'], ['kapper', 'a hairdresser with scissors and a comb beside a client in a salon chair'],
    ['schilder', 'a painter in white overalls on a stepladder painting a wall with a roller'], ['loodgieter', 'a plumber in blue overalls with a pipe wrench beside a washbasin and its pipe'],
    ['elektricien', 'an electrician with a yellow helmet and tool belt working on a wall socket'], ['politieagent', 'a police officer in a dark blue uniform and cap raising a hand at a crossroads'],
    ['brandweerman', 'a firefighter in a red helmet and striped jacket holding a spraying hose'], ['piloot', 'a pilot in a dark uniform and cap with an aeroplane in the sky behind'],
    ['tandarts', 'a dentist in a white coat looking into a patient’s mouth in a dental chair'], ['dierenarts', 'a vet with a stethoscope examining a dog on a table'],
    ['advocaat', 'a lawyer in a dark suit and tie holding a briefcase and a document'], ['postbode', 'a postman with a mail bag holding a parcel beside a letterbox'],
    ['kassier', 'a cashier behind a supermarket checkout with a till and groceries'], ['monteur', 'a mechanic in grey overalls with a spanner beside a car with its bonnet open'],
    ['kunstenaar', 'an artist in a beret holding a palette and brush beside a painting on an easel'], ['schoonmaker', 'a cleaner mopping the floor beside a yellow bucket'],
    ['uniform', 'a blue uniform jacket on a hanger with a matching cap'], ['salaris', 'an open pay envelope with two banknotes and a few coins'],
    ['werkgever', 'a woman in a dark suit pointing to her large office building'], ['werknemer', 'five employees standing together in front of their office building'],
  ] },
  { file: 'animals.svg', aspect: 1600 / 1500, entries: [
    ['dier', 'farm animals together behind a fence: a cow, a sheep, a pig and a duck'], ['boerderij', 'an old farmhouse with a red barn, a fence and a tree'],
    ['boer', 'a farmer in overalls and a flat cap holding a pitchfork'], ['paard', 'a brown horse standing side on'],
    ['koe', 'a black-and-white cow'], ['varken', 'a pink pig with a curly tail'],
    ['schaap', 'a white woolly sheep with a dark face'], ['geit', 'a goat with curved horns eating grass'],
    ['konijn', 'a white rabbit eating an orange carrot'], ['vogel', 'a small brown bird with a red breast sitting on a branch'],
    ['eend', 'a duck with a green head swimming on a river'], ['vlinder', 'a yellow butterfly above a small white flower'],
    ['kikker', 'a green frog sitting on a lily pad'], ['vos', 'a red fox with a white-tipped tail sitting in front of forest trees'],
    ['dierentuin', 'a zoo entrance gate with an elephant sign over the arch'], ['olifant', 'a large grey elephant with big ears and a long trunk'],
    ['leeuw', 'a lion with a brown mane lying in the sun'], ['aap', 'a brown monkey sitting and holding a yellow banana'],
    ['staart', 'a grey cat with its long curved tail highlighted'], ['poot', 'a dog with its four legs and paws highlighted, paw prints on the ground'],
  ] },
  { file: 'transport.png', aspect: 1377 / 1142, entries: [
    ['buslijn', 'bus route seven shown as a line joining four stops'], ['buschauffeur', 'a bus driver seated at the steering wheel'],
    ['fietspad', 'a red cycle path separated from the road'], ['rotonde', 'a circular road around a grassy central island'],
    ['stoep', 'Lotte walking on a raised pavement beside the road'], ['zebrapad', 'pedestrians crossing white zebra stripes between pavements'],
    ['verkeerslicht', 'a traffic light with its top red lamp lit'], ['spoor', 'two parallel railway rails on sleepers'],
    ['overstap', 'two trains linked by an arrow to show a transfer'], ['overstappen', 'Bram walking across a platform from one train to another'],
    ['kaartautomaat', 'a station ticket machine dispensing a ticket'], ['dienstregeling', 'a train timetable showing departure and arrival times'],
    ['vertrektijd', 'a train leaving the platform at eight o’clock'], ['aankomsttijd', 'a train arriving at the platform at nine o’clock'],
    ['reiziger', 'Lotte at a station with a suitcase and ticket'], ['controleur', 'an inspector scanning a passenger’s ticket inside a train'],
    ['spits', 'a long queue of cars and a crowded bus at rush hour'], ['storing', 'a stopped train with a maintenance worker and warning sign'],
    ['omleiding', 'a route turning onto an open side road before a barrier'], ['zitplaats', 'an empty upholstered passenger seat inside a train'],
  ] },
  { file: 'market.png', aspect: 1422 / 1106, entries: [
    ['komkommer', 'a cucumber with a cut round showing pale watery flesh'], ['ui', 'a brown onion and a half showing concentric rings'],
    ['knoflook', 'a garlic bulb and a peeled clove'], ['paprika', 'a red bell pepper and a cut half with seeds'],
    ['courgette', 'a courgette with a thick stalk and a cut round'], ['aubergine', 'a purple aubergine with cream-coloured flesh'],
    ['broccoli', 'a green broccoli head with a branching stalk'], ['bloemkool', 'a white cauliflower head with green leaves'],
    ['spinazie', 'a bunch of fresh spinach leaves'], ['champignon', 'a button mushroom and a cut half showing its gills'],
    ['druif', 'a bunch of purple grapes and one separate grape'], ['aardbei', 'red strawberries with green leafy tops'],
    ['citroen', 'a yellow lemon and a cut half'], ['kers', 'two red cherries with long stems'],
    ['perzik', 'a peach and a cut half showing its stone'], ['meloen', 'a netted cantaloupe melon with an orange-fleshed slice'],
    ['watermeloen', 'a green striped watermelon with a red slice'], ['pompoen', 'an orange pumpkin with a thick stem'],
    ['erwt', 'round green peas inside an open pod'], ['sperzieboon', 'long slender green bean pods with pale seeds'],
  ] },
  { file: 'hotel.png', aspect: 1312 / 1199, entries: [
    ['reservering', 'a hotel booking calendar beside a pen and room key'], ['bevestiging', 'a booking confirmation with a green check inside an envelope'],
    ['receptie', 'a hotel reception counter with a bell and room keys'], ['receptionist', 'a receptionist holding a room key'],
    ['eenpersoonskamer', 'a single hotel room with one narrow bed and one pillow'], ['tweepersoonskamer', 'a double hotel room with a wide bed and two pillows'],
    ['overnachting', 'Bram spending the night asleep in a hotel bed'], ['ontbijt', 'a breakfast tray with rolls, egg, jam and coffee at sunrise'],
    ['buffet', 'Lotte serving herself at a hotel buffet'], ['identiteitskaart', 'a generic identity card with a portrait and abstract details'],
    ['sleutelkaart', 'an electronic key card held against a hotel door reader'], ['shampoo', 'a shampoo bottle beside a person washing their hair'],
    ['haardroger', 'a handheld hairdryer with a power cord'], ['uitzicht', 'a scenic view through an open hotel window'],
    ['airconditioning', 'a wall-mounted air conditioner blowing cool air'], ['beddengoed', 'a folded stack of bed linen with a pillow'],
    ['dekbed', 'a thick quilted duvet on a bed'], ['laken', 'a single thin bedsheet held at its upper corners'],
    ['bad', 'a freestanding bathtub with taps'], ['kluis', 'a small open room safe containing a wallet and passport'],
  ] },
  { file: 'digital.png', aspect: 1402 / 1122, entries: [
    ['smartphone', 'a small touchscreen smartphone held in one hand'], ['tablet', 'a larger touchscreen tablet held with both hands'],
    ['website', 'a browser window showing a web page on a computer monitor'], ['wachtwoord', 'a masked password field beside a padlock'],
    ['bericht', 'conversational message bubbles on a phone'], ['bijlage', 'a document attached to an envelope with a paperclip'],
    ['oplader', 'a two-pin wall charger with a cable'], ['batterij', 'one cylindrical battery with its positive terminal visible'],
    ['bestand', 'a selected digital document in a computer folder'], ['printer', 'a desktop printer with a page in its output tray'],
    ['muis', 'a computer mouse with two buttons and a scroll wheel'], ['kabel', 'a computer cable with a connector at each end'],
    ['koptelefoon', 'a pair of over-ear headphones'], ['verbinding', 'a laptop connected to a router with a green check'],
    ['sturen', 'Bram sending a message from his laptop toward a recipient'], ['ontvangen', 'Lotte receiving a message coming into her laptop'],
    ['downloaden', 'a document moving downward from a cloud into a laptop'], ['opslaan', 'a document saved into a local folder with a green check'],
    ['inloggen', 'Lotte logging in with a password and a successful access check'], ['afdrukken', 'Bram printing a document from his computer'],
  ] },
  { file: 'outdoors.png', aspect: 1374 / 1145, entries: [
    ['bos', 'a dense forest of mature trees'], ['rivier', 'a winding river with two visible banks'],
    ['berg', 'a tall steep mountain with a rocky peak'], ['eiland', 'an island completely surrounded by water'],
    ['landschap', 'a pastoral landscape of fields, hills and a village'], ['pad', 'a narrow countryside footpath'],
    ['wandeling', 'Bram and Lotte taking a countryside walk'], ['picknick', 'a picnic on a blanket with food and a basket'],
    ['tent', 'one pitched camping tent'], ['camping', 'a campsite with tents and a camper van'],
    ['heuvel', 'a low rounded grassy hill'], ['rots', 'a large natural rock outcrop'],
    ['gras', 'a patch of grass growing from soil'], ['steen', 'a small stone in an open palm'],
    ['duin', 'a sandy coastal dune with beach grass'], ['kust', 'a coastline where land meets the sea'],
    ['haven', 'a sheltered harbour with moored boats'], ['boot', 'a small wooden rowing boat'],
    ['schip', 'a large seagoing cargo ship'], ['natuur', 'wild nature with a deer, birds, trees and a stream'],
  ] },
  { file: 'hobbies.png', aspect: 1145 / 1373, entries: [
    ['hobby', 'Lotte enjoying painting as a hobby at home'], ['voetbal', 'adults playing football beside a goal'],
    ['tennis', 'two adults playing tennis across a net'], ['basketbal', 'a player shooting a basketball toward a hoop'],
    ['wedstrijd', 'two teams playing a match with a referee and score'], ['team', 'four players in matching team shirts'],
    ['speler', 'one football player beside a ball'], ['bal', 'one round ball'],
    ['gitaar', 'an acoustic guitar'], ['piano', 'an upright piano with a stool'],
    ['viool', 'a violin and bow'], ['lied', 'Lotte singing a song with musical notes'],
    ['concert', 'musicians performing before an audience'], ['toneel', 'an empty theatre stage with open curtains'],
    ['theater', 'a theatre building with a theatrical-mask emblem'], ['bibliotheek', 'a library with shelves and a reading table'],
    ['schilderij', 'a framed landscape painting'], ['fotograferen', 'Bram photographing a house'],
    ['oefenen', 'Lotte practising at a piano with a music book'], ['winnen', 'a smiling winner holding a trophy on a podium'],
  ] },
  { file: 'restaurant.png', aspect: 1374 / 1145, entries: [
    ['menukaart', 'an open menu card with small food pictures'], ['ober', 'a waiter holding a serving tray'],
    ['bestelling', 'a waiter recording a customer’s food order'], ['gerecht', 'a prepared dish of fish, rice and vegetables'],
    ['voorgerecht', 'the starter highlighted before a main course and dessert'], ['hoofdgerecht', 'the main course highlighted between a starter and dessert'],
    ['nagerecht', 'the dessert highlighted after a starter and main course'], ['soep', 'a bowl of hot vegetable soup'],
    ['salade', 'a bowl of mixed salad'], ['saus', 'a sauceboat pouring sauce onto a plate'],
    ['olie', 'a bottle of cooking oil beside olives'], ['azijn', 'a bottle of vinegar with an apple and a sour-face symbol'],
    ['peper', 'a pepper mill and black peppercorns'], ['bestek', 'a dinner knife, fork and spoon'],
    ['servet', 'a folded dinner napkin beside a plate'], ['rekening', 'a restaurant bill totalling twelve plus eight equals twenty euros'],
    ['fooi', 'two coins left as a tip beside a paid bill'], ['bestellen', 'Lotte ordering a meal from a waiter'],
    ['proeven', 'Bram tasting a spoonful of soup'], ['honger', 'Bram feeling hungry and looking at food'],
  ] },
  { file: 'health.png', aspect: 1402 / 1122, entries: [
    ['afspraak', 'a calendar appointment beside a clock and stethoscope'], ['praktijk', 'a small doctor’s practice building'],
    ['wachtkamer', 'patients sitting in a waiting room'], ['balie', 'a reception counter with a receptionist and visitor'],
    ['verpleegkundige', 'a nurse in scrubs holding a clipboard'], ['verkoudheid', 'Lotte resting with a cold, a blanket and tissues'],
    ['recept', 'a prescription slip at a pharmacy'], ['pil', 'one round scored pill'],
    ['zalf', 'a tube of ointment beside a dab of cream'], ['pleister', 'an adhesive plaster with a central pad'],
    ['verband', 'a roll of bandage with a strip unrolled'], ['wond', 'a small scratch on a forearm'],
    ['knie', 'a bent leg with the knee joint highlighted'], ['schouder', 'a shoulder joint highlighted on an upper torso'],
    ['enkel', 'an ankle joint highlighted above a foot'], ['thermometer', 'a digital medical thermometer'],
    ['hoesten', 'Bram coughing into his elbow'], ['niezen', 'Lotte sneezing into a tissue'],
    ['ademen', 'a person breathing with an arrow toward the nose and lungs'], ['verzetten', 'an appointment moved from one calendar date to another'],
  ] },
  { file: 'housing.png', aspect: 1312 / 1199, entries: [
    ['woning', 'a small brick dwelling'], ['appartement', 'one self-contained apartment with rooms visible inside a larger building'],
    ['contract', 'a signed rental document with a pen and house key'], ['waarborg', 'money kept securely beside a house key as a rental deposit'],
    ['kelder', 'a cellar below ground in a house cross-section'], ['zolder', 'an attic beneath a sloping roof'],
    ['gang', 'an interior hallway with doors on both sides'], ['brievenbus', 'a wall-mounted letterbox with a letter in its slot'],
    ['deurbel', 'a finger pressing a doorbell beside the front door'], ['stopcontact', 'a European wall electrical socket'],
    ['verwarming', 'a heating radiator with warmth rising above it'], ['lift', 'an open elevator cabin'],
    ['verdieping', 'one complete storey highlighted in a three-storey building'], ['schuur', 'a small wooden garden shed'],
    ['garage', 'an open garage with a car inside'], ['hek', 'a closed garden gate with visible hinges and latch'],
    ['terras', 'a paved ground-level terrace beside a house'], ['voordeur', 'a front entrance door with a knocker and doorstep'],
    ['plafond', 'a highlighted ceiling above a hanging lamp'], ['dakraam', 'a window set into a sloping tiled roof'],
  ] },
  { file: 'social.png', aspect: 1374 / 1145, entries: [
    ['gezin', 'two parents with their two children'], ['baby', 'a baby asleep in a bassinet'],
    ['oom', 'a family tree highlighting the brother of a child’s mother'], ['tante', 'a family tree highlighting the sister of a child’s mother'],
    ['neef', 'a family tree highlighting a male cousin in a separate branch with shared grandparents'],
    ['nicht', 'a family tree highlighting a female cousin in a separate branch with shared grandparents'],
    ['oma', 'a grandmother sitting beside her grandchild'], ['opa', 'a grandfather sitting beside his grandchild'],
    ['cadeau', 'a wrapped gift with a ribbon bow'], ['verjaardag', 'a child celebrating a birthday with candles on a cake'],
    ['feest', 'several adults celebrating under party bunting'], ['gast', 'a guest arriving with flowers at a host’s open door'],
    ['taart', 'a decorated round cake'], ['kaars', 'one lit candle in a holder'],
    ['ballon', 'one inflated balloon on a string'], ['slinger', 'a strand of triangular party bunting'],
    ['boeket', 'a tied bouquet of cut flowers'], ['uitnodiging', 'an invitation card with a balloon picture emerging from an envelope'],
    ['bruiloft', 'a wedding couple exchanging rings before guests'], ['bruid', 'a bride in a white wedding dress holding a bouquet'],
  ] },
  { file: 'chores.png', aspect: 1122 / 1402, entries: [
    ['stofzuiger', 'a vacuum cleaner with a connected hose and floor nozzle'], ['bezem', 'a broom with a wooden handle'],
    ['emmer', 'an empty bucket with a carrying handle'], ['spons', 'a porous rectangular cleaning sponge'],
    ['doek', 'a folded cleaning cloth'], ['vaatwasser', 'an open dishwasher with plates inside'],
    ['afwas', 'dirty dishes waiting beside a sink'], ['wasgoed', 'a basket of laundry'],
    ['strijkijzer', 'an electric iron resting upright'], ['wasrek', 'a folding drying rack with clothes hanging on it'],
    ['wasknijper', 'a wooden spring clothes peg'], ['vuilniszak', 'a tied rubbish bag'],
    ['schoonmaken', 'Lotte wiping a tabletop with a cloth'], ['opruimen', 'Bram tidying books into a bookcase'],
    ['afwassen', 'Bram washing a plate in soapy water'], ['afdrogen', 'Lotte drying a clean plate with a tea towel'],
    ['stofzuigen', 'Bram vacuuming the floor'], ['vegen', 'Lotte sweeping crumbs towards a dustpan'],
    ['dweilen', 'Bram mopping a tiled floor beside a bucket'], ['strijken', 'Lotte ironing a shirt on an ironing board'],
  ] },
  { file: 'choices.png', aspect: 1312 / 1199, entries: [
    ['maat', 'a sweater with a measuring tape and the clothing size M circled'], ['mouw', 'a highlighted shirt sleeve with an arrow pointing to it'],
    ['kraag', 'an arrow pointing to a folded shirt collar'], ['knoop', 'a round sewing button with four holes'],
    ['rits', 'a zip with two rows of teeth and a slider'], ['zak', 'an arrow pointing to a shirt pocket'],
    ['stof', 'a roll of woven fabric with an unfolded end'], ['katoen', 'cotton bolls beside folded cotton cloth'],
    ['wol', 'a ball of wool beside a knitted piece'], ['patroon', 'a repeating geometric pattern on a fabric swatch'],
    ['streep', 'one broad stripe across a fabric swatch'], ['stip', 'one large round dot on a fabric swatch'],
    ['etiket', 'a clothing care label sewn inside a neckline'], ['paskamer', 'a fitting room with a curtain, mirror and stool'],
    ['oorbel', 'a hoop earring hanging from an earlobe'], ['ketting', 'a necklace on a display bust'],
    ['ring', 'a finger ring with a small green stone'], ['pyjama', 'a matching striped pyjama top and trousers'],
    ['sandaal', 'an open-toed sandal with straps'], ['passen', 'Lotte trying on a jacket in front of a shop mirror'],
  ] },
  { file: 'directions.png', entries: [
    ['links', 'an arrow pointing left'], ['rechts', 'an arrow pointing right'],
    ['rechtdoor', 'a road continuing straight ahead with a forward arrow'],
    ['naast', 'a red ball beside a green box'], ['achter', 'a red ball partly hidden behind a green box'],
    ['voor', 'a red ball in front of a green box'], ['onder', 'a red ball under a table'],
    ['boven', 'a red ball above a green box'], ['tussen', 'a red ball between two green boxes'],
    ['bij', 'a man waiting by an entrance'], ['tegenover', 'a bakery and school on opposite sides of a road'],
    ['dichtbij', 'a woman close to a house'], ['ver', 'a man far from a house at the end of a long path'],
    ['hoek', 'a shop on a street corner'], ['brug', 'a bridge over a river'],
    ['kruispunt', 'two roads meeting at a crossroads'], ['verkeer', 'cars and a bus on a road'],
    ['stoplicht', 'a traffic light showing red'], ['ingang', 'a man going into a building through an entrance'],
    ['uitgang', 'a woman leaving a building through an exit'],
  ] },
  { file: 'routines.png', entries: [
    ['staan', 'a man standing upright'], ['nemen', 'a man boarding a bus'],
    ['geven', 'a woman giving a book to a man'], ['doen', 'a man doing a task at his desk'],
    ['maken', 'a man making a wooden chair'], ['gebruiken', 'a woman using a phone'],
    ['wassen', 'a man washing his hands with soap and water'], ['poetsen', 'a woman brushing her teeth'],
    ['douchen', 'a person showering behind a frosted screen'], ['sluiten', 'a woman closing an open window'],
    ['beginnen', 'a man beginning a walk at the start of a path'], ['stoppen', 'a bus stopped at a red traffic light'],
    ['dansen', 'two adults dancing together'], ['zingen', 'a woman singing with musical notes'],
    ['lachen', 'a man laughing'], ['huilen', 'a woman crying with a tear on her cheek'],
    ['bellen', 'a man making a phone call'], ['ontmoeten', 'two adults meeting and shaking hands'],
    ['bezoeken', 'a woman visiting a museum'], ['sporten', 'a man exercising with weights'],
  ] },
  { file: 'school.png', entries: [
    ['beroep', 'three people in different occupations'], ['baan', 'a man working beside an employment document'],
    ['kantoor', 'an office with a desk and chair'], ['bedrijf', 'a company building'],
    ['collega', 'two colleagues at neighbouring desks'], ['leraar', 'a teacher pointing at a board'],
    ['leerling', 'a school pupil writing at a desk'], ['student', 'an adult student studying a book'],
    ['les', 'a teacher giving a lesson to a class'], ['cursus', 'course books beside a calendar of repeated lessons'],
    ['huiswerk', 'schoolwork on a table at home'], ['oefening', 'a workbook exercise with a pencil'],
    ['toets', 'a test paper with check boxes'], ['examen', 'students taking an exam at separate desks'],
    ['computer', 'a desktop computer with monitor, keyboard and mouse'], ['laptop', 'an open laptop'],
    ['scherm', 'a computer monitor'], ['toetsenbord', 'a computer keyboard'],
    ['schrift', 'an open lined notebook'], ['agenda', 'an open day planner'],
  ] },
  { file: 'travel.png', entries: [
    ['reis', 'a route on a map beside a suitcase'], ['reizen', 'a man travelling on a train'],
    ['vakantie', 'a woman relaxing on holiday in a deckchair'], ['zee', 'the sea with waves and a distant horizon'],
    ['strand', 'a sandy beach with shells beside the sea'], ['vliegtuig', 'an airplane on the ground'],
    ['vliegen', 'an airplane flying above clouds'], ['vliegveld', 'an airport terminal and control tower'],
    ['hotel', 'a hotel with a bed pictogram'], ['paspoort', 'a passport booklet with a globe emblem'],
    ['ticket', 'a train ticket with a train pictogram'], ['koffer', 'a wheeled suitcase'],
    ['bagage', 'a suitcase, travel bag and backpack'], ['perron', 'a station platform beside a train'],
    ['vertrek', 'a train departing away from a station'], ['aankomst', 'a train arriving toward a station'],
    ['vertraging', 'a waiting passenger beside a clock and a ten-minute delay indicator'],
    ['reserveren', 'a woman reserving a room at a hotel desk'], ['huren', 'a man renting a bicycle at a shop'],
    ['toerist', 'a tourist photographing a town square'],
  ] },
  { file: 'descriptions.png', entries: [
    ['lang', 'a long coat with a length arrow'], ['kort', 'a short coat with a length arrow'],
    ['snel', 'a rabbit running fast'], ['langzaam', 'a snail moving slowly'],
    ['makkelijk', 'an easy puzzle with four large pieces'], ['moeilijk', 'a person puzzling over many small puzzle pieces'],
    ['hoog', 'a tall tree with a height arrow'], ['laag', 'a low stool with a short height arrow'],
    ['sterk', 'a man easily carrying a large box'], ['zwak', 'the same man struggling to lift a box of the same size'],
    ['dik', 'a thick book with many pages'], ['dun', 'a thin book with few pages'],
    ['breed', 'a wide path with a width arrow'], ['smal', 'a narrow path with a width arrow'],
    ['zwaar', 'a person straining to lift a heavy suitcase'], ['boos', 'an angry man with a frown'],
    ['bang', 'a frightened child beside a friendly dog'], ['lekker', 'a woman enjoying the taste of cheese'],
    ['stil', 'a quiet room with one person reading'], ['druk', 'a busy town street with many people'],
  ] },
  { file: 'shopping.png', entries: [
    ['geld', 'a wallet with a banknote and coins'], ['prijs', 'a price tag showing ten euros'],
    ['euro', 'a simplified one-euro coin marked 1 €'], ['cent', 'a copper coin marked one cent'],
    ['kosten', 'a sweater with a twelve-euro price tag'], ['betalen', 'a customer paying by card at a terminal'],
    ['kassa', 'a cash register at a checkout'], ['bon', 'a receipt with item lines and a total'],
    ['winkelmandje', 'a plastic shopping basket'], ['contant', 'a hand paying with a banknote and coins'],
    ['kaart', 'a payment card with a chip'], ['duur', 'a coat with a hundred-euro price tag'],
    ['goedkoop', 'a coat with a five-euro price tag'], ['korting', 'a price tag reduced from ten to eight euros'],
    ['open', 'a shop with an open entrance door'], ['gesloten', 'a shop with a closed shutter'],
    ['nodig', 'a person with paper and an empty pen pot reaching for a pen'],
    ['kiezen', 'a person choosing the red sweater from two sweaters'],
    ['genoeg', 'two one-euro coins beside bread costing two euros and a check mark'],
    ['klant', 'a customer with groceries at a checkout'],
  ] },
  { file: 'numbers.png', entries: [
    ['dertien', 'a card showing 13'], ['veertien', 'a card showing 14'], ['vijftien', 'a card showing 15'],
    ['zestien', 'a card showing 16'], ['zeventien', 'a card showing 17'], ['achttien', 'a card showing 18'],
    ['negentien', 'a card showing 19'], ['twintig', 'a card showing 20'], ['dertig', 'a card showing 30'],
    ['veertig', 'a card showing 40'], ['vijftig', 'a card showing 50'], ['zestig', 'a card showing 60'],
    ['zeventig', 'a card showing 70'], ['tachtig', 'a card showing 80'], ['negentig', 'a card showing 90'],
    ['honderd', 'a card showing 100'], ['duizend', 'a card showing 1000'], ['nul', 'a card showing zero'],
    ['helft', 'one of two equal halves of a circle highlighted'], ['tellen', 'a man counting five coins'],
  ] },
  { file: 'calendar.png', entries: [
    ['maand', 'a whole calendar month highlighted'], ['datum', 'one date square highlighted on a calendar'],
    ['kalender', 'a wall calendar with several pages'], ['ochtend', 'a rising sun outside a breakfast window'],
    ['middag', 'a high afternoon sun outside a window'], ['avond', 'a setting sun outside a window'],
    ['nacht', 'the moon and stars outside a window at night'], ['minuut', 'a stopwatch marked one minute'],
    ['januari', 'a calendar card for month 01'], ['februari', 'a calendar card for month 02'],
    ['maart', 'a calendar card for month 03'], ['april', 'a calendar card for month 04'],
    ['mei', 'a calendar card for month 05'], ['juni', 'a calendar card for month 06'],
    ['juli', 'a calendar card for month 07'], ['augustus', 'a calendar card for month 08'],
    ['september', 'a calendar card for month 09'], ['oktober', 'a calendar card for month 10'],
    ['november', 'a calendar card for month 11'], ['december', 'a calendar card for month 12'],
  ] },
  { file: 'body.png', entries: [
    ['hoofd', 'a complete human head and neck'], ['buik', 'the abdomen highlighted on a front-view torso'],
    ['rug', 'the back highlighted on a person viewed from behind'], ['hand', 'an open hand with four fingers and a thumb'],
    ['arm', 'an arm from shoulder to wrist and hand'], ['been', 'a leg from hip to ankle'],
    ['voet', 'a bare foot with five toes'], ['oog', 'one eye with a green iris'],
    ['oor', 'one human ear'], ['neus', 'a nose highlighted on a profile of a head'],
    ['mond', 'a smiling mouth'], ['keel', 'the front of the throat highlighted below the chin'],
    ['tand', 'one white tooth'], ['gezicht', 'the facial oval highlighted, with a pointer on the cheek'],
    ['lichaam', 'a whole clothed person from head to feet'], ['pijn', 'a person holding a painful lower back'],
    ['dokter', 'a doctor in a white coat with a stethoscope'], ['apotheek', 'a pharmacy with a green cross'],
    ['medicijn', 'a medicine box and a blister strip of tablets'], ['gezond', 'a cheerful upright person beside a green check mark'],
  ] },
  { file: 'weather.png', aspect: 1275 / 1234, entries: [
    ['weer', 'a window framing sun, cloud and rain'], ['zon', 'a yellow sun with rays'],
    ['regen', 'a cloud dropping rain into a puddle'], ['wind', 'wind bending a tree and blowing leaves'],
    ['wolk', 'one white cloud'], ['sneeuw', 'snowflakes falling onto snowy ground'],
    ['mist', 'a house and tree partly obscured by fog'], ['storm', 'a dark storm cloud, lightning, rain and bent tree'],
    ['warm', 'a person wiping his forehead in warm sunshine'], ['koud', 'a person shivering in a scarf'],
    ['droog', 'a dry coat hanging on a hook'], ['nat', 'a wet coat dripping into a puddle'],
    ['lente', 'a tree with spring blossom and new leaves'], ['zomer', 'a fully green tree in summer sunshine'],
    ['herfst', 'a tree with autumn leaves falling'], ['winter', 'a bare tree covered in winter snow'],
    ['seizoen', 'four segments showing spring, summer, autumn and winter'],
    ['buiten', 'a woman and child playing outside a house'], ['binnen', 'a person reading inside a room'],
    ['regenen', 'rain falling on a street where a woman walks with an umbrella'],
  ] },
  { file: 'personal.png', entries: [
    ['adres', 'an envelope and a house with a location pin'], ['land', 'a stylised country map with a Belgian flag'],
    ['taal', 'two people speaking, with Hallo and Hello in speech bubbles'], ['nummer', 'a finger pressing number five on a keypad'],
    ['postcode', 'the postcode 3000 highlighted on an envelope'], ['woonplaats', 'a town with a location pin and Leuven sign'],
    ['nationaliteit', 'a generic passport booklet beside a Belgian flag'], ['leeftijd', 'a child with a birthday cake and five candles'],
    ['voornaam', 'a form with the first name Lotte highlighted'], ['achternaam', 'a form with the surname Claes highlighted'],
    ['hallo', 'a smiling adult waving hello'], ['goedemorgen', 'two adults greeting in the morning beside a sunrise window'],
    ['goedemiddag', 'two adults greeting in bright afternoon daylight'], ['goedenavond', 'two adults greeting at dusk'],
    ['welkom', 'a host inviting a guest through an open doorway'], ['bedanken', 'an adult expressing thanks while receiving a cup'],
    ['alsjeblieft', 'one friend politely asking another for tea at home'], ['alstublieft', 'a customer politely asking a café worker for coffee'],
    ['sorry', 'an adult apologising for a small accidental spill'], ['pardon', 'a traveller politely asking a passerby for help'],
  ] },
  { file: 'household.png', entries: [
    ['bord', 'a flat dinner plate'], ['beker', 'a red handleless drinking beaker'], ['kop', 'a teacup with handle and saucer'],
    ['mes', 'a rounded dinner knife'], ['vork', 'a four-tined fork'], ['lepel', 'a spoon'],
    ['pan', 'a cooking pan with a handle'], ['kom', 'a deep empty bowl'], ['koelkast', 'an open fridge with shelves'],
    ['oven', 'an oven with internal racks and no hob'], ['fornuis', 'a cooker with four burners above an oven'],
    ['handdoek', 'a folded green towel'], ['zeep', 'a bar of soap in a dish'], ['wasmachine', 'a front-loading washing machine'],
    ['vuilnisbak', 'a rubbish bin with a lid'], ['doos', 'an open empty cardboard box'], ['pakket', 'a parcel sealed with tape'],
    ['mand', 'a woven basket with a handle'], ['kussen', 'a soft square cushion'], ['deken', 'a folded blue blanket'],
  ] },
  { file: 'places.png', entries: [
    ['bakker', 'a bakery with bread in its window'], ['supermarkt', 'a supermarket entrance with groceries and trolley'],
    ['slager', 'a butcher shop with meat behind glass'], ['markt', 'an outdoor produce market'],
    ['restaurant', 'a restaurant with set dining tables and a waiter'], ['café', 'a café with coffee machine and cups'],
    ['winkelcentrum', 'an indoor shopping centre with several shops'], ['bushalte', 'a bus stop shelter with a bus pictogram'],
    ['bus', 'a city bus on a road'], ['tram', 'a tram on street rails with overhead wires'],
    ['metro', 'a metro train at an underground platform'], ['plein', 'an open paved town square'],
    ['museum', 'a museum gallery with paintings and a sculpture'], ['zwembad', 'a swimming pool with lane ropes'],
    ['sporthal', 'a sports hall with a basketball court'], ['ziekenhuis', 'a hospital entrance with medical cross and ambulance'],
    ['postkantoor', 'a post office with envelope sign and letterbox'], ['politiebureau', 'a police station with a police car'],
    ['stadhuis', 'a Flemish town hall with a clock tower and Belgian flag'], ['bioscoop', 'a cinema with rows of seats and a movie screen'],
  ] },
  { file: 'actions.png', entries: [
    ['fietsen', 'a woman riding a bicycle'], ['luisteren', 'an adult listening to a radio'],
    ['kijken', 'two adults looking at a passing train'], ['zoeken', 'a woman searching inside a bag'],
    ['openen', 'a woman opening a door'], ['dragen', 'a man wearing a white button-up shirt'],
    ['halen', 'an adult getting a bottle of milk from a fridge'], ['pakken', 'a man picking up a newspaper'],
    ['tekenen', 'a child drawing a house on paper'], ['wandelen', 'two adults walking in a park'],
    ['muziek', 'a guitar with musical notes'], ['radio', 'a portable radio with antenna and speaker'],
    ['televisie', 'a television on a stand'], ['krant', 'a folded newspaper with columns'],
    ['brief', 'a letter emerging from an envelope'], ['pen', 'a blue ballpoint pen'],
    ['potlood', 'a yellow wooden pencil'], ['papier', 'a plain white sheet of paper'],
    ['fles', 'a clear water bottle with a cap'], ['glas', 'a drinking glass filled with water'],
  ] },
  { file: 'colours.png', entries: [
    ['rood', 'a red T-shirt'], ['blauw', 'a blue T-shirt'], ['groen', 'a green T-shirt'], ['geel', 'a yellow T-shirt'],
    ['zwart', 'a black T-shirt'], ['wit', 'a white T-shirt'], ['bruin', 'a brown T-shirt'], ['grijs', 'a grey T-shirt'],
    ['oranje', 'an orange T-shirt'], ['roze', 'a pink T-shirt'], ['paars', 'a purple T-shirt'],
    ['licht', 'a bright room with sunlight through the window'], ['donker', 'a dark room with a closed curtain'],
    ['schoon', 'a clean white T-shirt'], ['vuil', 'a white T-shirt covered in mud stains'],
    ['leeg', 'an empty open basket'], ['vol', 'a basket full of apples'],
    ['zacht', 'a hand pressing a dent into a soft cushion'], ['hard', 'a hand pressing on a firm wooden stool'],
    ['kapot', 'a phone with a cracked screen'],
  ] },
  { file: 'food.png', entries: [
    ['kopen', 'a customer paying a coin for a loaf of bread'], ['melk', 'a bottle of white milk'],
    ['sap', 'a jug of orange juice'], ['bier', 'a mug of golden beer with foam'],
    ['wijn', 'a stemmed glass of red wine'], ['suiker', 'a bowl of sugar with sugar cubes'],
    ['zout', 'a salt shaker with a perforated lid'], ['boter', 'a block of butter on a dish'],
    ['rijst', 'a bowl of white rice'], ['pasta', 'a bowl of spiral pasta'],
    ['kip', 'a roast chicken on a plate'], ['vlees', 'a red beef steak'],
    ['vis', 'one whole fish on a plate'], ['ei', 'one brown egg'], ['aardappel', 'one potato'], ['tomaat', 'one red tomato'],
    ['wortel', 'one orange carrot'], ['banaan', 'one yellow banana'], ['peer', 'one green pear'], ['sinaasappel', 'one orange fruit'],
  ] },
  { file: 'home.png', entries: [
    ['tafel', 'a wooden dining table'], ['stoel', 'one wooden chair'],
    ['kamer', 'an almost empty room'], ['keuken', 'a kitchen with sink, counter and cooker'],
    ['tuin', 'a garden with lawn and flowerbeds'], ['bed', 'one bed with a pillow and blanket'],
    ['kast', 'a wooden cupboard with two doors'], ['lamp', 'a table lamp'],
    ['muur', 'a brick wall'], ['vloer', 'a wooden floor'], ['dak', 'a red tiled roof'], ['trap', 'a staircase'],
    ['badkamer', 'a bathroom with a bath and washbasin'], ['slaapkamer', 'a bedroom with bed and bedside table'],
    ['woonkamer', 'a living room with sofa and armchair'], ['spiegel', 'a rectangular wall mirror'],
    ['douche', 'a shower with showerhead and tray'], ['toilet', 'a toilet with cistern and seat'],
    ['balkon', 'an upstairs balcony with a railing'], ['gordijn', 'a curtain hanging beside a window'],
  ] },
  { file: 'clothing.png', entries: [
    ['broek', 'one pair of blue trousers'], ['rok', 'a green skirt'], ['shirt', 'a red short-sleeved T-shirt'],
    ['trui', 'a blue pullover sweater'], ['hemd', 'a white collared button-up shirt'], ['jurk', 'a purple dress'],
    ['schoen', 'one brown lace-up shoe'], ['sok', 'one white sock'], ['laars', 'one tall brown boot'],
    ['pet', 'a yellow baseball cap'], ['hoed', 'a grey brimmed hat'], ['sjaal', 'a purple scarf'],
    ['handschoen', 'one five-finger glove'], ['riem', 'a brown belt with buckle'],
    ['bril', 'a pair of eyeglasses with clear lenses'], ['horloge', 'an analogue wristwatch'],
    ['paraplu', 'an open orange umbrella'], ['rugzak', 'a green backpack'], ['portemonnee', 'a brown folding wallet'],
    ['vest', 'a green knitted cardigan with a buttoned front'],
  ] },
];

export const practiceArt = Object.fromEntries(sheets.flatMap(sheet => sheet.entries.map(([wordId, alt], index) => [
  'practice-' + wordId, { file: '/images/practice/' + sheet.file, alt, aspect: sheet.aspect || 1, columns: 4, rows: 5, column: index % 4, row: Math.floor(index / 4) },
])));
export const wordIllustration = wordId => practiceArt['practice-' + wordId] ? 'practice-' + wordId : undefined;

// Row boundaries are reviewed against each sheet, whose artwork is not at exact fifths.
const rowBounds = {
  'transport.png': [[0.6, 18.3], [20.2, 18.3], [39.8, 18.4], [59.5, 18.3], [79.1, 19.6]],
  'market.png': [[1.1, 18.9], [21.4, 18.9], [41.3, 17.5], [60, 17.5], [78.8, 19.9]],
  'hotel.png': [[1.1, 19.7], [21.8, 18.6], [41.4, 18.6], [61, 17], [79.1, 19.6]],
  'digital.png': [[0.9, 18.8], [20.5, 18.7], [40, 18.7], [59.4, 18], [78.2, 20.6]],
  'outdoors.png': [[1.1, 18.9], [21.2, 19], [41.3, 17.5], [59.9, 17.4], [78.4, 19.9]],
  'hobbies.png': [[0.8, 19.8], [21.4, 19.2], [41.5, 18.4], [60.7, 17.2], [78.7, 20.5]],
  'restaurant.png': [[1.1, 20.1], [22.2, 18.8], [41.9, 18.4], [61, 17], [78.9, 19.6]],
  'health.png': [[1.1, 19.8], [21.9, 19.1], [42.1, 16.9], [60, 16.9], [78, 20.6]],
  'housing.png': [[1.2, 18.6], [20.9, 18.5], [40.7, 18.3], [60.2, 18.5], [79.9, 18.9]],
  'social.png': [[1.1, 19.5], [21.6, 20.5], [43.1, 19], [63.1, 16.6], [80.6, 18.1]],
  'chores.png': [[1.1, 18.4], [20.6, 17.4], [39, 17.3], [57.4, 18.4], [76.9, 20.8]],
  'choices.png': [[1.2, 17.7], [20.1, 17.7], [39, 17.7], [58.2, 17.4], [76.9, 21]],
  'directions.png': [[1, 18.2], [20.2, 17.1], [38.3, 18.2], [57.6, 18.8], [77.6, 21.1]],
  'routines.png': [[1, 19.4], [21.5, 19.1], [41.7, 18.2], [61, 17.7], [79.9, 18.8]],
  'school.png': [[1, 19.9], [22.3, 19.4], [43.2, 18.2], [62.9, 17.6], [82, 15.7]],
  'travel.png': [[0.9, 19.7], [21.7, 17.7], [40.6, 19.3], [61.1, 16.2], [78.5, 20.2]],
  'descriptions.png': [[1, 18.4], [20.7, 18.4], [40.3, 18.3], [59.9, 16.9], [78.2, 20.6]],
  'shopping.png': [[0, 19.4], [19.4, 19.3], [38.7, 19], [57.7, 19.5], [77.2, 22.8]],
  'numbers.png': [[0, 20], [20, 19.5], [39.5, 19.5], [59, 17.3], [76.3, 23.7]],
  'calendar.png': [[1, 18.75], [20.85, 18.15], [40.4, 16.9], [58.5, 17.2], [77, 21.7]],
  'body.png': [[0, 19.6], [19.6, 18.2], [37.8, 18.2], [56, 20.5], [76.5, 23.5]],
  'weather.png': [[1.3, 18.6], [20.85, 18.8], [40.6, 18.15], [59.65, 18.25], [78.85, 19.5]],
  'home.png': [[0, 21], [21, 19], [40, 19], [59, 18.7], [77.7, 22.3]],
  'food.png': [[0, 22.3], [22.3, 19.1], [41.4, 18.1], [59.5, 16.3], [75.8, 24.2]],
  'actions.png': [[0, 22.2], [22.2, 21.3], [43.5, 20.5], [64, 16.4], [80.4, 19.6]],
  'clothing.png': [[0, 20.6], [20.6, 20], [40.6, 19.4], [60, 18.2], [78.2, 21.8]],
  'colours.png': [[0, 19.5], [19.5, 19.5], [39, 19.6], [58.6, 18.4], [77, 23]],
  'places.png': [[0, 22.4], [22.4, 20.6], [43, 19], [62, 18.5], [80.5, 19.5]],
  'household.png': [[0, 20], [20, 16.5], [36.5, 20.5], [57, 19.4], [76.4, 23.6]],
  'personal.png': [[0, 22], [22, 20], [42, 17.4], [59.4, 17.8], [77.2, 22.8]],
};
const columnBounds = {
  'transport.png': [[1.1, 23.3], [25.6, 23.8], [50.6, 23.7], [75.5, 23.4]],
  'market.png': [[1.1, 23.6], [25.9, 23.5], [50.6, 23.6], [75.5, 23.5]],
  'hotel.png': [[1.1, 23.5], [25.7, 23.6], [50.6, 23.6], [75.4, 23.5]],
  'digital.png': [[0.7, 24], [25.5, 24.1], [50.4, 24.1], [75.3, 24]],
  'outdoors.png': [[1.1, 23.6], [26, 23.4], [50.6, 23.5], [75.3, 23.6]],
  'hobbies.png': [[1.1, 23.5], [25.6, 23.9], [50.5, 23.9], [75.5, 23.5]],
  'restaurant.png': [[1.1, 23.7], [25.8, 23.7], [50.5, 23.7], [75.3, 23.6]],
  'health.png': [[1.1, 23.6], [25.5, 23.9], [50.6, 23.6], [75.4, 23.5]],
  'housing.png': [[1.6, 23.1], [26, 23], [50.3, 24], [75.6, 23.2]],
  'social.png': [[1.1, 23.7], [25.8, 23.7], [50.5, 23.7], [75.3, 23.6]],
  'chores.png': [[1.4, 22.6], [25.4, 23.9], [50.7, 24], [76.2, 22.4]],
  'choices.png': [[1.1, 23.6], [25.9, 23.6], [50.5, 23.6], [75.3, 23.6]],
  'directions.png': [[1, 23.5], [25.65, 23.65], [50.5, 23.85], [75.5, 23.5]],
  'routines.png': [[1.1, 23.55], [25.8, 23.65], [50.6, 23.65], [75.4, 23.6]],
  'school.png': [[1.3, 23.5], [26.4, 22.6], [50.6, 23.05], [75.1, 23.7]],
  'travel.png': [[1.3, 23], [25.7, 23.6], [50.7, 23.7], [75.8, 23]],
  'descriptions.png': [[1.1, 23.5], [25.8, 23.6], [50.6, 23.6], [75.4, 23.5]],
  'weather.png': [[1.25, 23.55], [25.85, 23.6], [50.6, 23.55], [75.25, 23.4]],
  'calendar.png': [[1.1, 23.6], [25.8, 23.7], [50.55, 23.75], [75.35, 23.65]],
};
for (const art of Object.values(practiceArt)) {
  const file = art.file.split('/').at(-1);
  const rows = rowBounds[file];
  if (rows) {
    const [top, height] = rows[art.row];
    const [left, width] = columnBounds[file]?.[art.column] || [art.column * 25, 25];
    art.bounds = [left, top, width, height];
  }
}
// Keep wider objects intact without letting them appear on neighbouring cards.
Object.assign(practiceArt['practice-vis'], { bounds: [0, 59.5, 28.5, 16.3] });
Object.assign(practiceArt['practice-ei'], { bounds: [30, 59.5, 20, 16.3] });
Object.assign(practiceArt['practice-televisie'], { bounds: [0, 64, 26, 16.4] });
Object.assign(practiceArt['practice-krant'], { bounds: [27, 64, 23, 16.4] });
Object.assign(practiceArt['practice-paars'], { bounds: [51, 39, 22.5, 19.6] });
Object.assign(practiceArt['practice-licht'], { bounds: [74, 39, 26, 19.6] });
Object.assign(practiceArt['practice-donker'], { bounds: [0, 58.6, 26, 18.4] });
Object.assign(practiceArt['practice-schoon'], { bounds: [27, 58.6, 23, 18.4] });
Object.assign(practiceArt['practice-bord'], { bounds: [0, 0, 26, 20] });
Object.assign(practiceArt['practice-beker'], { bounds: [27, 0, 23, 20] });
Object.assign(practiceArt['practice-goedemiddag'], { bounds: [0, 59.4, 26, 17.8] });
Object.assign(practiceArt['practice-goedenavond'], { bounds: [26.5, 59.4, 23.5, 17.8] });
Object.assign(practiceArt['practice-alsjeblieft'], { bounds: [0, 77.2, 26, 22.8] });
Object.assign(practiceArt['practice-alstublieft'], { bounds: [26.5, 77.2, 23.5, 22.8] });
Object.assign(practiceArt['practice-mond'], { bounds: [50, 37.8, 25, 17.5] });
Object.assign(practiceArt['practice-betalen'], { bounds: [25, 19.4, 26, 19.3] });
Object.assign(practiceArt['practice-helft'], { bounds: [50, 76.3, 23, 23.7] });
